ministryofjustice/laa-apply-for-legal-aid

Gemfile
Gemfile.lock
app/controllers/application_controller.rb
app/controllers/v1/applications_controller.rb
app/models/legal_aid_application.rb
app/serializers/applicant_serializer.rb
app/serializers/legal_aid_application_serializer.rb
config/routes.rb
spec/requests/legalaid_application_spec.rb

The Citizen application needs to be able to retrieve application and
applicant data from the database based on application reference.
This adds an endpoint to do this: /v1/applications/:id
* Add show action to applications resource in routes.rb.
* Define show method in ApplicationsController.rb.
* Add test to requests/legal_aid_application_spec.rb.
* Install webmock and faker gems to support testing.

Add endpoint to return an application

---

docs/pull_request_template.md

At our dev meeting today we agreed:
- what we think the person raising a pull request should check before asking
someone to spend time reviewing it.
- that there should be some basic description of what the PR does
- that we should link to the story in JIRA
This is a PR template that sets out the structure we expect; a description,
link to the story and a task list to help the person raising the PR to remember
the things to check before requesting review.
This is identical to the template that was introduced in ministryofjustice/laa-apply-for-legal-aid-citizen-frontend#25 so the content has already been reviewed. But if you want, you can review the content again.

Add a PR template including task list

---

app/controllers/v1/applicants_controller.rb
app/models/applicant.rb
app/serializers/applicant_serializer.rb
app/services/save_applicant.rb
db/migrate/20180913101947_rename_name_to_first_name.rb
db/migrate/20180913103146_add_last_name_to_applicants.rb
db/schema.rb
spec/models/applicant_spec.rb
spec/requests/create_applicant_spec.rb
spec/requests/legalaid_application_spec.rb
spec/services/save_applicant_spec.rb

Client name has been split out into two separate fields for first and last name
[Link to story](https://dsdmoj.atlassian.net/browse/AP-128)
As it stands the benefit checker requires letters from the surname in order to complete a successful request, and it was proving difficult to extract this information from a single client name field.

Split client name into first_name and last_name

---

app/controllers/proceeding_types_controller.rb
app/controllers/v1/proceeding_types_controller.rb
config/routes.rb
spec/requests/proceeding_types_controller_spec.rb

https://dsdmoj.atlassian.net/browse/AP-119
before proceeding types were retrieved with request path - /proceeding_types
with this change, it will be retrieved with request path - /v1/proceeding_types
and
removed the status endpoint which was hanging inside v1 namespace, it already exists outside.
this will fix the provider frontend rest call to API (for proceeding types)

added /v1 in request path for proceeding types

---

config/routes.rb
spec/requests/applicant_spec.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-8)
Why:
Doing this makes it clear that the url points to a single applicant
resource related to the application.

Changed the path of the applicant patch url to be singular.

---

README.md

Add CircleCI build status badge to README to will ensure that master build status is always visible.

Add CircleCI build status badge to README

---

Gemfile
Gemfile.lock
config/application.rb
db/migrate/20181017202608_enable_pgcrypto_extension.rb
db/migrate/20181018165257_add_foreign_keys.rb
db/migrate/20181018165405_id_to_uuid_fk.rb
db/migrate/20181018165537_uuid_migration.rb
db/schema.rb

The tables currently use sequential bigint to set the id. This change modifies the behaviour to use uuid instead.
The pgcrypto gem sets uuid as the default for all future tables that are created.
The webdack gem converts existing id fields to uuid and can be removed once the migrations have been run
Add foreign keys to existing references
Converts foreign keys on existing references to uuid
Convert all other id's (that are not foreign keys) to uuid

Migrate the database id's from sequential bigint to UUID

---

.gitignore

**Ignore git-crypt and Rails master keys**
As they're being generated at the CircleCI deploy stage and git-cryptcan't unlock files with untracked files.
Should have been part of https://github.com/ministryofjustice/laa-apply-for-legalaid-api/pull/36 😓

Ignore git-crypt and Rails master keys

---

.circleci/config.yml

So that we comply with Helm restrictions:
```
Error: UPGRADE FAILED: invalid release name, must match regex
^(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])+$ and the length must not
longer than 53
```
Addresses: https://github.com/ministryofjustice/laa-apply-for-legalaid-api/issues/42

Normalise release names in helm deploys

---

.circleci/config.yml

As we had two github teams setup and they were both being used for different purposes. This unifies all the configurations to use only one of those teams so we can make the other one obsolete.
Relates to: https://github.com/ministryofjustice/cloud-platform-environments/pull/233

Update GITHUB_TEAM_NAME_SLUG to right conf

---

features/providers/step_definitions/civil_journey_steps.rb
features/step_definitions/citizens_steps.rb

The `should` syntax in cucumber tests is generating a deprecation warning, changing to the `expect` syntax resolves this.

Resolve deprecation warning on cucumber tests by using the expect syntax

---

README.md

To ensure UAT releases that are no longer necessary are deleted.
This is to avoid exceeding the quota limits associated with UAT.
In the future, the idea is to have this process automated so that people don't have to worry about it.

Update instructions for release deploy cleansing

---

.circleci/config.yml

Recent circleci deployments to the staging environment have failed due
to an exceeded quota, however feedback from circleci indicates that the
build was successful. This meant that no one was aware of the failures.
To get more feedback in scenarios like this, add a --wait flag to the helm 
upgrade command so that if the deployment fails it will timeout and 
report a failure.
This replicates existing functionality for UAT deployments.
Separately, I have deleted old front-end/API releases from the staging 
namespace as they are no longer required, so the quota issue is no longer 
a problem.

Add timeout to staging/prod helm deploys

---

app/forms/applicants/basic_details_form.rb
app/validators/date_validator.rb
config/locales/en.yml

It was previously necessary to have validation to prevent users
entering a two-digit year of birth. This was due to the way the provider
front-end application handled dates of birth as three separate values
which were passed to the api.
Following the move to a single application the way the date of birth is
handled has changed to use a date object and this validation is no
longer needed. Two-digit dates of birth are correctly interpreted by
rails without any validation.
The validation on two-digit years was added in AP-161. I've commented 
on the ticket to explain the reasons for removing the validation and this
has been approved by Neil. 
[AP-161](https://dsdmoj.atlassian.net/browse/AP-161)

Remove validation for 2 digit year of birth

---

Gemfile.lock

this has been fixed in 2.0.6 this update applies the latest version
As mentioned here:
https://groups.google.com/forum/#!topic/rubyonrails-security/U_x-YkfuVTg
https://groups.google.com/forum/#!topic/rubyonrails-security/GKsAFT924Ag
2 vulnerabilities were discovered in rack 2.0.5, the version we were using, and the patch is available in 2.0.6
Highlighted by Matthew Rudy in the development slack channel here:
https://mojdt.slack.com/archives/C3F8L6XQU/p1541498824032500 

Rack gem had a vulnerability identified in version 2.0.5 

---

app/forms/applicants/address_form.rb
app/forms/applicants/basic_details_form.rb

The error summary was showing messages in an order different to the one in the design spec. 
[Link to story](https://dsdmoj.atlassian.net/browse/AP-171)
Moved the validation rules in the models so they are run and reported in the order required in the specification

Move validation order to match the order required by the design spec

---

app/assets/javascripts/templates/proceeding_result_template.js
app/assets/stylesheets/providers/legal_aid_applications.scss
app/views/providers/legal_aid_applications/new.html.erb

The current version has some styling differences to the prototype these changes bring it into line with the prototype
[Link to story](https://dsdmoj.atlassian.net/browse/AP-180)
Add padding to some elements for spacing
Replace link tag on text that was not a link
Change page the Home button redirects to

Add styling to the proceedings search page to match design spec

---

app/views/providers/address_lookups/_form.html.erb
app/views/providers/addresses/_form.html.erb
app/views/providers/applicants/new.html.erb
app/views/shared/forms/_text_fields.html.erb
config/locales/en.yml
spec/requests/providers/address_lookups_spec.rb
spec/requests/providers/addresses_request_spec.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-179)
- Added a new local variable to the Text Field partial that determines if a hint is displayed
This means on one page we can display the postcode field with a hint and on another without the hint
- Correcting the postcode text field partial call seemed to have fixed the error anchor link
- Added some logic that determines which title the manual address page should display depending on whether the user chose to input the address manual or was redirected after a lookup fail

Address lookup and selection page styling amendments (AP-179)

---

app/controllers/base_controller.rb
app/controllers/citizens/additional_accounts_controller.rb
app/views/citizens/additional_accounts/index.html.erb
app/views/citizens/additional_accounts/new.html.erb
config/routes.rb
db/migrate/20181107093419_add_has_offline_accounts_to_legal_aid_applications.rb
db/schema.rb
spec/requests/citizens/additional_accounts_spec.rb

[JIRA AP-71](https://dsdmoj.atlassian.net/browse/AP-71)
The start of these steps is at `/citizens/additional_accounts`
Adds two screens to allow a user to:
- Confirm they have no more accounts and continue
- Start the True Layer add another account journey
- Confirm they have other accounts, that they will need to supply other evidence, and continue
At the moment the next step in the process and the "add another account" journey are not defined, so the endpoints instead display simple landing pages.

AP-71 Allow applicant to select whether they have additional accounts

---

app/forms/applicants/address_selection_form.rb
app/models/address.rb
app/serializers/address_serializer.rb
app/services/map_address_lookup_results.rb
db/migrate/20181113153145_add_organisation_to_address.rb
db/schema.rb
spec/requests/applicants/create_address_spec.rb

[AP-181](https://dsdmoj.atlassian.net/browse/AP-181)
There are certain cases where the Ordnance Survey postcode API returns
results which do not have any values which we include in line_one or
line_two of the address. SW1A 1AA is an example of this. This means
that when the address is displayed for selection it is meaningless to
the user.
To address this, we will retrieve the ORGANISATION_NAME from the result 
and include it in the address. It will be persisted to the database. No change 
will be made to allow a user to manually enter an Organisation as part of an
address.
The story also refers to scenarios where no results are being returned by 
the API, even though it is a valid postcode (eg. SW1H 9AJ). I've opened a 
ticket with Ordnance Survey about this and will update Jira with the …

Retrieve Organisation from postcode API results

---

app/assets/javascripts/proceeding_types.es6
app/assets/stylesheets/providers/proceeding_types.scss
app/views/providers/legal_aid_applications/_proceeding_type.html.erb
app/views/providers/legal_aid_applications/new.html.erb
config/locales/en.yml

[Link to story](https://dsdmoj.atlassian.net/browse/AP-146)
- Update html as suggested in the ticket.
- Stop screen readers tabbing over select continue button
- Highlight the result item when the mouse hover overs  
- Each result item are now clickable and submit the selected proceeding.

AP-146 Proceeding search styling

---

app/assets/javascripts/proceeding_types.es6

[JIRA AP218](https://dsdmoj.atlassian.net/browse/AP-218)
The JavaScript code that handled submitting the form on clicking the div containing the proceeding type, had not been updated to match recent changes. That is, originally there was only one form and each button modified that form submission. Now there is a form for each proceeding type. Clicking the div now submits the form within that div.
Also note that this fixes the issue for keyboard submission too.

AP218 Fix proceeding search item not clickable

---

app/controllers/concerns/providers/steppable.rb
app/controllers/providers/check_benefits_controller.rb
app/controllers/providers/check_provider_answers_controller.rb
app/controllers/providers/online_bankings_controller.rb
app/forms/applicants/uses_online_banking_form.rb
app/models/legal_aid_application.rb
app/views/providers/check_provider_answers/index.html.erb
app/views/providers/online_bankings/show.html.erb
config/application.rb
config/locales/en.yml
config/routes.rb
db/migrate/20181129140032_add_uses_online_banking_to_applicant.rb
db/schema.rb
features/providers/civil_application_journey.feature
features/providers/step_definitions/civil_journey_steps.rb
spec/requests/citizens/accounts_spec.rb
spec/requests/providers/check_provider_answers_spec.rb
spec/requests/providers/online_bankings_spec.rb

[AP-209](https://dsdmoj.atlassian.net/browse/AP-209)
- Add a new page asking the provider if the client uses online banking. It has a yes/no radio button
- For now, it is after the **chek benefits** page but I will modify it as soon as AP-210 is merged
- If **Yes** is selected, it goes to **Check answers** page.
- If **No** is selected, it shows a placeholder message indicating to use CCMS
- Fix some sporadically failing tests (`spec/requests/citizens/accounts_spec.rb`)

[AP-209] Page "does-client-use-online-banking"

---

app/views/providers/about_the_financial_assessments/show.html.erb

[AP-210](https://dsdmoj.atlassian.net/browse/AP-210)
The original design included a warning symbol (a circle with an
exclamation mark in it). During review by the designer/product manager
it was decided that this was unnecessary and can be replaced with a
govuk-heading-m tag.

Remove Warning from about_the_financial_assessments

---

app/controllers/providers/check_benefits_controller.rb
app/helpers/check_provider_answers_helper.rb
app/models/legal_aid_application.rb
app/views/providers/check_provider_answers/index.html.erb
config/routes.rb
spec/requests/providers/check_benefits_spec.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-207)
- update address change link to go back to correct url based on how the address was inputed
- reset state back to check_your_answers on clicking back from check benefits page
- add a holding routes for passported check benefit 

fix issues with provider flow 

---

app/assets/javascripts/proceeding_types.es6
app/assets/stylesheets/providers/proceeding_types.scss
app/views/layouts/application.html.erb
app/views/providers/proceedings_types/_proceeding_type.html.erb

[AP-147](https://dsdmoj.atlassian.net/browse/AP-147)
* prevents proceedings type data being unnecessarily loaded on all pages.
* highlights text within the list proceedings search results that matches the user's search criteria

Ap 147 highlight proceedings text

---

app/assets/stylesheets/govuk-prefix-input.scss
app/lib/govuk_elements_form_builder/form_builder.rb
spec/lib/govuk_elements_form_builder/form_builder_spec.rb

To be used like this:
`govuk_text_field :home_value, input_prefix: '£'`
`govuk_text_field :home_percentage, input_prefix: '%'`

Add to govuk_text_field an option to insert a prefix inside the input

---

app/views/providers/proceedings_types/_proceeding_type.html.erb

I found a small accessibility issue when playing with accessibility audit tools. The ids used in the proceeding type forms were not unique.

Fix small accessibility issue in proceeding types

---

bin/uat_deploy

**Reduce number of UAT instances to 1**
UAT deploys are failing because of a lack of resources in the UAT
cloud platform environment.
To try and remediate this, reduce the number of instances created from
two to one. This should hopefully reduce resource consumption, while the
resilience offered by a replica instance is not really needed in a
short-lived UAT environment.
_Before_
Each environment has three pods, two applications and one postgres database:
_After_
Each environment has two pods, one applications and one postgres database:

Reduce number of UAT instances to 1

---

app/controllers/citizens/outstanding_mortgages_controller.rb
app/forms/legal_aid_applications/outstanding_mortgage_form.rb
app/helpers/gov_uk_form_helper.rb
app/lib/govuk_elements_form_builder/form_builder.rb
app/models/legal_aid_application.rb
app/views/citizens/outstanding_mortgages/show.html.erb
app/views/shared/forms/_form_group.html.erb
config/locales/en.yml
config/routes.rb
db/migrate/20181206100314_add_outstanding_mortgage_amount_to_legal_aid_applications.rb
db/schema.rb
spec/forms/outstanding_mortgage_form_spec.rb
spec/lib/govuk_elements_form_builder/form_builder_spec.rb
spec/requests/citizens/outstanding_mortgage_spec.rb

[AP-213](https://dsdmoj.atlassian.net/browse/AP-213)
Added a new citizens controller with show and update views.
Some extra complexity was added to get the £ sign within the input field.
GET renders:
PATCH with invalid input renders:

AP-213 Add Outstanding Mortgage page to Citizen journey

---

app/controllers/citizens/savings_and_investments_controller.rb
app/forms/savings_amounts/savings_amounts_form.rb
app/models/bank_account.rb
app/models/legal_aid_application.rb
app/models/savings_amount.rb
app/services/true_layer/importers/import_accounts_service.rb
app/views/citizens/savings_and_investments/_accounts_summary.html.erb
app/views/citizens/savings_and_investments/_attribute.html.erb
app/views/citizens/savings_and_investments/show.html.erb
config/locales/en.yml
config/routes.rb
db/migrate/20181210152857_add_account_type_to_bank_account.rb
db/migrate/20181211125447_create_saving_amounts.rb
db/schema.rb
spec/factories/legal_aid_applications.rb
spec/factories/savings_amounts.rb
spec/forms/savings_amounts/savings_amounts_form_spec.rb
spec/models/bank_account_spec.rb
spec/requests/citizens/savings_and_investments_spec.rb
spec/services/true_layer/importers/import_accounts_service_spec.rb
spec/support/true_layer_mock_data.rb

[AP-239](https://dsdmoj.atlassian.net/browse/AP-239)
Create a new page: `/citizens/savings_and_investment`.
At the top, it shows the true layer accounts if there are any.
The page contains 7 checkbox/inputs with the same pattern:
Click on the checkbox to reveal the text input.
These amounts are saved in a new model : `savings_amount`

AP-239 Citizen capital 2a savings and investments

---

app/controllers/citizens/restrictions_controller.rb
app/models/legal_aid_application.rb
app/models/legal_aid_application_restriction.rb
app/models/restriction.rb
app/views/citizens/restrictions/index.html.erb
config/locales/en.yml
config/routes.rb
db/migrate/20181207162049_create_restrictions.rb
db/migrate/20181207162311_create_legal_aid_application_restrictions.rb
db/schema.rb
db/seeds.rb
db/seeds/restriction.rb
spec/factories/legal_aid_application_restrictions.rb
spec/factories/restrictions.rb
spec/models/restriction_spec.rb
spec/requests/citizens/accounts_spec.rb
spec/requests/citizens/restrictions_spec.rb

[Jira AP-217](https://dsdmoj.atlassian.net/browse/AP-217)
This PR adds a `Restriction` model, and a `has_many :restrictions, through: :legal_aid_application_restrictions` on `LegalAidApplication`. The new page then allows a Citizen to choose to associate all, any or none of those restrictions with their current application.
`Restriction` has a number of predefined instances (named) to describe each restriction condition, and there is a class method to generate these. This has been added to seeding, so `rake db:seed` adds the standard `restrictions`. The generation task can be run multiple times without generating duplicates.
I cannot think of a normal invalid condition (the Citizen selects from pre-existings objects via checkboxes generated by the app). So there is no validation - and …

AP 217 Add restrictions that mean a Citizen cannot use capital assets

---

app/controllers/citizens/property_values_controller.rb
spec/requests/citizens/property_value_spec.rb

Property value was rendering a plain page when a value was entered.
Changed the controller to point to the outstanding mortgage path

Update route for citizen path to redirect to outstanding mortgage

---

app/controllers/citizens/own_homes_controller.rb
app/controllers/citizens/percentage_homes_controller.rb
app/controllers/citizens/property_values_controller.rb
app/controllers/citizens/shared_ownerships_controller.rb
app/controllers/providers/address_lookups_controller.rb
app/controllers/providers/address_selections_controller.rb
app/controllers/providers/addresses_controller.rb
app/controllers/providers/applicants_controller.rb
app/controllers/providers/online_bankings_controller.rb
app/forms/addresses/address_form.rb
app/forms/addresses/address_lookup_form.rb
app/forms/addresses/address_selection_form.rb
app/forms/applicants/basic_details_form.rb
app/forms/base_form.rb
app/forms/legal_aid_applications/outstanding_mortgage_form.rb
app/forms/legal_aid_applications/own_home_form.rb
spec/forms/addresses/address_form_spec.rb
spec/forms/addresses/address_lookup_form_spec.rb
spec/forms/addresses/address_selection_form_spec.rb
spec/forms/applicants/basic_details_form_spec.rb
spec/forms/legal_aid_applications/own_home_form_spec.rb
spec/requests/citizens/property_value_spec.rb

This PR: 
That is, this controller code:
```ruby
def show
@form = SomeForm.new(current_params)
end
def current_params
model.attributes.symbolize_keys.slice(:an_attribute, :another_attribute)
end
```
Is replaced with:
```ruby
def show
@form = SomeForm.new(model: model)
end
```
This means the complicated bit (deciding where to get the data (existing or passed in attribute)) is defined once (in `BaseForm`), and not in every controller.
Each form now just accepts the object it applies to, and it relies on the controller to choose/gather the object and pass it to the form. So parameters passed to the form to allow it to select an object have been removed. That is, instead of passing in the id of the `LegalAidApplication` to the form for it to gather that, and then from that get the target …

Make forms more consistent, and simplify initializating with existing objects

---

app/controllers/citizens/additional_accounts_controller.rb
app/views/citizens/accounts/index.html.erb
spec/requests/citizens/additional_accounts_spec.rb

The current flow goes from the account summary page to asking if you have online access to other banks, skipping out the intermediate step of asking i they have other accounts.
Users are now asked if they have other bank accounts before they are asked if they have online access to those accounts.
[Link to story](https://dsdmoj.atlassian.net/browse/AP-240)
Changed the behaviour of the controllers to implement this loop. I looked at recreating the steppable module from providers, but it seemed like an overly complicated way to achieve this result. Also this forms more of a loop and exit as opposed to a linear step.

Change order flow for citizens account questions

---

Gemfile
Gemfile.lock
app/lib/govuk_elements_form_builder/form_builder.rb
app/views/citizens/own_homes/show.html.erb
app/views/citizens/property_values/show.html.erb
app/views/citizens/savings_and_investments/_attribute.html.erb
app/views/providers/addresses/_form.html.erb
app/views/providers/online_bankings/show.html.erb
config/locales/en.yml
spec/factories/applicants.rb
spec/lib/govuk_elements_form_builder/form_builder_spec.rb
spec/requests/providers/online_bankings_spec.rb

. Add `govuk_radio_button` and `govuk_collection_radio_buttons` to the form builder
. Refactor form_builder and its tests to make it a bit less complicated and add `aria-describedby` attributes.
. Modify a couple of pages to use `govuk_collection_radio_buttons`.
FYI, this FormBuilder generates HTML described on https://design-system.service.gov.uk/components/radios/

FormBuilder : Add govuk_collection_radio_buttons

---

spec/requests/citizens/legal_aid_applications_spec.rb

**Fix flashing rspec test**
/spec/requests/citizens/legal_aid_applications_spec.rb fails if Faker
generates a first_name or last_name that contains a non-alpha
character - usually an apostrophe.
Prevent this occurring by using unescaped_response_body instead of
response.body for the comparison.

Fix flashing rspec test

---

db/migrate/20181219135328_create_other_assets_declarations_table.rb
db/schema.rb

Create other assets decalrations migration
This adds a migration to create the other assets declarations table, which should have been part of AP-216.

Recreate other assets

---

Gemfile
app/assets/stylesheets/govuk-currency-input.scss
app/assets/stylesheets/govuk_percent-input.scss
app/controllers/citizens/other_assets_controller.rb
app/controllers/providers/legal_aid_applications_controller.rb
app/forms/citizens/other_assets_form.rb
app/helpers/money_helper.rb
app/lib/govuk_elements_form_builder/form_builder.rb
app/models/legal_aid_application.rb
app/models/other_assets_declaration.rb
app/views/citizens/other_assets/_second_home_conditional_checkbox.html.erb
app/views/citizens/other_assets/show.html.erb
app/views/citizens/savings_and_investments/show.html.erb
app/views/shared/forms/_conditional_checkbox_with_numeric_input.html.erb
app/views/shared/revealing_checkbox/_attribute.html.erb
config/locales/en.yml
config/routes.rb
db/migrate/20181206142708_create_other_asset_declaration.rb
db/schema.rb
spec/factories/legal_aid_applications.rb
spec/factories/other_assets_declarations.rb
spec/forms/citizens/other_assets_form_spec.rb
spec/lib/govuk_elements_form_builder/form_builder_spec.rb
spec/models/legal_aid_application_spec.rb
spec/models/other_assets_declaraion_spec.rb
spec/requests/citizens/legal_aid_applications_spec.rb
spec/requests/citizens/other_assets_spec.rb
spec/requests/providers/legal_aid_applications_spec.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-216)
This page comprises 9 checkboxes which expand to expose 1 to 3 edit boxes
when checked.  The data is stored in an OtherAssetsDeclaration model which
is linked to the legal aid application on a one-to-one bases (legal aid application
has one other_assets_declaration) - this is to help prevent the legal aid declaration
model ending up with 50 columns.
Although working, the markup for the revealing checkboxes may need to be tweaked 
in order to make appearance and behaviour the same as on the other page with 
revealing checkboxes, probably by implementing this element in the FormBuilder 
and using the FormBuilder on both pages.

AP-216 Implementation of Other Assets page

---

app/controllers/concerns/providers/steppable.rb
app/controllers/providers/percentage_homes_controller.rb
app/helpers/application_helper.rb
app/views/citizens/other_assets/_second_home_conditional_checkbox.html.erb
app/views/providers/percentage_homes/show.html.erb
app/views/shared/forms/_percentage_home_form.html.erb
config/locales/en.yml
config/routes.rb
spec/requests/providers/percentage_home_spec.rb

[Create provider percentage share screen](https://dsdmoj.atlassian.net/browse/AP-225)
This creates the provider version of the 'What % share of your home do you legally own?' screen.
- amend citizens view to move content into shared form
- create provider view, using shared form
- create provider controller and route
- amend steppable to add navigation
- amend locales/en.yml to create citizen/provider wordings
- add spec
The change to application_helper.rb borrows shamelessly from @stephenrichards' https://github.com/ministryofjustice/laa-apply-for-legal-aid/pull/164.
Some work will still be required to fix navigation issues when all related screens are in place.

Create provider percentage share screen

---

app/controllers/concerns/providers/steppable.rb
app/controllers/providers/outstanding_mortgages_controller.rb
app/helpers/application_helper.rb
app/views/citizens/outstanding_mortgages/show.html.erb
app/views/providers/outstanding_mortgages/show.html.erb
app/views/shared/forms/_outstanding_mortgage_form.html.erb
config/locales/en.yml
config/routes.rb
db/schema.rb
spec/requests/providers/outstanding_mortgage_spec.rb

Adds the outstanding mortgage form to the provider journey and refactors the citizen form
[Link to story](https://dsdmoj.atlassian.net/browse/AP-223)
Used outstanding_mortgage form on citizen journey and refactored using Stephen's approach for the property value form so that translations are journey specific. 
Added the form to the steppable module - still needs to be defined with correct steps 

Ap223 provider outstanding mortgage

---

app/services/benefit_check_service.rb
spec/cassettes/BenefitCheckService/_check_benefits/when_some_credentials_are_missing/raises_a_detailed_error.yml
spec/cassettes/BenefitCheckService/_check_benefits/when_the_API_raises_an_error/raises_a_detailed_error.yml
spec/services/benefit_check_service_spec.rb

Improve error reporting of BenefitChecker API by including more information about the error.
Recently, the API raised an error because the `surname` passed in parameter was only one character.
However, the error we saw in Sentry was simply **"Savon::SOAPFault: (soapenv:Server.generalException)"**.
With this PR, the error includes the real error message **"Error in request parameter 'Surname'"**

Improve error reporting of BenefitChecker API

---

app/controllers/citizens/check_answers_controller.rb
app/controllers/concerns/flowable.rb
app/helpers/application_helper.rb
app/models/concerns/legal_aid_application_state_machine.rb
app/models/legal_aid_application.rb
app/services/page_flow_service.rb
app/views/citizens/check_answers/index.html.erb
app/views/citizens/own_homes/show.html.erb
app/views/citizens/percentage_homes/show.html.erb
config/locales/en.yml
config/locales/model_enum_translations.en.yml
config/routes.rb
spec/requests/citizens/check_answers_spec.rb
spec/requests/citizens/property_value_spec.rb
spec/requests/citizens/savings_and_investments_spec.rb
spec/requests/providers/check_provider_answers_spec.rb

[AP-258](https://dsdmoj.atlassian.net/browse/AP-258)
Implement the redirect to the check your answers page when the citizen is checking their answers

AP-258 - Citizen - Redirect to checking answers page

---

app/views/citizens/accounts/index.html.erb
app/views/citizens/additional_accounts/index.html.erb
app/views/citizens/additional_accounts/new.html.erb
app/views/citizens/consents/show.html.erb
app/views/citizens/information/show.html.erb
app/views/citizens/legal_aid_applications/show.html.erb
app/views/providers/check_benefits/index.html.erb
app/views/shared/forms/other_assets/_form.html.erb

Fix page layouts to ensure all except tables inside two-thirds div
[Link to story](https://dsdmoj.atlassian.net/browse/AP-259)
Put all of page content except tables inside a two-thirds width div, inside a row div.  Tables are full page width

AP-259 Fix Page layouts

---

app/assets/javascripts/proceeding_types.es6

[AP-254](https://dsdmoj.atlassian.net/browse/AP-254)
Allow users to 1) search within words, not just the start of words, and
2) ignore non-alphanumeric characters when searching, by:
1) changing the js-search search strategy to AllSubstringsIndexStrategy
and
2) adding a custom js-search tokenizer to remove non-alphanumeric
characters from search.

Improve proceedings search

---

app/controllers/citizens/additional_accounts_controller.rb
app/services/page_flow_service.rb
app/views/citizens/additional_accounts/index.html.erb
app/views/citizens/additional_accounts/new.html.erb
spec/requests/citizens/additional_accounts_spec.rb

[AP-255](https://dsdmoj.atlassian.net/browse/AP-255)
- Add back links to "Additional Accounts" pages
- Improve a tiny bit an exception message when `STEPS_FLOW` is not setup properly

AP-255 Fix additional account flow

---

.circleci/config.yml

[AP-282](https://dsdmoj.atlassian.net/browse/AP-282)
Triggers a deploy to staging every day at 2am UTC.
I just tried a schedule UAT deploy of this branch with a similar syntax and it worked. So hopefully this will work too.

AP-282 Nightly deploy to Staging

---

app/controllers/providers/providers_controller.rb
app/helpers/application_helper.rb
app/helpers/providers_helper.rb
app/views/providers/outstanding_mortgages/show.html.erb
app/views/providers/own_homes/show.html.erb
app/views/providers/proceedings_types/show.html.erb
app/views/providers/property_values/show.html.erb
app/views/providers/providers/show.html.erb
app/views/providers/restrictions/index.html.erb
app/views/providers/savings_and_investments/show.html.erb
app/views/shared/providers/_basic_page_template.html.erb
config/locales/en.yml
config/routes.rb
spec/requests/providers/providers_spec.rb

[Jira AP-257](https://dsdmoj.atlassian.net/browse/AP-257)
Adds a provider user profile page.
The username link at the top of the page now leads you to the new page (once you are logged in as a Provider):
Currently the new page doesn't show a lot as there is not a lot of Provider data coming back from the log on system. 
Note - that the route path attribute give the path `/providers/your_profile` and the "back" link does a JavaScript back - so takes you back to your previous page.
Note that I've also added a new template that makes it easier to create pages using the standard format. The template is inserted via the helper method `provider_basic_page`. If people like this approach, I don't think it will be difficult to extend it to work with forms.

AP-257 Add providers profile page

---

app/views/shared/forms/_next_action_buttons.html.erb

[AP-269](https://dsdmoj.atlassian.net/browse/AP-269)
The issue was that the partial containing the button is already inside a `two-thirds` div. So the buttons ended up nested in two `two-thirds` divs. And it would break line unnecessarily.

AP-269 Draft button placement

---

app/helpers/gov_uk_form_helper.rb
app/views/citizens/consents/show.html.erb
app/views/shared/forms/_body.html.erb

Adjust first paragraph which is in  a two-thirds div inside a two-thirds div.
[Link to story](https://dsdmoj.atlassian.net/browse/AP-90)
- put body text in simple p tags rather than govuk_body formbuilder method which adds the extra two thirds div
- remove the FormBuilder's govuk_body method as it isn't being used elsewhere
- remove the _body partial which is only used by the above method

AP-290 Adjust page layout on citizen consent page 

---

bin/clean_up_ecr.rb

AWS ECR repositories have a limit of 1000 images. When this limit is reached no further builds are possible.
This script will delete all but the last 30 days of images, allowing builds to resume.
To run it, first follow the instructions in https://dsdmoj.atlassian.net/wiki/spaces/ATPPB/pages/1377992881/ECR+Repository+Maintenance to connect to the ECR instance.
(The code for this was stolen shamelessly from https://gist.github.com/dmerrick/503655db7ff90b70c2d15fc9dd83b45e)

Add clean_up_ecr script

---

Procfile
docker/run

At the moment, when using `foreman`, when returning from the SAML authentication it redirects to port `5000` which is foreman default's port. And it fails because the app is on localhost:3002 (not 5000)
With this fix, you can choose which port you want to use : 
`foreman start -p 3000`
`foreman start -p 3002`
`foreman start` (port 5000)
And it will work

FIX - foreman in local - redirect to port 5000 after SAML auth

---

.circleci/config.yml
bin/clean_up_ecr
bin/delete_ecr_images

clean_up_ecr is a script that deletes old images in order to resolve/avoid the limit of 1000 images in the ECR repo. Rather than run this manually it would be useful if this was automated. This change creates a job to run it and add it to the nightly job in .circleci/config.yml.

Run clean_up_ecr nightly

---

config/locales/en.yml

[JIra AP-278](https://dsdmoj.atlassian.net/browse/AP-278)
Very small update to copy to allow same blank isa error message to be used in both the Citizen and Provider journeys.

AP-278 Modify blank isa error message so works for Citizen and Provider

---

app/controllers/concerns/providers/save_as_draftable.rb
app/controllers/concerns/providers/steps.rb
app/controllers/providers/check_passported_answers_controller.rb
app/controllers/providers/other_assets_controller.rb
app/helpers/check_answer_url_helper.rb
app/helpers/providers_helper.rb
app/models/concerns/legal_aid_application_state_machine.rb
app/views/providers/check_passported_answers/show.html.erb
app/views/shared/_check_answers_assets.html.erb
bin/uat_deploy
config/locales/en.yml
config/locales/model_enum_translations.en.yml
config/routes.rb
spec/factories/legal_aid_applications.rb
spec/helpers/check_answer_url_helper_spec.rb
spec/requests/citizens/check_answers_spec.rb
spec/requests/providers/check_passported_answers_spec.rb
spec/requests/providers/other_assets_spec.rb
spec/requests/providers/restrictions_spec.rb
spec/requests/providers/savings_and_investments_spec.rb
spec/support/change_link_matcher.rb

For passported clients (i.e. clients with a qualifying DWP benefit), the
provider fills out the capital questions rather than the client.
At the end of this process, the provider gets a chance to review the
answers he's supplied and change those that need changing.
[Link to story](https://dsdmoj.atlassian.net/browse/AP-275)
The main body of the citizens' check your answer page has been put into
a partial, and the providers/check_passported answers page uses that as well.
Because the Change links vary betwen the provider and passported journey, the
partial now calls a new helper method `#check_answer_url_for`

AP-275 check passported answers

---

db/migrate/20190122115534_update_provider_id_to_application.rb
db/schema.rb

As we don't remove the application from staging on deploying, we have several application which can't be accessed because we don't have provider id.
I have added a migration to default these application to the test user which is working.
https://sentry.service.dsd.io/mojds/apply-for-legal-aid-staging/issues/34419/

migration to add provider to legal aid application on staging

---

config/locales/en.yml
spec/forms/applicants/basic_details_form_spec.rb

[Link to story AP-285](https://dsdmoj.atlassian.net/browse/AP-285)
[Link to story AP-286](https://dsdmoj.atlassian.net/browse/AP-286)
Removed quotation marks from hint text.
Editing text and associated test for email error message - conforming to examples on GDS Design System.

Apply text changes

---

bin/uat_deploy

A small change to code that constructs the UAT instance name. The new system:
- Removes leading labels such as `feature/` or `release/`
- Truncates the end of the name rather than the beginning. As most devs put the ticket label at the start of the branch name, this is preserved in the UAT instance name.
If you look at the deployment output of this PR you can see the result of this change:
```
==> v1/Service
apply-for-legal-aid-ap-xxx-modify-name-of-uat-inst-postgresql    1m
apply-for-legal-aid-ap-xxx-modify-name-of-uat-inst-apply-for-le  1m
==> v1beta1/Deployment
apply-for-legal-aid-ap-xxx-modify-name-of-uat-inst-postgresql  1m
NOTES:
1. Get the application URL by running these commands:
http://ap-xxx-modify-name-of-uat-inst-applyforlegalaid-uat.apps.cloud-platform-live-0.k8s.integration. …
```

Change way UAT instances are named so that easier to identify

---

bin/uat_deploy

After the change to the naming convention for UAT instances, it's now
possible to have a name that ends with a '-'. This causes a failure
in CircleCI.
To fix this, amend the bash command that calculates the name so that it
strips any trailing dashes.

Fix bug with UAT names that end in dash

---

config/locales/devise.en.yml

[AP-317](https://dsdmoj.atlassian.net/browse/AP-317)
When a user signs in via the portal, devise sets a flash message which is displayed to the user. They don't need to see this.
Remove it by removing the message wording from the config/locales/devise.en.yml file.
This will allow other flash messages set by devise to still work as expected (if we need them - if we decide later that we don't then they can be removed by a separate change).

Remove 'Signed in successfully' message

---

.gitignore
app/controllers/concerns/providers/steps.rb
app/controllers/providers/client_received_legal_helps_controller.rb
app/controllers/providers/proceedings_before_the_courts_controller.rb
app/forms/merits_assessments/proceedings_before_the_court_form.rb
app/views/providers/proceedings_before_the_courts/show.html.erb
config/locales/en.yml
config/routes.rb
db/migrate/20190124113350_add_proceedings_before_the_court_to_merits_assessment.rb
db/schema.rb
features/providers/civil_application_journey.feature
spec/requests/providers/client_received_legal_helps_spec.rb
spec/requests/providers/proceedings_before_the_court_spec.rb

[AP-261](https://dsdmoj.atlassian.net/browse/AP-261)
Add the Merits Assessment page "Are the proceedings, for which funding is being sought, currently, before the court?"
This is based on Julien's [PR](https://github.com/ministryofjustice/laa-apply-for-legal-aid/pull/233) for AP-260, to make use of his new text_area FormBuilder component and to allow the two new pages to be integrated correctly.

AP-261 - Merits Assessment: Proceedings Before The court

---

app/views/providers/own_homes/show.html.erb
db/schema.rb

This fixes a bug on the Provider Own Home page where the H1 heading was duplicated
Used the basic_template rather than the default template.

Fix duplication of heading

---

app/assets/stylesheets/check-your-answers.scss
app/helpers/check_answers_helper.rb
app/views/shared/check_answers/_currency_items.html.erb
app/views/shared/check_answers/_item.html.erb
app/views/shared/check_answers/_items.html.erb

The GOVUK design system has additional styling for Check Your Answers pages, the `.app-check-your-answers--long` class which increases the width of question fields to prevent long questions being split over multiple lines.
This was removed from our version of the pattern by a previous commit but is now required for AP-266, the merits check your answers page.
This change adds back in the styling for the class, and amends the check_answers_helper and shared partials to allow an extra parameter (`is_long`) to be passed so that the `--long` version of the class can be used from the existing helper, eg
```
<%= check_answer_link(
name: 'foo',
url: '#',
question: 'a very long question that would split over multiple lines',
answer: 'yes',
is_long: true
) %>
```
would result in
instead of 
which …

Add styling for app-check-your-answers--long

---

app/helpers/application_helper.rb
app/views/citizens/consents/show.html.erb
app/views/citizens/information/show.html.erb
app/views/citizens/legal_aid_applications/index.html.erb
app/views/providers/about_the_financial_assessments/show.html.erb
app/views/providers/merits_declarations/show.html.erb
app/views/providers/start/index.html.erb
app/views/shared/forms/_detailed_list.html.erb
app/views/shared/forms/_list_items.html.erb
config/locales/en.yml

The existing detailed_list partial was not suitable for all list types, this creates a new list_item partial that is more flexible allowing new list items to be easily added or removed without needing to amend the code in the view.
The list_item partial checks the locales (en.yml) file for the relevant items. Instead of using:
```
item_1: First list item
item_2: Second list item
item_3: Another list item for good measure
```
You can now use:
```
list: |
First list item
Second list item
Another list item for good measure
```
Items in the list can be added or removed without needing to change anything in the view. 
The detailed_list partial has also been amended to use this partial.

Refactor exisiting lists to use the same partial

---

app/assets/stylesheets/providers/proceeding_types.scss
app/controllers/concerns/providers/steps.rb
app/controllers/providers/check_provider_answers_controller.rb
app/controllers/providers/proceedings_types_controller.rb
app/policies/legal_aid_application_policy.rb
app/views/providers/check_provider_answers/index.html.erb
app/views/providers/proceedings_types/_proceeding_type.html.erb
app/views/providers/proceedings_types/_proceeding_type_form.html.erb
app/views/providers/proceedings_types/index.html.erb
config/locales/en/generic.yml
config/locales/en/providers.yml
config/routes.rb
features/cassettes/Civil_application_journeys/I_am_able_to_select_and_delete_proceeding_types.yml
features/cassettes/Civil_application_journeys/I_am_able_to_select_multiple_proceeding_types.yml
features/providers/civil_application_journey.feature
features/providers/step_definitions/civil_journey_steps.rb
features/providers/step_definitions/skippy.rb
spec/requests/providers/address_selections_spec.rb
spec/requests/providers/addresses_spec.rb
spec/requests/providers/application_dependable_spec.rb
spec/requests/providers/base_controller_spec.rb
spec/requests/providers/check_provider_answers_spec.rb
spec/requests/providers/legal_aid_applications_spec.rb
spec/requests/providers/proceedings_types_spec.rb

[AP-295](https://dsdmoj.atlassian.net/browse/AP-295)
This PR changes the behaviour of `proceeding_types` page. Now:
- When a Provider selects a Proceeding Type from the search results it appears in the list of selected Proceeding Types.
- They can then either: select another Proceeding Type, remove a selected one, or click on Continue to move to the next page
- If they click Continue without having first selected a Proceeding Type, they see an error and are prompted to select one.

Ap 295 display selected legal proceeding

---

app/views/saml_idp/idp/saml_post.html.erb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-345)
We use `ruby-saml-idp` gem to mock saml.  In [app/views/saml_idp/idp/saml_post.html.erb](https://github.com/saml-idp/saml_idp/blob/master/app/views/saml_idp/idp/saml_post.html.erb) which post the saml details on load of page using javascript.   This would break when javascript is turned off.  
I have created a new version of app/views/saml_idp/idp/saml_post.html.erb in our app, which overrides the gem version and display a submit button if javascript is disabled.

AP-345 Unable to log in with SAML on UAT when Javascript is turned off

---

Gemfile
Gemfile.lock
config/initializers/sidekiq.rb

I noticed that the pulling of data from TrueLayer was not working in UAT because all UAT envs share the same redis instance and therefore, any UAT sidekiq instance could pick up a job started from any other UAT envs.
I'm adding the host (i.e.: `fix-sidekiq-applyforlegalaid-uat.apps.cloud-platform-live-0.k8s.integration.dsd.io`) as a namespace

FIX : Wrong Sidekiq instance picking up job

---

app/assets/stylesheets/layout.scss
app/helpers/application_helper.rb
app/views/layouts/_header.html.erb

[AP-303](https://dsdmoj.atlassian.net/browse/AP-303)
Implement the GOVUK pattern which hides the username and logout links in the header when a small screen is used, allowing them to be revealed by clicking the Menu button: https://design-system.service.gov.uk/styles/page-template/custom/index.html
* Amend `application_helper.rb` to generate the correct html, by creating each link as a list element in a `<ul>` with the `govuk-header__navigation` class
* Truncate usernames at 20 characters at all screen sizes to prevent overlap with the service name
* Add the Menu button to the `_header.html.erb` partial
* Add extra styling to `layout.css` to position new elements correctly

Show nav links as menu on small screens

---

app/views/feedback/show.html.erb

[AP-349](https://dsdmoj.atlassian.net/browse/AP-349)
Remove `back_link parameter` from call to `page_template` helper in `feedback/show.html.erb`.

Remove back link from post-feedback page

---

app/assets/stylesheets/check-your-answers.scss
app/helpers/check_answers_helper.rb
app/views/citizens/check_answers/index.html.erb
app/views/citizens/own_homes/show.html.erb
app/views/providers/check_merits_answers/show.html.erb
app/views/providers/check_provider_answers/index.html.erb
app/views/shared/_check_answers_assets.html.erb
app/views/shared/check_answers/_currency_items.html.erb
app/views/shared/check_answers/_item.html.erb
app/views/shared/check_answers/_items.html.erb
package-lock.json
package.json
spec/requests/citizens/check_answers_spec.rb
spec/requests/providers/check_passported_answers_spec.rb

[Jira AP-339](https://dsdmoj.atlassian.net/browse/AP-339)
Unfortunately this was a little like attacking a Hydra. Each action seemed to need multiple actions.
So in the end:
- Implemented [latest GOV-UK Check your answers styling](https://design-system.service.gov.uk/patterns/check-answers/). As there are many check your answers pages - they all needed to be updated.
- To get the new styling, `govuk-frontend` needed to be upgraded.
- Refactored `check_answer_link` to work with new styling - in the end split it into three. One to handle single entries, a second for lists of items, and another for groups of currency entries.
- This almost fixed the email issue, but with very long emails there was still an issue. Adding a `min-width` to `.govuk-summary-list__key` fixed that.

AP-339 Implement latest GOV-UK check answers styling and fix long emails

---

app/controllers/saml_sessions_controller.rb

[Jira AP-317](https://dsdmoj.atlassian.net/browse/AP-317)
Overridden the devise method that generates the flash messages, so that it just logs notice flash messages.

AP-317 supressing flash notices in SAML session controller

---

app/services/flow/base_flow_service.rb
app/services/flow/flows/provider_merits.rb
features/providers/civil_application_journey.feature
features/providers/step_definitions/civil_journey_steps.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-267)
amend flow so that when a provider changes a merits answer and presses continue they return to the check merits answers page

Ap 267 change merits answers

---

README.md
app/services/flow/base_flow_service.rb
app/services/flow/flow_steps.rb
app/services/flow/flows/citizen_capital.rb
app/services/flow/flows/citizen_start.rb
app/services/flow/flows/provider_capital.rb
app/services/flow/flows/provider_merits.rb
app/services/flow/flows/provider_start.rb
spec/services/flow_service_spec.rb

A small refactor. I've done three main things:
1. Remove some duplication of code (the `step` and `path` methods were very similar)
2. Moved `urls` into the context of the `STEPS` defining objects - so they no longer need to be passed into each `proc` call.
3. Added some specs that pass in a plain hash rather than an existing `STEPS` to make it easier to test at a very low level.

Refactor Flows

---

app/views/providers/check_merits_answers/show.html.erb

[AP-361](https://dsdmoj.atlassian.net/browse/AP-361)
On a number of merits questions a provider can enter text explanations. It is possible that a user will enter multiple paragraphs of text, especially on the Statement of Case screen. At present when these responses are displayed on the check your answers screen line-breaks are ignored which means that multiple paragraphs are displayed as a single block of text, making it hard to read.
To improve this, use the `simple_format` method to display text on the check your answers screen as it was entered by the user.
Note: there are other existing issues with the look and feel of this screen which will be addressed by a separate story to be created by the designer.

Improve text layout on check merits answers screen

---

Gemfile
Gemfile.lock
app/services/flow/flows/provider_capital.rb
app/views/providers/check_passported_answers/show.html.erb
app/views/shared/_check_answers_assets.html.erb
config/locales/en/providers.yml
config/locales/en/shared.yml
features/providers/check_your_answers.feature
features/providers/step_definitions/civil_journey_steps.rb
spec/factories/legal_aid_applications.rb
spec/requests/providers/check_passported_answers_spec.rb
spec/requests/providers/other_assets_spec.rb
spec/requests/providers/savings_and_investments_spec.rb
spec/requests/providers/shared_ownerships_spec.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-312)
- Implemented new GDS styling for Check passported answers page
- Ensures that restrictions are asked for if there any assets after changin

AP-312 Check passported answers changes

---

app/services/malware_scanner.rb
spec/services/malware_scanner_spec.rb

Improve the call to the malware scan `clamdscan`.
Before, if there was a problem with the command itself, it would no raise an error but fail silently and give a false positive result.
Now, it will raise an error.
And `Open3.capture3` seems to be a prefered way to run system commands with which you can get every outputs (stdout, stderr, and the exit code)

Improve malware scanner

---

app/forms/base_form.rb
app/forms/citizens/other_assets_form.rb
app/forms/legal_aid_applications/outstanding_mortgage_form.rb
app/forms/legal_aid_applications/property_value_form.rb
app/forms/merits_assessments/estimated_legal_cost_form.rb
app/forms/savings_amounts/savings_amounts_form.rb
app/forms/statement_of_cases/statement_of_case_form.rb
app/helpers/money_helper.rb
app/lib/govuk_elements_form_builder/form_builder.rb
app/services/currency_cleaner.rb
app/validators/currency_validator.rb
app/views/citizens/property_values/_form.html.erb
app/views/shared/forms/_error_summary.html.erb
app/views/shared/forms/_estimated_legal_cost_form.html.erb
app/views/shared/forms/_outstanding_mortgage_form.html.erb
app/views/shared/forms/_percentage_home_form.html.erb
app/views/shared/forms/other_assets/_second_home_conditional_checkbox.html.erb
app/views/shared/forms/revealing_checkbox/_attribute.html.erb
config/locales/en/activemodel.yml
db/schema.rb
spec/forms/citizens/other_assets_form_spec.rb
spec/forms/outstanding_mortgage_form_spec.rb
spec/helpers/money_helper_spec.rb
spec/requests/providers/estimated_legal_costs_spec.rb
spec/services/currency_cleaner_spec.rb
spec/validators/currency_validator_spec.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-325)
Previously, currency validations were inconsistent and allowed too many decimals.
Have created a new currency validator, which is used on all forms.
In addition, CurrencyCleaner will remove currency signs and commas if the string is a valid value.
If there are errors, the original String that was input by the user is redisplayed back on the form.

AP 325 Fix validation

---

app/views/shared/access_denied.html.erb
config/locales/en/shared.yml

[Link to story](https://dsdmoj.atlassian.net/browse/AP-351)
Add a return to applications link to the access denied page so a provider can exit the page and return to where they can search for the application they need.

Add a back to applications link to the access denied page

---

app/controllers/providers/capital_introductions_controller.rb
app/services/flow/flows/provider_start.rb
app/views/providers/capital_introductions/show.html.erb
config/locales/en/providers.yml
config/routes.rb
features/providers/civil_application_journey.feature
spec/requests/providers/capital_introductions_spec.rb
spec/requests/providers/check_benefits_spec.rb

add the capital introduction page to the start of the capital flow questions.
[Link to story](https://dsdmoj.atlassian.net/browse/AP-247)
updated the provider flow to direct the provider to this page if the client is passported, otherwise they dont see this page. 

AP 247 provider capital introduction

---

app/controllers/citizens/transactions_controller.rb
app/models/applicant.rb
app/models/bank_transaction.rb
app/models/transaction_type.rb
app/services/flow/flows/citizen_income.rb
app/views/citizens/transactions/show.html.erb
config/locales/en/citizens.yml
config/locales/en/default.yml
config/locales/en/models.yml
config/routes.rb
spec/factories/bank_transactions.rb
spec/factories/transaction_types.rb
spec/requests/citizens/transactions_spec.rb

[AP-186](https://dsdmoj.atlassian.net/browse/AP-186)
Paired with @AbdirizakObsiye2018 
Page to assign transactions to a transaction type.
Works with any transaction type.
`transaction_type` is a parameter of the page.
For example: `/citizens/transactions?transaction_type=salary`
If the transaction type is a `credit` type, only `credit` transactions are listed. And vice versa.
Transaction types are:
```
credit: 
salary
benefits
maintenance_in
property_or_lodger
student_loan
pension
fiends_or_family
debit: 
rent_or_mortgage
council_tax
child_care
maintenance_out
legal_aid
```

AP-186 Identity Salary

---

.circleci/config.yml
Dockerfile
app/forms/statement_of_cases/statement_of_case_form.rb
app/services/malware_scanner.rb
spec/requests/providers/statement_of_case_spec.rb
spec/services/malware_scanner_spec.rb

[AP-396](https://dsdmoj.atlassian.net/browse/AP-396)
Disable malware-check for now.
At the moment, `clamdscan` stops when the k8s container is restarted
TODO: re-enable it when `clamdscan` works consistently

Disable malware check until it works consistently

---

app/assets/javascripts/table-select-all.es6
app/assets/javascripts/table-sort.es6
app/assets/stylesheets/table-sort.scss
app/controllers/citizens/transactions_controller.rb
app/views/citizens/transactions/show.html.erb
config/locales/en/citizens.yml
spec/requests/citizens/transactions_spec.rb

[AP-383](https://dsdmoj.atlassian.net/browse/AP-383)
Adding features to the bank transactions page: 
- select all
- ability to sort columns
- Removing check box next to items already selected in other categories
**select all** and the **sort** are mostly copied from Malcolm's code on the prototype

AP-383 identify salary - sorting and select all

---

app/assets/stylesheets/no_wrap.scss
app/controllers/providers/statement_of_cases_controller.rb
app/forms/statement_of_cases/statement_of_case_form.rb
app/models/statement_of_case.rb
app/views/providers/statement_of_cases/_uploaded_files.html.erb
app/views/providers/statement_of_cases/show.html.erb
config/locales/en/activemodel.yml
config/locales/en/generic.yml
config/locales/en/providers.yml
features/support/steps_helper.rb
spec/factories/statement_of_cases.rb
spec/requests/providers/statement_of_case_spec.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-365)
- Added a partial to display details of files already uploaded
- Added an Upload button to allow upload of files without progressing to the next page
- Changed validation to iterate through all files uploaded in one go and perform validation
- Added validation to ensure a file was specified if the upload button was pressed.

Ap 365 multiple files upload

---

app/controllers/citizens/identify_types_of_outgoings_controller.rb
app/services/flow/flows/citizen_income.rb
app/views/citizens/identify_types_of_outgoings/show.html.erb
config/locales/en/citizens.yml
config/locales/en/models.yml
config/routes.rb
spec/requests/citizens/identify_types_of_outgoings_spec.rb

[AP-377](https://dsdmoj.atlassian.net/browse/AP-377)
This commit adds the necessary code for the page to allow a citizen to
identify their regular outgoings.
The previous and next pages do not yet exist so navigation is not fully
implemented here. For this reason no feature tests have been written.
These will need to be addressed when more of the flow is in place.
- add route
- add controller
- add (minimal) navigation
- add view
- add translations
- add tests

Add Identify Types of Outgoing page

---

app/helpers/capital_helper.rb
app/views/citizens/check_answers/index.html.erb
app/views/providers/check_passported_answers/show.html.erb
app/views/shared/_check_answers_assets.html.erb
app/views/shared/check_answers/_one_link_section.html.erb
spec/requests/citizens/check_answers_spec.rb
spec/requests/providers/check_passported_answers_spec.rb

[Jira AP-390](https://dsdmoj.atlassian.net/browse/AP-390)
Modifies the way the capital helpers work so that attributes can be flagged as percentage, and used that facility to fix the fact that second home percentage was being show as currency.

AP-390 Show percentage for second_home_percentage in check answer pages

---

app/assets/stylesheets/providers/legal_aid_applications.scss
app/controllers/providers/statement_of_cases_controller.rb
app/models/pdf_file.rb
app/services/pdf_converter.rb
app/views/providers/statement_of_cases/_uploaded_files.html.erb
app/views/providers/statement_of_cases/show.html.erb
config/routes.rb
spec/requests/providers/statement_of_case_spec.rb
spec/services/pdf_converter_spec.rb

[Jira AP-367](https://dsdmoj.atlassian.net/browse/AP-367)
- Add an destroy action to the Statement of Case controller. 
- Adds a form to each file in the original files list - that on submission submits the current original file id to the destroy action
- Restyles the submit buttons to look like links
- Moves the start of the form on the show page - so that the destroy forms are not nested within the main page forms.

AP-367 Add destroy uploaded file action to statement of case

---

app/controllers/admin/legal_aid_applications_controller.rb
app/views/admin/legal_aid_applications/_legal_aid_applications.html.erb
config/locales/en/admin.yml
config/routes.rb
spec/requests/admin/legal_aid_applications_spec.rb

[AP-371](https://dsdmoj.atlassian.net/browse/AP-371)
Enhance existing admin functionality to allow a user to delete an single record.
- amend view to add a delete button at the end of each row
- add a translation for the button name
- add controller functionality to delete a single application
- add a route
- add tests
It is possible to have a `legal_aid_application` without an `applicant` (if a user starts an application but aborts before saving the client's details). The controller checks if an `applicant` is present and if so destroys it. This cascades so that all related data is deleted. If an `applicant` is not present then the `legal_aid_application` is instead destroyed, also cascading to delete related data.

Delete individual applications using admin account

---

app/views/citizens/identify_types_of_incomes/show.html.erb
config/locales/en/citizens.yml

[Link to story](https://dsdmoj.atlassian.net/browse/AP-417)
Added a hint to the income types page in line with the prototype. The ticket identifies a missing translation but this no longer appears to be an issue as it was resolved by Julien last week.

Added hint for financial help from friends or family

---

app/controllers/citizens/outgoings_summary_controller.rb
app/services/flow/flows/citizen_income.rb
app/views/citizens/outgoings_summary/_add_other_outgoings.html.erb
app/views/citizens/outgoings_summary/_outgoing_type_item.html.erb
app/views/citizens/outgoings_summary/index.html.erb
config/locales/en/citizens.yml
config/locales/en/transaction_types.yml
config/routes.rb
spec/requests/citizens/outgoings_summary_spec.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-379)
Add a new screen to display outgoing payment types selected by the user.
- add controller
- add route
- add view
- add flow
- add translations
- add spec

AP-379 - Create summary of outgoing payment types screen

---

app/controllers/providers/legal_aid_applications_controller.rb
app/controllers/providers/other_assets_controller.rb
app/views/shared/check_answers/_no_link_items.html.erb
features/citizens/citizens.feature
features/citizens/step_definitions/citizens_steps.rb
features/providers/check_your_answers.feature
features/providers/step_definitions/civil_journey_steps.rb
spec/requests/providers/legal_aid_applications_spec.rb

Steps that jumps into a journey by working through a large sequence of previous steps, have been replaced with steps that build the application and associated objects first and then step straight into journey at the appropriate point.
On my system, this PR changed the running time of the `cucumber` command:
Before: real (4 min 16 sec), user (1 min 53 sec)
After: real (2 min 7 sec), user (0 min 56 sec)
So time taken to complete the cucumber tests has been halved.
As the new system uses existing factory traits - there is now some randomness in attribute values. So some feature test that assumed a certain set of attributes are present before the changes made by the specific feature test, have been modified (and some removed). 
The basic assumptions I've used are:
- Feature test should test …

Tech debt: Step into journeys to improve cucumber performance

---

app/views/providers/providers/show.html.erb

[Jira AP-397](https://dsdmoj.atlassian.net/browse/AP397)
Back link behaved differently to other back links in app - and this caused a loop to develop if you clicked back repeatedly.
Fixed by removing page's special behaviour.

AP-397 Fix back link on Provider page

---

app/helpers/application_helper.rb
app/views/layouts/_header.html.erb
config/locales/en/generic.yml

[link to ticket](https://dsdmoj.atlassian.net/secure/RapidBoard.jspa?rapidView=233&projectKey=AP&modal=detail&selectedIssue=AP-398)
I created an application helper method for the menu button ( similar to the existing home_link)
This is because in that method, it returns nothing if there's nothing in the user_header_link
(which should only be visible for providers).

AP-398 Hide Menu button for Citizens

---

helm_deploy/apply-for-legal-aid-uat/templates/deployment.yaml
helm_deploy/apply-for-legal-aid/templates/deployment.yaml

Our main container was stuck in a `CrashLoopBackOff`. Adding a delay to the probes seems to fix the problem

Add delay to container's probes

---

app/controllers/citizens/bank_transactions_controller.rb
app/controllers/citizens/income_summary_controller.rb
app/controllers/citizens/transactions_controller.rb
app/models/bank_transaction.rb
app/models/legal_aid_application.rb
app/views/admin/legal_aid_applications/_legal_aid_applications.html.erb
app/views/citizens/income_summary/_income_type_item.html.erb
app/views/citizens/income_summary/index.html.erb
config/locales/en/citizens.yml
config/routes.rb
features/providers/step_definitions/civil_journey_steps.rb
spec/requests/citizens/bank_transactions_spec.rb
spec/requests/citizens/check_answers_spec.rb
spec/requests/citizens/income_summary_spec.rb

[Jira AP-375](https://dsdmoj.atlassian.net/browse/AP-375)
- Updates model associations so that can easily get from an application to the bank transactions associated with it.
- Adds a scope to get a hash with transaction types as keys, and the array of bank transactions of that type as the values
- Adds a table of selected bank transactions to each transaction type section of `citizens/income_summary`
- Adds an action that disassociates a bank transaction from a transaction type and uses that as an endpoint for "remove" "links" (that are in fact buttons, but look like links)

AP-375 Show selected transaction on summary of income types page

---

helm_deploy/apply-for-legal-aid-uat/templates/network-policy.yaml
helm_deploy/apply-for-legal-aid-uat/templates/service-monitor.yaml

When deploying to UAT, we get the error:
`Error: release apply-for-legal-aid-fix-typo failed: networkpolicies.networking.k8s.io "allow-prometheus-scraping" already exists`.
This is because it is trying to create the same resource simultaneously.
Giving it a dynamic name fixes the problem.
I'm also changing the name of the `ServiceMonitor` because it has the same problem.

fix duplicated NetworkPolicy & ServiceMonitor in UAT

---

app/models/concerns/legal_aid_application_state_machine.rb
spec/requests/citizens/check_answers_spec.rb

I added the letter 's' to details_latest_incident in the state machine. This resolves the issue where the provider can't go to the next step (start of the merits)

Fix typo in state machine

---

app/models/transaction_type.rb
app/views/citizens/identify_types_of_outgoings/show.html.erb
config/locales/en/transaction_types.yml
db/migrate/20190313174812_add_archived_at_to_transaction_types.rb
db/schema.rb
spec/models/transaction_type_spec.rb
spec/requests/citizens/outgoings_summary_spec.rb

[AP-426](https://dsdmoj.atlassian.net/browse/AP-426)
Changes to the 'identify types of outgoing' and 'outgoings summary' screens:
- The main change is the removal of council tax as a category (I've added an `archived_at` column to the `transaction_types` table in the database to facilitate this)
- There are also a couple of minor wording changes and the addition of a hint

Ap 426 remove council tax

---

app/views/citizens/income_summary/index.html.erb
config/locales/en/citizens.yml
features/citizens/citizens.feature
features/providers/step_definitions/civil_journey_steps.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-421)
The wording of the link to the transactions page is currently identical
for each transaction type. This will give each link a unique wording
related to the transaction type.
- add link wordings to locales file
- amend view to use new wordings
- minor changes to feature tests to accommodate these changes

Rename links on income summary page

---

helm_deploy/prometheus-alerts.yaml

[AP-74](https://dsdmoj.atlassian.net/browse/AP-74)
This PR is to add some explanation about Promotheus alerts.
But it doesn't change anything about our infrastructure because the alerts are to be set manually with  the `kubectl` command

Add info about prometheus alerts

---

app/controllers/providers/start_merits_assessments_controller.rb
app/models/concerns/legal_aid_application_state_machine.rb
app/services/flow/flows/provider_capital.rb
app/services/flow/flows/provider_merits.rb
app/views/providers/start_merits_assessments/show.html.erb
config/locales/en/providers.yml
config/routes.rb
features/providers/civil_application_journey.feature
spec/requests/citizens/check_answers_spec.rb
spec/requests/providers/start_merits_assessments_spec.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-434)
Create screen at start of merits flow to inform provider of the
information they will need to enter.
- add controller and route
- add view
- amend flows
- add text to locale file
- create spec
- amend feature test

Add merits start page

---

helm_deploy/apply-for-legal-aid/templates/network-policy.yaml
helm_deploy/apply-for-legal-aid/templates/service-monitor.yaml

The nightly staging deploy job failed with: 
`Error: UPGRADE FAILED: no NetworkPolicy with the name "apply-for-legal-aid" found`
I ran the command on my computer and reproduced the error.
I think there is a conflict of names between resources.
I tried using `{{ template "apply-for-legal-aid.fullname" . }}` like for the other resources (Deployment, Ingress, Secret, Service) but got the same error.
`{{ .Release.Name }}-netpol` works and it makes sense in my opinion (`netpol` is the shortname for `NetworkPolicy`. See `kubectl api-resources`).
I'm also changing the name of the service monitor resource to follow the same pattern.
I ran several times the staging deploy command from my computer and it now works.

FIX: failed deployment because of NetworkPolicy name

---

app/views/providers/address_selections/show.html.erb
app/views/shared/page_templates/_form_page_template.html.erb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-399)
Fixed issue where the address selection field extended beyond the window on mobile devices.
Remove unnecessary divs to match govuk styling requirements

AP-399 Fix address field width for mobile devices

---

app/assets/javascripts/bank_transactions.es6
app/controllers/citizens/bank_transactions_controller.rb
app/views/citizens/income_summary/_income_type_item.html.erb
config/routes.rb
spec/requests/citizens/bank_transactions_spec.rb
spec/requests/citizens/income_summary_spec.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-386)
Use javascript to allow a user to remove bank transactions that they have identified as income without refreshing the screen.
- Adds 'remote: true' to the partial that generates the 'Remove' link to so that an ajax request is send when clicked.
- Adds a javascript file to handle the ajax response and remove the appropriate row of the table.
- Corrects a typo in 'remove_transaction_type'.

Ap 386 remove transactions without reload

---

app/controllers/admin/settings_controller.rb
app/forms/settings/setting_form.rb
app/models/legal_aid_application.rb
app/models/setting.rb
app/services/true_layer/api_client_mock.rb
app/services/true_layer/bank_data_import_service.rb
app/services/true_layer/sample_data.rb
app/views/admin/legal_aid_applications/index.html.erb
app/views/admin/settings/show.html.erb
config/locales/en/admin.yml
config/locales/en/helpers.yml
config/routes.rb
db/migrate/20190319145411_create_settings.rb
db/schema.rb
spec/requests/admin/legal_aid_applications_spec.rb
spec/requests/admin/settings_spec.rb
spec/services/true_layer/api_client_mock.rb
spec/services/true_layer/api_client_spec.rb
spec/services/true_layer/bank_data_import_service_spec.rb

[AP-436](https://dsdmoj.atlassian.net/browse/AP-436)
- Added a settings page
- Added a link to it in the admin page
- Added a "Mock TrueLayer Data" to the settings page.
- Modify the TrueLayer API client so if the flag above is turned on, the sample data is used.
Settings page:

AP-436 Use sample bank transactions instead of TrueLayers' data

---

app/assets/stylesheets/helpers.scss
app/views/providers/providers/show.html.erb
spec/requests/providers/providers_spec.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-413)
The 'role' field on the provider profile page can contain a long list of roles which does not currently wrap.
This commit adds a css class to force the text to wrap. It also changes the way the comma-separated list of roles is displayed by adding a space after each comma, which will prevent the list wrapping mid-word.

AP-413 Add styling to wrap text on provider profile

---

app/helpers/gov_uk_form_helper.rb
app/lib/govuk_elements_form_builder/form_builder.rb
app/views/providers/applicants/show.html.erb
app/views/shared/forms/_date_input_fields.html.erb
config/locales/en/forms.yml
config/locales/en/helpers.yml
config/locales/en/providers.yml

[Link to story](https://dsdmoj.atlassian.net/browse/AP-428)
Created a helper for input labels in govuk style and applied it to the relevant fields
amend input widths
Remove unused translations

AP-428 Update client details page inputs and text styling

---

app/controllers/providers/application_confirmations_controller.rb
app/controllers/providers/check_provider_answers_controller.rb
app/helpers/check_answers_helper.rb
app/models/legal_aid_application.rb
app/views/providers/check_provider_answers/index.html.erb
app/views/shared/check_answers/_item.html.erb
app/views/shared/page_templates/_default_page_template.html.erb
config/locales/en/generic.yml
features/providers/check_your_answers.feature
features/providers/step_definitions/civil_journey_steps.rb
spec/models/legal_aid_application_spec.rb
spec/requests/providers/check_provider_answers_spec.rb
spec/support/common_methods.rb

Ap 296 Check Your Answers page is Read Only for applications that are provider_submitted.
[Link to story](https://dsdmoj.atlassian.net/secure/RapidBoard.jspa?rapidView=233&projectKey=AP&modal=detail&selectedIssue=AP-296)
I created read_only variable in the controller which is true when the state is provider_submitted. This means that the check your answers page for provider can be read only on the condition that the application is submitted.
Also, When a provider clicks link 'View' on an application that has state provider_submitted, they'll be directed to the read only version of the check your answers page. 
Created a helper method for getting the html value of a button.
Updated the provider_step when the provider submits an application and is on the application_confirmation page, so …

AP-296 Check Your Answer is Read Only for submitted applicant

---

config/initializers/hosting_environment.rb
lib/hosting_environment.rb
spec/lib/hosting_environment_spec.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-468)
Created a HostingEnvironment class to determine which environment we're running in.
Within this class, there is the .env class method to return the environment name in symbol format.
Also, created methods: test?, development?, uat?, staging? and live? that return true if it's in said environment.
A runtime error is set off if the environment url is unknown.
Lastly, created tests.

AP-468 HostingEnvironment class to determine where we are running

---

app/services/flow/flows/provider_merits.rb
app/views/providers/check_merits_answers/show.html.erb
features/providers/civil_application_journey.feature
features/providers/step_definitions/civil_journey_steps.rb
spec/requests/citizens/check_answers_spec.rb
spec/requests/providers/check_merits_answers_spec.rb
spec/requests/providers/respondents_spec.rb

Merits-Assessment-Flow is correct to current requirements
[Link to story](https://dsdmoj.atlassian.net/secure/RapidBoard.jspa?rapidView=233&projectKey=AP&modal=detail&selectedIssue=AP-392)
- Skip over two pages in the provider merits flow for passported and non-passported applications. This is because these pages are not needed now but could be used in the future for certain proceeding types. The pages are  proceedings_before_the_courts  and client_received_legal_helps.
- Remove the mentions of client has not received legal help and proceedings before the courts in the check merits answers page.
- Created tests for Merits-Assessment-Flow to check that the flow is correct and updated tests to not include proceedings_before_the_courts  and client_received_legal_helps pages.
Before you ask …

AP-392 Merits-Assessment-Flow

---

app/views/providers/about_the_financial_assessments/show.html.erb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-459)
Removed the containing div from the `<form>` element.  Buttons are now aligned as needed.  Shown to Simon and approved.

AP-459 button alignment

---

app/views/providers/check_passported_answers/show.html.erb
features/providers/civil_application_journey.feature

[Link to story](https://dsdmoj.atlassian.net/browse/AP-462)
Changed text of submit button to continue button on check_passported_answers

AP-462 Changed text of button

---

app/services/flow/flows/provider_start.rb
spec/helpers/providers_helper_spec.rb

[AP-489](https://dsdmoj.atlassian.net/browse/AP-489)
Fixing this error: https://sentry.service.dsd.io/mojds/apply-for-legal-aid-staging/issues/35319/
This bug happens when you leave the application at the manual address input stage.
Then, when accessing the list of applications, it crashes because the path for the `:addresses` step is not defined
- Adding the path for the `:addresses` step
- Adding a unit test to make sure the paths of all steps are always present

AP-489 Add path for :address and add unit tests to make sure all paths are always present

---

app/assets/stylesheets/govuk-mods.scss
app/controllers/citizens/means_test_results_controller.rb
app/views/citizens/means_test_results/show.html.erb
app/views/providers/application_confirmations/show.html.erb
config/locales/en/citizens.yml
config/routes.rb
spec/requests/citizens/means_test_results_spec.rb

[Jira AP-471](https://dsdmoj.atlassian.net/browse/AP-471)
Adds a new page to the Citizen journey - Means Test Result.
Prototype page is here: https://apply-for-legal-aid-prototype.herokuapp.com/apply_for_legal_aid_prototype/citizen_means_calculation
Currently this page stands alone as the page that leads to it is not yet in master. See https://github.com/ministryofjustice/laa-apply-for-legal-aid/pull/420

AP-471 Applicant Means Test Result

---

Gemfile
Gemfile.lock
app/assets/stylesheets/pagination.scss
app/controllers/providers/legal_aid_applications_controller.rb
app/helpers/pagination_helper.rb
app/views/providers/legal_aid_applications/_legal_aid_applications.html.erb
app/views/providers/legal_aid_applications/index.html.erb
config/initializers/pagy.rb
config/locales/en/model_enum_translations.yml
config/locales/en/pagy.yml
spec/requests/providers/legal_aid_applications_spec.rb

[Jira AP-467](https://dsdmoj.atlassian.net/browse/AP-467)
Adds pagination to the providers page using the [Pagy gem](https://github.com/ddnexus/pagy).
I've got everything working as defined in the spec, except on page 4 the links look like:
After that (page 5 onwards) they match the spec:

AP-467 Add pagination to providers home page

---

app/views/citizens/check_answers/index.html.erb
config/locales/en/citizens.yml

* Reword text to remove reference to 30 days of transactions - changed in translation.
* Remove copy about merits assessments as this doesn't apply to citizens - removed from view and translation. 

Minor copy changes

---

app/services/address_lookup_service.rb
features/cassettes/Civil_application_journeys/Completes_the_application_using_address_lookup.yml
features/cassettes/Civil_application_journeys/Completes_the_application_using_manual_address.yml
features/cassettes/Civil_application_journeys/I_am_able_to_clear_proceeding_on_the_proceeding_page.yml
features/cassettes/Civil_application_journeys/I_am_able_to_select_and_delete_proceeding_types.yml
features/cassettes/Civil_application_journeys/I_can_see_that_the_applicant_does_not_receive_benefits.yml
features/cassettes/Civil_application_journeys/I_can_see_that_the_applicant_receives_benefits.yml
features/cassettes/Civil_application_journeys/I_want_to_change_address_from_the_check_your_answers_page.yml
features/cassettes/Civil_application_journeys/I_want_to_change_address_manually_from_the_check_your_answers_page.yml
features/cassettes/Civil_application_journeys/I_want_to_return_to_check_your_answers_from_address_select.yml
features/cassettes/Civil_application_journeys/No_results_returned_is_seen_on_screen_when_invalid_proceeding_search_entered.yml
spec/cassettes/address_selections_requests/GET_/providers/applications/_legal_aid_application_id/address_selections/edit/when_the_provider_is_authenticated/a_postcode_have_been_entered_before/but_the_lookup_does_not_return_any_valid_results/renders_the_manual_address_selection_page.yml
spec/cassettes/address_selections_requests/GET_/providers/applications/_legal_aid_application_id/address_selections/edit/when_the_provider_is_authenticated/a_postcode_have_been_entered_before/performs_an_address_lookup_with_the_provided_postcode.yml
spec/cassettes/address_selections_requests/GET_/providers/applications/_legal_aid_application_id/address_selections/edit/when_the_provider_is_authenticated/a_postcode_have_been_entered_before/renders_the_address_selection_page.yml
spec/cassettes/providers_legal_aid_application_proceedings_type_requests/index_GET_/providers/applications/_legal_aid_application_id/proceedings_types/when_the_provider_is_authenticated/back_link/the_applicant_s_address_used_s_address_lookup_service/should_redirect_to_the_address_lookup_page.yml
spec/services/address_lookup_service_spec.rb

Currently a welsh postcode will return the address with Welsh language place names
[Link to story](https://dsdmoj.atlassian.net/browse/AP-486)
Added a language parameter to the request to specify 'EN' for english language spellings.

AP-486 Specify english language for welsh addresses

---

app/controllers/application_controller.rb
app/controllers/citizens/legal_aid_applications_controller.rb
app/controllers/errors_controller.rb
app/views/errors/show.html.erb
app/views/errors/show/_assessment_already_completed.html.erb
app/views/errors/show/_link_expired.html.erb
app/views/errors/show/_page_not_found.html.erb
config/locales/en/errors.yml
config/routes.rb
spec/requests/citizens/legal_aid_applications_spec.rb
spec/requests/citizens/restrictions_spec.rb
spec/requests/errors_spec.rb
spec/requests/providers/restrictions_spec.rb

[Jira AP-449](https://dsdmoj.atlassian.net/browse/AP-449)
Adds an **errors** controller and uses it to display errors for "page not found", "assessment already completed" and "link expired".
Then uses error pages as endpoints for errors at start of Citizen journey.

AP-449 Add applicant error pages for when link does not work

---

app/helpers/page_template_helper.rb
app/views/admin/settings/show.html.erb
app/views/providers/applicants/show.html.erb
app/views/shared/page_templates/_default_page_template.html.erb

[Jira AP-482](https://dsdmoj.atlassian.net/browse/AP-482)
Corrects some errors in the mark up of the providers/applicant page.
- Modified the page template so that the margin below the heading can be set easily. Using the form page template results in a 15px margin below the heading, whereas the default page template heading has 30px below the head.
- Put the applicant name fields within a fieldset and put the legend within a legend tag rather than a span, and again within the new fieldset.
- Removed the duplication of the class "govuk-input" within the name input fields.
- Used the `govuk_text_field` `label` option to add a correctly format label *within the form group* which then allowed me to remove the labels that were rendering outside the form group.
When I started this I thought I …

AP-482 Fix markup issues in providers/applicant

---

app/controllers/citizens/identify_types_of_incomes_controller.rb
app/controllers/citizens/identify_types_of_outgoings_controller.rb
app/models/legal_aid_application_transaction_type.rb
spec/requests/citizens/identify_types_of_incomes_spec.rb
spec/requests/citizens/identify_types_of_outgoings_spec.rb

[Jira AP-457](https://dsdmoj.atlassian.net/browse/AP-457)
The cause of the bug:
If you do this
```ruby
selected_ids = [1,2,3]
legal_aid_application.update!(transaction_type_ids: selected_ids)
```
That removes all existing association between the legal aid application and transaction types, as well as apply the new associations. So each update to associate one type (debit or credit) of transaction type was wiping the associations with the other transaction type.
The solution is a little more verbose, but ensures that only the correct transaction types are modified.

AP-457 Fix issue with wrong transaction types being deleted by update

---

app/views/shared/forms/_savings_and_investments_form.html.erb

HTML structure for tickboxes.
The tickboxes in page _**savings_and_investment**_ were not wrapped in a form group.  

AP-461 - HTML structure for tickboxes

---

helm_deploy/grafana-dashboards/nginx-errors.yaml
helm_deploy/prometheus-alerts.yaml

[Link to story](https://dsdmoj.atlassian.net/browse/AP-435)
- Add a new Grafana dashboard to display any HTTP 500 errors triggered by nginx/ingress. The dashboard is here: https://grafana.apps.cloud-platform-live-0.k8s.integration.dsd.io/d/147f7f8a4e81465bb8727edd1548b87ab0230a0c/laa-apply-http-5xx-nginx-ingress-errors
- Add a Prometheus alert that will post to the appropriate Slack channel when any HTTP 500 error is triggered by nginx/ingress.

AP-435 monitoring 500 status codes

---

app/views/providers/details_latest_incidents/show.html.erb
config/locales/en/activemodel.yml
config/locales/en/providers.yml
config/locales/en/shared.yml
features/providers/civil_application_journey.feature

[Link to story](https://dsdmoj.atlassian.net/browse/AP-554)
I just had to change the copy because even though the copy was about "date your client contacted you the incident", the model attribute was already called `occurred_on`

AP-554 Change copy on details_latest_incident page

---

app/views/citizens/identify_types_of_outgoings/show.html.erb
config/locales/en/citizens.yml
config/locales/en/transaction_types.yml

[Link to story](https://dsdmoj.atlassian.net/browse/AP-494)
Update copy and order of transaction type on the `/citizens/identify_types_of_outgoing` page

AP-494 Update copy of outgoing types

---

spec/spec_helper.rb

Builds are currently failing on CircleCI as the version of
chromedriver we are using (74.0.3729.6) is not compatible with the
version of chrome that runs on CircleCI (72.0.3626.121-1).
This change will force chromedriver to version 2.46, which does support
v72 of chrome.
This probably isn't a long term solution but as there is already an existing
story to remove chromedriver [(AP-523)](https://dsdmoj.atlassian.net/browse/AP-523) this should work as an interim 
solution to allow builds to pass.

Force version of chromedriver used

---

app/helpers/gov_uk_form_helper.rb
app/lib/govuk_elements_form_builder/form_builder.rb
app/views/citizens/additional_accounts/index.html.erb
app/views/citizens/additional_accounts/new.html.erb
app/views/citizens/shared_ownerships/show.html.erb
app/views/providers/client_received_legal_helps/show.html.erb
app/views/providers/proceedings_before_the_courts/show.html.erb
app/views/shared/forms/_shared_ownership_form.html.erb
app/views/shared/forms/_success_prospect_form.html.erb
config/locales/en/citizens.yml
config/locales/en/helpers.yml

[Link to story](https://dsdmoj.atlassian.net/browse/AP-458)
In order to improve the layout of pages that contain vertically-aligned radio buttons, amend form_builder so that padding is added above the radio buttons. The padding is not added if the radio buttons are inline.

AP-458 - Add padding between page titles and radio buttons

---

app/controllers/citizens/legal_aid_applications_controller.rb
app/controllers/citizens/resend_link_requests_controller.rb
app/mailers/concerns/notify_template_methods.rb
app/mailers/feedback_mailer.rb
app/mailers/notify_mailer.rb
app/mailers/resend_link_request_mailer.rb
app/models/legal_aid_application.rb
app/services/secure_application_finder.rb
app/views/citizens/resend_link_requests/show.html.erb
app/views/citizens/resend_link_requests/update.html.erb
app/views/errors/show/_link_expired.html.erb
config/application.rb
config/govuk_notify_templates.yml
config/initializers/date_formats.rb
config/initializers/gov_uk_notify.rb
config/locales/en/citizens.yml
config/locales/en/errors.yml
config/routes.rb
spec/mailers/resend_link_request_mailer_spec.rb
spec/models/legal_aid_application_spec.rb
spec/requests/citizens/legal_aid_applications_spec.rb
spec/requests/citizens/resend_link_requests_spec.rb
spec/requests/errors_spec.rb
spec/services/secure_application_finder_spec.rb

[JIRA AP-532](https://dsdmoj.atlassian.net/browse/AP-532)
This PR changes the response to someone trying to start the Citizen journey with an expired link. They are now sent to a page where they are prompted to send a request for a new link.
- A refactor of the existing mailer so that I could reuse code in the a new mailer.
- Change the citizens/legal_aid_applications_controller response to an expired request to redirect to a new end point.
- Removed the error/link_expired endpoint as it is now redundant
- Moved the `LegalAidApplication.find_by_secure_id!` functionality to a service so that I could reuse the functionality a little more easily.
- Created `Citizens::ResendLinkRequestsController` with `show` and `update` actions to handle the new request link functionality. 
- Created …

AP 532 Applicant needs new link notification

---

.circleci/config.yml

For the last couple of days CircleCI builds have been failing with this error when installing packages:
To fix it, I've added an extra step to the build process to run `sudo apt-get update` before running any installs.

Run sudo apt-get update as part of build

---

.rubocop.yml
Gemfile
Gemfile.lock

Performance Cops have been removed from RuboCop 0.68, which we upgraded to earlier. As a result of this a number of warnings are now thrown when `rubocop` and `erblint` run.
eg.
Following the recommendations here
this PR installs `rubocop-performance` to maintain the level of `rubocop` coverage we had before.

Install rubocop-performance gem

---

app/lib/prometheus_collectors/collectors.rb
app/lib/prometheus_collectors/sidekiq_queue_collector.rb
app/services/metrics/send_metrics.rb
app/services/metrics/sidekiq_queue_sizes.rb
config/application.rb
config/initializers/prometheus_metrics.rb
config/initializers/sidekiq.rb
helm_deploy/apply-for-legal-aid/templates/_envs.tpl
helm_deploy/apply-for-legal-aid/templates/_helpers.tpl
helm_deploy/apply-for-legal-aid/templates/deployment_metrics.yaml
helm_deploy/apply-for-legal-aid/templates/deployment_web.yaml
helm_deploy/apply-for-legal-aid/templates/metrics-cronjob.yaml
helm_deploy/prometheus-alerts.yaml
lib/tasks/send_metrics_to_prometheus.rake
spec/lib/prometheus_collectors/sidekiq_queue_collector_spec.rb
spec/services/metrics/send_metrics_spec.rb
spec/services/metrics/sidekiq_queue_sizes_spec.rb

[AP-409](https://dsdmoj.atlassian.net/browse/AP-409)
- creating `SidekiqQueueCollector`. It is started on the `metrics` container, collect metrics from the job and send them to prometheus.
- creating `SidekiqQueueSizes`. It collects sidekiq queue sizes and send them to the collector above
- creating a kubernetes cron-job. It will run `SidekiqQueueSizes` every minute. (Or every hour in UAT). I tried running it every minute in UAT and it runs OK but it will be too much when we have several UAT envs with a job for each
- moving the `metrics` container to its own pod so it can be used by all pods and it's best practice to have only one container per pod as much as possible
- creating a prometheus alert. It triggers if total size of all queues is more than 10 or if that metric is absent
In …

Ap 409 monitor sidekiq

---

helm_deploy/apply-for-legal-aid/templates/deployment_metrics.yaml

When creating this PR https://github.com/ministryofjustice/laa-apply-for-legal-aid/pull/437
I moved the `metrics` container to its own pod and accidentally used the wrong value for the number of replicas.
`{{ .Values.worker.replicaCount }}` is **2** in staging and production but I think **1** is enough.

Fix number of replicas for the metrics container

---

app/services/flow/flows/provider_merits.rb
app/views/providers/check_merits_answers/show.html.erb
app/views/providers/shared_ownerships/show.html.erb
features/providers/civil_application_journey.feature
spec/requests/providers/check_merits_answers_spec.rb
spec/requests/providers/statement_of_case_spec.rb

Remove Estimated Legal Costs From Merits Flow and the check answers page
[Link to story](https://dsdmoj.atlassian.net/secure/RapidBoard.jspa?rapidView=233&projectKey=AP&modal=detail&selectedIssue=AP-562)
1. Remove Estimated Legal Costs From Merits Flow and the check answers page
2. Amend tests
- Fix bug for shared_ownership page where there is a duplicate title on a passported application.

Ap 562 Remove Estimated Legal Costs From Merits Flow

---

app/assets/stylesheets/narrow-table-display.scss
app/assets/stylesheets/width-style-correction.scss
app/views/providers/transactions/show.html.erb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-455)
Added new HTML with the column 3 title and new classes. 
Added new CSS for narrow displays.
Added new CSS to remove padding that affects narrow displays.
Added new CSS to control white-space wrapping for "select all".

New Style and HTML for narrow tables

---

spec/factories/bank_transactions.rb

Some tests are failing whenever the `happened_at` happens to be just outside the filter used on the `legal_aid_application.bank_transactions ` method : 
```ruby
def bank_transactions
return applicant.bank_transactions if Setting.mock_true_layer_data?
set_transaction_period unless transaction_period_start_at? && transaction_period_finish_at?
applicant.bank_transactions.where(
happened_at: transaction_period_start_at..transaction_period_finish_at
)
end
def set_transaction_period
update!(
transaction_period_start_at: 3.months.ago.beginning_of_day,
transaction_period_finish_at: Time.now.beginning_of_day
)
end
```

Fix sporadically failing test

---

.circleci/config.yml

Nightly deployments to staging are failing as CircleCI cannot find the correct versions of packages to install. This is the same issue that was partially fixed here https://github.com/ministryofjustice/laa-apply-for-legal-aid/pull/485. The change made there doesn't affect the `clean_up_ecr` job, so this change pulls the `sudo apt-get update` command into a separate process which is now run run by both jobs.

Run sudo apt-get update during nightly deploys

---

app/assets/javascripts/respondent_detail.es6
app/views/providers/respondents/_respondent_detail.html.erb
app/views/providers/respondents/show.html.erb
config/locales/en/providers.yml

Bail conditions content on /respondent page 
For the question 'Have bail conditions been set?' on the respondent page, the label for its text area should change depending on whether the user selects yes or no as an answer to this question.
[Link to story](https://dsdmoj.atlassian.net/secure/RapidBoard.jspa?rapidView=233&projectKey=AP&modal=detail&selectedIssue=AP-531)
1. Added custom data attributes to store the two labels for Bail conditions. 
2. Using JavaScript in the front-end to change the label depending on the option selected for bail_conditions_set ('yes', 'no').
3. Update the error text and the error summary list depending on the label.

AP531 Bail conditions content on /respondent page

---

bin/uat_deploy

In UAT, the name of the release can be too long depending on the length of the name of the branch.
i.e. : https://circleci.com/gh/ministryofjustice/laa-apply-for-legal-aid/5190
We can easily fix that by replacing `apply-for-legal-aid` at the beginning with `apply`.
But it stays `apply-for-legal-aid` in staging and production

Reducing size of release name in UAT

---

app/controllers/feedback_controller.rb
app/controllers/providers/legal_aid_applications_controller.rb
app/helpers/providers_helper.rb
app/mailers/feedback_mailer.rb
app/mailers/notify_mailer.rb
app/mailers/resend_link_request_mailer.rb
app/services/citizen_email_service.rb
app/services/flow/base_flow_service.rb
app/services/flow/flow_error.rb
app/services/flow/flows/provider_start.rb
app/services/flow/key_point.rb
spec/requests/feedbacks_spec.rb
spec/requests/providers/legal_aid_applications_spec.rb
spec/services/citizen_email_service_spec.rb

[JIRA AP-587](https://dsdmoj.atlassian.net/browse/AP-587)
This PR addresses 2 issues.
There were two things preventing Sidekiq handling failed email sends:
1. When mail send was being retried, Sidekiq was not finding the module `NotifyTemplateMethods` that was mixed into the mailers. Adding a `require_relative` pointing at the module file fixed that.
2. The mailer method `deliver_later` was not raising errors on connection failure. Changing this to the bang version fixed that: `deliver_later!`
With these changes in place when I disconnected my computer from the network and triggered a client journey start email, it was held in Sidekiq and retried until the connection was re-enabled.
While working on this bug I found another bug that I've also fixed here. If the code base changed so that a …

AP 587 Retry failed email notifications

---

Gemfile
Gemfile.lock
features/support/env.rb
spec/spec_helper.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-523)
Replace deprecated gem `chromedriver-helper` with `webdrivers`

AP-523 Replace deprecated chrome drive gem

---

app/models/ccms/submission.rb
app/services/ccms/add_applicant_service.rb
app/services/ccms/applicant_add_status_requestor.rb
app/services/ccms/applicant_add_status_response_parser.rb
app/services/ccms/check_applicant_status_service.rb
db/migrate/20190514142921_add_applicant_add_tx_id_to_ccms_submissions.rb
db/migrate/20190514212618_add_poll_count_to_ccms_submissions.rb
db/schema.rb
spec/data/ccms/applicant_add_status_response.xml
spec/factories/submissions.rb
spec/models/ccms/submission_spec.rb
spec/services/ccms/add_applicant_service_spec.rb
spec/services/ccms/applicant_add_status_requestor_spec.rb
spec/services/ccms/applicant_add_status_response_parser_spec.rb
spec/services/ccms/check_applicant_status_service_spec.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-576)
This change adds functionality to the CCMS orchestration process to poll the status of the creation of an applicant in CCMS. It:
- amends the add_applicant_service so that the transaction_id sent in the add request is recorded against the submission, so that it can be included in the poll request
- adds a poll count to the submission record which is incremented for each poll. An error is thrown when a limit (10) is reached
- adds a new check_applicant_status_service to handle the call to CCMS and process the response
- fixes minor issues with existing tests/test data

AP-576 - CCMS -Poll add_applicant requests

---

app/assets/javascripts/checkbox_control.es6
app/controllers/citizens/identify_types_of_outgoings_controller.rb
app/views/citizens/identify_types_of_outgoings/show.html.erb
config/locales/en/citizens.yml
features/citizens/citizens.feature
spec/requests/citizens/identify_types_of_outgoings_spec.rb

[AP-570](https://dsdmoj.atlassian.net/browse/AP-570)
This adds a None Selected checkbox to the Update Types of Payments Page in the Citizen Journey.
99% is copied from Rob's PR: https://github.com/ministryofjustice/laa-apply-for-legal-aid/pull/508

AP-570 Update types of payments pages

---

app/services/ccms/applicant_add_requestor.rb
app/services/ccms/applicant_add_status_requestor.rb
app/services/ccms/applicant_search_requestor.rb
app/services/ccms/base_requestor.rb
app/services/ccms/case_add_requestor.rb
app/services/ccms/case_add_status_requestor.rb
app/services/ccms/reference_data_requestor.rb
spec/services/ccms/applicant_add_requestor_spec.rb

A refactor to address:
- Remove the loading of `soap_client` from the initialization method. This was leading to `super()` having to be called unnecessarily in child classes of `BaseRequestor`.
- Set WSDL file and namespace definition at the class level, so that is done once on app load instead of every time an instance is created. I've also simplified the WSDL config so that all that needs to be defined in each child class is the file name, and `BaseRequestor` can be left to identify the storage location.

Small CCMS refactor to remove initialize overload

---

app/models/ccms/submission.rb
app/services/ccms/add_applicant_service.rb
app/services/ccms/add_case_service.rb
app/services/ccms/applicant_add_response_parser.rb
app/services/ccms/applicant_add_status_response_parser.rb
app/services/ccms/applicant_search_response_parser.rb
app/services/ccms/base_response_parser.rb
app/services/ccms/base_submission_service.rb
app/services/ccms/case_add_response_parser.rb
app/services/ccms/case_add_status_response_parser.rb
app/services/ccms/check_applicant_status_service.rb
app/services/ccms/obtain_applicant_reference_service.rb
app/services/ccms/obtain_case_reference_service.rb
app/services/ccms/reference_data_response_parser.rb
db/migrate/20190515141352_add_case_add_tx_id_to_ccms_submissions.rb
db/schema.rb
spec/factories/submissions.rb
spec/models/ccms/submission_spec.rb
spec/services/ccms/add_applicant_service_spec.rb
spec/services/ccms/add_case_service_spec.rb
spec/services/ccms/applicant_add_response_parser_spec.rb
spec/services/ccms/applicant_add_status_response_parser_spec.rb
spec/services/ccms/applicant_search_response_parser_spec.rb
spec/services/ccms/case_add_response_parser_spec.rb
spec/services/ccms/case_add_status_response_parser_spec.rb
spec/services/ccms/check_applicant_status_service_spec.rb
spec/services/ccms/obtain_applicant_reference_service_spec.rb
spec/services/ccms/obtain_case_reference_service_spec.rb
spec/services/ccms/reference_data_response_parser_spec.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-577)
Add functionality to submission.process! for submissions in the
applicant_ref_obtained state:
- additions to existing submission model and spec
- new field to store the case_add_transaction_id in the database so it
can be used for polling later
- new add_case service to handle api call and response parsing

AP-577 - CCMS Add Case Orchestration

---

app/services/ccms/document_id_requestor.rb
app/services/ccms/document_id_response_parser.rb
app/services/ccms/document_upload_requestor.rb
app/services/ccms/document_upload_response_parser.rb
app/services/ccms/wsdls/DocumentServicesWsdl.xml
spec/data/ccms/document_id_request.xml
spec/data/ccms/document_id_response.xml
spec/data/ccms/document_upload_request.xml
spec/data/ccms/document_upload_response.xml
spec/services/ccms/document_id_requestor_spec.rb
spec/services/ccms/document_id_response_parser_spec.rb
spec/services/ccms/document_upload_requestor_spec.rb
spec/services/ccms/document_upload_response_parser_spec.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-613)
To upload documents for an application (eg statements of case) into CCMS, two calls to CCMS webservices are required:
1. to 'register' the document and receive a document_id
2. to upload a base64 encoded version of the file
This PR creates _requester and _response_parser classes to handle these two calls, based on the pattern used for other API calls to CCMS.
It also adds test data and the WSDL which is the basis of the request.

AP-613 - CCMS document upload requestors and parsers

---

app/controllers/providers/identify_types_of_outgoings_controller.rb
app/services/flow/flows/provider_capital.rb
app/views/citizens/identify_types_of_outgoings/show.html.erb
app/views/providers/identify_types_of_outgoings/show.html.erb
app/views/providers/outgoings_summary/_add_other_outgoings.erb
app/views/shared/forms/_identify_types_of_outgoings_form.html.erb
config/locales/en/citizens.yml
config/locales/en/providers.yml
config/locales/en/shared.yml
features/providers/complete_and_check_means_answers.feature
features/providers/step_definitions/civil_journey_steps.rb
features/support/steps_helper.rb
spec/requests/providers/identify_types_of_outgoings_spec.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-592)
Implement the **Identify types of outgoings** page on the provider flow.
Move the view to a partial in order to reuse the html from the applicant flow

AP-592 add other type of payment for provider

---

app/controllers/application_controller.rb
app/controllers/concerns/providers/application_dependable.rb
config/routes.rb
spec/requests/errors_spec.rb
spec/requests/providers/about_the_financial_assessments_spec.rb
spec/requests/providers/address_lookups_spec.rb
spec/requests/providers/address_selections_spec.rb
spec/requests/providers/addresses_spec.rb
spec/requests/providers/applicants_spec.rb
spec/requests/providers/application_dependable_spec.rb
spec/requests/providers/check_provider_answers_spec.rb
spec/requests/providers/online_bankings_spec.rb

[AP-586](https://dsdmoj.atlassian.net/browse/AP-586)
This was a little more complicated than I thought. You can't just catch `ActionController::RoutingError` in the controller, because the error occurs before the controller is loaded - a controller instance is created once routing determines which class of controller to use. Instead I had to add a catch all route at the end of the routes (as described [here](https://stackoverflow.com/questions/18359088/custom-error-handling-with-rails-4-0#20508445)).
Also many request specs test for application id not matching. This I think is over-kill as it is basically repeatedly testing the same functionality. So I've removed many of these tests; leaving ones where something else was tested too.

AP-586 Handle 404 errors

---

app/models/ccms/submission.rb
app/models/concerns/ccms_submission_state_machine.rb
app/services/ccms/document_id_requestor.rb
app/services/ccms/document_upload_requestor.rb
app/services/ccms/obtain_document_id_service.rb
db/migrate/20190529090545_add_documents_to_ccms_submissions.rb
db/migrate/20190529164413_add_ccms_document_id_to_pdf_files.rb
db/schema.rb
spec/factories/submissions.rb
spec/models/ccms/submission_spec.rb
spec/services/ccms/obtain_document_id_service_spec.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-579)
Create a new service to register all documents that need to be uploaded
to CCMS for an application and receive a document id in return.
If no documents exist for the application, the status is changed to
completed as at that point all relevant data has been sent to CCMS.

AP-579 - Add service to obtain CCMS document ids

---

app/services/metrics/send_metrics.rb
config/application.rb
config/initializers/prometheus_metrics.rb
helm_deploy/apply-for-legal-aid/templates/_envs.tpl
helm_deploy/apply-for-legal-aid/templates/deployment_metrics.yaml
helm_deploy/apply-for-legal-aid/templates/deployment_web.yaml
helm_deploy/apply-for-legal-aid/templates/service-metrics.yaml
helm_deploy/apply-for-legal-aid/templates/service.yaml
spec/services/metrics/send_metrics_spec.rb

Ruby metrics were not reported since the metrics container was moved to its own pod.
A separate service needed to be created so the web and the worker pods can send metrics to it

Fix ruby metrics

---

app/assets/javascripts/checkbox_control.es6
app/controllers/citizens/other_assets_controller.rb
app/controllers/providers/other_assets_controller.rb
app/forms/citizens/other_assets_form.rb
app/views/citizens/other_assets/show.html.erb
app/views/providers/other_assets/show.html.erb
app/views/shared/forms/other_assets/_form.html.erb
config/locales/en/activemodel.yml
config/locales/en/citizens.yml
config/locales/en/providers.yml
config/locales/en/shared.yml
db/migrate/20190523115648_rename_other_assets_declarations_columns.rb
db/schema.rb
features/citizens/citizens.feature
features/providers/check_your_answers.feature
features/providers/civil_application_journey.feature
spec/factories/other_assets_declarations.rb
spec/forms/citizens/other_assets_form_spec.rb
spec/requests/citizens/other_assets_spec.rb
spec/requests/providers/other_assets_spec.rb

AP572 & AP582 change other assets page for provider and applicant
[Link to provider other assets story](https://dsdmoj.atlassian.net/secure/RapidBoard.jspa?rapidView=233&projectKey=AP&modal=detail&selectedIssue=AP-572)
[Link to applicant other assets story](https://dsdmoj.atlassian.net/secure/RapidBoard.jspa?rapidView=233&projectKey=AP&modal=detail&selectedIssue=AP-582)
- Changed the order of the options and the content as written in the user stories. 
- Added a 'Select all that apply header'
- Updated jewellery_value to valuable_items_value within the app and database (via migration file) as this now takes a total value of valuable items.
-------------------------
- Updated Timeshare name to Timeshare property within the database (via a migration file) and app.
- Added Javascript for the …

AP572 & AP582 change other assets page for provider and applicant

---

app/views/shared/forms/vehicles/_remaining_payment.html.erb
config/locales/en/activemodel.yml

[Link to story](https://dsdmoj.atlassian.net/browse/AP-660)
- Adding missing locales
- Fix this bug: On `remaining_payment` if “Yes” is selected and any error is shown (like for a non-numeric value) the selected answer changes to “No” 

AP-660 Bug fix on vehicles/remaining_payment page

---

app/views/providers/address_selections/show.html.erb
config/locales/en/activemodel.yml
spec/forms/addresses/address_selection_form_spec.rb
spec/requests/providers/address_selections_spec.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-521)
Address drop down was not showing the error styling on the input field. This change applies the GDS error styling requirements to the address selection drop down menu.

ap521 Amend the error validation styling for address selection

---

app/models/ccms/submission.rb
app/models/concerns/ccms_submission_state_machine.rb
app/services/ccms/upload_documents_service.rb
spec/factories/submissions.rb
spec/models/ccms/submission_spec.rb
spec/services/ccms/upload_documents_service_spec.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-581)
Create a new service to upload all documents for an application to CCMS (at this point only Statements of Case).
This does not handle retrying failed uploads, which will be addressed in another story.

AP-581 - Add service to upload documents to CCMS

---

app/assets/stylesheets/long-email-truncation.scss
app/views/shared/_provider_header_link.html.erb
config/initializers/mock_saml.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-601)
New SCSS file with CSS to do the following:
- max-width that prevents email containing field from overlapping with the service title (non-mobile).
- overflow, vertical alignment added to stop other undesirable effects.
- removed Ruby truncation, so that full width is used in mobile displays.

AP-601 Dealing with Long Emails

---

app/models/address.rb
app/services/ccms/applicant_add_requestor.rb
app/services/ccms/applicant_add_status_requestor.rb
app/services/ccms/applicant_search_requestor.rb
app/services/ccms/case_add_requestor.rb
app/services/ccms/case_add_status_requestor.rb
app/services/ccms/document_id_requestor.rb
app/services/ccms/document_upload_requestor.rb
app/services/ccms/reference_data_requestor.rb
spec/services/ccms/applicant_add_requestor_spec.rb
spec/services/ccms/applicant_add_status_requestor_spec.rb
spec/services/ccms/applicant_search_requestor_spec.rb
spec/services/ccms/case_add_requestor_spec.rb
spec/services/ccms/case_add_status_requestor_spec.rb
spec/services/ccms/document_id_requestor_spec.rb
spec/services/ccms/document_upload_requestor_spec.rb
spec/services/ccms/reference_data_requestor_spec.rb

Tidy up CCMS services: 
- remove unused methods
- remove nocov from `call` methods
- add tests for `call` methods, mocking soap calls
- minor naming corrections 
Also improve functionality of `pretty_postcode` method to prevent multiple spaces being added.

Tidy up ccms services

---

app/services/ccms/case_add_status_requestor.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-718)
Change reference to `CaseServiceWsdl.xml` to the correct `CaseServicesWsdl.xml`. Calls to CCMS to create a case will fail without this change.

Fix typo in case create wsdl name

---

app/services/ccms/wsdls/DocumentServicesWsdl.xml

[Link to story](https://dsdmoj.atlassian.net/browse/AP-718)
The WSDL for the api call to upload a document to CCMS is incorrect. Replace it with the correct version of DocumentServicesWsdl.xml.

CCMS: Use correct DocumentServicesWsdl.xml

---

app/controllers/citizens/vehicles_controller.rb
app/controllers/providers/vehicles_controller.rb
app/forms/legal_aid_applications/own_vehicle_form.rb
app/models/legal_aid_application.rb
app/services/flow/flows/citizen_vehicle.rb
app/services/flow/flows/provider_vehicle.rb
app/services/save_applicant_means_answers.rb
app/views/citizens/vehicles/show.html.erb
app/views/providers/vehicles/show.html.erb
app/views/shared/_check_answers_vehicles.html.erb
app/views/shared/forms/vehicles/_own_vehicle.html.erb
config/locales/en/activemodel.yml
config/locales/en/citizens.yml
config/locales/en/helpers.yml
config/locales/en/providers.yml
config/locales/en/shared.yml
config/routes.rb
db/migrate/20190611134522_add_own_vehicle_to_legal_aid_application.rb
db/schema.rb
features/providers/civil_application_journey.feature
spec/factories/legal_aid_applications.rb
spec/requests/citizens/check_answers_spec.rb
spec/requests/citizens/vehicles_spec.rb
spec/requests/providers/check_passported_answers_spec.rb
spec/requests/providers/means_summaries_spec.rb
spec/requests/providers/vehicles_spec.rb
spec/services/save_applicant_means_answers_spec.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-689)
- On the "Do you own a vehicle?" page, prevent "No" from being selected by adding a new attribute and a form
- Save the applicant's vehicle answers at the end of the applicant flow

AP-689 default unselect vehicle radio button

---

app/controllers/providers/substantive_applications_controller.rb
app/controllers/providers/used_delegated_functions_controller.rb
app/forms/base_form.rb
app/forms/concerns/date_field_builder.rb
app/forms/incidents/latest_incident_form.rb
app/forms/legal_aid_applications/used_delegated_functions_form.rb
app/services/flow/flows/provider_start.rb
app/views/providers/used_delegated_functions/show.html.erb
app/views/shared/forms/vehicles/_remaining_payment.html.erb
config/locales/en/activemodel.yml
config/locales/en/providers.yml
config/routes.rb
db/migrate/20190611120953_add_used_delegated_functions_on_to_legal_aid_applications.rb
db/schema.rb
features/providers/civil_application_journey.feature
spec/forms/concerns/date_field_builder_spec.rb
spec/forms/incidents/latest_incident_form_spec.rb
spec/forms/legal_aid_applications/used_delegated_functions_form_spec.rb
spec/requests/providers/check_benefits_spec.rb
spec/requests/providers/used_delegated_functions_spec.rb

[Jira AP-662](https://dsdmoj.atlassian.net/browse/AP-662)
This adds a page for the provider to input whether they used Delegated Functions, and if so when.
On building this I found that I was copying into the form a lot of complication from other forms that use date. So I created `DateFieldBuilder` to put all that complication into one object that could be reused across such forms. To test it's reuse, I refactored `Incidents::LatestIncidentForm` to check that the functionality worked in another form. I've add a tech debt ticket for other Forms to be likewise refactored ([AP-740](https://dsdmoj.atlassian.net/browse/AP-740)).
I have added a holding action controller `Providers::SubstantiveApplicationsController`. The functionality for this should be added in PR-663

AP-662 has Provider used Delegated Functions?

---

app/controllers/concerns/backable.rb
app/controllers/providers/applicant_details_controller.rb
app/controllers/providers/applicants_controller.rb
app/controllers/providers/legal_aid_applications_controller.rb
app/forms/applicants/basic_details_form.rb
app/helpers/providers_helper.rb
app/services/flow/flows/provider_start.rb
app/services/flow/key_point.rb
app/views/providers/applicant_details/show.html.erb
app/views/providers/applicants/new.html.erb
app/views/providers/check_provider_answers/index.html.erb
app/views/shared/forms/_applicant_form.html.erb
config/locales/en/providers.yml
config/locales/en/shared.yml
config/routes.rb
spec/requests/providers/applicant_details_spec.rb
spec/requests/providers/applicants_spec.rb
spec/requests/providers/concerns/draftable_spec.rb
spec/requests/providers/email_addresses_spec.rb
spec/requests/providers/legal_aid_applications_spec.rb

[AP-661](https://dsdmoj.atlassian.net/browse/AP-661)
- Rename path `/providers/applications/:id/applicant` to `/providers/applications/:id/applicant_details`
- Add new path `/providers/applicants`
This new controller is the new start of the provider flow. It creates the application and the applicant on submit. It then removes itself from the history and adds `/providers/applications/:id/applicant_details` instead.
That way, when navigating back to this step, the provider can edit the applicant's details rather than being presented with an empty page that would create an additional applicant and application when submitted

AP-661 blank applications

---

config/locales/en/providers.yml
spec/requests/providers/start_merits_assessments_spec.rb

Update content on 'Provide details of the case' page
[Link to story](https://dsdmoj.atlassian.net/secure/RapidBoard.jspa?rapidView=233&modal=detail&selectedIssue=AP-564)
- Changed 'details about the most recent incident' to 'details about the latest domestic abuse incident'
- Removed 'the estimated costs of doing the work'
- Wrote tests

AP564 Content change to 'Provide details of the case' page

---

app/assets/javascripts/admin-delete.es6
app/views/admin/legal_aid_applications/_legal_aid_applications.html.erb
app/views/admin/legal_aid_applications/index.html.erb
config/locales/en/admin.yml

Add Admin Confirmation button upon deleting an application or all applications
[Link to story](https://dsdmoj.atlassian.net/secure/RapidBoard.jspa?rapidView=233&projectKey=AP&modal=detail&selectedIssue=AP-556)
Have a confirmation button on the admin page upon clicking either:
-  the delete button on a legal aid application record
- the delete all applications button
Include the confirmation button into an alert/error summary message, which appears when 'Delete all applications' or 'Delete' buttons are pressed.
Have JavaScript toggle the view of the error summary/confirmation alert message when a button is pressed. Also, have JavaScript to adapt the 'Yes, delete' confirmation button's action route to the data record delete was clicked on or to all applications if 'Delete all applications' …

AP556 Admin Confirm Delete

---

app/controllers/citizens/identify_types_of_incomes_controller.rb
app/controllers/citizens/identify_types_of_outgoings_controller.rb
app/controllers/providers/identify_types_of_incomes_controller.rb
app/controllers/providers/identify_types_of_outgoings_controller.rb
config/locales/en/activerecord.yml
config/locales/en/citizens.yml
config/locales/en/providers.yml
spec/requests/citizens/identify_types_of_incomes_spec.rb
spec/requests/citizens/identify_types_of_outgoings_spec.rb
spec/requests/providers/identify_types_of_incomes_spec.rb
spec/requests/providers/identify_types_of_outgoings_spec.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-670)
Fix wrong error messages on **select types of incomes/outgoings** pages

AP-670 fix wrong error messages

---

app/controllers/providers/success_likely_controller.rb
app/forms/merits_assessments/success_likely_form.rb
app/forms/merits_assessments/success_prospect_form.rb
app/lib/govuk_elements_form_builder/form_builder.rb
app/models/merits_assessment.rb
app/services/flow/flows/provider_merits.rb
app/views/providers/check_merits_answers/show.html.erb
app/views/providers/success_likely/index.html.erb
app/views/shared/forms/_success_prospect_form.html.erb
app/views/shared/forms/success_prospect/_success_prospect_item.html.erb
config/locales/en/activemodel.yml
config/locales/en/helpers.yml
config/locales/en/providers.yml
config/locales/en/shared.yml
config/routes.rb
db/migrate/20190617103359_add_success_likely_to_merits_assessments.rb
db/schema.rb
features/providers/civil_application_journey.feature
spec/lib/govuk_elements_form_builder/form_builder_spec.rb
spec/requests/providers/check_merits_answers_spec.rb
spec/requests/providers/statement_of_case_spec.rb
spec/requests/providers/success_likely_spec.rb
spec/requests/providers/success_prospects_spec.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-692)
- Add new **Is the chance of a successful outcome 50% or better?** page
- Remove **more than 50%** from `success_prospect` page and change copy
- Modify FormBuilder to allow passing hint option to radio buttons

AP-692 split prospects of success

---

app/controllers/citizens/has_dependants_controller.rb
app/forms/legal_aid_applications/has_dependants_form.rb
app/services/flow/flows/citizen_capital.rb
app/views/citizens/has_dependants/show.html.erb
app/views/shared/forms/_has_dependants_form.html.erb
config/locales/en/activemodel.yml
config/locales/en/citizens.yml
config/routes.rb
db/migrate/20190628120413_add_has_dependants_to_legal_aid_applications.rb
db/schema.rb
features/citizens/citizens.feature
spec/requests/citizens/has_dependants_spec.rb

A page with a yes or no checkbox form, which says if a legal aid application has or doesn't have a dependant or dependants
[Link to story](https://dsdmoj.atlassian.net/secure/RapidBoard.jspa?rapidView=233&projectKey=AP&modal=detail&selectedIssue=AP-720)
- Added column has_dependants to legal aid applications table
- Created controller for has_dependants as well as a form and view
- Created request tests and a feature test for 'no'
- Updated routes and translation files

AP-720 Do you have dependants

---

Gemfile.lock

This reverts commit 64b3fa516a8916b8c229d059572ebb05160b2697.
Yesterday's update of Rubocop https://github.com/ministryofjustice/laa-apply-for-legal-aid/pull/610 seems to have broken `erblint`.
I spent 10 minutes trying to fix it but did not succeed.
I suggest we revert the update until we find a solution.

Revert "Bump rubocop from 0.71.0 to 0.72.0"

---

app/views/providers/check_merits_answers/show.html.erb
app/views/shared/check_answers/_no_link_item_bold.html.erb
config/locales/en/providers.yml
spec/requests/providers/check_merits_answers_spec.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-686)
Removed latest incident page with date and details sections. Added latest incident date to the told_on page.
Add validation for the order of the dates.
Refactor the page to use the DateFieldBuilder method.

Ap-686 check your answers latest incident

---

package.json
yarn.lock

Bump jQuery from v1.12.4 to v3.4.1
UAT: https://bump-jquery-version-applyforlegalaid-uat.apps.cloud-platform-live-0.k8s.integration.dsd.io/
I went through the whole flow in UAT and it works well.
Dependabot tried to upgrade to v3.4.0 the other day (https://github.com/ministryofjustice/laa-apply-for-legal-aid/pull/614) but the feature tests were failing.
v3.4.1 seems to be OK.

Bump jQuery from v1.12.4 to v3.4.1

---

app/controllers/admin/legal_aid_applications_controller.rb
app/views/admin/legal_aid_applications/_legal_aid_applications.html.erb
app/views/admin/legal_aid_applications/index.html.erb
spec/requests/admin/legal_aid_applications_spec.rb

Admin index page has pagination on legal aid applications
[Link to story](https://dsdmoj.atlassian.net/secure/RapidBoard.jspa?rapidView=233&projectKey=AP&modal=detail&selectedIssue=AP-555)
- Add Pagination to admin page using Pagy gem (With maximum of 10 items on each paginated page)
- Remove limit of 25 latest applications shown on admin page
- Create request test for pagination

AP-555 Admin Pagination

---

spec/factories/bank_accounts.rb
spec/factories/bank_transactions.rb
spec/factories/legal_aid_applications.rb
spec/factories/merits_assessments.rb
spec/factories/other_assets_declarations.rb
spec/factories/savings_amounts.rb
spec/forms/legal_aid_applications/percentage_home_form_spec.rb
spec/forms/outstanding_mortgage_form_spec.rb
spec/forms/savings_amounts/savings_amounts_form_spec.rb
spec/models/other_assets_declaration_spec.rb
spec/models/savings_amount_spec.rb
spec/requests/citizens/accounts_spec.rb
spec/requests/citizens/dependants/relationships_spec.rb
spec/requests/citizens/outstanding_mortgage_spec.rb
spec/requests/citizens/savings_and_investments_spec.rb
spec/requests/providers/other_assets_spec.rb
spec/requests/providers/savings_and_investments_spec.rb
spec/support/true_layer_mock_data.rb

Remove annoying Faker's deprecation warnings by removing the use of `Faker::Number.decimal`

Stop Faker warnings

---

Gemfile

Added line `gem 'wdm', '>= 0.1.0' if Gem.win_platform?` to Gemfile for Ruby on Windows

Added new line to Gemfile for Windows users

---

db/migrate/20190705091659_delete_unnecessary_proceeding_types.rb

I noticed that this new migration is breaking the DB setup in UAT because the DB is empty at that point and `ProceedingType.find_by(ccms_code: 'DA001').id` is failing.
Error in sentry:
https://sentry.service.dsd.io/mojds/apply-laa-apply-for-legal-aid-/issues/36527/

Fix migration

---

app/models/legal_aid_application.rb
spec/factories/legal_aid_applications.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-777)
Fix for this error: https://sentry.service.dsd.io/mojds/apply-for-legal-aid-staging/issues/36456/
It happens when an admin tries to delete an application which has a vehicle
This fix is covered by this test : https://github.com/ministryofjustice/laa-apply-for-legal-aid/blob/master/spec/models/legal_aid_application_spec.rb#L306
- Adding `with_vehicle` to the `with_everything` trait broke the test.
- Adding  `, dependent: :destroy` to `has_one :vehicle` made the test green again.

AP-777 Delete vehicle when deleting application

---

.circleci/config.yml

The `clean_up_ecr` CircleCI job is failing since I introduced the parallelism.

Fix failing clean_up_ecr job in CircleCI

---

app/controllers/v1/fake_providers_controller.rb
app/models/firm.rb
app/models/office.rb
app/models/provider.rb
app/services/provider_details_creator.rb
app/workers/provider_details_creator_worker.rb
db/migrate/20190712133912_create_firms_and_offices.rb
db/schema.rb
spec/factories/firms.rb
spec/factories/offices.rb
spec/requests/saml_sessions_spec.rb
spec/requests/v1/fake_providers_spec.rb
spec/services/provider_details_creator_spec.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-775)
Paired with Julien
This is the first part of AP-775, sectioned of as its own PR so that there is not one huge PR at the end. None of the work is visible on the front end for this change.
Added new tables for offices and firms.
Updated the fake provider name api to return the same provider code code for each office, to add the legal aid code to the name to match the expected data from CCMS

Ap-775-add-offices-and-firms

---

app/lib/govuk_elements_form_builder/form_builder.rb
spec/lib/govuk_elements_form_builder/form_builder_spec.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-762)
Bug Fix : prevent showing hint for each radio button when using govuk_collection_radio_buttons

Bug Fix : prevent showing hint for each radio button when using govuk_collection_radio_buttons

---

README.md

Just a char change in the README file to keep the readme up to date. 
Project ruby version got updated but the Readme wasn't reflecting it.

Update Readme Ruby version to 2.6.3

---

app/views/admin/legal_aid_applications/_legal_aid_applications.html.erb
app/views/providers/legal_aid_applications/_legal_aid_applications.html.erb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-602)
Ensure all dates are in GDS style, eg ‘4 June 2019’.
Update all pages not using this format to use the 'long_date' format
defined in config/locales/en/date.yml (or 'short_date' if it appears in
a table).
There only appears to be two to change:
- views/admin/legal_aid_applications/_legal_aid_applications.html.erb
- views/providers/legal_aid_applications/_legal_aid_applications.html.erb

AP-602 Standardise date formats across the app

---

spec/factories/dependants.rb
spec/factories/incidents.rb
spec/requests/citizens/dependants/full_time_educations_spec.rb
spec/requests/citizens/dependants/monthly_incomes_spec.rb

I noticed that the `it 'redirects to the assets page'` test of `monthly_incomes_spec.rb` is intermittently failing if the dependant happens to be less than 18 years old.
So I fixed this test by fixing the age of the dependant using the `:over_18` factory trait.
- I also added another test for the scenario if the dependant is less than 18.
- Added all attributes in the dependant's factory.
- Removed a duplicate in `schema.rb`
---
Additionally, this test is also failing intermittently: https://github.com/ministryofjustice/laa-apply-for-legal-aid/blob/master/spec/forms/incidents/told_on_form_spec.rb#L99
Because the test only passed `told_on` as a parameter to the form but not `occurred_on`, it can happen that `occurred_on` which is generated as `Faker::Date.backward(90)` by the factory could …

Fix intermittent failing tests

---

.circleci/config.yml
bin/delete_uat_release

- only runs on master branch
- only runs when git message contains "Merge pull request #"
- Extract branch from git log
- Generate UAT release name the same way it is done when it's created
- Delete UAT release
I tested it by running the different commands in a CircleCI container but we can't really be sure it works until it's merged

Delete UAT release when PR gets merged

---

app/controllers/providers/applicants_controller.rb
app/controllers/providers/confirm_offices_controller.rb
app/controllers/providers/select_offices_controller.rb
app/controllers/saml_sessions_controller.rb
app/forms/providers/office_form.rb
app/lib/govuk_elements_form_builder/form_builder.rb
app/models/legal_aid_application.rb
app/models/office.rb
app/views/citizens/additional_accounts/index.html.erb
app/views/citizens/additional_accounts/new.html.erb
app/views/citizens/has_other_dependants/show.html.erb
app/views/providers/confirm_offices/show.html.erb
app/views/providers/select_offices/show.html.erb
config/initializers/mock_saml.rb
config/locales/en/activemodel.yml
config/locales/en/providers.yml
config/routes.rb
features/providers/civil_application_journey.feature
features/step_definitions/civil_journey_steps.rb
spec/factories/providers.rb
spec/lib/govuk_elements_form_builder/form_builder_spec.rb
spec/requests/providers/applicants_spec.rb
spec/requests/providers/confirm_offices_spec.rb
spec/requests/providers/select_offices_spec.rb
spec/requests/saml_sessions_spec.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-775)
Paired with Will
After a provider logs in, they need to select which office they belong to.
Here is the logic:
In addition to that diagram, if the provider's firm has only one office, we automatically assign the office to the provider and skip the confirm/select pages.

AP-775 Confirm/Select Office

---

app/views/providers/bank_transactions/_list_selected.html.erb
config/locales/en/date.yml
config/locales/en/time.yml

[Link to story](https://dsdmoj.atlassian.net/browse/AP-602)
Dates should be formatted '1 July 2019' not '01 July 2019' - ie with no leading 0 on the day.
This PR amends the formatting in `locales/en/date.yml` so that dates are displayed correctly.
While changing this I noticed that the `transaction_date` format in `locales/en/time.yml` is a duplicate of the `short_date` format in `locales/en/date.yml`. `transaction_date` is only
used in one place so to avoid confusion I've removed it from `time.yml` and replaced that one instance with `short_date` instead.

AP-602 Standardise date formats

---

.hintrc

[Link to story](https://dsdmoj.atlassian.net/browse/AP-705)
Customized the webhint `.hintrc` file to allow for specific bypassing of hints that the GDS desing system will fail.  
Confirmed what messages are okay with Oliver Byford at GDS and from the [GDS list of known validation errors](https://github.com/alphagov/govuk-frontend/issues/1280) 

AP-705 (revisited) Attempt to better customize webhint

---

bin/uat_deploy

`bin/uat_deploy` contains some old code which was intended to delete old UAT releases to prevent the number building up. It was never implemented properly and didn't actually delete anything, but gave the impression to the user that it did.
Following the recent change to delete old UAT instances when their branch is deleted in GitHub this code is completely redundant as well as being misleading, so I think we should remove it.

Delete unused 'clean_old_releases' code

---

app/controllers/providers/applicants_controller.rb
app/controllers/providers/confirm_offices_controller.rb
app/controllers/providers/select_offices_controller.rb
app/forms/providers/office_form.rb
app/models/office.rb
app/models/provider.rb
app/services/ccms/case_add_requestor.rb
app/services/provider_details_creator.rb
app/views/providers/confirm_offices/show.html.erb
app/views/providers/select_offices/show.html.erb
ccms_integration/ccms_spec.rb
config/attribute-map.yml
config/locales/en/activemodel.yml
db/migrate/20190725130335_rename_provider_selected_office.rb
db/migrate/20190725130416_create_offices_providers.rb
db/migrate/20190729100602_rename_provider_offices.rb
db/schema.rb
features/step_definitions/civil_journey_steps.rb
spec/factories/offices.rb
spec/requests/providers/applicants_spec.rb
spec/requests/providers/confirm_offices_spec.rb
spec/requests/providers/select_offices_spec.rb
spec/requests/saml_sessions_spec.rb
spec/services/ccms/case_add_requestor_spec.rb
spec/services/provider_details_creator_spec.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-816)
Changing the relations between providers and offices.
**Before:**
- A provider has one firm.
- A firm has several providers
- A firm has several offices
To get the list of offices a provider can access, we would do `provider.firm.offices` because we assumed that a provider could access all offices withing their firm.
**After**
We were wrong.
Providers withing the same firm don't always have access to all offices within their firm.
Therefore, this PR adds the `provider.offices` relation and prevent providers from selecting offices they don't have access to even if they belong to the same firm.
And changed `provider.office` to `provider.selected_office` to make it more obvious that this is the office they selected when they login …

AP-816 Fix providers-offices relation

---

app/javascript/src/proceeding_types.js

[Link to story](https://dsdmoj.atlassian.net/browse/AP-826)
A javascript event has been added to allow the user to select a proceeding type by clicking on the whole row and not necessarily on the button.
However, if you click on the button, you're basically clicking on the row and the button at the same time. Therefore, the javascript event gets triggered and the normal HTML form event gets also triggered. This submits the form twice.
Ending the JavaScript event with `return false` stops the event from propagating to its default event.

AP-826 Prevent double submit when selecting proceeding type

---

spec/services/ccms/case_add_requestor_xml_blocks_spec.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-794)
The correct values were already being generated.  This just adds a test to prove that that is the case.

AP-794 CCMS paylod block BAIL_CONDITIONS_SET

---

package.json
yarn.lock

I approved this Dependabot PR earlier https://github.com/ministryofjustice/laa-apply-for-legal-aid/pull/697. It seems to be causing failures on `master` now. This reverts it so it can be investigated properly.

revert webhint upgrade

---

app/models/ccms/submission.rb
app/services/ccms/attribute_value_generator.rb
config/ccms/ccms_keys.yml
spec/services/ccms/case_add_requestor_xml_blocks_spec.rb
spec/support/xml_extractor.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-835)
[Link to story](https://dsdmoj.atlassian.net/browse/AP-839)
renamed merits_assessment and means_assessment in the XmlExtractor to deal with a naming disparity with the xml file.
checked that hard coded true values were correct and added tests for these values.
reordered ccms case submission states to make it more readable

Ap835 hard coded ccms true results and 839 APP_AMEND_TYPE

---

.circleci/config.yml
db/migrate/20190724135655_add_enum_column_to_application_scope_limitations.rb
db/schema.rb

[Sentry Error](https://sentry.service.dsd.io/mojds/apply-for-legal-aid-staging/issues/36929/)
PR https://github.com/ministryofjustice/laa-apply-for-legal-aid/pull/683 adds two migrations adding the same column so the second is crashing and preventing `db:migrate` to work.
- I'm removing this migration
- Changing CircleCI to use `db:schema:load` from master and then `db:migrate` from the branch. In order to mimic the behaviour in live but without having to run old migrations.
- I also took the opportunity to align our `schema.rb` file with what is really generated by the migrations and is, therefore, the real state of the DB in production envs.

Remove buggy migration and align DB with migrations

---

.hintrc
app/services/html_page_saver.rb
features/support/env.rb
spec/services/html_page_saver_spec.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-858)
Avoid these WebHint false positives:
- Don't check pages from TrueLayer
- Doctype not being present
-  "'charset' meta element should be the first thing in '<head>'."
The last one happened because Capybara's `page.save_page` inserts `<base href="http://localhost:3004" />`  as the first element in the `<head>` tag.
So this PR implements it better to avoid the WebHint error.
For the Doctype error, the problem is that the page saved to file does not include the Doctype and I didn't manage to fix that so I added this error as an exception in Webhint's config.

AP-858 Avoid webhint false positives

---

Gemfile
Gemfile.lock
app/controllers/saml_idp_controller.rb
app/services/provider_details_creator.rb
app/views/providers/providers/show.html.erb
config/attribute-map.yml
config/initializers/mock_saml.rb
config/locales/en/providers.yml
db/migrate/20190806115955_add_name_and_email_to_providers.rb
db/schema.rb
spec/factories/providers.rb
spec/requests/providers/providers_spec.rb
spec/services/provider_details_creator_spec.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-778)
. Get provider email from the SAML response and saves it.
. Save provider name from the provider details API into its own attribute
I had to use a fork of the `ruby-saml-idp` gem in order to have attributes in the mock SAML response 

AP-778 Save provider name and email

---

Gemfile
Gemfile.lock
app/assets/stylesheets/admin.scss
app/controllers/admin/benefit_types_controller.rb
app/controllers/admin/legal_aid_applications_controller.rb
app/controllers/admin/settings_controller.rb
app/helpers/admin_helper.rb
app/helpers/layouts_helper.rb
app/models/benefit_type.rb
app/views/admin/benefit_types/_form.html.erb
app/views/admin/benefit_types/edit.html.erb
app/views/admin/benefit_types/index.html.erb
app/views/admin/benefit_types/new.html.erb
app/views/admin/benefit_types/show.html.erb
app/views/admin/legal_aid_applications/index.html.erb
app/views/admin/settings/show.html.erb
app/views/layouts/admin.html.erb
config/locales/en/activerecord.yml
config/locales/en/admin.yml
config/locales/en/generic.yml
config/locales/en/layouts.yml
config/routes.rb
db/migrate/20190808094323_create_benefit_types.rb
db/schema.rb
db/seeds.rb
db/seeds/data/benefit_types.yml
db/seeds/legal_framework.rb
spec/factories/benefit_types.rb
spec/models/benefit_type_spec.rb
spec/requests/admin/benefit_types_spec.rb

[Jira AP-638](https://dsdmoj.atlassian.net/browse/AP-638)
- Adds a new model `BenefitType` to act as a group object for benefits, that should make it easier to manage whether they are excluded from gross income.
- Adds seeding of known excluded benefit types
- Adds Admin controller to allow modification of benefit types
- Tidied up seeds, and used Dibber's report functionality to provide a better output on seeding
- Added an Admin layout with basic navigation

AP-638 categorise benefits as included or excluded

---

app/models/application_proceeding_type.rb
app/services/ccms/attribute_value_generator.rb
app/services/ccms/case_add_requestor.rb
ccms_integration/ccms_spec.rb
config/ccms/ccms_keys.yml
db/migrate/20190812135413_add_proceeding_case_id_to_application_proceeding_types.rb
db/schema.rb
db/seeds/proceeding_case_id.rb
spec/factories/submissions.rb
spec/models/application_proceeding_type_spec.rb
spec/rails_helper.rb
spec/services/ccms/case_add_requestor_spec.rb
spec/services/ccms/case_add_requestor_xml_blocks_spec.rb
spec/support/xml_extractor.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-795)
Each proceeding on each case needs a unique id to be assigned and included in the CCMS payload.  The id is in the form `P_nnnnnnnn` where `nnnnnnnn` is a number greater than 55,000,000.
This is achieved by adding a `proceeding_case_id` column to the `application_proceeding_types` table, and linking it to a Postgres sequence starting at 55,000,001.  There is no Rails Migration DSL keyword for adding a sequence, so it needs to be added with a hand-coded `ADD SEQUENCE` SQL statement, which unfortunately means it is not dumped to the `db/schema.rb` file.  It has therefore been added in the seeds, and will only create the sequence and alter the column to use the sequence if it hasn't already been done before.
Before you ask people to …

AP-795 Generate unique Proceeding Case ID

---

.hintrc
bin/generate_webhint_reports.sh

Turned off HTML-checker for Webhint as it was causing random errors.

Disable HTML-CHECKER on webhint ☹

---

README.md
lib/tasks/webhint.rake

Add a rake task to run related webhint tasks with a single command, rather than running several commands independently.
Running `rake webhint:generate_reports` will delete any existing files from previous runs, generate new pages, and run webhint against each page.

Add webhint rake task

---

app/assets/stylesheets/check-your-answers.scss
app/views/providers/submitted_applications/show.html.erb
config/locales/en/providers.yml
features/providers/civil_application_journey.feature

Remove income and payments from /submitted_application for passported applications and replace with govuk-tag 'Passported'
[Link to story](https://dsdmoj.atlassian.net/secure/RapidBoard.jspa?rapidView=233&projectKey=AP&modal=detail&selectedIssue=AP-867)
- Update the view and replace incomes and outgoing details with 'Passported' govuk-tag when the application is passported.
- Override govuk-tag style to capitalize and not be all capitals
(I read about overriding govuk styles here https://design-system.service.gov.uk/get-started/extending-and-modifying-components/#small-modifications-to-components )
- Update feature test and locales

AP867 Update Submitted Application for passported

---

Rakefile

Include webhint:generate_reports into tests and replace cucumber (bundle execute rake) with it. This is because webhint also runs cucumber tests.

Include Webhint into tests

---

app/models/provider.rb
app/services/ccms/case_add_requestor.rb
ccms_integration/ccms_spec.rb
config/ccms/ccms_keys.yml
spec/services/ccms/case_add_requestor_spec.rb
spec/services/ccms/case_add_requestor_xml_blocks_spec.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-904)
Amend `ccms_integration/ccms_spec.rb` so that it injects two cases into
CCMS when it is run - one delegated functions (as it does already) and
one substantive.
- Add an extra `context` to account for the substantive case. This
involves some refactoring of the existing spec.
- Amend `save_request` functionality so that it includes the case type in
the filename, to make it easier to see what each payload is.
- Use factories to create `proceeding_types` and `scope_limitations`,
instead of doubles.
- Changes to `case_add_requestor` and `ccms_keys` to ensure correct values
are being populated in the payload.

AP-904 - Create substantive cases with CCMS integration spec

---

app/controllers/citizens/identify_types_of_incomes_controller.rb
app/controllers/citizens/identify_types_of_outgoings_controller.rb
app/controllers/providers/identify_types_of_incomes_controller.rb
app/controllers/providers/identify_types_of_outgoings_controller.rb
app/forms/citizens/other_assets_form.rb
app/forms/savings_amounts/savings_amounts_form.rb
app/javascript/src/checkbox_control.js
app/models/concerns/capital.rb
app/views/shared/forms/_identify_types_of_outgoings_form.html.erb
app/views/shared/forms/_savings_and_investments_form.html.erb
app/views/shared/forms/_types_of_income_form.html.erb
app/views/shared/forms/other_assets/_form.html.erb
db/migrate/20190827122038_add_none_selected.rb
db/schema.rb
spec/forms/citizens/other_assets_form_spec.rb
spec/forms/savings_amounts/savings_amounts_form_spec.rb
spec/requests/citizens/identify_types_of_incomes_spec.rb
spec/requests/citizens/identify_types_of_outgoings_spec.rb
spec/requests/citizens/other_assets_spec.rb
spec/requests/citizens/savings_and_investments_spec.rb
spec/requests/providers/identify_types_of_incomes_spec.rb
spec/requests/providers/identify_types_of_outgoings_spec.rb
spec/requests/providers/other_assets_spec.rb
spec/requests/providers/savings_and_investments_spec.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-824)
Fix the issues by persisting "None of these" checkboxes to DB.
pages affected:
- `/citizens/identify_types_of_income`
- `/citizens/identify_types_of_outgoing`
- `/citizens/other_assets`
- `/citizens/savings_and_investment`
- `/providers/applications/:legal_aid_application_id/identify_types_of_income`
- `/providers/applications/:legal_aid_application_id/identify_types_of_outgoing`
- `/providers/applications/:legal_aid_application_id/other_assets`
- `/providers/applications/:legal_aid_application_id/savings_and_investment`
I think that's all of them

AP-824 persist none_selected checkboxes

---

.circleci/config.yml

- Remove use of parallelism but use different jobs instead. It simpler and make more sense
- move `webhint` to the end of the previous job running all the tests. Rather than a separate job. With 2 jobs, there was twice the overhead of setting up the image.
- modify workflows to move jobs that don't rely on each other into separate workflows. Split `build_and_deploy` into 2 workflows :
- `test` runs all the tests. Has only one job. This should be the only mandatory job when a PR needs to be merged
- `build_and_deploy` builds the docker image, push it to ECR, and can be deployed to UAT/Staging/Prod
- in addition to saving the webhint reports. We also save the html pages. That was a request from Malcolm
- use CircleCI versions of `postgres` and `redis`. They have some improvements that make …

Simplify CircleCI process by using a separate job and workflow rather than parallelism. And some other improvements

---

app/controllers/citizens/other_assets_controller.rb
app/controllers/citizens/restrictions_controller.rb
app/controllers/citizens/vehicles/purchase_dates_controller.rb
app/controllers/citizens/vehicles_controller.rb
app/controllers/providers/other_assets_controller.rb
app/controllers/providers/property_values_controller.rb
app/controllers/providers/restrictions_controller.rb
app/controllers/providers/vehicles/purchase_dates_controller.rb
app/controllers/providers/vehicles_controller.rb
app/forms/citizens/other_assets_form.rb
app/forms/legal_aid_applications/own_vehicle_form.rb
app/forms/legal_aid_applications/property_value_form.rb
app/forms/legal_aid_applications/restrictions_form.rb
config/locales/en/activemodel.yml
spec/forms/legal_aid_applications/restrictions_form_spec.rb
spec/requests/citizens/other_assets_spec.rb
spec/requests/citizens/restrictions_spec.rb
spec/requests/providers/other_assets_spec.rb
spec/requests/providers/restrictions_spec.rb

[Jira AP-917](https://dsdmoj.atlassian.net/browse/AP-917)
Removed the inconsistency where `journey` was sometimes aliased as `mode`.
Also removed singular journeys - so now the two current journeys are the plurals `:citizens` and `:providers` which match the controller namespace and therefore can be determined from the current controller's ancestors (see helper method `journey_type` in `app/controllers/concerns/flowable.rb`)

AP-917 Remove mode as alias for journey

---

app/models/ccms/submission.rb
app/models/concerns/ccms_submission_state_machine.rb
app/models/provider.rb
app/services/ccms/add_case_service.rb
app/services/ccms/case_add_requestor.rb
app/services/ccms/obtain_document_id_service.rb
app/services/ccms/upload_documents_service.rb
ccms_integration/ccms_spec.rb
spec/factories/submissions.rb
spec/models/ccms/submission_spec.rb
spec/services/ccms/add_case_service_spec.rb
spec/services/ccms/case_add_requestor_spec.rb
spec/services/ccms/obtain_document_id_service_spec.rb
spec/services/ccms/upload_documents_service_spec.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-810)
Documents (eg statement of case PDFs) aren't currently being uploaded to CCMS correctly. The current, incorrect, process is:
1. request_case_id
2. create_an_applicant
3. poll_applicant_creation
4. create_case
5. poll_case_creation_result
6. request_document_ids
7. upload_documents
This is incorrect as document ids need to be included in the
create_case payload.
This commit changes the order of CCMS requests to
1. request_case_id
2. create_an_applicant
3. poll_applicant_creation
4. request_document_ids
5. create_case
6. poll_case_creation_result
7. upload_documents
by amending the logic in `ccms_submission_state_machine`, and changing various CCMS `_service` classes appropriately.
It also amends `case_add_requestor.rb` so that …

Ap 810 fix ccms document upload

---

app/helpers/application_helper.rb
app/helpers/page_template_helper.rb
config/locales/en/errors.yml
spec/requests/providers/applicants_spec.rb

[Jira AP-538](https://dsdmoj.atlassian.net/browse/AP-538)
Modifies the way page the header is defined so that the header within `head` can be set differently to that used within the `body`. Then set the `head` title to be prefixed with "Error: " when an error occurs.

AP-538 Add "Error: " prefix to page head title if error present

---

app/models/service_level.rb
app/services/ccms/attribute_value_generator.rb
app/services/proceeding_type_populator.rb
app/services/service_level_populator.rb
config/ccms/ccms_keys.yml
db/migrate/20190828131221_remove_service_levels_table.rb
db/migrate/20190828131723_recreate_service_levels.rb
db/migrate/20190828133153_re_add_default_service_level_idto_proceeding_types.rb
db/schema.rb
db/seeds/legal_framework/levels_of_service.csv
spec/factories/proceeding_types.rb
spec/factories/service_levels.rb
spec/factory_specs/proceeding_types_factory_spec.rb
spec/rails_helper.rb
spec/requests/proceeding_types/index_proceeding_types_spec.rb
spec/services/ccms/case_add_requestor_spec.rb
spec/services/ccms/case_add_requestor_xml_blocks_spec.rb
spec/services/service_level_populator_spec.rb
spec/support/xml_attribute_block_matcher.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-803)
- Refactored the `ServiceLevel` model so that the fixed value `service_level_id` (renamed `service_level_number`) was not the primary key
- generated  the dynamic values for the `LEVEL_OF_SERVICE` and `PROCEEDING_LEVEL_OF_SERVICE' attributes
- refactored the `XMLBlockMatchers' to match expectation of presence, type and response value in one line

AP-803 CCMS payload attributes for LEVEL_OF_SERVICE

---

app/services/ccms/attribute_value_generator.rb
config/ccms/ccms_keys.yml
spec/factories/legal_aid_applications.rb
spec/services/ccms/case_add_requestor_spec.rb
spec/services/ccms/case_add_requestor_xml_blocks_spec.rb

Attributes relating to the applicant’s identity is generated from the application
[Link to story](https://dsdmoj.atlassian.net/secure/RapidBoard.jspa?rapidView=233&projectKey=AP&modal=detail&selectedIssue=AP-878)
1. Update ccms_keys to use the application to grab data about the applicant
2. Update and fix tests
The attributes updated to use applicant information are below:
- POST_CODE
- FIRST_NAME
- SURNAME
- SURNAME_AT_BIRTH
- DATE_OF_BIRTH
- USER_PROVIDER_FIRM_ID
- APPLICATION_CASE_REF
- CLIENT_AGE
- DATE_ASSESSMENT_STARTED
- DATE_CLIENT_VISITED_FIRM
Add the following attributes to be generated as a  global_means attribute:
- BEN_DOB
- BEN_NI_NO
- BEN_SURNAME

Ap 878 Applicant Identity Attributes

---

app/forms/legal_aid_applications/substantive_application_form.rb
app/models/legal_aid_application.rb
app/services/working_day_calculator.rb
features/step_definitions/civil_journey_steps.rb
spec/forms/legal_aid_applications/substantive_application_form_spec.rb
spec/requests/providers/substantive_applications_spec.rb
spec/services/working_day_calculator_spec.rb

[Jira AP-851](https://dsdmoj.atlassian.net/browse/AP-851)
- Modified `WorkingDayCalculator` to make it easier to pass a start day in as well as number of days
- Increased days defined by `LegalAidApplication::WORKING_DAYS_TO_COMPLETE_SUBSTANTIVE_APPLICATION` to 20
- Modified `substantive_application_deadline` calculation to set date from date delegated function used rather than Today.
- Updated specs to match.

AP-851 Increase time to submit substantive application

---

app/services/ccms/attribute_value_generator.rb
config/ccms/ccms_keys.yml
db/migrate/20190903092600_change_default_cost_limitations_from_integer_to_decimal.rb
db/schema.rb
spec/services/ccms/case_add_requestor_spec.rb
spec/services/ccms/case_add_requestor_xml_blocks_spec.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-879)
A number of legal framework data items are being hardcoded in the create case payload. These can now be replaced with real data.
* Add correctly sourced data for
`REQ_COST_LIMITATION`
`APP_IS_FAMILY`
`CAT_OF_LAW_DESCRIPTION`
`CAT_OF_LAW_HIGH_LEVEL`
`CAT_OF_LAW_MEANING`
`CATEGORY_OF_LAW`
`DEFAULT_COST_LIMITATION`
`DEFAULT_COST_LIMITATION_MERITS`
`MATTER_TYPE`
`PROCEEDING_NAME`
to `ccms_keys`.
* Remove any hardcoded values.
* Update tests appropriately.
* Amend `proceeding_types` database table to use `decimal`s for both `cost_limitation`s, as this is more appropriate for monetary values than `integer`s.

AP-879 Add legal framework data to CCMS payload

---

config/ccms/ccms_keys.yml
spec/services/ccms/case_add_requestor_xml_blocks_spec.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-903)
Four additional attributes are required in the CCMS create case payload:
`MEANS_EVIDENCE_PROVIDED`   (hardcoded to `true`)
`MEANS_EVIDENCE_REQD`   (hardcoded to `false`)
`MERITS_EVIDENCE_PROVIDED`   (hardcoded to `true`)
`MERITS_EVIDENCE_REQD`   (hardcoded to `false`)
Enable those blocks with correct hardcoded values in `ccms_keys` and amend specs appropriately.
This PR also makes a couple of other minor changes - it fixes an incorrect test in `case_add_requestor_xml_blocks_spec` and alphabetises some lists of attributes in that spec to make them easier to read and maintain.

AP-903 Evidence uploaded/required attributes

---

app/services/ccms/attribute_value_generator.rb
config/ccms/ccms_keys.yml
spec/services/ccms/case_add_requestor_xml_blocks_spec.rb

There are a number of CCMS attributes relating to the application that need to be generated
[Link to story](https://dsdmoj.atlassian.net/secure/RapidBoard.jspa?rapidView=233&projectKey=AP&modal=detail&selectedIssue=AP-880)
Update values generation for the attributes:
- EMERGENCY_FC_CRITERIA
- URGENT_HEARING_DATE
Write and update tests for attributes:
- EMERGENCY_FC_CRITERIA
- URGENT_HEARING_DATE
- CONFIRMED_NOT_PASSPORTED
Set the attribute value for CONFIRMED_NOT_PASSPORTED to false and omit from payload and add to ccms_keys file

AP880 CCMS payload general application attributes

---

app/views/layouts/application.html.erb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-899)
Added the relevant nofollow/noindex meta tag to the application.html.erb so that it is applied across all of our pages and in all environments.
There are alternative way stop indexing of page that allows for more granular control, however that seems overkill for now as we want to hide all pages and environments from indexing.

Ap-899 Add nofollow noindex tags to prevent indexing

---

app/models/ccms/submission.rb
app/models/ccms/submission_document.rb
app/services/ccms/add_case_service.rb
app/services/ccms/case_add_requestor.rb
app/services/ccms/obtain_document_id_service.rb
app/services/ccms/upload_documents_service.rb
ccms_integration/ccms_spec.rb
db/migrate/20190904151326_remove_ccms_document_id_from_pdf_files.rb
db/migrate/20190909095604_create_submission_documents.rb
db/migrate/20190909101523_remove_documents_from_ccms_submission.rb
db/schema.rb
spec/factories/legal_aid_applications.rb
spec/factories/submission_documents.rb
spec/factories/submissions.rb
spec/services/ccms/case_add_requestor_spec.rb
spec/services/ccms/case_add_requestor_xml_blocks_spec.rb
spec/services/ccms/obtain_document_id_service_spec.rb
spec/services/ccms/upload_documents_service_spec.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-916)
CCMS document upload functionality currently only handles statement of case documents. It also needs to include means and merits reports.
* Add `SubmissionDocument` model with `belongs_to`/`has_many` relationship with `Submission` model, to hold details of documents to be uploaded for a submission.
* Refactor code so that documents are held as `SubmissionDocument`s instead of in a hash.
* Amend `obtain_document_id_service` so that means and merits reports are also identified and added to the `documents` array in the `submission` model.
* Amend `upload_documents_service` so that PDF files for the three different types of document are retrieved from the correct locations and uploaded.
* Remove the `ccms_document_id` field from the …

AP-916 Inject means and merits reports into CCMS

---

app/views/layouts/application.html.erb

Google tag manager bug fix
I altered the application layout view to render a partial for google tag manager instead of a normal layout view file.

Google tag manager bug fix

---

app/assets/stylesheets/pagination.scss
config/locales/en/pagy.yml

[Link to story](https://dsdmoj.atlassian.net/browse/AP-935)
Added new styles to the pagination.scss file.  Adapting our existing styles rather than importing them from the Design System (which would have needed HTML changes too).
Removed the `&raquo;` and `&laquo;` from the translation file - this is done with CSS now.

AP-935 MoJ Design System styling for pages

---

app/assets/stylesheets/table-category-column.scss
app/assets/stylesheets/tags.scss
app/controllers/providers/about_the_financial_assessments_controller.rb
app/controllers/providers/legal_aid_applications_controller.rb
app/forms/legal_aid_applications/substantive_application_form.rb
app/forms/legal_aid_applications/used_delegated_functions_form.rb
app/helpers/gov_uk_form_helper.rb
app/helpers/providers_helper.rb
app/helpers/table_sort_helper.rb
app/helpers/tag_helper.rb
app/helpers/transaction_type_helper.rb
app/models/concerns/legal_aid_application_state_machine.rb
app/services/substantive_application_deadline_calculator.rb
app/views/providers/legal_aid_applications/_legal_aid_applications.html.erb
app/views/providers/transactions/show.html.erb
config/locales/en/model_enum_translations.yml
config/locales/en/providers.yml
config/locales/en/sorting.yml
features/providers/check_your_answers.feature
features/step_definitions/civil_journey_steps.rb
spec/forms/legal_aid_applications/substantive_application_form_spec.rb
spec/forms/legal_aid_applications/used_delegated_functions_form_spec.rb
spec/models/legal_aid_application_spec.rb
spec/requests/providers/about_the_financial_assessments_spec.rb
spec/requests/providers/substantive_applications_spec.rb
spec/requests/providers/used_delegated_functions_spec.rb

[Jira AP-512](https://dsdmoj.atlassian.net/browse/AP-512)
The main purpose of this PR is to modify the appearance of the `providers/applications` page, and add sorting. However, to achieve that a number of prior steps were required.
**Note: the sorting applied in this PR does not work across pagination. This is a known issue and will be addressed in another ticket.**
- Fixed a bug where if you hit back and then save as draft after sending the client the email link, and the client then completed their journey, the provider couldn't then proceed beyond the `Providers::AboutTheFinancialAssessmentsController`
- Move the calculation of the emergency application deadline from the page first showing that deadline (where they choose where to submit a substantive application now or later), to the …

AP 512 homepage table styling and functionality

---

app/services/ccms/attribute_value_generator.rb
app/views/shared/_application_ref.html.erb
config/ccms/ccms_keys.yml
spec/services/ccms/case_add_requestor_spec.rb
spec/services/ccms/case_add_requestor_xml_blocks_spec.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-927)
Added a block that assigns the providers email address to the application for submission to CCMS.

AP-927 Add provider email to CCMS attribute blocks

---

app/views/shared/_application_ref.html.erb

The line of code deleted in this PR was added in error in the ap-927 merged code. This is to remove it.

ap-927 remove code added in error

---

app/services/cfe/base_service.rb
app/services/cfe/create_capitals_service.rb
app/services/cfe/submission_manager.rb
spec/services/cfe/create_assessment_service_spec.rb
spec/services/cfe/create_capitals_service_spec.rb
spec/services/cfe/submission_manager_spec.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-939)
In order for the Apply service to query the Check Financial Eligibility
service, it has to perform the  following 6 steps:
1. Create Assessment
2. Create Application
3. Create Capitals
4. Create Vehicles
5. Create Properties
6. Obtain Assessment Result
This PR covers step 3.
- Created `CreateCapitalsService`
- Modified `CFE::SubmissionManager` to call `CreateCapitalsService` as part of the workflow

AP-939 Query CFE service - create capitals

---

app/controllers/providers/address_selections_controller.rb
app/helpers/address_helper.rb
app/models/address.rb
features/providers/civil_application_journey.feature
spec/forms/addresses/address_form_spec.rb
spec/requests/providers/check_provider_answers_spec.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-813)
Addresses are currently displayed like this on the first check your answers page:
2
DENMAN ROAD
LONDON
SE155NP
They should be displayed as
2 Denman Road
London
SE15 5NP
ie - in title case, with line 1 and line 2 combined and a space in the
postcode.
Implement this by amending `address_helper.rb `to
- concatenate `address_line_1` and `address_line_2`
- calling `titelize` on the first three lines
- calling the `address` model's `pretty_postcode` method

AP-813 Display addresses better

---

app/controllers/home_controller.rb
app/views/home/index.html.erb
config/locales/en/home.yml
config/routes.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-921)
A user visiting the application on eg https://apply-for-legal-aid.service.justice.gov.uk is presented with a page displaying 'welcome home'. They should instead see the providers'
start page.
* Amend `routes.rb` so that root instead directs the user to `providers/start#index`
* Remove redundant code for the previous landing page

AP-921 Change provider root

---

app/controllers/providers/merits_reports_controller.rb
app/models/legal_aid_application.rb
app/services/ccms/attribute_value_generator.rb
app/services/ccms/case_add_requestor.rb
app/services/ccms/obtain_case_reference_service.rb
app/views/shared/_application_ref.html.erb
spec/factories/applicants.rb
spec/factories/cfe_submissions.rb
spec/factories/legal_aid_applications.rb
spec/requests/providers/merits_reports_spec.rb
spec/services/ccms/case_add_requestor_spec.rb
spec/services/ccms/case_add_requestor_xml_blocks_spec.rb

[AP-912](https://dsdmoj.atlassian.net/browse/AP-912)
Updated the partial used the report PDF so that it includes the CCMS case reference.
Added some code to gather the case reference from CCMS, if that hasn't already occurred when the report is called.
Also a little tidying up - mainly to remove the inconsistency of the name of the attribute holding the case reference.

AP-912 Add CCMS case reference to merits report PDF

---

app/forms/savings_amounts/savings_amounts_form.rb
app/services/ccms/attribute_value_generator.rb
app/services/cfe/create_capitals_service.rb
config/locales/en/activemodel.yml
config/locales/en/shared.yml
db/migrate/20190918102038_rename_isa_to_offline_accounts.rb
db/schema.rb
features/citizens/citizens.feature
spec/factories/savings_amounts.rb
spec/forms/savings_amounts/savings_amounts_form_spec.rb
spec/requests/citizens/savings_and_investments_spec.rb
spec/requests/providers/savings_and_investments_spec.rb
spec/services/ccms/case_add_requestor_spec.rb
spec/services/ccms/case_add_requestor_xml_blocks_spec.rb
spec/services/cfe/create_capitals_service_spec.rb

This is an addition to the pull request AP-939 that was merged yesterday after discovering that savings amounts should be added to the capitals payload.
[Link to story](https://dsdmoj.atlassian.net/browse/AP-939)
- rename `isa` field on `SavingsAmount` model to `offline_accounts` to better reflect the data held in that field
- Added the non-zero savings amount fields to the capitals payload

AP-939 Add savings amounts to capitals payload

---

app/services/ccms/attribute_value_generator.rb
app/services/ccms/case_add_requestor.rb
ccms_integration/ccms_spec.rb
config/ccms/ccms_keys.yml
spec/services/ccms/case_add_requestor_xml_blocks_spec.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-952)
There are issues with substantive case payloads being injected in CCMS. This PR fixes the following issues:
* `ApplicationAmendmentType` is incorrectly being set as `SUBDP` for all cases. It should be `SUB` for substantive cases and `SUBDP` for delegated functions cases.
*  `CURRENT_CERT_SUBSTANTIVE`, `SUBSTANTIVE_APP` and `PROCEEDING_APPLICATION_TYPE` attributes are currently omitted. These should be included with values of `false`, `true` and `Substantive` for substantive cases, and `false`, `false` and `Both` for delegated functions cases.
* Fix a bug caused by a change to the `provider` model which was causing the `ccms_spec` to fail - add an email address to the provider double.

Ap 952 create valid substantive case

---

app/services/ccms/case_add_requestor.rb
ccms_integration/ccms_spec.rb
spec/services/ccms/case_add_requestor_spec.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-956)
`ccms_spec.rb` uses factories to create proceeding types and scope
limitations for test applications. The data produced by these factories
by default is not compatible with CCMS and so the cases produced are
not useable. 
Additionally, `ccms_spec.rb` is using incorrect provider details. Some of
the details it currently populates is related to a different firm to
the rest of the provider data.
* create proceeding types and scope limitations for substantive and
delegated functions cases using valid data
* fix incorrect provider details by using data for Desor & Co
* replace an unnecessary ActiveRecord call in `case_add_requestor` with a
method call to the scope limitation model

AP-956 Fix incorrect CCMS test data

---

config/initializers/date_formats.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-964)
Date-times formatted for inclusion in CCMS payloads are appearing incorrectly.
The format is coded as `%Y-%m-%ddT%H:%M:%S.%3N`, which includes an erroneous `d`. This  `d` is appearing in the resulting date string.
Change the format to `%Y-%m-%dT%H:%M:%S.%3N` to prevent the `d` appearing.

AP-964 Fix CCMS datetime format

---

ccms_integration/ccms_spec.rb

Changes in AP-936 (https://github.com/ministryofjustice/laa-apply-for-legal-aid/pull/876)
mean that tests in `ccms_spec.rb` now fail as the `legal_aid_application` is not in the expected state.
Set the `legal_aid_application` to be in the state of `:submitting_assessment` before running the tests, so that all state machine transitions are correct

Fix ccms_spec.rb

---

app/forms/concerns/date_field_builder.rb
spec/forms/concerns/date_field_builder_spec.rb
spec/forms/dependant_form/details_form_spec.rb

[Jira AP-825](https://dsdmoj.atlassian.net/browse/AP-825)
Updates `DateFieldBuilder` so that it accepts both 4 character and 2 character years.
The existing day and month behaviour seems to comply to the ticket spec so I didn't change anything for those date elements.
I started by modifying the dependants form, then the base form class, before finally modifying `DateFieldBuilder`. So the specs cover the core class and a form where it is used.

AP-825 Update DateFieldBuilder to format year entries

---

app/services/ccms/case_add_requestor.rb

LevelOfService in the CCMS case creation payload is currently hardcoded as '3'.
Replace this with a call to get this from the database- `proceeding_type.default_level_of_service.service_level_number` (which will always return 3 anyway as that's the only level of service we're currently using).

AP-963 Replace hardcoded level_of_service in CCMS payloads

---

app/models/concerns/cfe_submission_state_machine.rb
app/services/cfe/base_service.rb
app/services/cfe/create_properties_service.rb
app/services/cfe/create_vehicles_service.rb
app/services/cfe/submission_manager.rb
spec/cassettes/CFE_SubmissionManager/_call/completes_process.yml
spec/services/cfe/create_properties_service_spec.rb
spec/services/cfe/submission_manager_spec.rb

[Jira AP-941](https://dsdmoj.atlassian.net/browse/AP-941)
Adds the service `CFE::CreatePropertiesService` to manage the passing of property data to the Eligibility API. This service is also added to the CFE Submission manager

AP-941 Add service to pass property data to eligibility API

---

app/services/ccms/attribute_value_generator.rb
app/services/ccms/case_add_requestor.rb
config/ccms/ccms_keys.yml
spec/models/legal_aid_application_spec.rb
spec/models/opponent_spec.rb
spec/services/ccms/case_add_requestor_xml_blocks_spec.rb
spec/support/xml_extractor.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-930)
CCMS is currently unable to handle an API call to create a new opponent. Instead a decision has been taken to hardcode details of a dummy opponent.
This change amends the code used to generate the create case payload to ensure the correct values are populated.
The main changes are:
- update `ccms_keys.yml` to ensure correct values are populated in `opponent` and `other_party` blocks.
- update `ccms_case_requestor.rb` to ensure that correct `ns2:OtherParty` section is created and that `opponent` and `other_party` blocks are always generated exactly once.

AP-930 Hard code CCMS dummy opponent

---

app/services/ccms/case_add_requestor.rb
spec/services/ccms/case_add_requestor_spec.rb

[AP-957](https://dsdmoj.atlassian.net/browse/AP-957)
[AP-958](https://dsdmoj.atlassian.net/browse/AP-958)
Three CategoryOfLaw attributes in the CCMS create case payload are currently hardcoded. We hold the relevant data in the database so the values should be retrieved from there.
Amend `case_add_requestor` so that `CategoryOfLawCode`, `CategoryOfLawDescription` and `RequestedAmount` are populated correctly.

AP-957/AP-958 - Populate category of law attributes from database

---

spec/services/ccms/case_add_requestor_xml_blocks_spec.rb
spec/support/xml_extractor.rb

CCMS Omit change_in_circumstance from ccms payload
Missed change_in_circumstance attribute from the AP960 ticket
[Link to story](https://dsdmoj.atlassian.net/secure/RapidBoard.jspa?rapidView=233&projectKey=AP&modal=detail&selectedIssue=AP-960)
Set the generation of the xml block to false for this attribute.

CCMS Omit change_in_circumstance from ccms payload

---

app/assets/stylesheets/bank-selection.scss
app/controllers/citizens/additional_accounts_controller.rb
app/controllers/citizens/banks_controller.rb
app/lib/omniauth/strategies/true_layer.rb
app/models/true_layer_bank.rb
app/services/flow/flows/citizen_start.rb
app/services/true_layer/banks_retriever.rb
app/views/citizens/accounts/index.html.erb
app/views/citizens/banks/_bank.html.erb
app/views/citizens/banks/_error.html.erb
app/views/citizens/banks/index.html.erb
app/workers/true_layer_banks_update_worker.rb
config/application.rb
config/initializers/devise.rb
config/locales/en/citizens.yml
config/routes.rb
db/migrate/20190925095224_create_true_layer_banks.rb
db/schema.rb
features/citizens/citizens.feature
spec/cassettes/true_layer_banks_api.yml
spec/factories/true_layer_banks.rb
spec/lib/omniauth/strategies/true_layer_spec.rb
spec/models/true_layer_bank_spec.rb
spec/requests/citizens/accounts_spec.rb
spec/requests/citizens/additional_accounts_spec.rb
spec/requests/citizens/bank_spec.rb
spec/requests/citizens/consents_spec.rb
spec/services/true_layer/banks_retriever_spec.rb
spec/workers/true_layer_banks_update_worker_spec.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-667)
- Fetch and save list of banks the same way Rob did it for bank holidays
- Implement bank selection before TrueLayer
- Forward selected bank go TrueLayer
UAT: https://ap-667-replace-truelayer-scree-applyforlegalaid-uat.apps.live-1.cloud-platform.service.justice.gov.uk/

AP-667 Bank selection page for OpenBanking

---

app/services/ccms/obtain_document_id_service.rb
app/services/ccms/upload_documents_service.rb

Sidekiq is attempting to request document ids/upload documents multiple times.
To fix this, update the database by calling `submission.save` each time a document is processed by either the `obtain_document_id_service` or the `upload_documents_service`.

Fix document upload processing

---

app/controllers/providers/legal_aid_applications_controller.rb
app/models/legal_aid_application.rb
app/views/providers/legal_aid_applications/_error.html.erb
app/views/providers/legal_aid_applications/_legal_aid_applications.html.erb
app/views/providers/legal_aid_applications/index.html.erb
app/views/providers/legal_aid_applications/search.html.erb
config/locales/en/providers.yml
config/routes.rb
features/providers/civil_application_journey.feature
spec/models/legal_aid_application_spec.rb
spec/requests/providers/legal_aid_applications_spec.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-968)
I tried using PostreSQL's Full text searching (https://www.postgresql.org/docs/9.5/textsearch-intro.html) but it doesn't match what we want. It seems to work on words. For example, it doesn't find "Reese-Mogg" with "smog"
So I'm using PostreSQL's `regexp_replace` to remove all non-alphanumeric characters.

AP-968 Search applications

---

config/govuk_notify_templates.yml

The production Notify template ID for the `reminder_to_submit_an_application` email is currently incorrect - it is set to the same value as the development template. This causes errors on staging and production.
This commit adds the correct template ID.

Fix incorrect Notify template ID

---

bin/delete_ecr_images

The number of images in ECR is causing alerts as it is exceeding 500.
Reduced the length of time that images are retained for, from 30 days, down to 10 days. 

Reduce number of days that images are retained for

---

app/controllers/concerns/providers/authorizable.rb
app/models/legal_aid_application.rb
app/policies/legal_aid_application_policy.rb
config/locales/en/errors.yml
spec/factories/legal_aid_applications.rb
spec/models/legal_aid_application_spec.rb

This is the same as the ticket https://github.com/ministryofjustice/laa-apply-for-legal-aid/pull/926
I've requested a pull-request on this new branch because i've merged the old 926 before pushing into UAT.
**Remove redirect message on submitted applications**
[Link to story](https://dsdmoj.atlassian.net/secure/RapidBoard.jspa?rapidView=233&projectKey=AP&modal=detail&selectedIssue=AP-882)
- Remove Update denied notification
- Prevent a provider from editing an already submitted application by adding a #submitted_to_ccms? method to the legal aid application model then call this method from the pundit policy.
- Add tests
The #submitted_to_ccms? method considers the below states as a submitted application:
:generating_reports
:submitting_assessment
:assessment_submitted
Before you ask people …

Ap 882 remove redirect message fix

---

app/services/ccms/wsdls/CaseServicesSTGWsdl.xml
app/services/ccms/wsdls/ClientProxyServiceSTGWsdl.xml
app/services/ccms/wsdls/DocumentServicesSTGWsdl.xml
app/services/ccms/wsdls/GetReferenceDataSTGWsdl.xml

Omitting "/ccmssoa/" bit by accident was causing a "403 Forbidden"
response from the API Gateway when attempting connections from our
service.

Fix CCMS API Gateway path for staging

---

app/models/cfe/result.rb
app/services/ccms/attribute_value_generator.rb
config/ccms/ccms_keys.yml
spec/factories/cfe_results.rb
spec/factories/cfe_results/mock_results.rb
spec/models/cfe/result_spec.rb
spec/services/ccms/case_add_requestor_spec.rb
spec/services/ccms/case_add_requestor_xml_blocks_spec.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-982)
Populated the four CCMS attributes whose source is the result returned from the Check Financial Eligibility service from the `CFE::Result` model.

AP-982 Populate CCMS attributes from assessment results

---

app/controllers/providers/address_selections_controller.rb
app/forms/addresses/address_selection_form.rb
app/helpers/address_helper.rb
app/models/address.rb
app/serializers/address_serializer.rb
app/services/map_address_lookup_results.rb
features/providers/civil_application_journey.feature
spec/requests/providers/check_provider_answers_spec.rb
spec/services/map_address_lookup_results_spec.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-949)
- Examined the return from the address API and put different bits into different areas as needed.  Example: If Organisation is there, it goes on line 1, otherwise the street name and number does.  
- Removed the Organisation field (it now goes into line 1) as this was not editable.
- Added in the county field, so manually entered addresses with a county have that shew up on the CYA screen.
- Undid the wrapping of AP-813 - this should no longer be necessary.
- Changed the capitalisation code to keep hyphens and stop putting spaces between numbers and letters.

AP-949 Address Fixes

---

app/services/ccms/case_add_requestor.rb
ccms_integration/ccms_spec.rb
spec/services/ccms/case_add_requestor_spec.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-1001)
The case creation payload to CCMS is including multiple scope
limitations when it should contain only one.
This is occurring because proceeding_type.scope_limitations returns all
possible scope limitations for that proceeding type.
Instead use @legal_aid_application.scope_limitations, which returns the
scope limitation actually selected for the proceeding type.

AP-1001 Fix CCMS scope limitations

---

app/forms/savings_amounts/savings_amounts_form.rb
app/services/ccms/attribute_value_generator.rb
app/services/cfe/create_capitals_service.rb
app/views/shared/forms/revealing_checkbox/_attribute.html.erb
config/locales/en/activemodel.yml
config/locales/en/shared.yml
db/migrate/20191018174252_add_column_and_rename_existing_on_savings_amounts.rb
db/schema.rb
features/cassettes/Civil_application_journeys/Receives_benefits_and_completes_the_application.yml
features/citizens/citizens.feature
features/providers/check_your_answers.feature
features/providers/civil_application_journey.feature
spec/factories/savings_amounts.rb
spec/forms/savings_amounts/savings_amounts_form_spec.rb
spec/requests/citizens/savings_and_investments_spec.rb
spec/requests/providers/savings_and_investments_spec.rb
spec/services/ccms/case_add_requestor_spec.rb
spec/services/ccms/case_add_requestor_xml_blocks_spec.rb
spec/services/cfe/create_capitals_service_spec.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-852)
The first checkbox on the savings_and_investment screen needs to be
split into two checkboxes to improve user experience.
This PR
* amends the savings_amounts table to hold two values, not just one
* changes label, hint and error text in translation files for both
provider and citizen screens
* amends the CFE service to ensure all capital values are included
* fixes tests that break as a result of those changes
It also makes a number of other changes to the wordings on the
savings_and_investment screen to bring it line with the prototype (for
example, changing 'Cash savings' to 'Money not in a bank account').

Ap 852 split bank accounts

---

app/services/ccms/applicant_add_requestor.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-1018)
Apply does not ask for the applicant's gender, but all CCMS applicant creation payloads need to contain it. This is currently hardcoded as `FEMALE` which results in all correspondence from CCMS being addressed to 'Ms.'.
This PR changes the hard coded gender to `UNSPECIFIED`.

AP-1018 Change hard coded applicant gender

---

app/models/provider.rb
app/services/provider_details_creator.rb
db/migrate/20191025151150_add_user_login_id_to_provider.rb
db/schema.rb
spec/services/provider_details_creator_spec.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-1020)
A provider user's user_login_id is currently mocked by the Provider
model, which means that all submissions to CCMS contain the same id.
This is incorrect.
Add a column to the providers table to hold this data, and extract it
from the provider details api payload when creating a provider.

AP-1020 Store provider user_login_id

---

app/views/providers/check_benefits/_check_benefits_result.html.erb

Removed the .`column_width: 'full` on the  interruption panel - for some reason it was stopping cucumber from clicking on the Continue button on our local dev machines (but not CircleCI)

Remove column width full due to local cucumber issues

---

app/controllers/providers/means_reports_controller.rb
app/views/providers/means_reports/show.html.erb
app/views/shared/check_answers/_capital_result.html.erb
ccms_integration/ccms_spec.rb
config/locales/en/providers.yml
config/locales/en/shared.yml
spec/factories/cfe_results/mock_results.rb
spec/factories/legal_aid_applications.rb
spec/requests/providers/means_reports_spec.rb
spec/services/ccms/add_case_service_spec.rb
spec/services/ccms/obtain_document_id_service_spec.rb
spec/services/reports/means_report_creator_spec.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-914)
Display the CCMS case reference on the means report
* reuse the pattern used for merits report to add the CCMS reference to the means report
Display the capital assessment result on the means report
* add a new partial containing the total capital, capital thresholds and capital contribution amount and include it in the means_reports/show.html.erb view
* add wordings to translation files, including values for the lower and upper capital thresholds which aren't defined anywhere else in the application

AP-914 - Add details to means report

---

app/services/ccms/case_add_requestor.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-1042)
All cases injected to CCMS are including a ProviderCaseReferenceNumber
of 'PC4'. This will be confusing for solicitors.
Apply doesn't currently ask the provider for their reference as part of
the application process.
For now the agreed fix is to remove the ProviderCaseReferenceNumber
from the case creation payload. If solicitor feedback from beta testing
indicates they need it, then it can be added back along with a change to
the Apply journey to allow a solicitor to enter it.

AP-1042 Remove hardcoded provider reference

---

helm_deploy/apply-for-legal-aid/templates/service-monitor.yaml

[Link to Cloud Platform Issue](https://github.com/ministryofjustice/cloud-platform-environments/issues/1105)
Our current k8s UAT namespace deployment sets an individual release per branch. These releases run in parallel under the same namespace, effectively simulating the praised Heroku Pull Review feature.
Because we use the standard configuration for Prometheus Service Monitors that just matches by the application name, we were getting multiple matches/targets for each release on UAT.
This was causing that every release in UAT namespace was creating a Prometheus target against itself but also against every other release under the same namespace.
As a consequence of that, Prometheus receives multiple different samples with identical labels and timestamp, so discards the duplicated and …

Avoid Prometheus duplicated targets in UAT

---

app/services/address_lookup_service.rb
spec/services/address_lookup_service_spec.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-989)
We want to be alerted when calls to the Ordnance Survey Places API fail.
This commit adds Sentry calls to the `AddressLookupService` class in two places, so that alerts will occur if the service is unavailable and if the service is available but is unsuccessful in returning a response (for example if authentication fails).

AP-989 Add Sentry alerting for postcode lookup

---

app/services/ccms/attribute_value_generator.rb
config/ccms/ccms_keys.yml
spec/services/ccms/add_case_service_spec.rb
spec/services/ccms/case_add_requestor_spec.rb
spec/services/ccms/case_add_requestor_xml_blocks_spec.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-1044)
Attribute `LAR_INFER_B_1WP1_36A` is being populated with `application.benefit_check_result`.
`benefit_check_result` is an object, so this appears in the xml payloads like: `#&lt;BenefitCheckResult:0x000055f9a5681a38&gt;`
This is a boolean attribute, so this PR changes it to populate `true` if `application.benefit_check_result.result` is `yes`, and `false` otherwise.

AP-1044 Correct benefit check result

---

app/models/concerns/ccms_submission_state_machine.rb
app/services/ccms/add_applicant_service.rb
app/services/ccms/add_case_service.rb
app/services/ccms/check_applicant_status_service.rb
app/services/ccms/check_case_status_service.rb
app/services/ccms/obtain_applicant_reference_service.rb
app/services/ccms/obtain_case_reference_service.rb
app/services/ccms/obtain_document_id_service.rb
spec/models/ccms/submission_spec.rb
spec/services/ccms/add_case_service_spec.rb
spec/services/ccms/obtain_document_id_service_spec.rb

[AP-1019](https://dsdmoj.atlassian.net/browse/AP-1019)
[AP-1023](https://dsdmoj.atlassian.net/browse/AP-1023)
[AP-1036](https://dsdmoj.atlassian.net/browse/AP-1036)
This PR fixes multiple issues with document uploads to CCMS.
[84de860](https://github.com/ministryofjustice/laa-apply-for-legal-aid/commit/84de86076b1f04237a9ef7b56aced66f175707c1) - ensures that `submission.save!` is called after any change to the `submission` object. This will mean that any sidekiq worker that subsequently updates the same `submission` will always be working on the latest version of that object. 
[531f45e](https://github.com/ministryofjustice/laa-apply-for-legal-aid/commit/531f45e696409adc692ef9fa5ec29c1c7d1f7f20) - the CCMS submission state machine calls `process_async!` after each change in state. This is …

AP 1019 et al - document uploads to CCMS

---

app/services/ccms/attribute_value_generator.rb
config/ccms/ccms_keys.yml
spec/services/ccms/case_add_requestor_spec.rb
spec/services/ccms/case_add_requestor_xml_blocks_spec.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-1059)
This PR fixes a number of issues with attributes being injected into CCMS:
- `WARNING_LETTER_SENT` - will populate the correct value from the database
- `INJ_REASON_NO_WARNING_LETTER` - will populate the correct value from the database if `WARNING_LETTER_SENT` is `false`, and be omitted otherwise
- `GB_INPUT_B_7WP2_1A` - will be `true` if `offline_current_accounts` or `offline_savings_accounts` are populated in the database, otherwise `false`
- `GB_INPUT_B_8WP2_1A` - this will be `true` if `other_person_account` is populated in the database, otherwise `false`
- `GB_INPUT_B_10WP2_1A` - this will be `true` if `peps_unit_trusts_capital_bonds_gov_stocks` is populated in the database, otherwise `false`
- `GB_INPUT_B_17WP2_7A` - this …

AP-1059 CCMS warning letter and savings attributes

---

app/services/ccms/case_add_requestor.rb
spec/services/ccms/case_add_requestor_spec.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-1016)
The `DelegatedFunctionsApply` attribute is not being correctly populated. It is being set to false on DF cases when it should be true.
This is occurring because the attribute is populated with `!limitation.substantive`, I think on the assumption that if it’s not a substantive limitation then it must be delegated functions. However this is not the case, a limitation can apply to both substantive and delegated functions cases.
This PR changes that functionality so that `DelegatedFunctionsApply` is populated with `limitation.delegated_functions`.

AP-1016 Fix CCMS delegated functions flag

---

app/services/ccms/attribute_value_generator.rb
config/ccms/ccms_keys.yml
spec/services/ccms/case_add_requestor_xml_blocks_spec.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-1064)
`VALPOSSESS_INPUT_C_12WP2_8A` is being hard coded as 1000, resulting in incorrect data being injected to CCMS.
This PR amends the valuable_possessions_aggregate_value method in `attribute_value_generator.rb` so that it returns the correct value (`other_assets_declaration.valuable_items_value`).
It also adds some validation so that `VALPOSSESS_INPUT_C_12WP2_7A` and `VALPOSSESS_INPUT_C_12WP2_8A` are only populated in the payload if `GB_INPUT_B_12WP2_2A` is `true` (ie valuable possessions exist).
It also corrects some minor typoes.

AP-1064 CCMS valuable possessions

---

config/ccms/ccms_keys.yml
spec/services/ccms/case_add_requestor_xml_blocks_spec.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-1057)
A number of attributes in CCMS payloads are hardcoded with a string identifying it as being an Apply application.
This text is being exposed to providers when amendments are carried out, which is not desirable (it is intended just for caseworkers).
Replace the string with a `.` to remove this issue for the following attributes:
`EMERGENCY_FC_CRITERIA`
`EMERGENCY_FURTHER_INFORMATION`
`MAIN_PURPOSE_OF_APPLICATION`
`REASON_APPLYING_FHH_LR`
`REASON_NO_ATTEMPT_TO_SETTLE`
`REASON_SEPARATE_REP_REQ`
`INJ_RECENT_INCIDENT_DETAIL`
`INJ_REASON_POLICE_NOT_NOTIFIED`
This also affects one attribute (`INJ_REASON_NO_WARNING_LETTER`) which currently displays a value from the database. It has been decided that for consistency this will also be …

AP-1057 Amend hard coded text in CCMS payloads

---

app/models/cfe/result.rb
app/services/cfe/create_capitals_service.rb
app/services/mock_benefit_check_service.rb
app/views/providers/capital_assessment_results/_other_assets.html.erb
app/views/providers/capital_assessment_results/_property_results.html.erb
app/views/providers/capital_assessment_results/_result_details.html.erb
app/views/providers/capital_assessment_results/_total_capital.html.erb
app/views/providers/capital_assessment_results/show.html.erb
config/locales/en/providers.yml
spec/factories/cfe_results.rb
spec/factories/cfe_results/mock_results.rb
spec/models/cfe/result_spec.rb
spec/requests/citizens/legal_aid_applications_spec.rb
spec/requests/providers/capital_assessment_results_spec.rb
spec/services/cfe/create_capitals_service_spec.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-948)
- altered position of additional property on page
- Subtotal of disposable capital before deduction of pensioner disregard
- Fixed randomly failing test where Faker-generated text was being found on a page

AP-948 Improve means result page

---

helm_deploy/apply-for-legal-aid/templates/dashboard_daily_new_providers_cron.yaml
helm_deploy/apply-for-legal-aid/templates/dashboard_number_provider_firms_cron.yaml
helm_deploy/apply-for-legal-aid/templates/dashboard_past_three_weeks_average_feedback_score.yaml
helm_deploy/apply-for-legal-aid/templates/dashboard_past_weeks_average_feedback_score.yaml
helm_deploy/apply-for-legal-aid/templates/dashboard_started_applications_cron.yaml
helm_deploy/apply-for-legal-aid/templates/dashboard_submitted_applications_cron.yaml
helm_deploy/apply-for-legal-aid/templates/dashboard_total_submitted_applications_cron.yml

Chsnged the names of two cronjobs to make them shorteras that appears to be causing problems on deployment to UAT

Fix cronjob name

---

helm_deploy/apply-for-legal-aid/templates/.dashboard_template_cron.yaml.sample
helm_deploy/apply-for-legal-aid/templates/dashboard_total_submitted_applications_cron.yml

Changed the name of cronjob `total-submitted-applications` to `ttl-submitted-applications` so that it conformed to the 26-character limit for cronjob names

Fix issue with overlong cronjob name

---

app/views/providers/delegated_confirmation/index.html.erb
config/locales/en/providers.yml
features/providers/pathways_from_check_your_answers.feature
spec/requests/providers/delegated_confirmation_spec.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-1069)
edited H1
removed body text about returning to complete a substantive
renamed Jims branch because the name was too long for circleci

Ap 1069 content edit delegated function

---

app/models/ccms/submission.rb
db/migrate/20191114151820_add_on_delete_to_merits_assessment_fk.rb
db/migrate/20191114152212_add_on_delete_to_statement_of_case_fk.rb
db/migrate/20191114193807_add_on_delete_to_ccms_submissions_fk.rb
db/schema.rb
spec/factories/ccms_submission_documents.rb
spec/factories/ccms_submission_histories.rb
spec/factories/ccms_submissions.rb
spec/factories/legal_aid_applications.rb
spec/requests/admin/legal_aid_applications_spec.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-1032)
The button in the Admin screen to Delete All cases does not currently work. It fails due to FK violations in various relations.
This PR does three things:
* It fixes the violations by adding `dependent: :destroy` to the `CCMS::Submission` model for `SubmissionHistory` and `SubmissionDocument` associations, and `on_delete: :cascade` to three foreign keys. This will ensure that all data can be successfully deleted.
* Updates the `with a lot of associations` test in `admin/legal_aid_applications_spec`. This test was previously using an application created with the `:with_everything` trait. This trait has not been updated as extra associations have been added to the app, and so the test was passing even though the functionality did …

AP-1032 Make admin delete all work

---

config/routes.rb
spec/requests/security_text_spec.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-923)
[MoJ Security Guidance](https://ministryofjustice.github.io/security-guidance/contact/implement-security-txt/#implementing-securitytxt) states “Domains where the MOJ is primarily responsible for cyber security must  redirect the /.well_known/security.txt location to the central security.txt file.”
This commit adds a route to redirect to the security text here: https://raw.githubusercontent.com/ministryofjustice/security-guidance/master/contact/vulnerability-disclosure-security.txt when a user visits /.well_known/security.txt.

AP-923 Add /.well-known/security.txt

---

spec/support/xml_attribute_block_matcher.rb

The `XMLBlockMatchers` was not correctly matching XML attribute strings when they were decimals with zeros as decimal places.  For example `1234.00` would fail because it didn't match `1234.0`.
- Chnaged the matcher to recognise currency and numeric decimals and format the expected value to two decimal places before comparison.

FIX matching error in XML blocks for decimals ending in 0

---

app/controllers/providers/merits_declarations_controller.rb
app/models/merits_assessment.rb
spec/requests/providers/merits_declarations_spec.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-1035)
If the user pressed Save as Draft on the Merits Declaration page, the `submitted_at` field was being set on the `MeritsAssessment` which in turn caused the application to be shown as 'Submitted` on the index page.
- Amended  conditions under which `submitted_at` was set
- wrote specs to test the behaviour for both Save as Draft and Continue scenarios

AP-1035 fix bug where saved applications showing as submitted

---

app/models/legal_aid_application.rb
app/services/ccms/case_add_requestor.rb
spec/models/legal_aid_application_spec.rb
spec/services/ccms/case_add_requestor_xml_blocks_spec.rb
spec/support/xml_extractor.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-1081)
On any delegated functions case injected into CCMS the cost limit is showing as £1350 (the delegated functions cost limit). However all delegated functions cases also have a substantive part and so the substantive cost limit of £25000 should apply.
This PR amends the legal aid application model so that the substantive cost limitation is always returned.
Investigating this issue highlighted that the `DevolvedPowersDate` attribute in payloads to CCMS is hardcoded as 01/04/2019. This PR fixes it so `delegated_functions_used_on` date is populated  if delegated functions apply, and is omitted otherwise.

AP-1081 delegated function cost limitation

---

features/providers/check_your_answers.feature
features/step_definitions/civil_journey_steps.rb

```features/providers/check_your_answers.feature:36```
was failing due to an ```'``` in the matching text, however instead of failing noticeably it reported ```You can implement step definitions for undefined steps with these snippets:``` and as a ```pending test``` it is skipped over by any of the checks.
```bundle exec cucumber features/providers/civil_application_journey.feature:429```
was showing a deprecation warning over the use of ```should```. I changed this to use the preferred ```expect```

Fix issues with feature tests

---

.circleci/config.yml

On circle CI "build & push" job, we started having errors on the build when trying to install Python dependencies.
The errors are related with missing remote .deb packages. And this is happening as we do not "apt-get update" before "apt-get install".
Adding the update before the install calls fixes it.

Update packages before install Python dependencies

---

Gemfile
Gemfile.lock
app/views/admin_users/sessions/new.html.erb
config/initializers/omniauth.rb
spec/requests/omniauth_csrf_vulnerability_spec.rb

Fixes https://github.com/ministryofjustice/laa-apply-for-legal-aid/issues/1002
Omniauth has a severe CSRF vulnerability when combined with Rails that has not been patched.
In order to mitigate it there are mainly two actions to take:
1. Turn GET requests links to `/auth/:provider` routes into POST requests.
2. Install `omniauth-rails_csrf_protection` gem.
The architecture of our service (a flow redirecting to different steps) contains a step redirecting to TrueLayer `/auth/truelayer`.
Redirections cannot easily be turned into POST requests and trying to fix that would break the templated "flow with steps" approach.
Due to that, we had to explicitly enable GET requests on Omniauth, as Omniauth rails csrf protection gem enforces POST by default.
CVE: …

Mitigate Omniauth CSRF vulnerability

---

app/services/ccms/case_add_requestor.rb
config/ccms/ccms_keys.yml
spec/services/ccms/case_add_requestor_xml_blocks_spec.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-1091)
Opponent name is hardcoded as 'APPLY service application' in several places. This is appearing on correspondence sent to solicitors and so needs to be changed.
Replace `APPLY service application` with `.` in three places where it occurs:
`OTHER_PARTY_NAME` (in other party section)
`OTHER_PARTY_NAME` (in opponent section)
`OTHER_PARTY_NAME_MERITS` (in opponent section)
Additionally replace the text hardcoded for `LAR_INPUT_T_1WP2_8A` ('Apply Service Application. See uploaded means report in CCMS') with `.` as it is also incorrect.

AP-1091 Change hardcoded opponent name

---

app/models/dashboard/widget_data_providers/daily_new_providers.rb
spec/models/dashboard/widget_data_providers/daily_new_providers_spec.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-1095)
The DailyNewProviders Geckoboard data provider returns an array of hashes, each hash containing a date and the number of first-time Provider logins.  However, a record was not being produced for days when there were no logins. That meant that if there were no logins over the past 7 days, an empty array is returned, which causes Geckoboard to error with "No data to display"
This change ensures that a hash is returned for each of the past 7 days, even if the value is zero.

AP-1095 Fix widget to send zero values

---

app/models/dashboard/widget.rb
app/models/dashboard/widget_data_providers/past_three_weeks_average_feedback_score.rb
app/models/dashboard/widget_data_providers/past_weeks_average_feedback_score.rb
app/models/dashboard/widget_data_providers/started_applications.rb
app/models/dashboard/widget_data_providers/submitted_applications.rb
spec/models/dashboard/widget_data_providers/past_three_weeks_average_feedback_score_spec.rb
spec/models/dashboard/widget_data_providers/past_weeks_average_feedback_score_spec.rb
spec/models/dashboard/widget_data_providers/started_applications_spec.rb
spec/models/dashboard/widget_data_providers/submitted_applications_spec.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-1098)
We record individual satisfaction scores on a range from 0 to 4.  The two widgets previously just added the scores together and divided by the number of records, so you get a figure like 3.7.  The GDS standard prefers scores in the range 0-100, so this change is to multiply the scores by 25, thus transforming 3.7 into 67.5 which is much more meaningful.
Also changed all the widgets which return a value for each day to return zero for days where there aren't any, rather than just omit the record as was happening before

AP-1098 Convert satisfaction scores to GDS standard

---

app/models/dashboard/widget_data_providers/daily_new_providers.rb
app/models/dashboard/widget_data_providers/number_provider_firms.rb
spec/models/dashboard/widget_data_providers/daily_new_providers_spec.rb
spec/models/dashboard/widget_data_providers/number_provider_firms_spec.rb

When a user that is not on the whitelist attempts to login, a Provider record is created by the devise authentication before being refused entry.  We don't want that record to be counted in the Geckoboard dashboard stats.
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1106)
- changed  the Dashboard data providers for User sign ups and number of firms signed up to only count records that are in the whitelist.

AP-1106 exclude providers not on whitelist from dashboard stats

---

app/controllers/providers/means_reports_controller.rb
app/controllers/providers/merits_reports_controller.rb
app/services/reports/base_report_creator.rb
app/services/reports/means_report_creator.rb
app/services/reports/merits_report_creator.rb
spec/requests/providers/means_reports_spec.rb
spec/requests/providers/merits_reports_spec.rb
spec/services/reports/means_report_creator_spec.rb
spec/services/reports/merits_report_creator_spec.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-1078)
The CCMS case reference is not appearing on means and merits reports. This was working but has stopped, due to a change in the CCMS submission process. Previously the call to CCMS to get the case reference always took place before the reports were generated but this is no longer the case.
To fix this, move the `ensure_case_ccms_reference_exists` functionality from the `means_`/`merits_report_controller`s (where it wasn't being called) into the `means_`/`merits_report_creator` services, and ensure a CCMS case reference is always present before creating the reports.
This includes a refactor of the `report_creator`s, creating a `base_report_creator` to provide common functionality.

AP-1078 Refactor CCMS ref on means/merits reports

---

app/controllers/admin/submitted_applications_reports_controller.rb
app/models/legal_aid_application.rb
app/views/admin/submitted_applications_reports/_submitted_applications.html.erb
app/views/admin/submitted_applications_reports/show.html.erb
app/views/layouts/admin.html.erb
config/locales/en/admin.yml
config/locales/en/layouts.yml
config/routes.rb
spec/requests/admin/submitted_applications_reports_spec.rb

Create a report of submitted applications on the admin page
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1093)
- Create controller, view, route and associated translation files for a report
of submitted applications on the admin page
- Update the admin page to have a link to the submitted applications report
- Create a request test for this new page
- Create a scope on the legal aid application model for applications submitted to ccms to reduce 
the number of database queries for filtering for this report
PR requested changes:
- Added pagination with a 10 applications per page limit
- Updated tests to include pagination
- Refactored submitted_applications_reports_controller.rb

AP1093 Create a report of submitted applications on the admin page

---

app/models/dashboard/widget_data_providers/total_submitted_applications.rb
spec/models/dashboard/widget_data_providers/total_submitted_applications_spec.rb

[Fix Total submitted applications widget bug](https://dsdmoj.atlassian.net/browse/AP-1131)
Amend the dashboard widget for `total submitted applications` this was counting _all_ MeritsAssessments rather than limiting it to those with a submitted date

AP-1131 - Only count submitted MeritsApplications

---

.circleci/config.yml

Minor spelling error in circle ci config

Circle CI job name error

---

app/services/dashboard_event_handler.rb
spec/events_spec.rb

No-story: Hotfix
This addresses the issue where applications appear on the graph but not the total.
Work to address this long term will be covered by ap-1109 but as that is a day or so away this fixes it short term.

Hotfix: Call both dashboard widgets when MeritsAssessment saved

---

app/models/provider.rb
spec/models/provider_spec.rb

BugFix - Make whitelisted users check case insensitive
Update condition to test if provider username is in whitelisted user to be case insensitive
Write test to check for this

BugFix - Make whitelisted users check case insensitive

---

.rubocop.yml
app/services/provider_details_retriever.rb

Bug Fix -Update Provider retreiver to use URI.escape instead of CGI.escape
Disable rubocop methods to allow URI.escape to be used instead.
This will fix the issue with providers getting a 500 error on a login attempt via saml.

Bug Fix - Update Provider retreiver to use URI.escape instead of CGI.escape

---

helm_deploy/prometheus-alerts.yaml

[Sidekiq errors in prometheus](https://dsdmoj.atlassian.net/browse/AP-1132)
There are two (immediate, obvious) errors with the prometheus/sidekiq reports
1) A single report exists for sidekiq being down or too busy
2) The metrics cronjob stopped working on 28th November
This PR addresses the first issues as having a single alert for missing or too busy was making debugging hard!

AP-1132: Split the sidekiq prometheus alerts into two

---

app/assets/stylesheets/govuk-mods.scss
app/views/providers/statement_of_cases/show.html.erb
config/locales/en/providers.yml

[Statement of case process and requirements not clear](https://dsdmoj.atlassian.net/browse/AP-1129)
Updated the `statement of case` view, removed the unnecessary bullet point and added the required warning.
This needed a tweak to the stylesheet to align the warning logo with a two-line message.  I added this as a separate class rather than inline to allow re-use.

AP-1129: Update statement of case

---

.circleci/config.yml

Ignore the `uat deploy` job when merging to master. 
Once a PR is merged to master, we shouldn't be deploying to UAT anyway.  This means that the master branch status should be able to be green, as all steps will be completed, rather than remaining amber as at present
This should allow us to still deploy non-master branches to UAT

Circle CI config update

---

.circleci/config.yml

This is the second part of #1132, it removes the `hold_uat` job

Circle CI update

---

app/forms/respondents/respondent_form.rb
app/javascript/src/respondent_detail.js
app/views/providers/respondents/_respondent_detail.html.erb
app/views/providers/respondents/show.html.erb
config/locales/en/activemodel.yml
config/locales/en/helpers.yml
config/locales/en/providers.yml
features/providers/civil_application_journey.feature
spec/factories/respondents.rb
spec/forms/respondents/respondent_form_spec.rb

Add text box for the respondent's police notified question for the  'yes' answer.
[Link to story](https://dsdmoj.atlassian.net/secure/RapidBoard.jspa?rapidView=233&projectKey=AP&modal=detail&selectedIssue=AP-1133)
This was to keep the existing functionality for police notified 'no' answer except allow a textbox to be used for when the answer is 'yes' as-well.
- Update respondent form to validate the text box if the answer is 'yes' or 'no' (true or false)
- Remove :police_notified from the clear_details method as the same text box is used for a yes or no answer and both require it.
- Create respondent javascript file to update the text box label depending on the 'yes' or 'no' answer for police notified. Also update the error messages.
- Update the view to always show the textbox for police …

AP1133 police notified

---

.circleci/config.yml

Saving the gem bundler cache correctly has taken time to run the `Install ruby gems` step in Circle 
from: ![image](https://user-images.githubusercontent.com/6757677/71261109-6ea80c80-2334-11ea-8b47-6bd7e140552c.png)
to:
This is because once CircleCI has run bundle install once, it caches that copy for re-use on subsequent containers.  It will get updated each time we change the Gemfile (i.e. after each dependabot update) but other than that it should speed up the run times.
The test run entirely has moved from:
this afternoon to 
on this build
## Next steps
added issue #1136 for further improvements

CircleCI: Update the gemfile cache

---

.circleci/config.yml

Revert the UAT deploy changes to circle config. 
Deploying master to UAT is needed sometimes.  This reverts the changes that removed the option and tried to make it automatic

Revert circle UAT changes

---

Dockerfile
README.md
bin/cleanup_manual_snapshots
bin/create_manual_snapshot
helm_deploy/apply-for-legal-aid/templates/cronjob-db-backup-cleanup.yaml
helm_deploy/apply-for-legal-aid/templates/cronjob-hourly-db-backup.yaml

Added 2 cronjobs to deal with DB backups.
The first take an hourly snapshot and stores this in our RDS backup storage along side the daily snapshots taken by cloud platforms. Daily snapshots are retained for 7 days.
The second cronjob manages deleting the hourly snapshots. It deletes all but the most recent 30 snapshots every 4 days. We are currently taking 32 per day so this should mean we have approx 2 days of hourly snapshots available in case we need to do a restore.

AP-1126 Add new cronjob for database backups

---

helm_deploy/apply-for-legal-aid/templates/cronjob-hourly-db-backup.yaml

Changed the scheduler, I had misinterpreted and it was running every minute past every hour between 7am and 9pm, this actually meant it was taking a backup every 3 minutes, I assume because thats how long it takes to create a backup. This change now sets it to run at 3 minutes past the hour during the relevant timeframe.

Amend DB backup cronjob schedule

---

app/services/provider_email_service.rb
spec/services/provider_email_service_spec.rb

Redirect provider when citizen completes means
[Link to story](https://dsdmoj.atlassian.net/secure/RapidBoard.jspa?rapidView=233&projectKey=AP&modal=detail&selectedIssue=AP-1164)
Update the url to redirect the provider to the application that the citizen completed means on
To note:
Unfortunately, If the provider is signed out and clicks the link, they will be sent directly to the /providers index page after sign in, instead of the providers_legal_aid_application_client_completed_means_url

AP1164 Redirect provider when citizen completes means

---

.circleci/config.yml
Dockerfile
app/controllers/status_controller.rb
config/routes.rb
spec/requests/status_spec.rb
spec/routing/routes_spec.rb

[Update the status page of Apply](https://dsdmoj.atlassian.net/browse/AP-1162)
This provides:
* a simple `/ping` endpoint that will display static values
(separate PR required to configure values in K8S and CircleCI)
* a dynamic `/healthcheck` endpoint that displays values indicating
up-state of required dependencies
By default the `/status` endpoint will still return the dynamic data
this means that monitoring & K8S should not be impacted.
There will be a subsequent commit to change it to see if K8S deploys
are affected when deployed to UAT

AP-1162: Implement new status controller setup

---

app/controllers/status_controller.rb
spec/requests/status_spec.rb

Remove COMMIT_ID from the status controller
It got removed from the setup in #1164 but not from the display

BugFix: Remove COMMIT_ID from status controller

---

app/javascript/packs/application.js

Proceedings list does not work in Internet Explorer 11
[Link to story](https://dsdmoj.atlassian.net/secure/RapidBoard.jspa?rapidView=233&projectKey=AP&modal=detail&selectedIssue=AP-1181)
Require babel/polyfill via core-js to use promises in javascript
https://babeljs.io/docs/en/babel-polyfill

AP1181 - Bug fix Proceeding Types in IE11

---

.circleci/config.yml
features/support/env.rb
features/support/screenshot_helper.rb

Updates cucumber to save screenshot when features fail
The screenshots will be stored in `tmp/capybara` so the screenshots will be ignored by .gitignore.
The file pattern is:
`folder`-`feature_file_name`-feature-`yearmonthday`T`time`.png
this allows you to see to the state of the page at failure
It will also upload the files in CircleCI, these will be available in the artifacts folder and means that you won't need to scroll through the list of jobs to find the failures

Auto screenshot cucumber failures

---

helm_deploy/apply-for-legal-aid/templates/_helpers.tpl
helm_deploy/apply-for-legal-aid/templates/cronjob-db-backup-cleanup.yaml
helm_deploy/apply-for-legal-aid/templates/cronjob-hourly-db-backup.yaml

database backup cronjobs were running and failing in UAT and staging due to hard coded production values, also we dont need hourly backups of these DBs.
Added a helper in `helpers.tpl` to check if the env is `production` and if it isn't then the cronjob is scheduled to run on 31st February, for both the backup and cleanup scripts

fix issue of running db backups in non-prod env

---

.circleci/config.yml
helm_deploy/apply-for-legal-aid/templates/cronjob-reset-started-apps-counter.yaml

[Link to story](https://dsdmoj.atlassian.net/browse/AP-1160)
Added a cronjob that updates the geckoboard at midnight with the aim of resetting the started applications widget to zero for each day, actually runs at 18 mins past midnight.

Ap 1160 reset counter

---

.rubocop_todo.yml
app/assets/stylesheets/success_message.scss
app/controllers/feedback_controller.rb
app/controllers/saml_sessions_controller.rb
app/helpers/page_template_helper.rb
app/views/feedback/new.html.erb
app/views/feedback/show.html.erb
app/views/shared/forms/_success_message.html.erb
app/views/shared/page_templates/_default_page_template.html.erb
config/locales/en/feedback.yml
spec/requests/feedbacks_spec.rb
spec/requests/saml_sessions_spec.rb

AP1141 - Display the feedback survey upon sign out
[Link to story](https://dsdmoj.atlassian.net/secure/RapidBoard.jspa?rapidView=233&projectKey=AP&modal=detail&selectedIssue=AP-1141)
- Add a successful sign-out message with custom styling
- Update feedback controller
- Remove `redirect_to idp_sign_out_provider_session_url(SAMLRequest: 1)` as we'll no longer be using the LAA Online portal logout page.
- Update tests and relevant I18n translation files

AP1141 Feedback on Signout

---

Gemfile.lock
helm_deploy/apply-for-legal-aid/templates/cronjob-deliver-scheduled-mail.yaml

there was an issue with the name of the branch failing to deply to UAT. the original dependabot update failed, this allows it to be tested in uat before merging
Bumps [prometheus_exporter](https://github.com/discourse/prometheus_exporter) from 0.4.16 to 0.4.17.
- [Release notes](https://github.com/discourse/prometheus_exporter/releases)
- [Changelog](https://github.com/discourse/prometheus_exporter/blob/master/CHANGELOG)
- [Commits](https://github.com/discourse/prometheus_exporter/compare/v0.4.16...v0.4.17)
Signed-off-by: dependabot-preview[bot] <support@dependabot.com>

Bump prometheus_exporter from 0.4.16 to 0.4.17

---

app/services/pdf_converter.rb

Bug fix for NoMethodError: undefined method `pdf_attachment_id' for nil:NilClass
in PdfConverter
- Use Safe Navigation Operator to fix bug

Bug fix for PdfConverter

---

README.md

[Link to story](https://dsdmoj.atlassian.net/browse/AP-1177)
This ticket was to update the apply system to consume the new format returned by the provider details API.  In fact there is nothing to do: the API now returns a new element in it's response to detail the Fee Earners, but we don't use that data and the rest of the structure remains the same.
I have used this opportunity to add a little section to the README to explain how this process works.

AP-1177 Update README to explain Provider details retrieval process

---

package.json
yarn.lock

Reverts ministryofjustice/laa-apply-for-legal-aid#1199
until a fix to use jest 25.1.0 is made as it breaks yarn tests

Revert "Bump jest from 24.9.0 to 25.1.0"

---

helm_deploy/apply-for-legal-aid/templates/cronjob-reset-dashboard-overnight.yaml

When running the command 
```shell
rake job:dashboard:update['Applications FeedbackScores']
```
on the server, it successfully runs the dashboard update for both `Applications` and `FeedbackScores`.
However, when docker/helm executes 
```shell
command: ['rake', "job:dashboard:update[\'Applications FeedbackScores\']"]
```
sidekiq complains about executing `'Applications` and `FeedbackScores'`.
Each has a quote pre- or suffix-ed.
This PR addresses the issue by removing the quotes inside the rake task call.
This is counter-intuitive as it will not work locally or indeed from a command line on the server, but after deploying the build to UAT and manually running the cronjob it seems to work :man_shrugging: 
Attempt 1: escape the quotes : `command: ['rake', "job:dashboard:update[\'Applications …

Fix the cronjob fix

---

.circleci/config.yml

deploy_uat will be an optional step on non-master branches but, when code is merged to master, it will build and deploy to UAT then wait for approval to push to staging and prod environments.
This was deployed in January, but a corruption in the master branch kubernetes pods on UAT caused a false positive so the changes were reverted. 
This will ensure that UAT master is always up to date and surface any issues around the deploy step before it gets to the staging environment.  e.g. a dependabot merge that breaks deploy could be merged to master but not actually deployed until some days later when code is changed and we may not be sure if the code or gem update broke the deploy
Update the circle config file to:-
* make hold_uat and deploy_uat ignore the master branch
* add an …

Modify CircleCI to auto deploy master merges

---

.circleci/config.yml

Fix the master auto-uat deploy
This solution was tested multiple times on the branch prior to rebasing. 
In all cases, the branch successfully built and deployed to UAT with no user intervention.
I then reverted the step to only run on master and squashed the commits

Fix: Circle CI automatically deploy master branches to UAT

---

.rspec
app/models/provider.rb
features/support/env.rb
spec/models/legal_aid_application_spec.rb
spec/models/provider_spec.rb
spec/requests/providers/check_benefits_spec.rb
spec/requests/providers/legal_aid_applications_spec.rb

Set RSpec to run the tests in random, this helps to ensure that tests truly pass and that early-run tests are not changing the set-up for subsequent ones
1. locally run the tests randomly and fix tests that regularly fail 
1. push each individual commit to github, this will ensure they still work when run sequentially
1. set the .rspec file to `--order rand`

Make test sequence random

---

bin/delete_uat_release
bin/uat_deploy

The regex for removing the dots in dependabot PR names were in the
bin scripts as well as circle/config.

FIX: Circle update the bin/uat scripts

---

app/models/transaction_type.rb
app/services/ccms/attribute_value_generator.rb
config/ccms/attribute_block_configs/base.yml
config/ccms/attribute_block_configs/non_passported.yml
spec/factories/transaction_types.rb
spec/models/legal_aid_application_spec.rb
spec/models/transaction_type_spec.rb
spec/services/ccms/requestors/case_add_requestor_xml_blocks/non_passported_attributes_spec.rb

AP1197 Add non-passported outgoing transaction attributes for legal_aid and maintenance_out to CCMS payload
[Link to story](https://dsdmoj.atlassian.net/secure/RapidBoard.jspa?rapidView=233&projectKey=AP&modal=detail&selectedIssue=AP-1197)
- Add two outgoing transactions attributes maintenance_out and legal_aid (criminal legal aid payments) into the non-passsported flow.
- Add `.for_outgoing_type?` to help with retrieval of required outgoing transactions data.
- Update tests
To note: The method calls for outgoing_* attributes should end in a '?' as it returns a boolean value. I've amended the case for OUTGOING attributes in the attribute_value_generator to use `.chomp('?'))`

AP1197 Add legal_aid and maintenance_out attributes to CCMS payload

---

app/helpers/page_template_helper.rb
app/views/providers/application_confirmations/show.html.erb
app/views/shared/page_templates/_default_page_template.html.erb

allow nil page_titles as this supresses a `Headings must not be empty` accessibility warning in the nightly build

FIX: remove webhints accessibility warning

---

app/views/shared/forms/_savings_and_investments_form.html.erb
app/views/shared/forms/other_assets/_form.html.erb
features/providers/civil_application_journey.feature

[Link to story](https://dsdmoj.atlassian.net/browse/AP-1310)
Update the `none of these` checkboxes on savings and investments and assets views for providers
It was possible, after going backward and forwards to submit the forms with no checkboxes selected
This was because the `true` value was being stored as the value of the attribute rather than just true or empty

AP-1310: Update `none of these` checkbox handling

---

app/controllers/providers/offline_accounts_controller.rb
app/forms/savings_amounts/offline_accounts_form.rb
app/forms/savings_amounts/savings_amounts_form.rb
app/models/concerns/capital.rb
app/models/provider.rb
app/services/flow/flows/provider_capital.rb
app/services/flow/flows/provider_vehicle.rb
app/views/providers/offline_accounts/show.html.erb
app/views/shared/check_answers/_assets.html.erb
app/views/shared/forms/_offline_accounts_form.html.erb
config/locales/en/activemodel.yml
config/locales/en/providers.yml
config/locales/en/shared.yml
config/routes.rb
db/migrate/20200310162254_add_no_accounts_selected_to_savings_amount.rb
db/schema.rb
features/providers/check_your_answers.feature
features/providers/civil_application_journey.feature
features/providers/complete_and_check_means_answers.feature
features/providers/non_passported_journey.feature
spec/forms/savings_amounts/offline_accounts_form_spec.rb
spec/forms/savings_amounts/savings_amounts_form_spec.rb
spec/requests/providers/check_passported_answers_spec.rb
spec/requests/providers/offline_accounts_spec.rb
spec/requests/providers/savings_and_investments_spec.rb
spec/requests/providers/vehicles/regular_uses_spec.rb
spec/requests/providers/vehicles_spec.rb
spec/services/ccms/requestors/case_add_requestor_xml_blocks/non_passported_variable_attributes_spec.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-1220)
- create new `OfflineAccountsController`
- create new `OfflineAccountsForm`
- create new view for `OfflineAccounts`
- remove reference to `offline_current_accounts` and `offline_savings_accounts` from `SavingsAmountFrom` and `SavingsAndInvestmentsController`
- Updated flow to go to Offline accounts after vehicles

AP-1220 Ask about accounts on separate page

---

app/controllers/citizens/declarations_controller.rb
app/controllers/providers/about_the_financial_assessments_controller.rb
app/controllers/providers/check_passported_answers_controller.rb
app/controllers/providers/check_provider_answers_controller.rb
app/models/concerns/legal_aid_application_state_machine.rb
app/services/flow/flows/provider_capital.rb
app/services/test_application_creation_service.rb
config/locales/en/model_enum_translations.yml
db/migrate/20200319152301_replace_state_value.rb
features/step_definitions/civil_journey_steps.rb
spec/factories/legal_aid_applications.rb
spec/requests/citizens/declarations_spec.rb
spec/requests/providers/about_the_financial_assessments_spec.rb
spec/requests/providers/check_merits_answers_spec.rb
spec/requests/providers/check_passported_answers_spec.rb
spec/requests/providers/check_provider_answers_spec.rb
spec/requests/providers/means_summaries_spec.rb
spec/requests/providers/restrictions_spec.rb

Rename state means_completed to provider_assessing_means
[Link to story](https://dsdmoj.atlassian.net/secure/RapidBoard.jspa?rapidView=233&projectKey=AP&modal=detail&selectedIssue=AP-1323)

Rename state means_completed to provider_assessing_means

---

app/controllers/providers/declarations_controller.rb
app/views/providers/declarations/show.html.erb
app/views/providers/legal_aid_applications/index.html.erb
config/locales/en/providers.yml
config/routes.rb
features/providers/civil_application_journey.feature
features/step_definitions/civil_journey_steps.rb
spec/requests/providers/declarations_spec.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-1311)
Implement a new view and route handling for a provider declaration before they add the user data

AP-1311: Move provider declaration

---

app/views/shared/forms/_list_items.html.erb

Webhint raised an issue where `li` tags should be directly inside `ul` tags
Moving the `strong` tag inside the `li` tags makes webhint happy

Fix: list-item display

---

db/migrate/20200327115015_update_name_in_transaction_types.rb
db/migrate/20200327115101_add_column_to_transaction_types.rb
db/schema.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-1336)
2 migrations - first renames pension to private_pension
second migration adds a new boolean column and sets the relevant boolean value.

AP-1336 Update seed data and add column

---

app/services/cfe/base_service.rb
app/services/cfe/obtain_assessment_result_service.rb
features/cassettes/Civil_application_journeys/Receives_benefits_and_completes_the_application.yml
spec/services/cfe/obtain_assessment_result_service_spec.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-1309)
- Added header to call from CFW::ObtainAssessmentResultService to instruct CFE to return result in V2 format
- A CFE::V2::Result record in automatically created in place of a CFE::V1:Result
- Result page uses the same method calls to display results and interim values

AP-1309 all calls to use V2 of CFE API

---

app/services/cfe/create_dependants_service.rb
spec/services/cfe/create_dependants_service_spec.rb
spec/services/cfe/create_other_income_service_spec.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-1333)
- Added `CFE::CreateDependantsService`
This branch was taken from Ap-1335, so contains those changes as well.  best reviewed after AP-1335 has been merged to master, and this branch rebased on master.

AP-1333 Create Dependants Service

---

app/models/transaction_type.rb
db/migrate/20190313174812_add_archived_at_to_transaction_types.rb
spec/models/transaction_type_spec.rb

Change TransactionType populate to add a `populate_without_income` class method
This allows the early migration not to try and update a column that has not been created yet
It was simpler to update one call rather than make all the other calls use a `populate_with_income` variant

FIX: Update TransactionType seeding to fix broken migration

---

app/views/providers/income_summary/index.html.erb
app/views/providers/transactions/show.html.erb
config/locales/en/providers.yml
config/locales/en/transaction_types.yml
features/providers/civil_application_journey.feature
features/providers/complete_and_check_means_answers.feature
features/providers/non_passported_journey.feature
spec/requests/providers/transactions_spec.rb

AP1341 Content updates to help provider with how to categorise income
[Link to story](https://dsdmoj.atlassian.net/secure/RapidBoard.jspa?rapidView=233&projectKey=AP&modal=detail&selectedIssue=AP-1341)
- Update and add content on the /income_summary page
- Update and add content on the transaction pages for each income category
- Update tests

AP1341 Content updates to income summary and transactions pages

---

app/controllers/providers/used_delegated_functions_controller.rb
spec/requests/providers/used_delegated_functions_spec.rb

A Scheduled Mailing ERROR was being sent to sentry [here](https://sentry.service.dsd.io/mojds/apply-for-legal-aid/issues/48883/). 
Scheduled Mailing was sending and retrying to send SubmitApplicationReminderMailer email even though one of its values needed used_delegated_functions. The solution was to not send that email when the used_delegated_functions is false.
[Link to story](https://dsdmoj.atlassian.net/secure/RapidBoard.jspa?rapidView=233&projectKey=AP&modal=detail&selectedIssue=AP-1387)
- Don't send reminder mailer when the provider did not use delegated functions.
- Update tests

AP1387 Scheduled Mailing bug when used delegated functions is false

---

app/models/dashboard/widget_data_providers/total_declined_open_banking.rb
app/models/legal_aid_application.rb
app/services/dashboard_event_handler.rb
spec/factories/legal_aid_applications.rb
spec/models/dashboard/widget_data_providers/total_declined_open_banking_spec.rb

Track total of applicants that have said 'No' to open banking consent
[Link to story](https://dsdmoj.atlassian.net/secure/RapidBoard.jspa?rapidView=233&projectKey=AP&modal=detail&selectedIssue=AP-1369)
Add dataset for total_declined_open_banking
Update tests

AP1369 Declined open banking consent tracker

---

app/controllers/providers/income_summary_controller.rb
app/models/legal_aid_application.rb
app/views/providers/income_summary/_income_type_item.html.erb
app/views/providers/income_summary/index.html.erb
config/locales/en/activemodel.yml
features/providers/non_passported_journey.feature
features/step_definitions/civil_journey_steps.rb
spec/factories/bank_transactions.rb
spec/factories/legal_aid_applications.rb
spec/models/legal_aid_application_spec.rb
spec/requests/providers/income_summary_spec.rb

AP1340 Validation for categorising bank transactions
[Link to story](https://dsdmoj.atlassian.net/secure/RapidBoard.jspa?rapidView=233&projectKey=AP&modal=detail&selectedIssue=AP-1340)
The BankTransaction model belongs_to a TransactionType, optionally (optional: true). Therefore, on the income summary page, you could have transaction_types on the model such as '1. Benefits' but no bank transactions were added or are associated with it. I added validation on the legal aid application model to check that those transaction types on the model have one or more bank transactions. If not then add relevant errors.
**I've listed each step in the commit messages instead of overdoing this PR message.** Please have a look at them [here](https://github.com/ministryofjustice/laa-apply-for-legal-aid/pull …

AP1340 Validation for categorising bank transactions

---

app/controllers/citizens/additional_accounts_controller.rb
app/services/flow/flows/citizen_start.rb
app/views/citizens/additional_accounts/new.html.erb
config/locales/en/citizens.yml
config/locales/en/helpers.yml
features/cassettes/Citizen_journey/Follow_citizen_journey_from_Accounts_page.yml
features/citizens/citizens.feature
spec/requests/citizens/additional_accounts_spec.rb

AP1375 Contact Solicitor if additional bank accounts are offline
[Link to story](https://dsdmoj.atlassian.net/secure/RapidBoard.jspa?rapidView=233&projectKey=AP&modal=detail&selectedIssue=AP-1375)
When a citizen has_offline_accounts:
- Redirect citizen to contact_provider page in the flow.
- Update state to :use_ccms!
- Remove hint text "If you do not, you will need to provide paper evidence for these accounts"
- Allow user to go back and change the answer by updating the state to :provider_submitted
Also:
- Rename param from **:has_offline_accounts** to **:has_online_accounts** since that's what we're asking the user.
Update the feature tests

AP1375 Contact Solicitor if additional bank accounts are offline

---

app/mailers/feedback_mailer.rb

https://mojdt.slack.com/archives/GBGST41DE/p1590055157054400?thread_ts=1590054242.053200&cid=GBGST41DE
The email that the Apply team receive when feedback is provided uses true/false as the answer to the first question. This PR changes it so we use Yes/No instead, in keeping with how the question is asked on the ```/feedback/new``` page

change text for boolean

---

app/services/cfe/create_assessment_service.rb
spec/cassettes/CFE_SubmissionManager/_call/completes_process.yml
spec/services/cfe/create_assessment_service_spec.rb

AP1444 Use new CFE Assessment POST response
[Link to story](https://dsdmoj.atlassian.net/secure/RapidBoard.jspa?rapidView=233&projectKey=AP&modal=detail&selectedIssue=AP-1444)
Get assessment_id from the response instead of the :objects key (which is soon to be removed/deprecated)

AP1444 Use new CFE Assessment POST response

---

app/services/ccms/requestors/non_passported_case_add_requestor.rb
config/ccms/attribute_block_configs/non_passported.yml
spec/services/ccms/requestors/case_add_requestor_xml_blocks/non_passported_attributes_spec.rb
spec/services/ccms/requestors/case_add_requestor_xml_blocks/passported_attributes_spec.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-1428)
The `NonPassportedCaseAddRequestor` derives from the `CaseAddRequestor` - however it doesn't inherit the value of the class method `wsdl_location`.  This fixes that.

AP-1428 add WSDL location to non-passported case add requestor

---

.rubocop.yml
app/controllers/citizens/citizen_base_controller.rb
app/models/legal_aid_application.rb
app/presenters/applicant_account_presenter.rb
app/services/ccms/attribute_value_generator.rb
app/services/ccms/requestors/applicant_add_requestor.rb
app/services/cfe/submission_manager.rb
app/services/cleanup_capital_attributes.rb
app/services/flow/base_flow_service.rb
app/services/legal_aid_applications/calculation_date_service.rb
app/services/mock_benefit_check_service.rb
app/services/true_layer/bank_data_import_service.rb
app/views/providers/declarations/show.html.erb
app/views/shared/forms/_applicant_form.html.erb
config/locales/en/providers.yml
features/support/env.rb
spec/requests/providers/applicants_spec.rb
spec/requests/providers/legal_aid_applications_spec.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-1389)
- renamed the back button to Home on the declarations page
- renamed the home button to Back on the client details page
- implemented latest rubocop checks

AP-1389 Rename Home and Back liks

---

app/javascript/src/respondent_detail.js
app/lib/govuk_elements_form_builder/form_builder.rb
app/views/providers/respondents/_respondent_detail.html.erb
spec/lib/govuk_elements_form_builder/form_builder_spec.rb

AP1115 Fix screen reader issues with multiple H1s on the Respondants page
[Link to story](https://dsdmoj.atlassian.net/secure/RapidBoard.jspa?rapidView=233&projectKey=AP&modal=detail&selectedIssue=AP-1115)
- Allow the use of a h2 tag for govuk_collection_radio_buttons
- Add htag param to fieldset_legend method on form builder
- Update the respondent page to use this instead
- Update tests
**Another bugfix:**
- Fix voiceover bug with using class 'govuk-visually-hidden' because the screen reader reads whatever is inside it aloud even if it's hidden. Instead use class 'govuk-radios__conditional--hidden' for this, which hides it from the screen reader too if it's not showing on the page.
e.g. visually hidden (visually hides) but doesn't hide from the screenreaders/the ear.
Co-authored-by: …

AP1115 Fix screen reader issues with multiple H1s on the Respondants page

---

.circleci/config.yml
Gemfile
Gemfile.lock

This is a pre-cursor to turning on paralellism.
With these timings in place, we should be able to assess and properly run the test in parallel
should we ever need to.  They will also allow us to use CircleCI insights to monitor the state of the tests for issues.

CircleCI Update: Enable test timings

---

app/controllers/citizens/additional_accounts_controller.rb
spec/requests/citizens/additional_accounts_spec.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-1446)
When the client arrives on the 'citizens/additional_accounts' page, the state is reverted to 'provider_submitted' and the boolean 'has_offline_accounts' is set to nil. This requires the client to make a selection before leaving the page (particularly relevant on a re-visit, as currently the initial response is stored and not changed). This allows the user to change their mind about additional accounts at any point in the subflow and to use the back buttons to amend their answers.

AP-1446 Flow around offline bank accounts

---

app/models/legal_aid_application.rb
app/services/true_layer/api_client.rb
spec/services/true_layer/bank_data_import_service_spec.rb
spec/services/true_layer/importers/import_transactions_service_spec.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-1486)
TrueLayer have confirmed that it is because we are asking for transactions in the future, i.e. our end date isn't in the past.
Reverted the calls to truelayer to be `DateTime` instead of simply `Date`
According to #771 
> because TrueLayer's filter is only granular to the date anyway, not the time
This reverts the `to_date` to the beginning of the chosen day, either today or the delegated_permission date, depending.

AP-1486: true layer date formatting

---

app/services/benefit_check_service.rb
spec/services/benefit_check_service_spec.rb

AP1485 BugFix - Return false after a Raven.capture_exception
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1485)
Return false after a Raven.capture_exception this is because our app gets the result and tries to dig into the hash result
but as it's a Raven event it raises another sentry error of "undefined method `dig' for #<Raven::Event"
Update tests for catching Savon::SOAPFault error and a StandardError

AP1485 BugFix - Return false after a Raven.capture_exception

---

app/controllers/providers/check_benefits_controller.rb

We got an invalid transition exception on the live system - this fixes that.

Guard against transitioning to use_ccms if already there

---

app/models/irregular_income.rb
app/models/legal_aid_application.rb
app/views/citizens/check_answers/_student_finance.html.erb
app/views/citizens/check_answers/index.html.erb
config/locales/en/citizens.yml
spec/factories/irregular_incomes.rb
spec/factories/legal_aid_applications.rb
spec/requests/citizens/check_answers_spec.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-1466)
Added a `student_finance` module to the check your answers page. If the client has student finance it will also show the value, otherwise this section is hidden. Created a factory for irregular incomes.

Ap 1466 student finance cya

---

spec/javascript/worker_waiter.spec.js

The error was "TypeError: Cannot assign to read only property 'reload' of object '[object Location]'"
This is related to this issue https://github.com/facebook/jest/issues/9471
It is a workaround to fix the yarn test failure by mocking out window.location
This was caused when upgrading jest to version 26

BugFix jest(jsdom) issue for window.location.reload

---

.circleci/config.yml

In an attempt to help debug the dropping code-coverage issue I have added this output in circle
If your unit-test job fails with code-coverage of 99.94% it will output the simplecov report to the artifacts tab.  
You can double click on index to open the report and see what has failed.  This may be of use longer-term but it is primarily to diagnose the issue currently occurring.

FIX: Store coverage output as artifact

---

.circleci/config.yml

BugFix Run JavaScript tests in CircleCI as part of unit tests job
The problem was that JavaScript tests weren't running as part of CircleCI.
- Reuse the javascript_tests rake command to run our javascript tests in circle ci job called unit_tests

BugFix Run JavaScript tests in CircleCI as part of unit tests job

---

config/locales/en/shared.yml

[Link to story](https://dsdmoj.atlassian.net/browse/AP-1470)
The means report contains `Total disposable income asssessed`. This removes the extra `s` so that `assessed` is spelled correctly.

AP-1470 Fix typo on means report

---

Gemfile
Gemfile.lock
Guardfile

Add cucumber to guard
A patch release when I implemented this originally and broken the cucumber-guard integration, now they've re-aligned the versions and it's functioning again

FIX: Add cucumber to guard

---

README.md
app/services/cfe/create_state_benefits_service.rb
spec/factories/bank_transactions.rb
spec/services/cfe/create_state_benefits_service_spec.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-1490)
There are two issues here:
* When the `state_benefits` payload is created to be sent to CFE, it is only including transactions marked as `benefits` by the solicitor, not `excluded_benefits`.
* When the `state_benefits` payload is created to be sent to CFE, it includes the metadata `name` of the benefit type, however CFE is expecting to receive the metadata `label`. This means all benefits are being classified as `other` in CFE.
This PR:
*  adds `excluded_benefits` to the select logic in `CreateStateBenefitsService` so that all benefit transactions are passed to CFE. It also fixes a bug in the `bank_transactions` factory which was masking this problem.
* amends `CreateStateBenefitsService` to use the metadat `label` , not name.
* …

AP-1490 Disregarded benefits not being sent to CFE

---

app/views/providers/address_selections/show.html.erb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-1118)
added an alert to the postcode so that screenreaders will use this to confirm to the user the postcode they have selected

AP-1118 add an alert for screenreaders

---

app/models/concerns/legal_aid_application_state_machine.rb
app/views/providers/check_benefits/_check_benefits_result.html.erb
app/views/providers/check_benefits/_how_we_checked.html.erb
app/views/providers/check_benefits/_use_ccms.html.erb
config/locales/en/providers.yml
features/cassettes/Civil_application_journeys/I_am_instructed_to_use_CCMS_on_the_passported_journey_with_an_applicant_does_not_receive_benefits.yml
features/providers/civil_application_journey.feature
features/providers/non_passported_journey.feature
features/step_definitions/civil_journey_steps.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-1513)
When a provider receives a negative DWP check result on the passported journey, they do not have the option to change the applicant's details. They do have this option on the non-passported journey.
This commit moves the code which displays the applicant's details, including the link to change them, to a new partial which is now used on both pages. It also refactors the providers translations to move wordings to the new partial, and adds a feature test for this scenario.

AP-1513 change passported client details

---

app/helpers/user_transactions_helper.rb
app/models/transaction_type.rb
features/citizens/citizens.feature
spec/factories/legal_aid_applications.rb
spec/helpers/user_transactions_helper_spec.rb
spec/models/transaction_type_spec.rb

AP1451 Don't show disregarded benefits on the applicants check answers page
- Update the UserTransactionsHelper to skip excluded benefit transaction types from showing on the citizen check answers.
- Update TransactionType model with method #excluded_benefit? instead of doing that logic in the above helper
- Add test for UserTransactionsHelper
- Update Feature Tests and TransactionType tests

AP1451 Don't show disregarded benefits on the applicants check answers page

---

app/services/ccms/attribute_value_generator.rb
config/ccms/attribute_block_configs/base.yml
config/ccms/attribute_block_configs/non_passported.yml
spec/services/ccms/requestors/case_add_requestor_xml_blocks/non_passported_variable_attributes_spec.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-1517)
To ensure the income contribution amount calculated by CFE is received by CCMS so that it can be displayed in PUI and correspondece, the attributes `INCOME_CONT` and `OUT_INCOME_CONT` and `PUI_CLIENT_INCOME_CONT` need to be included in the case creation payload populated with the income contribution value.
To achieve this:
- remove `OUT_INCOME_CONT` and `PUI_CLIENT_INCOME_CONT` from `attribute_block_configs/base.yml`
- add `OUT_INCOME_CONT` to `attribute_block_configs/non-passported.yml`
- fix `PUI_CLIENT_INCOME_CONT` in `attribute_block_configs/non-passported.yml` so that it includes the income contribution, not the capital contribution
- leave `INCOME_CONT` in `attribute_block_configs/base.yml` as it is currently being used …

AP-1517 Send correct income contribution to CCMS

---

app/controllers/auth_controller.rb
app/controllers/citizens/consents_controller.rb
config/initializers/omniauth.rb
config/locales/en/citizens.yml
spec/requests/auth_spec.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-1518)
The applicant authentication at the bank is handled by OmniAuth through True Layer.  If the applicant fails to authenticate, then the default action in development mode is to raise an exception, and in production mode to redirect the callback to `/auth/failure`.  This controller action handles failed provider logins to the Apply system as well as failed applicant bank logins..
- added a configuration directive to the OmniAuth initializer config to keep the same behaviour as in development as in production,  (i.e. to redirect to `/auth/failure`)
- in the `AuthController#failure` action, detect those requests which are as a result of a TrueLayer auth fail (the origin parameter will be `/citizens/banks`) and redirect them to …

AP-1518 Gracefully handle True Layer auth errors

---

app/models/concerns/legal_aid_application_state_machine.rb

Steps to reproduce
* start passported claim
* Say yes to delegated functions
* Yes to make substantive now - save and continue
* back button, change to no
and the transition will fail
This fix allows a user to transition from
:provider_used_delegated_functions to :provider_entering_means
ans allows a user to change their mind around progressing
with a substantive application

FIX: Update provider_used_delegated_functions event

---

db/migrate/20200724083605_add_new_provider_table_fields.rb
db/schema.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-1314)
Add new fields to the Provider table. This ticket no longer updates the contact_id field and the default for the portal_enabled should be true. These changes are detailed on a comment in the ticket.

AP-1314 Add new fields to the Provider(User) table

---

app/services/mock_provider_details_retriever.rb
app/services/provider_details_retriever.rb
spec/cassettes/encoded_provider_details_api.yml
spec/cassettes/provider_details_api.yml
spec/services/mock_provider_details_retriever_spec.rb
spec/services/provider_details_retriever_spec.rb

Bug Fix this sentry issue [ProviderDetailsRetriever::ApiError](https://sentry.service.dsd.io/mojds/apply-for-legal-aid/issues/40113/)
In the ProviderDetailsRetriever the method [encode_www_form_component](https://apidock.com/ruby/v1_9_3_125/URI/encode_www_form_component/class) method converts a space to a + which fails to retreive information for a provider username that has a space in it "John Lang" > "John+Lang" but instead use %20 which works "John Lang" > "/John%20Lang"
Update tests

Update ProviderDetailsRetriever to replace space with %20 in url

---

app/services/provider_details_creator.rb

We now use permissions to decide whether or not provider firms can process passported or non-passported applications beyond the DWP check, but we forgot to assign passported permissions as a default to all new firms being created (which happens when a provider user from that firm logs in for the very first time).
This bugfix rectifies that.

Bugfix 2807 add permissions to new firms as they are created

---

Dockerfile
app/models/concerns/legal_aid_application_state_machine.rb

The state machine was not allowing transition from use_ccms to entering_applicant_details which is required if they first get a negative benefit check result, and then go back and change the details.

BUGFIX - allow transition from use_ccms to entering_applicant_details

---

app/models/concerns/legal_aid_application_state_machine.rb

Invalid transition caused an error when clicking the back button to go back to the /substantive_application
Fix the above issue by updating the state machine

BugFix InvalidTransition error after clicking back button to get back to /substantive_application page

---

app/views/shared/forms/_identify_types_of_outgoings_form.html.erb
app/views/shared/forms/_types_of_income_form.html.erb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-1534)
Because these pages do not use forms we cannot use the
`shared/show_errors` partial so I've added manual spans using
the usual gov_uk error classes and an ID tag that allows
the header box error link to pass focus to the form group

AP-1534: Add Error message outputs

---

app/assets/stylesheets/providers/legal_aid_applications.scss

[Link to story](https://dsdmoj.atlassian.net/browse/AP-1531)
The page shows a table with a form embedded in the final cell for removing the transaction.  
As it’s a form it uses an input type button to submit the form.
GOVUK design system buttons should look like this 
---
To make the submission look like a link it was styled with a css class `button-as-link` that spoofs the look of a `govuk-link` but did not include the focus state.
I have extended the hacky CSS override with a focus state that also mimics a `govuk-link` this should work for keyboard users but may need further investigations after the in depth accessibility review

AP-1531: Add focus state to button-as-link

---

app/views/admin/feedback/_feedbacks.erb
config/locales/en/admin.yml

[Link to story](https://dsdmoj.atlassian.net/browse/AP-1394)
This will allow admin users to identify different sources of feedback.
This was already in the database and fulfills the original requirement of the ticket.
There was discussion during dev-time around storing the path, but this has been pushed back to a larger scoped ticket.

AP-1394: Add source column to feedback admin page

---

app/models/concerns/passported_state_machine.rb

Allow transitioning, via the back button (presumably) from provider_entering_merits

FIX: Update check_passported_answers event

---

db/migrate/20200729140115_remove_legal_aid_application_state_column.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-1461)
This is the final clear up PR for AP-1461. It removes the column now that we have successfully migrated the data

AP-1461: Remove the LegalAidApplication state column

---

Gemfile
Gemfile.lock

Following a bump of the `aasm` gem from `5.0.8` to `5.1.0`, the following warning is displayed:
```
[DEPRECATION] :after_commit AASM callback is not safe in terms of race conditions and redundant calls.
Please add `gem 'after_commit_everywhere', '~> 0.1', '>= 0.1.5'` to your Gemfile in order to fix that.
```
This commit adds the `after_commit_everywhere` gem as recommended.

Fix AASM deprecation warning

---

app/controllers/admin/firms_controller.rb
app/controllers/admin/providers_controller.rb
app/controllers/admin/user_dashboard_controller.rb
app/services/admin/provider_details_service.rb
app/views/admin/firms/index.html.erb
app/views/admin/providers/check.html.erb
app/views/admin/providers/index.html.erb
app/views/admin/providers/new.html.erb
app/views/admin/user_dashboard/index.html.erb
app/views/layouts/admin.html.erb
config/locales/en/activemodel.yml
config/locales/en/admin.yml
config/locales/en/layouts.yml
config/routes.rb
db/schema.rb
spec/requests/admin/firms_spec.rb
spec/requests/admin/providers_spec.rb
spec/services/admin/provider_details_service_spec.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-1316)
This PR provides a screen to add new provider users to the system.  It first checks that the username is known to CCMS by contacting the ProviderDetails API, and if it is, displays back the firm name to confirm adding.
The work is done by the `Admin::ProviderDetailsService` which has a `#check` and `#create` methods. The firm and any office records are added as required.
The old `ProviderDetailsRetriever` and `ProviderDetailsCreator` services will be retired once we switch over to using the new method of adding users.

AP-1316 - Add users

---

app/services/provider_details_creator.rb
db/migrate/20200803154318_remove_details_response_from_providers.rb
db/schema.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-1315)
The field `details_response` is no longer needed on the `Provider` model. This PR removes it and any references to it in code.

AP-1315 Remove details_response from Provider

---

app/models/provider.rb
spec/factories/firms.rb
spec/models/provider_spec.rb

Firms' should have a default permission of passported and therefore if there is none then
send a message to sentry via raven.
Unlikely but it's better to be safe than sorry.
- Add Raven capture message if a Firm has no permissions at all using `Raven.capture_message`

Notify sentry when a Firm has no permission

---

app/controllers/citizens/resend_link_requests_controller.rb
app/mailers/resend_link_request_mailer.rb
app/views/citizens/resend_link_requests/update.html.erb
config/govuk_notify_templates.yml
config/locales/en/citizens.yml
spec/mailers/resend_link_request_mailer_spec.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-614)
Most of the work on this ticket had already been done (the pages already existed), however the request for a new link sent an email to the apply-for-legal-services email address, which informed us that a clienbt had requested a new link and it noted which client and which application. I have replaced this functionality  so that a new email is sent to the client with a new link.
As a result we may want to remove the template `new_link_request` as this is no longer used.

Ap 614 reminder email client

---

.circleci/config.yml

This does two things to the circle merge & deploy process
It makes the deploy to master UAT optional
* for the duration of the DAC tetsing we should avoid merging code
unless it is an accessibility update required for them to complete tests
* it runs the production hold notification as a stub, this allows us to
deploy to production without waiting for the message to appear in slack,
sometimes for bugfixes, we are monitoring closely and the addition 30
second delay can be excruciating.  It also mirrors the flow in CFE, but
I forgot to replicate it back when I made the original changes!

DAC: Update Circle CI

---

.circleci/config.yml

Add hold_master_uat approval step, this allows us to hold back code changes from UAT master
I added the notification, but forgot the approval step!

DAC: fix master UAT deploys

---

app/services/provider_details_creator.rb
spec/services/provider_details_creator_spec.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-1592)
Update the ProviderDetailsCreator to add methods to set the contact_id for the provider.  Having read the README and
looking at the SamlSessionsController, I think this will update details each
time a user logs in.

AP-1592: Ensure provider contact ID presence

---

app/models/cfe/base_result.rb
features/providers/civil_application_journey.feature
spec/models/cfe/v2/result_spec.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-1557)
When the feature to require manual checking of applications is enabled, incorrect means results are displayed. The same text is always displayed regardless of the result, and refers to restrictions on assets, even if restrictions do not apply. This text should only be displayed if restrictions do apply; in all other cases the correct result text should be displayed.
To fix this, this PR amends the logic in the `overview` method of the `CFE::BaseResult` class so that `manual_check_required` is only returned when restrictions apply. In all other scenarios the correct result will be returned and the relevant text displayed on screen.

AP-1557 Display correct means result when manual_check_required is set

---

app/views/citizens/legal_aid_applications/index.html.erb
spec/requests/citizens/legal_aid_applications_spec.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-1566)
Include the provider firm name on `citizens/legal_aid_applications` so that it displayed to the applicant.

AP-1566 Display firm name to citizen

---

app/services/provider_details_creator.rb
spec/services/provider_details_creator_spec.rb

The data returned from the providerDetails API is inconsistent and doesn't always match the MockProviderDetailsRetriever 
Sometimes it returns an encoded name that we store as `provider.name` e.g. FIRST%20LAST_NAME, sometimes it's a value we store as `provider.email` and, it appears, sometimes it's a value we store as `provider.username`
This solution should match any of the local values we store to ensure the record gets updated on login

FIX: Update ProviderDetailsCreator

---

app/javascript/src/modules/proceedings.js
app/views/providers/proceedings_types/index.html.erb
config/locales/en/providers.yml

AP1562 Proceeding Types: Inform screen reader users to tab out of serach box to see results
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1562)
- Add a span tag with class attribute 'govuk-visually-hidden' and a role attribute with alert.
- Update the span tag with javascript when proceeding types result is returned. This causes the role alert to alert a screen reader that a change has been made and reads out the message to tab out of the search box when results appear below the search box.
The above should work for Chrome and JAWS users etc.
**Extra for Safari browser:**
The Safari browser doesn’t alert messages when the focus is on the search box - Not to my knowledge. Instead it reads out the content of the input field and overrides any alerts / role='alert' 
Similar to this …

AP1562 Proceeding Types: Inform screen reader users to tab out of serach box to see results

---

app/assets/stylesheets/helpers.scss
app/views/providers/submitted_applications/show.html.erb

AP1567 Add a page break before sections for print view
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1567)
Update the print view of the submitted applications page by adding a css style page break
before certain sections: 
- Income, regular payments and assets
- merits
- client declaration (signature)
The image below shows that 'Income, regular payments and assets' heading is now on its own page rather than on the first page. This means that it's easier to read.

AP1567 Add a page break before sections for print view

---

Dockerfile
app/views/citizens/identify_types_of_incomes/show.html.erb
app/views/citizens/identify_types_of_outgoings/show.html.erb
app/views/providers/identify_types_of_incomes/show.html.erb
app/views/providers/identify_types_of_outgoings/show.html.erb
app/views/shared/forms/_identify_types_of_outgoings_form.html.erb
app/views/shared/forms/_types_of_income_form.html.erb
spec/requests/citizens/identify_types_of_incomes_spec.rb
spec/requests/citizens/identify_types_of_outgoings_spec.rb
spec/requests/providers/identify_types_of_incomes_spec.rb
spec/requests/providers/identify_types_of_outgoings_spec.rb

AP1555 Show expanded detail only for citizen on the types of income and outgoing pages
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1555)
Update types of income and outgoing pages for provider and citizen by showing expanded details for the
Citizen but not for the provider
Test the above logic

AP1555 Show expanded detail only for citizen on the types of income and outgoing pages

---

app/models/concerns/base_state_machine.rb
spec/requests/providers/check_benefits_spec.rb

Bug fix for a transition error on the check provider answers
A transition error occurred [here](https://sentry.service.dsd.io/mojds/apply-for-legal-aid/issues/62316/?referrer=slack)
> AASM::InvalidTransitionProviders::CheckBenefitsController#index
> Event 'applicant_details_checked' cannot transition from 'provider_entering_means'
This happens when the provider clicks the back button on the check provider answers page instead of clicking the change links on that page.
- Fix the above error by allowing providers to click the back button on the check provider answers page.
- Test this.

BUGFIX AASM Transition error on check provider answers page

---

app/assets/stylesheets/providers/legal_aid_applications.scss
app/views/providers/check_benefits/_how_we_checked.html.erb
app/views/providers/check_benefits/_use_ccms.html.erb
app/views/providers/use_ccms/show.html.erb
config/locales/en/providers.yml

[Link to story](https://dsdmoj.atlassian.net/browse/AP-1378)
On `/check_benefits`, there are two places where, when a link has focus, white text is displayed on a yellow background. This contrast is not accessible.
There are two different solutions to fix these:
1) remove inline styling from the `govuk-details__summary` in the `_how_we_checked partial` which was setting the text colour to white, and replace it with CSS. This styling has lower precedence and allows the inherited black colour to be used as expected when the element has focus.
2) add a CSS class to style links as black when they have focus, and add this in the relevant places.
In addition to fixing the two identified issues in the ticket, this also fixes them in two additional places - on the `Back to my applications` links …

AP-1378 Fix colour contrast on check_benefits

---

app/views/providers/email_addresses/show.html.erb
config/locales/en/providers.yml
features/providers/civil_application_journey.feature

[Link to story](https://dsdmoj.atlassian.net/browse/AP-1223)
Add hint text to the field used by solicitors to enter their client's email address by adding it to the translation file and form.

AP-1223 Add hint text to email field

---

app/views/citizens/banks/index.html.erb
config/locales/en/citizens.yml
features/citizens/citizens.feature

[Link to story](https://dsdmoj.atlassian.net/browse/AP-1575)
Add hint to text to bank selection screen so that the citizen is clear what they need to do. This PR adds the relevant text to the translation file and changes the view to display it.

AP-1575 Add hint text to bank selection screen

---

helm_deploy/prometheus/prometheus-alerts-production.yaml
helm_deploy/prometheus/prometheus-alerts-staging.yaml
helm_deploy/prometheus/prometheus-alerts-uat.yaml

[Link to story](https://dsdmoj.atlassian.net/browse/AP-1456)
The previous handling of prometheus alerts was a single file, hard coded to production. If anyone wanted to make changes they had to do a search and replace for environment names and severity levels.
This resulted in a developer, new to the team, missing some of the references and alerts firing on an all environments when issues happened on live 😬 
This is step one of what should ultimately be incorporated into the helm charts and deployed each time we update stacks.
It adds a file for each of the alerting levels with names set correctly, it also adds a link to kibana for the correct environment for 500 error tracking

BugFix: Prometheus alerts

---

package.json
yarn.lock

Fix: update serialize-javascript

---

app/views/shared/forms/_offline_accounts_form.html.erb
app/views/shared/forms/_savings_and_investments_form.html.erb
app/views/shared/forms/other_assets/_form.html.erb
spec/requests/providers/savings_and_investments_spec.rb

AP1540 Accessibility fix for Savings and Investments and other assets page
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1540)
- Add the aria-describedby id to the select_all_that_apply field as it broke WAVE testing of aria tags for other assets page and savings and investments page
- Turn all elements with the html class 'select-all-that-apply-hint' to a span tag with class govuk-hint in order to standardise it with gds design system [here](https://design-system.service.gov.uk/components/checkboxes/)
- Fix the problem where error messages are being bunched underneath the select_all_that_apply heading when checkboxes are selected but they have no nested values. Do this by not duplicating those errors under the heading. However, allow for when no checkboxes are selected error …

AP1540 Accessibility fix for Savings and Investments and other assets page

---

app/views/providers/property_values/_form.html.erb
config/locales/en/providers.yml

The hint on the `/property_value` page was missing/moved
I removed the controller_t method that was being used and switched it to t. It is possible to use the controller_t method it just makes the translation path a bit more long winded (as below).
form:
providers:
property_values:
hint:
property_value: You can use property websites to find the estimated value 

BugFix: Property value page had a missing translation for the hint

---

db/seeds/test_provider_populator.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-1319)
The seeding of users on ap-1319 is broken as it falls over when it tries to update an existing user's permissions.
This change checks to see if the user has a permission first and only updates if the permission doesn't already exist

Fix seeding providers users

---

app/views/providers/statement_of_cases/show.html.erb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-1542)
Accessibility fixes:
Page Title was already fixed for this page
Page orientation issue - keyboard hides text field in landscape mode - this seems to be a mobile device issue, regardless of webpage or app, in landscape the full size keyboard obscures half of the screen.
Navigation using Tab/Keyboard - removed the focus from a hidden error element to remove the second tab required to move from `Back` link to the `Upload File `button. Users can now go directly to this button from the `Skip to Main Content` option

ap-1542 accessibility on statement of case page

---

.circleci/config.yml

Revert the hold step for master UAT

DAC-FIX: revert the master UAT hold

---

app/lib/govuk_elements_form_builder/form_builder.rb
app/views/citizens/accounts/gather.html.erb
app/views/citizens/banks/_error.html.erb
app/views/providers/address_selections/show.html.erb
app/views/providers/confirm_offices/show.html.erb
app/views/providers/has_other_dependants/show.html.erb
app/views/providers/legal_aid_applications/_error.html.erb
app/views/providers/remove_dependant/show.html.erb
app/views/shared/forms/_date_input_fields.html.erb
app/views/shared/forms/_error_summary.html.erb
app/views/shared/forms/_next_action_buttons.html.erb
app/views/shared/forms/_success_message.html.erb
config/locales/en/helpers.yml
spec/lib/govuk_elements_form_builder/form_builder_spec.rb
spec/requests/providers/client_received_legal_helps_spec.rb

AP1527 Accessility Error Summary fix
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1527)
- Update the error summary and error messages to match Govuk design system guidelines. This fixes the accessibility issue where screen readers were not reading out the error summary. 
This includes 'tab-index=-1' which refocusses onto the error summary when a failed form is submitted. Also, 'role="alert"' to read the messsage out from a screen reader. More info here [govuk design system](https://design-system.service.gov.uk/components/error-summary/)
Add a hidden html span tag with the message 'Error:' which matches [govuk design system](https://design-system.service.gov.uk/components/error-message/) guidelines around error messages. It is a hidden field to make screen readers aware of an …

AP1527 Accessibility Error Summary fix

---

Dockerfile

The database backup cronjob was failing due to `kubectl` not being installed on the docker image. The install was failing because of an incorrectly formatted curl command.
Moved the `--retry` and `--retry-delay `flags to after the filename.b

Bugfix: move flags in curl command

---

app/controllers/auth_controller.rb
config/initializers/omniauth.rb
spec/requests/applicants/omniauth_callbacks_spec.rb
spec/requests/auth_spec.rb

AP1512 WIP post truelayer access denied issue debugging

AP1512 post truelayer, access denied issue debugging

---

app/models/dashboard/widget_data_providers/pending_ccms_submissions.rb

Remove date filter from the pending ccms submissions geckoboard dataset
This is so that older pending ccms submissions are visible

Remove date filter from pending ccms failures dashboard

---

app/controllers/feedback_controller.rb
app/views/feedback/new.html.erb
config/locales/en/feedback.yml
features/citizens/citizens.feature
features/providers/civil_application_journey.feature

AP1583 Update feedback difficulty text for provider and citizen
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1583)
- Update the feedback page to show two different texts for the difficulty question - one for the citizen and one for the provider.
- Update the feature tests to test this.

AP1583 Update feedback difficulty text for provider and citizen

---

.circleci/config.yml

Add in the hold on master UAT for the pentesting
This PR essentially re-implements/reverts the DAC changes made here
https://github.com/ministryofjustice/laa-apply-for-legal-aid/pull/1680/files

add a hold for releases to UAT master

---

app/controllers/citizens/consents_controller.rb
app/forms/applicants/open_banking_consent_form.rb
app/views/admin/submitted_applications_reports/_submitted_applications.html.erb
app/views/citizens/consents/show.html.erb
app/views/layouts/_footer.html.erb
app/views/privacy_policy/index.html.erb
app/views/providers/check_benefits/_check_benefits_result.html.erb
app/views/providers/check_benefits/_use_ccms.html.erb
app/views/providers/end_of_applications/show.html.erb
app/views/providers/legal_aid_applications/_legal_aid_applications.html.erb
app/views/providers/open_banking_consents/show.html.erb
app/views/providers/start/index.html.erb
app/views/providers/submitted_applications/show.html.erb
app/views/providers/use_ccms/show.html.erb
app/views/shared/_application_ref.html.erb
app/views/shared/forms/_open_banking_consents.html.erb
config/locales/en/activemodel.yml
config/locales/en/admin.yml
config/locales/en/citizens.yml
config/locales/en/layouts.yml
config/locales/en/privacy_policy.yml
config/locales/en/providers.yml
config/locales/en/shared.yml
spec/requests/citizens/consent_spec.rb
spec/requests/providers/check_benefits_spec.rb
spec/requests/providers/use_ccms_spec.rb

AP1563 Accessibility: Abbreviation tags for screen readers
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1563)
Started with one abbreviation and added a <abbr...> element to it.
Add an abbreviation helper tag for CCMS. This improves accessibility for JAWS users
for reading out abbreviations in capitals.
Initially starting with the first page (index page) and the image shows the hint text for CCMS being it's full name

AP1563 Accessibility: Abbreviation tags for screen readers

---

app/controllers/citizens/accounts_controller.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-1643)
After receiving an error authenticating with TrueLayer, if a user tries again and successfully authenticates, the same error is still displayed. This change fixes this problem by setting `session[:worker_id] = nil` in `accounts_controller` after the error has been handled. This removes the worker from the session and when the second attempt is made a new worker
is created. This prevents the error from being replayed.

AP-1643 Clear TrueLayer errors

---

app/controllers/citizens/accounts_controller.rb
app/controllers/citizens/consents_controller.rb
app/services/true_layer/api_client.rb
app/views/citizens/accounts/gather.html.erb
config/locales/en/citizens.yml
spec/requests/citizens/accounts_spec.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-1641)
If errors are received when authenticating with a bank through TrueLayer an ugly error string is displayed on the page. This change improves that by extracting the description of the error and displaying it, or a default error if no description can be found.
It does several things:
- Add methods to the `accounts_controller` to parse the error and extract the relevant description or provide a default error.
- Amends the error generated by the `api_client` to make it easier to parse.
- Removes an error status that was being set by `consents_controller` if authentication failed. This was having the effect of making it look as if the error was caused by the user not giving consent, when this was not the case.
- Wraps the error in a …

AP-1641 Improve display of TrueLayer errors

---

app/models/cfe/remarks.rb
app/views/providers/means_reports/_caseworker_review.html.erb
config/locales/en/providers.yml
spec/models/cfe/remarks_spec.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-1606)
Related to CFE PR https://github.com/ministryofjustice/check-financial-eligibility/pull/300
If a CFE result is received that has a `residual_balance` remark (ie the applicant's capital is greater than the lower threshold and their current account balance is greater than 0), it needs to be flagged for caseworker review on the means report.
This is mostly done automatically by existing functionality. The `residual_balance` flag is slightly different to existing remarks as it does not need a category displayed. This PR amends the remarks model and caseworker review partial to check the type of remark, and only displays the category if appropriate. It also adds a translation to display the correct wording.
Before you ask people to …

AP-1606 Display residual balance flag on means report

---

app/views/citizens/legal_aid_applications/index.html.erb

close a h2 tag

---

app/assets/stylesheets/layout.scss

The <abbr> tag for screen readers adds some styling below acronyms. This removes that styling (dots below abbreviations).
I have put the css in` layout.scss` as it applies across the service, however if there s a more appropriate place for it let me know, happy to move it.

Amend the <abbr> styling

---

.rubocop.yml
app/helpers/check_answers_helper.rb

Turned on all new cops in rubocop 0.90 and added fixes for all suggestions.
The `SoleNestedConditional` cop threw up 3 issues in:
`app/controllers/providers/transactions_controller.rb`
and
`spec/support/soap_matchers.rb`
The changes I made in these files to pass the cop, do not appear to me to be the most readable, essentially due to the use of `!` to indicate a negative/false requirement.
I am happy to revert these changes and use a `rubocop ignore/disable` if that is preferable, or if anyone has an alternatvie suggestion I am all ears. 👂

Rubocop Update: update cops and fixes

---

app/views/providers/check_benefits/_check_benefits_result.html.erb
config/locales/en/providers.yml

[Link to story](https://dsdmoj.atlassian.net/browse/AP-1647)
AP-1409 made changes to the changes to the `/check_benefits` page when the result from DWP was negative.
Some of these changes appear to have been lost, probably as a result of a rebase or merge conflict resolution.
This PR reinstates those changes.

AP-1647 Re-fix DWP text

---

app/lib/omniauth/strategies/laa_oauth2.rb
app/lib/omniauth/strategies/true_layer.rb
spec/lib/omniauth/strategies/laa_o_auth2_spec.rb
spec/spec_helper.rb

Subclass oauth2
This is to better test the issue that is caused by omniauth raising a CSRF detected error
Send a sentry message with raven containing the client_id , request params and session 'state' value
This is an almost exact copy of the oauth2 https://github.com/omniauth/omniauth-oauth2/blob/master/lib/omniauth/strategies/oauth2.rb
and it was subclassed to allow for better logging.
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1512)
**To note:**
I've added a rubocop disable # rubocop:disable Lint/MissingSuper
for the  callback error class which subclasses standard error

AP1512 Subclass oauth2

---

yarn.lock

Github has flagged a security issue with the `bl` package. [CVE-2020-8244](https://github.com/advisories/GHSA-pp7h-53gx-mx7r).  'bl' is an indirect dependency of the `@hint/configuration-web-recommended` library. This has been resolved by updating `bl` to 2.2.1 as recommended.

Fix yarn security issue

---

yarn.lock

Fix CVE-2020-8244 (https://github.com/advisories/GHSA-pp7h-53gx-mx7r) in
the 'bl' library by bumping the version number to 2.2.1 as advised.

Fix security vulnerability in bl library

---

app/controllers/providers/check_merits_answers_controller.rb
app/views/providers/date_client_told_incidents/show.html.erb
app/views/providers/respondents/show.html.erb
app/views/providers/start_merits_assessments/show.html.erb
app/views/providers/statement_of_cases/show.html.erb
app/views/providers/success_likely/index.html.erb
app/views/providers/success_prospects/show.html.erb
features/providers/civil_application_journey.feature
spec/requests/providers/check_merits_answers_spec.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-1558)
There is inconsistent behaviour when using the back links in the merits screens. It often takes the user back much further than required, into the means screens, and results in a lot of clicking to get back to the correct place.
This commit hardcodes the correct back link path into each view in the merits flow.

AP-1558 Fix back button behaviour in merits screens

---

app/javascript/src/start_button.js
app/views/citizens/legal_aid_applications/index.html.erb
app/views/providers/legal_aid_applications/index.html.erb
app/views/providers/start/index.html.erb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-1615)
Add `role=button` to start links/buttons
Reword so they say Start now
Add in a click event handler so that start buttons all respond to the spacebar as well as enter key

Ap 1615 a11y start button

---

README.md
app/views/citizens/check_answers/index.html.erb
app/views/shared/check_answers/_merits.html.erb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-1613)
Rejig the <dl> tags to either separate lists out or merge them into one another in line with DAC report

Ap 1613 accessibility definition lists

---

app/views/providers/legal_aid_applications/_legal_aid_applications.html.erb
app/views/providers/transactions/show.html.erb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-1612)
In two places there are tables that contain deliberately empty cells - the provider's applications list and the transaction selection screens.
These are read out by screen readers which is confusing for users. The null cells cannot be easily removed as they are used to rearrange the layout of the pages on small screens.
Instead to prevent the cells being announced by screen readers, mark them as `aria-hidden="true"`.

AP-1612 Make screen readers ignore null table cells

---

app/presenters/bank_transaction_presenter.rb
app/services/true_layer/importers/import_transactions_service.rb
db/migrate/20200903165732_add_running_balance_to_bank_transactions.rb
db/schema.rb
spec/factories/bank_transactions.rb
spec/presenters/bank_transaction_presenter_spec.rb
spec/services/true_layer/importers/import_transactions_service_spec.rb
spec/support/true_layer_mock_data.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-1638)
Caseworkers need to be able to a running balance for a bank account on the bank transactions csv report. We already receive this information from TrueLayer, we just don't do anything with it.
This PR contains two commits:
[2e21f1c](https://github.com/ministryofjustice/laa-apply-for-legal-aid/commit/2e21f1c48a623346120df11ea39a06eaf7ef7eb7) adds a `running_balance` field to the `bank_transaction` model and adds functionality to populate that with the value received from TrueLayer.
[bc0cc87](https://github.com/ministryofjustice/laa-apply-for-legal-aid/commit/bc0cc876c329db9b7e084a5379ec6b9d365ed35b) amends the `bank_transaction_presenter` in order to include that running balance on the report.
Before you ask people to review this …

AP-1638 Display running balance on caseworker bank transactions csv

---

app/models/bank_account.rb
app/presenters/bank_transaction_presenter.rb
app/views/citizens/accounts/index.html.erb
app/views/providers/applicant_bank_accounts/show.html.erb
spec/presenters/bank_transaction_presenter_spec.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-1657)
Caseworkers need to know more information about transactions on the bank transaction csv report. This change adds the account name and account type to the report.
The account name should be displayed on the report in a particular format used elsewhere in the application (ie "bank_name account_name". As part of this change a method has been added to the `bank_account` model to provide this name, and this also has been added to the two views display that data. 

AP-1657 account details on transaction csv

---

helm_deploy/prometheus/prometheus-alerts-production.yaml
helm_deploy/prometheus/prometheus-alerts-staging.yaml
helm_deploy/prometheus/prometheus-alerts-uat.yaml

Cloud Platforms need us to update out prometheus alerting labels.

update prometheus alerts label

---

app/services/true_layer/importers/import_provider_service.rb
spec/services/true_layer/importers/import_provider_service_spec.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-1644)
If a user authenticates twice with the same bank through TrueLayer, a duplicate `bank_provider` record is created resulting in duplicate `bank_account`, `bank_account_holder`, and `bank_transaction` records.
This duplication occurs because `ImportProviderService` checks for existing `bank_provider` based on `credentials_id`, however `credentials_id` is always unique and so no duplicate will ever be found.
This PR changes this functionality so that it instead checks for duplicates based on `true_layer_provider_id`, which will be consistent for all bank details retrieved from a given bank.

AP-1644 Prevent duplicate bank providers

---

bin/cleanup_manual_snapshots
bin/create_manual_snapshot

No ticket for this. A sentry error was being created because of failing backups.
Revert the changes made to the backup DB script, testing was done in staging. The script/cronjobs all work now in staging so these changes revery just the credentials, which will allow the scripts to work in prod only.

revert to prod credentials for backup scripts:

---

app/controllers/citizens/legal_aid_applications_controller.rb
app/controllers/providers/confirm_offices_controller.rb
spec/requests/applicants/omniauth_callbacks_spec.rb
spec/requests/citizens/accounts_spec.rb
spec/services/cfe/create_capitals_service_spec.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-1667)
The purpose of this ticket is to stop sessions (which are stored in the cookie) from getting too large.  We suspect that this is the reason we are occasionally getting Access Denied error on the callback from TrueLayer, because the session which holds a state variable has been truncated.
The session contains a history of pages visited, which is used by the back buttons to determine where to go back to.
This ticket does two things:
1) on login by the applicant (i.e. clicking on the link that has been sent them in the mail), it resets the session
2) On logging in by the provider, resetting the session isn't an option because devise has already put something it needs there, so we simply reset the page history to an empty array …

AP-1667 Reset sessions on login

---

app/services/state_benefit_analyser_service.rb
spec/factories/bank_transactions.rb
spec/services/state_benefit_analyser_service_spec.rb

Add selected_by 'System' to bank transactions metadata when the system automatically
selects state benefits from the transactions in the bank.
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1639)

AP1639 Add selected_by 'System' metadata for bank transactions

---

helm_deploy/apply-for-legal-aid/templates/_helpers.tpl

After fixing the DB backup issue in prod I forgot to reset the schedules for UAT and Staging, which meant these cronjobs were making lots of failing pods on both environments.

revert cronjob schedule in UAT and staging

---

app/views/providers/providers/show.html.erb
spec/requests/providers/providers_spec.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-938)
The profile page shows the role codes for the logged in user, which looks confusing -  the codes are meaningless to the user. This commit removes the roles from the view so they are no longer displayed to the user.

AP-938 Remove provider roles from profile screen

---

app/javascript/src/continue_button.js
app/javascript/src/start_button.js
app/views/providers/application_confirmations/show.html.erb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-1616)
On `application_confirmations/show.html.erb`, the 'Back to your application' link has been styled as a button but does not have a role of `button` assigned or a keyboard event handler to allow keyboard-only users to activate the element with the space bar.
This change adds a role of `button` to the link and create an event handler to allow a user to activate the `button` with the space bar.
It also fixes a couple of issues with the similar event handler for `start` buttons, 
- an error is firing an error on all pages where there is no `start` button. Fix this by adding a check for `null`s
- the default space bar behaviour of scrolling is firing when a user uses the keyboard to activate the button, which looks a bit strange. Add …

AP-1616 Make continue link styled as button accessible

---

app/models/legal_aid_application.rb
spec/services/cfe/create_capitals_service_spec.rb

Bugfix
If only one type of account (current or savings) is created by the test, then the other account type had a value of 0.  Zero is handled as a number in the test whereas any positive or negative value is a string. The fix moves the creation of the string to the method on legal_aid_application instead of in the test.

move the to_s to fix tests

---

app/assets/stylesheets/table-sort.scss

[Link to story](https://dsdmoj.atlassian.net/browse/AP-1620)
Table headers on `/applications`, `/incoming_transactions` and `/outgoing_transactions` do not have GOVUK compliant contrast when they have focus.
This change adds formatting using CSS so that the cell is correctly highlighted with both a black border and a yellow border.

AP-1620 Make table header contrast accessible

---

README.md
db/seeds/test_provider_populator.rb

This PR does three things: 
- Adds a section to the README explaining the difference of behaviour between signing out when using the LAA Portal for authentication, and signing out when using mock saml.
- Adds a section to the README explaining how to configure localhost to use the LAA Portal staging environment for authentication
- Adds a user BENREID to the seed data which can be used to sign on to the LAA Staging Portal
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1680)

AP-1680 Update readme and add user for portal login

---

app/models/firm.rb
spec/models/firm_spec.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-1665)
Adds the passported responsibility to all new firms automatically so that providers can use the system without any further admin interaction.

AP-1665 Set default responsibility for firms

---

app/views/admin/firms/index.html.erb
config/locales/en/admin.yml
spec/factories/firms.rb
spec/models/firm_spec.rb
spec/requests/admin/firms_spec.rb
spec/requests/providers/check_benefits_spec.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-1668)
Amend the index view for /admin/firms to display which permissions a firm holds.
Also adjusts the table layout to account for the extra column and tidies up the existing code a little.

AP-1668 List firm permissions

---

app/services/ccms/submitters/obtain_applicant_reference_service.rb
spec/data/ccms/applicant_search_response_results_no_details.xml
spec/services/ccms/submitters/obtain_applicant_reference_service_spec.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-1648)
A recent production incident highlighted that it's possible for an applicant to exist in the CCMS database but be disabled, in which case a non-zero `record_count` is returned to Apply but no `ClientReferenceNumber` is included. This causes failures later in the submission process
This PR changes that functionality so that in this situation Apply makes a call to CCMS to create a new applicant.

AP-1648 Add CCMS applicant if no applicant ref returned

---

config/locales/en/providers.yml

AP1618 Content change on use_ccms page
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1618)
Update the content of use_ccms page when provider does not receive the citizens open banking consent

AP1618 Update content of use_ccms page

---

app/views/providers/income_summary/_add_other_income.html.erb
app/views/providers/outgoings_summary/_add_other_outgoings.erb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-1624)
The `income_summary` and `outgoings_summary` pages contain a link and an image inside an `h2` tag. This is confusing for screenreader users.
This changes the `h2` tag to a `div`, as recommended by DAC.

AP-1624 Fix inaccurate heading structure

---

app/lib/govuk_elements_form_builder/form_builder.rb
app/views/providers/confirm_offices/show.html.erb
config/locales/en/providers.yml
spec/lib/govuk_elements_form_builder/form_builder_spec.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-1610)
Move the text inside an HTML block in providers.yml
This allows the view to call a single block and assign
it to the legend inside the govuk_collection_radio_buttons
helper

AP-1610: Update confirm_office view

---

app/views/shared/forms/proceedings_types/_proceeding_type_form.html.erb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-1623)
As per the comment on the Jira ticket, this adds an aria-label with the select and continue text and also the name of the proceeding. So a screen reader will read out e.g. "Select and continue Forced marriage protection order"

AP-1623 add the proceeding meaning to aria label

---

app/helpers/accessible_link_helper.rb
app/views/providers/about_the_financial_assessments/show.html.erb
app/views/providers/address_selections/show.html.erb
app/views/providers/bank_transactions/_list_selected.html.erb
app/views/providers/has_other_dependants/show.html.erb
app/views/providers/income_summary/_income_type_item.html.erb
app/views/providers/outgoings_summary/_outgoing_type_item.html.erb
app/views/shared/check_answers/_item.html.erb
app/views/shared/check_answers/_one_change_link_long_answers_section.erb
app/views/shared/check_answers/_one_link_section.html.erb
app/views/shared/check_answers/_only_link_section.html.erb
app/views/shared/forms/proceedings_types/_proceeding_type.html.erb
config/locales/en/providers.yml
spec/helpers/accessible_link_helper.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-1625)
There are a number of links in the application where the intent is clear for a sighted user but not obvious for a screenreader user, especially when multiple links exist on a page. This change adds a helper method to create links with text that is partially hidden using a `govuk-visually-hidden` span.
This allows us to keep to our current design but also add extra context for screenreader users - for example a link can be displayed as 'Change' but read out as 'Change postcode'.

AP-1625 More descriptive links for screenreaders

---

app/models/legal_aid_application.rb

We're seeing lots of Sentry alerts due to exceeding the number of permitted calls to Geckoboard. This seems to be linked (at least partially) to the `ProviderDataJob`, which is triggered by a save to the `LegalAidApplication model`. The call is guarded by an if statement that always resolves to true:
`if proc { |laa| laa.state.eql?(:assessment_submitted) }`
It returns the proc, which is truthy, so a Geckoboard request is sent every time an application is saved. This corrects it so that the request is only made when the application is submitted:
`if proc { |laa| laa.state }.eql?(:assessment_submitted)`

Reduce calls to Geckoboard

---

app/views/providers/capital_income_assessment_results/_result_details.html.erb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-1626)
This was being called as a partial from capital_assessment_results
and capital_income_assessment_results.  In both cases it was being
called below the blue panel that already contained an H1.
Therefore downgrading this to an H2 should have no effect on the
display for users and will improve experince for screenreader
users

AP-1626: Update result details header

---

.circleci/config.yml

Due to issues with yarn and upgrades to ruby/yarn packages/circle docker images we are removing webhint from the circle process
This is intended to be a short term removal until we have time/skills on the team to address the webhint/yarn config and either
a) fix the current implmentation, or;
b) replace it with an alternative automated accessibility scanner
[Spike to investigate re-implementation](https://dsdmoj.atlassian.net/browse/AP-1710)

TECH-DEBT: remove webhint from Circle CI

---

features/cassettes/Civil_application_journeys/Completes_the_application_using_manual_address.yml
features/cassettes/Civil_application_journeys/I_want_to_change_address_manually_from_the_check_your_answers_page.yml
features/providers/civil_application_journey.feature
spec/cassettes/Providers_AddressSelectionsController/GET_/providers/applications/_legal_aid_application_id/address_selections/edit/when_the_provider_is_authenticated/a_postcode_has_been_entered_before/but_the_lookup_does_not_return_any_valid_results/renders_the_manual_address_selection_page.yml
spec/requests/providers/address_selections_spec.rb

The OS postcode checker previously didn't return any addresses for `SW1H 9AJ`, so that postcode is used in tests for non-existent addresses. However 102 Petty France is now (correctly) returned for that postcode. This will cause tests to fail next time VCR cassettes are recorded.
This changes `SW1H 9AJ` to `XX1X 1XX` (which is vaild postcode that is unlikely to have any addresses associated with it the near future) in one spec and two feature tests, and re-records the cassettes.

Fix flaky postcode test

---

package.json
yarn.lock

Now that webhint is not blocking these, update yarn by adding resolutions for node-forge and yargs-parser, address the CVE-2020-7720 and GHSA-p9pc-299p-vxgp  warnings

Tech-Debt: remove yarn warnings

---

app/models/concerns/base_state_machine.rb

We're seeing production errors due to a valid state transition.
It's possible for a provider to process a non-passported case that uses delegated functions, get to the `non_passported_client_instructions` screen, then hit back twice.
This currently throws the error `Event 'applicant_details_checked' cannot transition from 'delegated_functions_used'`.
This change adds the `delegated_functions_used` state to the `applicant_details_checked` event so that this is allowed.

Add extra state transition to fix production errors

---

app/controllers/concerns/backable.rb
app/controllers/feedback_controller.rb
app/controllers/saml_sessions_controller.rb
app/controllers/test/sessions_controller.rb
app/mailers/concerns/notify_template_methods.rb
app/mailers/feedback_mailer.rb
app/views/feedback/new.html.erb
config/application.rb
config/govuk_notify_templates.yml
config/locales/en/feedback.yml
config/locales/en/helpers.yml
config/routes.rb
db/migrate/20200921143900_add_email_to_feedback.rb
db/seeds/test_provider_populator.rb
features/providers/civil_application_journey.feature
spec/rails_helper.rb
spec/requests/feedbacks_spec.rb
spec/requests/saml_sessions_spec.rb
spec/services/govuk_emails/email_monitor_spec.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-1545)
- Added `originating_page` and `email` to `feedbacks` table
- On signing out, stored the provider id in the session as `signed_out_provider_id` to make it available to the Feedback controller
- in `FeedbackController#new` extracted the `signed_out_provider_id` from the session and submitted it as a hidden field
- in `FeedbackController#create` extracted got the provider id either from the hidden form param (if signed out) or the session and stored in the Feedack record
- stored the originating page  the Feedback record
- Duplicated the gov uk templates with two new variables: originating page and provider email
- updated the FeedbackMailer to use the new templates with the additional variables
- Wrote `Test::SessionsController` …

AP-1545 Record providers email and page on feedback

---

app/views/shared/forms/_date_part_input_fields.html.erb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-1629)
The input type for the date field is set as 'text'. This means mobile users may have to switch to a numeric keypad to enter values.
Add `inputmode="numeric" pattern="[0-9]*"` to the date input form so that this is fixed for all date fields. When a mobile user enters data their keyboard will default to a numeric keypad.

AP-1629 Use correct input type on date fields

---

app/helpers/capital_helper.rb
app/helpers/liquid_capital_items_helper.rb
app/services/cfe/create_capitals_service.rb
app/views/shared/_savings_and_investments.html.erb
app/views/shared/check_answers/_assets.html.erb
app/views/shared/check_answers/_one_link_section.html.erb
spec/requests/providers/means_reports_spec.rb
spec/services/cfe/create_capitals_service_spec.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-1701)
Added a new method to `CapitalHelper` to display `passported` or `non-pasported` differently due to how we handle bank balances.
Renamed the `offline_current/savings_accounts` and also the TrueLayer obtained accounts.
I need to confirm with Dave about the preferred naming of these on the `means_report` and `capital_assessment_result` pages

Ap 1701 savings account bugfix

---

app/controllers/feedback_controller.rb
app/controllers/saml_sessions_controller.rb
app/mailers/feedback_mailer.rb
app/views/feedback/show.html.erb
spec/factories/feedbacks.rb
spec/requests/feedbacks_spec.rb

Prior to this PR, when a citizen clicked the feedback link, there was no way to get back to the application after the feedback had been submitted.  We now use the same mechanism as for providers.  There is no feedback link for providers that are filling in feedback after having signed out.
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1695)

AP-1695 Provide back to application link for citizens feedback form

---

app/views/admin/legal_aid_applications/_legal_aid_applications.html.erb
config/locales/en/admin.yml

[Link to story](https://dsdmoj.atlassian.net/browse/AP-1703)
Add a new column to the applications table to display the provider.username for each application
Add a mail_to link to the username that points to the provider.email address

AP-1703 add username to applications table

---

app/lib/omniauth/strategies/moj_oauth2.rb
app/lib/omniauth/strategies/true_layer.rb
app/models/debug.rb
db/migrate/20201005152150_create_debugs_table.rb
db/schema.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-1735)
- Copied the class `Omniauth::Strategies::Oauth2` from the `omniauth-oauth2` gem into the Apply project and renamed it `Omniauth::Strategies:MojOauth2`
- Changed `Omniauth::Strategies::TrueLayer` in our app to derive from `Omniauth::Strategies:MojOauth2` instead of `Omniauth::Strategies::Oauth2`
- Created a `debugs` table to hold debug info
- modified `Omniauth::Strategies:MojOauth2` to write debug info to the debugs table when making a true layer request, when processing a true layer callback, and when there is a CSRF error

AP-1735 Record TrueLayer requests and callbacks

---

app/lib/govuk_elements_form_builder/form_builder.rb
app/views/citizens/additional_accounts/index.html.erb
app/views/citizens/additional_accounts/new.html.erb
app/views/citizens/banks/index.html.erb
app/views/citizens/consents/show.html.erb
app/views/citizens/student_finances/show.html.erb
app/views/providers/applicant_bank_accounts/show.html.erb
app/views/providers/confirm_offices/show.html.erb
app/views/providers/dependants/_form.html.erb
app/views/providers/has_dependants/show.html.erb
app/views/providers/has_other_dependants/show.html.erb
app/views/providers/no_income_summaries/show.html.erb
app/views/providers/no_outgoings_summaries/show.html.erb
app/views/providers/remove_dependant/show.html.erb
app/views/providers/restrictions/_form.html.erb
app/views/providers/select_offices/show.html.erb
app/views/providers/used_delegated_functions/show.html.erb
app/views/shared/forms/_open_banking_consents.html.erb
app/views/shared/forms/_success_prospect_form.html.erb
app/views/shared/forms/vehicles/_remaining_payment.html.erb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-1698)
Work through the application and ensure that all forms with radio buttons are accessible in-line with DAC recommendations
I have extended the formbuilder to:
* allow hidden legend This can be used on pages where a simple h1 radio button is not enough
* Allow passing a block to the method which allows wrapping help text inside a form  group without writing them manually each time
* Add yes/no button array to reduce repetition in views
Ensured the radio buttons in use have a correctly structured fieldset and legend. This was done by either
a) adding a fieldset tag around a complex radio button collection; or
b) switching to use the govuk_collection_radio_buttons helper method where possible
These fall outside the scope of this …

Ap-1698: radio button accessibility

---

app/services/ccms/manual_review_determiner.rb
config/locales/en/admin.yml
spec/services/ccms/manual_review_determiner_spec.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-1739)
- changed conditons for flagging in `CCMS::ManualReviewDeterminer`
- updated label and hint text of setting

AP-1739 Route all non-passported applications for caseworker review

---

.circleci/config.yml
app/mailers/feedback_mailer.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-1741)
DAC are using master UAT for accessibility testing.  We don't want to deploy to that environment automatically while that is going on.

AP-1741 Manually approve deployments to master UAT

---

app/helpers/table_sort_helper.rb
app/javascript/src/table-sort.js
app/views/providers/legal_aid_applications/_legal_aid_applications.html.erb
config/locales/en/providers.yml

[Link to story](https://dsdmoj.atlassian.net/browse/AP-1614)
Following the DAC report, changes were requested to the screen-reader functionality of the applications table
This PR attempts to follow the recommendations by simplifying the prompts and matches the handling as used on their example

AP-1614: sorting table accessibility update

---

.circleci/config.yml

[Link to story](https://dsdmoj.atlassian.net/browse/AP-1741)

AP-1741a fix bug in workflow

---

app/views/citizens/means_test_results/show.html.erb
config/locales/en/citizens.yml

[Link to story](https://dsdmoj.atlassian.net/browse/AP-1703)
Added a div with the new feedback link to /means_test_results 
Amended the success_message check so we don't show the "signed out" message at the top of the page when citizen visits the page
A subsequent rebase has replaced the changes to the feedback controller which checks success message.

AP-1706 feedback link for citizen

---

config/locales/en/shared.yml

[Link to story](https://dsdmoj.atlassian.net/browse/AP-1508)
Removed reference to Universal Credit because you cannot use Apply if you are in receipt of this benefit

AP-1508-update content

---

app/views/citizens/check_answers/index.html.erb
config/locales/en/citizens.yml
config/locales/en/providers.yml
features/citizens/citizens.feature
features/step_definitions/citizens_steps.rb
spec/requests/citizens/check_answers_spec.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-1617)
Update translation files for provider and citizen to improve terminology used around income and outgoings.

AP-1617 Update language for income and outgoings

---

app/helpers/flow_helper.rb
app/javascript/src/modules/proceedings.js
app/views/providers/proceedings_types/index.html.erb
app/views/shared/forms/_next_action_buttons.html.erb
app/views/shared/forms/proceedings_types/_proceeding_type_form.html.erb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-1708)
In searching for ways of improving the accessibility of the proceeding type page I reviewed the DAC report and aria handling. 
I have refined the aria tags to provide a (hopefully) simpler screenreader flow.
The proposed accessible drop-down doesn't allow the large volume of data we currently require to display but it might be worth adding another ticket to see if it would improve the address drop-down handling?

AP-1708: proceeding type accessibility update

---

app/views/citizens/legal_aid_applications/index.html.erb
config/locales/en/citizens.yml
config/locales/en/providers.yml

[Link to story](https://dsdmoj.atlassian.net/browse/AP-1732)
Copy changes to reflect the fact that it is TrueLayer collecting bank details on behalf of the LAA

AP-1732 replace references to LAA with TrueLayer

---

app/policies/legal_aid_application_policy.rb
spec/policies/legal_aid_application_policy_spec.rb

When attempting to delete an old claim a user was shown an authoriasation error
Because it was an old claim, it had been marked as `use_ccms` because the benefit
check failed.  This also meant that the application failed the `passported?` check
and theerfore the provider needed non-passported permissions to delete the claim.
This checks the state_machine_proxy and returns the correct permissions. It may
be worth nothing that this is a bit of a stricking plaster fix and that other
legacy claims may be in non-passported states due to the migration and that we
should endeavour to assess the liklihood of this recurring.

BUGFIX: update pundit

---

app/controllers/providers/no_income_summaries_controller.rb
app/views/providers/no_income_summaries/show.html.erb
config/locales/en/providers.yml
features/providers/non_passported_journey.feature

AP-1702 Add dynamic content to NoIncomeSummaries page
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1702)
- Add student finance content to the NoIncomeSummaries page when there are no other incomes but there is student finance.
- Add testing

AP-1702 Add dynamic content to NoIncomeSummaries page

---

.circleci/config.yml

Revert the circle hold-uat changes.  There will be a third DAC review so only commented out for now

REVERT: remove hold-uat step from circle

---

spec/requests/citizens/gather_transactions_spec.rb

`spec/requests/citizens/gather_transactions_spec.rb` was added using the old method of storing page histories in the session. This changes two tests to use the `PageHistoryService`.

Fix page history when gathering bank transactions

---

app/views/shared/check_answers/_merits.html.erb
app/views/shared/check_answers/_restrictions.html.erb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-1751)
Fixes issue raised in Section 4.6 of the security testing report.
* Removes the use of `simple_format` to display user-entered text, which is causing HTML render instead of being escaped.
* Fixes a minor layout issue caused by the removal of `simple_format` from the `restrictions` partial.
* Fixes a pre-existing issue where a section break on the merits check your answers page is displayed incorrectly when 'Have the police been notified?' is answered 'Yes'

AP-1751 Fix HTML injection

---

app/helpers/table_sort_helper.rb
app/javascript/src/details-polyfill.js
app/views/providers/legal_aid_applications/_legal_aid_applications.html.erb
app/views/providers/proceedings_types/index.html.erb
app/views/providers/substantive_applications/show.html.erb
app/views/providers/transactions/show.html.erb
app/views/shared/forms/_shared_ownership_form.html.erb
config/locales/en/providers.yml

[Link to story](https://dsdmoj.atlassian.net/browse/AP-1727)
Following the DAC re-review, the following changes were required.
1. Form Controls - Grouped (A)
"do you want to make a substantive application now?"
"does your client own their home with anyone else?"
These views were missing fieldsets that enclosed the radio buttons
2. Sortable table (A)
The initial issue has been fixed and has been approved by DAC as a workable solution. It now needs to be applied to the transaction tables in the service:
3. Status message (AA)
The issue  with he proceeding type view has been initially resolved but have resulted in a new issue:
The alert is not being read out to JAWS users when browsing in Internet Explorer. The role has changed from Alert to Region which will prevent the live region from …

AP-1762: Accessibility updates

---

features/step_definitions/civil_journey_steps.rb

When the delete function was added there were two anchor tags on the row
and this step was amended to look for the anchor tag containing the
applicants name.  This breaks when faker generates a name with an
apostrophe e.g. O`Malley.
This check has been removed and it now looks for the anchor tag in the
first cell of the row instead

BUGFIX: remove names from cucumber step

---

spec/services/reports/mis/non_passported_application_csv_line_spec.rb

This was causing the tests in `non_passported_applications_report_spec.rb` to fail because it was locking the date before the cut off for the new report.  
Turning it into a block means that Timecop resets the date at the end.
Maybe we should look at implementing safe_mode? https://github.com/travisjeffery/timecop#timecopsafe_mode

BUGFIX: wrap timecop in do block

---

Gemfile
Gemfile.lock
app/helpers/application_helper.rb
app/javascript/src/print_button.js
app/views/layouts/_google_tag_manager.html.erb
app/views/layouts/application.html.erb
app/views/providers/statement_of_cases/show.html.erb
app/views/saml_idp/idp/saml_post.html.erb
config/initializers/secure_headers.rb
spec/requests/providers/submitted_applications_spec.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-1756)
See 4.14 of the security testing report.
Adds the `secure_headers` gem and configures it to generate `content-security-policy` (CSP) headers. The recommendation was to add this header `Content-Security-Policy: script-src 'self'; object-src 'none'; require-trusted-types-for 'script';` however for various this reasons this does not completely suit our application and extra configuration is required:
* `script_src` - additionally allows scripts from https://www.google-analytics.com and https://www.googletagmanager.com in order for Google Analytics to continue to function
* `img_src` - additionally allows images from https://truelayer-client-logos.s3-eu-west-1.amazonaws.com and https://truelayer-provider-assets.s3.amazonaws.com to …

AP-1756 Add gem to implement content-security-policy headers

---

config/initializers/session_store.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-1752)
Add `session_store` to initializers to allow secure_cookies to be set
This uses the Rails.env.production? test, which sets it to `true` for UAT, STAGING and PRODUCTION.
For local development mode it is therefore `false`
The HostEnv variable `app/models/host_env.rb` we use elsewhere is unsuitable as this value is not known at the point the docker image is built which causes it to fail.
An alternative option is to add in a new environment variable to only have secure_cookies in production however I am not sure of the value of that as we run all 3 environments in production mode and use HTTPS in all of them.

AP-1752 add secure ssl config option

---

app/views/shared/check_answers/_client_details.html.erb
app/views/shared/check_answers/_no_link_item.html.erb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-1725)
Removed an errant comma which was breaking the `align_right` variable and returning `true` instead of `false` on `app/views/shared/check_answers/_no_link_item.html.erb`
Changed the align_right status to `false` for client details as there does not appear to be any page where these need to be aligned right.

AP-1725 left align content

---

app/controllers/admin/settings_controller.rb
app/forms/settings/setting_form.rb
app/models/setting.rb
app/views/admin/settings/show.html.erb
config/locales/en/admin.yml
config/locales/en/helpers.yml
db/migrate/20201020100508_add_welsh_flag_to_settings.rb
db/schema.rb
lib/tasks/setup_db_for_testing.rake
spec/models/setting_spec.rb
spec/requests/admin/settings_spec.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-1763)
- Add allow_welsh_translation column to settings table
- Add allow_welsh_translation attribute and section to admin form
- Update tests

AP-1763 Welsh Feature Flag

---

.rubocop.yml
app/forms/legal_aid_applications/used_delegated_functions_form.rb
app/helpers/gov_uk_form_helper.rb
app/helpers/time_helper.rb
app/views/providers/used_delegated_functions/show.html.erb
app/views/shared/forms/_date_input_fields.html.erb
config/locales/en/activemodel.yml
config/locales/en/shared.yml
spec/forms/legal_aid_applications/used_delegated_functions_form_spec.rb
spec/helpers/time_helper_spec.rb
spec/requests/providers/used_delegated_functions_spec.rb

AP-1717 delegated function date is within last 12 months
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1717)
- Add validation to check that the delegated function date is within the last 12 months
- Add error message
- Update hint to be a dynamic date and be within the 12 months period
- Add TimeHelper to help with the dynamic date
- Update tests

AP-1717 delegated function date is within last 12 months

---

app/mailers/notify_mailer.rb
app/services/citizen_email_service.rb
config/govuk_notify_templates.yml
spec/mailers/notify_mailer_spec.rb
spec/services/citizen_email_service_spec.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-1568)
- Update NotifyMailer to include provider firm name
- Update tests

AP-1568 Update NotifyMailer to include provider firm name

---

config/locales/cy/activemodel.yml
config/locales/cy/activerecord.yml
config/locales/cy/citizens.yml
config/locales/cy/contacts.yml
config/locales/cy/currency.yml
config/locales/cy/errors.yml
config/locales/cy/feedback.yml
config/locales/cy/generic.yml
config/locales/cy/helpers.yml
config/locales/cy/layouts.yml
config/locales/cy/model_enum_translations.yml
config/locales/cy/privacy_policy.yml
config/locales/cy/shared.yml
config/locales/cy/transaction_types.yml
config/locales/cy/true_layer_errors.yml
lib/tasks/cy.rake
lib/tasks/helpers/cy_helper.rb
spec/i18n_spec.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-1672)
Copies all translations for the applicant journey the `/cy` locale and converts them to fake-Welsh (by reversing each string) for use in developing the Welsh language version of the applicant journey.
* This only applies to text that appears on the current applicant journey - any translations for providers or for parts of the applicant journey that are no longer visible to applicants (eg dependants, vehicles, capital and equity) have not been included.
* Behaviour of `spec/i18n_spec.rb` has been changed - it now tests for all translations in the English locale but only translations on pages on the applicant journey for the Welsh locale.
* Rake task to generate fake-Welsh versions of all translation files is included for future …

AP-1672 Add fake Welsh translations

---

app/services/reports/mis/application_detail_csv_line.rb
app/services/reports/mis/non_passported_application_csv_line.rb
app/services/reports/mis/sanitisable.rb
spec/services/reports/mis/application_detail_csv_line_spec.rb
spec/services/reports/mis/non_passported_application_csv_line_spec.rb
spec/services/reports/mis/sanitisable_spec.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-1748)
CSV files produced by Apply are vulnerable to csv injection exploits. This adds a mixin to provide functionality to sanitise the data by prefixing an apostrophe to any fields that begin with an exploitable character (+, -, =, @ or %).
This has been added to the `ApplicationDetailCsvLine` and `NonPassportedApplicationCsvLine` classes to sanitise both reports (the non-passported application report doesn't contain any user-entered data so is not particularly vulnerable but has been included for consistency).

AP-1748 Sanitise CSV files

---

app/controllers/feedback_controller.rb
app/controllers/saml_sessions_controller.rb
app/mailers/feedback_mailer.rb
app/models/legal_aid_application.rb
app/views/feedback/new.html.erb
config/govuk_notify_templates.yml
spec/mailers/feedback_mailer_spec.rb
spec/models/legal_aid_application_spec.rb
spec/requests/feedbacks_spec.rb
spec/requests/saml_sessions_spec.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-1727)
- Update feedback process to include legal aid application infromation: application_ref, state, user_type (citizen / provider).
- Give the application_id to the feedback mailer to gather application information for the email.
-  Use the PageHistoryService / page_history to get the application id
- Add provider email from :current_provider 
- Application information is left empty on the feedback mailer
- Use the existing session['current_application_id'] to get the provider email
- Pass the session['current_application_id'] as a param to the feedback mailer
--- 
- Update tests
- Test when a provider clicks feedback whilst not on an application e.g. on the index page / application dashboard

AP-1727 Add application detail to Feedback email

---

app/controllers/providers/transactions_controller.rb
app/views/providers/transactions/show.html.erb
features/step_definitions/civil_journey_steps.rb
spec/requests/providers/transactions_spec.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-1773)
Update the transaction handling.  
Previously transactions that had been identified as benefits would be displayed, ticked, on the add new transactions page. If a user submitted the page (regardless of adding new ticked rows) all rows would identified as `manually_chosen`.
This affected the data sent to CFE.
This removes previously ticked rows.  The main screen says 
So I have taken this to mean that the `remove` link is the sole way of de-selecting a line-item.  Now a provider can only tick new rows on the incoming_transactions page

AP-1773: update benefit selection

---

app/views/citizens/student_finances/show.html.erb

[AP-1776](https://dsdmoj.atlassian.net/browse/AP-1776)
The Student Finance view on the applicant journey contains a 'Save and come back later' button. This save-as-draft functionality is not available to applicants, only solicitors, so this commit removes the button from the view.

Remove save as draft button from applicant screen

---

app/lib/omniauth/strategies/true_layer.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-1723)
Add a tracking_id to the auth request sent to TrueLayer that allows us to track an individuals session with true layer

AP-1724 add tracking _id for true layer journey

---

config/locales/en/providers.yml

**What**
https://dsdmoj.atlassian.net/browse/AP-1439
/providers/applications/[client id]/application_confirmation
Remove full stop from 'We've sent an email to [email address].' as it could be seen as a typo. 
**Checklist**

AP-1439 Remove full stop from 'Application created' page

---

app/services/admin/provider_details_service.rb
spec/services/admin/provider_details_service_spec.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-1769)
We have had errors raised where an attempt to add a user failed. We
believe that it was a copy and paste from an outlook email or word
document the text `brand new‑user` was parsed as `BRAND%20NEW\u2011USER`
This adds a test for those circumstances and displays an error on the
admin pages requesting the text be re-typed from scratch.
If the user did it on the portal I would expect the portal to handle the
error on its own

AP-1769: Update ProviderDetailsService

---

app/views/shared/forms/_date_part_input_fields.html.erb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-1767)
Remove html attribute pattern to prevent html form validation because we use our form object to validate not the html as it was not showing gds style errors.

AP1-1767 Remove html attribute pattern to prevent html form validation

---

.circleci/config.yml

In some of the work to ignore webhint and turn uat deploys
off and on again some of the jobs got orphaned.
It was possible for the cucumber tests to fail and still push to live
It is still possible for master uat deploy to fail but as the helm
work is progressing I will leave that one for now!

tech-debt: update circle flow

---

spec/rails_helper.rb
spec/requests/citizens/check_answers_spec.rb

Rspec occasionally fails if Faker generates a firm name (or person's name) with an apostrophe.
the line
`expect(response.body).to include(firm.name)`
will fail if the firm name is "O'Keefe & Sons" because the response body contains the special 
characters apostrophe and ampersand encoded into HTML entities.  
In a further little twist sent just to torment us, it encodes most special characters as the named enitity, e.g. the ampersand as `&amp;` but the apostrophe as a decimal entity `&#39;` rather than the more usual  `&apos;`.
This PR adds a method `html_compare` to `rails_helper.rb` which can be used to overcome that, and so the line above can be written
`expect(response.body).to include(html_compare(firm.name))`
and always pass no matter what Faker throws at it.
Describe what you did …

Helper method to compare HTML in Rspec

---

app/forms/citizens/other_assets_form.rb
config/locales/en/activemodel.yml
config/locales/en/shared.yml
spec/forms/citizens/other_assets_form_spec.rb

*What*
[Link to story](https://dsdmoj.atlassian.net/secure/RapidBoard.jspa?rapidView=233&projectKey=AP&modal=detail&selectedIssue=AP-1582&assignee=5f968777632c6200712e443f)
Description
1/ Change check box text from ‘Any valuable items worth over £500’ to ‘Any valuable items worth £500 or more’.
Reason: our current text does not allow for items worth exactly £500.
2/ Change hint text from ‘Enter the estimated value, minus any sale costs’ to ‘Enter the estimated value’.
Reason: spoke to Dave about this and he agreed that asking for the estimated value is sufficient here, without the added burden of the provider or client having to guess or find out ‘sale costs’.
3/ Validation and Error message if value less than £500 entered:
Estimated value must be £500 or more
User Story
As a provider,
I …

AP-1582 Valuable items content and validation

---

app/views/providers/respondents/show.html.erb

**What**
[Link to story](https://dsdmoj.atlassian.net/secure/RapidBoard.jspa?rapidView=233&projectKey=AP&modal=detail&selectedIssue=AP-1572&assignee=5f968777632c6200712e443f)
Fixed the respondent page where there was a large gap between heading and first question 'Does the opponent have the mental capacity...' .
**Checklist**

AP-1572 Opponent page large gap between heading and first question

---

config/locales/en/providers.yml

*What*
[Link to story](https://dsdmoj.atlassian.net/secure/RapidBoard.jspa?rapidView=233&projectKey=AP&modal=detail&selectedIssue=AP-1636&assignee=5f968777632c6200712e443f)
The following content is potentially misleading as it sounds like getting legal aid is a formality once the case details are entered:
You still have to provide details of the case before we can grant legal aid.
Change it to:
You still need to provide details of the case before we can decide if they’re eligible.
All 6 instances of this page should be updated.
*Checklist*

AP-1636 updated content on means calculation result eligibility page

---

Rakefile

Webhint runs as part of the `rake` test suite. It usually fails. We've removed it from the CircleCI pipeline so it also makes sense to also remove it here, replacing it with `cucumber` so that the feature tests still run.
Webhint can still be run locally by running `rake webhint:generate_reports`.

Remove webhint from Rake

---

config/locales/en/providers.yml

[Link to story](https://dsdmoj.atlassian.net/secure/RapidBoard.jspa?rapidView=233&modal=detail&selectedIssue=AP-1397)
Updated the declaration text in the providers.yml file to include mention of benefits fraud, so that providers are aware of the consequences of their client committing benefits fraud. 
Note: The shared.yml file which contains the text for the application_declaration already includes content regarding benefits fraud, so I did not update this. 

Change text of provider declaration to include benefits fraud

---

spec/factories/transaction_types.rb

Having a debit name with a credit type may have caused issues
This was caused by the transaction type factory picking a random
value using TransactionType::NAMES.values.flatten.sample
Because it was randomised within the factory, re-running rspec with
the same seed would not provide the same type on a subsequent run!

BUGFIX: error on legal_aid_application_spec.rb:278

---

app/forms/statement_of_cases/statement_of_case_form.rb
app/services/malware_scanner.rb
config/locales/en/activemodel.yml
db/migrate/20201022121901_add_status_to_malware_scan_results.rb
db/schema.rb
spec/requests/providers/statement_of_case_spec.rb
spec/services/malware_scanner_spec.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-1745)
- Add an error message when the clamadscan is down.
- Replace the raising of error :ClamdscanError with a raven capture message
- Update tests
This is a temporary fix until we turn this malware scanning into a worker/job that can be retried automatically.

AP-1745 Error handling when Clamav is down or raises an error

---

app/services/flow/flows/provider_start.rb
spec/services/flow/base_flow_service_spec.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-1781)
Add a FlowStep for the delete page to prevent the below error:
```
Flow::FlowError
:path of step :delete is not defined
```
The error occurred when clicking on the delete page as it was not a part of the flow and had no path for step :delete

AP-1781 BugFix for flow on delete path

---

app/views/citizens/means_test_results/show.html.erb
app/views/providers/delete/show.html.erb
app/views/providers/submitted_applications/show.html.erb
spec/requests/providers/delete_controller_spec.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-1581)
Fixed the formatting of some header-value pairs to match formatting everywhere else. The header should have emphasis while the value does not. 

fix formatting of header-value displays

---

app/controllers/auth_controller.rb
app/controllers/citizens/banks_controller.rb
app/controllers/citizens/check_answers_controller.rb
app/controllers/citizens/citizen_base_controller.rb
app/controllers/citizens/gather_transactions_controller.rb
app/controllers/citizens/legal_aid_applications_controller.rb
app/lib/omniauth/strategies/moj_oauth2.rb
app/lib/omniauth/strategies/true_layer.rb
app/models/applicant.rb
app/services/oauth_session_saver.rb
config/application.rb
config/initializers/devise.rb
db/migrate/20201023142248_add_rememberable_to_applicant.rb
db/schema.rb
spec/lib/omniauth/strategies/moj_oauth2_spec.rb
spec/rails_helper.rb
spec/services/oauth_session_saver_spec.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-1778)
We have seen instances of applicants using mobile phones having the session destroyed between making the call to true layer and receiving the call back, which in turn causes an Omniauth CSRF error.  We believe this behaviour is caused by the applicant switching to another app on their mobile phone to look up their credentials and then switching back to the browser to continue.  This has been observed to happen.
Adding the `rememberable` Devise module is not enough to cure this problem because at the start of the applicant journey, the magic link is decoded to provide a `legal_aid_application_id` which is stored in the session.  So even with the `rememberable` module enabled, the new session will not contain the …

AP-1778 Add rememberable Devise module to Applicant

---

bin/delete_uat_release
bin/uat_deploy

Forgot to remove the `--force` flag from the ap-1515 PR and also the `--purge` flag

remove old command flags

---

app/forms/applicants/email_form.rb
spec/forms/applicants/email_form_spec.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-1797)
Call `#strip!` on email address in EmailForm before validation

AP-1797 strip leading and trailing spaces from email address

---

app/controllers/citizens/additional_accounts_controller.rb
app/controllers/citizens/consents_controller.rb
app/controllers/providers/applicant_employed_controller.rb
app/controllers/providers/check_benefits_controller.rb
app/controllers/providers/use_ccms_employed_controller.rb
app/models/concerns/base_state_machine.rb
app/models/legal_aid_application.rb
app/services/reports/mis/non_passported_application_csv_line.rb
app/services/reports/mis/non_passported_applications_report.rb
db/migrate/20201105112815_add_reason_to_state_machine_proxies.rb
db/schema.rb
spec/factories/legal_aid_applications.rb
spec/requests/admin/reports_spec.rb
spec/requests/citizens/additional_accounts_spec.rb
spec/requests/providers/applicant_employed_spec.rb
spec/requests/providers/use_ccms_employed_spec.rb
spec/services/reports/mis/non_passported_application_csv_line_spec.rb
spec/services/reports/mis/non_passported_applications_report_spec.rb

[Link to story](https://dsdmoj.atlassian.net/browse/AP-1784)
- Added `ccms_reason` column to `state_machine_proxies`, and set all existing records in state `use_ccms` to have a `ccms_reason` of `unknown`.
- Added an after block to the `use_ccms` event on the state machine to record reason
- Updated all calls to use_ccms! to provide a reason
- Added `ccms_reason` column to Non-Passported Applications Report
- Moved `base_state_machine.rb`, `non_passported_state_machine.rb` and `passported_state_machine.rb` from `models/concerns` to `models` where they belong

AP-1784 record reason for transitioning to use_ccms
