- spec/models/provider_spec.rb
- spec/requests/saml_sessions_spec.rb
- spec/services/provider_after_login_service_spec.rb
running `rspec --seed 63916` would trigger a set of failing tests
Sometimes the mock_saml is turned on or off for a specific test
If it set and a following test needs it in the other value it
needs to be turned back to false
> FLICKERING-TESTS: ensure saml setting

- app/services/reports/mis/non_passported_application_csv_line.rb
- spec/services/reports/mis/non_passported_application_csv_line_spec.rb
- spec/services/reports/mis/non_passported_applications_report_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1791)
> AP-1791 Add applicant name and deleted status to non-passported report

- app/views/providers/legal_aid_applications/_legal_aid_applications.html.erb
- features/providers/deleting_applications.feature
- features/step_definitions/civil_journey_steps.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1802)
On the applications list page for a provider, hide the delete button for applications with status 'submitted', since these cannot be deleted. Update the cucumber test feature 'delete_applications'.
> hide delete button for submitted applications

- Gemfile
- Gemfile.lock
- spec/helpers/time_helper_spec.rb
- spec/models/scheduled_mailing_spec.rb
- spec/services/ccms/requestors/applicant_add_requestor_spec.rb
- spec/services/ccms/requestors/applicant_add_status_requestor_spec.rb
- spec/services/ccms/requestors/applicant_search_requestor_spec.rb
- spec/services/ccms/requestors/case_add_requestor_spec.rb
- spec/services/ccms/requestors/case_add_status_requestor_spec.rb
- spec/services/ccms/requestors/document_id_requestor_spec.rb
- spec/services/ccms/requestors/document_upload_requestor_spec.rb
- spec/services/ccms/requestors/reference_data_requestor_spec.rb
- spec/services/reports/mis/non_passported_application_csv_line_spec.rb
- spec/services/reports/mis/non_passported_applications_report_spec.rb
Suggestion to remove timecop gem and replace it with rails [ActiveSupport::Testing::TimeHelpers ](https://api.rubyonrails.org/v5.2.4/classes/ActiveSupport/Testing/TimeHelpers.html)
Non blocker issue:
- The TimeHelper turns nanoseconds to 0 and this means tests for the #transaction_request_id will have 0 in place of the nanosecond making the test less accurate bot not wrong.
> Note that the usec for the time passed will be set to 0 to prevent rounding errors with external services, like MySQL (which will round instead of floor, leading to off-by-one-second errors).
> Remove timecop gem

- app/services/test_application_creation_service.rb
- spec/factories/legal_aid_applications.rb
- spec/mailers/submit_provider_financial_reminder_mailer_spec.rb
- spec/models/legal_aid_application_spec.rb
- spec/requests/admin/legal_aid_applications_spec.rb
- spec/requests/providers/restrictions_spec.rb
- spec/services/reports/mis/non_passported_applications_report_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1799)
Fix `state_machine` traits in the `legal_aid_applications` factory so that they use `update!` instead of `update`. This has surfaced some failing tests which are also fixed here.
> AP-1799 Use update! in factories

- app/models/address.rb
- app/services/address_lookup_service.rb
- config/initializers/settings.rb
- spec/services/address_lookup_service_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1425)
- Don't send a sentry message if the user has typed a postcode with the correct format but was a mistype.
- test the changes
> AP1425 Suppress Sentry alerts for postcode not found

- config/sidekiq.yml
- spec/services/metrics/sidekiq_queue_sizes_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1595)
ActiveStorage is enqueing `active_storage_analysis` and `active_storage_purge ` jobs which are never being processed because sidekiq does not know about the queues. There are currently ~6000 analysis and ~60 purge jobs queued in production. This change adds queue details to `config/sidekiq.yml` so that those jobs will be processed.
> AP-1595 Enable ActiveStorage sidekiq queue

- app/controllers/admin/legal_aid_applications_controller.rb
- app/models/legal_aid_application.rb
- spec/factories/legal_aid_applications.rb
- spec/models/legal_aid_application_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1808)
- Allow the deletion of the applicant when its application is deleted. This deletes it's bank transaction data, too.
- Remove deletion of applicant in admin controller as deleting the application deletes the applicant now
> AP-1808 Allow destroying application to destroy the applicant it belongs to

- features/support/env.rb
- Update the features config to prevent the auto mix-in of Rack::Test helpers as they aren't being used.
> Update cucumber-rails config

- app/services/ccms/submitters/add_applicant_service.rb
- app/services/ccms/submitters/add_case_service.rb
- app/services/ccms/submitters/base_submission_service.rb
- app/services/ccms/submitters/check_applicant_status_service.rb
- app/services/ccms/submitters/check_case_status_service.rb
- app/services/ccms/submitters/obtain_applicant_reference_service.rb
- app/services/ccms/submitters/obtain_case_reference_service.rb
- app/services/ccms/submitters/obtain_document_id_service.rb
- app/services/ccms/submitters/upload_documents_service.rb
- spec/services/ccms/submitters/add_applicant_service_spec.rb
- spec/services/ccms/submitters/add_case_service_spec.rb
- spec/services/ccms/submitters/check_applicant_status_service_spec.rb
- spec/services/ccms/submitters/check_case_status_service_spec.rb
- spec/services/ccms/submitters/obtain_applicant_reference_service_spec.rb
- spec/services/ccms/submitters/obtain_case_reference_service_spec.rb
- spec/services/ccms/submitters/obtain_document_id_service_spec.rb
- spec/services/ccms/submitters/upload_documents_service_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1268)
Added StandardError, Savon::Error, Savon::HTTPError and Savon::SOAPFault to the rescue clause when submitting a request to ccms. This is in order to then update the submission history table with the errors that weren't being caught before.
> AP-1268 Rescue uncaught errors during CCMS submission

- Gemfile
- Gemfile.lock
- app/forms/statement_of_cases/statement_of_case_form.rb
- spec/requests/providers/statement_of_case_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1804)
There is a security vulnerability in the way we check for valid statement of case file types using the file's `content_type`, which can be forged in HTTP requests.
Instead we can use the `MimeMagic` gem, which is able to examine the content of the file itself in order to identify the type more accurately.  This was chosen over the similar `Ruby-FileMagic` gem as it's easier to implement and better maintained.
> AP-1804 Add MimeMagic gem to validate file types

- app/controllers/saml_sessions_controller.rb
- spec/requests/saml_sessions_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1789)
When a CCMS user without Apply permissions tries to login they get an error due to a malformed SAML response from the portal. 
This change will capture the error and redirect the user to the access denied page
The `/invalid_login` page would appear to be the more appropriate page to redirect the user to, but this currently requires the user to have an account created for them when the login failed, however due to the SAML response this doesnt happen.
> Ap 1789 portal auth error

- config/initializers/redis.rb
Changes to the redis gem were causing deprecation warnings to be constantly displayed by sidekiq. We added a redis initializer to suppress those warnings.
The issue with redis has subsequently been [fixed](https://github.com/resque/redis-namespace/pull/171) however our initializer is now causing the deprecation warning to be displayed when running eg rspec or cucumber from the command line:
Removing the initializer prevents the deprecation warning from being displayed on the command line and does not reintroduce the warning to sidekiq.
> Remove redis initializer to prevent deprecation warning being displayed

- config/environments/development.rb
- config/environments/test.rb
- config/locales/cy/generic.yml
- config/locales/en/generic.yml
- config/locales/en/transaction_types.yml
- features/cassettes/Citizen_journey_in_Welsh/Follow_citizen_journey_from_Accounts_page.yml
- features/citizens/citizens_welsh.feature
- features/step_definitions/citizens_steps.rb
- spec/i18n_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1678)
In order to thoroughly test for missing Welsh translations on the applicant journey, this PR:
* expands the existing `spec/i18n_spec.rb` test (which previously only tested for missing Welsh translations on the `/citizens` path) to also test for missing Welsh translations on `/accessibility_statement`, `/contact`, `/error`, `/feedback`, and `/privacy_policy`.
* sets `config.action_view.raise_on_missing_translations` to true in `development` and `test` environments so that missing translations are surfaced as exceptions instead of falling back on default values (and fixes some missing translations identified as a result 😬).
* adds new feature tests to visit all pages on the citizen journey in Welsh - combined with the above change …
> AP-1678 Test for missing Welsh translations

- app/forms/statement_of_cases/statement_of_case_form.rb
- spec/requests/providers/statement_of_case_spec.rb
- Allow docx and doc file types
mimemagic gem returns content type application/zip for docx or doc type files and zip files are not allowed to be uploaded
https://github.com/minad/mimemagic#extra-magic-overlay
> Allow microsoft word documents to be uploaded on the statement of case page

- .circleci/config.yml
- app/assets/stylesheets/admin/submissions.scss
- app/controllers/admin/legal_aid_applications/submissions_controller.rb
- app/helpers/hash_format_helper.rb
- app/views/admin/legal_aid_applications/_legal_aid_applications.html.erb
- app/views/admin/legal_aid_applications/submissions/show.html.erb
- config/locales/en/admin.yml
- config/routes.rb
- features/admin/application_list.feature
- features/step_definitions/admin_steps.rb
- features/support/env.rb
- spec/helpers/hash_format_helper_spec.rb
- spec/requests/admin/legal_aid_applications/submissions_controller_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1269)
Add an additional controller/view to display data from the CFE and CCMS submissions
This will allow admin users to view this data without relying on Devs manually extracting and parsing data
I have included the CFE result behind a collapsible details section so that it can be readers choice and they don't have to scroll past it to get to the CCMS submission data
There should be a subsequent ticket to add the Submission History XML request and response
> AP-1269:View for submission data on admin pages

- app/controllers/admin/admin_base_controller.rb
- app/controllers/admin/reports_controller.rb
- app/controllers/citizens/additional_accounts_controller.rb
- app/controllers/citizens/consents_controller.rb
- app/controllers/providers/use_ccms_controller.rb
- app/models/concerns/base_state_machine.rb
- app/models/concerns/non_passported_state_machine.rb
- app/models/legal_aid_application.rb
- app/services/reports/mis/non_passported_applications_report.rb
- spec/factories/legal_aid_applications.rb
- spec/requests/citizens/additional_accounts_spec.rb
- spec/requests/providers/use_ccms_spec.rb
Users were being told to use CCMS but the applications weren't in all cases being switched to `use_ccms` state with an appropriate reason.  This PR rectifies that.
It also ensures that the admin reports are not cached so that a fresh copy is sent every time.
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1790)
> AP-1790 Ensure state change to use_ccms

- app/services/ccms/submitters/obtain_document_id_service.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1552)
Update the comment on pdf attachments to reveal that we ignore the original statement of case
document and only send the pdf version/attachment.
> AP-1552 Update the comment on pdf attachments

- lib/tasks/helpers/permissions_updater.rb
- lib/tasks/permissions_updater.rake
- spec/lib/task_helpers/permissions_updater_spec.rb
**What**
[Link to story](https://dsdmoj.atlassian.net/secure/RapidBoard.jspa?rapidView=233&projectKey=AP&modal=detail&selectedIssue=AP-1810&assignee=5f968777632c6200712e443f)
Enabled non-passported permissions for all providers.
**Checklist**
> AP-1810 Enable non passported permissions all providers

- app/services/provider_details_creator.rb
- db/seeds/test_provider_populator.rb
- spec/requests/saml_sessions_spec.rb
- spec/services/provider_details_creator_spec.rb
**What**
[Link to story](https://dsdmoj.atlassian.net/secure/RapidBoard.jspa?rapidView=233&projectKey=AP&modal=detail&selectedIssue=AP-1811&assignee=5f968777632c6200712e443f)
All new firms added automatically are able to submit a non-passported application in provider details creator.
**Checklist**
> AP-1811 Give non-passported role automatically to all further new providers

- app/forms/applicants/email_form.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1476)
Add a check that prevents validation of the form when save_as_draft is used.
> AP-1476 update validation save on draft

- app/forms/statement_of_cases/statement_of_case_form.rb
- config/locales/en/activemodel.yml
- spec/requests/providers/statement_of_case_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1255)
- Change wording of error message if no file is uploaded and no text entered
- Change position of error message to above file (this is done by assigning the error to the `original_file` attribute)
> AP-1255 Copy change and error message position change

- app/controllers/citizens/additional_accounts_controller.rb
- app/controllers/providers/applicant_bank_accounts_controller.rb
- app/controllers/providers/confirm_offices_controller.rb
- app/controllers/providers/has_other_dependants_controller.rb
- app/controllers/providers/no_income_summaries_controller.rb
- app/controllers/providers/no_outgoings_summaries_controller.rb
- app/controllers/providers/remove_dependant_controller.rb
- app/lib/govuk_elements_form_builder/form_builder.rb
- app/views/admin/settings/show.html.erb
- app/views/citizens/consents/show.html.erb
- app/views/citizens/student_finances/show.html.erb
- app/views/providers/applicant_employed/index.html.erb
- app/views/providers/confirm_offices/show.html.erb
- app/views/providers/dependants/_form.html.erb
- app/views/providers/has_dependants/show.html.erb
- app/views/providers/no_income_summaries/show.html.erb
- app/views/providers/no_outgoings_summaries/show.html.erb
- app/views/providers/respondents/_respondent_detail.html.erb
- app/views/providers/success_likely/index.html.erb
- app/views/shared/forms/vehicles/_ages.html.erb
- app/views/shared/forms/vehicles/_own_vehicle.html.erb
- app/views/shared/forms/vehicles/_regular_use.html.erb
- spec/requests/citizens/additional_accounts_spec.rb
- spec/requests/providers/applicant_bank_accounts_spec.rb
- spec/requests/providers/confirm_offices_spec.rb
- spec/requests/providers/has_other_dependants_controller_spec.rb
- spec/requests/providers/no_income_summaries_spec.rb
- spec/requests/providers/no_outgoings_summaries_spec.rb
- spec/requests/providers/remove_dependant_controller_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1726)
- Update form builder method #yes_no_radio_button_array to use the value true or false as true or false has been used in many more places as the radio button value than yes or no.
- Update relevant controllers to expect true or false instead of yes or no
- Update views to pass in (form.yes_no_radio_button_array, :value, :label,...) to the form.govuk_collection_radio_buttons method
- Update tests
> AP-1726 Standardise usage of radio buttons

- app/controllers/admin/legal_aid_applications/submissions_controller.rb
- app/views/admin/legal_aid_applications/submissions/show.html.erb
- config/routes.rb
- spec/factories/ccms_submission_histories.rb
- spec/requests/admin/legal_aid_applications/submissions_controller_spec.rb
**What**
[Link to story](https://dsdmoj.atlassian.net/secure/RapidBoard.jspa?rapidView=233&projectKey=AP&modal=detail&selectedIssue=AP-1279&assignee=5f968777632c6200712e443f)
Added ability to download both XML request and response and tests 
**Checklist**
> AP-1279 XML download button added to submissions

- README.md
~[Link to story](https://dsdmoj.atlassian.net/browse/AP-XXX)~ (there's no ticket for this work)
This commit adds the architecture diagram for Apply to the README.
The CI status badge is also moved to the top along with some new
headings for technical information and dependencies to improve the
structure.
The description seemed like it was for back when this was the API
half of Apply, so it has been updated to a more accurate description
of what the system really does.
The diff has some whitespace removed from the README, apologies. Happy to remove it if it makes it hard to review this.
> Add architecture diagram to README

- app/presenters/bank_transaction_presenter.rb
- spec/presenters/bank_transaction_presenter_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1874)
On the bank transactions CSV file, some sort codes were being interpreted by Excel as dates and displayed wrongly.  This PR forces them to be interpreted as plain text by preceeding them with a single quote
> AP-1874 format sort code as plain text

- app/models/cfe/v2/result.rb
- spec/factories/cfe_results.rb
- spec/factories/cfe_results/v2/mock_results.rb
- spec/factory_specs/cfe_result_factory_spec.rb
- spec/models/cfe/v2/result_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1875)
We are no longer using the monthly_equivalent calculator to calculate the student loan value. Student loan is now under irregular income instead of other_income and the annual sum is divided by 12. 
Changed `mei_student_loan` to take the value from cfe_result.gross_income[:monthly_student_loan] This ensures that wherever `mei_student_loan` is used (particularly to display results) we now access the correct value.
The `monthly_student_loan` value is already being included in the calculations for total monthly/disposable income etc. So the totals and calculations are all still correct it is only on pages where we breakdown by income type that the values are not being displayed.
> ap-1875 display the student loan value

- README.md
~[Link to story](https://dsdmoj.atlassian.net/browse/AP-XXX)~
Change the architecture diagram to be a link instead of an embedded image.
> Change the architecture diagram to be a link

- app/views/layouts/pdf.html.erb
- spec/cassettes/stylesheets.yml
- spec/cassettes/stylesheets2.yml
- spec/requests/providers/means_reports_spec.rb
- spec/requests/providers/merits_reports_spec.rb
- spec/services/reports/means_report_creator_spec.rb
- spec/services/reports/merits_report_creator_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1876)
Changed the wicked_pdf pack tag to wicked_pdf link tag pointing to the compiled webpack stylesheets, so that the means report displays with the correct formatting. 
> Ap 1876 report formatting

- app/controllers/admin/legal_aid_applications/submissions_controller.rb
- app/views/admin/legal_aid_applications/submissions/show.html.erb
- app/views/layouts/pdf.html.erb
- config/routes.rb
- features/admin/application_list.feature
- features/step_definitions/admin_steps.rb
- spec/requests/admin/legal_aid_applications/submissions_controller_spec.rb
Add method of opening generated reports from submission page
This is to help us debug issues where documents generated and sent to CCMS do not match the /means_report view
> Bugfix: Webpacker pdf report display

- app/helpers/pdf_helper.rb
- app/views/admin/legal_aid_applications/submissions/show.html.erb
- app/views/layouts/pdf.html.erb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1876)
This requires a new helper method.  
Basically, the wicked helpers are very limited in usefulness and restrictive in how they function/expect your service to function.
Therefore I reverse-engineered what their helper does and wrapped dit in out own helper that reads the CSS from the webpack object (regardless of it's compiled name) and exports it as an on-page stylesheet tag
I also added a fix to only show download links on the admin pages if the report has a document (and can therefore be downloaded)
> Bug-fix: Webpacker pdf fix

- app/views/providers/statement_of_cases/show.html.erb
- config/locales/en/providers.yml
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1705)
Display hint text informing users of maximum file size.
> AP-1705 Add hint text to statement of case screen

- app/mailers/feedback_mailer.rb
[AP-1670](https://dsdmoj.atlassian.net/browse/AP-1670)
Update feedback mailer to use actual translations rather than input keys for feedback emails.
> AP-1670: Update Feedback Mailer to get correct translations for Notify feedback personalisations

- .overcommit.yml
- Gemfile
- Gemfile.lock
- README.md
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1886)
Added the overcommit gem, which allows you to configure pre-commit hooks for the whole project. 
Added rubocop and erblint to pre-commit hooks. 
This is to try to prevent the issue of starting pipelines which fail on lint checks. 
Instructions to install locally are in the README. 
> Ap 1886 add overcommit gem 

- app/webpack/src/checkbox_control.js
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1817)
Add some javascript that sets the value to true when the None of these checkbox is selected and sets it to false when it is deselected by clicking any of the other options.
The value for None of these is still set as default true on page load.
> AP-1817 checkbox bugfix

- app/mailers/concerns/notify_template_methods.rb
- app/mailers/notify_mailer.rb
- app/mailers/resend_link_request_mailer.rb
- app/mailers/submit_citizen_financial_reminder_mailer.rb
- app/services/submit_citizen_reminder_service.rb
- config/govuk_notify_templates.yml
- spec/mailers/notify_mailer_spec.rb
- spec/mailers/submit_application_reminder_mailer_spec.rb
- spec/mailers/submit_citizen_financial_reminder_mailer_spec.rb
- spec/services/submit_citizen_reminder_service_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1807)
Added in new parameter for client emails to include the date on which the url expires. 
URL is set to expire 7 days from the date it is issued. Reminder emails have the date set on the day they are scheduled
For UAT testing this has 3 new notify templates. Once it has passed UAT these will need to be removed and the original templates updated to include the new wording and date. This will then need to be tested in staging before release to production.
> Ap 1807 applicant email

- app/webpack/src/table-select-all.js
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1833)
Converted the jQuery code that allows a user to select all/clear all in a table to vanilla javascript. This makes the select all functionality accessible to users who are using non-jQuery-supporting browsers/technology. 
> Convert jQuery in table-select-all.js to javascript 

- app/controllers/citizens/additional_accounts_controller.rb
- app/forms/applicants/open_banking_consent_form.rb
- app/views/citizens/additional_accounts/_error.html.erb
- app/views/citizens/additional_accounts/index.html.erb
- app/views/citizens/additional_accounts/new.html.erb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1888)
* Add a partial to display error summaries on the `/additional_accounts` screens [1]
* Add a better-worded error for `/additional_accounts/new` 
* Fix the issue where html was being displayed in the error summary
[1] we're using this pattern in a number of places - there are at least eight other versions of the errors partial knocking about 🤦 I'm going to create a separate ticket to look at refactoring that to remove the duplication.
> AP-1888 Display error summaries on additional accounts screens

- db/sample_data/bank_transactions_3.csv
- lib/tasks/cfe_printer.rake
- lib/tasks/helpers/cfe_payload_recorder.rb
Sometimes it is necessary to replay what apply sent to CFE in order to debug something in CFE.  This PR introduces that ability with a rake task that will read the CFE::SubmissionHistory records for an application, and output the details as YAML which can then be replayed locally to CFE with the `rake replay` task in the CFE repo.
`rake cfe:record_payloads[L-A12-B34]`
This will print out YAML which can be copied and pasted into the `tmp/api_replay.yml` file in the CFE project ready for the `rake replay` task.
> Record CFE API interaction

- app/mailers/submit_application_reminder_mailer.rb
- spec/mailers/submit_application_reminder_mailer_spec.rb
- spec/services/submit_application_reminder_service_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1878)
Change formatting of the dates we include in the substantive reminder email to exclude any preceding zeros in the day field on date, to be inline with GDS guidelines https://www.gov.uk/guidance/style-guide/a-to-z-of-gov-uk-style
> AP-1878 update styling to match GDS

- Dockerfile
We have had a few [circle failures like these](https://app.circleci.com/pipelines/github/ministryofjustice/laa-apply-for-legal-aid/6061/workflows/ed269959-f68f-47a9-9355-dbfac998f189/jobs/42462) today. This is caused by the `curl` command (used to install `kubectl`) in the docker file, failing.
The actual error is 
` OpenSSL SSL_read: SSL_ERROR_SYSCALL, errno 104`
Which seems to just be caused by an intermittent network issue, so it is difficult to replicate. The output at the moment does not give any indication that the retries are occurring.
I have added the flag `--retry-connrefused `to see if this can help with these errors. This flag may give us another opportunity at retrying the connection/`curl` command before it fails.
> add new retry for curl:

- Gemfile
- Gemfile.lock
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1909)
This is because it is disllowed by our csp policy. I've left a git issue in their repo better_errors/issues/496#issue-762183543
- Remove better_errors and its required binding_of_caller gem.
> AP-1909 Remove better_errors gem

- app/views/providers/statement_of_cases/show.html.erb
- config/locales/en/providers.yml
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1900)
- Remove opponent name as a bullet point because we record this value earlier in the application journey.
> AP-1900 Remove "the opponent's name" content from the statement of case page

- app/controllers/admin/settings_controller.rb
- app/forms/settings/setting_form.rb
- app/models/setting.rb
- app/views/admin/settings/show.html.erb
- config/locales/en/admin.yml
- config/locales/en/helpers.yml
- db/migrate/20201210161115_add_cash_payment_flag_to_settings.rb
- db/schema.rb
- lib/tasks/setup_db_for_testing.rake
- spec/models/setting_spec.rb
- spec/requests/admin/settings_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1852)
Add a new feature flag to the `/admin/settings` page which will hide/show access to the cash payments part of the Apply journey.
The new setting is called `:allow_cash_payment`
> AP-1852 add feature flag for cash payments

- helm_deploy/apply-for-legal-aid/templates/network-policy.yaml
- helm_deploy/apply-for-legal-aid/templates/service-monitor.yaml
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1870)
Following a discussion with a Cloud Platform representative, I have restored the `network-policy` and `service-monitor` templates, as they monitor the metrics endpoint.
> AP-1870: Update prometheus alerting

- app/controllers/providers/use_ccms_controller.rb
- app/models/concerns/base_state_machine.rb
- spec/requests/providers/use_ccms_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1907)
The `Providers::UseCCMSController` sets the state to `use_ccms` and the `ccms_reason` to a value depending on what page the request came from.  This does not work well if an application is already in `use_ccms` state, and it is viewed from the applications list page.  This bug is fixed by not calling '#use_ccms!' if the state is already `use_ccms`
> AP-1907 Fix unknown ccms reason

- .overcommit.yml
- package.json
- yarn.lock
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1887)
Add standard JS - a linting package for JavaScript
Added to overcommit.yml file so it will run on pre-commit hook
> add standard js

- config/environments/production.rb
- config/environments/test.rb
When sprockets was removed, these became superflouous and can/should be removed
> Tech-debt: remove asset config

- Gemfile
- Gemfile.lock
- README.md
- spec/rails_helper.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1857)
Add `pry-rescue` and `pry-stack_explorer` gems so that rspec tests are halted to allow investigation when a failure occurs.
This does not happen automatically when running `bundle exec rspec`. A developer needs to run `bundle exec rescue rspec` for this to take affect; the readme has been updated to reflect this. A further ticket will be added to spike an investigation into automatically running `pry-rescue` as part of the standard rspec test suite.
> AP-1857 Add pry-rescue gems

- app/services/ccms/payload_generators/entity_attributes_generator.rb
- spec/services/ccms/payload_generators/entitiy_attributes_generator_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1939)
During the ccms submission we generate entitiy attributes
- This change captures the error and sends a message to Sentry via Raven explaining the config. This allows for better debugging.
After rescuing the error , it reraises it. It'll be rescued again later. This rescue duplication is so that we can check
what the config looked like in the attribute generation.
- Test this
> Capture exceptions during entity attributes generation

- .rubocop.yml
As time passes and the log and tmp folders increase in size
rubocop initialisation slows down because it pre-scans all
files
By ignoring them it speeds up considerably
> Fix: Speed up rubocop

- app/forms/applicants/basic_details_form.rb
- app/forms/concerns/date_field_builder.rb
- app/views/shared/forms/_applicant_form.html.erb
- spec/forms/applicants/basic_details_form_spec.rb
* revert the fields to DATE_PARTS : this was actually okay as-was and did not need to be updated
* Update the basic_details_form  - The conversion between date_of_birth and dob was causing issues
date_of_birth would load and render on the view but not save
dob would save but would not load when the form was rendered
Removing the conversion makes the field names longer but allows rendering _and_ saving!
> formbuilder: date of birth updates

- app/views/admin/legal_aid_applications/submissions/show.html.erb
- spec/helpers/hash_format_helper_spec.rb
Fix bug ActionView::Template::Error undefined method `result' for nil:NilClass
in sentry [here](https://sentry.io/organizations/ministryofjustice/issues/2134505463/?project=5416054&query=is%3Aunresolved)
- Do this by returning result: 'nil' to signifiy an empty cfe_result as opposed to an empty string
- Test the format helper to show that a hash with an empty value returns an empty string ''
- result: 'nil' passed to format_helper will show Result: Nil for every nil cfe_result instead of using {result: nil} which would return an empty string and not displayed.
> AdminPage: Return result for empty cfe submission result

- app/models/bank_account.rb
- app/services/ccms/attribute_value_generator.rb
- config/ccms/attribute_block_configs/base.yml
- config/ccms/attribute_block_configs/non_passported.yml
- spec/fixtures/files/ccms_keys/standard_ccms_keys.yml
- spec/models/bank_account_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1954)
Raised during work on [AP-1859](https://dsdmoj.atlassian.net/browse/AP-1859)
Bank account holder information is hardcoded for CCMS attributes in several places. Tidy this up by reducing this to a single coding in the `BankAccount` model and let all other places reference that. This will make further analysis of the other CCMS attributes easier.
Also:
* Fixes an error in the `BankAccount` model where `ClientSole` should be `Client Sole`.
* Renames the `bank_account_holders` method to `bank_account_holder_type` to remove possible confusion with the `BankAccountHolder` model used elsewhere.
* Changes a hardcoded CCMS bank name attribute from `Mock Bank` to use the actual bank name.
> AP-1954 Remove account holder duplication

- app/models/legal_aid_application.rb
- app/services/reports/mis/non_passported_application_csv_line.rb
- spec/services/reports/mis/non_passported_application_csv_line_spec.rb
- spec/services/reports/mis/non_passported_applications_report_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1941)
Populates the date the application was submitted to CCMS on the non-passported application report.
> AP-1941 Add date_submitted to non-passported csv

- app/controllers/concerns/providers/application_dependable.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1959)
As part of the `Providers::ApplicationDependable` module, every controller set the `provider_step` field to the name of the controller.  This is to allow the application to be saved, and then picked up at the same place at a later date.
Unfortunately, this is also true for the DeleteController.  If the user accidentally hits the delete button, then backs out, the provider step remains set at delete.  This means that when they click on the application from the index page, it immediately asks them to confirm they want to delete the application (thank God!)
Solution: Don't set the provider step to `:delete`
> AP-1959 BUGFIX do not set provider step to delete

- spec/factories/cash_transactions.rb
- spec/models/aggregated_cash_income_spec.rb
Update variables created between rubocop update PR being created and merged to master
> Fix: rename variables inline with new rubocop

- app/mailers/feedback_mailer.rb
- config/govuk_notify_templates.yml
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1917)
Created a new version of the feedback template on Notify, that adds a `non_live_env` suffix to the subject line
Added a helper method to the feedback_mailer that checks for uat, staging, or localhost in the current host URL and sends ' -non live' to the template
If none of those are found, it will send an empty string ('') as notify does not handle nil gracefully!
> AP-1917: Identify non live feedback

- app/controllers/admin/legal_aid_applications_controller.rb
- app/views/admin/legal_aid_applications/index.html.erb
- config/locales/en/admin.yml
- config/locales/en/generic.yml
- config/locales/en/helpers.yml
- config/routes.rb
- features/admin/application_list.feature
- features/step_definitions/admin_steps.rb
- spec/requests/admin/legal_aid_applications_controller_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1938)
Added a search form to the Admin/application list page
This allows admin users to search for Client (case insensitive name matches anywhere e.g. `th` would match `Theon Grayjoy` and `Sarah Smith`), ccms_reference, and application id or reference (exact matches only)
An error message is displayed if an admin hits search with no criteria
> AP-1938: admin search

- app/models/legal_aid_application.rb
- app/views/shared/check_answers/_assets.html.erb
- config/locales/en/providers.yml
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1934)
Under "which types of savings and investments does your client have?", if there is no Savings (or Current) Account uploaded, this will show 'None Declared'. If it is uploaded with a balance of 0, this will still show as £0.
> AP-1934 Show savings account as "none declared" on caseworker means report

- README.md
- config/environments/test.rb
- Set the log_level to fatal which logs when something happens that causes the application to crash. This reduces log pollution and speeds up testing.
- Create an environment variable ENV['RAILS_ENABLE_TEST_LOG'] to allow default logging in the test environment e.g.
`RAILS_ENABLE_TEST_LOG=1 rspec ./spec`
- Update readme
resources: https://jtway.co/speed-up-your-rails-test-suite-by-6-in-1-line-13fedb869ec4
> Reduce log pollution in the testing environment

- app/controllers/providers/income_summary_controller.rb
- app/controllers/providers/outgoings_summary_controller.rb
- app/models/cash_transaction.rb
- app/views/providers/income_summary/index.html.erb
- app/views/providers/outgoings_summary/index.html.erb
- app/views/shared/_cash_transactions.html.erb
- config/locales/en/providers.yml
- config/locales/en/shared.yml
- db/migrate/20210115142828_update_column_type_on_cash_transactions.rb
- db/migrate/20210115142908_delete_column_on_cash_transactions.rb
- db/migrate/20210115155032_reinstate_cash_transaction_index.rb
- db/schema.rb
- spec/models/cash_transaction_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1524)
Added a shared partial to show the cash transactions to the providers on the income and outgoings summary pages.
Added conditionals to hide the content where cash transactions dont exist.
Moved the student finance section out of the Ordered list
on income summary as it was more appropriate in the Other income section.
> Ap 1524 display cash

- app/controllers/providers/proceedings_types_controller.rb
- app/services/proceeding_types_service.rb
- app/views/providers/proceedings_types/index.html.erb
- app/views/shared/forms/proceedings_types/_legacy_proceeding_type_form.html.erb
- app/views/shared/forms/proceedings_types/_proceeding_type_form.html.erb
- app/webpack/src/modules/proceedings.js
- config/locales/en/providers.yml
- features/accessibility/provider.feature
- features/providers/civil_application_journey.feature
- features/step_definitions/civil_journey_steps.rb
- spec/requests/providers/proceedings_types_spec.rb
- spec/services/proceeding_types_service_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1925)
- Add new multiple proceedings view/form behind feature flag. seperate the proceeding_types_form into two , one for the old implementation and the new one this will introduce.
- Update proceeding types controller and add a proceeding types service object which encapsulates the adding of proceeding types with a substantive scope limitation.
- Update the proceedings.js file for the multiple proceedings feature
- Update tests
> AP1925 multiple proceedings search

- app/services/true_layer/importers/import_accounts_service.rb
- app/services/true_layer/importers/import_provider_service.rb
- app/services/true_layer/importers/import_transactions_service.rb
- config/environments/test.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1976)
- There's no need for the level of detail in the logs to see bank info so silence the logs around it.
- Silence logs around bank info.
- Update the test environment to use the defualt logger ActiveSupport::Logger as it includes the #silence method needed to carry out the above tests.
> AP-1976 fix silencing logs around certain functions

- app/views/providers/end_of_applications/show.html.erb
- config/locales/en/providers.yml
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1910)
Updated the content to providers know what they are supposed to retain in terms of evidence of financial eligibility
> ap-1910 update end of application content

- app/controllers/citizens/check_answers_controller.rb
- app/jobs/bank_transactions_analyser_job.rb
- spec/jobs/bank_transactions_analyser_job_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1991)
We send the citizen completed means to the provider before the appliction has completed submission as in completed the bank transaction analyser job
This means the provider won't think to continue on with an application with the wrong state
> AP-1991 Shift the citizen completed means mailer to a later stage

- app/services/cfe/create_capitals_service.rb
- spec/services/cfe/create_capitals_service_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1993)
CFE is failing if on the non-passported journey the provider says yes to "Does your client have any savings account your client cannot access on-line".  
This is because in the non-passported journey, we only ask for savings account, not current account, so that field remains nil.  This value of nil was being sent to CFE, which rejected it as invalid.
The solution is not to send details of any field which is nil.
> BUGFIX - Don't send details for current account to CFE when nil

- app/models/concerns/base_state_machine.rb
- app/models/legal_aid_application.rb
- spec/models/legal_aid_application_spec.rb
- spec/requests/admin/legal_aid_applications/submissions_controller_spec.rb
- spec/requests/admin/submitted_applications_reports_spec.rb
- spec/services/reports/reports_creator_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1962)
The legal_aid_application model overrides the default ccms_submission method, causing it to create a new submission when it is called (if one doesn't already exist)
- remove the method 
- fix some tests which break as a result
> AP-1962 Remove overriden ccms_submission method

- app/services/cfe/create_capitals_service.rb
The code was testing `current_account_balance` for nil in order to decide whether or not to include `savings_account_balance` in the CFE payload for capital.  It should of course be testing `savings_account_balance`.  This bug was causing savings account balance of nil to be sent to CFE which caused a validation error.
> BUGFIX - test savings account balance not current account balance

- app/forms/statement_of_cases/statement_of_case_form.rb
- config/locales/en/providers.yml
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1955)
Users are currently able to upload statement of case files up to 8mb in size. This can cause issues after base64 encoding - there is a 10mb limit on the AWS gateway, and encoded files can exceed that limit.
This amends the `StatementOfCase` model to reduce the permitted file size to 7mb, which is hopefully low enough to prevent the 10mb limit being hit.
> AP-1955 Reduce size of statement of case uploads

- app/helpers/check_answers_helper.rb
- app/helpers/transaction_type_helper.rb
- app/models/base_aggregated_cash_transaction.rb
- app/models/cash_transaction.rb
- app/services/flow/flows/citizen_capital.rb
- app/views/citizens/cash_incomes/_cash_income_form.html.erb
- app/views/citizens/check_answers/_cash_transactions.html.erb
- app/views/citizens/check_answers/index.html.erb
- app/views/shared/check_answers/_no_link_cash_transaction_item.html.erb
- app/views/shared/partials/_revealing_checkbox.html.erb
- config/locales/cy/activemodel.yml
- config/locales/cy/citizens.yml
- config/locales/cy/dates.yml
- config/locales/cy/shared.yml
- config/locales/en/activemodel.yml
- config/locales/en/citizens.yml
- config/locales/en/shared.yml
- features/cassettes/Citizen_journey/Follow_citizen_journey_from_Accounts_page_selecting_both_income_and_outgoing_categories.yml
- features/cassettes/Citizen_journey/Follow_citizen_journey_from_Accounts_page_selecting_no_income_or_outgoing_categories.yml
- features/citizens/citizens.feature
- lib/tasks/helpers/cy_helper.rb
- spec/models/cash_transaction_spec.rb
- spec/requests/citizens/check_answers_spec.rb
- spec/requests/citizens/identify_types_of_outgoings_spec.rb
- spec/services/cfe/create_capitals_service_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1937)
* Implements the sections for Incoming and outgoing cash payments on the Citizen Check Your Answers page
* Flow skips cash income or cash outgoings pages if no categories were selected on the previous page
> AP-1937 Citizens CYA for cash receipts and payments

- app/views/providers/other_assets/_form.html.erb
- app/views/shared/forms/_offline_accounts_form.html.erb
- app/views/shared/forms/_savings_and_investments_form.html.erb
- app/views/shared/forms/policy_disregards/_form.html.erb
- app/webpack/src/checkbox_control.js
- features/providers/civil_application_journey.feature
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1990)
- Removed jQuery from checkbox_control.js
- Changed the data-deselect-ctrl attribute in some forms so the 'none_selected' checkbox is always selected by id and not name attribute
- Added the policy disregards page to the 'changing checkbox answers via back button' cucumber test
> AP-1990 remove jQuery from checkbox_control.js

- app/views/providers/substantive_applications/show.html.erb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1973)
Refactor `/app/views/providers/substantive_applications/show.html.erb` to use the new formbuilder.
> AP-1973 Convert substantive form to use new formbuilder

- bin/delete_ecr_images
- Use DateTime instead of Time class for strptime method. This is because it raises a bug in circleci:
```bash
./bin/delete_ecr_images:15:in `block in <main>': undefined method `strptime' for Time:Class (NoMethodError)
```
This is because we require 'date' in the delete_ecr_images file. Instead of requiring 'time' and using Time objects etc. I changed the code to use DateTime. This uses .in_time_zone and DateTime.current to meet TimeZone standardisations requirements.
> BUGFIX Use DateTime instead of Time class for strptime method

- bin/delete_ecr_images
This is because #in_time_zone and #current aren't methods of DateTime object. Also, this ruby file is not requiring **ActiveSupport** and all of it's date / time / timezone **extensions** including #in_time_zone and #current
This fixes the issue:
```bash
./bin/delete_ecr_images:15:in `block in <main>': undefined method `in_time_zone' for #<DateTime:0x0000560e3caf61a8> (NoMethodError)
```
The ruby core Time class is not extended by the rails ActiveSupport::TimeZone which has the benefits of Time.**current** etc.
Therefore #in_time_zone is not extended onto Date objects (DateTime).
As this is a nightly job, I don't believe it's neccessary to require 'activesupport/all' here and i don't think timezones will be an issue on this job.
**Resource**: …
> BUGFIX NightlyJob, undo timezone adherence for cleaning ecr images

- config/locales/cy/dates.yml
- config/locales/en/dates.yml
- spec/helpers/transaction_period_helper_spec.rb
- This puts the long date as e.g. 21 October 2020
rather than October 21, 2020
It is used in the transactions_helper. Above the transactions table we have 21 October 2020 to 21 January 2021
- Update the tests
> Update the long_date form for i18n localisation

- app/controllers/providers/delegated_functions_dates_controller.rb
- app/controllers/providers/used_delegated_functions_controller.rb
- app/forms/legal_aid_applications/confirm_delegated_functions_date_form.rb
- app/forms/legal_aid_applications/delegated_functions_date_form.rb
- app/services/flow/flows/provider_start.rb
- app/views/providers/delegated_functions_dates/show.html.erb
- config/locales/en/activemodel.yml
- config/locales/en/providers.yml
- config/routes.rb
- features/providers/civil_application_journey.feature
- features/support/steps_helper.rb
- spec/forms/legal_aid_applications/delegated_functions_date_form_spec.rb
- spec/requests/providers/delegated_functions_date_spec.rb
- spec/requests/providers/used_delegated_functions_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1957)
- Add a new page to confirm the delegated functions date
- Duplicate the used delegated functions form with some changes for the new page. This is because the used delegated functions form is already complicated enough and reusing it will make it more so, thus it seems better to have duplication.
- Add requests tests and form tests
- Update the  feature tests
> AP-1957 delegated functions date confirmation page

- .rubocop.yml
- bin/bundle
This is because #present? is not a ruby method and this file is not a rails file.
> BugFix reverse rubocop fix for bin/bundle file 

- app/views/providers/other_assets/_second_home_conditional_checkbox.html.erb
- app/views/shared/forms/revealing_checkbox/_attribute.html.erb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1996)
Fixed so that fields are expanded to show errors on the conditionally revealed fields 
> AP-1996 show checkbox errors on revealed fields

- app/models/cfe/v3/result.rb
- app/services/cfe/obtain_assessment_result_service.rb
- spec/factories/cfe_results.rb
- spec/factories/cfe_results/v3/mock_results.rb
- spec/factories/legal_aid_applications.rb
- spec/factory_specs/cfe_result_factory_spec.rb
- spec/models/cfe/v3/result_spec.rb
- spec/requests/providers/means_reports_spec.rb
- spec/services/cfe/obtain_assessment_result_service_spec.rb
- spec/services/reports/means_report_creator_spec.rb
[AP-1970](https://dsdmoj.atlassian.net/browse/AP-1970)
To complete the cash transactions work this PR parses the CFE V3 response when admin settings are set to include cash transactions. V3 CFE result factories and traits have been setup, separately to V2, with a view for the latter to be removed once this work is all live.
> AP-1970: Parse CFE V3 response and add relevant tests for it

- app/helpers/check_answers_helper.rb
- app/views/layouts/pdf.html.erb
- app/views/providers/means_reports/show.html.erb
- app/views/shared/check_answers/_capital_result.html.erb
- app/views/shared/check_answers/_income_result.html.erb
- app/views/shared/check_answers/_item.html.erb
- app/views/shared/check_answers/_merits.html.erb
- app/views/shared/check_answers/_no_link_item.html.erb
- app/views/shared/check_answers/_one_link_section.html.erb
- app/views/shared/check_answers/_property.html.erb
- app/views/shared/check_answers/_restrictions.html.erb
- app/webpack/stylesheets/check-your-answers.scss
[AP-1968](https://dsdmoj.atlassian.net/browse/AP-1968)
Refactored the align right styling as even though it was being set it appears it wasn't being used when an html file was set to read_only for the reports generation. Also wickedpdf sets out it's own formatting when creating a pdf which supersedes class name styling so by setting text-precision this assists with the rendering process to ensure there is whitespace between question/answers in the means (and other) reports. 
> AP-1968: Update styling and read_only values for the means report

- ccms_integration/example_payloads/Dave_Fabby_CaseAddPayload.xml
- ccms_integration/example_payloads/NonPassportedFullMonty.csv
- ccms_integration/example_payloads/NonPassportedFullMonty.xml
- ccms_integration/example_payloads/PassportedSingleProceedingNonMol.xml
- ccms_integration/example_payloads/PassportedSingleProceedingNonMolDelegated.xml
- config/ccms/attribute_block_configs/base.yml
- config/ccms/attribute_block_configs/non_passported.yml
- spec/data/ccms/case_add_request.xml
- spec/services/ccms/requestors/case_add_requestor_xml_blocks/non_passported_additional_property_attributes_spec.rb
- spec/services/ccms/requestors/case_add_requestor_xml_blocks/passported_attributes_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2020)
- Hardcode GB_INPUT_B_17WP2_7A to false 
- Add new attribute GB_INPUT_B_17WP2_8A with hardcode value of false
- remove ccms attribute OTHCAPITAL_INPUT_C_17WP2_14A
- Update tests
left to do:
> AP-2020 Update other capital ccms attributes

- app/models/sent_email.rb
- app/services/govuk_emails/email_monitor.rb
- spec/services/govuk_emails/email_monitor_spec.rb
The SentEmail.create! was failing with a validation error  (not all emails have an email address amongst the parameters) and this was causing the job to fail, and be retried by sidekiq after having sent the mail, resulting in duplicate mails.
This solves the problem by:
- removing the validates presence of addressee
- trapping errors, reporting them to Sentry, and allowing the job to continue
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2042)
> AP-2042 Trap ActiveRecord errors and prevent job from failing

- features/support/steps_helper.rb
One of the steps in the features was changed and there was no helpers
matching the new text.  This updates the step helper so that any
number of days can be used
> BugFix: Update step helper

- app/views/layouts/_header.html.erb
- features/citizens/citizens.feature
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2038)
Use a conditional check to hide the sign in link in the header on the citizen journey but still have it visible for admin and provider journeys.
> ap-2038 remove sign in link from citizen views

- app/views/providers/income_summary/_income_type_item.html.erb
- app/views/providers/outgoings_summary/_outgoing_type_item.html.erb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2043)
added a space and single quote marks to separate out the error name and class, erblint was failing when just a space was added to fix this, which is probably how it got introduced in the first place.
> ap-2043 add quote marks for proper separation

- app/views/layouts/_header.html.erb
Remove leftover code from header of page
> Remove leftover code

- app/jobs/govuk_notify_mailer_job.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2007)
Hide logging mailer arguments for security. This means information about the applicant or provider is kept hidden from logs.
> AP-2007 Hide logging mailer arguments for security

- app/views/providers/restrictions/show.html.erb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2023)
Use form instance instead of legal aid application . This fixes the issue with assigning errors correctly
> AP-2023 BugFix Restrictions page error not appearing correctly

- app/services/flow/flows/citizen_capital.rb
- features/citizens/citizens.feature
- spec/requests/citizens/identify_types_of_incomes_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2021)
Flow now runs correctly: User selects change link on CYA page to return to 'which payments do you receive' then directs to cash_income page before going back to CYA page. I have also added these steps to the relevant feature test.
> AP-2021 Changed the citizen flow to redirect correctly

- app/forms/respondents/respondent_form.rb
- config/locales/en/activemodel.yml
- spec/forms/respondents/respondent_form_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2024)
Form validation added to handle true or false selection. Translations also added.
When nothing selected OR text box is blank, the error is now correctly displayed at the top & at the relevant question level, ie the question is highlighted in red with an appropriate error message.
> AP-2024 error now works when police_notified is blank

- Dockerfile
- app/views/layouts/pdf.html.erb
- app/webpack/stylesheets/check-your-answers.scss
[AP-2033](https://dsdmoj.atlassian.net/browse/AP-2033)
Urgh! Where do I start. PDF generation locally was working whereas in our remote environments it was not. Wicked_PDF is a wrapper for wkhtmltopdf which, when running on our base Docker image which uses alpine, doesn't play nicely and ends up overriding any CSS (if it even exists) with its own defaults. The mostly successful solution to this issue was working out that our docker image needed additional base fonts installed to mitigate this behaviour when wkhtmltopdf runs on alpine. However even so, some in-line styling is needed as the Webkit Q rendering engine isn't perfect due to this. Also whatever we see generated by the html isn't what is going to be generated in the pdf. That is a misconception also noted by the open source …
> AP-2033: Fix PDF generation

- spec/requests/citizens/cash_incomes_spec.rb
- spec/requests/citizens/cash_outgoings_spec.rb
The date was hardcoded to expect November so I've changed it to make sure it won't fail again in the future.
I chose this over a travel_to on the page call as that seemed more fragile for future changes
> Update cash tests

- app/controllers/providers/has_other_proceedings_controller.rb
- app/forms/providers/has_other_proceedings_form.rb
- app/views/providers/has_other_proceedings/show.html.erb
- app/views/providers/proceedings_types/index.html.erb
- app/views/shared/forms/proceedings_types/_proceeding_type_form.html.erb
- spec/requests/providers/has_other_proceedings_controller_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1981)
Updated proceedings types page and has other proceedings page to use new formbuilder
> Update formbuilder in proceedings types forms

- app/views/providers/application_confirmations/show.html.erb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2004)
Remove back link from page that is displayed after a provider and clicked the button to send the applicant an email with a link to complete the appplication.
Previously, clicking the back link would have redisplayed the "Give your client temporary access to the system page" enabling the provider to send another email, which would have been confusing.
Clicking the back link again would have caused a transition error because the case is already in "awaiting applicant" state.
> AP-2004 Remove back link from Application Created page

- config/initializers/sentry.rb
This is because it is being used by the email monitor and caused a addressee can't be blank error in sentry
> BugFix - Revert the data scrubbing for sentry config

- app/views/shared/partials/_revealing_checkbox.html.erb
- config/locales/cy/shared.yml
- config/locales/en/shared.yml
[AP-2067](https://dsdmoj.atlassian.net/browse/AP-2067) & [AP-2071](https://dsdmoj.atlassian.net/browse/AP-2071)
Minor content changes on /citizens/cash_income and /citizens/cash_outgoings
- amend label on maintence and legal aid checkboxes
- fix bug preventing hints being displayed on checkboxes
- refactor hint functionality on `_revealing_checkbox` partial to allow different hints to be displayed for income and outgoings
> AP-2067/2071 Content changes on cash_income and cash_outgoings screen

- config/initializers/sentry.rb
This stops any pii leaking into sentry as the logs are shown in the breadcrumbs.
Reimplement sidekiq before_send sanitisation of arguments to stop PII in sentry.
> BugFix Remove active support and sidekiq logger from sentry

- config/ccms/means_entity_configs/non_passported.yml
[AP-2063](https://dsdmoj.atlassian.net/browse/AP-2063)
Duplicate entity ids are happening due to the fact the OTHERSAVING attribute is using the wrong instance label. By correcting it to what we have in our example xml payload this should avoid duplicates and fix this issue.
> Ap 2063 duplicate entity id

- features/support/steps_helper.rb
Feature tests are failing because they expect the delegated function used on date to have a leading zero. This date is not displayed with a leading zero in the app. We've only just reached a date when this becomes a problems, so this hasn't been an issue up until now.
Thi fixes the expected date format to strip the zero.
> Fix delegated functions date format in cucumber

- app/views/providers/income_summary/index.html.erb
- app/views/providers/outgoings_summary/index.html.erb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2073)
Add spacing above button of padding size 6
> AP-2073 Fix spacing issue on income and outgoings summary pages

- app/controllers/admin/settings_controller.rb
- app/controllers/providers/check_client_details_controller.rb
- app/controllers/providers/evidence_of_benefits_controller.rb
- app/controllers/providers/received_benefit_confirmations_controller.rb
- app/forms/settings/setting_form.rb
- app/models/dwp_override.rb
- app/models/setting.rb
- app/views/admin/settings/show.html.erb
- app/views/providers/check_client_details/show.html.erb
- app/views/providers/evidence_of_benefits/show.html.erb
- app/views/providers/received_benefit_confirmations/show.html.erb
- config/locales/en/admin.yml
- config/locales/en/helpers.yml
- config/routes.rb
- db/migrate/20210305123318_add_dwp_override_flag_to_settings.rb
- db/migrate/20210305145638_create_dwp_overrides.rb
- db/schema.rb
- lib/tasks/setup_db_for_testing.rake
- spec/models/setting_spec.rb
- spec/requests/admin/settings_spec.rb
- spec/requests/providers/check_client_details_spec.rb
- spec/requests/providers/evidence_of_benefits_spec.rb
- spec/requests/providers/received_benefit_confirmations_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2089)
- Add DWP override feature flag
- Add DWPOverride model and database table
- Add routes, controllers and views for three new pages: `check_client_details`, `received_benefit_confirmation` and `evidence_of_benefit`. None of these pages are currently wired into any flows.
NB: `received_benefit_confirmation` is different to the `confirm_benefit_received` requested on the ticket, as it leads to a controller called `ConfirmBenefitReceivedsController` which is really ugly. Happy to rename it if required.
> AP 2089 - DWP override prep

- Gemfile
- app/controllers/providers/confirm_dwp_non_passported_applications_controller.rb
- app/services/flow/flows/provider_dwp_override.rb
- app/services/flow/flows/provider_start.rb
- app/services/flow/key_point.rb
- app/services/flow/provider_flow_service.rb
- app/views/providers/confirm_dwp_non_passported_applications/show.html.erb
- config/routes.rb
- spec/requests/providers/check_provider_answers_spec.rb
- spec/requests/providers/confirm_dwp_non_passported_applications_spec.rb
Add a new flow for the DWP override which jumps to blue box page and continues back to the check_benefits page.
> Add new DWP Override flow to service

- app/views/shared/forms/_types_of_outgoings_form.html.erb
- config/locales/en/shared.yml
- features/support/steps_helper.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2068)
Update content
1. Update ‘rent or mortgage’ hint text to read:
For example, rent, mortgage or board and lodging.
2. Update ‘childcare costs’ hint text to read:
For example, to a childminder, nanny or nursery.
3. Update ‘maintenance payments' hint text to read:
This includes child maintenance.
> AP-2068 Update hint text on Identify Types of Outgoing page

- app/models/cfe/v1/result.rb
- app/models/cfe/v2/result.rb
Raised in response to https://sentry.io/organizations/ministryofjustice/issues/2265136023/?project=5416053
[AP-2035](https://github.com/ministryofjustice/laa-apply-for-legal-aid/pull/2339) removed v1 and v2 of the CFE Result model. This can cause issues as the `cfe_results` table uses single table inheritance. When a record that uses `CFE::V1::Result` or `CFE::V2::Result` is read or updated it will throw an error if the model is not present.
There is minimal risk of this happening but there are a handful of applications in production that have v2 results but have not been submitted yet. If the provider submits them then an error may occur. It seems safer to retain the old models. 
This adds them back in with comments to not delete them in future.
> Bugfix: Re-add old CFE Result models

- app/services/govuk_emails/delivery_man.rb
- spec/services/govuk_emails/delivery_man_spec.rb
Related to this sentry issue has been discarded because it can reoccur in staging and we're okay with that. Under Sentry staging, settings, inbound filters, discarded >
When the DeliveryMan calls `deliver_now!` on a mailer job but that mailer raises an error then we should capture the issue and send the exception to Sentry.
This will mean that the ScheduledMailingsDeliveryJob can continue to call the DeliveryMan for 'waiting' jobs / scheduled mailings.
Update tests
> BugFix - Capture exceptions in DeliveryMan when mailers raise an error

- app/controllers/providers/check_benefits_controller.rb
- app/controllers/providers/confirm_dwp_non_passported_applications_controller.rb
- app/services/flow/flows/provider_dwp_override.rb
- app/services/flow/flows/provider_start.rb
- app/views/providers/confirm_dwp_non_passported_applications/show.html.erb
- app/webpack/stylesheets/interruption-panel.scss
- config/locales/en/providers.yml
- features/providers/civil_application_journey.feature
- features/step_definitions/civil_journey_steps.rb
- spec/requests/providers/check_benefits_spec.rb
- spec/requests/providers/check_provider_answers_spec.rb
- spec/requests/providers/confirm_dwp_non_passported_applications_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2082)
Solicitors need to be able to override a DWP benefit check result. This commit adds an alternative results page so that after a negative result the solicitor is given the option of overriding it. For now this simply leads to a holding page.
> AP-2082 DWP Override Blue Box

- .rubocop.yml
- app/models/assigned_df_scope_limitation.rb
- app/models/assigned_substantive_scope_limitation.rb
- lib/tasks/helpers/scope_limitations_migrator.rb
- lib/tasks/scope_limitations_migrator.rake
- spec/lib/migration_helpers/scope_limitations_migrator_spec.rb
- spec/requests/admin/settings_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2046)
This PR contains a migration script to convert the old application_scope_limitation records into application_proceeding_types_scope_limitation records.  This is non-destructive (i.e. it doesn't delete the original records) and does not install any code which relies on the new records.  It will allow us to ensure that the migration has gone smoothly on the live database before deploying any code which relies on it.  It is also idempotent, so can be run multiple times with no adverse effects.
> AP-2046Z Application/Scope Limitation migration scripts

- app/controllers/providers/check_provider_answers_controller.rb
- app/controllers/providers/confirm_dwp_non_passported_applications_controller.rb
- app/controllers/providers/received_benefit_confirmations_controller.rb
- app/forms/providers/received_benefit_confirmation_form.rb
- app/models/dwp_override.rb
- app/models/legal_aid_application.rb
- app/services/flow/flows/provider_dwp_override.rb
- app/views/providers/received_benefit_confirmations/show.html.erb
- app/views/shared/forms/received_benefit_confirmation/_form.html.erb
- config/locales/en/activemodel.yml
- config/locales/en/providers.yml
- config/locales/en/shared.yml
- config/routes.rb
- features/providers/civil_application_journey.feature
- spec/requests/providers/check_client_details_spec.rb
- spec/requests/providers/check_provider_answers_spec.rb
- spec/requests/providers/confirm_dwp_non_passported_applications_spec.rb
- spec/requests/providers/received_benefit_confirmations_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2084)
Page to confirm which benefit is received if client details are correct. 
Provider can only select 1 option.
If the provider selects one of the 5 state benefit options it should continue to new page AP-2085.
Provider receives an error if no option is selected and tries to continue with the journey. 
If the provider selects ‘None of the above’ continue to normal non-passported journey.
> AP 2084 DWP Confirm Benefits Received

- db/migrate/20210226133024_add_type_to_application_proceeding_types_scope_limitations.rb
- db/migrate/20210309195130_add_unique_idex_to_application_proceeding_types_scope_limitations.rb
- db/migrate/20210315164353_add_type_to_unique_index.rb
- db/schema.rb
Running the AP-2046Z migration failed on UAT master because of a unique index violation.  This is because the substantive and delegated functions scope limitations for some proceeding types are the same, meaning that when you add delegated functions it tries to add an `AssignedDfScopeLimtiation` record with the same `application_proceeding_type_id` and `scope_limtiation_id` as an existing `AssignedSubstantiveScopeLimitation` record.  Making the index unique on `type`, `application_proceeding_type_id` and `scope_limitation_id` gives us what we need.
> Ap 2046y include type in unique index

- app/mailers/submit_application_reminder_mailer.rb
- app/models/concerns/base_state_machine.rb
- spec/requests/admin/settings_spec.rb
- Fix AASM::InvalidTransition error for https://sentry.io/organizations/ministryofjustice/issues/2274131373/?project=5416054&referrer=slack . This allows used delegated functions to be changed and the provider to continue with the application.
- Also, fix submit application reminder mailer issue when there is no used delegated functions. https://sentry.io/organizations/ministryofjustice/issues/2267314506/?project=5416053&referrer=slack
- Fix failing Admin Settings test
> BugFix application reminder no delegated functions & transition error

- app/controllers/providers/proceedings_types_controller.rb
- app/controllers/v1/proceeding_types_controller.rb
- app/services/proceeding_type_full_text_search.rb
- app/views/providers/proceedings_types/index.html.erb
- app/webpack/src/modules/proceedings.js
- features/providers/civil_application_journey.feature
- features/support/steps_helper.rb
- spec/javascript/modules/proceedings.spec.js
- spec/requests/proceeding_types/index_proceeding_types_spec.rb
- spec/services/proceeding_type_full_text_search_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2056)
In order to prevent a provider selecting the same proceeding type twice for an application, proceeding types already selected are removed from the proceeding type search results..
This is achieved by the javascript passing in the current page URL to the `V1::ProceedingTypesController` which in turn allows the `ProceedingTypeFullTextSearch` service to access the `LegalAidApplication` to get a list of `ProceedingTypes` that have already been added to the application and remove them from the search results.
This PR also re-enables Full Text searching, tweaked to allow search by partial words, and returns results ordered by relevance.  This can be changed to order them alphabetically if required.
Before you ask people to review this …
> AP-2056 Remove selected proceeding types from search list

- app/controllers/providers/means_reports_controller.rb
- app/models/cfe/base_result.rb
- app/models/legal_aid_application.rb
- app/services/ccms/attribute_value_generator.rb
- app/services/ccms/manual_review_determiner.rb
- app/services/reports/means_report_creator.rb
- app/views/providers/means_reports/_caseworker_review.html.erb
- app/views/providers/means_reports/show.html.erb
- config/locales/en/providers.yml
- db/migrate/20210309111908_add_unique_index_to_dwp_overrides.rb
- db/schema.rb
- spec/factories/dwp_overrides.rb
- spec/models/cfe/v3/result_spec.rb
- spec/models/legal_aid_application_spec.rb
- spec/services/ccms/manual_review_determiner_spec.rb
- spec/services/ccms/requestors/case_add_requestor_xml_blocks/passported_attributes_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2087)
- Put the decision making for caseworker review in one place, `ManualReviewDeterminer` to be used both by Means Report Generator and CCMS payload 
- Update `ManualReviewDeterminer` to add in `:dwp_override` review reason if DWP result overridden
- Update `#applicant_receives_benefits?`, `#passported?` and `#non_passported?` to take DWP override into account
- Ensure only one DWPOverride record per 'LegalAidApplication`
> AP-2087 Require Caseworker review if DWP result has been overridden

- app/controllers/admin/reports_controller.rb
- app/controllers/application_controller.rb
- app/controllers/providers/provider_base_controller.rb
- app/services/reports/reports_types_creator.rb
- app/views/admin/reports/index.html.erb
- config/locales/en/activemodel.yml
- config/locales/en/admin.yml
- config/routes.rb
- spec/factories/ccms_submission_histories.rb
- spec/factories/ccms_submissions.rb
- spec/factories/legal_aid_applications.rb
- spec/requests/admin/reports_spec.rb
- spec/services/reports/reports_types_creator_spec.rb
- spec/services/true_layer/bank_data_import_service_spec.rb
Using L&D time to generate a CCMS report with xml payload details based on options in the Admin reports UI.
Feel free to pull this down and test, though tricky without real submissions to CCMS.
In this PR I've extended factories to accommodate successfully submitted cases to CCMS in the CCMS Submission and CCMS Submission History tables. With that, I've then got a custom report generator that uses a UI to capture what a user would like to find in terms of Apply/CCMS cases, whether they are passported or not, date ranges, capital assessment result and also to extract XML attribute values into a CSV file.
> Ccms report generator

- db/anonymise/rules.rb
The provider usernames were repeating and causing an
issue with the unique index on the provider table
Adding a 3 digit random suffix to the name should prevent this
A long term alternatice may be to change email to a sequence
e.g. username: test1, email: test1@example.com
username: test2, email: test1@example.com, etc
> Tech-debt: Update anonymise rules

- app/models/legal_aid_application.rb
- app/models/proceeding_merits_task/attempts_to_settle.rb
- db/anonymise/rules.rb
- db/migrate/20210319110509_create_attempts_to_settle.rb
- db/schema.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2138)
Adds the `ProceedingMeritsTask::AttemptsToSettle` model and database table. The table contains only a text field and a foreign key to the `legal_aid_applications` table.
> AP-2138 Add AttemptsToSettle model

- app/controllers/providers/bank_transactions_controller.rb
- spec/requests/providers/bank_transactions_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2150)
Previously, when a bank transaction was removed from an income or outgoings category on the income summary page, it merely set the `transaction_type_id` field to nil, thereby removing the link with that transaction type.  however, it left the `meta_data` field intact which meant that the transaction could not be shown when assigned to another category.  This PR fixes that.
> AP-2150 Bugfix remove bank transaction on income summary page

- app/controllers/saml_idp_controller.rb
Previously it looked at the values in mock_saml.rb
Which was fine as that was how we seeded the database
Now we can restore an anonymised DB from a remote service
the canonical email addresses will be in the DB.
This change leaves the values in mock_saml for seeding UAT
and local databases but now looks for email addresses in
the Providers table while still using the default mock_saml
password
> Tech-debt: Update fake saml logon

- app/views/shared/forms/_types_of_income_form.html.erb
- config/locales/cy/shared.yml
- config/locales/en/shared.yml
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2066)
- Update the content for **provider and citizen** side of identify types of income except the hint for friends_or_family which is only changed for the citizen side
> AP-2066 Update content for identify types of income page

- app/views/providers/confirm_dwp_non_passported_applications/show.html.erb
- app/webpack/stylesheets/alternative-error-style.scss
- app/webpack/stylesheets/application.scss
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2104)
Remove existing error styling (summary at top of page)
Add error message in white below the field and make it link to the first radio button.
Add styling to add error bar to left hand side and make it white
> AP 2104 dwp error styling

- package.json
- yarn.lock
Update two security warnings from dependabot
* ssri addresses CVE-2021-27290
* is-svg addresses CVE-2021-28092
> Security: yarn update

- Gemfile.lock
- scripts/migration_hook.rb
The `migration_hook` script used by the 'Check anonymise rules' GitHub action does not identify cases where a table has been renamed. It only alerts if there is a difference in the number of tables between the rules file and the schema.
This change amends the script to identify any difference in table names by finding the difference between the two arrays and failing with an appropriate message.
> Identify renamed tables in migration_hook

- features/step_definitions/civil_journey_steps.rb
The setup for the test chose a random proceeding_type
Now we remove the current proceeding type from the
search results this would occasionally fail
> Fix: Flickering search feature

- Gemfile
- Gemfile.lock
- app/forms/statement_of_cases/statement_of_case_form.rb
After the issues with MimeMagic, the Rails core team moved to an updated version of Marcel that changed it's mime data source and removed any reference to mimemagic
We used a specific call to mime magic to determine the Statement of Case upload, so I have replaced that with a call to the equivalent Marcel call and then removed the mimemagic gem entirely
> Tech debt:remove mimemagic

- config/environments/development.rb
The silence method is used on the activesupport logger not the default rails logger.
This caused an issue locally around truelayer bank import data worker
> BugFix Local Dev environment logger issue when using silence method

- app/models/base_aggregated_cash_transaction.rb
- app/webpack/src/modules/proceedings.js
- spec/models/aggregated_cash_income_spec.rb
- spec/models/aggregated_cash_outgoings_spec.rb
- spec/requests/citizens/cash_incomes_spec.rb
- spec/requests/citizens/cash_outgoings_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2111)
CFE expects the cash payment dates to be the three months prior to the calculation date, which is either today or the delegated functions date if that has been used.
This PR changes the AggregatedCashIncome model to use the calculation date, rather than today's date.
> AP-2111 Use transaction_period as basis for cash payment months

- app/controllers/providers/has_other_proceedings_controller.rb
- app/models/application_proceeding_type.rb
- app/models/legal_aid_application.rb
- app/services/ccms/requestors/case_add_requestor.rb
- db/migrate/20210324140533_add_lead_type_to_application_proc_types.rb
- db/schema.rb
- features/step_definitions/civil_journey_steps.rb
- lib/tasks/set_lead_proceeding.rake
- spec/models/application_proceeding_type_spec.rb
- spec/requests/providers/check_passported_answers_spec.rb
- spec/requests/providers/has_other_proceedings_controller_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1960)
Add a method to check if a proceeding type is the first to be assigned to an application, if it is, a new attribute lead_proceeding, is set to TRUE. All subsequent proceedings on the same application have this value set as FALSE.
Why? Apply does not actually care about a lead proceeding, it is a CCMS requirement. As such the first proceeding added is as good as any. However when we make subsequent proceeding types dependant on the first one then the first proceeding entered becomes important to Apply so the assigning it as lead_proceeeding seems like the best choice.
The ticket specifies it should be a domestic abuse type, but as all our proceedings are Domestic Abuse there is no need to do extra work to determine this is the …
> Ap 1960 specify a lead proceeding

- lib/tasks/set_lead_proceeding.rake
This rake task was part of ap-1960 to set lead_proceeding for an application.
The rake task has been run to set all existing `application_proceeding_type.lead_proceeding` to TRUE
The rake task is no longer required.
> rake task has been run so remove it

- app/models/concerns/translatable_model_attribute.rb
- app/views/providers/confirm_dwp_non_passported_applications/show.html.erb
- spec/factories/legal_framework_serialized_merits_task_list.rb
* Prefix final args with ** on TranslatableModelAttribute and the legal_framework_merits_task_list factory
* Update the confirm_dwp_non_passported_applications.show view to better handle the error message text
> Bug-fix: Remove noise from rspec output

- helm_deploy/apply-for-legal-aid/templates/ingress.yaml
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2258)
- Add modescurity rule to our ingress.
We have ingress configured in our config files and not in cloud platform.
> AP-2258 Add modsecurity to our ingress

- app/models/application_proceeding_type.rb
- app/models/legal_aid_application.rb
- db/migrate/20210408162032_add_delegated_functions_date_to_application_proceeding_types.rb
- db/schema.rb
- lib/tasks/move_delegated_functions_data.rake
- spec/models/application_proceeding_type_spec.rb
- spec/models/legal_aid_application_spec.rb
- spec/requests/providers/means_summaries_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2172)
- Add two columns to the application proceeding types table: **used_delegated_functions_on** and **used_delegated_functions_reported_on**
- Add a rake task to migrate used delegated functions values from the legal aid applications to the application proceeding types table
> AP-2172 Add used_delegated_functions columns and rake task

- lib/tasks/move_delegated_functions_data.rake
This fixes the broken rake task with no method pluck_id when it should be pluck(:id)
> BugFix Fix broken rake task to pluck id for applications

- spec/models/application_proceeding_type_spec.rb
Update the test to reduce the flickering, it was using an equality matcher
on an array.  Sometimes the objects are back to front and therefore not
equal.  Using match_array ensures that the two values are present
regardless of the sequence
> Bug-fix: update flickering test

- spec/requests/providers/application_merits_task/remove_involved_child_spec.rb
One of the new tests did not ensure the name was escaped
this adds the helper that ensures the name is checked
properly
> Bug-fix: Address flickering test

- Gemfile
- Gemfile.lock
The recent upgrade of REXML from 3.2.4 to 3.2.5 has affected our ability to login locally using mock saml.
Details:  The decoding of the saml signature gives the following error:
```
REXML::ParseException < RuntimeError
"Garbage component exists at the end: <]>: </p:Response[@ID=$id]/ds:Signature]>"
```
Have pinned the REXMl version to 3.2.4 in the Gemfile.
> Downgrade rexml

- lib/tasks/migrate_submitted_at.rake
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2227)
> Fix the rake task to migrate submitted_at attribute

- Gemfile
- Gemfile.lock
- lib/tasks/cucumber_steps.rake
`rake cucumber:steps`
gives the following output:
```
CUCUMBER steps:
+----------------------------------------------------------------------------------------------+------------------------------------------------------+
| stepname                                                                                     | location                                             |
+----------------------------------------------------------------------------------------------+------------------------------------------------------+
| the page is accessible                                                                       | features/step_definitions/accessibility.rb:1         |
| I am logged in as a provider                                                                 | …
```
> Rake task to list cucumber steps

- features/step_definitions/civil_journey_steps.rb
Update the creation of the application to ensure the searched for value is
_never_ the proceeding type used in the creation by the factory
Sometimes the ProceedingType.all.first would return the 'non-mol' proceeding type thus rendering the subsequent search invalid
The creation of the PT and SL were very old and seem to have been replaced by this trait so I'd thought I'd try it 🤷‍♂️ 
> bug-fix: Flicking feature

- app/views/providers/limitations/_proceeding_type.html.erb
- app/views/providers/limitations/show.html.erb
- app/views/shared/forms/_next_action_buttons.html.erb
- config/locales/en/providers.yml
- features/providers/civil_application_journey.feature
- spec/requests/providers/limitations_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2277)
Update 'What you're applying for' page to show scope limitations for each proceeding type as part of multiple proceedings. The updated version is currently hidden behind the multiple proceedings feature flag. When the flag is off, the existing page will display. 
> AP-2277 update scope limitations page

- app/services/reports/mis/application_detail_csv_line.rb
- app/services/reports/mis/non_passported_application_csv_line.rb
- spec/requests/admin/reports_spec.rb
- spec/services/reports/mis/application_detail_csv_line_spec.rb
- spec/services/reports/mis/non_passported_application_csv_line_spec.rb
- spec/services/reports/mis/non_passported_applications_report_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2249)
Change the way we report passported/non-passported cases on the admin report
Add in the dwp_override column and result
Remove the Apply application_ref
> Ap 2249 update the admin reports

- app/controllers/providers/limitations_controller.rb
This is just in prepareation for the switch to multiple proceedings - we need all new applications to start recording their DF dates on the application proceeding type record AS WELL AS the legal aid application, so that the DF dates refactoring in AP-2234 will work. 
There is already a rake task to copy over the data for older applications.
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2289)
> AP-2289 duplicate DF dates on application_proceeding_type

- app/controllers/providers/has_other_proceedings_controller.rb
- app/views/providers/proceedings_types/index.html.erb
- app/views/shared/forms/proceedings_types/_proceeding_type_form.html.erb
- app/webpack/stylesheets/providers/legal_aid_applications.scss
- config/locales/en/providers.yml
- spec/requests/providers/has_other_proceedings_controller_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2278)
Updated proceedings index (search) page to display hint text
Improved styling of proceeding item results on search page
Updated has_other_proceedings page to display an error and prevent the user from continuing if they have not selected a domestic abuse proceeding
Added rspec tests
> AP-2278 select at least one domestic abuse proceeding

- spec/forms/legal_aid_applications/used_multiple_delegated_functions_form_spec.rb
- spec/requests/providers/proceeding_merits_task/involved_children_spec.rb
* Ensure the InvolvedChildrenController name is escaped with by the html_compare method
* added additional debugging tests to the used_multiple_delegated_functions_form_spec if the new ones pass and the original ones fail then we can delete the original ones, or delete the new ones if they are impractical 🤷‍♂️ 
Since adding the debug step I cannot make the test flicker, so I've left it in place to see if it will fail longer term
> Tech-debt/Flickering tests

- app/controllers/providers/confirm_multiple_delegated_functions_controller.rb
- app/controllers/providers/used_multiple_delegated_functions_controller.rb
- app/models/concerns/binary_choice_form.rb
- app/services/flow/flows/provider_start.rb
- app/views/providers/confirm_multiple_delegated_functions/show.html.erb
- config/locales/en/providers.yml
- config/routes.rb
- features/providers/civil_application_journey.feature
- spec/factories/legal_aid_applications.rb
- spec/requests/providers/confirm_multiple_delegated_functions_dates_spec.rb
- spec/requests/providers/used_multiple_delegated_functions_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2233)
In the multi proc flow, this page only exists if the provider enters a DF over 1 month old. Page displays the date if over 1 month. If there are multiple dates, the radio buttons + error message for blank both pluralise.
> Ap 2233 check delegated functions page

- bin/df_dates_updater.rb
In the migration to use delegated function dates on the `application_proceeding_type`, the rake task to copy the dates from the `legal_aid_application` to the `application_proceeding_type` was not run before deleting those columns from the legal_aid_applications table (it had been run earlier, but application had been created since then).
This script finds all the application proceeding types without delegated function dates, and checks the legal aid application record to see if there is a value in the `substantive_application_deadline_on` (which means delegated functions have been used).  If there is, it updates the application proceeding type with a date 20 working days before the deadline, and uses the reminder mail's created_at date as the DF reporting date.
Before you ask people to …
> Repair Delegated Function dates

- app/views/providers/application_merits_task/has_other_involved_children/show.html.erb
- app/views/providers/has_other_dependants/show.html.erb
- app/views/providers/has_other_proceedings/show.html.erb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2146)
Made the first heading h1 and size xl, and the second heading h2 and size l - this is to have a consistent heading hierarchy and page flow
> Ap-2146 update heading sizes and hierarchy on 'add another' pages

- app/controllers/providers/has_other_proceedings_controller.rb
- app/controllers/providers/in_scope_of_laspos_controller.rb
- app/forms/legal_aid_applications/in_scope_of_laspo_form.rb
- app/models/legal_aid_application.rb
- app/services/flow/flows/provider_start.rb
- app/views/providers/check_provider_answers/_shared.html.erb
- app/views/providers/in_scope_of_laspos/show.html.erb
- app/views/providers/used_multiple_delegated_functions/show.html.erb
- app/views/shared/check_answers/_delegated_functions.html.erb
- app/views/shared/check_answers/_proceedings_details.html.erb
- config/locales/en/activemodel.yml
- config/locales/en/providers.yml
- config/locales/en/shared.yml
- config/routes.rb
- db/migrate/20210518095337_add_in_scope_of_laspo.rb
- db/schema.rb
- features/providers/civil_application_journey.feature
- spec/factories/proceeding_types.rb
- spec/requests/providers/has_other_proceedings_controller_spec.rb
- spec/requests/providers/in_scope_of_laspos_controller_spec.rb
- spec/requests/providers/proceedings_types_spec.rb
Added controller, view and rspec tests for the LASPO page
Added new column to legal_aid_application to record response
Updated the flow so this page is only triggered if Section 8 proceedings have been selected
Updated the CYA page and merits report to show the response to the LASPO question (only displays if the application has S8 proceedings)
> AP-2241 LASPO page

- config/locales/en/shared.yml
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2153)
Add hint text to tell providers to include accounts with no money in them
> AP-2153 add hint text to offline account checkbox

- app/controllers/providers/used_delegated_functions_controller.rb
- app/forms/legal_aid_applications/confirm_delegated_functions_date_form.rb
- app/forms/legal_aid_applications/used_multiple_delegated_functions_form.rb
- spec/forms/legal_aid_applications/confirm_delegated_functions_date_form_spec.rb
- spec/forms/legal_aid_applications/used_multiple_delegated_functions_form_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2204)
removed commented out code that was no longer needed
revised a test that was checking something incorrectly
Set reported_on_date value in the form instead of calling a method on the model
Updated multiple DF form to no longer leave the value nil if the date is over a month ago
> AP-2204 fix bug where df date_reported_on was not being stored for cases where df date was over a month old

- app/models/concerns/base_state_machine.rb
- app/models/legal_aid_application.rb
- spec/mailers/feedback_mailer_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2267)
Update the base state machine to define the states that occur before the dwp check.
Update the LegalAidApplication model to use the above states to check if a legal aid application is in the pre_dwp_check state.
Test the above.
> AP-2267 BugFix - Update predwp check to be more accurate

- db/migrate/20210602110352_remove_legal_aid_application_association_from_chances_of_success.rb
- db/migrate/20210602114709_remove_submitted_at_from_chances_of_success.rb
- db/schema.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2276)
- Add migration to remove the legal aid application reference/association with chances of success because it is now associated through the application proceeding type
- Add migration to remove submitted_at from chances of success because it is now under the legal aid application under the name 'merits_submitted_at'
**Tested with:**
Production anonymised data
Rails console and checking if the data has properly been migrated previously from this  PR https://github.com/ministryofjustice/laa-apply-for-legal-aid/pull/2492
> AP-2276 Add migration to remove two columns from ChancesOfSuccess

- config/ccms/attribute_block_configs/base.yml
- config/ccms/attribute_block_configs/non_passported.yml
- spec/data/ccms/case_add_request.xml
- spec/services/ccms/requestors/case_add_requestor_xml_blocks/non_passported_variable_attributes_spec.rb
- spec/services/ccms/requestors/case_add_requestor_xml_blocks/passported_attributes_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2330)
- Added block to `config/ccms/attribute_block_configs/non_passported.yml` to generate value
- Added test to ensure it was generated for non-passported applications
- Added test to ensure it was omitted for passported applications
> AP-2330 Add PASSPORTED_NINO attribute to passported payloads

- config/ccms/attribute_block_configs/base.yml
- config/ccms/attribute_block_configs/non_passported.yml
- spec/data/ccms/case_add_request.xml
- spec/services/ccms/requestors/case_add_requestor_xml_blocks/non_passported_attributes_spec.rb
- spec/services/ccms/requestors/case_add_requestor_xml_blocks/passported_attributes_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2328)
- Add attribute GB_INFER_T_6WP1_66A to the ccms payload for passported and omit for non-passported applications
- Test the above
Co-authored-by: willc-work
> AP-2328 Add new ccms attribute to check passported or not

- app/services/ccms/requestors/document_id_requestor.rb
- app/services/ccms/requestors/document_upload_requestor.rb
- app/services/ccms/submitters/obtain_document_id_service.rb
- spec/services/ccms/requestors/document_upload_requestor_spec.rb
- spec/services/ccms/submitters/obtain_document_id_service_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2344)
- Add gateway evidence document attachments to the ccms document upload process
- Test the above.
We thoroughly test with a statement of case attachment. Do you think these tests should be duplicated for gateway evidence? The document upload process focuses on documents attached to the application and not what type specifically.
> AP-2344 Include gateway evidence documents to ccms upload

- app/controllers/providers/proceeding_merits_task/chances_of_success_controller.rb
- spec/requests/providers/proceeding_merits_task/chances_of_success_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2349)
Don't update the merits task list status of chances of success to complete if the success_likely is false.
Co-authored: colinbruce 
> AP-2349 Add extra logic around task completion for chances of success

- app/models/dependant.rb
- app/services/ccms/attribute_value_generator.rb
- app/services/ccms/requestors/case_add_requestor.rb
- app/services/ccms/requestors/non_passported_case_add_requestor.rb
- config/ccms/attribute_block_configs/non_passported.yml
- config/ccms/means_entity_configs/non_passported.yml
- spec/factories/dependants.rb
- spec/factories/legal_aid_applications.rb
- spec/services/ccms/requestors/case_add_requestor_xml_blocks/non_passported_dependant_child_attributes_spec.rb
- spec/support/xml_extractor.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2331)
- Added code to generate the `CLIENT_RESIDING_PERSON` entity if there are any dependant children
- Added code to generate and test the following attributes for *each* child dependant within that entity for non-passported applications
- `CLI_RES_PER_INPUT_B_12WP3_20A`
- `CLI_RES_PER_INPUT_B_12WP3_21A`
- `CLI_RES_PER_INPUT_B_12WP3_23A`
- `CLI_RES_PER_INPUT_B_12WP3_24A`
> AP-2331 Non-passported dependant child attributes in CCMS payload

- app/services/dashboard_event_handler.rb
- spec/services/dashboard_event_handler_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2359)
Previously we would update geckoboard after each step of the CCMS `dance`
That could mean 20-30 calls in a few seconds and would occasionally trip
the geckoboard rate limits
This PR attempts to reduce that noise bu sending a ccms_submission_saved job
when a CCMS submission is initialised and then updating again when it concludes
either completed or failed.  It also updates the Applications call to send
whether the job completes successfully or not.  This should clear the
CCMS error widget when manually pushing a CCMS job though
> AP-2359: Reduce Dashboard::UpdaterJob calls to geckoboard

- app/models/legal_aid_application.rb
- spec/factories/dwp_overrides.rb
- spec/models/legal_aid_application_spec.rb
- spec/requests/providers/substantive_applications_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2372)
Extended the substantive_applications_spec tests to ensure the correct routing when a provider overrides the DWP result
but does not have evidence of the benefit received
Updated the applicant_receives_benefit method of LegalAidApplication to only return true if the provider has selected yes to having evidence of the benefit
> AP-2372: BugFix for DF and DWP override routing issue

- app/forms/applicants/basic_details_form.rb
- app/forms/base_form.rb
- app/forms/legal_aid_applications/dependant_form.rb
- app/forms/opponents/opponent_form.rb
- app/forms/providers/application_merits_task/involved_child_form.rb
- lib/tasks/clean_whitespaces.rake
- spec/requests/providers/applicant_details_spec.rb
- spec/requests/providers/application_merits_task/involved_children_spec.rb
- spec/requests/providers/application_merits_task/opponents_spec.rb
- spec/requests/providers/dependants_controller_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2360)
1. Squish/Remove trailing and duplicate whitespaces from attributes relating to Dependant, Applicant, InolvedChild and Opponent
2. Test the above
> AP-2360 Remove trailing whitespaces for Applicant and Dependant

- lib/tasks/clean_whitespaces.rake
Don't squish whitespaces when nil attributes. In particular the Applicant, which can exist at bare minimum with no details.
> Fix Rake Job for cleaning whitespaces 

- app/controllers/admin/reports_controller.rb
Create an admin report synchronously on initial admin report setup, when there is no admin report at all. This creates them before the cronjob which executes at 8pm.
> BugFix - Create admin report when none exists

- spec/requests/providers/used_multiple_delegated_functions_spec.rb
- Seperate out a test block for multiple used delegated functions as this is a flickering test.
- This will enable us to narrow down the cause of the flickering test if it happens again.
- An assumption could be the application proceeding types are returning in different order because of the factory. Another assumption is that it's to do with timezones. Just an assumption.
> BugFix Separate flickering test for multiple used delegated functions

- spec/services/legal_framework/proceeding_types_service_spec.rb
Fix a test that occasionally fails when the proceedings are in a different order
> Bugfix: test that falls over if proc types in wrong order

- spec/requests/providers/applicant_bank_accounts_spec.rb
There are some issues with BigDecimal, see their issues page and
this seems to be a new occurence.  An issue has been raised on
their repo https://github.com/ruby/bigdecimal/issues/194 but
this seems to work on the previously flickering values
It forces the value into a big decimal while setting the
precision manually based on the string length of the
random value generated, minus the decimal place separator
> BugFix: Address flickering tests

- spec/requests/providers/used_multiple_delegated_functions_spec.rb
Ensure the application proceeding types are always sorted
in the order expected by the each_with_index blocks
The params are sent to the controller in the sequence a->b
but sometimes are created as b->a this caused the sequence
of date - i.days to be in the wrong order
This aims to make the tests idempotent
> BugFix: Flickering Multiple DF dates

- app/mailers/feedback_mailer.rb
- spec/mailers/feedback_mailer_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2366)
Return an empty string when no legal_aid_application can be loaded, rather than
defaulting to `non-passported`
> AP-2366: Update FeedbackMailer

- config/ccms/attribute_block_configs/non_passported.yml
- spec/services/ccms/requestors/case_add_requestor_xml_blocks/non_passported_attributes_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2324)
Add NonPassported CCMS attribute hardcoded to FALSE
> Ap-2334 add NP CCMS attribute

- config/routes.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2275)
There are various reasons for removing the obsolete routes:
1. Citizen journey no longer uses the page e.g. incoming transactions is now in provider
2. Excess routes left over by not setting only: [] on resources
> AP-2275 Remove obsolete routes in config/routes.rb

- app/services/pdf_converter.rb
- spec/services/pdf_converter_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2379)
**Error in sentry:**
```
ArgumentError Sidekiq/PdfConverterWorker
'statement_of_case_3_pdf' is not a valid attachment_type
```
If say a statement of case was uploaded 3 times then the attachment_name will increment to statement_of_case_3
which is fine. However, this multi-file upload triggers the error below:
The problem is in the PDFConvertor worker placing the wrong value in attachment_type for the Attachment model.
Attachment#attachment_type is an enum and e.g. 'statement_of_case_3' is not matching with 'statement_of_case_pdf' in the model.
- The solution is to get the type value from the #attachment_type method instead of the #attachment_name
**### This fixes the bug but does not fix existing failed PDFConvertor workers in …
> BugFix File uploads / Attachment creation errors for multiple attachments

- app/models/proceeding_type.rb
- config/ccms/attribute_block_configs/base.yml
- spec/data/ccms/case_add_request.xml
- spec/data/ccms/mp_case_add_request.xml
- spec/services/ccms/requestors/case_add_requestor_xml_blocks/passported_attributes_spec.rb
- spec/services/legal_framework/proceeding_types_service_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2923)
This attribute was previously omitted.  Now it is included for every proceeding type, coded to true if the proceeding. is a section 8 proceeding, otherwise false.
> AP-2329 Add CHILD_PARTIES_C attribute for each proceeding

- app/forms/providers/gateway_evidence_form.rb
- app/forms/statement_of_cases/statement_of_case_form.rb
- app/helpers/attachments_helper.rb
- app/views/providers/check_merits_answers/show.html.erb
- app/views/providers/gateway_evidences/show.html.erb
- app/views/providers/submitted_applications/show.html.erb
- app/views/shared/check_answers/_item.html.erb
- app/views/shared/check_answers/_merits.html.erb
- app/views/shared/check_answers/_merits_orig.html.erb
- app/views/shared/check_answers/_no_link_item.html.erb
- db/migrate/20210621100811_add_original_filename_to_attachments.rb
- db/schema.rb
- features/providers/civil_application_journey.feature
- features/providers/multi_proceedings.feature
- features/step_definitions/civil_journey_steps.rb
- spec/factories/gateway_evidences.rb
- spec/factories/legal_aid_applications.rb
- spec/factories/statement_of_cases.rb
- spec/helpers/attachments_helper_spec.rb
- spec/requests/providers/application_merits_task/statement_of_case_spec.rb
- spec/requests/providers/gateway_evidence_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2321)
- Add migration to create a new column original_filename for Attachment to store the files original names.
- Show the uploaded files names on the check answers page. This includes statement of case and gateway evidence.
- Create a helper to return file names concatenated with their file size. 
- Test this helper
**Also**:
```
Update html class '.govuk-summary-list--no-border' to class '.govuk-summary-list__row--no-border'
This is done for row by row basis. This is because it was not working when printing the check merits answers
page. The browser print page/popup would still show the border. Now with the __row--no-border it no longer shows as expected.
This is because the class was being added to a summary list row and thus …
```
> AP-2321 Show uploaded files names on check answers page

- app/helpers/attachments_helper.rb
- spec/helpers/attachments_helper_spec.rb
Some attachments in our current database do not have original_filename values in their Attachment records.
This caused a bug because the attachment helper used on the check merits answers page was expecting something.
Use the attachment_type as the default name for the file when no original_filename exists.
This should not be required going forward because all attachments will now have original_filenames attached.
Related ticket https://github.com/ministryofjustice/laa-apply-for-legal-aid/pull/2651
> BugFix Allow for existing attachments with no original filenames

- spec/requests/providers/applicant_bank_accounts_spec.rb
- spec/services/true_layer/bank_data_import_service_spec.rb
There was another flicker when the truelayer MOCK_DATA generated
a value of `823332.18`, the test found `823332.1800000001`
previous experience shows this would have been fine at
`823332.19`
This solution converts the float to a string and passes it to
BigDecimal.  Passing the float directly requires the precision
to be sent, which requires converting to a string!
I've backported this solution to a previous bugfix as it's easier
to read and means the code is more consistent
> BugFix: Address BigDecimal rounding issues

- app/controllers/providers/capital_assessment_results_controller.rb
- spec/requests/providers/capital_assessment_results_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2356)
As part of the MP work the task list was being created on arriving at the task list controller, this creates it after the capital assessment page.  
This means it will be created for all applications regardless of the MP flag state and allows applications in progress to route back to the task list seamlessly
Tasks completed while the flag is false are still marked as complete as the code to mark tasks as complete checks for the existence before flagging and is not behind the flag
> AP-2356: Always create task list

- app/views/citizens/banks/index.html.erb
- app/views/citizens/consents/show.html.erb
- features/accessibility/citizen.feature
- features/citizens/citizens.feature
- features/citizens/citizens_welsh.feature
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1742)
Update button text on a couple pages in citizens journey to match the rest of the non-passported journey
This is also in line with GDS guidelines regarding button text: https://design-system.service.gov.uk/components/button/ 
> Update button text

- spec/factories/legal_aid_applications.rb
Trying to debug a solution to the `Providers::ProceedingMeritsTask::ChancesOfSuccessController` flicker that seems to occur more on Circle than local.
The flicker indicated that something was wrong in the `chances_of_success` routing in `provider_merits.rb` and, because this was a true flicker rather than a race condition, it couldn't be replicated.
Therefore I decided to update the factory trait used for the legal_aid_application to ensure the provider_step_params was populated with a merits_task_list_id that would enable the correct routing.
This has been run ~8 times on Circle and not failed once.
> Tech debt/fix chance of success routing flicker

- config/ccms/attribute_block_configs/non_passported.yml
- spec/services/ccms/requestors/case_add_requestor_xml_blocks/non_passported_attributes_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2336)
Added a block that checks if childcare is being paid by the applicant and returns true if it is and false if it snot
> AP-2336 add childcare boolean attribute

- app/helpers/capital_helper.rb
- app/helpers/policy_disregards_helper.rb
- app/views/shared/check_answers/_assets.html.erb
- app/views/shared/check_answers/_dependants.html.erb
- app/views/shared/check_answers/_no_link_item.html.erb
- app/views/shared/check_answers/_one_link_section.html.erb
- config/locales/en/shared.yml
- features/providers/check_your_answers.feature
- features/providers/civil_application_journey.feature
- features/providers/complete_and_check_means_answers.feature
- features/step_definitions/civil_journey_steps.rb
- spec/helpers/policy_disregards_helper_spec.rb
- spec/requests/providers/check_passported_answers_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2298)
Updated capital helper methods to return a full list of items for savings and investments and other assets so that all labels can be displayed on the check your answers page, so that providers can check if they've missed something. 
Same for policy disregards.
Updated summary list styling on this page to make it consistent. 
Updated tests, added new feature test and step which checks the answers for all items of a CYA section e.g. savings and investments
> AP-2298 display all labels

- config/locales/en/errors.yml
- spec/requests/errors_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1953)
Update content on already shared financial info page in citizens journey 
i.e. page that shows when a client clicks on the link but they have already shared their financial info
> Update content on already shared financial info page

- config/ccms/attribute_block_configs/non_passported.yml
- spec/services/ccms/requestors/case_add_requestor_xml_blocks/non_passported_attributes_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2337)
add omitted CCMS attributes for non passported applications
> AP-2337 add omitted CCMS attrs for non passported

- app/views/providers/means_reports/show.html.erb
- app/views/providers/merits_reports/show.html.erb
- app/views/shared/check_answers/_merits.html.erb
- features/providers/multi_proceedings.feature
- features/step_definitions/civil_journey_steps.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2384)
Allow for missing gateway evidence in merits report because applications that were created without a gateway evidence may fail to generate a merits report.
> AP-2384 Allow for missing gateway evidence in merits report

- db/anonymise/rules.rb
The restore of the anonymised database dump of production is not working, and failing with this error:
`psql:./tmp/production.anon.sql:261403: ERROR:  missing data for column "ccms_opponent_id"`
`CONTEXT:  COPY opponents, line 1: "841cbaf4-0bdd-4bd1-bda3-934b36983fe5	9437bcfb-2e7a-4590-8e8f-9edf80a0fcd9`
The `ccms_opponent_id` column is all nil in the live database - that shouldn't be a problem, but when restoring it seems to expect a value.  This PR is to put in a fake number so that there is data there.
> Add DB anonymisation rule

- app/models/dependant.rb
- app/services/ccms/requestors/case_add_requestor.rb
- app/services/ccms/requestors/non_passported_case_add_requestor.rb
- config/ccms/attribute_block_configs/non_passported.yml
- config/ccms/means_entity_configs/non_passported.yml
- spec/models/dependant_spec.rb
- spec/services/ccms/requestors/case_add_requestor_xml_blocks/non_passported_dependant_child_attributes_spec.rb
[This ticket](https://dsdmoj.atlassian.net/browse/AP-2333)
and
[this ticket](https://dsdmoj.atlassian.net/browse/AP-2352)
Originally, these two tickets were to add single attributes relating to dependants to the payload.  However, these attributes were for adults, and the CLIENT_RESIDING_PERSON entity was only being added for child dependants.  It turns out that there needs to be an instance block for each dependant, with some attributes for adults only, some for children only and some for both.  This rectifiers that situation and should be the last of the dependant attribtues.
> AP-2333 Dependant attributes

- .circleci/config.yml
- helm_deploy/apply-for-legal-aid/templates/deployment_web.yaml
ClamAV has been causing some failures as our image is not up to date
Changes to our existing repo were not resulting in the newest image being tagged as latest
Change where we get the clamav docker image from - now using HMPPS one
> CHange the image used for CLAMAV use the hmpps image

- db/anonymise/rules.rb
> Remove newline from anonymised name

- app/services/ccms/ccms_error.rb
- app/services/ccms/submitters/add_applicant_service.rb
- app/services/ccms/submitters/add_case_service.rb
- app/services/ccms/submitters/base_submission_service.rb
- app/services/ccms/submitters/check_applicant_status_service.rb
- app/services/ccms/submitters/check_case_status_service.rb
- app/services/ccms/submitters/obtain_applicant_reference_service.rb
- app/services/ccms/submitters/obtain_case_reference_service.rb
- app/services/ccms/submitters/obtain_document_id_service.rb
- app/services/ccms/submitters/upload_documents_service.rb
- app/services/reports/base_report_creator.rb
- app/workers/ccms/submission_process_worker.rb
- config/initializers/sidekiq_middleware.rb
- spec/services/ccms/submitters/add_applicant_service_spec.rb
- spec/services/ccms/submitters/add_case_service_spec.rb
- spec/services/ccms/submitters/check_applicant_status_service_spec.rb
- spec/services/ccms/submitters/check_case_status_service_spec.rb
- spec/services/ccms/submitters/obtain_applicant_reference_service_spec.rb
- spec/services/ccms/submitters/obtain_case_reference_service_spec.rb
- spec/services/ccms/submitters/obtain_document_id_service_spec.rb
- spec/services/ccms/submitters/upload_documents_service_spec.rb
- spec/services/reports/bank_transactions/bank_transaction_report_creator_spec.rb
- spec/services/reports/means_report_creator_spec.rb
- spec/services/reports/merits_report_creator_spec.rb
- spec/workers/ccms/submission_process_worker_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2161)
- Check the retry count for a submission step, if it reached the max of 10 (4hrs-ish total) then it will do submission.fail! 
- Add a middleware to sidekiq to gather the retry count of a worker and to place it in an attribute reader for the ccms/submission_process_worker
Sidekiq error handling was being blocked with our code which fails the submission if an exception is raised.
Remove the submission.fail! from the ccms submission services and place it in the worker. 
This means that Sidekiq can continue with its error handling
https://github.com/mperham/sidekiq/wiki/Error-Handling
Also, re-raise exceptions after they're caught in the submission services so that sidekiq workers can handle it.
<details>
<summary>This table …
> AP-2161 CCMS submission retries

- .rubocop.yml
- spec/helpers/hash_format_helper_spec.rb
We had ignored the new `Layout/LineEndStringConcatenationIndentation` cop because of the number of false positives, these have been addressed in a subsequent update, so I've removed the override and fixed the remaining issue
> Tech debt/rubocop fix

- app/webpack/src/checkbox_control.js
Remove checkbox and hidden field from checkbox memory when previously selected checkbox is deselected
I also ran the standard.js linter on the file hence why there are so many changes, removal of semi-colons etc.
Line 56 is the relevant new line 
> AP-2358 fix checkbox deselect bug

- config/initializers/omniauth.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2306)
Update the OmniAuth initializer
Requiring a controller in an initializer reloads all helpers and
this was causing the deprecation warning.  Wrapping the requires in
the suggested `Rails.application.reloader.to_prepare do` block seems
to have quieted the warning when running server and console locally
Testing on UAT to ensure there are no issues with production
style execution
> AP-2306: Remove deprecation warnings

- app/controllers/citizens/cash_incomes_controller.rb
- app/controllers/citizens/cash_outgoings_controller.rb
- app/models/cash_transaction.rb
- app/views/citizens/cash_incomes/_cash_income_form.html.erb
- app/views/citizens/cash_outgoings/_cash_outgoings_form.html.erb
- app/views/shared/forms/_types_of_outgoings_form.html.erb
- db/migrate/20210712112003_add_no_cash_income_and_outgoings.rb
- db/schema.rb
- spec/requests/citizens/cash_incomes_spec.rb
- spec/requests/citizens/cash_outgoings_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2273)
Added attributes to LegalAidApplication to record when no cash income/outgoings have been selected
This is so we can display 'None of the above' as checked when a user returns to the page via the back button or from the CYA page
> AP-2273 cash transactions none of the above

- app/models/dashboard/single_object/applicant_email.rb
- app/models/dashboard/single_object/feedback.rb
- app/models/dashboard/single_object/provider_data.rb
- app/models/dashboard/widget.rb
- app/models/dashboard/widget_data_providers/applications.rb
- app/models/dashboard/widget_data_providers/number_provider_firms.rb
- app/models/dashboard/widget_data_providers/pending_ccms_submissions.rb
- app/models/dashboard/widget_data_providers/percentage_declined_open_banking.rb
Bug-Fix: Geckoboard …
Add double-splat to the dataset_definition calls, these
all the hashes in the methods to be flattened and passed
to the find_or_create method of the geckoboard datasets
class
Remove the `to_hash` from the Geckoboard fields, the
double_splat fix makes these superfluous
> Bug-fix: Geckoboard fix

- app/controllers/providers/confirm_dwp_non_passported_applications_controller.rb
- features/providers/pathways_from_check_your_answers.feature
- spec/requests/providers/confirm_dwp_non_passported_applications_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2398)
Remove check_benefits from page history, so that back button on DWP override page links to check_provider_answers page.
> Ap 2398 back link dwp override

- app/views/providers/confirm_dwp_non_passported_applications/show.html.erb
- config/locales/en/providers.yml
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2400)
Following govuk guidelines, put abbreviation (DWP) in brackets after first usage of full name
Add abbr tag to dwp page header but not tab header
> AP-2400 DWP abbreviation

- app/models/concerns/base_state_machine.rb
After allowing the pausing of submissions this prevented the state changing after a manual start of the job
> Fix: Allow transition from paused to assessment_submitted

- app/services/true_layer/importers/import_account_balance_service.rb
This forces the conversion of numbers into a 2 digit float and reduces the errors often seen on circle e.g.
```ruby
expected: ["311466.63", "87518.82"]
got: ["311466.63", "87518.82000000001"]
```
> Tech-Debt: Flickering numbers

- helm_deploy/apply-for-legal-aid/templates/cronjob-reset-dashboard-overnight.yaml
- lib/tasks/jobs/dashboard_updater.rake
This suddenly failed and seems to not be accepting arguments
This fix changes the method of calling the rake task and
works locally
> Fix: The overnight update job rake task

- app/helpers/tag_helper.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2433)
Stop text from wrapping in updated tags in applications table
> AP-2433 stop text in tag from wrapping

- app/controllers/providers/limitations_controller.rb
- app/views/providers/check_provider_answers/_shared.html.erb
- app/views/providers/limitations/_legacy_proceeding_types.html.erb
- app/views/shared/check_answers/_emergency_costs.html.erb
- app/views/shared/check_answers/_merits.html.erb
- app/views/shared/check_answers/_merits_orig.html.erb
- config/locales/en/shared.yml
- features/providers/civil_application_journey.feature
- spec/requests/providers/limitations_spec.rb
Remove the settings flag from the cost override feature so it is accessible to any user who use delegated functions
Update limitations/legacy_proceeding_types to show the new form and display errors correctly
Update check_provider_answers so the new section is shown if DF have been used and the chnage link works to allow users to change the information
Update merits page to show the new emergency cost override details only on merits reports and not on the merits_assessment page (it cannot be changed from here due to a state change)
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2367)
> Ap 2367 implement cost override

- app/models/legal_framework/merits_task_list.rb
- app/services/flow/flows/provider_capital.rb
- app/services/flow/flows/provider_merits.rb
- features/accessibility/provider.feature
- features/cassettes/Checking_ccms_means_does_NOT_auto_grant/I_am_able_to_create_a_passported_application_with_Cap_Contribs_3k_and_with_restrictions.yml
- features/cassettes/Checking_ccms_means_does_NOT_auto_grant/I_am_able_to_create_a_passported_application_without_Cap_Contribs_and_with_no_restrictions.yml
- features/cassettes/Civil_application_journeys/Completes_the_application_using_manual_address.yml
- features/cassettes/Civil_application_journeys/Completes_the_merits_application_for_applicant_that_does_not_receive_passported_benefits.yml
- features/cassettes/Civil_application_journeys/I_am_able_to_view_the_client_completed_means_answers.yml
- features/cassettes/Civil_application_journeys/I_can_see_that_the_applicant_receives_benefits.yml
- features/cassettes/Provider_accessibility/I_complete_the_non-passported_means_assessment_and_it_is_accessible.yml
- features/cassettes/Provider_accessibility/I_complete_the_non-passported_merits_assessment_and_it_is_accessible.yml
- features/providers/check_ccms_autogrant.feature
- features/providers/civil_application_journey.feature
- features/providers/merits_task_list.feature
- features/step_definitions/civil_journey_steps.rb
- spec/factories/legal_aid_applications.rb
- spec/models/legal_framework/merits_task_list_spec.rb
- spec/requests/providers/application_merits_task/has_other_involved_children_spec.rb
- spec/requests/providers/application_merits_task/statement_of_case_spec.rb
- spec/requests/providers/capital_assessment_results_spec.rb
- spec/requests/providers/capital_income_assessment_results_spec.rb
- spec/requests/providers/merits_task_lists_controller_spec.rb
- spec/requests/providers/proceeding_merits_task/chances_of_success_spec.rb
- spec/requests/providers/proceeding_merits_task/success_prospects_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2385)
remove MP flag setting from merits task list options.
Allows merits task list to be used before MP is released
Fix for the issues below:
When setting up the applications for the task list, it needs to be explicit about the proceeding type.
Previous issues were being caused by the factory bot assigning sequential numbers
```ruby
sequence(:ccms_code) { |n| format('DA%<number>03d', number: n) }
```
Meaning that when recorded individually it would return DA001, but when run as part of the suite it could be DA008, DA0009, etc and the cassette would then be 'wrong' and the tests would fail
<details>
<summary>Issues:</summary>
currently 3 feature tests are failing:
features/accessibility/provider.feature:206 # Scenario: I complete the …
> Ap 2385 release merits task list

- app/services/legal_framework/merits_tasks_retriever_service.rb
- app/views/providers/has_other_proceedings/show.html.erb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2393)
In all places in the Apply service, proceedings are displayed in the order they were added to the application.
> AP-2393 Ensure Proceedings are displayed in a consistent order

- config/locales/cy/citizens.yml
- config/locales/cy/shared.yml
- config/locales/en/citizens.yml
- config/locales/en/shared.yml
[Link to story](https://dsdmoj.atlassian.net/secure/RapidBoard.jspa?rapidView=233&modal=detail&selectedIssue=AP-2353)
- Ran i18n-tasks unused to identify (potentially) unused translations (this identified a lot of false positives).
- Ran bundle exec rake to identify any tests that have been broken by missing translations and replaced the missing translation.
- Tested the citizen journey and the provider journey manually for passported and non-passported claims and replaced any missing translations.
- I have attempted to check that none of the translations removed are used, but this could do with another pair of eyes and some manual testing.
> Ap 2353 remove unused content translations

- app/controllers/providers/check_merits_answers_controller.rb
- app/models/concerns/base_state_machine.rb
- app/models/legal_aid_application.rb
- spec/models/legal_aid_application_spec.rb
- spec/requests/providers/check_merits_answers_spec.rb
- spec/services/reports/reports_creator_spec.rb
This was originally implemented at haste due to the
short notice of CCMS shutdown.  It was not clear
when developing at pace that the first call to the
CCMS APIs were made in the ReportsCreatorWorker.
Therefore when we 'paused' teh submissions the reports
creator was failing to create the documents as there
was no way to fulfill the `ensure_case_ccms_reference_exists`
by requesting a `case_ccms_reference`
This PR moves the pause step forward to after check_merits
and removes the check on whether the step should run in the
controller …
> Fix: Change pause_submission event handling

- docs/pull_request_template.md
Remove the checklist from the PR template and replace with bullet points as reminders
> Tech-debt: Update PR template

- Gemfile
- Gemfile.lock
- spec/rails_helper.rb
The after_commit_everywhere was being flagged as a dependabot update
but I could find no use or invocation of it in the application
The ClimateControl gem was configured in rails_helper but, again,
never invoked …
> Tech-Debt: Remove unused gems

- .circleci/config.yml
- spec/spec_helper.rb
This adds some git & bash magic to the circle ci job.
If your commits on a branch include changes to files that match the regex `/services/ccms/*.*` the standard circle unit test job will run the CCMS tests too.
The overnight job will still run to ensure nothing slips through, but this should increase confidence that CCMS changes are monitored without having to manually run jobs
> ### Things to note
> The first unit_test should have taken the reduced time
> The TEMP commit should run all the tests because I changed a file that matched the /service/ccms/. pattern
> 
> Once this has been approved, I'll remove the temp commit, it's only to prove the theory …
> TechDebt: Improve ccms test handling

- app/services/proceeding_type_full_text_search.rb
- spec/services/proceeding_type_full_text_search_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2467)
[Link to Sentry issue](https://sentry.io/organizations/ministryofjustice/issues/2573606235/?project=5416054&query=is%3Aunresolved)
Fixed bug whereby If two or more consecutive spaces were used to separate search terms( e.g. "non&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;mol"), the method to transform the search terms into a Postgres `ts_query` did not take this into account, raised a 500 error in Sentry and returned no matching results.
- The …
> AP-2467 BUGFIX PT search not handling multiple spaces search terms

- app/controllers/concerns/providers/application_dependable.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2416)
This was impossible to test in code, I wrote explicit Rspec and cucumber tests and they all passed, including `BROWSER=chrome cucumber`
Then I found [this unmerged PR](https://github.com/rails/rails/pull/41517) to fix it but in the meantime I used the fix from the original issue [here](https://github.com/rails/rails/issues/38080#issuecomment-589856401) and tested in browser
Because the headers do not seem to be generated when running tests the encode_header block needs `:nocov:` because the tests never hit it 😢  …
> AP-2416: Handle accented characters

- .circleci/config.yml
- .github/workflows/anonymise_check.yml
- .github/workflows/brakeman-analysis.yml
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2453)
Revert the CI changes to only use main from now on
> AP-2453: Revert CI to only use main

- app/views/providers/proceedings_types/index.html.erb
- app/views/shared/forms/proceedings_types/_proceeding_type_form.html.erb
- features/step_definitions/civil_journey_steps.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2463)
Remove tabindex which was causing unusual tabbing behaviour
Updated index page to use formbuilder fieldset and removed separate template
> AP-2463 improve proceedings search keyboard navigation

- app/webpack/src/modules/proceedings.js
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2325)
The proceedings search results returned from the backend are ordered by relevance, but previously were displayed randomly in the frontend. They are now displayed in the correct order.  …
> AP-2425 Display proceedings in correct order

- config/locales/en/forms.yml
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2448)
If a postcode lookup fails due to a connection failure (eg if wifi is turned off), the user should see the manual address entry screen with an appropriate message however instead  an error is presented to the user.
This commit adds the correct wording to the `config/locales/en/forms.yml` locale. It also corrects the wording which is displayed when an unsuccessful response is received from the OS API, as it is currently a bit misleading (new wordings have been agreed with Jim.) …
> AP-2448 Add translation for failed address lookup

- app/webpack/src/modules/proceedings.js
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2426)
Remove min length for highlighted terms so that numbers can be highlighted in the proceedings search results
> AP-2426 Fix highlighting of numbers in proceedings search results

- app/models/legal_aid_application.rb
- app/services/dashboard_event_handler.rb
- spec/services/dashboard_event_handler_spec.rb
We were getting a lot of noise on sentry from geckoboard re:
> Geckoboard::UnexpectedStatusError
> You have exceeded the API rate limit of 60 requests per minute. Try sending data less frequently
I think this may have been caused by the after_save hooks on LegalAidApplications, it was sending a  dashboard.delegated_functions_used every time the record was saved, so for each subsequent page save it would trigger.  
While debugging, it would actually send it 3 times on each page save!  
There used to be a separate data set but this metric is now recorded in the generic `applications` dataset and is therefore updated at many other stages, e.g. creation, submission, etc
Therefore removing this after_save hook will hopefully reduce the number of API pushes to geckoboard, reducing complaints! …
> Tech-Debt: Reduce Geckoboard noise

- app/views/providers/check_client_details/show.html.erb
A [change](https://github.com/DFE-Digital/govuk-formbuilder/pull/308) to the DFE GOVUK Formbuilder has resulted in an incorrect legend being displayed for the radio buttons on `/check_client_details`
This is because `legend: { text: '' }` now falls back to the default value (`Check_client_details`) instead of not displaying a legend.
This commit replaces it with `legend: nil` so that no legend is displayed.
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2501) …
> AP-2501 Incorrect legend on /check_client_details

- app/webpack/src/modules/proceedings.js
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2496)
Deselect the previously selected proceeding item when a new search results are returned
This is to ensure the tabbing behaviour in the proceeding items results list works correctly …
> AP-2496 Add JS to deselect previously selected proceeding item

- app/services/true_layer/api_client.rb
- spec/factories/legal_aid_applications.rb
- spec/models/aggregated_cash_income_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2507)
The lead_proceeding was not being set correctly for the tests. Previously when geckoboard was being notified it must also have been instantiating the application_proceeding_type and assigning the lead_proceeding, however when that notification was removed the lead_proceeding was not being saved.
Added a reload to the factory so that the lead_proceeding is saved after it is created. …
> AP-2507- ccms failures 

- app/helpers/accessible_navigation_helper.rb
- spec/helpers/accessible_navigation_helper_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2500)
Removes the line in the accessibility helper method that automatically adds a title attribute to elements  
- it is unnecessary duplication of text/info which also causes a WAVE warning
- further reasons for not using the title attribute: https://www.tpgi.com/using-the-html-title-attribute/ 
Updates unit tests  …
> AP-2500 remove title text for labelled elements

- app/services/govuk_emails/delivery_man.rb
- spec/services/govuk_emails/delivery_man_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2506)
When we send an email to an unallowed account using Notify on non-live environments it returns a BadRequestError.
These will never succeed, but previously we stored the ScheduledMail and kept retrying.  This now traps the error and swallows it so sentry will not get excessive alerts, it also cancels the ScheduledMail so that subsequent attempts will not occur …
> AP-2506: Improve handling of email errors

- db/migrate/20210913150028_re_seed.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2510)
Data seeding in database schema migrations can cause problems later on.  This removes the code to populate the 
DefaultCostLimitation table.
> AP-2510 Remove data seed from schema migration

- config/initializers/filter_parameter_logging.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2060)
- Currently we are logging some pii information to Kibana
- Went through the provider and citizen journeys attempting to find where this data was being logged.
- The examples I found were all caused by Rails parameter logging and can be filtered by adding to filter_parameter_logging.rb
- I have also included as many free text fields as possible on the basis that these could contain pii. …
> Remove pii from Kibana logs

- db/schema.rb
- spec/models/setting_spec.rb
The `alert_via_sentry` setting should default to `true` but a migration hasn't run properly and is defaulting to `false`. This updates the schema and related tests.
> Fix default for alert_via_sentry

- app/jobs/reports_uploader_job.rb
- helm_deploy/apply-for-legal-aid/templates/cronjob-admin-report.yaml
- lib/tasks/jobs/create_admin_reports.rake
- spec/models/legal_aid_application_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2531)
This is an interim PR to help us get to the bottom of what is happening to the Submitted Applications report, which appears to be deleted from S3 storage sometime after creation.
This PR does two things:
- set the cronjob `successfulJobsHistoryLimit` value to 3 so that the containers stay around and enable us to view the logs
- Adds lots of debugging logs to the `ReportsUploaderJob` …
> AP-2531 Cronjob Logging

- app/models/legal_aid_application.rb
- app/models/proceeding.rb
- spec/factories/legal_aid_applications.rb
- spec/factories/proceedings.rb
- spec/factory_specs/legal_aid_application_factory_spec.rb
- spec/models/legal_aid_application_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2615)
- changed association `has_many :attempts_to_settle` to be made through `proceedings` rather than `application_proceeding_types`
- changed association `has_many :chances_of_success` to be made through `proceedings` rather than `application_proceeding_types`
- added method `#lead_proceeding` to replace `#lead_proceeding_type`
- added method `#find_or_set_lead_proceeding` to replace `#find_or_create_lead_proceeding_type`
- added_method '#proceedings_by_name` to replace `#application_proceedings_by_name`
- changed `#lowest_prospect_of_success` to use `proceedings` instead of `application_proceeding_types`
- added `with_proceedings` traits to legal aid application factory
Before you ask people to …
> AP-2615 LegalAidApplication - use Proceeding

- db/migrate/20211102100659_add_digest_extracted_at_to_settings.rb
- db/schema.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2603)
- Added field to record time of last data digest extract.
> AP-2603 Add digest_extracted_at field to Settings

- app/controllers/concerns/providers/application_dependable.rb
- spec/requests/providers/gateway_evidence_spec.rb
Our version of external pull request https://github.com/ministryofjustice/laa-apply-for-legal-aid/pull/2973, created to reduce the risk of security issues.
This version makes a couple of minor changes from the original so that the test actually passes. …
> Add test coverage for invalid uploaded file header 🇧🇷 

- app/helpers/application_helper.rb
- app/views/shared/check_answers/_merits.html.erb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2623)
Refactors the `linked_children_names` method to use a `Proceeding record` instead of an `ApplicationProceedingType` record, and updates the `views/shared/check_answers/_merits.html.erb` partial to reflect that change.
Note: this change doesn't remove any references to `ApplicationProceedingType` from the `_merits.html.erb` partial. This will be done in a separate ticket. …
> AP-2623 Use Proceeding model in ApplicationHelper

- app/models/application_proceeding_type.rb
- app/models/proceeding.rb
- app/services/reports/mis/application_detail_csv_line.rb
- spec/factories/legal_aid_applications.rb
- spec/services/reports/mis/application_detail_csv_line_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-593)
Refactors the `ApplicationsDetailsCSVLine` model to use `Proceedings` instead of `ApplicationProceedingTypes`.
This requires moving some methods from the `ApplicationProceedingType` model to the `Proceeding` model, and some factory changes.
Note: this change leaves some references to `ApplicationProceedingType` in `application_detail_csv_line_spec`. These cannot be removed until the `ChancesOfSuccess` model has been refactored to remove reliance on `ApplicationProceedingTypes`. …
> AP-2593 Use Proceeding in ApplicationsDetailsCSVLine

- app/helpers/table_sort_helper.rb
- app/webpack/stylesheets/table-sort.scss
add break which is hidden at certain breakpoints so the arrows wrap to a new line if there is not enough space
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2535)
> AP-2535 fix table sort arrows

- app/models/proceeding.rb
- app/services/proceeding_sync_service.rb
- db/data/20211103105816_populate_extra_proceedings_fields.rb
- db/data_schema.rb
- db/migrate/20211103105546_add_extra_fields_to_proceedings.rb
- db/migrate/20211103112548_set_new_proceeding_fields_to_not_null.rb
- db/schema.rb
- spec/factories/proceedings.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2468)
- Migration to add extra fields:
- `matter_type`
- `category_of_law`
- `category_law_code`
- Data migration to populate those fields on existing records
- Migration to make those fields `NOT NULL`
- Modified creation of `Proceeding` record to include the new values
- Modified Factory …
> AP-2648 Add Extra fields to Proceeding table

- app/services/mark_purgeable_service.rb
- db/migrate/20211104141141_add_purgeable_tolegal_aid_applications.rb
- db/schema.rb
- helm_deploy/apply-for-legal-aid/templates/cronjob-mark-purgeable.yaml
- lib/tasks/purge.rake
- spec/services/mark_purgeable_service_spec.rb
Service to mark as purgaeble those records ripe for deletion
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2609)
- Added purgeable column to `LegalAidApplication`
- Service to mark all records over a certain age as purgeable
- Rake take to run that service
- Cronjob to run the rake task nightly …
> AP-2609 Mark purgeable service

- app/views/providers/limitations/_proceeding_type.html.erb
- app/views/providers/limitations/_proceeding_types.html.erb
- app/views/providers/limitations/_proceeding_types_with_df.html.erb
- features/accessibility/provider.feature
- features/providers/civil_application_journey.feature
- features/providers/merits_task_list.feature
- features/step_definitions/debug_steps.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2618)
Updates three Limitations partials to use `Proceedings` via the `proceedings_by_name` method on the `LegalAidApplication` model instead of `ApplicationProceedingTypes` via the `application_proceedings_by_name` method.
The ticket mentions updating the Limitations controller too, however that file contains no references to ApplicationProceedingTypes so no change has been made. …
> AP-2618 Use Proceedings on Limitations views

- app/views/shared/check_answers/_substantive_limitations.html.erb
Changing the view to use lead_application_proceeding_type rather than
application_proceeding_type.first stops the issues with
scope limitations being assigned
> FIX: Update tests

- app/controllers/providers/proceeding_merits_task/attempts_to_settle_controller.rb
- app/controllers/providers/proceeding_merits_task/chances_of_success_controller.rb
- app/controllers/providers/proceeding_merits_task/linked_children_controller.rb
- app/controllers/providers/proceeding_merits_task/success_prospects_controller.rb
- app/helpers/task_list_helper.rb
- app/models/proceeding.rb
- app/services/flow/flows/provider_merits.rb
- app/views/providers/proceeding_merits_task/attempts_to_settle/show.html.erb
- app/views/providers/proceeding_merits_task/chances_of_success/index.html.erb
- app/views/providers/proceeding_merits_task/linked_children/show.html.erb
- app/views/providers/proceeding_merits_task/success_prospects/show.html.erb
- app/views/shared/check_answers/_merits.html.erb
- features/providers/merits_task_list.feature
- features/step_definitions/civil_journey_steps.rb
- spec/helpers/providers_helper_spec.rb
- spec/helpers/task_list_helper_spec.rb
- spec/models/proceeding_spec.rb
- spec/requests/providers/check_merits_answers_spec.rb
- spec/requests/providers/proceeding_merits_task/attempts_to_settle_controller_spec.rb
- spec/requests/providers/proceeding_merits_task/chances_of_success_spec.rb
- spec/requests/providers/proceeding_merits_task/linked_children_spec.rb
- spec/requests/providers/proceeding_merits_task/success_prospects_spec.rb
[Link to story](https://dsdmoj.atlassian.net/jira/software/c/projects/AP/boards/233?modal=detail&selectedIssue=AP-2619)
[Link to story](https://dsdmoj.atlassian.net/jira/software/c/projects/AP/boards/233?modal=detail&selectedIssue=AP-2625)
- Amended task_list_helper.rb to include proceeding_id rather than application_proceeding_type_id in proceeding_task_url
- Amended attempts_to_settle_controller.rb, chances_of_success_controller.rb, linked_children_controller.rb and success_prospects_controller.rb to use proceeding_id.
- Amended flow defined in provider_merits.rb to use proceeding_id.
- Amended app/views/providers/proceeding_merits_task/attempts_to_settle/show.html.erb, app/views/providers/proceeding_merits_task/chances_of_success/index.html.erb, …
> Ap 2619 convert merits tasks flow to use proceeding

- .circleci/config.yml
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2643)
Replace `circleci/*` with `cimg/`
Replace `-node-browsers` with just `-browsers`
Load `chrome` and `chromedrivers` as part of the integration tests job only, they aren't needed for rspec …
> AP-2643: Update CircleCI images

- app/models/concerns/delegated_functions.rb
- spec/models/legal_aid_application_spec.rb
Bugfix - a method on delegated functions was only covered by tests in CCMS files. This meant that running rspec tests without CCMS tests would result in 99.99% coverage issue. This adds a test to cover the method in question and also a note to merge it with the method above when application_proceeding_type are removed. …
> add test for method only used in CCMS tests

- Gemfile
- Gemfile.lock
- bin/sidekiq_health_check
- helm_deploy/apply-for-legal-aid/templates/deployment_worker.yaml
Test to see if removing sidekiq alive is feasible in Apply (and maybe others?)
It doesn't help with the sidekiq gem update but it does reduce our gemfile size?
Should we remove it or close and ignore this PR?
| Remove sidekiq alive | close and kill this PR | user |
| :-: |:-: |---|
| yes |  | @colinbruce 
| yes |  | @willc-work  
|  |  | @kmahern  
|  |  | @RoseSAK  
|  |  | @stephenrichards  
| yes |  | @mpw5  
Feel free to edit this comment with your response - if you care enough to comment! 😃  …
> Tech-Debt: Remove sidekiq alive

- app/views/shared/check_answers/_emergency_limitations.html.erb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2617)
Updates `emergency_limitations` partial use `Proceeding` objects instead of `ApplicationProceedingType` objects. Also fixes a couple of minor stylistic things. …
> AP-2617 Use Proceedings in shared CYA partials

- app/controllers/providers/submitted_applications_controller.rb
- app/views/providers/submitted_applications/show.html.erb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2622)
This is slightly different to what the ticket asked for. The lines of code that refer to `application_proceedings_types` aren't acually needed - they are passed to the `app/views/shared/check_answers/_merits.html.erb` partial however aren't ever used. I suspect they are a hangover from pre-multiple proceedings days.
This change simply deletes the unused code. The submitted application page appears as expected without it. It might be useful if someone could double-check my logic though 😁  …
> AP-2622 Remove unneeded SubmittedApplication code

- app/controllers/providers/check_merits_answers_controller.rb
- app/views/providers/check_merits_answers/show.html.erb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2627)
Similar to [AP-2622](https://github.com/ministryofjustice/laa-apply-for-legal-aid/pull/3051), rather than change `application_proceeding_types` to `proceedings`, I've simply removed them as they are no longer being used.
- You …
> AP-2627 Remove unused CheckMeritsAnswers code

- app/controllers/admin/settings_controller.rb
- app/forms/settings/setting_form.rb
- app/models/setting.rb
- app/views/admin/settings/show.html.erb
- config/locales/en/admin.yml
- config/locales/en/helpers.yml
- db/migrate/20211112174848_add_employed_journey_flag_to_settings.rb
- db/schema.rb
- lib/tasks/setup_db_for_testing.rake
- spec/models/setting_spec.rb
- spec/requests/admin/settings_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2636)
Adds a feature flag setting to allow employed journeys to be enabled/disabled.
> AP-2636 Add feature flag for employed journeys

- app/models/legal_framework/serializable_merits_task_list.rb
- app/services/metrics/sidekiq_queue_sizes.rb
The pattern we currently use causes a lot of errors
as it is unsupported in the next update of ruby
This PR adds the new, permitted_classes: pattern.
It works with the current version of ruby _and_ the
next, 3.1, release of ruby …
> Tech debt: Update YAML.safe_load instantiation pattern

- Gemfile.lock
Revert to `ruby` and the let the relevant systems handle the platform
> Fix: Gemfile.lock platforms

- app/views/providers/income_summary/index.html.erb
- app/views/providers/means_summaries/show.html.erb
- app/views/providers/no_income_summaries/show.html.erb
- config/locales/en/providers.yml
- features/providers/non_passported_journey.feature
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2598)
Update the display of student finance amounts in both income summary pages and the means summary page.
Fixes a bug on the means summary that meant the student finance amount was never displayed …
> AP-2598: Update student finance content

- bin/uat_deploy
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2633)
UAT Ingress notation has incorrect naming. This fixes the uat_deploy script so that the ingress is set correctly.
> AP-2633 Fix ingress annotation for UAT deployments

- app/views/providers/substantive_applications/show.html.erb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2614)
Donditionally revealed text content is no longer deemed to be accessible by the GOV.UK Design system - remove this content and replace with warning text below the radios fieldset …
> AP-2614 remove conditionally revealed text

- app/controllers/providers/applicant_employed_controller.rb
- config/environments/development.rb
- config/environments/production.rb
- config/environments/test.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2702)
> AP-2702 Do not call HMRC interface unless config settings true

- bin/uat_deploy
- bin/uat_deploy_to_live
On branches with long names, deployments to the live cluster fail because the annotation we set in `uat_deploy_to_live` does not match the truncated ingress name expected by cloud platform.
This commit updates the `uat_deploy_to_live` so that it also truncates long names to 52 characters, which allows deployments to succeed. …
> Fix live deployments for long branch names

- app/views/providers/applicant_employed/index.html.erb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2703)
> AP-2703 Remove reference to HMRC in Applicant Employed page

- app/services/destroy_purgeable_service.rb
- app/webpack/src/modal-dialogue.js
- helm_deploy/apply-for-legal-aid/templates/cronjob-destroy-purgeable.yaml
- lib/tasks/purge.rake
- spec/services/destroy_purgeable_service_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2610)
- Added DestroyPurgeableService to delete records with purgeable date in the past and updated_at at least 2 years ago
- Added a rake task purge:destroy to run the service
- Added cronjob to run purge:destroy every morning at 01:30 …
> AP-2610 Delete purgeable applications

- app/models/provider.rb
- db/data/20211125142125_add_employment_to_permissions_table.rb
- db/data_schema.rb
- spec/models/provider_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2697)
Add a new permission and a method to check for employment permissions.
Currently employment is a child of non_passported permission. There is no specific reason why it is not `application.employment.*` and it is an easy change if this is preferred. My thinking is that employed would only be of use to users with non_passported permssion. However all users have non_passported permissions so it is not a strong argument for how I have implemented it.
I have tested using `provider.employment_permissions?` to change the flow and it works as expected.
The ticket is light on details about the `done when` for this spike. We can either merge this PR in readiness for when it is needed, or wait until it is needed and it can be done as part …
> ap-2697 Add employment permissions

- app/views/providers/applicant_employed/index.html.erb
- config/environments/development.rb
- config/environments/production.rb
- config/environments/test.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2716)
- Set the rails configuration flag `collect_hmrc_data` to true
- re-instated copy about collecting HRMC data on applicant_employed page
> AP-2716 Reinstate HMRC check

- app/models/legal_aid_application.rb
- app/views/shared/check_answers/_assets.html.erb
The means report is showing £0 for the balance on accounts when they do not exist. This was noticed by a caseworker on a savings account, change made to both savings and current accounts to ensure we report these correctly on the means report. The safe operator (&) in the query returns a 0 as the savings accounts is an empty array …
> bugfix: display correct response on means report

- app/views/providers/applicant_bank_accounts/show.html.erb
- app/views/providers/has_other_dependants/show.html.erb
- app/views/providers/has_other_proceedings/show.html.erb
- app/views/providers/no_income_summaries/show.html.erb
- app/views/providers/no_outgoings_summaries/show.html.erb
- config/locales/en/providers.yml
Update the size of several secondary headings in order to remain consistent across the service
Update 'no' radio button content on no income summaries and no outgoings summaries pages …
> AP-2649 update secondary heading sizes

- app/services/ccms/requestors/case_add_requestor.rb
- spec/data/ccms/mp_df_case_add_request.xml
- spec/services/ccms/requestors/case_add_requestor_xml_blocks/non_passported_attributes_spec.rb
- spec/services/ccms/requestors/case_add_requestor_xml_blocks/passported_attributes_spec.rb
Substantive scope limitations are incorrectly appearing on emergency applications in CCMS.
This is because the `generate_scope_limitations` method in the `CaseAddRequestor` class sets the `DelegatedFunctionsApply` attribute as `proceeding.used_delegated_functions?` for both the substantive and delegated functions scope limitations. This means that for a DF application, both scope limitations have a `DelegatedFunctionsApply` attribue of `true`.
This is incorrect - only the delegated functions scope limitation should have a `DelegatedFunctionsApply` attribue of `true`.
This PR changes that method so that the substantive scope limitation always has a `DelegatedFunctionsApply` attribute of `false`, and the delegated functions scope limitations always has a `DelegatedFunctionsApply` attribute …
> AP-2719 BUGFIX: Substantive scope limitations appearing on Emergency Applications

- app/models/concerns/base_state_machine.rb
- spec/services/ccms_restart_submissions_spec.rb
There was a bug in the `restart_submission` event that bypassed the generate reports step
This fix redirects the event to duplicate the steps undertaken in the `generate_reports`
event that generate the means/merits report and trigger the email to providers …
> Fix: Restart CCMS submissions

- app/controllers/providers/applicant_employed_controller.rb
- app/controllers/providers/confirm_dwp_non_passported_applications_controller.rb
- app/views/providers/applicant_employed/index.html.erb
- app/views/providers/confirm_dwp_non_passported_applications/show.html.erb
- app/webpack/stylesheets/interruption-panel.scss
- config/locales/en/providers.yml
- features/accessibility/provider.feature
- features/providers/civil_application_journey.feature
- features/providers/non_passported_journey.feature
- features/providers/pathways_from_check_your_answers.feature
- spec/factories/legal_aid_applications.rb
- spec/requests/providers/applicant_employed_spec.rb
- spec/requests/providers/confirm_dwp_non_passported_applications_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2565)
Moves the call to HMRC from the Is your client employed? page to the DWP results page.
The call only takes place if the provider confirms that the non-passported DWP benefit check is correct _and_ the employed journey feature flag is enabled _and_ the provider has the correct permissions _and_ the HMRC call setting is enabled.
Also adds hint text to the DWP results page, with a helper method to identify when to display this.
Note: requires confirmation of the wording of the hint text from Jim, but the rest of the code can be reviewed now.
- …
> AP-2565 Move HMRC call

- README.md
- lib/tasks/db.rake
- scripts/restore_anon_db.sh
- scripts/restore_anonymised_db.sh
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2555)
Add shell script to copy the anonymised.sql file to the selected pod and run a rake task to drop existing DB and replace it with the anonymised version.
Also outputs a list of 10 user email addresses to make logging it easier.
- …
> AP-2555 remote restore anonymised DB to uat

- spec/models/proceeding_merits_task/chances_of_success_spec.rb
Tests in `spec/models/proceeding_merits_task/chances_of_success_spec.rb` are occasionally failing due to the way `application_proceeding_types` and `proceedings` are set up.
By creating the `proceeding` after the creation of the `application` and `application_proceeding_types`, and by creating different numbers of `application_proceeding_types` and `proceedings`, it is possible for the `proceeding_case_id` to be non-unique.
This changes the set up so that identical `application_proceeding_types` and `proceedings` are created simultaneously, replicating what happens in the real service. This should prevent the unique constraint being violated.
- Github should not be reporting conflicts; you …
> Fix flaky chances of success tests

- bin/uat_deploy
deploy to uat was using an old namespace env var on circle ci
> bugfix: use correct namespace env var

- .circleci/config.yml
- spec/spec_helper.rb
The overnight, full test run on circle had stopped running all the tests:
This PR:
* Adds a method of ensuring the i18n tests are run to spec helper
* Moves the ENV_VARs inline to the command, setting it in the run/environment way was not being loaded by rspec, this should ensure _all_ tests are run …
> Fix: Full CCMS test run on CircleCI

- helm_deploy/apply-for-legal-aid/templates/cronjob-export-digest.yaml
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2747)
Previous cronjob containers were failing with `OOMKilled`
> AP-2747 Increase memory on digest export cron job

- app/controllers/admin/settings_controller.rb
- app/forms/settings/setting_form.rb
- app/models/setting.rb
- app/views/admin/settings/show.html.erb
- config/locales/en/admin.yml
- config/locales/en/helpers.yml
- db/migrate/20211208161719_add_evidence_upload_flag_to_settings.rb
- db/schema.rb
- lib/tasks/setup_db_for_testing.rake
- spec/models/setting_spec.rb
- spec/requests/admin/settings_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2729)
Adds a setting to allow the new evidence upload feature to be toggled for solicitors.
> AP-2729 Add evidence upload feature flag

- app/models/document_category.rb
- app/models/legal_aid_application.rb
- db/migrate/20211209141633_add_required_document_categories_to_legal_aid_applications.rb
- db/schema.rb
- spec/models/legal_aid_application_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2731)
Adds a field to the `LegalAidApplication` model to hold an array of document categories required for evidence upload.
This defaults to an empty array and is validated against the list of categories held in the `document_categories` table via a scope on the `DocumentCategory` model. …
> AP-2731 Add required_document_categories field

- app/models/hmrc/employment.rb
- app/models/hmrc/employment_income_summary.rb
- app/models/hmrc/employment_payment.rb
- app/models/hmrc/response.rb
- spec/factories/hmrc/responses.rb
- spec/factory_helpers/hmrc_response/use_case_one.rb
- spec/factory_specs/hmrc_response/use_case_one_helper_spec.rb
- spec/models/hmrc/employment_income_summary_spec.rb
- spec/models/hmrc/employment_payment_spec.rb
- spec/models/hmrc/employment_spec.rb
- spec/models/hmrc/response_spec.rb
- spec/workers/hmrc/result_worker_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2568)
- after discussion with Pamela, it was agreed the Employment income summary page would show payment date rather than range as shown in the ticket.  The parsed response (`HMRC::EmploymentIncomeSummary`) reflects this.
- The parser currently only works when the applicant has one job - this is because we don't know how the data will be presented for applicants with more than one job.
This PR parses the HMRC and presents it in a way which is easy to display on the review income employment page.
- Created `HMRC::EmploymentIncomeSummary` to encapsulate all income from all employments
- Created `HMRC::Employment` to encapsulate each employment
- Created `HMRC::EmploymentPayment` to encapsulate each payment
- Added scope …
> AP-2568 Parse HMRC response

- app/views/layouts/application.html.erb
- app/views/providers/substantive_applications/show.html.erb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2759)
In a couple of places the warning text icon has an 'i' instead of an exclamation mark
> fix warning text icons

- app/models/legal_aid_application.rb
- app/services/required_document_category_analyser.rb
- spec/factories/legal_aid_applications.rb
- spec/models/legal_aid_application_spec.rb
- spec/services/required_document_category_analyser_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2732)
- Created new required_document_category_analyser service class
- Converted section_8_proceedings? on legal_aid_application model to use proceedings rather than proceeding_types
- Added new trait on legal_aid_applications factory with_multiple_proceedings_inc_section8 to facilitate testing …
> ap-2732: create required_document_category_analyser

- app/controllers/providers/employment_incomes_controller.rb
- app/forms/legal_aid_applications/employment_income_form.rb
- app/services/flow/flows/provider_capital.rb
- app/views/providers/employment_incomes/show.html.erb
- config/locales/en/activemodel.yml
- config/locales/en/providers.yml
- config/routes.rb
- db/migrate/20211209134144_add_employment_attrs_to_legal_aid_application.rb
- db/schema.rb
- spec/requests/providers/client_completed_means_spec.rb
- spec/requests/providers/employed_incomes_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2567)
also 
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2569)
Add a new view and controller and add them to the provider flow
Add new attributes about employment details to LegalAidApplication (ap-2569)
Display the HMRC response to the user at the start of the client journey (before income summary pages)
Add tests …
> Ap2567 hmrc results

- spec/factories/legal_aid_applications.rb
TEsts were failing with duplicate key.
This was caused by the LegalAidApplication factory traits `:with_proceeding_types` and `:with_proceedings` being called together.  The `:with_proceeding_types` trait creates a `Proceeding` as well as an `ApplicationProceedingType`, causing the `:with_proceeding` trait to fail when it creates the same `Proceeding`.
This is fixed by modifying the `:with_proceedings` trait to only create the`Proceeding` if it doesn't already exist.  This can be reverted once we've removed the `:with_proceeding_types` trait. …
> Testing bugfix

- spec/models/legal_aid_application_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2763)
Occasionally, runnng the rspec suite of tests would result in less than 100% coverage, the culprit being the `online_current_accounts_balance` method on LegalAidApplication.  This PR adds a test to ensure that method is always adequately tested. …
> AP-2763 Test to ensure 100% code coverage

- app/services/reports/base_report_creator.rb
- app/services/reports/means_report_creator.rb
- app/services/reports/merits_report_creator.rb
- spec/services/reports/means_report_creator_spec.rb
- spec/services/reports/merits_report_creator_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2362)
Update the report generation, previously we would see an occasional error when reports did not have a document attached (see the logging introduced by #2755).
This adds some logic to the means and merit report generators to extend the checks for existing records.
* If an attachment exists and its linked document is present, it will continue to log the state and exit the generator
* If an attachment exists and its linked document cannot be found, it destroys the existing attachment and recreates from scratch
It extends the logging (that can be checked on kibana) so we can monitor for extra occurences …
> AP-2362:improve report generation

- app/helpers/gov_uk_form_helper.rb
- app/views/providers/has_evidence_of_benefits/show.html.erb
- config/locales/en/providers.yml
- spec/requests/providers/has_evidence_of_benefits_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2733)
- Amended  `yes_no_options` helper method to optionally take hint text for individual radio buttons
- Amended  `yes_no_options` to use a `Struct` rather than `OpenStruct`
- Display new copy on page if evidence upload setting is TRUE …
> AP-2733 Change copy on has_benefit_evidence page 

- app/services/digest_exporter.rb
- helm_deploy/apply-for-legal-aid/templates/cronjob-export-digest.yaml
- spec/services/digest_exporter_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2778)
The digest exporter cron job was failing every night to to running out of memory, and taking 45 minutes to run before failing.  Several steps have been taken to solve this issue:
- increase memory on kubernetes cronjob definition
- Read the ids of the digest records and process, rather than read all 9,000 into memory at the same time
- format the output into an array and write to the spreadsheet once, rather than make an API call to the spreadsheet for each line (this has reduced the running time from 45 minutes to < 3 minutes
- Add logging to that progress can be monitored
- Add Extracted at time to the header line of the worksheet
- Tests and rubocop should be passing: `bundle exec …
> AP-2778 digest exporter cron

- app/services/hmrc/create_responses_service.rb
- spec/services/hmrc/create_responses_service_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2782)
Adds a guard clause to the call method of the CreateResponsesService class to prevent duplicate calls to HMRC being made.
> AP-2782 Prevent duplicate HMRC requests

- app/views/providers/means_summaries/show.html.erb
Discussed with Stevey, Jim and Pamela the original ticket says to hide it if there is no answer but we usually show something to allow ther user the option to change their answer.
Change the check your answers page to display the employment section all of the time, but hide the details section if the answer to the first question is No. …
> bugfix: always show employment section

- app/models/cfe/base_result.rb
- app/models/cfe/v1/result.rb
- app/models/cfe/v2/result.rb
- spec/factories/cfe_results.rb
- spec/factories/cfe_results/v1/mock_results.rb
- spec/factories/cfe_results/v2/mock_results.rb
- spec/factories/legal_aid_applications.rb
- spec/models/cfe/v1/result_spec.rb
- spec/models/cfe/v2/result_spec.rb
Occasionally, unit tests on Circle-CI would fail due to test coverage being less than 100%.
This could be reliably reproduced on Circle CI by using the seed 51620.
It turns out that with certain seeds, the `:nocov:` at the beginning and end of `app/models/cfe/v1/results.rb` and 
`app/models/cfe/v1/results.rb` were not being honoured, and they were being counted as not tested.
This PR re-instates the tests (and factories, and mock result objects) for those two files. …
> Re-instate testing for CFE V1 and V2 results

- app/models/application_proceeding_type.rb
- app/models/proceeding.rb
- app/services/ccms/attribute_value_generator.rb
- spec/models/application_proceeding_type_spec.rb
- spec/models/proceeding_spec.rb
- spec/services/ccms/requestors/case_add_requestor_spec.rb
- spec/services/ccms/requestors/case_add_requestor_xml_blocks/passported_attributes_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2723)
Removal of `ApplicationProceedingTypes` from the CCMS `AttributeValueGenerator` class and specs. There are still some references to `ApplicationProceedingTypes` in that code but these can't be removed until `ChancesOfSuccess` has been converted to use only `Proceedings`. …
> AP-2723 Replace ApplicationProceedingTypes with Proceedings in CCMS code

- config/locales/en/providers.yml
Fixes a small typo on the `client_completed_means` screen.
> Fix typo: HRMC -> HMRC

- app/controllers/providers/proceeding_merits_task/attempts_to_settle_controller.rb
- app/controllers/providers/proceeding_merits_task/chances_of_success_controller.rb
- app/controllers/providers/proceeding_merits_task/linked_children_controller.rb
- app/controllers/providers/proceeding_merits_task/success_prospects_controller.rb
- app/forms/chances_of_successes/success_likely_form.rb
- app/forms/providers/proceeding_merits_task/linked_children_form.rb
- app/models/legal_framework/serializable_merits_task_list.rb
- app/models/proceeding_merits_task/attempts_to_settle.rb
- app/models/proceeding_merits_task/chances_of_success.rb
- app/services/flow/flows/provider_merits.rb
- app/services/legal_framework/merits_tasks_retriever_service.rb
- app/services/reports/mis/application_detail_csv_line.rb
- db/migrate/20211223105917_allow_null_apt_on_chances_of_success.rb
- db/schema.rb
- spec/factories/chances_of_successes.rb
- spec/factories/legal_aid_applications.rb
- spec/factories/proceeding_merits_task/proceeding_linked_children.rb
- spec/forms/providers/proceeding_merits_task/linked_children_form_spec.rb
- spec/models/legal_aid_application_spec.rb
- spec/models/legal_framework/serializable_merits_task_list_spec.rb
- spec/models/proceeding_merits_task/chances_of_success_spec.rb
- spec/requests/providers/proceeding_merits_task/chances_of_success_spec.rb
- spec/requests/providers/proceeding_merits_task/linked_children_spec.rb
- spec/requests/providers/proceeding_merits_task/success_prospects_spec.rb
- spec/requests/providers/submitted_applications_spec.rb
- spec/services/legal_framework/merits_tasks_retriever_service_spec.rb
- spec/services/reports/mis/application_detail_csv_line_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2721)
- Revove ApplicationProceedingType from:
- `MeritsTaskListController`
- `AttemptsToSettelController`
- `ChancesOfSuccessController`
- `LinkedChildrenController`
- `SucessProspectsController`
- And associated models, services and forms
- enabled Null on application_proceeding_id fields on the following tables:
- `chances_of_successes`
- `attempts_to_settles` …
> AP-2721 Remove ApplicationProceedingType from Merits Task List

- spec/services/ccms/requestors/case_add_requestor_spec.rb
- spec/services/ccms/requestors/case_add_requestor_xml_blocks/non_passported_additional_property_attributes_spec.rb
- spec/services/ccms/requestors/case_add_requestor_xml_blocks/non_passported_attributes_spec.rb
- spec/services/ccms/requestors/case_add_requestor_xml_blocks/non_passported_benefits_attrs_spec.rb
- spec/services/ccms/requestors/case_add_requestor_xml_blocks/non_passported_dependant_child_attributes_spec.rb
- spec/services/ccms/requestors/case_add_requestor_xml_blocks/non_passported_entities_spec.rb
- spec/services/ccms/requestors/case_add_requestor_xml_blocks/non_passported_variable_attributes_spec.rb
- spec/services/ccms/requestors/case_add_requestor_xml_blocks/passported_attributes_spec.rb
- spec/services/ccms/submitters/add_case_service_spec.rb
- spec/services/ccms/submitters/upload_documents_service_spec.rb
After AP-2721 (#3227) removed the application_proceeding_type from chances_of_success
these all started failing because the factory could not add a non-existent field
> Fix: CCMS tests were failing

- config/initializers/omniauth.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2098)
Omniauth is printing warnings about not using GET in omniauth requests.  We are unable to resolve this at the moment, but this PR will silence the warnings in the log, reducing the possibility of bad actors being warned about this potential vulnerabililty. …
> AP-2098 Silence GET warnings

- .circleci/config.yml
- bin/delete_dependabot_deployment
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2780)
Delete any uat deployments for branches starting 'dependabot' immediately after deployment. Uses circle job filters so that only branches matching regex /dependabot.*/ are deleted. …
> Amend circleci config to delete dependabot deployments

- .circleci/config.yml
Bump CircleCI Slack Orb to 4.5.2.
> Bump CircleCI Slack Orb to 4.5.2

- spec/requests/providers/has_other_proceedings_controller_spec.rb
This will probably be removed soon, but this should help prevent
the dependabot PRs flickering in the meantime.
The sequence of the ApplicationProceedingTypes was not always
returning the eldest as the first in the array …
> Fix: Flickering provider test

- app/models/document_category.rb
- app/models/legal_aid_application.rb
- app/services/ccms/submitters/obtain_document_id_service.rb
- spec/models/document_category_spec.rb
- spec/models/legal_aid_application_spec.rb
- spec/services/ccms/submitters/obtain_document_id_service_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2737)
ObtainDocumentIdService used a hard-coded list of attachment types to exclude from uploading to CCMS.  This PR refactors that code to use the `submit_to_ccms` field on the DocumentCategory record to decide whether or not to upload it to CCMS.  This is because this list will change over time, and the control of what to upload and what to omit is all in one place.
- Refactored `valid_document_categories` scope on `DocumentCategory` to a class method `.displayable_document_category_names` - it returns an array of names, not an array of records, and so isn't a scope
- Added class method `.submittable_category_names` to DocumentCategory
- Refactored `ObtainDocumentIdService` to use `DocumentCategory.submittable_category_names` rather …
> AP-2737 Refactor ObtainDocumentIdService to use DocumentCategory

- app/views/shared/check_answers/_merits.html.erb
- config/locales/en/shared.yml
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2647)
Emergency Cost Limit details are displayed twice on the certificate page. This removes the incorrect second occurrence from the merits CYA partial.
> AP-2647 Remove duplicate Emergency Cost Limit section

- helm_deploy/apply-for-legal-aid/templates/cronjob-admin-report.yaml
- helm_deploy/apply-for-legal-aid/templates/cronjob-destroy-purgeable.yaml
- helm_deploy/apply-for-legal-aid/templates/cronjob-export-digest.yaml
- helm_deploy/apply-for-legal-aid/templates/cronjob-extract-digest.yaml
- helm_deploy/apply-for-legal-aid/templates/cronjob-mark-purgeable.yaml
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2806)
Where jobs where being retained, revert to 0 for successful and 1 for failed
this should reduce the memory of storing superflouous success pods and allow
debugging from the last failed one …
> AP-2806: Reset cronjob limits

- app/models/attachment.rb
- app/models/document_category.rb
- app/validators/document_category_validator.rb
- config/locales/en/activemodel.yml
- spec/models/attachment_spec.rb
- spec/requests/providers/has_other_proceedings_controller_spec.rb
- spec/validators/document_category_validator_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2736)
The `Attachment` model previously validated attachment types based on a hard-coded enum in the model itself.
This means that there is a risk of the canonical list of document types being in several places in the code.
This PR fixes that by placing the list in the `DocumentCategoryValidator` class.
- created `DocumentCategoryValidator` class to validate `Attachment#attachment_type` and `DocumentCategory#name`
- Added scopes to the `Attachment` based on valid document types from `DocumentCategoryValidator` …
> AP-2736 attachment validation

- db/data/20220111135820_standardise_matter_types.rb
- db/data_schema.rb
- db/schema.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2802)
Proceeding records are now created from the response from LFA, and the name of the matter type differs slightly from those on the Proceeding Type records, so we had some Proceeding records with `Domestic abuse` or `Section 8 proceedings`,  and others with `Domestic Abuse` and `Children - section 8`.  This was causing problems in the application digest export to the dashboard.
This PR sets all matter type names on the Proceeding records to the LFA standard, and sets the digest extracted setting back to the beginning of Apply-time so that all digest records are re-generated. …
> AP-2802 Standardise Matter Type names on Proceeding rec

- app/views/providers/means_summaries/show.html.erb
- app/views/shared/check_answers/_no_employed_income.html.erb
- config/locales/en/shared.yml
- features/providers/employed_journey.feature
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2774)
- Adds a new partial to render a CYA block to display the solicitor's answer when no employment income is returned by HMRC.
- Updates the employed journey feature tests to include all steps up to the check your answers page.
- Hides all employment journey CYA changes behind the feature flag/firm permission as we don't want solicitors seeing them yet. …
> AP-2774 Display solicitor answers on CYA when no HMRC data exists

- Gemfile
- Gemfile.lock
Load from master - this has had a patch to handle aliased keys
that allows the Psych 4 update applied by Ruby 3.1
This should stop the overnight i18n tests from failing
> Fix: Update I18n-task gem

- app/jobs/reports_uploader_job.rb
- app/services/reports/mis/application_details_report.rb
- lib/tasks/jobs/create_admin_reports.rake
- spec/jobs/reports_uploader_job_spec.rb
- spec/services/reports/mis/application_details_report_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2827)
Several changes to ensure that we are alerted when an exception occurs during generation of reports overnight:
- Full test coverage of ReportsUploader job
- backgrounding of report generation rather than in the cronjob ephemeral pod
- Capturing exceptions and explicitly sending them to Sentry.  The exception is not re-raised because we don't particularly want the job to be retried lots of times.
- The PR description should say what …
> AP-2827 Capture exceptions during Report Generation

- app/services/hmrc/mock_interface_response_service.rb
- spec/services/hmrc/mock_interface_response_service_spec.rb
The `HMRC::MockInterfaceResponseService` does not set the `submission_id` on the `HMRC::Response` record. This causes the process to fail as the `submission_id` is used to subsequently update the `Response` with the correct json payload.
This changes the `MockInterfaceResponseService` so that it generates a `submission_id` uuid, and updates the `Response record` with it, in its initializer.
- You should …
> Fix mock HMRC data generation

- app/helpers/application_helper.rb
- app/views/providers/check_merits_answers/show.html.erb
- app/views/shared/forms/_list_items.html.erb
- app/views/shared/forms/_list_with_items.html.erb
- config/locales/en/providers.yml
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2764)
Update the bullet points on check_merits_answers to match the prototype
* Add new privacy policy bullet point with a clickable link
* Update share information text with contractions of OGDs
This adds a new helper method and partial to handle a single bullet point with clickable text
The current list  helper/partial could not handle _any_ html values  …
> AP-2764: Update check_merits_answers confirmation bullet points

- app/models/cfe/v4/result.rb
- spec/factories/cfe_results/v4/mock_results.rb
- spec/factories/proceedings.rb
- spec/models/cfe/v4/result_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2813)
Updates v4 of the CFE `Result` model to replace a reference to the deprecated `ProceedingType` model with `Proceeding`. Also updates tests, factories and fixtures. …
> AP-2813 Remove ProceedingType from CFE Result v4

- app/services/hmrc/create_responses_service.rb
- spec/services/hmrc/create_responses_service_spec.rb
The original used Rails.env.production?  but that is always set
because it is set in the Dockerfile.  This uses HostEnv to allow
checking for any environment except production
> Fix: Update Mock HMRC data

- Gemfile
- Gemfile.lock
These were blocking each other (and everything) in the dependabot PRs
Sidekiq-status wouldn't update because i18n had been withdrawn and vice-versa
Also import other dependabot updates from today to reduce rebases needed …
> Fix: Update sidekiq-status and i18n - group other gem updates

- app/controllers/providers/submitted_applications_controller.rb
- app/views/providers/submitted_applications/_employment_income_table.html.erb
- app/views/providers/submitted_applications/show.html.erb
- config/locales/en/providers.yml
- spec/requests/providers/submitted_applications_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2576)
Adds a new partial to display income from employment on the certificate page. This is only displayed if the feature flag is on, the solicitor has permission, and employment data exists. If this is the case the name of the subsequent section is changed from 'Income' to 'Other income'.
Also adds tests. We don't test many of the other components on that page but it felt useful to have them to ensure that the display logic was working correctly. These can be removed/reduced if it seems unnecessary.  …
> AP-2576 Add employment data to certificate

- app/views/providers/capital_income_assessment_results/_employment_income.html.erb
- app/views/providers/capital_income_assessment_results/_other_income.html.erb
- app/views/providers/capital_income_assessment_results/_result_details.html.erb
- config/locales/en/providers.yml
- spec/requests/providers/capital_income_assessment_results_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2575)
Add ‘Employment income' section to the 'Income calculation’ accordion on the CFE results page and populate with results data from CFE.
Fix a couple of failure points on mock_interface_response_service.rb to allow for testing. …
> ap-2575: Add employment income to cfe results page

- app/views/providers/no_employment_incomes/show.html.erb
- config/locales/en/providers.yml
[Link to story](https://dsdmoj.atlassian.net/jira/software/c/projects/AP/boards/233?modal=detail&selectedIssue=AP-2779)
Update the content on the page where the provider has said their client is employed but HMRC returns no data.
Removed the line ‘A caseworker will ask for evidence of this’ and added the hint: "You'll need to upload supporting evidence later." under the heading "Enter your client’s employment details:" …
> Make changes to content on HMRC 'no data' page

- .circleci/config.yml
- .github/workflows/ci-docker-image.yml
- docker/apply_ci.dockerfile
Create a new `apply-ci.dockerfile`, this replaces steps in the CircleCI jobs that were taking minutes for each job to pull down and install the same packages
Create a new Github Action that will build and push an image from the new dockerfile to dockerhub on a daily basis, but should be amended to weekly when we are happy with the stability
Switch CircleCI to use the new image from dockerhub and remove the jobs that were no longer needed …
> Fix: Use new docker image for tests

- config/locales/cy/generic.yml
- features/citizens/citizens_welsh.feature
- features/step_definitions/citizens_steps.rb
Update the welsh language feature tests
* Ensure they render with proper labels for the language switcher helper
* Ensure each feature switches back to English at the end of the test, this prevents the locale leaking into subsequent feature tests …
> Fix: Welsh language features

- config/locales/en/providers.yml
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2865)
Updates the hint text on the statement of case and evidence upload pages, bringing it in line with the prototype and  including a list of valid file types. …
> AP-2865 Update hint text on file upload pages

- .circleci/config.yml
- spec/spec_helper.rb
Now that the rspec tests are running in parallel, we no longer need the I18n tests to behind a flag, also we don't need the full test suite to run overnight
> Fix: Remove overnight test run

- app/webpack/src/dropzone.js
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2878)
Trigger the page reload after the `queuecomplete` event
Success was being triggered after a successful upload, even if more jobs were on the queue.  Chrome handled this more gracefully than firefox and others, but I'm not sure it was the right way! …
> AP-2878: Update dropzone handling

- helm_deploy/apply-for-legal-aid/templates/cronjob-admin-report.yaml
The cronjob is _not_ completeing successfully but the cronjob container thinks it has 🤷‍♂️ 
Also, there is nothing in kibana to show what is happening so this update retains one successful job so we can read the logs the next morning …
> Debug: Admin-report

- .circleci/config.yml
- Gemfile
- Gemfile.lock
- app/controllers/concerns/providers/authorizable.rb
- spec/services/hmrc/mock_interface_response_service_spec.rb
Try and reduce some noise in the test outputs 
The Sprocket warnings are part of the RailsAdmin gem and are addressed in an upcoming v3 release that switches to webpacker and, therefore, removes the sprockets noise …
> LND: Test tidy

- app/services/flow/flows/provider_merits.rb
- spec/helpers/providers_helper_spec.rb
- spec/requests/providers/application_merits_task/date_client_told_incidents_spec.rb
[Link to story](https://dsdmoj.atlassian.net/jira/software/c/projects/AP/boards/233?modal=detail&selectedIssue=AP-2885)
Flow::FlowError: :path of step :date_client_told_incidents is not defined" was being raised in Sentry. After investigations, this is raised when the user clicks Save and come back later on the 'Latest incident details' page. When they click on applicant name to continue the application they are then unable to progress the application, as they are taken to the applicant details page rather than the latest incident details page (resulting in a further 'enter_applicant_details' cannot transition from 'provider_entering_merits' sentry error)
I noticed that the same issue was affecting the chances_of_success page so I have also added a path to this step.
- Added path to …
> ap-2885: add path to date_client_told_incidents path step

- app/controllers/providers/uploaded_evidence_collections_controller.rb
- app/controllers/v1/uploaded_evidence_collections_controller.rb
- app/forms/providers/uploaded_evidence_collection_form.rb
- app/forms/providers/uploaded_evidence_submission_form.rb
- app/models/legal_aid_application.rb
- app/models/uploaded_evidence_collection.rb
- app/services/required_document_category_analyser.rb
- app/validators/document_category_validator.rb
- app/views/providers/uploaded_evidence_collections/_upload_evidence.html.erb
- app/views/providers/uploaded_evidence_collections/_uploaded_files.html.erb
- app/views/providers/uploaded_evidence_collections/show.html.erb
- config/locales/en/activemodel.yml
- config/locales/en/providers.yml
- db/seeds/document_categories.csv
- spec/models/document_category_spec.rb
- spec/requests/providers/uploaded_evidence_collection_spec.rb
- spec/requests/v1/uploaded_evidence_collections_spec.rb
- spec/services/required_document_category_analyser_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2739)
Adds validation to the evidence upload screen. This takes two forms: validation of individual files (for file format, malware, etc), which is done at upload time, and validation that evidence meets requirements (ie all files have been categorised and all mandatory evidence types have at least one file categorised), which is done on submission of the form.
To implement this properly it was necessary to add `employment_evidence` as a document type, make changes to the view to dynamically display which benefits the applicant receives, and refactor the delete button functionality to remove conflicts between submitting/deleting files.
NOTE: This doesn't completely achieve everything on the ticket - errors are rendered at the top of …
> AP-2739 Evidence upload validation

- app/views/providers/employment_incomes/show.html.erb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2877)
When Tax or National Insurance values on the Employment Income Review screen have more then five significant digits they exceed the column width and wrap incorrectly.
1. Update `app/views/providers/employment_incomes/show.html.erb` so that the widths of the table header columns match the widths of the table body columns. This improves the amount of space available for the data.
2. Add the `govuk-table__cell--numeric` class to Income and Deductions values to bring them into line with other monetary values in the service, and also with the prototype design.
- Github should not be reporting conflicts; you should have recently run `git …
> AP-2877 Employment data alignment

- app/controllers/providers/client_completed_means_controller.rb
- app/views/providers/client_completed_means/show.html.erb
- config/locales/en/providers.yml
- spec/requests/providers/client_completed_means_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2927)
After the applicant has supplied bank details, the provider continues the financial assessment.  At the beginning of that, there is a page which shows a numbered list of the things still to do.  Included in that list was the step to enter employment details, shown regardless of whether or not the applicant is employed.  
This PR removes that for applicants who are not employed. …
> AP-2927 Do not display check employment details for unemployed

- app/services/cfe/create_employments_service.rb
- spec/services/cfe/create_employments_service_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2866)
When making a CFE submission for an applicant that is employed but is not found in the HMRC API, the parsing of the HMRC Response fails.
This is caused by a check in the CreateEmploymentsService which assumes that if an applicant is employed then they will have HMRC data; this will not always be the case.
This replaces the call to `legal_aid_application.employed?` in the guard before processing the response with
`legal_aid_application.hmrc_employment_income?` which ensures that we only try to parse employment data when the data actually exists.
- Github should not be reporting conflicts; you should have recently run `git rebase …
> AP-2866 Parse HMRC Responses with no employments

- app/services/cfe/create_employments_service.rb
- app/views/providers/means_reports/show.html.erb
- app/views/providers/means_summaries/show.html.erb
- app/views/shared/check_answers/_no_employed_income.html.erb
- spec/requests/providers/means_reports_spec.rb
- spec/services/cfe/create_employments_service_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2891)
Update the caseworker means report to display full employment income information entered by the solicitor when no data is returned for the applicant by the HMRC API. …
> AP-2891 Display employment income data on means report when no HMRC data exists

- app/models/legal_aid_application.rb
- app/services/manual_review_detailer.rb
- app/services/results_panel_selector.rb
- spec/models/legal_aid_application_spec.rb
- spec/services/manual_review_detailer_spec.rb
- spec/services/results_panel_selector_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2950)
* Adds a new method to the `LegalAidApplication` model to returns a boolean value indicating whether _any_ employment income data has been manually entered by the provider. This returns true if either `extra_employment_information` is true or `full_employment_details` contains data.
* Amends the `ManualReviewDetailer` service class to use that method to determine whether casworker review is required.
* Amends the `ResultsPanelSelector` service class to use that method to determine the correct result panel to display. …
> AP-2950 Include all manually entered employment income data for result panel/caseworker reviews

- app/views/problem/index.html.erb
- config/locales/cy/errors.yml
- config/locales/en/errors.yml
- spec/requests/problem_spec.rb
Improves the wording of the error page displayed when calls to DWP fail, adding a reference to using CCMS.
> Update Benefit Checker failure page

- helm_deploy/apply-for-legal-aid/templates/deployment_web.yaml
Return clamav image to older version as the new one broke deployments
> Fix: Update clamav docker image

- app/views/accessibility_statement/index.html.erb
- config/locales/cy/accessibility_statement.yml
- config/locales/en/accessibility_statement.yml
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2765)
Remove text that says page titles do not conform to accessibility guidelines - they are no longer an issue
> AP-2765 update accessibility statement

- .github/workflows/ci-docker-image.yml
Add a workflow-dispatch option for manual triggering
Update docker tag to add a label with the current ruby version appended
> Tech-debt: Update docker cli action

- .github/workflows/ci-docker-image.yml
The previous invocation of workflow_disptach caused an error
Try changing to a symbol even though no instructions follow it
> Fix: Docker image job

- .github/workflows/ci-docker-image.yml
The previous push command pushed a specific tag, `latest`,
removing the tag should push both tagged versions from
the github container, i.e. latest & latest-ruby-version
> Fix: Docker build action

- app/views/providers/application_merits_task/statement_of_cases/_show_new.html.erb
- app/views/providers/uploaded_evidence_collections/_upload_evidence.html.erb
- app/webpack/src/dropzone.js
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2974)
- Fixed the validation errors so that the correct error is displayed if there is a second error (on second upload)
- The errors are hidden if a valid file is then uploaded
- Fixed on both evidence upload and statement of case page
- Moved the code to hide error messages into a separate function, and called this function on the 'drop' event and on the 'Choose files' click event
- Added a new accepted document type that supports MS Word 2007 files  …
> AP-2974 fix validation errors not appearing the second time

- docker/run
This should prevent the new ruby from pushing the proposals
in the rails console when working on remote containers
> Fix: Remove IRB prompts in docker containers

- app/views/providers/legal_aid_applications/_legal_aid_applications.html.erb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2979)
Increase padding around buttons on dashboard
> AP-2979 increase padding around buttons on dashboard

- app/views/layouts/_header.html.erb
- app/views/shared/_provider_header_link.html.erb
- app/webpack/stylesheets/layout.scss
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2931)
The links on the right of the header were misaligned. Now they are aligned with the rest of the header
> AP-2931 fix header nav links

- spec/models/legal_aid_application_spec.rb
In `spec/models/legal_aid_application_spec.rb` we test the output of `uploaded_evidence_by_category`, which is a hash of arrays. The elements of those arrays are not always populated in the same order, which causes a test to fail. 
This adds a `deep_match` method (shamelessly stolen from https://github.com/ministryofjustice/check-financial-eligibility/pull/826/commits/bd67f5f18032da34bc3a18dd834e77cbca09cccd) which allows for comparison of nested data structures and updates the test to use it. …
> Fix flaky rspec array comparison

- app/models/dashboard/widget_data_providers/pending_ccms_submissions.rb
- spec/models/dashboard/widget_data_providers/pending_ccms_submissions_spec.rb
[We implemented a state of `abandoned` so we could track submissions that we manually excluded from continuing, but did not exclude them from the widget.  Therefore they would perpetually appear on the queue without this fix …
> Fix: Update CCMS Submission geckoboard widget

- scripts/db_export.sh
The changes to step 2 make it quieter and allows the user to
copy and paste the third instruction without having to
scroll paste all the `drop` outputs
The changes to step 3 remove the reference to `staging`
as that was inappropriate and confusing! …
> Update the database restore instructions

- output.sarif.json
- spec/spec_helper.rb
Allows running individual examples, contexts
or describes using `f...`.
example
```
fit 'is a test' do
end
```
```
rspec
=> runs just the `fit` test
```
One way I like to run specific specs or groups of specs.
> Allow use of focused spec running

- spec/services/hmrc/mock_interface_response_service_spec.rb
Fix a couple of rubocop violations that snuck into `main`
`Style/TrailingCommaInArrayLiteral` and
`Style/QuotedSymbols`. Came in from govuk-rubocop
recently i guess?!
> Fix couple of rubocop violations

- Gemfile
- Gemfile.lock
The Gem itself has already been updated to 8.x so
having this locked at >7 seems superflouous
> Tech-debt: Update DataMigrate gem reference

- README.md
During a github change a few months ago the CC integration was refreshed.  I think that broke the links here, so this updates the guids for the badges
> Tech-debt: Update the code climate badges

- app/helpers/hash_format_helper.rb
- app/views/admin/legal_aid_applications/submissions/show.html.erb
- spec/helpers/hash_format_helper_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3024)
* Improve handling of remarks - the array of GUIDs returned by CFE for remarks broke the logic of the hash loop this ensures that a hash is rendered the same as before, but anything else will be treated as a string and output simply
* Improve handling when a CFE Result is missing, this is an edge case but occurred while working on debugging the issue.  It should never occur in production but will ensure the page does not crash if it does …
> AP-3024: Improve admin CFE display

- .circleci/config.yml
Only log in to Docker when required. 
Prevent failed log ins blocking the pipeline when Docker log in is not required.
> Fix CircleCi Build

- spec/zeitwork_spec.rb
This is not strictly necessary for CI hosted test suite runs
due to rails 6/7 default behaviour of eager loadong during test 
suite run on envs with ENV['CI'] set, including circleci. This would
resut in an eager load error being raised regardless.
However this test would fail locally or anywhere if the app is not zeitwork compliant
explictly and is recommended particulalry for rails migrations/bumps.
see https://edgeguides.rubyonrails.org/classic_to_zeitwerk_howto.html#check-zeitwerk-compliance-in-the-test-suite
for more.
- There should be no unnecessary whitespace changes. These make diffs harder to …
> Add explicit check for zeitwork compliance

- .rubocop_todo.yml
- spec/forms/legal_aid_applications/shared_ownership_form_spec.rb
- spec/models/application_merits_task/involved_child_spec.rb
- spec/models/bank_account_spec.rb
- spec/models/cfe/v2/result_spec.rb
- spec/models/cfe/v3/result_spec.rb
- spec/models/cfe/v4/result_spec.rb
- spec/models/firm_spec.rb
- spec/models/host_env_spec.rb
- spec/models/legal_aid_application_spec.rb
- spec/models/legal_framework/serializable_merits_task_spec.rb
- spec/models/transaction_type_spec.rb
- spec/requests/admin/roles_spec.rb
- spec/requests/providers/applicant_employed_spec.rb
- spec/requests/providers/application_merits_task/statement_of_case_spec.rb
- spec/requests/providers/capital_assessment_results_spec.rb
- spec/requests/providers/capital_income_assessment_results_spec.rb
- spec/requests/providers/check_provider_answers_spec.rb
- spec/requests/providers/legal_aid_applications_spec.rb
- spec/requests/providers/offline_accounts_spec.rb
- spec/requests/providers/savings_and_investments_spec.rb
- spec/services/ccms/requestors/case_add_requestor_xml_blocks/non_passported_entities_spec.rb
- spec/services/ccms/requestors/case_add_requestor_xml_blocks/non_passported_variable_attributes_spec.rb
- spec/services/ccms/requestors/case_add_requestor_xml_blocks/passported_attributes_spec.rb
- spec/services/ccms/submitters/add_applicant_service_spec.rb
- spec/services/ccms/submitters/add_case_service_spec.rb
- spec/services/ccms/submitters/check_applicant_status_service_spec.rb
- spec/services/ccms/submitters/check_case_status_service_spec.rb
- spec/validators/document_category_validator_spec.rb
Fix GOVUK Rubocop RSpec/ExcessiveDocstringSpacing offences.
"RSpec/ExcessiveDocstringSpacing: Excessive whitespace. (https://www.rubydoc.info/gems/rubocop-rspec/RuboCop/Cop/RSpec/ExcessiveDocstringSpacing)"
> Fix GOVUK Rubocop RSpec/ExcessiveDocstringSpacing offences

- app/controllers/providers/full_employment_details_controller.rb
- app/models/hmrc/response.rb
- app/models/legal_aid_application.rb
- spec/factories/hmrc/responses.rb
- spec/models/hmrc/response_spec.rb
- spec/models/legal_aid_application_spec.rb
- spec/requests/providers/full_employment_details_controller_spec.rb
[Link to story](https://dsdmoj.atlassian.net/jira/software/c/projects/AP/boards/233?modal=detail&selectedIssue=AP-3026)
When there is a pending response from HMRC: 
-display full employment details screen
-send a message to Sentry containing the correlation id
Also improve tests for full employment details controller by testing correct rendering of full employment details screen. …
> Ap 3026 handle pending HMRC response

- lib/tasks/employ.rake
Enable rake employ for all but production
Simplifies set for employment journey testing
on non-prod
> enable employed journey on all but production via cli

- bin/uat_deploy
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2853)
Updated the uat_deploy script to remove the `LEGACY_RELEASE_HOST` value and leave the `ingress.hosts` value as an array to avoid refactoring the `ingress.yaml` file and leave us able to add further hosts in the future if needed
- …
> AP-2853: Remove legacy ingress values

- .circleci/config.yml
There was a missed, legacy, ENV_VAR in the staging deploy job, this removes it 
> Fix: remove legacy env var name from staging job

- .circleci/config.yml
- bin/delete_uat_release
- bin/uat_deploy
- helm_deploy/apply-for-legal-aid/README.md
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2198)
Update CircleCI config
* create a new context for uat in circleci with values required for UAT namespace access
* refactor K8S_UAT_NAMESPACE calls to use K8S_NAMESPACE, the same as staging and prod
* Update the circleci uat jobs to use `context: laa-apply-for-legalaid-uat` and import the new values
* Update the dockerhub scripts to ensure that new test images can be created …
> AP-2198: Update Circle CI UAT variable handling

- app/models/host_env.rb
- features/support/env.rb
- spec/lib/omni_auth/hmrc_spec.rb
- spec/services/hmrc/interface/result_service_spec.rb
- spec/services/hmrc/interface/submission_service_spec.rb
What: fix
Why: Reduce CodeQL warnings
How:
* Update the regex handling stub requests in submission_service_spec
> Tech-Debt: Address CodeQL issues

- app/models/hmrc/response.rb
- app/services/hmrc/mock_data/unknown_response.json.erb
- app/services/hmrc/parsed_response/persistor.rb
- app/services/hmrc/parsed_response/validator.rb
- features/providers/employed_journey.feature
- features/step_definitions/civil_journey_steps.rb
- spec/factories/hmrc/responses.rb
- spec/factories/legal_aid_applications.rb
- spec/models/hmrc/response_spec.rb
- spec/models/legal_aid_application_spec.rb
- spec/requests/providers/employed_incomes_spec.rb
- spec/services/hmrc/parsed_response/persistor_spec.rb
- spec/services/hmrc/parsed_response/validator_spec.rb
Use validator "service" object for HMRC response
Used to determine whether employment records can be created from
the HMRC response.
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3028)
> [AP-3028] handle HMRC unexpected responses

- helm_deploy/apply-for-legal-aid/templates/cronjob-admin-report.yaml
The cronjob that generates the admin report each night is failing, suspected out of memory
This PR increasese the memory of the cronjob pod that runs that job
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2953) …
> AP-2953 Increase memory allocation for admin report generation

- app/services/hmrc/parsed_response/validator.rb
- spec/services/hmrc/parsed_response/validator_spec.rb
Do not validate on HMRC response first name attribute
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3062)
HMRC response could have supplied a slightly different firstname.
For example, one including a middlename has been seen. …
> Do not validate hmrc_response for first name match

- helm_deploy/apply-for-legal-aid/templates/cronjob-admin-report.yaml
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2953)
this is the second attempt to increase the resource sizes of this cronjob so that it
runs to completion.
The timing of the jobs has also been increased so that it runs several times throughout the
day enabling us to see whether this has been effective without waiting overnight.  If successful,
it will be set back to one overnight run again.
- …
> AP-2953 increase resources for admin_report crontab

- app/services/hmrc/parsed_response/validator.rb
- spec/services/hmrc/parsed_response/validator_spec.rb
Validate for and alert on HMRC responses with missing employments
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3064)
HMRC can potentially return internal server errors
which can result in the employments not being available.
This results in no employments being persisted and therefore
users having to enter these details manually
In such instances we want to capture the error and alert
ourselves to the problem so we can investigate. …
> [AP-3064] Validate and alert for missing employments

- app/views/providers/employment_incomes/show.html.erb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3042)
Re-factor the employment_income error display - move the radio buttons into a govuk_radio_buttons_fieldset this then, correctly, handles the expected error display …
> AP-3042: Update employment_income error display

- app/views/providers/open_banking_consents/show.html.erb
- config/locales/en/providers.yml
- spec/requests/providers/open_banking_consents_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3059)
On the banking consents page, it displayed three bullet points, the third of which said that the provider agreed that the applicant was not employed.  This change is to remove that if the applicant is employed, and only display it when not employed. …
> AP-3059 Omit third bullet point for employed applicants

- app/webpack/src/dropzone.js
This was a spike ticket investigating the styling/removal of the file preview animation in dropzone.
This PR is just to disable the preview for now.
See ticket for further info and link to design ticket for potentially presenting a more GOV.UK style preview in the future …
> AP-2924 disable previews in dropzone

- Gemfile
- Gemfile.lock
SimpleCommand has been poorly maintained in the past and gem releases have been few and far between leaving users reliant on the main github branch ([see comments from September 2020!](https://github.com/ministryofjustice/laa-apply-for-legal-aid/commit/8a9c6f1529aff5b02746156bc77f12f615c956df)).
New versions have been released, so this reverts to loading gem versions and manually updates to the latest release …
> Tech-debt: Update simple_command gem loading

- app/services/hmrc/parsed_response/validator.rb
- spec/services/hmrc/parsed_response/validator_spec.rb
Do not validate on first or last name, only nino and dob
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3062)
Avoid mismatches resulting from unusual
names and spelling mistakes either by our
users or in HMRC records.
We want some level of validation so we can
be confident our request of HMRC results in
a response for the individual/applicant entered
in our system. We have decided as a team (CB/JS/SR)
that the unique nature of a nino coupled with a date
of birth should suffice to give us warning of inappropriate
responses from HMRC. …
> [AP-3062] Do not validate on first or last name

- app/jobs/reports_uploader_job.rb
- app/services/reports/mis/application_details_report.rb
- spec/jobs/reports_uploader_job_spec.rb
- spec/services/reports/mis/application_details_report_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3065)
The cronjob that runs the ReportsUploaderJob to create the admin report CSV
file and attach it to the AdminReport record is failing silently, we think because
the contab pod is running out of memory (The whole CSV file is created in memory).
This change refactors it to output the data line by line to a temporary file, and
then attach that file to the AdminReport record
- The PR description should say what you changed and why, with …
> AP-3065 Refactor Admin Report creation to use temporary file

- package.json
- yarn.lock
Reduce the security alerts by removing the manual resolution of node-forge at 0.10.0 
And allowing yarn install to update to the latest version
It was [added to resolve](https://github.com/ministryofjustice/laa-apply-for-legal-aid/pull/1819) earlier warnings …
> Fix: node-forge yarn security warnings

- config/initializers/secure_headers.rb
Allow localhost running versions of our APIs to connect via JS.
Without this config change javascript search for proceeding types
does not function when LFA is running on localhost, at least.
example error when inspect proceedings select page from chrome console
```
Refused to connect to 'http://localhost:4001/proceeding_types/searches' because it violates the following Content Security Policy directive: "connect-src 'self' www.google-analytics.com *.justice.gov.uk".
``` …
> Allow localhost for content security policy

- app/services/reports/mis/application_details_report.rb
- helm_deploy/apply-for-legal-aid/templates/cronjob-admin-report.yaml
- lib/tasks/jobs/create_admin_reports.rake
- spec/services/reports/mis/application_details_report_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3065)
Recen change to create CSV in tempfile and attach that hasn't worked - jobs are still failing silently.  This change is to retain the cron job pods so that we can look at the logs and see what went wrong. …
> AP-3065 Retain cron pods so we can examine logs

- helm_deploy/apply-for-legal-aid/templates/.dashboard_template_cron.yaml.sample
- helm_deploy/apply-for-legal-aid/templates/cronjob-admin-report.yaml
- helm_deploy/apply-for-legal-aid/templates/cronjob-db-backup-cleanup.yaml
- helm_deploy/apply-for-legal-aid/templates/cronjob-deliver-scheduled-mail.yaml
- helm_deploy/apply-for-legal-aid/templates/cronjob-destroy-purgeable.yaml
- helm_deploy/apply-for-legal-aid/templates/cronjob-export-digest.yaml
- helm_deploy/apply-for-legal-aid/templates/cronjob-extract-digest.yaml
- helm_deploy/apply-for-legal-aid/templates/cronjob-hourly-db-backup.yaml
- helm_deploy/apply-for-legal-aid/templates/cronjob-mark-purgeable.yaml
- helm_deploy/apply-for-legal-aid/templates/cronjob-metrics.yaml
- helm_deploy/apply-for-legal-aid/templates/cronjob-reset-dashboard-overnight.yaml
We had started to see deprecation warnings when deleting Helm charts `batch/v1beta1 CronJob is deprecated in v1.21+, unavailable in v1.25+; use batch/v1 CronJob` 
This should update all cronjobs, remove the warnings and ensure the system remains future proof …
> Fix: Update Cronjob api version

- .rubocop_todo.yml
- spec/services/ccms/requestors/applicant_add_requestor_spec.rb
- spec/services/ccms/requestors/applicant_add_status_requestor_spec.rb
- spec/services/ccms/requestors/applicant_search_requestor_spec.rb
- spec/services/ccms/requestors/case_add_requestor_spec.rb
- spec/services/ccms/requestors/case_add_status_requestor_spec.rb
- spec/services/ccms/requestors/document_id_requestor_spec.rb
- spec/services/ccms/requestors/document_upload_requestor_spec.rb
- spec/services/ccms/requestors/reference_data_requestor_spec.rb
- spec/services/true_layer/api_client_spec.rb
- spec/services/true_layer/bank_data_import_service_spec.rb
- spec/services/true_layer/banks_retriever_spec.rb
- spec/services/true_layer/importers/import_account_balance_service_spec.rb
- spec/services/true_layer/importers/import_account_holders_service_spec.rb
- spec/services/true_layer/importers/import_accounts_service_spec.rb
- spec/services/true_layer/importers/import_provider_service_spec.rb
- spec/services/true_layer/importers/import_transactions_service_spec.rb
- spec/services/true_layer_error_decoder_spec.rb
- spec/services/use_ccms_arbiter_spec.rb
- spec/support/shared_context/ccms_soa_configuration_context.rb
- spec/support/shared_examples/cfe_failures_shared_examples.rb
- spec/support/shared_examples/legal_framework_failures_shared_examples.rb
- spec/validators/document_category_validator_spec.rb
- spec/workers/ccms/submission_process_worker_spec.rb
- spec/workers/hmrc/result_worker_spec.rb
- spec/workers/hmrc/submission_worker_spec.rb
- spec/workers/import_bank_data_worker_spec.rb
Fix GOVUK Rubocop RSpec/ContextWording offences.
Start context description with 'when', 'with', 'without', 'and', or 'but'. (https://rspec.rubystyle.guide/#context-descriptions, https://www.rubydoc.info/gems/rubocop-rspec/RuboCop/Cop/RSpec/ContextWording) …
> Rubocop fixes

- config/initializers/rack_attack.rb
It was expecting all submissions to have a body comprised of a string - when uploading files the filetype changes
This checks that the body is a string before checking for text values
> Fix: Rack Attack blocking

- app/views/providers/submitted_applications/show.html.erb
- config/locales/en/providers.yml
Added a print button to the Submitted Application Page
> Fix: Add print button to Submitted Application page

- app/services/reports/mis/application_details_report.rb
- helm_deploy/apply-for-legal-aid/templates/cronjob-admin-report.yaml
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3065)
Now that we have found the reason why the admin report was failing, and fixed it, we can remove some of the debugging and revert back to generating the report just once per day …
> AP-3065 Remove debugging and multiple runs per day

- app/services/use_ccms_arbiter.rb
- spec/services/use_ccms_arbiter_spec.rb
Refactor tests to provide a clearer logical breakdown of passported and non-passported scenarios. 
> Refactor tests

- app/controllers/providers/confirm_dwp_non_passported_applications_controller.rb
- spec/requests/providers/confirm_dwp_non_passported_applications_spec.rb
Remove the correct_dwp_result? check from the make_hmrc_call? method
This was an oversight as the HMRC call should be made if the client is employed regardless of the providers response to the DWP result check question …
> Fix: Update HMRC::CreateResponseService invocation

- .rubocop_todo.yml
- spec/factory_specs/legal_aid_application_factory_spec.rb
- spec/factory_specs/v4/cfe_result_factory_spec.rb
- spec/forms/outstanding_mortgage_form_spec.rb
- spec/forms/providers/application_merits_task/involved_child_form_spec.rb
Fix GOVUK Rubocop RSpec/ContextWording offences.
Start context description with 'when', 'with', 'without', 'and', or 'but'. (https://rspec.rubystyle.guide/#context-descriptions, https://www.rubydoc.info/gems/rubocop-rspec/RuboCop/Cop/RSpec/ContextWording) …
> Fix GOVUK Rubocop RSpec/ContextWording offences.

- app/models/application_digest.rb
- app/services/flow/flows/provider_capital.rb
- app/services/hmrc/status_analyzer.rb
- db/migrate/20220512125715_add_employed_field_to_digest.rb
- db/schema.rb
- features/step_definitions/civil_journey_steps.rb
- lib/tasks/digest.rake
- spec/factories/applicants.rb
- spec/factories/legal_aid_applications.rb
- spec/factories/permissions.rb
- spec/forms/applicants/employed_form_spec.rb
- spec/models/application_digest_spec.rb
- spec/requests/providers/applicant_employed_spec.rb
- spec/requests/providers/client_completed_means_spec.rb
- spec/services/digest_extractor_spec.rb
- spec/services/hmrc/status_analyzer_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3091)
- added three new boolean columns to the `application_digests` table to hold the extra information
- `employed`
- `hmrc_data_used`
- `referred_to_caseworker`
-  Created service class `HMRC::StatusAnalyzer` to give results about the state of the HMRC responses
- Refactored the `provider_capital` flow to use `HMRC::StatusAnalyzer` rather than nested `ifs`
- Used the `HMRC::StatusAnalyzer` to populate the `hmrc_data_used` column on `application_digests`
- Added trait `:with_employed_applicant` to `LegalAidApplication` factory, and used it in cucumber tests that now required it.
After this has been deployed, run the following command on live to reset the last-extracted date to ensure that all
existing records are updated.
`rake …
> AP-3091 Extra employment info on application Digest

- .circleci/config.yml
- bin/delete_dependabot_deployment
the delete script was failing to authenticate with the cluster after we updated the ENV_VARs
this PR fixes the issue by:
set a context for deleting depenadbot job in circleci
update the ENV_VAR use for the namespace …
> bugfix: update dependabot delete script

- features/providers/check_multiple_employment.feature
- features/providers/check_pending_employment.feature
- features/providers/check_single_employment.feature
- features/support/env.rb
- features/support/hooks.rb
This is merge into branch to fix failing cukes
Enable Mock HMRC calls during employed journey feature tests
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2640)
Employed journey tests are dependant on the
hmrc mock/sandobox data. This relies on a
config setting being in place and the test
were failing on CI as the mock was not enabled.
This stubs that config so feature tests can be run against it.
Should we be doing this however? We should, perhaps,
be using vcr to record (or otherise stub) real staging
hmrc responses - so long as no sensitive info is exposed. …
> [AP-2640 ]Add feature test hooks to mock hmrc calls

- app/lib/sidekiq/exhausted_failure_message.rb
- app/workers/pdf_converter_worker.rb
- spec/workers/pdf_converter_worker_spec.rb
Raise Sentry alerts only when 10 attempts have failed to convert a document to PDF.
Reduce the amount of errors raised so the key issues can be focused on.
[Link to story](https://dsdmoj.atlassian.net/jira/software/c/projects/AP/boards/233?modal=detail&selectedIssue=AP-2363) …
> AP-2363 Improve alerting around document conversion

- app/services/hmrc/parsed_response/validator.rb
- spec/services/hmrc/parsed_response/validator_spec.rb
[Link to story](https://dsdmoj.atlassian.net/jira/software/c/projects/AP/boards/233?modal=detail&selectedIssue=AP-3128)
Stop sentry alerting where HMRC has no re record of the client details
> ap-3128: Remove sentry alert where hmrc can't find client details

- app/views/shared/check_answers/_employed_income.html.erb
- app/views/shared/check_answers/_full_employment_details.html.erb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2959)
Removed right-alignment of the employment notes field on the means report, to bring it in line with GDS guidelines
> AP-2959 remove right alignment

- app/controllers/providers/limitations_controller.rb
- app/forms/legal_aid_applications/emergency_cost_override_form.rb
- app/models/legal_aid_application.rb
- app/views/providers/check_provider_answers/_shared.html.erb
- app/views/providers/limitations/_cost_limits.html.erb
- app/views/providers/limitations/_proceeding_types.html.erb
- app/views/providers/limitations/_proceeding_types_with_df.html.erb
- app/views/providers/merits_reports/show.html.erb
- app/views/shared/_review_application.html.erb
- app/views/shared/check_answers/_emergency_costs.html.erb
- app/views/shared/check_answers/_substantive_costs.html.erb
- config/locales/en/activemodel.yml
- config/locales/en/providers.yml
- config/locales/en/shared.yml
- db/migrate/20220527111338_add_cost_overrides.rb
- db/schema.rb
- features/accessibility/provider.feature
- features/providers/civil_application_journey.feature
- features/providers/cost_override.feature
- features/step_definitions/civil_journey_steps.rb
- features/support/screenshot_helper.rb
- spec/forms/legal_aid_applications/emergency_cost_override_form_spec.rb
- spec/models/legal_aid_application_spec.rb
- spec/requests/providers/check_provider_answers_spec.rb
- spec/requests/providers/limitations_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3167)
Extend the limitations handling to allow providers to override substantive cost limits if the value is below the maximum of £25k
> AP-3167: Allow change of substantive cost limits

- spec/models/cfe/remarks_spec.rb
Spec the ignoring of employment related bank transaction remarks
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3217)
These have been ignored to prevent a category mismatch error
from preventing generation of bank_transaction reports in a related
PR.
~~- [ ] add positive test for Transaction Id mismatch error~~ …
> [AP-3217] Specs for bank transaction employment remarks

- app/views/providers/declarations/show.html.erb
On the provider declaration page, change the home link to read back, to be consistent
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3120)
> AP-3120 change home link to back

- app/webpack/stylesheets/check-your-answers.scss
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3100)
Add break word property to stop text overflowing on check answers pages
> AP-3100 wrap text on cya pages

- app/views/shared/forms/_applicant_form.html.erb
- config/locales/cy/shared.yml
- config/locales/en/shared.yml
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3125)
Update applicant name field label to read 'Name' instead of 'Full name'
> Update applicant name field label

- config/locales/en/providers.yml
- features/accessibility/provider.feature
- features/providers/check_your_answers.feature
- features/providers/civil_application_journey.feature
- features/providers/deleting_applications.feature
- features/providers/merits_task_list.feature
- features/providers/pathways_from_check_your_answers.feature
- features/step_definitions/civil_journey_steps.rb
- features/step_definitions/cookie_steps.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3131)
Update heading on the dashboard page to read 'Applications' instead of 'Your applications'
> AP-3131 Update h1 on dashboard

- app/models/cfe/v4/result.rb
- spec/models/cfe/v4/result_spec.rb
Fix `undefined method any?' for nil:NilClass`
Seen against a CFE::V4::Result object in production
which did not have any `employment_income`
> Fix `undefined method `any?' for nil:NilClass`

- app/helpers/time_helper.rb
- app/views/providers/application_merits_task/date_client_told_incidents/show.html.erb
- app/views/providers/application_merits_task/involved_children/_form.html.erb
- config/locales/cy/shared.yml
- config/locales/en/providers.yml
- config/locales/en/shared.yml
- spec/helpers/time_helper_spec.rb
- spec/requests/providers/used_multiple_delegated_functions_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3126)
Update date hint text on a few pages:
- Delegated functions page - remove leading zero from month
- Involved children - add date hint text 
- Latest incident details - add hint text to occured_on field, and update told_on hint text to be today's date …
> AP-3126 update date hint text

- app/controllers/providers/provider_base_controller.rb
- app/controllers/providers/review_and_print_applications_controller.rb
- app/controllers/providers/submitted_applications_controller.rb
- app/models/cfe/base_result.rb
- spec/models/cfe/v1/result_spec.rb
- spec/models/cfe/v2/result_spec.rb
- spec/models/cfe/v3/result_spec.rb
- spec/models/cfe/v4/result_spec.rb
- spec/requests/providers/submitted_applications_spec.rb
Do not show employment income for applications with  CFE result of version 3 or less
[link to bug](https://dsdmoj.atlassian.net/browse/AP-3228)
- Promote `display_employment_income?` method
- Only checks `jobs?` for version 4+ CFE results
Handles [this specific sentry error](https://sentry.io/organizations/ministryofjustice/issues/3346747387/?project=5416054&query=is%3Aunresolved) seen in production.
The error arises from calling a non-existent method `jobs?`
on prior versions of CFE results. This can happen when a provider reviewing 
at a old submitted application and is likely to happen more as and when we role out
the employment journey to other providers …
> [AP-3228] Handle old CFE result for empoyment journey error

- app/services/hmrc/parsed_response/validator.rb
- spec/services/hmrc/parsed_response/validator_spec.rb
Fixes a false positive in the test
couple of test were not calling `call` the class before checking
whether the spy received message.
> Fix false positive

- app/services/hmrc/mock_data/no_employments.json.erb
- app/services/hmrc/mock_interface_response_service.rb
- app/services/hmrc/parsed_response/validator.rb
- spec/services/hmrc/parsed_response/validator_spec.rb
This is a pr to disable sentry alerting where HMRC returns that they have a record of the applicant, but no associated employments.
> Disable sentry alert when hmrc return no employments for applicant

- app/services/dashboard_event_handler.rb
- spec/services/dashboard_event_handler_spec.rb
This ensures that when we take the decision to abandon a CCMS submission the dashboard will update sooner. 
At the moment it waits until the next CCMS submission is kicked off before updating geckoboard or has to be manually triggered by a developer …
> Fix: Update the dashboard event handling for abandoning CCMS

- db/seeds.rb
This will automatically run `rake employ` as part of `rake db:reset` or `rake db:seed` in development environment
> Auto Set up employed journey when seeding in dev

- app/controllers/providers/client_completed_means_controller.rb
- app/controllers/providers/employment_incomes_controller.rb
- app/models/legal_aid_application.rb
- app/services/flow/flows/provider_capital.rb
- app/services/hmrc/mock_data/recently_employed.json.erb
- app/services/hmrc/mock_interface_response_service.rb
- app/services/hmrc/status_analyzer.rb
- app/views/providers/employment_incomes/show.html.erb
- features/providers/check_multiple_employment.feature
- spec/factories/applicants.rb
- spec/factories/employments.rb
- spec/models/legal_aid_application_spec.rb
- spec/requests/providers/employed_incomes_spec.rb
- spec/services/hmrc/status_analyzer_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3240)
In the above scenario, the provider should be told that's the case, shown the details and be given the opportunity to provide an explanation.  This has now been
fixed by:
- making it follow the not_employed journey only if the applicant is not employed AND there are no eligible employment payments (i.e. within the transaction period).
Changes
- new method `#employment_payments` added to `LegalAidApplication` to return all employment_payments from all employments
- new method '#eligible_employment_payments` added to `LegalAidApplication` to return only those employment payments which fall within the transaction period
- `HMRC::StatusAnalyzer` amended to add new return status `:unexpected_employment_data` in this case
- The …
> AP-3240 Unemployed applicant with HMRC employment income

- .circleci/config.yml
Over time, jobs have been moved, temp jobs added and removed, etc and the flow had got a bit disjointed.
This PR should 
* ensure that nothing is deployed until all build and test steps have successfully completed
* allow the hold production job to be run even if the slack notification has not yet been sent - being unable to deploy to prod because the slack API has failed would be bad! …
> Update: Refine circle merge workflow

- db/schema.rb
Update schema definition with timestamp precision defaults for rails 7
These change occur on any rails db:migrate following
the upgrade to rails 7.
see [issue](https://github.com/rails/rails/issues/44571) which
supposedly says precision 6 is default anyway. …
> Add rails 7 timestamp precision changes

- db/anonymise/rules.rb
Add rule to anonymise orginal_filename of attachments
This should be done to handle the edge case
where attachments can have PII in the name.
> Add fake attachment original name rule

- app/views/shared/_review_application.html.erb
call shared/irregular_incomes_table as when generated it was not finding it as just irregular_incomes_table
> Fix: Update review_application page

- app/helpers/application_helper.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3276)
- Remove deprecated class and replace with new class 
- Styling wasn't preserved so had to add a couple of other classes to style the link correctly
- This is a recommended change following the update to GOVUK Frontend 4.2
- You …
> AP-3276 remove deprecated header class

- app/models/uploaded_evidence_collection.rb
Bugfix
https://sentry.io/organizations/ministryofjustice/issues/3407948574/?project=5416054&referrer=slack
An error is being thrown when a user reaches uploaded evidence collection and they dont add mandatory evidence as the validation is looking for a benefit type, in this case the required evidence was for employment not benefits.
This change returns nil when a dwp_benefit override doesnt exist and subsequently the correct error is presented to the user
- The PR description should say what …
> add safe operator when checking for dwp_benefit type

- app/services/reports/means_report_creator.rb
- app/services/reports/merits_report_creator.rb
- app/views/providers/means_reports/show.html.erb
- app/views/providers/merits_reports/show.html.erb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3269)
Remove legacy invocation of instance variables and replace
with a line in the view that creates an instance variable is
not passed in.
This allows the instance variable to be used in all the nested
partials that require them, a ticket will be raised to address
this by switching the nested partials to not require an instance
version of the required …
> AP-3269: remove Rails 7 deprecation warnings

- app/views/providers/bank_statements/show.html.erb
- app/views/shared/means/_student_finances.html.erb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3337)
When the user does not upload a file on the bank statement upload page, they get an error. This error now displays on the dropzone as well as in the error summary, as expected. …
> AP-3337 display error on field when file is not uploaded

- app/forms/providers/bank_statement_form.rb
- app/webpack/src/dropzone.js
- config/locales/en/activemodel.yml
- config/locales/en/providers.yml
- spec/fixtures/files/sample_csv.csv
- spec/requests/providers/application_merits_task/statement_of_case_spec.rb
- spec/requests/providers/bank_statements_spec.rb
- spec/requests/v1/bank_statements_spec.rb
- spec/requests/v1/statement_of_cases_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3281)
Add csv to the allowed file types for bank statement for both JS and ruby solutions
Add tests to ensure that csv can be uploaded on bank_statement and not on statement _of_case …
> Ap 3281 add csv file type to bank_statement upload

- app/models/cfe/empty/result.rb
- app/services/ccms/attribute_value_generator.rb
- app/services/reports/reports_creator.rb
- spec/models/cfe/empty/result_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3278)
AP-3338 added a blank_cfe_result for bank_statement_upload cases
This ticket is to use that blank_cfe_result to get the means report working so that the application can be submitted to ccms.
The bank_statements will automatically be uploaded to CCMS as part of the document upload process. …
> Ap 3278 ccms submission

- app/views/admin/settings/show.html.erb
Fix bug with enabling miniloop on the admin settings page (where it was enabling the enable_cfe_v5 flag instead).
> Fix bug with miniloop settings page

- config/locales/en/providers.yml
- spec/services/ccms/manual_review_determiner_spec.rb
[Relates story](https://dsdmoj.atlassian.net/browse/AP-3386)
uploaded_bank_statements are raising a missing translation
error locally when displaying the means_report. This falls back to 
humanized key value on hosted envs. This fixes …
> Add missing translation for means reports

- app/controllers/providers/proceeding_loop/client_involvement_type_controller.rb
- app/forms/proceedings/client_involvement_type_form.rb
- app/services/flow/flows/provider_start.rb
- app/services/flow/proceeding_loop.rb
- app/services/legal_framework/add_proceeding_service.rb
- app/views/providers/check_provider_answers/_shared.html.erb
- app/views/providers/proceeding_loop/client_involvement_type/show.html.erb
- app/views/shared/check_answers/_client_involvement_type_details.html.erb
- app/views/shared/check_answers/_delegated_function_details.erb
- app/views/shared/check_answers/_proceeding_details.erb
- config/locales/en/activemodel.yml
- config/locales/en/providers.yml
- config/locales/en/shared.yml
- config/routes.rb
- features/cassettes/mini-loop/When_the_application_has_a_single_proceeding_and_I_m_going_to_use_delegated_functions.yml
- features/cassettes/mini-loop/When_the_application_has_a_single_proceeding_and_I_m_not_using_delegated_functions.yml
- features/cassettes/mini-loop/When_the_application_has_a_single_proceeding_and_I_m_using_delegated_functions.yml
- features/providers/mini-loop/multi_proceeding.feature
- features/providers/mini-loop/single_proceeding.feature
- spec/cassettes/ClientInvolvementTypeController/GET_/providers/applications/_legal_aid_application_id/client_involvement_type/_proceeding_id/when_the_provider_is_authenticated/displays_the_heading.yml
- spec/cassettes/ClientInvolvementTypeController/GET_/providers/applications/_legal_aid_application_id/client_involvement_type/_proceeding_id/when_the_provider_is_authenticated/returns_http_success.yml
- spec/cassettes/ClientInvolvementTypeController/POST_/providers/applications/_legal_aid_application_id/client_involvement_type/_proceeding_id/when_the_provider_is_authenticated/when_the_Continue_button_is_pressed/redirects_to_next_page.yml
- spec/cassettes/Proceedings_ClientInvolvementTypeForm/_save/when_the_client_involvement_type_submitted_is_valid/updates_the_proceeding.yml
- spec/forms/proceedings/client_involvement_type_form_spec.rb
- spec/requests/providers/in_scope_of_laspos_controller_spec.rb
- spec/requests/providers/proceeding_loop/client_involvement_type_controller_spec.rb
- spec/services/flow/proceeding_loop_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3359)
Add the Client Involvement Type page to the mini-loop, this allows the provider
to record the CIT for each proceeding before moving on to the next proceeding or exiting the loop …
> AP-3359: Add client involvement type to mini loop

- app/views/providers/means_summaries/show.html.erb
- app/views/shared/_review_application.html.erb
- app/views/shared/check_answers/_bank_statements.html.erb
- config/locales/en/shared.yml
- features/providers/check_your_answers.feature
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3378)
Add a bank statement section to the review_and_print page only visible if bank statements have been uploaded
Amend an existing partial to reuse it for the review page
Add some translations
fix an issue with a < / h 2 >  tag
- You …
> AP-3378 add bank_statement filenames to review page

- config/initializers/date_formats.rb
- spec/requests/providers/substantive_applications_spec.rb
The update to rails 7 removed the automatic conversion of dates to_s.  This meant that the default date format was not being applied and was falling back to YYYY-MM-DD
The hotfix applied means that we do not have to manually update each date with .to_fs any more …
> Fix: Date display

- spec/models/legal_aid_application_transaction_type_spec.rb
- spec/models/transaction_type_spec.rb
Moved scope specs to correct model class spec and replaced with specs that 
excercise the owning classes scopes.
Both transaction_types and legal_aid_application_transaction_types
have `.credits` and `.debits` scopes. The transaction_types model's
scopes were being tested in the legal_aid_application_transaction_types
specs and there were no specs excercising the expected behaviour of
the transaction_types model's scopes. I have added the later and moved
and rejigged the former.
- The PR …
> Move the credits and debits scope specs to correct class

- README.md
These updates were made with the intention of reducing confusion when onboarding
new developers to the project.
- Update referenced Rails version
- Remove postgres version
- Remove duplicate .env.test information
- Add `LOCAL_CLAMAV=true` to .env.test information
- Remove duplicate dev LAA portal authentication information
> Update README.md to improve clarity

- app/views/providers/means_summaries/_income_assessment.html.erb
- features/providers/check_your_answers.feature
Only display cash payments section if uploading bank statements
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3365)
**This is one solution** to handle the difference between the needs
of the non passported bank statement and trulayer journeys.
The banks statement journey will have no categorised bank transactions
so we just show Yes/No answers in the "What payments does your client receive/make?" 
sections. The "Payments your client receives/makes in cash" sections then display the 
monthly amounts entered per category.
The truelayer journey will have categorised bank transactions as well as
cash potentially. This is displayed as a £ total per Category or "None". The
"Payments your client receives/makes in cash" section is not shown because
cash is already included in the totals …
> [AP-3365] conditional display of cash payment CYA sections

- features/step_definitions/civil_journey_steps.rb
- features/step_definitions/evidence_upload_steps.rb
Increase maximum wait time for file upload
[Dev time discussion trello card](https://trello.com/c/2l9Y4JSo/125-flaky-file-attachment-feature-tests)
Several features using these tests are flaky
and previous increases in max wait time has
helped annecdotally. This change is to test
whether it wil further reduce flaky features. …
> Increase max wait time to attach a file

- spec/requests/feedbacks_spec.rb
Before, if the offending spec took longer than 10 seconds to make the first two
requests, the third request would be successful and the test would fail.
This is something I'd seen a few times, most recently [in this run].
[in this run]: https://app.circleci.com/pipelines/github/ministryofjustice/laa-apply-for-legal-aid/17300/workflows/6b49be0f-8c15-4eb0-98c3-d94ec84deeee/jobs/90881
This freezes time so the test will always pass, no matter how slow our CI test
suite is.
> Fix flaky rack-attack spec

- config/application.rb
Once upon a time in #933, we added the [blazer] gem.
Several years later, we removed the [blazer] gem in #2025.
We forgot to remove the `db_url` variable from the config though.
This removes the redundant config.
[blazer]: https://github.com/ankane/blazer
> Remove redundant blazer db_url config

- app/services/cfe/submission_manager.rb
- spec/services/cfe/submission_manager_spec.rb
While investigating a CFE issue, this caused me some issues. I have extracted the fix to it's own PR...
There was a test that was "passing" because the submission_manager failed and therefore the Service was never "called"
I deleted it so that it does not cause confusion and, complying with the commit message that added it, have removed the CreateCashTransactionsService one-off call and incorporated it into the NON_PASSPORTED_SERVICES array …
> Fix: Update CFE service calls

- app/controllers/providers/means/identify_types_of_incomes_controller.rb
- app/controllers/providers/means/identify_types_of_outgoings_controller.rb
- app/models/legal_aid_application_transaction_type.rb
- app/models/transaction_type.rb
- spec/factories/legal_aid_applications.rb
- spec/models/legal_aid_application_transaction_type_spec.rb
- spec/models/transaction_type_spec.rb
- spec/requests/providers/means/identify_types_of_incomes_controller_spec.rb
- spec/requests/providers/means/identify_types_of_outgoings_controller_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3368)
Remove Cash transactions for both income and outgoings when the corresponding payment category is removed
At the moment, if you have selected a payment category and entered cash payments for that category, if you return to the identify types of payments page and remove that category, the cash transactions are not removed and will still show up on the cash payments page and on the CYA page.
All cash transactions need to be removed when the payment category is removed. …
> [AP-3368] Remove cash payments once the category has been removed

- Gemfile
- Gemfile.lock
- spec/requests/errors_spec.rb
This project leans heavily on cucumber for feature tests, and we write **no**
RSpec system specs at all.
In my opinion this is quite unusual, and a side effect of this is that we use
RSpec request specs (which are a wrapper around
ActionDispatch::IntegrationTestCase) a lot to assert against the rendered
content.
This isn't necessarily a bad thing, since Rails integration tests can offer lots
of benefits over system tests (e.g speed, greater control over HTTP verbs and
this session etc).
While I think this combination makes it harder for us to do
accessibility-focussed test-driven development (Capybara and RSpec system specs
are excellent for this), that conversation is one for another day.
This proposed change makes use of an abstraction discussed at length in [this
blog …
> Add capybara support to integration tests

- app/views/citizens/accounts/index.html.erb
- app/views/providers/application_merits_task/has_other_involved_children/show.html.erb
- app/views/providers/bank_transactions/_list_selected.html.erb
- app/views/providers/check_client_details/show.html.erb
- app/views/providers/confirm_multiple_delegated_functions/show.html.erb
- app/views/providers/income_summary/_income_type_item.html.erb
- app/views/providers/means/employment_incomes/show.html.erb
- app/views/providers/outgoings_summary/_outgoing_type_item.html.erb
- config/locales/cy/citizens.yml
- config/locales/en/citizens.yml
- config/locales/en/providers.yml
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3197)
Added table captions to several tables throughout the service which were missing captions. 
All captions are visually hidden but will be read out by a screenreader. 
Also updated the remove-transaction links on the income summary/outgoings to be more descriptive  …
> AP-3197 Add table captions and make links descriptive

- Gemfile
- Gemfile.lock
- app/views/layouts/application.html.erb
- config/locales/cy/layouts.yml
- config/locales/en/layouts.yml
Pretty much every view in the application leans primarily on GOV.UK Design
System components.
This introduces the [govuk-components] gem to help us manage this complexity.
Rather than relying on copy-paste to ensure we render the design system
components accurately, we can render these resuable components. They are well
tested, customisable, and should reflect the design system accurately.
[govuk-components]: https://github.com/DFE-Digital/govuk-components
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3423)
> [AP-3423] - Add GovukComponents gem

- app/models/setting.rb
- db/migrate/20220830144657_remove_enable_employed_journey_from_settings.rb
- db/schema.rb
Before, in #4216, the `enable_employed_journey` setting was removed and the
associated column was ignored.
Now that change has been deployed successfully, we can safely remove the column
from the database table.
This removes the column from the settings table and removes the
`.ignored_columns` method defined in the Setting model.
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2637)
> Remove `enable_employed_journey` column from settings

- app/views/providers/proceeding_loop/client_involvement_type/show.html.erb
- app/views/providers/proceeding_loop/confirm_delegated_functions_date/show.html.erb
- app/views/providers/proceeding_loop/delegated_functions/show.html.erb
- app/views/providers/proceeding_loop/emergency_defaults/show.html.erb
- app/views/providers/proceeding_loop/emergency_level_of_service/show.html.erb
- app/views/providers/proceeding_loop/substantive_defaults/show.html.erb
- app/views/providers/proceeding_loop/substantive_level_of_service/show.html.erb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3409)
Update page and form layouts to improve accessibility of proceeding loop pages
- move headings into page template so error summary appears in the correct place at the top of the page
- ensure form fields are linked to the correct heading and question …
> AP-3409 Accessibility fixes for proceeding loop pages

- app/services/currency_cleaner.rb
- spec/validators/currency_validator_spec.rb
Before, when validating a currency that was `nil`, and the attribute was not allowed to be blank, an error was raised.
This amends the `CurrencyCleaner` class so that `nil` values are cast to an empty string, and the `spec/validators/currency_validator_spec.rb` is updated to account for this.
> Fix currency validation bug

- bin/setup
Replace npm with yarn in our setup script.
Yarn is predominately used throughout codebase, this change make it consistent  and stops conflicting/mixing of package and yarn lock files.
> Replace npm with yarn

- package.json
- yarn.lock
nth-check is vulnerable to Inefficient Regular Expression Complexity
**References**
https://github.com/advisories/GHSA-rp65-9cf3-cjxr
https://nvd.nist.gov/vuln/detail/CVE-2021-3803
https://huntr.dev/bounties/8cf8cc06-d2cf-4b4e-b42c-99fafb0b04d0 …
> [Security] Selectively bump nth-check to 2.1.1

- app/controllers/providers/means/identify_types_of_incomes_controller.rb
- app/controllers/providers/means/regular_incomes_controller.rb
- app/forms/providers/means/regular_income_form.rb
- app/models/legal_aid_application.rb
- app/models/regular_transaction.rb
- app/services/flow/flows/provider_capital.rb
- app/views/providers/means/regular_incomes/show.html.erb
- config/locales/en/activemodel.yml
- config/locales/en/helpers.yml
- config/locales/en/providers.yml
- config/routes.rb
- db/anonymise/rules.rb
- db/migrate/20220902150227_create_regular_transactions.rb
- db/migrate/20220915104106_add_regular_transactions_indexes.rb
- db/schema.rb
- features/providers/check_your_answers.feature
- features/providers/non_passported_journey.feature
- features/step_definitions/bank_statement_uploaded_steps.rb
- spec/factories/cash_transactions.rb
- spec/factories/regular_transactions.rb
- spec/forms/providers/means/regular_income_form_spec.rb
- spec/models/legal_aid_application_spec.rb
- spec/models/regular_transaction_spec.rb
- spec/requests/providers/client_completed_means_spec.rb
- spec/requests/providers/means/identify_types_of_incomes_controller_spec.rb
- spec/requests/providers/means/regular_incomes_controller_spec.rb
Before, when providers with employment and bank upload permissions submitted income data for their client, they could only specify which transactions their client received.
This data is not granular enough, and makes it impossible to obtain a financial eligibility assessment (CFE) result for the client.
As part of ongoing work to iterate on the bank upload journey, providers are now able to tell us how much (amount), and how often (frequency) their client receives these income payments.
Next steps will include:
- updating the list of frequencies for each type of transaction
- replicating this functionality for the outgoings page
This user journey is restricted by feature flag at the controller level.
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3445) …
> Providers can submit more accurate income data

- README.md
Before, tests tagged with `ccms` were only run if explictly included in the test command.
In #3466, this was changed so that `ccms` tests ran as part of the test suite by default.
This updates the README to reflect that change.
> Remove CCMS testing section from README

- app/controllers/providers/means/identify_types_of_incomes_controller.rb
- app/models/legal_aid_application.rb
- app/services/flow/flows/provider_capital.rb
- app/services/flow/flows/provider_start.rb
- app/views/providers/means_summaries/_income_assessment.html.erb
- features/providers/check_your_answers.feature
- features/providers/enhanced_bank_upload/check_your_answers.feature
- features/providers/enhanced_bank_upload/enhanced_bank_upload_flow.feature
- features/providers/non_passported_journey.feature
- features/step_definitions/bank_statement_uploaded_steps.rb
- features/step_definitions/enhanced_bank_upload_steps.rb
- spec/models/legal_aid_application_spec.rb
- spec/requests/providers/bank_statements_spec.rb
- spec/requests/providers/client_completed_means_spec.rb
- spec/requests/providers/means/employed_incomes_spec.rb
- spec/requests/providers/means/full_employment_details_controller_spec.rb
- spec/requests/providers/means/identify_types_of_incomes_controller_spec.rb
Before, the `Providers::Means::IdentifyTypesofIncomesController` redirected all
requests to the new `Providers::Means::RegularIncomesController` if the enhanced
bank upload setting was enabled.
Initially this seemed reasonable, however it was based on some incorrect
assumptions.
When the enhanced bank upload setting is enabled, only applications that are
using the bank upload journey should use the new flow.
This change seeks to redress the incorrect flows and ensure that only
non-passported applications that are using the bank statement upload journey use
the new how much, how often (enhanced bank upload) flow.
_Note: In each scenario the setting is enabled and the application is uploading bank_ 
_statements. If either of those conditions aren't met, the user will be directed to the_ …
> Ensure correct flows use enhanced bank upload journey

- features/providers/enhanced_bank_upload/check_your_answers.feature
- features/providers/enhanced_bank_upload/enhanced_bank_upload_flow.feature
Several cucumber tests that rely on uploading files are flaky, and have been failing at a higher rate recently.
They seem to fail because validations that ensure supporting evidence has been uploaded have not been met. This is likely due to latency in the system.
This adds assertions that the files have been uploaded before attempting to navigate to the next step of the user journey in two of these tests.
The intention of this change is to ensure that the file has been uploaded, but it also ensures we are testing more realistic and appropriate user behaviour (i.e we care that the user knows the file has been uploaded too).
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3505)
> Fix flaky cucumber upload tests

- package.json
- yarn.lock
The package terser before 4.8.1, from 5.0.0 and before 5.14.2 are vulnerable to Regular Expression Denial of Service (ReDoS) due to insecure usage of regular expressions.
**References**
https://github.com/advisories/GHSA-4wf5-vphf-c2xc
https://github.com/terser/terser/blob/master/lib/compress/evaluate.js%23L135
https://snyk.io/vuln/SNYK-JS-TERSER-2806366 …
> [Security] Selectively bump terser to 5.15.0

- app/models/cfe/v5/result.rb
- app/services/cfe/obtain_assessment_result_service.rb
- features/providers/enhanced_bank_upload/check_your_answers.feature
- features/support/steps_helper.rb
- lib/tasks/cfe_result_v42v5.rake
- spec/cassettes/EmergencyLevelOfServiceController/GET_/providers/applications/_legal_aid_application_id/emergency_level_of_service/_proceeding_id/when_the_provider_is_authenticated/when_the_proceeding_has_more_than_one_possible_level_of_service/asks_the_user_to_select_a_level_of_service.yml
- spec/cassettes/Proceedings_EmergencyLevelOfServiceForm/_save/when_the_user_doesn_t_answer_the_question/generates_the_expected_error_message.yml
- spec/cassettes/SubstantiveLevelOfServiceController/GET_/providers/applications/_legal_aid_application_id/substantive_level_of_service/_proceeding_id/when_the_provider_is_authenticated/when_the_proceeding_has_more_than_one_possible_level_of_service/asks_the_user_to_select_a_level_of_service.yml
Existing V5 responses were being stored in the database as CFE::V4::Result (there being no difference in the result layout between v4 and v5).
This PR creates a CFE::V5::Result class, identical to CFE::V4::result, and ensures exising CFE responses are written as the new class.
A rake task  `cfe:v5:convert` has been provided to convert existing v5 results to the new model.
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3506) …
> AP-3506 Convert v5 CFE response to V5 models

- app/forms/proceedings/emergency_defaults_form.rb
- app/forms/proceedings/substantive_defaults_form.rb
- app/models/proceeding.rb
- app/models/scope_limitation.rb
- app/services/legal_framework/add_proceeding_service.rb
- app/services/legal_framework/proceeding_types/defaults.rb
- db/anonymise/rules.rb
- db/migrate/20220915124637_create_scope_limitation.rb
- db/schema.rb
- lib/tasks/migrate_scope_limitations.rake
- spec/cassettes/LegalFramework_AddProceedingService/_call/correct_params/when_the_enable_loop_feature_flag/is_off/creates_scope_limitations.yml
- spec/cassettes/LegalFramework_AddProceedingService/_call/correct_params/when_the_enable_loop_feature_flag/is_off/does_not_create_scope_limitations.yml
- spec/cassettes/LegalFramework_AddProceedingService/_call/correct_params/when_the_enable_loop_feature_flag/is_on/does_not_create_scope_limitations.yml
- spec/cassettes/Proceedings_EmergencyDefaultsForm/_save/when_the_submission_is_valid/and_the_user_accepts_the_defaults/without_calling_the_subject/creates_a_scope_limitation_object.yml
- spec/cassettes/Proceedings_EmergencyDefaultsForm/_save/when_the_submission_is_valid/and_the_user_rejects_the_defaults/without_calling_the_subject/does_not_create_a_scope_limitation_object.yml
- spec/cassettes/Proceedings_EmergencyDefaultsForm/_save/when_the_user_doesn_t_answer_the_question/without_calling_the_subject/does_not_create_a_scope_limitation_object.yml
- spec/cassettes/Proceedings_SubstantiveDefaultsForm/_save/when_the_submission_is_valid/and_the_user_accepts_the_defaults/without_calling_the_subject/creates_a_scope_limitation_object.yml
- spec/cassettes/Proceedings_SubstantiveDefaultsForm/_save/when_the_submission_is_valid/and_the_user_rejects_the_defaults/without_calling_the_subject/does_not_create_a_scope_limitation_object.yml
- spec/cassettes/Proceedings_SubstantiveDefaultsForm/_save/when_the_user_doesn_t_answer_the_question/without_calling_the_subject/does_not_create_a_scope_limitation_object.yml
- spec/factories/proceedings.rb
- spec/factories/scope_limitations.rb
- spec/forms/proceedings/emergency_defaults_form_spec.rb
- spec/forms/proceedings/substantive_defaults_form_spec.rb
- spec/models/proceeding_spec.rb
- spec/models/scope_limitation_spec.rb
- spec/services/legal_framework/add_proceeding_service_spec.rb
- spec/services/legal_framework/proceeding_types/defaults_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3495)
This creates a new ScopeLimitaton object and updates handlers to create new ScopeLimitation objects going forward.
It adds helper methods to read data from the proceedings table (current records) _or_ the ScopeLimitations table (new records) depending on what is available …
> AP-3495: Refactor scope limitations

- features/providers/bank_statement_upload.feature
- features/providers/evidence_upload.feature
- features/providers/merits_task_list.feature
- features/providers/statement_of_case_upload.feature
- features/support/hooks.rb
- spec/requests/providers/application_merits_task/statement_of_case_spec.rb
- spec/requests/providers/bank_statements_spec.rb
- spec/requests/providers/gateway_evidence_spec.rb
- spec/requests/providers/uploaded_evidence_collection_spec.rb
- spec/requests/status_spec.rb
- spec/requests/v1/bank_statements_spec.rb
- spec/requests/v1/statement_of_cases_spec.rb
- spec/requests/v1/uploaded_evidence_collections_spec.rb
- spec/services/malware_scanner_spec.rb
- spec/support/malware_scanner.rb
Before, clamav was used for malware scanning in all tests that interacted with the `MalwareScanner` class (either directly or indirectly).
While it is important and useful to test the entire stack in integration tests, clamav is a source of repeated flakiness across the test suite due to the latency it introduces (especially in CI).
This updates RSpec specs and Cucumber tests to mock a successful clamav response
unless they are explicitly tagged with `clamav: true` or `@clamav`.
> Use clamav in tests when explicitly tagged

- app/controllers/providers/means/regular_outgoings_controller.rb
- app/forms/providers/means/regular_outgoings_form.rb
- app/models/legal_aid_application.rb
- app/services/flow/flows/provider_capital.rb
- app/views/providers/means/regular_outgoings/show.html.erb
- app/views/providers/means_summaries/_income_assessment.html.erb
- app/webpack/stylesheets/dropzone.scss
- config/locales/en/activemodel.yml
- config/locales/en/helpers.yml
- config/locales/en/providers.yml
- config/routes.rb
- features/providers/enhanced_bank_upload/check_your_answers.feature
- features/providers/enhanced_bank_upload/enhanced_bank_upload_flow.feature
- spec/factories/regular_transactions.rb
- spec/factories/transaction_types.rb
- spec/forms/providers/means/regular_outgoings_form_spec.rb
- spec/models/legal_aid_application_spec.rb
- spec/requests/providers/means/regular_outgoings_controller_spec.rb
- spec/requests/providers/means/student_finance_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3460)
- Add route, controller, form, view and content for regular outgoings page, so providers can select outgoing categories and add the amount and frequency of payment for each category
- Add rspec tests for form and controller
- Update existing rspec tests and feature tests …
> AP-3460 enhanced bank upload regular outgoings

- features/providers/bank_statement_flow.feature
If the request to upload the document hasn't completed (and subsequently updated the DOM), the "Save and continue" button will be clicked before the document has uploaded. This means the form returns an error and the user does not navigate to the "Review employment income" page as expected by the test.
This adds an assertions against the rendered content to ensure that the document has been uploaded before submitting the form. This prevents the test being flaky, but it doesn't resolve the underlying issue.
Here are some UX/testing considerations that might improve the user experience and the robustness of the test:
- Prevent form submissions while documents are being uploaded.
- Offer a visual affordance to the user that the document is being uploaded (e.g a spinning progress icon).
- …
> Fix flaky document upload spec

- helm_deploy/apply-for-legal-aid/templates/cronjob-admin-report.yaml
- helm_deploy/apply-for-legal-aid/templates/cronjob-db-backup-cleanup.yaml
- helm_deploy/apply-for-legal-aid/templates/cronjob-deliver-scheduled-mail.yaml
- helm_deploy/apply-for-legal-aid/templates/cronjob-destroy-purgeable.yaml
- helm_deploy/apply-for-legal-aid/templates/cronjob-export-digest.yaml
- helm_deploy/apply-for-legal-aid/templates/cronjob-extract-digest.yaml
- helm_deploy/apply-for-legal-aid/templates/cronjob-hourly-db-backup.yaml
- helm_deploy/apply-for-legal-aid/templates/cronjob-mark-purgeable.yaml
- helm_deploy/apply-for-legal-aid/templates/cronjob-metrics.yaml
- helm_deploy/apply-for-legal-aid/templates/cronjob-reset-dashboard-overnight.yaml
Add backoffLimit for all cronjob Jobs on all environments
UAT environments are erroring when performing many of the jobs
due to database pods being recycled and not migrated/seeded.
The large numbers of errored job pods were persisting in the UAT
namespace eating up pods unnecessarily and could, in-extremis,
cause deployment failures due to pod limits?!
Failure of a cronjob's Job pod is usually configuration related
and is not likely to succeed on subsequent attempts. Combined
with the current cronjob `failedJobsHistoryLimit` of 0 or 1 a
`backofLimit` of 1 means failed or errored pods will remain
around for debugging purposes on any environment in any event.
The [backoffLimit](https://kubernetes.io/docs/concepts/workloads/controllers/job/#pod-backoff-failure-policy) setting allows …
> Add backoffLimit to all cronjob job specs

- db/migrate/20220915131126_remove_proceedings_scope_limitations.rb
- db/schema.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3495)
After the previous migration has been executed and the rake task, that moves data from the proceedings table to the new ScopeLimitation table, has been run - this can be merged to remove the original columns …
> AP-3495: remove scope_limitation fields from Proceeding

- .circleci/config.yml
- config/environments/test.rb
This ensures the application is eager loaded when running tests in CI.
This is the default behaviour since Rails 7+, and can help catch certain errors before deployment.
It also ensures all application code is checked by simplecov when doing performaing coverage checks.
> Eager load the application in CI

- .circleci/config.yml
This change was [recommended] by the operations team ahead of 
some changes to CircleCI.
[recommended]: https://mojdt.slack.com/archives/C02D2NEF9CJ/p1665061637638169
We were already using the default version in most places, however 
this removes the version flag from the two remaining places it was used.
> Use default Docker version in CircleCI

- .github/dependabot.yml
Remove Webhint's ignored dependencies via dependabot.
Webhint and its dependencies were removed from the codebase, therefore, we no longer need to ignore these via dependabot
> Chore: remove webhint ignored dependencies

- app/helpers/capital_helper.rb
- app/services/flow/flows/provider_vehicle.rb
- app/views/shared/check_answers/_assets.html.erb
- features/providers/bank_statement_flow.feature
- features/providers/check_your_answers.feature
- features/providers/enhanced_bank_upload/check_your_answers.feature
- features/providers/means_report.feature
- features/step_definitions/bank_statement_uploaded_steps.rb
- features/step_definitions/enhanced_bank_upload_steps.rb
- features/step_definitions/means_report_steps.rb
Add "Which bank accounts does your client have?" step to bank statement upload
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3536)
This seems to have been missed from existing/basic bank 
statement upload flow and should be included in both the 
basic and enhanced flow.
NOTE: In the context of non-passported bank statement
uploads the name `offline_accounts` is wrong as well
as the field saving_amounts#offline_current_accounts
and saving_amounts#offline_saving_accounts. renaming
or adding new columns to reflect the new logic (to just
collect a flat amount for all current accounts whether
off or online) would require rejigging various other
classes. …
> [AP-3536] Add current and saving account totals to bank statement uploads

- Gemfile
- Gemfile.lock
- config/initializers/strong_migrations.rb
As the application continues to scale, we will need to think more 
about how we do safe migrations.
This gem reduces some of that cognitive load by catching unsafe 
migrations in development and giving developers insight on how 
to mitigate problematic migrations.
Default configuration has been applied, except the targeted 
database version has been set to 10.
> Use strong_migrations gem

- .overcommit.yml
This adds a pre-commit check to overcommit to run the DB Anonymiser check
If you have added a new table to the schema but not created a new rule for it, it will cause your commit to fail
It means you won't get pinged on github, but this will only work if you have activated overcommit, so I would suggest leaving the Github action as a backup …
> Discussion: check DB anonymizer rules when commiting

- features/step_definitions/civil_journey_steps.rb
- features/step_definitions/merits_task_steps.rb
- spec/forms/applicants/basic_details_form_spec.rb
- spec/forms/legal_aid_applications/restrictions_form_spec.rb
- spec/forms/providers/proceeding_merits_task/linked_children_form_spec.rb
- spec/helpers/policy_disregards_helper_spec.rb
- spec/models/address_spec.rb
- spec/models/applicant_spec.rb
- spec/models/cfe/v4/result_spec.rb
- spec/models/legal_framework/merits_task_list_spec.rb
- spec/requests/citizens/gather_transactions_spec.rb
- spec/requests/providers/address_selections_spec.rb
- spec/requests/providers/addresses_spec.rb
- spec/requests/providers/bank_transactions_spec.rb
- spec/requests/providers/check_benefits_spec.rb
- spec/requests/providers/confirm_dwp_non_passported_applications_spec.rb
- spec/requests/providers/limitations_spec.rb
- spec/requests/providers/proceeding_merits_task/attempts_to_settle_controller_spec.rb
- spec/requests/providers/proceeding_merits_task/chances_of_success_spec.rb
- spec/requests/providers/proceeding_merits_task/linked_children_spec.rb
- spec/requests/providers/submitted_applications_spec.rb
- spec/services/ccms/requestors/case_add_requestor_xml_blocks/non_passported_variable_attributes_spec.rb
- spec/services/ccms/submitters/check_case_status_service_spec.rb
- spec/services/ccms/submitters/obtain_document_id_service_spec.rb
- spec/services/dashboard_event_handler_spec.rb
- spec/services/govuk_emails/delivery_man_spec.rb
- spec/services/hmrc/create_responses_service_spec.rb
- spec/services/malware_scanner_spec.rb
- spec/services/populators/transaction_type_populator_spec.rb
- spec/services/reports/reports_creator_spec.rb
As Hamlet almost once said:
> ".to_not or .not_to be"
This replaces the former with the later in our tests, in the interests of consistency and correctness.
> Replace `.to_not` expectations with `.not_to`

- app/services/flow/flows/provider_capital.rb
- spec/requests/providers/means/regular_incomes_controller_spec.rb
Before, the `:regular_incomes` step, defined a `check_answers` flow that could never be reached in practice.
All applications that reach the `:regular_incomes` step are using the enhanced bank upload journey (and uploading bank statements) by design.
This removes that redundant `check_answers` flow and associated tests.
> Remove redundant regular incomes flow

- app/views/providers/means_summaries/_income_assessment.html.erb
- features/providers/check_your_answers.feature
- features/providers/enhanced_bank_upload/check_your_answers.feature
- features/step_definitions/check_your_answers_steps.rb
- features/step_definitions/enhanced_bank_upload_steps.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3559)
Fix logic for displaying the employment income details section on the means summary page.
The following scenarios should now work as expected, for all three non-passported journeys (Truelayer journey, open banking journey, enhanced bank upload journey):
**Scenario 1:** Provider has selected employed and HMRC returns data - **show employment details section**
**Scenario 2:** Provider has selected unemployed and HMRC returns data - **show employment details section**
**Scenario 3:** Provider has selected unemployed and HMRC does NOT return data - **DON'T show employment details section**
- Added a feature test to test Scenario 3 on the enhanced bank upload journey
- I have not added a feature test to test the open banking scenario …
> AP-3559 means summary page employment details section display logic

- app/services/flow/flows/provider_capital.rb
- spec/requests/providers/means/identify_types_of_outgoings_controller_spec.rb
Prevent basic uploads navigating to truelayer income_summary
This is a live bug whereby if the provider does not add any
outgoings on the outgoings page but has provided incomes
on the earlier incomes page they will be take to the
income_summary page - this page is only for categorising
bank transactions and part of the truelayer path only.
ps: this would not effect the enhanced journey.
- You should …
> Prevent basic uploads navigating to truelayer `income_summary`

- app/views/admin/legal_aid_applications/index.html.erb
- app/views/citizens/consents/show.html.erb
- app/views/citizens/means_test_results/show.html.erb
- app/views/providers/addresses/show.html.erb
- app/views/providers/confirm_dwp_non_passported_applications/show.html.erb
- app/views/providers/end_of_applications/show.html.erb
- app/views/providers/gateway_evidences/show.html.erb
- app/views/providers/means/has_dependants/show.html.erb
- app/views/providers/start/index.html.erb
- app/views/providers/transactions/show.html.erb
Before, inset text components were rendered adhoc by replicating and tweaking HTML examples from the GOV.UK Design System.
This replaces all usages of the inset text component with its `govuk-components` counterpart.
> Use `govuk_inset_text` ViewComponent helper

- app/views/providers/means/housing_benefits/show.html.erb
- app/views/providers/means/regular_incomes/show.html.erb
- app/views/providers/means/regular_outgoings/show.html.erb
Before, these nested fieldsets in the regular transaction forms were using a `<p>` tag.
This was an accessibility issue, so the fieldset headings have been updated to use `<h2>` tags.
> Use `<h2>` tag for nested fieldset headings

- app/controllers/providers/means/housing_benefits_controller.rb
- app/forms/providers/means/housing_benefit_form.rb
- app/forms/providers/means/regular_income_form.rb
- app/forms/providers/means/regular_outgoings_form.rb
- app/forms/providers/means/regular_transaction_form.rb
- app/models/legal_aid_application.rb
- app/views/providers/means/housing_benefits/show.html.erb
- config/locales/en/activemodel.yml
- config/locales/en/helpers.yml
- config/locales/en/providers.yml
- spec/forms/providers/means/housing_benefit_form_spec.rb
- spec/forms/providers/means/regular_outgoings_form_spec.rb
- spec/forms/providers/means/regular_transaction_form_spec.rb
- spec/requests/providers/means/housing_benefits_controller_spec.rb
This introduces a new `RegularTransactionForm` model for persisting regular
transaction data for an application (and destroying dependent records).
Each of `RegularIncome`, `RegularOutgoings` and `HousingBenefit` forms make
use of this new abstract form.
The basic premise of this refactor is that each of the forms exhibit the same
characteristic behaviour:
1. They validate user input (i.e an option is selected, inputs are valid).
2. They facilitate validation and creation of regular transaction records that
belong to a given legal aid application.
3. They persist some data on the legal aid application record itself.
4. They destroy the correct combination of associated records. This is currently
complicated by several factors:
- The relationship between LegalAidApplication <> …
> Refactor regular transaction forms

- app/helpers/proceeding_helper.rb
- spec/helpers/proceeding_helper_spec.rb
The tests for the `#scope_limits` helper method introduced recently were [flaky] 
because they expected scope limitations for a given proceeding to be returned in 
a particular order.
[flaky]: https://app.circleci.com/pipelines/github/ministryofjustice/laa-apply-for-legal-aid/18383/workflows/ce9fab1b-fdf1-46c5-855a-a0684d15e294/jobs/96235
This updates the tests to prefer the less specific `contain_exactly` helper over `eq`.
The tests have also been refactored with the aim of telling more of a story, since 
at first it wasn't clear to me what the tests were doing, or where the data was 
coming from.
The `#scope_limits` method itself has also been simplified.
> Fix flaky proceeding helper spec

- app/controllers/providers/application_merits_task/statement_of_cases_controller.rb
- app/services/flow/flows/provider_merits.rb
- app/services/flow/merits_loop.rb
- features/cassettes/mini-loop_additional_merits_questions/Clicking_the_merits_questions_out_of_sequence_allow_a_group_to_be_completed_regardless_of_start_point.yml
- features/providers/merits_task_list.feature
- features/providers/mini-loop/merits_questions.feature
- features/step_definitions/civil_journey_steps.rb
- spec/factories/legal_framework_merits_task_list.rb
- spec/factories/legal_framework_serialized_merits_task_list.rb
- spec/requests/providers/application_merits_task/client_denial_of_allegation_spec.rb
- spec/requests/providers/application_merits_task/has_other_involved_children_spec.rb
- spec/requests/providers/application_merits_task/opponents_spec.rb
- spec/requests/providers/application_merits_task/statement_of_case_spec.rb
- spec/requests/providers/merits_task_lists_controller_spec.rb
- spec/requests/providers/proceeding_merits_task/attempts_to_settle_controller_spec.rb
- spec/requests/providers/proceeding_merits_task/linked_children_spec.rb
- spec/requests/providers/proceeding_merits_task/success_prospects_spec.rb
- spec/services/flow/merits_loop_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3561)
Extract merits question logic to separate class that allows merits questions to be grouped by application or proceeding.ccms_code
This allows a user to answer a single question and be looped through the remaining questions without being bounced to the merits_task_list each time
Clicking on Latest incident details, the user will be taken through each question in group 1 and then returned to the merits task list
If the user starts lower down the list, e.g. Statement of case, they will get taken to `Latest incident details,` then though each `Not started` until reaching `Client offer of undertaking`
If they start with Chances of Success for Child arrangements order before completing  Children involved in this application  in Group …
> AP-3561: Update merit question flow

- app/views/shared/_review_application.html.erb
Remove "housing benefit total" from income section
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3558)
The income section of the review and print page
is only to be used by truelayer applications
for which the housing benefit transaction type
is not applicable.
The enhanced bank statement journey will replace the
the entire "income, regular payments and assets" section
and show housing benefit in in a separate section according
to designs. …
> fix review page housing benefit

- app/views/providers/capital_assessment_results/_result_details.html.erb
- app/views/providers/capital_assessment_results/show.html.erb
- app/views/providers/capital_income_assessment_results/_bank_statements.html.erb
- app/views/providers/capital_income_assessment_results/_deductions.html.erb
- app/views/providers/capital_income_assessment_results/_disposable_income.html.erb
- app/views/providers/capital_income_assessment_results/_employment_income.html.erb
- app/views/providers/capital_income_assessment_results/_other_income.html.erb
- app/views/providers/capital_income_assessment_results/_outgoings.html.erb
- app/views/providers/capital_income_assessment_results/_result_details.html.erb
- app/views/providers/capital_income_assessment_results/show.html.erb
- app/views/shared/_other_assets.html.erb
- app/views/shared/_property_results.html.erb
- app/views/shared/_restrictions.html.erb
- app/views/shared/_savings_and_investments.html.erb
- app/views/shared/_total_capital.html.erb
- app/views/shared/_vehicle_results.erb
Before, accordion components were rendered adhoc by replicating and tweaking HTML examples from the GOV.UK Design System.
This replaces accordion components with their govuk-components counterparts.
> Use `govuk_accordion` ViewComponent helper

- app/services/cfe/create_applicant_service.rb
- spec/services/cfe/create_applicant_service_spec.rb
In order for CFE to apportion child care cost allowance for an applicant, it needs to know whether an applicant is employed or not.
This adds `employed` to the `CreateApplicantService` payload, so that the data point can be persisted to the applicant in CFE.
[Changes have been made to CFE][cfe-changes] to take into account this new information when collating the childcare costs allowance for an assessment.
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3560)
[cfe-changes]: https://github.com/ministryofjustice/check-financial-eligibility/pull/1163
> Send applicant employed status to CFE

- app/views/privacy_policy/index.html.erb
- config/locales/en/privacy_policy.yml
Crime Apply have stolen our privacy policy and noticed some small issues on the page - a missing full stop, an unnecessary colon and a missing header. This is just a small PR to fix these.
> Small content fixes on the privacy policy page

- app/forms/legal_aid_applications/has_other_proceedings_form.rb
- config/locales/en/activemodel.yml
- config/locales/en/providers.yml
- spec/requests/providers/has_other_proceedings_controller_spec.rb
This prefers default Rails validations to custom validation, 
reduces the external API of the form model, and prefers 
default error message lookups to custom ones.
> Simplify `LegalAidApplications::HasOtherProceedingsForm`

- db/schema.rb
These colums need to be nullable and migration reflects this but
schema does not currently
To fix problems locally you can run this
```
rails db:migrate:down VERSION=20220708123323
```
```
rails db:migrate:up VERSION=20220708123323
``` …
> Update schema to reflect migrations

- app/views/shared/check_answers/_merits.html.erb
Add explicit instance vars to route path helper calls.
Fixes potential failed merits report caused by various new merits question renderings
Errors are raised - see Sidekiq/ReportsCreatorWorker errors such as below
```
ActionView::Template::Error: No route matches {:action=>"show", :controller=>"providers/application_merits_task/client_denial_of_allegations", :locale=>:en}, missing required keys: [:legal_aid_applicat...
While route helpers can deduce missing ke
```
This is because while path helpers can deduce a missing require route key when rendered in the rails
standard MVC way (via ActionDispatch cleverness) the way the MeritsReportCreator (and MeansReportCreator) work is to call `Controller.renderer.render` directly, which cannot deduce the missing route keys (I assume).
Solution: …
> Add application instance var to path call

- app/views/providers/applicant_bank_accounts/show.html.erb
- app/views/providers/has_evidence_of_benefits/show.html.erb
- app/views/providers/proceeding_merits_task/attempts_to_settle/show.html.erb
- app/views/providers/proceeding_merits_task/linked_children/show.html.erb
- app/views/providers/proceeding_merits_task/specific_issue/show.html.erb
Remove explicit builder arguments
It is set to be this by default 
```
ActionView::Base.default_form_builder = GOVUKDesignSystemFormBuilder::FormBuilder
```
> Remove explicit builder arguments.

- .overcommit.yml
It was running (slowly) on each commit this changes it so that it only runs when files in the db/migrate folder are in the commit, this retains the speed of not tripping the github action with a speed increase on every other commit! …
> Fix: Update overcommit rule for DB anonymisation

- features/providers/check_your_answers.feature
Before, this test was flaky because it would try to navigate to the next page while a document was being uploaded.
In #4375, that document upload spec expected to see "document.pdf UPLOADED" content before clicking "Save and continue". This ensured that the document had finished uploaded before navigating away.
This test appeared to work similarly, except it would fail sporadically.
On closer inspection, it turns out the "hello_world.pdf" file was already uploaded. This meant the test attempted to navigate away by clicking "Save and continue" straight away (rather than waiting for the upload to finish).
This updates the test to upload a different second file, and expect both files to be uploaded before navigating away from the page.
As in #4375, similar considerations should be made, but …
> Fix flaky bank statement spec

- app/models/applicant.rb
- spec/factories/applicants.rb
- spec/forms/applicants/basic_details_form_spec.rb
Replace multiline anchors with start and end of string anchors
[came out of story](https://dsdmoj.atlassian.net/browse/AP-3608)
Nino validation uses the multiline anchors but should
use start and end instead. I noticed this raises error
when spiking use of `validate :blah, :format: { with: regex }`
rails valiadaion
```
The provided regular expression is using multiline anchors (^ or $), which may present a security risk. Did you mean to use \A and \z, or forgot to add the :multiline => true option?
``` …
> Replace multiline anchors with start and end of string anchors

- db/schema.rb
These columns were added as nullable string columns in #4048, but for some reason the schema did not reflect this until #4530.
Since then, #4529 undid the change in #4530, so this redoes the change again.
Before, the columns were nullable but specified as `null: false` in the schema.
Now, they are still nullable, and the schema reflects that.
> Update schema.rb to reflect nullable columns

- app/models/proceeding_merits_task/attempts_to_settle.rb
- app/models/proceeding_merits_task/chances_of_success.rb
The `application_proceeding_types` table was dropped in #3427, but associated columns were not removed from the `chances_of_successes` and `attempts_to_settles` tables.
This ignores the column in both models, so that the columns can be safely removed in a subsequent change.
> Ignore soon to be deleted columns

- db/schema.rb
1. Timestamp precision
This was originally addressed in 22fe6852d095d7d096d1de790af58413e0187bd0 but
the changes were since merged in a different change inadvertently.
Since Rails 7.0, datetime column precision is set to 6 by default.
This means `t.datetime "partied_at"` would generate a column in postgres of
`timestamp(6) without time zone` type.
Before Rails 7.0, datatime column precision was set to nil by default.
This meant `t.datetime "partied_at"` would have generated a column in postgres
of `timestamp without time zone` type.
It seems that we always used the default, which means any datetime columns added
to the database **before** Rails 7.0 have a type without any precision, but any
datetime columns added to the database **after** Rails 7.0 have a type with
precision (6). …
> Update schema.rb to reflect production

- db/migrate/20221118094938_remove_application_proceeding_type_from_attempts_to_settles.rb
- db/migrate/20221118095617_remove_application_proceeding_type_from_chances_of_successes.rb
- db/schema.rb
The `application_proceeding_types` table was dropped in #3427, but these columns were not removed.
This removes the `application_proceeding_type_id` columns from the `attempts_to_settles` and `chances_of_successes` tables since they no longer correspond to anything.
> Remove redundant proceeding type columns

- app/models/proceeding_merits_task/attempts_to_settle.rb
- app/models/proceeding_merits_task/chances_of_success.rb
These columns were ignored so they could be removed safely.
They have since been removed in #4595, so we can stop ignoring the columns.
> Stop ignoring columns

- app/forms/proceedings/emergency_defaults_form.rb
- app/forms/proceedings/substantive_defaults_form.rb
- spec/cassettes/Proceedings_SubstantiveDefaultsForm/_save/when_the_submission_is_valid/and_the_user_accepts_the_defaults/when_the_proceeding_already_has_scope_limitations/deletes_the_existing_substantive_scope_limitations_and_creates_one_new_substantive_scope_limitation.yml
- spec/forms/proceedings/emergency_defaults_form_spec.rb
- spec/forms/proceedings/substantive_defaults_form_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3624)
It is possible that the user has already entered non-default scope limitations when they arrive at the default scope limitation page (e.g. if they use the back button). The application was adding the default scope limitation in addition to any existing scope limitations. Instead, delete any existing scope limitations. This applies to both substantive and emergency scope limitations. …
> ap-3624: prevent duplicate scope limitations

- app/views/providers/application_merits_task/statement_of_cases/show.html.erb
- app/views/providers/confirm_client_declarations/show.html.erb
- app/webpack/stylesheets/application.scss
- app/webpack/stylesheets/citizens/declarations.scss
- app/webpack/stylesheets/govuk-mods.scss
Before, custom markup was used to render two instances 
of the [GOV.UK Warning text component][component].
Rather than maintaining custom HTML, we can make use 
of the `govuk_warning_text` ViewComponent instead.
This adopts that component and removes some styles that 
are no longer in use.
[component]: https://design-system.service.gov.uk/components/warning-text/
> Use govuk_warning_text component

- app/models/concerns/delegated_functions.rb
- app/services/ccms/attribute_value_generator.rb
- spec/models/legal_aid_application_spec.rb
Remove duplicate delegated functions method
[Link to story](https://dsdmoj.atlassian.net/browse/AP-6329)
`#proceedings_used_delegated_functions?` and `#used_delegated_functions?`
do the same thing. Keep the shorter one as more succint while still
sufficiently desccribing its function.
- You …
> Remove duplicate delegated functions method

- spec/models/legal_framework/merits_task_list_spec.rb
- spec/requests/providers/application_merits_task/client_denial_of_allegation_spec.rb
- spec/requests/providers/application_merits_task/client_offered_undertakings_controller_spec.rb
- spec/requests/providers/application_merits_task/date_client_told_incidents_spec.rb
- spec/requests/providers/application_merits_task/has_other_involved_children_spec.rb
- spec/requests/providers/application_merits_task/nature_of_urgencies_controller_spec.rb
- spec/requests/providers/application_merits_task/opponents_spec.rb
- spec/requests/providers/application_merits_task/statement_of_case_spec.rb
- spec/requests/providers/proceeding_merits_task/attempts_to_settle_controller_spec.rb
- spec/requests/providers/proceeding_merits_task/chances_of_success_spec.rb
- spec/requests/providers/proceeding_merits_task/linked_children_spec.rb
- spec/requests/providers/proceeding_merits_task/opponents_application_controller_spec.rb
- spec/requests/providers/proceeding_merits_task/prohibited_steps_controller_spec.rb
- spec/requests/providers/proceeding_merits_task/specific_issue_controller_spec.rb
- spec/requests/providers/proceeding_merits_task/vary_order_controller_spec.rb
- spec/support/task_list_matcher.rb
Add a new set of rspec matchers that can be passed a group, task, and optionally, a state to determine
the current state of the task list.
`have_completed_task(:group, :task_name)`
`have_not_started_task(:group, :task_name)`
and, underlying them,
`have_task_in_state((:group, :task_name, :state)` …
> Fix: Improve task list test handling

- spec/requests/providers/confirm_non_means_tested_applications_controller_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3634)
Just adding rspec tests for the ConfirmNonMeansTestedApplicationsController
> AP-3634 non means test interrupt page

- config/routes.rb
Introduce the `scope` helper with `module:` arguments to simplify
the application and proceeding level merits task list routes, as well
as the proceeding loop routes.
> Refactor routes

- app/views/layouts/application.html.erb
Remove IE conditional comments
Conditional comments are conditional statements interpreted by Microsoft Internet Explorer versions 5 through 9 in HTML source code.
Browser viersions that are no longer support by MS nor us.
In addition, these source paths do not exist, therefore would return a 404 if browsing on the relevant browsers. …
> Remove IE conditional comments

- app/services/ccms/attribute_value_generator.rb
- app/services/ccms/requestors/case_add_requestor.rb
- spec/services/ccms/requestors/case_add_requestor_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3497)
- Modified CCMS payload to send multiple emergency/substantive scope limitations for each proceeding where these exist.
- Specify "MULTUPLE" as requested scope where there exist multiple emergency or substantive scope limitations for a proceeding, or where delegated functions have been used. …
> Ap 3497 multiple scope limitations ccms

- app/controllers/providers/merits_task_lists_controller.rb
- app/services/legal_framework/opponent_task_update_service.rb
- spec/factories/legal_framework_merits_task_list.rb
- spec/factories/legal_framework_serialized_merits_task_list.rb
- spec/requests/providers/merits_task_lists_controller_spec.rb
- spec/services/legal_framework/opponent_task_update_service_spec.rb
When the opponent split was deployed, more applications than expected were in progress
This handles the display and generation of the task list.  If an application has a task list with the original, single, opponents_detail task it was failing.
When displaying the task list, this now replaces it with the three new questions and marks them as complete
This should be short-lived and removable soon
- You …
> Fix: Opponent task errors while in progress

- package.json
- yarn.lock
The loader-utils package <1.4.1 >=2.0.0 <2.0.3 are vulnerable to Regular Expression Denial of Service (ReDoS).
ReDos bug fixed in [v1.4.2](https://github.com/webpack/loader-utils/releases/tag/v1.4.2), [v2.0.4](https://github.com/webpack/loader-utils/releases/tag/v2.0.4) and [v3.2.1](https://github.com/webpack/loader-utils/releases/tag/v3.2.1)
The latest possible version that can be installed is 1.4.2 because of the following conflicting dependencies:
```
@rails/webpacker@5.4.3 requires loader-utils@^1.4.0 via a transitive dependency on babel-loader@8.2.2
@rails/webpacker@5.4.3 requires loader-utils@^1.2.3 via a transitive dependency on css-loader@3.6.0
@rails/webpacker@5.4.3 requires loader-utils@^1.1.0 via mini-css-extract-plugin@0.9.0
@rails/webpacker@5.4.3 requires loader-utils@^1.1.0 …
```
> [Security] Selectively bump loader-utils to v1.4.2

- config/webpack/production.js
Omit asset source maps from the production environment, as to reduce the number of 500 http requests to said assets.
> Omit asset sourcemaps from prod env

- app/forms/legal_aid_applications/has_other_proceedings_form.rb
- app/models/legal_aid_application.rb
- app/services/legal_framework/lead_proceeding_assignment_service.rb
- spec/models/legal_aid_application_spec.rb
- spec/requests/providers/has_other_proceedings_controller_spec.rb
- spec/services/legal_framework/lead_proceeding_assignment_service_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3659)
-Remove validation that there is a domestic abuse proceeding (where the provider has full_section_8 permission)
-Make first proceeding added the lead_proceeding (currently it is the first domestic abuse proceeding)
-Remove redundant find_or_set_lead_proceeding method …
> Ap 3659 remove domestic abuse proceeding limitation

- .github/dependabot.yml
We don't use the `sprockets` gem anymore, so we don't need to ignore it anymore.
> Remove redundant dependabot ignore rule

- .erb-lint.yml
- app/views/shared/forms/_applicant_form.html.erb
- app/views/shared/forms/_cash_income_form.html.erb
- app/views/shared/forms/_cash_outgoings_form.html.erb
- app/views/shared/forms/_date_input_fields.html.erb
- app/views/shared/forms/_date_part_input_fields.html.erb
- app/views/shared/forms/_error_summary.html.erb
- app/views/shared/forms/_error_summary_hidden.html.erb
- app/views/shared/forms/_next_action_buttons.html.erb
- app/views/shared/forms/_offline_accounts_form.html.erb
- app/views/shared/forms/_radio_inputs.html.erb
- app/views/shared/forms/_text_fields.html.erb
- app/views/shared/forms/_types_of_income_form.html.erb
- app/views/shared/forms/_types_of_outgoings_form.html.erb
- app/views/shared/forms/proceedings_types/_legacy_proceeding_type_form.html.erb
- app/views/shared/forms/proceedings_types/_proceeding_type.html.erb
- app/views/shared/forms/received_benefit_confirmation/_form.html.erb
- app/views/shared/forms/revealing_checkbox/_attribute.html.erb
Before, all templates in `app/views/shared/forms` were excluded from Rubocop linting.
This removes that rule, and resolves all failures.
All failures were resolved with the `--autocorrect` flag, and are all trivial.
> Address Rubocop erblint failures in `app/views/shared/forms`

- db/migrate/20221201085138_remove_enhanced_bank_upload_from_settings.rb
- db/schema.rb
In #4638 the `enhanced_bank_upload` column in the `Setting` model was ignored, and `Setting.enhanced_bank_upload?` always returns `true`.
This safely removes the `enhanced_bank_upload` column from the `settings` table.
> Remove `enhanced_bank_upload` column from settings

- app/helpers/means_report_helper.rb
- app/models/cfe/submission.rb
- app/models/legal_aid_application.rb
- app/models/setting.rb
- app/services/cfe/service_set.rb
- app/services/flow/flows/provider_capital.rb
- app/services/flow/flows/provider_start.rb
- app/views/providers/means_summaries/_income_assessment.html.erb
- app/views/shared/check_answers/_income_result.html.erb
- app/views/shared/check_answers/_income_summary.html.erb
- app/views/shared/review_application/_income_payments_and_assets_for_bank_statement_upload.html.erb
- spec/helpers/means_report_helper_spec.rb
- spec/models/cfe/submission_spec.rb
- spec/models/legal_aid_application_spec.rb
- spec/models/setting_spec.rb
- spec/requests/providers/client_completed_means_spec.rb
- spec/services/cfe/service_set_spec.rb
- spec/services/reports/means_report_creator_spec.rb
Now that the enhanced bank upload functionality has been released to all
providers with bank statement upload permissions and the flag always returns
`true`, the `enhanced_bank_upload?` method no longer means anything.
This replaces its usage with calls to `uploading_bank_statements?`.
While there are some applications that have not been completed that used the
original, non-enhanced bank statement upload journey, these are nominal.
Any issues that arise will be dealt with manually, although it is likely the
small number of affected applications (~ 5) will remain inactive.
> Remove `enhanced_bank_upload?` methods

- app/services/flow/flows/provider_start.rb
- spec/requests/providers/applicant_details_spec.rb
Remove unneeded forward step logic?
[Came out of story](https://dsdmoj.atlassian.net/browse/AP-3608)
Added in this PR https://github.com/ministryofjustice/laa-apply-for-legal-aid/pull/1408
I am, nonetheless, unable to find a situation where this is used except in tests.
I have removed the example that tests this specific logic to see
what else falls out of the woodwork. …
> Remove unneeded forward step logic?

- app/controllers/providers/application_merits_task/client_offered_undertakings_controller.rb
- app/forms/providers/application_merits_task/client_offered_undertakings_form.rb
- app/views/providers/application_merits_task/client_offered_undertakings/show.html.erb
- config/locales/en/activemodel.yml
- config/locales/en/providers.yml
- features/providers/mini-loop/merits_questions.feature
- spec/forms/providers/application_merits_task/client_offered_undertakings_form_spec.rb
- spec/requests/providers/application_merits_task/client_offered_undertakings_controller_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3668)
Ensure the providers enter a response for the client undertakings question regardless of whether they answer yes or no
This extrapolates and interpolates the values into split inputs on the page and merges into the single, additional_information, field in the database  …
> AP-3668: Update Client Undertaking question

- .git-blame-ignore-revs
- app/models/applicant.rb
- features/providers/means_report.feature
- features/step_definitions/means_report_steps.rb
- spec/factories/legal_aid_applications.rb
- spec/models/applicant_spec.rb
Modify applicant#age to address non means tested application logic
Ensure means and merits reports can be generated for 
Non-means-tested (NMT) applications
For NMT applications the age should be based on the value
stored in the db. This is set at the relevant point which
for NMT is when providers continue past the first check 
your answers page. …
> [AP-3685] Modify applicant#age to apply non means tested logic

- spec/factories/cfe_results.rb
- spec/factories/cfe_results/empty/results.rb
- spec/factories/cfe_results/v3/results.rb
- spec/factories/cfe_results/v4/results.rb
- spec/factories/cfe_results/v5/results.rb
- spec/factories/cfe_submissions.rb
- spec/factories/legal_framework_submissions.rb
- spec/factories/scope_limitations.rb
- spec/factories/submissions.rb
Before, some factory associations were _always_ created, even 
when the parent record was not.
This behaviour was unexpected (to me at least), and I suspect 
unintentional.
Now, factory associations are not explicitly created, and instead 
defer to the parent object strategy (e.g if a `cfe_result` is built 
rather than created, its associated `submission` will also be built).
> Clean up factory associations

- .github/workflows/anonymise_check.yml
- .github/workflows/base-docker-image.yml
- .github/workflows/ci-docker-image.yml
- .github/workflows/codeql-analysis.yml
This PR:
* Updates all CodeQL actions to v2 as v1 is due to be deprecated on Jan 18th 2023
* Updates all checkout actions to v3 as v2 uses node12 which has also been deprecated
> Fix: Update the github action versions

- spec/factories/other_assets_declarations.rb
- spec/factories/providers.rb
This PR address some recent feature flickers:
* The features/providers/check_single_employment.feature (and probably others) would intermittently fail becuase the seed would generate a value below 500 and cause the validation to fail and leave it on the previous page
This updates the `other_assets_declaration` factory to ensure a valuable_items_value cannot be below the validation threshold
* We saw an instance where a test failed because faker randomly picked `rose` as a username but there is an existing provider in the seeded table that caused it to fail
This adds a zero-padded three-digit suffix to the username field in the `provider` factory to ensure this does not recur, e.g. `rose_056` …
> Fix: Flaky features
