ministryofjustice/laa-apply-for-legal-aid

Dockerfile, README.md
=> feature/AP-96  Added dockerfile to build containers.

.rubocop.yml, app/models/applicant.rb, app/models/legal_aid_application.rb, db/migrate/20180821121644_add_applicant_reference_legal_aid_applications.rb, db/migrate/20180821122427_remove_legal_aid_application_reference_applicant.rb, spec/models/applicant_spec.rb, spec/models/legalaid_application_spec.rb
The current CircleCI build is failing due to Rubocop errors (my fault - Sergio had introduced Rubocop in the interim, I didn't rebase from master before pushing so all tests passed in my branch but fail after the merge). These changes will fix those errors.
=> Fix Rubocop errors

README.md, app/controllers/proceeding_types_controller.rb, app/controllers/v1/proceeding_types_controller.rb, app/serializers/proceeding_types_serializer.rb, config/routes.rb, db/migrate/20180911143012_add_new_columns_to_proceeding_types.rb, db/schema.rb, db/seeds/proceeding_types.rb, spec/requests/proceeding_types_controller_spec.rb
This is the first part of the story where I have provided a GET endpoint on API.
This will be utilised by the provider frontend rather than reading from json file.
https://dsdmoj.atlassian.net/browse/AP-119
=> Feature/ap 199- GET end point to pull proceeding types from API

app/controllers/v1/addresses_controller.rb, app/models/address.rb, app/models/applicant.rb, app/serializers/address_serializer.rb, app/serializers/applicant_serializer.rb, config/locales/en.yml, config/routes.rb, db/migrate/20181011143410_create_addresses.rb, db/schema.rb, spec/factories/addresses.rb, spec/models/address_spec.rb, spec/rails_helper.rb, spec/requests/applicants/create_address_spec.rb, spec/requests/applicants/create_applicant_spec.rb, spec/requests/applicants/patch_applicant_spec.rb, spec/requests/legalaid_applications/show_application_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-153)
AP153 requires that an address can be entered which is associated with an applicant, an applicant can have more than one address. A new table has been created which references the applicants table and validation applied in line with the design requirements.
=> Add address table and endpoint to handle addresses

Brewfile, README.md, bin/setup
1. Add `postgresql` to `Brewfile` and add `brew bundle` instruction to README
2. change `system` to `system!` in `bin/setup` for consistency with other commands and so it shows an error if the command fails
3. Remove incomplete endpoint documentation from README as we should generate documentation from the code with something like Swagger
=> More small improvements to the setup process and README file

app/controllers/base_controller.rb, app/controllers/citizens/additional_accounts_controller.rb, app/helpers/gov_uk_form_helper.rb, app/views/citizens/additional_accounts/index.html.erb, app/views/citizens/additional_accounts/new.html.erb, app/views/shared/forms/_fieldset_header.html.erb, app/views/shared/forms/_form_group.html.erb, app/views/shared/forms/_radio_inputs.html.erb, config/locales/en.yml, spec/requests/citizens/additional_accounts_spec.rb
[AP-71](https://dsdmoj.atlassian.net/browse/AP-71)
This is the original version of AP-71 before I messed up the Squash. It included the better version of `GovUkFormHelper`
=> AP-71 Allow applicant to select whether they have additional accounts

app/views/citizens/accounts/index.html.erb, config/locales/en.yml
[Link to story](https://dsdmoj.atlassian.net/browse/AP-70)
Add the missing title for citizens accounts index page
=> add title to citizens accounts index page

README.md, docs/README_alt.md, docs/troubleshooting.md
* Deprecated alternative setup
* Added a troubleshooting section
* Added some information related with the HELM setup
=> Update README instructions

.circleci/config.yml, Gemfile, Gemfile.lock, config/application.rb, spec/i18n_spec.rb
* Use appropriate CircleCI cache for rubygems bundle
CircleCI generated a previous cache with incorrect data and it's not possible to overwrite the cache without asking CircleCI support to delete it. This:
1. uses a different name for the cache
2. ensures the path that bundle check and bundle install use is the same as the cached one.
* Set default test suite to RSpec
* Spec to check there are no translations missing
=> Minor app tweaks

app/controllers/providers/check_your_answers_controller.rb, app/views/providers/check_your_answers/confirm.html.erb, config/locales/en.yml, features/providers/civil_application_journey.feature, features/providers/step_definitions/civil_journey_steps.rb, spec/requests/providers/check_your_answers_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-200)
- Add application confirmation page
- update feature tests
- update specs
=> AP-200 confirm application created

app/views/layouts/_header.html.erb, config/locales/en.yml
- updated gov.uk logo link to gov.uk 
- move copy to the locale
=> AP-193 header navigation to gov.uk

app/helpers/application_helper.rb, app/views/layouts/_header.html.erb, config/locales/en.yml, features/providers/civil_application_journey.feature, features/providers/step_definitions/civil_journey_steps.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-194)
- add a link to header to link to  provider home page 
=> AP-194 provider home navigation

app/controllers/concerns/providers/steppable.rb, app/controllers/providers/applicants_controller.rb, app/controllers/providers/emails_controller.rb, app/forms/applicants/basic_details_form.rb, app/models/applicant.rb, app/views/providers/applicants/show.html.erb, config/routes.rb, spec/models/applicant_spec.rb, spec/requests/providers/applicants_spec.rb, spec/requests/providers/emails_spec.rb, spec/requests/providers/legal_aid_applications_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-199)
- on navigating to any page in the application any previously entered information is visible
- update specs
=> AP-199 show previously entered information

app/controllers/concerns/providers/steppable.rb, app/controllers/providers/check_benefits_controller.rb, app/controllers/providers/check_provider_answers_controller.rb, app/views/providers/check_benefits/index.html.erb, app/views/providers/check_provider_answers/index.html.erb, features/cassettes/Civil_application_journeys/Completes_the_application_using_address_lookup.yml, features/providers/civil_application_journey.feature, features/providers/step_definitions/civil_journey_steps.rb, spec/factories/addresses.rb, spec/factories/applicants.rb, spec/factories/legal_aid_applications.rb, spec/requests/providers/address_selections_spec.rb, spec/requests/providers/addresses_spec.rb, spec/requests/providers/check_benefits_spec.rb, spec/requests/providers/check_provider_answers_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-207)
- move check your answers page before benefit checker is run 
- update back links 
- update specs
=> AP-207 Move check your answers page in flow

app/views/providers/address_selections/show.html.erb, package-lock.json, package.json
Update govuk to the most recent version
[Link to story](https://dsdmoj.atlassian.net/browse/AP-219)
=> Update govuk-frontend to the most recent version (2.4.0)

Gemfile, app/controllers/citizens/own_homes_controller.rb, app/controllers/citizens/percentage_homes_controller.rb, app/forms/legal_aid_applications/percentage_home_form.rb, app/helpers/application_helper.rb, app/views/citizens/own_homes/show.html.erb, app/views/citizens/percentage_homes/show.html.erb, app/views/layouts/application.html.erb, config/locales/en.yml, config/routes.rb, db/migrate/20181206132736_add_percentage_home_to_legal_aid_application.rb, db/schema.rb, spec/forms/legal_aid_applications/percentage_home_form_spec.rb, spec/requests/citizens/percentage_home_spec.rb
[AP-215](https://dsdmoj.atlassian.net/browse/AP-215)
Added the page **What % share of your home do you legally own?**
=> AP-215 Add What % share of your home do you legally own? page

app/controllers/citizens/shared_ownerships_controller.rb, app/forms/legal_aid_applications/shared_ownership_form.rb, app/models/legal_aid_application.rb, app/views/citizens/shared_ownerships/_shared_ownership_item.html.erb, app/views/citizens/shared_ownerships/show.html.erb, config/locales/en.yml, config/routes.rb, db/migrate/20181205144814_add_shared_ownership_to_legal_aid_applications.rb, db/schema.rb, spec/forms/legal_aid_applications/shared_ownership_form_spec.rb, spec/models/legal_aid_application_spec.rb, spec/requests/citizens/shared_ownerships_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-214)
- Added the page "Do you own your home with anyone else?"
- Added SHARED_OWNERSHIP_REASONS constants in legal_aid_application model
=> AP-214 Citizen capital 1d. Shared ownership

app/views/providers/about_the_financial_assessments/show.html.erb, app/views/providers/check_provider_answers/index.html.erb, config/locales/en.yml
[Link to story](https://dsdmoj.atlassian.net/browse/AP-241)
Move submit explanation text from check your answers page to about the online financial assessment page
=> AP-241 move submit explanation text

app/views/citizens/accounts/index.html.erb, app/views/citizens/information/show.html.erb, app/views/citizens/legal_aid_applications/show.html.erb, app/views/citizens/own_homes/show.html.erb, app/views/home/index.html.erb, app/views/layouts/_footer.html.erb, app/views/providers/about_the_financial_assessments/show.html.erb, app/views/providers/address_lookups/_form.html.erb, app/views/providers/address_selections/show.html.erb, app/views/providers/addresses/_form.html.erb, app/views/providers/applicants/show.html.erb, app/views/providers/check_benefits/index.html.erb, app/views/providers/check_provider_answers/_check_provider_answers_item.html.erb, app/views/providers/legal_aid_applications/index.html.erb, app/views/providers/start/index.html.erb, app/views/shared/forms/_error_summary.html.erb, config/locales/en.yml
[Link to story](https://dsdmoj.atlassian.net/browse/AP-237)
- move views text to translation file
=> AP-237 review use of translation framework

config/locales/en.yml
=> AP-227 correct spelling of repossession

.gitignore, .vscode/launch.json, app/controllers/providers/shared_ownerships_controller.rb, app/forms/legal_aid_applications/shared_ownership_form.rb, app/views/citizens/shared_ownerships/_shared_ownership_item.html.erb, app/views/citizens/shared_ownerships/show.html.erb, app/views/providers/shared_ownerships/show.html.erb, app/views/shared/forms/_shared_ownership_form.html.erb, app/views/shared/forms/shared_ownership_form/_shared_ownership_item.html.erb, config/locales/en.yml, config/routes.rb, spec/requests/providers/shared_ownerships_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-224)
- create a single shared ownership form the citizens  and provider journey 
- add provider shared ownership routes
=> AP-224 Provider capital 1d. Shared ownership

db/seeds/provider.rb
Fix issues with seeding on staging
=> fix issues provider seeding

app/controllers/concerns/providers/steps.rb, app/controllers/providers/check_provider_answers_controller.rb, app/controllers/providers/other_assets_controller.rb, app/controllers/providers/savings_and_investments_controller.rb, app/controllers/providers/shared_ownerships_controller.rb, app/models/legal_aid_application.rb, app/views/providers/check_provider_answers/index.html.erb, app/views/providers/savings_and_investments/show.html.erb, config/locales/model_enum_translations.en.yml, spec/factories/legal_aid_applications.rb, spec/requests/providers/check_provider_answers_spec.rb, spec/requests/providers/other_assets_spec.rb, spec/requests/providers/outstanding_mortgage_spec.rb, spec/requests/providers/own_home_spec.rb, spec/requests/providers/percentage_home_spec.rb, spec/requests/providers/property_value_spec.rb, spec/requests/providers/restrictions_spec.rb, spec/requests/providers/savings_and_investments_spec.rb, spec/requests/providers/shared_ownerships_spec.rb, spec/support/back_link_matcher.rb
This PR is to ensure all the back links go to the appropriate page
depending on what previous answers were given.
[Link to story](https://dsdmoj.atlassian.net/browse/AP-253)
Updated steps.rb, and where necessary the logic in the controllers.
Added back link tests in all the request specs
=> AP-253 Ensure back links on provider journey work as expected

config/locales/en.yml, spec/forms/savings_amounts/savings_amounts_form_spec.rb
[Jira AP-277](https://dsdmoj.atlassian.net/browse/AP-277)
Makes the error message more descriptive. Also updated the specs to match.
=> AP-277 Update error message on ApplicantCapitalSavings#show

app/views/layouts/_footer.html.erb, config/locales/en.yml
Change the footer to match the new design
[Link to story](https://dsdmoj.atlassian.net/browse/AP-272)
Current footer design is out of date, placeholder values used for contact and feedback until these are confirmed
=> Update footer to match the required design

app/views/layouts/_footer.html.erb, features/providers/civil_application_journey.feature, features/providers/step_definitions/civil_journey_steps.rb, spec/requests/contact_spec.rb
PR addressing @reggieb's comment from PR https://github.com/ministryofjustice/laa-apply-for-legal-aid/pull/218
=> AP-305 address feedbacks from code review

config/locales/en.yml
This is a test PR for content changes. It's okay to merge, just testing the process.
Content change:
Savings and investments question:
-- updated hint text on signatory on other accounts
=> Change to savings question

app/models/legal_aid_application.rb, app/models/merits_assessment.rb, db/migrate/20190123111544_create_merits_assessments.rb, db/schema.rb
Creating `legal_aid_application.merits_assessment` model and table
=> Create merits_assessment model

app/lib/govuk_elements_form_builder/form_builder.rb, spec/lib/govuk_elements_form_builder/form_builder_spec.rb
Adding `govuk_text_area` to `FormBuilder`
=> Add text_area component to FormBuilder

app/controllers/concerns/providers/steps.rb, app/controllers/providers/check_passported_answers_controller.rb, app/controllers/providers/client_received_legal_helps_controller.rb, app/forms/base_form.rb, app/forms/merits_assessments/client_received_legal_help_form.rb, app/lib/govuk_elements_form_builder/form_builder.rb, app/models/concerns/legal_aid_application_state_machine.rb, app/views/providers/client_received_legal_helps/show.html.erb, config/locales/en.yml, config/routes.rb, db/migrate/20190123151412_add_client_received_legal_help_to_nerits_assessments.rb, db/migrate/20190123151514_add_application_purpose_to_merits_assessments.rb, db/schema.rb, features/providers/civil_application_journey.feature, spec/factories/merits_assessments.rb, spec/factories/restrictions.rb, spec/requests/providers/check_passported_answers_spec.rb, spec/requests/providers/client_received_legal_helps_spec.rb
[AP-260](https://dsdmoj.atlassian.net/browse/AP-260)
- Add `text_area` to `FormBuilder`
- new page: Merits Assessment - Has client received legal help for the matter?
=> AP-260 Merits Assessment - Has client received legal help for the matter?

app/controllers/concerns/providers/steps.rb, app/controllers/providers/estimated_legal_costs_controller.rb, app/forms/merits_assessments/estimated_legal_cost_form.rb, app/lib/govuk_elements_form_builder/form_builder.rb, app/views/providers/estimated_legal_costs/show.html.erb, app/views/shared/forms/_estimated_legal_cost_form.html.erb, config/locales/en.yml, config/routes.rb, db/migrate/20190129120515_add_estimated_legal_cost_to_merits_assessments.rb, db/schema.rb, spec/lib/govuk_elements_form_builder/form_builder_spec.rb, spec/requests/providers/estimated_legal_costs_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP263)
- Add new page: Merits Assessment - What are the estimated legal costs of doing the work?
- Updated FormBuilder to create a text box without a label
=> Ap 263 Merits Assessment - What are the estimated legal costs of doing the work?

app/controllers/concerns/providers/steps.rb, app/controllers/providers/check_provider_answers_controller.rb, app/controllers/providers/proceedings_types_controller.rb, app/views/providers/applicants/show.html.erb, app/views/providers/check_provider_answers/index.html.erb, app/views/providers/proceedings_types/show.html.erb, app/views/shared/forms/_next_action_buttons_form.html.erb, config/locales/en.yml, features/cassettes/Civil_application_journeys/I_am_able_to_clear_proceeding_on_the_proceeding_page.yml, features/cassettes/Civil_application_journeys/I_want_to_return_to_the_check_your_answers_page_without_changing_proceeding_type.yml, features/cassettes/Civil_application_journeys/No_results_returned_is_seen_on_screen_when_invalid_proceeding_search_entered.yml, features/providers/civil_application_journey.feature, features/providers/step_definitions/civil_journey_steps.rb, spec/requests/providers/address_selections_spec.rb, spec/requests/providers/addresses_spec.rb, spec/requests/providers/application_dependable_spec.rb, spec/requests/providers/check_provider_answers_spec.rb, spec/requests/providers/legal_aid_applications_spec.rb, spec/requests/providers/proceedings_types_spec.rb
[AP-279](https://dsdmoj.atlassian.net/browse/AP-279)
Move legal proceedings page to between the address selection on the check answers page
=> AP-279 Move legal proceedings page

app/controllers/concerns/providers/steps.rb, app/controllers/providers/check_merits_answers_controller.rb, app/controllers/providers/merits_declarations_controller.rb, app/controllers/providers/statement_of_cases_controller.rb, app/controllers/providers/success_prospects_controller.rb, app/models/concerns/legal_aid_application_state_machine.rb, app/views/providers/check_merits_answers/show.html.erb, config/locales/en.yml, config/locales/en/generic.yml, config/locales/en/model_enum_translations.yml, config/locales/en/providers.yml, config/locales/en/shared.yml, config/routes.rb, db/schema.rb, features/providers/civil_application_journey.feature, spec/factories/legal_aid_applications.rb, spec/factories/merits_assessments.rb, spec/factories/statement_of_cases.rb, spec/requests/providers/check_merits_answers_spec.rb, spec/requests/providers/estimated_legal_costs_spec.rb, spec/requests/providers/merits_declarations_spec.rb, spec/requests/providers/statement_of_case_spec.rb, spec/requests/providers/success_prospects_spec.rb
[AP-266](https://dsdmoj.atlassian.net/browse/AP-266)
Create a new Check Your Answers page for merits assessment questions. This displays the data entered on the previous merits pages. The 'Change' links and related functionality have not been implemented; they will be done under [AP-267](https://dsdmoj.atlassian.net/browse/AP-267).
Note: two of the merits pages (statement of case, prospects of success) are not finished yet, so have not been fully included here. I'll add the extra functionality when they are ready.
=> Add check merits answers screen

app/controllers/providers/address_lookups_controller.rb, app/views/shared/access_denied.html.erb, config/locales/en/shared.yml, spec/requests/providers/address_lookups_spec.rb, spec/requests/providers/base_controller_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-311)
Update styling on the  no access page
=> AP-311 no access page styling

app/controllers/providers/legal_aid_applications_controller.rb, app/models/legal_aid_application.rb, spec/requests/providers/legal_aid_applications_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-347)
Update `providers/applications` to only display the current provider applications.
=> AP-347 Restrict applications to creator

app/models/concerns/legal_aid_application_state_machine.rb, spec/requests/citizens/check_answers_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-340)
The above ticket is incorrect, as this work has been completed in the follow [PR](https://github.com/ministryofjustice/laa-apply-for-legal-aid/pull/256).  What i have done is the citizens capital questions.
=> AP-221 citizens capital questions - ensure related fields are in sync

.git-crypt/keys/default/0/7F6D3B095238754680D42F49886C4C04BB346D41.gpg
New collaborators:
BB346D41 Kerin Cosford <cosford@gmail.com>
=> Add 1 git-crypt collaborator

app/controllers/concerns/backable.rb, app/controllers/concerns/flowable.rb, app/services/flow/base_flow_service.rb
=> Small tweak to Backable to replace shift while

config/sidekiq.yml
=> Fix sidekiq mailer queue

app/assets/stylesheets/check-your-answers.scss, app/controllers/citizens/legal_aid_applications_controller.rb, app/helpers/check_answers_helper.rb, app/views/citizens/check_answers/index.html.erb, app/views/shared/_check_answers_assets.html.erb, app/views/shared/check_answers/_item.html.erb, app/views/shared/check_answers/_items.html.erb, app/views/shared/check_answers/_no_link_item.html.erb, app/views/shared/check_answers/_no_link_items.html.erb, app/views/shared/check_answers/_one_link_section.html.erb, config/locales/en/citizens.yml, config/locales/en/generic.yml, features/citizens/citizens.feature, features/citizens/step_definitions/citizens_steps.rb, features/support/steps_helper.rb, spec/factories/legal_aid_applications.rb, spec/requests/citizens/check_answers_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-344)
- Update citizens capital check your answer page styling
- Amend specs
- Add feature tests
=> AP-344 Applicant check your answers 'Capital' page styling & change links

config/locales/en/models.yml, config/routes.rb
[Jira AP-376](https://dsdmoj.atlassian.net/browse/AP-376)
Most of the work for this has already been done. So this just adds a couple of tweaks:
- Updates the page titles so they start with "Your ..."
- Changes the routes so that the urls are in the form: `citizens/transactions/:transaction_type`. So for example: `citizens/transactions/maintenance_in`
=> AP-376 Identify other income types

config/locales/en/models.yml, spec/requests/citizens/identify_types_of_incomes_spec.rb, spec/requests/citizens/identify_types_of_outgoings_spec.rb
=> Bug fix. Add missing locales

app/views/layouts/_header.html.erb
AP-398 update code for toggling menu
=> AP-398 update code for toggling menu

app/controllers/citizens/other_assets_controller.rb, spec/requests/citizens/other_assets_spec.rb
Fix for bug
https://sentry.service.dsd.io/mojds/apply-laa-apply-for-legal-aid-/issues/35121/
https://sentry.service.dsd.io/mojds/apply-for-legal-aid-staging/issues/35135/
=> Fix bug when submitting the other_assets form in the citizen journey

app/controllers/citizens/incoming_transactions_controller.rb, app/controllers/citizens/outgoing_transactions_controller.rb, app/services/flow/flows/citizen_income.rb, app/views/citizens/income_summary/_income_type_item.html.erb, app/views/citizens/outgoings_summary/_outgoing_type_item.html.erb, app/views/citizens/transactions/show.html.erb, config/routes.rb, features/citizens/citizens.feature, features/providers/step_definitions/civil_journey_steps.rb, spec/requests/citizens/transactions_spec.rb
amend citizen flow to include income and outgoing page
[Link to story](https://dsdmoj.atlassian.net/browse/AP-406)
Julien helped me to split transactions into incoming and outgoing transactions and create the relevant controllers.
Updated the citizen flow to match the design, updated the cucumber tests to incorporate the new journey elements.
=> Ap 406 citizen flow

app/controllers/citizens/income_summary_controller.rb, app/controllers/citizens/outgoings_summary_controller.rb, app/models/concerns/legal_aid_application_state_machine.rb, app/views/citizens/bank_transactions/_list_selected.html.erb, app/views/citizens/income_summary/_income_type_item.html.erb, app/views/citizens/outgoings_summary/_outgoing_type_item.html.erb, app/views/citizens/outgoings_summary/index.html.erb, config/locales/en/citizens.yml, spec/factories/transaction_types.rb, spec/requests/citizens/income_summary_spec.rb, spec/requests/citizens/outgoings_summary_spec.rb
[Jira AP-380](https://dsdmoj.atlassian.net/browse/AP-380)
Add selected transactions to summary of regular payments.
Reworks code added in AP-375 so that it can be used here too.
=> AP-380 Add selected transactions to summary of regular payments

app/views/citizens/income_summary/index.html.erb, app/views/citizens/outgoings_summary/index.html.erb, config/locales/en/citizens.yml, features/citizens/citizens.feature, features/providers/step_definitions/civil_journey_steps.rb, spec/requests/citizens/transactions_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-425)
- amend title of page
- add category-specific link text to each transaction type
=> AP-425 Refine outgoing payment summary screen

app/services/true_layer/sample_data.rb
[AP-473](https://dsdmoj.atlassian.net/browse/AP-473)
Updating bank transactions data when bypassing TrueLayers' data
=> AP-473 Update bank transactions data

helm_deploy/apply-for-legal-aid/templates/ingress.yaml
Fix our ingress config following a change from cloud-platform.
https://mojdt.slack.com/archives/CH6D099DF/p1554135480007100
**TODO later :**
- cleanup our ingress config and the matching `Values` config. 
=> Fix ingress host

app/views/home/index.html.erb, app/views/providers/start/index.html.erb, config/locales/en/providers.yml, spec/requests/providers/start_spec.rb
[AP-427](https://dsdmoj.atlassian.net/browse/AP-427)
=> AP-427 Update copy of provider's start page

app/views/providers/address_selections/show.html.erb, app/views/shared/page_templates/_form_page_template.html.erb
Previous fix included the correct fix, but also introduced a change that broke header styles of other pages
[Jira Ticket AP-399](https://dsdmoj.atlassian.net/browse/AP-399)
=> AP-399 Correction of address dropdown width fix

app/helpers/flow_helper.rb, app/helpers/gov_uk_form_helper.rb, app/views/citizens/accounts/index.html.erb, app/views/citizens/additional_accounts/index.html.erb, app/views/citizens/additional_accounts/new.html.erb, app/views/citizens/check_answers/index.html.erb, app/views/citizens/consents/show.html.erb, app/views/citizens/identify_types_of_incomes/show.html.erb, app/views/citizens/identify_types_of_outgoings/show.html.erb, app/views/citizens/income_summary/index.html.erb, app/views/citizens/information/show.html.erb, app/views/citizens/outgoings_summary/index.html.erb, app/views/citizens/transactions/show.html.erb, app/views/providers/about_the_financial_assessments/show.html.erb, app/views/providers/check_benefits/index.html.erb, app/views/providers/check_passported_answers/show.html.erb, app/views/providers/check_provider_answers/index.html.erb, app/views/providers/start_merits_assessments/show.html.erb, app/views/shared/forms/_next_action_buttons.html.erb, config/locales/en/generic.yml, config/locales/en/providers.yml, features/citizens/citizens.feature, features/providers/check_your_answers.feature, features/providers/civil_application_journey.feature, features/providers/step_definitions/civil_journey_steps.rb, spec/requests/saml_sessions_spec.rb
[AP-350](https://dsdmoj.atlassian.net/browse/AP-350)
Change copy of Continue buttons. With a few exceptions (see Jira ticket)
=> AP-350 Change submit buttons' copy

app/services/true_layer/sample_data.rb
[AP-522](https://dsdmoj.atlassian.net/browse/AP-522)
=> AP-522 Change sample bank data to be more realistic

helm_deploy/grafana-dashboards/http_status_codes.yaml, helm_deploy/prometheus-alerts.yaml
[AP-432](https://dsdmoj.atlassian.net/browse/AP-432)
I created a Grafana dashboard which allows us to monitor HTTP status codes:
https://grafana.apps.cloud-platform-live-0.k8s.integration.dsd.io/d/36a118233e8f4e8ca66eac7ac86da1d4/laa-apply-http-status-codes?orgId=1
This PR contains the code of the dashboard and instructions on how to update it or create a new one
This PR also contains the code to create a Prometheus Alert for:
More than one hundred 404 errors in one day.
With a link to Kibana to see the details of the 404 errors.
=> AP-432 Grafana dashboard

app/controllers/providers/check_merits_answers_controller.rb, app/controllers/providers/means_summaries_controller.rb, app/controllers/providers/merits_declarations_controller.rb, app/helpers/application_helper.rb, app/models/concerns/legal_aid_application_state_machine.rb, app/services/flow/flows/provider_merits.rb, app/views/providers/check_merits_answers/show.html.erb, app/views/providers/merits_declarations/show.html.erb, app/views/shared/forms/_detailed_list.html.erb, app/views/shared/forms/_list_items.html.erb, config/locales/en/generic.yml, config/locales/en/model_enum_translations.yml, config/locales/en/providers.yml, db/migrate/20190417130107_add_submitted_at_to_merits_assessments.rb, db/schema.rb, features/providers/civil_application_journey.feature, features/providers/step_definitions/civil_journey_steps.rb, spec/factories/merits_assessments.rb, spec/models/legal_aid_application_spec.rb, spec/requests/providers/check_merits_answers_spec.rb, spec/requests/providers/means_summaries_spec.rb, spec/requests/providers/merits_declarations_spec.rb, spec/requests/providers/success_prospects_spec.rb
[AP-423](https://dsdmoj.atlassian.net/browse/AP-423)
- Move page after Check Answers
- Change copy
- Record timestamp when provider clicked the button]
- Fix this bug: https://sentry.service.dsd.io/mojds/apply-for-legal-aid-staging/issues/35215/
=> AP-423 Provider declaration

app/services/flow/flows/citizen_income.rb, features/citizens/citizens.feature
[Link to story](https://dsdmoj.atlassian.net/browse/AP-546)
I'm only removing the pages from the flow but not deleting them because they will be reused in the provider flow
=> AP-546 Remove transaction selection from applicant flow

app/controllers/providers/client_completed_means_controller.rb, app/services/flow/flows/provider_capital.rb, app/services/flow/key_point.rb, app/views/providers/client_completed_means/show.html.erb, app/views/providers/means_summaries/show.html.erb, config/locales/en/providers.yml, config/routes.rb, features/providers/civil_application_journey.feature, features/providers/step_definitions/civil_journey_steps.rb, spec/requests/citizens/declarations_spec.rb, spec/requests/providers/client_completed_means_spec.rb, spec/services/flow/key_point_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-549)
Add a new page at the beginning of the second provider flow. (after the applicant flow).
This new page contains information that was previously on the first "Check Answer" page of the second provider flow
=> AP-549 Split means summary page in two

app/controllers/providers/bank_transactions_controller.rb, app/controllers/providers/income_summary_controller.rb, app/models/bank_account.rb, app/models/bank_provider.rb, app/models/bank_transaction.rb, app/policies/legal_aid_application_policy.rb, app/services/flow/flows/provider_capital.rb, app/views/providers/bank_transactions/_list_selected.html.erb, app/views/providers/income_summary/_add_other_income.html.erb, app/views/providers/income_summary/_income_type_item.html.erb, app/views/providers/income_summary/index.html.erb, config/locales/en/providers.yml, config/locales/en/time.yml, config/routes.rb, features/providers/civil_application_journey.feature, spec/helpers/providers_helper_spec.rb, spec/models/legal_aid_application_spec.rb, spec/requests/providers/bank_transactions_spec.rb, spec/requests/providers/client_completed_means_spec.rb, spec/requests/providers/income_summary_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-550)
Add "Income summary" page to the provider flow
WIP
Base on AP-549 until it gets merged
=> Ap 550 move income summary to provider flow

app/views/citizens/accounts/index.html.erb, config/locales/en/citizens.yml, spec/requests/citizens/accounts_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-548)
On the `/citizens/accounts` page, add a link to add another account
=> AP-548 Add link to add another account

spec/services/save_applicant_means_answers_spec.rb
This test has been unreliable. This PR should fix the problem
=> Fix unreliable test

app/controllers/concerns/providers/application_dependable.rb, app/controllers/providers/incoming_transactions_controller.rb, app/controllers/providers/transactions_controller.rb, app/helpers/providers_helper.rb, app/services/flow/base_flow_service.rb, app/services/flow/flows/provider_capital.rb, app/views/providers/income_summary/_income_type_item.html.erb, app/views/providers/transactions/show.html.erb, config/locales/en/providers.yml, config/locales/en/transaction_types.yml, config/routes.rb, db/migrate/20190424092935_add_provider_step_params_to_legal_aid_applications.rb, db/schema.rb, spec/helpers/providers_helper_spec.rb, spec/requests/providers/transactions_spec.rb, spec/services/flow/base_flow_service_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-553)
Move incoming transaction pages to provider flow
=> AP-553 move incoming transaction pages to provider flow

app/controllers/providers/date_client_told_incidents_controller.rb, app/forms/incidents/told_on_form.rb, app/services/flow/flows/provider_merits.rb, app/views/providers/date_client_told_incidents/show.html.erb, app/views/shared/forms/_date_input_fields.html.erb, config/locales/en/activemodel.yml, config/locales/en/providers.yml, config/locales/en/shared.yml, config/routes.rb, db/migrate/20190425131605_add_told_on_to_incidents.rb, db/schema.rb, features/providers/civil_application_journey.feature, features/providers/step_definitions/civil_journey_steps.rb, spec/factories/incidents.rb, spec/requests/providers/date_client_told_incidents_spec.rb, spec/requests/providers/start_merits_assessments_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-492)
Adding new page to ask when did the applicant told the provider about the latest incident
I mostly copied the page and form Rob created for the `details_latest_incidents` page
=> AP-492 Adding new page to ask when did the applicant told the provider about the latest incident

app/controllers/providers/outgoings_summary_controller.rb, app/services/flow/flows/provider_capital.rb, app/views/providers/outgoings_summary/_add_other_outgoings.erb, app/views/providers/outgoings_summary/_outgoing_type_item.html.erb, app/views/providers/outgoings_summary/index.html.erb, config/locales/en/providers.yml, config/routes.rb, features/providers/civil_application_journey.feature, spec/requests/providers/income_summary_spec.rb, spec/requests/providers/outgoings_summary_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-551)
Add "Outgoings summary" page to the provider flow
=> AP-551 move outgoings summary to provider flow

app/views/citizens/restrictions/_form.html.erb, app/views/providers/restrictions/index.html.erb, config/locales/en/citizens.yml, config/locales/en/providers.yml, config/locales/en/restrictions.yml, features/citizens/citizens.feature, features/providers/check_your_answers.feature, features/providers/civil_application_journey.feature
[Link to story](https://dsdmoj.atlassian.net/browse/AP-506)
Update copy of restrictions page on both journeys
=> AP-506 Update copy of the Restrictions page

app/views/citizens/legal_aid_applications/index.html.erb, config/locales/en/citizens.yml
[Link to story](https://dsdmoj.atlassian.net/browse/AP-474)
Minor amendments to content and layout on /citizens/legal_aid_applications page.
=> AP-474 - Copy changes to /citizens/legal_aid_applications

app/views/citizens/information/show.html.erb, config/locales/en/citizens.yml, features/citizens/citizens.feature
[Link to story](https://dsdmoj.atlassian.net/browse/AP-475)
Updates the page to match the [prototype](https://apply-for-legal-aid-prototype.herokuapp.com/apply_for_legal_aid_prototype/bank_access_information).
=> AP-475 Update citizens/information page copy

app/models/transaction_type.rb, app/views/citizens/identify_types_of_incomes/show.html.erb, config/locales/en/citizens.yml, config/locales/en/transaction_types.yml
[Link to story](https://dsdmoj.atlassian.net/browse/AP-479)
Update copy and order of transaction type on the `/citizens/identify_types_of_income` page
=> AP-479 Update copy and order of types of income

app/controllers/status_controller.rb, app/services/malware_scanner.rb, helm_deploy/apply-for-legal-aid/templates/deployment_web.yaml, helm_deploy/prometheus-alerts.yaml, spec/requests/status_spec.rb, spec/services/malware_scanner_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-415)
- Add 2 more prometheus rules:
- Disk space
- Long requests
- improve health check endpoint to also check for:
- DB connection
- Redis connection
- Results of malware scanner
=> AP-415 Improving container's health status and add Prometheus rules

app/views/providers/outgoings_summary/_outgoing_type_item.html.erb, spec/requests/providers/outgoings_summary_spec.rb
[JIRA AP-583](https://dsdmoj.atlassian.net/browse/AP-583)
To be honest - I've just copied the structure used on the income summary page and added a test.
=> AP-583 Ensure link add transaction link still present when transactions exist

app/assets/javascripts/checkbox_control.es6, app/controllers/citizens/identify_types_of_incomes_controller.rb, app/helpers/gov_uk_form_helper.rb, app/views/citizens/identify_types_of_incomes/show.html.erb, app/views/shared/forms/_fieldset_header.html.erb, config/locales/en/activerecord.yml, config/locales/en/citizens.yml, features/citizens/citizens.feature, spec/requests/citizens/identify_types_of_incomes_spec.rb
[Jira AP-569](https://dsdmoj.atlassian.net/browse/AP-569)
This add a None Selected checkbox to the Update Types of Income Page in the Citizen Journey.
JavaScript is used to deselect selected checkboxes when the None Selected checkbox is checked.
An error is added if none of the checkboxes is selected.
=> AP 569 update types of income pages

config/initializers/sidekiq.rb
Avoid all these messages when running Sidekiq in development :
By only sending sidekiq metrics to prometheus in production and on a kubernetes deploy.
Replication the condition from this file: 
https://github.com/ministryofjustice/laa-apply-for-legal-aid/blob/master/config/initializers/prometheus_metrics.rb
=> FIX - Preventing PrometheusExporter to run on sidekiq in local

app/forms/citizens/other_assets_form.rb, app/models/legal_aid_application.rb, app/services/flow/flows/vehicle_steps.rb, app/views/shared/_check_answers_assets.html.erb, app/views/shared/_check_answers_vehicles.html.erb, config/locales/en/activemodel.yml, config/locales/en/shared.yml, db/migrate/20190516094442_remove_vehicle_from_other_assets_declaration.rb, db/schema.rb, features/providers/check_your_answers.feature, spec/factories/other_assets_declarations.rb, spec/forms/citizens/other_assets_form_spec.rb, spec/models/other_assets_declaration_spec.rb, spec/requests/citizens/other_assets_spec.rb, spec/requests/providers/check_passported_answers_spec.rb, spec/requests/providers/other_assets_spec.rb, spec/requests/providers/vehicles_spec.rb
[AP-593](https://dsdmoj.atlassian.net/browse/AP-593)
. Adding vehicle questions to passported "Check Answers" page
. Removing vehicle questions from `other_assets_declaration` model
=> AP-593 Adding vehicle questions to passported "Check Answers" page

app/controllers/concerns/flowable.rb, app/controllers/providers/identify_types_of_incomes_controller.rb, app/helpers/application_helper.rb, app/helpers/transaction_type_helper.rb, app/models/transaction_type.rb, app/services/flow/flows/provider_capital.rb, app/views/citizens/identify_types_of_incomes/show.html.erb, app/views/providers/identify_types_of_incomes/show.html.erb, app/views/providers/income_summary/_add_other_income.html.erb, app/views/providers/income_summary/_income_type_item.html.erb, app/views/providers/outgoings_summary/_outgoing_type_item.html.erb, app/views/shared/forms/_transaction_type_check_boxes.html.erb, app/views/shared/forms/_types_of_income_form.html.erb, config/locales/en/citizens.yml, config/locales/en/providers.yml, config/locales/en/shared.yml, config/locales/en/transaction_types.yml, spec/requests/providers/identify_types_of_incomes_spec.rb, spec/requests/providers/income_summary_spec.rb, spec/requests/providers/outgoings_summary_spec.rb
[JIRA AP-585](https://dsdmoj.atlassian.net/browse/AP-585)
Updates `Providers::IdentifyTypesOfIncomesController` with functionality from `Citizens::IdentifyTypesOfIncomesController`
=> AP-585 Add another type of income for provider

.circleci/config.yml, .gitignore, .hintrc, bin/generate_webhint_reports.sh, features/citizens/citizens.feature, features/providers/civil_application_journey.feature, features/support/env.rb, package-lock.json, package.json
Cucumber test marked with the `@webhint` tag will be processed by webhint and a report will be generated for each page.
1. Mark some cucumber features with the `@webhint tag`. (I marked two for the moment)
2. In CircleCI, click on the `hold_webhint` job to trigger the `run_webhint` job :
3. Once the `run_webhint` job is finished, you can find the report in the Artifacts tab, in the `webhint-reports/` folder.
Click the `index.html` files to see the reports :
https://circleci.com/gh/ministryofjustice/laa-apply-for-legal-aid/5268#artifacts/containers/0
0. Run `npm install` to install webhint
1. Run `./bin/generate_webhint_reports.sh` script
2. Reports can now be found in the `hint-report/ ` folder
- customise `.hintrc` file to choose which hints to apply
- fix errors and warnings reported by …
=> SPIKE AP-487 Setup CircleCI to generate webhint reports

app/models/ccms/submission.rb, app/services/ccms/case_add_status_requestor.rb, app/services/ccms/check_applicant_status_service.rb, app/services/ccms/check_case_status_service.rb, db/migrate/20190524142923_rename_poll_count_to_applicant_poll_count.rb, db/migrate/20190524143312_add_case_poll_count_to_ccms_submissions.rb, db/schema.rb, spec/factories/submissions.rb, spec/models/ccms/submission_spec.rb, spec/services/ccms/case_add_status_requestor_spec.rb, spec/services/ccms/check_applicant_status_service_spec.rb, spec/services/ccms/check_case_status_service_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-578)
Add a new service to poll CCMS to establish the success of a request to create a case in CCMS.
=> AP-578 - Poll CCMS case creation

app/services/flow/citizen_flow_service.rb, app/services/flow/flows/citizen_capital.rb, app/services/flow/flows/citizen_vehicle.rb, app/services/flow/flows/provider_capital.rb, app/services/flow/flows/provider_vehicle.rb, app/services/flow/provider_flow_service.rb, app/views/shared/_check_answers_assets.html.erb, app/views/shared/_check_answers_vehicles.html.erb, config/locales/en/shared.yml, features/citizens/citizens.feature, spec/requests/citizens/check_answers_spec.rb, spec/requests/citizens/vehicles/regular_uses_spec.rb, spec/requests/citizens/vehicles_spec.rb, spec/requests/providers/check_passported_answers_spec.rb, spec/services/flow/base_flow_service_spec.rb
[AP-594](https://dsdmoj.atlassian.net/browse/AP-594)
[AP-598](https://dsdmoj.atlassian.net/browse/AP-598)
Add links to Vehicle question for the applicant's check answers page
=> AP-594 applicant check vehicle answers

app/services/flow/flows/provider_vehicle.rb, app/views/shared/forms/other_assets/_second_home_conditional_checkbox.html.erb, features/providers/complete_and_check_means_answers.feature, features/providers/step_definitions/civil_journey_steps.rb, helm_deploy/apply-for-legal-aid/templates/_helpers.tpl, spec/factories/legal_aid_applications.rb, spec/requests/citizens/check_answers_spec.rb, spec/requests/contact_spec.rb, spec/requests/providers/check_merits_answers_spec.rb, spec/requests/providers/check_passported_answers_spec.rb, spec/requests/providers/means_summaries_spec.rb, spec/requests/providers/vehicles/regular_uses_spec.rb, spec/requests/providers/vehicles_spec.rb
[AP-595](https://dsdmoj.atlassian.net/browse/AP-595)
[AP-597](https://dsdmoj.atlassian.net/browse/AP-597)
Adding links to the vehicle questions in the non-passported provider's check answers pages.
=> AP-595 AP-597 non passported check vehicle answers

app/assets/javascripts/table-select-all.es6, app/assets/javascripts/table-sort.es6, app/assets/stylesheets/table-sort.scss, app/views/providers/transactions/show.html.erb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-599)
Restyled headers for table. Re-did select all link. Added padding to cells. Made table full-width. Redid screen reader wording.
Second PR for this change - first was corrupted with unidentified file changes.  This PR, total file change count is 4.
=> Ap 599 table headers 2

app/views/citizens/restrictions/_form.html.erb, app/views/providers/date_client_told_incidents/show.html.erb, app/views/shared/forms/_identify_types_of_outgoings_form.html.erb, app/views/shared/forms/_types_of_income_form.html.erb, app/views/shared/forms/vehicles/_estimated_value.html.erb, app/views/shared/forms/vehicles/_own_vehicle.html.erb, app/views/shared/forms/vehicles/_purchase_date.html.erb, app/views/shared/forms/vehicles/_remaining_payment.html.erb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-618)
Fix a few page headers
=> AP-618 Fix some page headers

app/views/shared/forms/_shared_ownership_form.html.erb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-460)
Added in code to encase question in fieldset.  Paired (remotely) with Rob.
=> AP-460 Added in missing fieldset code

app/services/ccms/applicant_add_status_response_parser.rb, app/services/ccms/base_response_parser.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-718)
As part of a spike to test the process to inject a case from apply into CCMS, I've noticed a couple of small issues that are causing problems. This PR fixes them.
=> Fix minor CCMS issues

config/environments/production.rb, config/environments/test.rb, package-lock.json, package.json
[Link to story](https://dsdmoj.atlassian.net/browse/AP-735)
- Ran `NPM Install`
- Ran `NPM Update`
- Amended `test.db` as per https://github.com/alphagov/govuk-frontend/issues/1350#issuecomment-493129270
=> Installed & Updated NPM.  Added new code to test.rb.

config/locales/en/citizens.yml
[Link to story](https://dsdmoj.atlassian.net/browse/AP-691)
Changed 2 lines of text in the citizens YML file as per the ticket
=> AP-691 text changes

app/assets/javascripts/table-select-all.es6, app/assets/javascripts/table-sort.es6, app/assets/stylesheets/narrow-table-display.scss, app/assets/stylesheets/table-category-column.scss, app/assets/stylesheets/table-sort.scss, app/views/providers/transactions/show.html.erb, config/locales/en/providers.yml, config/locales/en/transaction_types.yml
[Link to story](https://dsdmoj.atlassian.net/browse/AP-563)
Added new column.
CSS changes to account for narrow screens
CSS addition to account for new "tag" in category column
HTML changes for new column, and an annoying pseudo column needed for narrow screens.
JS changes for new functionality and to account for pseudo column.
New entries in YML files.
=> AP-563 Category column in transactions table

app/views/providers/check_provider_answers/index.html.erb, config/locales/en/providers.yml
[Link to story](https://dsdmoj.atlassian.net/browse/AP-674)
- Added new text to the YML file.
- Amended the HTML as per the ticket.
=> AP-674 & AP-690 Content updates on CYA screen and declaration screen

app/views/providers/statement_of_cases/show.html.erb, config/locales/en/activemodel.yml, config/locales/en/generic.yml, config/locales/en/providers.yml, features/providers/civil_application_journey.feature
[Link to story](https://dsdmoj.atlassian.net/browse/AP-603)
Removed redundant translations
Added new translations (including generic translations)
Amended translations
Amended structure of page
=> Ap 603 statement case content

app/controllers/citizens/savings_and_investments_controller.rb, app/controllers/providers/savings_and_investments_controller.rb, app/forms/savings_amounts/savings_amounts_form.rb, app/views/citizens/other_assets/show.html.erb, app/views/citizens/savings_and_investments/show.html.erb, app/views/providers/other_assets/show.html.erb, app/views/providers/savings_and_investments/show.html.erb, app/views/shared/forms/_identify_types_of_outgoings_form.html.erb, app/views/shared/forms/_savings_and_investments_form.html.erb, app/views/shared/forms/_types_of_income_form.html.erb, config/locales/en/activemodel.yml, config/locales/en/activerecord.yml, config/locales/en/citizens.yml, config/locales/en/providers.yml, config/locales/en/shared.yml, features/citizens/citizens.feature, features/providers/check_your_answers.feature, features/providers/civil_application_journey.feature, spec/forms/savings_amounts/savings_amounts_form_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-533)
Add 'none of these' checkbox and change copy on the savings and investment pages on both 
=> Ap 533 and ap 565 savings page changes

app/controllers/citizens/dependants/relationships_controller.rb, app/forms/dependant_form/relationship_form.rb, app/models/dependant.rb, app/services/flow/flows/citizen_dependants.rb, app/views/citizens/dependants/relationships/show.html.erb, app/views/shared/forms/dependants/_details.html.erb, app/views/shared/forms/dependants/_relationship.html.erb, config/locales/en/activemodel.yml, config/locales/en/citizens.yml, config/locales/en/shared.yml, config/routes.rb, db/migrate/20190702144049_add_relationship_to_dependant.rb, db/schema.rb, features/citizens/citizens.feature, spec/factories/dependants.rb, spec/models/dependant_spec.rb, spec/requests/citizens/dependants/details_spec.rb, spec/requests/citizens/dependants/relationships_spec.rb, spec/requests/citizens/dependants_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-722)
Dependant relationship page.
=> AP-722 dependant relationship

app/controllers/citizens/has_other_dependants_controller.rb, app/services/flow/flows/citizen_dependants.rb, app/views/citizens/has_other_dependants/show.html.erb, config/locales/en/citizens.yml, config/routes.rb, features/citizens/citizens.feature, spec/requests/citizens/dependants/details_spec.rb, spec/requests/citizens/dependants_spec.rb, spec/requests/citizens/has_other_dependants_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-726)
Add  "Do you have any other dependants?" page
=> AP-726 "Do you have any other dependants?" page

app/controllers/citizens/dependants/full_time_educations_controller.rb, app/forms/dependant_form/details_form.rb, app/forms/dependant_form/full_time_education_form.rb, app/services/flow/flows/citizen_dependants.rb, app/views/citizens/dependants/full_time_educations/show.html.erb, app/views/shared/forms/dependants/_full_time_educations.html.erb, config/locales/en/activemodel.yml, config/locales/en/shared.yml, config/routes.rb, db/migrate/20190704131448_add_in_full_time_education_to_dependants.rb, db/schema.rb, spec/factories/dependants.rb, spec/requests/citizens/dependants/full_time_educations_spec.rb, spec/requests/providers/percentage_home_spec.rb
[Jira AP-724](https://dsdmoj.atlassian.net/browse/AP-724)
Adds a page to the Citizen journey with forms etc.
=> AP-724 Add Dependant in full time education or training page

app/models/scope_limitation.rb, app/services/scope_limitations_populator.rb, db/migrate/20190704160038_create_scope_limitations.rb, db/schema.rb, db/seeds/scope_limitations.csv, db/seeds/scope_limitations.rb, spec/factories/scope_limitations.rb, spec/models/scope_limitation_spec.rb, spec/services/scope_limitations_populator_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-757)
Create a database table, model and seed data for scope limitations.
=> AP-757 - Create and populate scope limitations table and model

app/controllers/citizens/vehicles/purchase_dates_controller.rb, app/controllers/providers/vehicles/purchase_dates_controller.rb, app/forms/applicants/basic_details_form.rb, app/forms/vehicle_form/purchase_date_form.rb, app/views/shared/forms/_date_input_fields.html.erb, config/locales/en/activemodel.yml
[Link to story](https://dsdmoj.atlassian.net/browse/AP-740)
refactor existing date fields to use the `DateFieldBuilder` that was introduced by Rob.
=> Ap 740 date field builder

app/services/benefit_check_service.rb, app/services/flow/flows/provider_start.rb, app/views/providers/check_provider_answers/index.html.erb, config/locales/en/providers.yml, features/providers/civil_application_journey.feature, features/providers/step_definitions/civil_journey_steps.rb, spec/forms/legal_aid_applications/percentage_home_form_spec.rb, spec/requests/providers/check_benefits_spec.rb, spec/requests/providers/check_provider_answers_spec.rb, spec/requests/providers/proceedings_types_spec.rb, spec/requests/providers/substantive_applications_spec.rb, spec/requests/providers/used_delegated_functions_spec.rb
[AP-772](https://dsdmoj.atlassian.net/browse/AP-772)
[AP-773](https://dsdmoj.atlassian.net/browse/AP-773)
move **used delegated function** page earlier in the flow and modify flow after benefit checker
=> AP-772 move used delegated function page

app/controllers/citizens/dependants/assets_values_controller.rb, app/forms/dependant_form/assets_value_form.rb, app/services/flow/flows/citizen_dependants.rb, app/views/citizens/dependants/assets_values/show.html.erb, app/views/shared/forms/dependants/_assets_value.html.erb, config/locales/en/activemodel.yml, config/locales/en/citizens.yml, config/locales/en/shared.yml, config/routes.rb, db/migrate/20190708151000_add_assets_to_dependants.rb, db/schema.rb, spec/requests/citizens/dependants/assets_values_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-725)
=> AP-725 Dependant assets

Gemfile, Gemfile.lock, README.md, app/helpers/check_benefits_helper.rb, app/models/legal_aid_application.rb, app/services/benefit_check_service.rb, app/services/mock_benefit_check_service.rb, spec/models/legal_aid_application_spec.rb, spec/requests/providers/check_benefits_spec.rb, spec/services/benefit_check_service_spec.rb, spec/services/mock_benefit_service_check_spec.rb
Adds a simple lookup Mock of the benefit checker, for when we have problems accessing the Benefits Checker API
=> Add a Mock Benefit Checker that can be used in dev and test environments

app/controllers/citizens/dependants/monthly_incomes_controller.rb, app/forms/dependant_form/monthly_income_form.rb, app/services/flow/flows/citizen_dependants.rb, app/views/citizens/dependants/monthly_incomes/show.html.erb, app/views/shared/forms/dependants/_monthly_incomes.html.erb, config/locales/en/activemodel.yml, config/locales/en/shared.yml, config/routes.rb, db/migrate/20190704130740_add_income_to_dependants.rb, db/schema.rb, features/citizens/citizens.feature, spec/requests/citizens/dependants/full_time_educations_spec.rb, spec/requests/citizens/dependants/monthly_incomes_spec.rb, spec/requests/citizens/dependants/relationships_spec.rb
Dependants income page, which records whether the dependant has an income or not. If it does then record this value
[Link to story](https://dsdmoj.atlassian.net/secure/RapidBoard.jspa?rapidView=233&projectKey=AP&modal=detail&selectedIssue=AP-723)
- Add attributes/columns to the Dependants table: has_income and monthly_income
- Create controller, form, view and route for Dependants income get and patch paths
- Update locales
- Update Citizen dependant flow path
- Create request and feature tests
=> AP723 Dependants Income

.circleci/config.yml, bin/delete_uat_release
This script worked on my computer but not in CircleCI.
This PR should fix.
I tested it on CircleCI this time
=> Fix delete_uat CircleCI job

.circleci/config.yml, README.md, bin/generate_webhint_reports.sh, features/support/env.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-706)
**BEFORE**:
The `run_webhint` CircleCI job would:
- run feature tests marked with @webhint and saves all pages to disk
- run webhint on these pages
**AFTER**:
- When the `build_and_test` job runs the cucumber tests, whenever it encounters a new page it saves it to the disk
- When the `run_webhint` job runs, it runs webhint on these pages
**It's better because**:
- We don't have to worry about marking pages with @webhint
- Feature tests are only run once
- If a page is covered by cucumber tests, it is also automatically covered by webhint
**Other stuff**:
- GZip the webhint HTML reports before saving them because it's much faster
- When webhint runs, add a progress indication.
=> AP-706 All pages to be checked by webhint

app/controllers/concerns/providers/draftable.rb, app/controllers/providers/end_of_applications_controller.rb, app/controllers/providers/merits_declarations_controller.rb, app/helpers/flow_helper.rb, app/models/concerns/legal_aid_application_state_machine.rb, app/services/flow/flows/provider_merits.rb, app/services/flow/key_point.rb, app/views/providers/end_of_applications/show.html.erb, app/views/shared/forms/_next_action_buttons.html.erb, config/locales/en/model_enum_translations.yml, config/locales/en/providers.yml, config/routes.rb, db/migrate/20190729100046_remove_merits_completed_states.rb, features/providers/civil_application_journey.feature, spec/factories/legal_aid_applications.rb, spec/requests/providers/end_of_applications_spec.rb, spec/requests/providers/merits_declarations_spec.rb, spec/support/flow_helpers.rb
[Jira AP-747](https://dsdmoj.atlassian.net/browse/AP-747)
Adds end of application controller and show view. Changes ending state to `application_submitted`
=> AP-747 Add end of application

app/views/providers/limitations/show.html.erb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-779)
Added in a missing div to fix a spacing problem
=> Amend location of div to fix spacing issue

package.json, yarn.lock
Reverts ministryofjustice/laa-apply-for-legal-aid#730
=> Revert "Bump webpack-dev-server from 3.7.2 to 3.8.0"

app/services/ccms/attribute_value_generator.rb, config/ccms/ccms_keys.yml, spec/services/ccms/case_add_requestor_xml_blocks_spec.rb, spec/support/xml_attribute_block_matcher.rb, spec/support/xml_extractor.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-836)
Added tests for the various CCMS attributes.
Currently have an issue matching the expected values for some tests. The expected value is a long string, the matcher fails for these cases. Currently these tests are commented out until i can work out the issue.
=> Ap 836 ccms various hard coded

app/javascript/src/modules/proceedings.js, app/javascript/src/proceeding_types.js, db/schema.rb, package.json, spec/javascript/modules/proceedings.spec.js, spec/javascript/proceeding_types.spec.js
Unit Testing ProceedingTypes JavaScript
[Link to story](https://dsdmoj.atlassian.net/secure/RapidBoard.jspa?rapidView=233&projectKey=AP&modal=detail&selectedIssue=AP-828)
Separate ProceedingTypes JavaScript out into smaller functions and place into proceedings module, to make it easier to test. 
Create a async/await function for the request.
Unit Test functions in the module e.g. getAll() . I wasn't able to test the filterSearch() as it manipulates the DOM with JQuery and is better tested with integration testing - Capybara (which it is already)
=> AP828 Unit Testing ProceedingTypes JavaScript

app/assets/stylesheets/helpers.scss, app/helpers/application_helper.rb, app/views/citizens/declarations/show.html.erb, app/views/layouts/_footer.html.erb, app/views/layouts/_header.html.erb, app/views/layouts/application.html.erb, app/views/providers/submitted_applications/show.html.erb, app/views/shared/_applicant_declaration.html.erb, config/locales/en/citizens.yml, config/locales/en/providers.yml, config/locales/en/shared.yml, spec/requests/providers/submitted_applications_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-804)
Print application by running `window.print()`
=> AP-804 Print application

config/ccms/ccms_keys.yml, spec/services/ccms/case_add_requestor_xml_blocks_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-811)
Add 2 new CCMS attributes and tests
=> Ap 811 new attributes

spec/services/ccms/case_add_requestor_xml_blocks_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-868)
The ticket details 2 attributes, however FAMILY_STMT_DETAIL was already done under AP-836
=> AP-868 Add remaining family statement attribute and test

app/services/ccms/attribute_value_generator.rb, config/ccms/ccms_keys.yml, db/schema.rb, spec/services/ccms/case_add_requestor_spec.rb, spec/services/ccms/case_add_requestor_xml_blocks_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-840)
Added attributes to check application and updates the XML accordingly.
=> Ap 840 client assets

bin/uat_deploy
On PR https://github.com/ministryofjustice/laa-apply-for-legal-aid/pull/753, we forgot to also change the UAT command
=> Fix UAT deploy

README.md
Update README to describe how to enable Create Test Applications as Admin
[Link to story](https://dsdmoj.atlassian.net/secure/RapidBoard.jspa?rapidView=233&projectKey=AP&modal=detail&selectedIssue=AP-805)
=> Update README to Include Create Test Applications as Admin

app/services/ccms/attribute_value_generator.rb, config/ccms/ccms_keys.yml, spec/services/ccms/case_add_requestor_spec.rb, spec/services/ccms/case_add_requestor_xml_blocks_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-870)
more CCMS attributes and tests
=> Ap 870 other assets

app/services/ccms/attribute_value_generator.rb, config/ccms/ccms_keys.yml, spec/services/ccms/case_add_requestor_xml_blocks_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-873)
=> Add attribute to omit list

ccms_integration/ccms_spec.rb
The spec to test integration with CCMS (ie create a case in SOA) is
currently failing.
Fix it by:
* creating a legal_aid_application with other_assets_declaration,
savings_amount and respondent, so that the correct data is available
when the test runs
* using a valid username (actually an id)
=> Fix ccms_spec

config/locales/en/providers.yml
Content change to Before you continue page
[Link to story](https://dsdmoj.atlassian.net/secure/RapidBoard.jspa?rapidView=233&modal=detail&selectedIssue=AP-841)
Update the list on the capital introduction page/ Before you continue page
=> AP841 Update content on capital introduction page

config/locales/en/helpers.yml
[Link to story](https://dsdmoj.atlassian.net/browse/AP-714)
copy change
=> AP-714 fix hint text

app/views/shared/forms/_identify_types_of_outgoings_form.html.erb, app/views/shared/forms/_savings_and_investments_form.html.erb, app/views/shared/forms/_types_of_income_form.html.erb, app/views/shared/forms/other_assets/_form.html.erb, config/locales/en/generic.yml, config/locales/en/shared.yml
[Link to story](https://dsdmoj.atlassian.net/browse/AP-484)
- put tickbox questions inside fieldsets
- harmonised tickbox titles
- removed duplicate H1s
=> Ap 484 tickboxes

app/models/respondent.rb, config/ccms/ccms_keys.yml, db/schema.rb, spec/services/ccms/case_add_requestor_xml_blocks_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-875)
Added tests for existing attributes and created new attributes where required
=> Ap 875 hard coded CCMS attributes

app/assets/stylesheets/govuk-mods.scss
[Link to story](https://dsdmoj.atlassian.net/browse/AP-933)
Added CSS for start button arrow.
Removed unrelated CSS that is no longer needed at all. 
=> AP-933 Start Button Arrow

app/services/ccms/attribute_value_generator.rb, config/ccms/ccms_keys.yml, spec/services/ccms/case_add_requestor_spec.rb, spec/services/ccms/case_add_requestor_xml_blocks_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-883)
Add tests for various hard coded attributes
add method for the prospects of success value 
=> Ap 883 last few attributes

package.json, yarn.lock
=> Undo breaking dependabot change

app/views/providers/address_selections/show.html.erb, config/locales/en/providers.yml
[Link to story](https://dsdmoj.atlassian.net/browse/AP-600)
Added a Ruby if statement, if number of addresses is 1, say "address" rather than "addresses"
=> AP-600 Single Address Situations

README.md
Adding instructions to access Sidekiq monitoring, Rals Admin panel and
links to slack channels with alerts for our different environments.
=> Add Monitoring and Debugging section to README

app/models/ccms/submission.rb, app/services/ccms/base_response_parser.rb, app/services/ccms/base_submission_service.rb, app/services/ccms/case_add_requestor.rb, spec/models/ccms/submission_spec.rb, spec/services/ccms/applicant_add_response_parser_spec.rb, spec/services/ccms/applicant_add_status_response_parser_spec.rb, spec/services/ccms/applicant_search_response_parser_spec.rb, spec/services/ccms/case_add_requestor_spec.rb, spec/services/ccms/case_add_response_parser_spec.rb, spec/services/ccms/case_add_status_response_parser_spec.rb, spec/services/ccms/reference_data_response_parser_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-741)
- Add more information to errors to make troubleshooting easier
- Steps of the CCMS submission are run in Sidekiq so will be retried when there is an error
- The errors handled by `handle_failure` are rescued. I'm not sure about the nature of this error but I added code to log it in Sentry
=> AP-741 CCMS errors: add more information to make troubleshooting easier

app/services/ccms/case_add_requestor.rb, spec/factories/proceeding_types.rb, spec/factories/scope_limitations.rb, spec/factories/submissions.rb, spec/services/ccms/case_add_requestor_xml_blocks_spec.rb
Fix rubocop alerts from https://github.com/ministryofjustice/laa-apply-for-legal-aid/pull/910
=> Fix rubocop alerts

app/jobs/govuk_notify_mailer_job.rb, app/mailers/feedback_mailer.rb, app/mailers/notify_mailer.rb, app/mailers/resend_link_request_mailer.rb, app/services/govuk_emails/email.rb, app/services/govuk_emails/email_monitor.rb, config/application.rb, config/initializers/gov_uk_notify.rb, spec/cassettes/govuk_email_delivered.yml, spec/jobs/govuk_notify_mailer_job_spec.rb, spec/mailers/feedback_mailer_spec.rb, spec/mailers/notify_mailer_spec.rb, spec/mailers/resend_link_request_mailer_spec.rb, spec/requests/citizens/resend_link_requests_spec.rb, spec/requests/feedbacks_spec.rb, spec/services/citizen_email_service_spec.rb, spec/services/govuk_emails/email_monitor_spec.rb, spec/services/govuk_emails/email_spec.rb, spec/services/smoke_test/test_emails_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-838)
Re-send email if needed or send an alert in slack if email permanently failed
=> AP-838 Monitor emails

app/models/provider.rb, app/services/ccms/attribute_value_generator.rb, app/services/ccms/case_add_requestor.rb, app/services/mock_provider_details_retriever.rb, ccms_integration/ccms_spec.rb, config/initializers/mock_saml.rb, spec/services/ccms/case_add_requestor_spec.rb, spec/services/ccms/case_add_requestor_xml_blocks_spec.rb, spec/services/mock_provider_details_retriever_spec.rb, spec/services/provider_details_creator_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-965)
Added 2 new users 'NEETADESOR' and 'DAVIDGREYLLPTWO' to the mock_saml and set up hardcoded details for these providers which are required for CCMS
Set the CCMS submission to use the provider username linked to the application and remove the hardcoded value "NEETADESOR'
=> Ap 965 ccms user login

app/models/concerns/legal_aid_application_state_machine.rb, spec/models/legal_aid_application_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-974)
Show "submitted" state when the application has been submitted by the provider
=> AP-974 Show "Submitted" state when provider submitted application

app/views/providers/start/index.html.erb, config/locales/en/providers.yml
[Jira AP-978](https://dsdmoj.atlassian.net/browse/AP-978)
Updates the text on the page.
=> AP-978 Update start page text

app/views/providers/end_of_applications/show.html.erb, config/locales/en/providers.yml, spec/requests/providers/end_of_applications_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-332)
Add link to the feedback page when the application is submitted
=> AP-332 Add link to the feedback page when the application is submitted

app/controllers/concerns/providers/authorizable.rb, app/models/legal_aid_application.rb, app/policies/legal_aid_application_policy.rb, config/locales/en/errors.yml, spec/factories/legal_aid_applications.rb, spec/models/legal_aid_application_spec.rb
Reverts ministryofjustice/laa-apply-for-legal-aid#926
=> Revert "AP882 Remove redirect message on submitted applications"

app/helpers/application_helper.rb, config/locales/en/providers.yml, features/providers/check_your_answers.feature, features/providers/civil_application_journey.feature, features/providers/pathways_from_check_your_answers.feature, features/step_definitions/civil_journey_steps.rb
https://dsdmoj.atlassian.net/browse/AP-1047
Change:
Your legal aid applications
to
Your applications
Tell us the basic case details and see if your client’s benefits or income qualifies for legal aid.
to
Tell us the basic case details and we’ll check if your client is entitled to legal aid.
Start Now
to
Start now
LAA Ref
to
LAA reference
=> AP-1047 content edits to provider dashboard

app/views/providers/end_of_applications/show.html.erb, config/locales/en/providers.yml
https://dsdmoj.atlassian.net/browse/AP-1040
- changed bulleted list to numbered list
- added third item to list ('keep it on file')
- changed feedback sentence and made it inset text
=> AP-1040 content and style changes

app/views/contacts/show.html.erb, config/locales/en/contacts.yml, spec/requests/contact_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-931)
=> AP-931 new contact us layout

app/assets/stylesheets/interruption-panel.scss, app/views/providers/check_benefits/_check_benefits_result.html.erb, app/views/providers/check_benefits/_use_ccms.html.erb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1070)
=> AP-1070 Changes to interruption card

README.md
The link was dead as the guide has been moved to a new URL.
=> Upgrade Git Crypt guide link in Readme

app/views/shared/check_answers/_item.html.erb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-712)
=> AP-712 Added one single space to CYA screen element

app/views/citizens/property_values/_form.html.erb, app/views/citizens/property_values/show.html.erb, app/views/providers/property_values/show.html.erb, app/views/shared/forms/_outstanding_mortgage_form.html.erb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1080)
Updated layout to be accessible
=> Ap 1080 layout

app/views/providers/used_delegated_functions/show.html.erb, app/views/shared/_show_errors.html.erb, app/views/shared/forms/_savings_and_investments_form.html.erb, app/views/shared/forms/_shared_ownership_form.html.erb, app/views/shared/forms/_success_prospect_form.html.erb, app/views/shared/forms/other_assets/_form.html.erb, app/views/shared/forms/vehicles/_remaining_payment.html.erb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1053)
Added styling to show error messages below the question/above the response fields in addition to the summary at the top of the page
=> Ap 1053 error message styling in form

app/views/providers/merits_declarations/show.html.erb, config/locales/en/providers.yml
[Link to story](https://dsdmoj.atlassian.net/browse/AP-857)
Update the content on the declaration page and add a new div with the information about printing and signing
=> ap-857 update merits declaration content

config/locales/en/providers.yml
https://dsdmoj.atlassian.net/browse/AP-1048
_Change_
You've told us you've used delegated functions. You can continue into a full (or 'substantive') application now or start later.
to
You told us you've used delegated functions. You can make a substantive application now or come back and do it later.
_Change_
No, I'll start later
to
No, I’ll do it later
_Change_
You must submit a full application by [date]
to
You must submit a substantive application by [date]
=> AP-1048 making substantive application edits

app/models/dashboard/widget_data_providers/failed_ccms_submissions.rb, app/models/dashboard/widget_data_providers/pending_ccms_submissions.rb, helm_deploy/apply-for-legal-aid/templates/.dashboard_template_cron.yaml.sample, helm_deploy/apply-for-legal-aid/templates/dashboard_failed_ccms_submissions_cron.yaml, helm_deploy/apply-for-legal-aid/templates/dashboard_pending_ccms_submissions_cron.yaml, spec/models/dashboard/widget_data_providers/failed_ccms_submissions_spec.rb, spec/models/dashboard/widget_data_providers/pending_ccms_submissions_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1071)
- Created `Dashboard::WidgetDataProviders::FailedCCMSSubmissions'
- Created `Dashboard::WidgetDataProviders::PendingCCMSSubmissions'
- Added cronjobs for both the above widgets
=> AP-1071 Add Dashboard widgets for CCMS submissions

.circleci/config.yml
Our current `test` workflow in Circle CI takes about 14-15 min per run.
Internally the `test` job have different main checks that run sequentially:
- Checks linters for Ruby and ERB.
- Runs rspec unit tests.
- Runs cucumber integration tests.
- Generates webhint reports over cucumber results.
We can extract those checks into separate jobs and run them in parallel. So the total test time will be the longest of the individual previously listed checks. 
Also, Webhint reports take quite a big chunk of time on the sequential testing and they do not need to be run over every single commit in every single branch, specially with the amount of work we push that does not contain frontend changes. 
This PR address it in two ways:
1. Webhint reports generation over developer branches won't run …
=> Speed up Circle CI tests

app/models/dashboard/widget_data_providers/past_three_weeks_average_feedback_score.rb, app/models/dashboard/widget_data_providers/past_weeks_average_feedback_score.rb, spec/models/dashboard/widget_data_providers/past_three_weeks_average_feedback_score_spec.rb, spec/models/dashboard/widget_data_providers/past_weeks_average_feedback_score_spec.rb
[Dashboard errors causing sidekiq errors in prometheus](https://dsdmoj.atlassian.net/browse/AP-1132)
Add handling for attempting to divide zero feedbacks
=> AP-1132 : Dashboard errors in sidekiq/prometheus

app/views/providers/check_benefits/_check_benefits_result.html.erb, config/locales/en/providers.yml
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1124)
Added a new page title without client name
added a H1 heading with client name and result
=> remove applicant name from page title

app/controllers/admin/feedback_controller.rb, app/views/admin/feedback/_feedbacks.erb, app/views/admin/feedback/show.html.erb, app/views/feedback/new.html.erb, app/views/layouts/admin.html.erb, config/locales/en/admin.yml, config/locales/en/generic.yml, config/locales/en/helpers.yml, config/locales/en/layouts.yml, config/routes.rb, spec/requests/admin/feedback_spec.rb
[Access provider feedback](https://dsdmoj.atlassian.net/browse/AP-1105)
Implemented a new admin controller and associated views allowing admin users to view paginated Feedback
=> AP-1105: admin feedback review

LICENCE.md
Updates the copyright licence for this year
=> Update year in licence file

app/views/providers/statement_of_cases/show.html.erb, config/locales/en/generic.yml, config/locales/en/providers.yml, helm_deploy/apply-for-legal-aid/templates/cronjob-db-backup-cleanup.yaml
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1137)
Add new bullet point and update content for other bullet points
=> ap-1137-make requirements clear

bin/cleanup_manual_snapshots
cronjob was set up for running in staging, all running as expected so this changes it to stop running in staging and only take hourly snapshots of production
=> Update cronjob script to use production values

app/views/admin/submitted_applications_reports/_submitted_applications.html.erb, config/locales/en/admin.yml
Add the name of the user to the submitted applications report
[Link to story](https://dsdmoj.atlassian.net/secure/RapidBoard.jspa?rapidView=233&projectKey=AP&modal=detail&selectedIssue=AP-1143)
=> AP1143 Add provider username to submitted applications report

app/views/providers/email_addresses/show.html.erb, config/locales/en/helpers.yml, spec/requests/providers/email_addresses_spec.rb
Update email addresses page
Remove email hint
Remove size on the label
Update test
=> AP1082 Update email addresses page

helm_deploy/apply-for-legal-aid/templates/_helpers.tpl
=> temporary alter schedule:

package.json, yarn.lock
Reverts ministryofjustice/laa-apply-for-legal-aid#1185
=> Revert "Bump jest from 24.9.0 to 25.1.0"

config/locales/en/providers.yml
https://dsdmoj.atlassian.net/browse/AP-1215
Edited last sentence on page to make it a bit less wordy.
=> ap-1215-edit-content-on-cya-page

helm_deploy/apply-for-legal-aid/templates/cronjob-reset-dashboard-overnight.yaml
Add missing close quote to prevent sentry errors and allow cronjob to run
=> Fix: reset dashboard cronjob

app/services/ccms/attribute_value_generator.rb, config/ccms/attribute_block_configs/non_passported.yml, spec/services/ccms/requestors/case_add_requestor_xml_blocks/non_passported_variable_attributes_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1189)
Added code to generate the value for various capital assets to the CCMS payload
=> AP-1189 Capital assets attributes

config/locales/en/providers.yml
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1243)
=> AP-1243 Minor copy change

app/services/ccms/attribute_value_generator.rb, config/ccms/attribute_block_configs/non_passported.yml, spec/services/ccms/requestors/case_add_requestor_xml_blocks/non_passported_variable_attributes_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1193)
=> AP-1193 Vehicles attributes in CCMS payload

app/services/ccms/attribute_value_generator.rb, config/ccms/attribute_block_configs/non_passported.yml, spec/services/ccms/requestors/case_add_requestor_xml_blocks/non_passported_variable_attributes_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1196)
added the capital attributes for non-passported
=> AP-1196 Add capital attributes

app/models/applicant.rb, app/services/ccms/attribute_value_generator.rb, app/services/ccms/payload_generators/entity_attributes_generator.rb, config/ccms/attribute_block_configs/non_passported.yml, spec/services/ccms/payload_generators/entitiy_attributes_generator_spec.rb, spec/services/ccms/requestors/case_add_requestor_xml_blocks/non_passported_attributes_spec.rb, spec/services/ccms/requestors/case_add_requestor_xml_blocks/non_passported_variable_attributes_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1191)
=> AP-1191 - general application level attributes in CCMS payload

.rubocop.yml, app/controllers/admin/reports_controller.rb, app/models/merits_assessment.rb, app/services/reports/mis/application_detail_csv_line.rb, app/services/reports/mis/application_details_report.rb, app/views/admin/reports/index.html.erb, app/views/layouts/admin.html.erb, config/locales/en/admin.yml, config/locales/en/layouts.yml, config/routes.rb, spec/factories/legal_aid_applications.rb, spec/models/merits_asssessment_spec.rb, spec/requests/admin/reports_spec.rb, spec/services/reports/mis/application_detail_csv_line_spec.rb, spec/services/reports/mis/application_details_report_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-980)
- Created `Reports::MIS::ApplicationDetailsReport` class to generate the report
- Created `Reports::MIS::ApplicationDetailCsvLine` to create one CSV line for each application
- Created `Admin::ReportsController`
=> AP-980 Download CSV of submitted applications

.circleci/config.yml
Add filters to auto-deploy dependabot branches
=> CircleUpdate: Auto-deploy dependabot branches

app/services/cfe/obtain_assessment_result_service.rb, spec/services/cfe/obtain_assessment_result_service_spec.rb
Do not review until ap-1257 is merged
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1257)
I realised that AP-1257 was missing the functionality to write v2 results to the cfe_reults table. This adds in that functionality and tests for v2, also renames the existing tests to v1.
=> Ap 1257 additional

app/models/applicant.rb, app/models/cfe/v2/result.rb, config/ccms/attribute_block_configs/non_passported.yml, spec/factories/cfe_results.rb, spec/factories/cfe_results/v2/mock_results.rb, spec/models/applicant_spec.rb, spec/models/cfe/v2/result_spec.rb, spec/services/ccms/requestors/case_add_requestor_xml_blocks/non_passported_variable_attributes_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1195)
This is a rebase of the original PR.  Significant changes have been made to the CFE::Result object and the rules on what to send to CCMS.  This allows me to monitor the changes needed in this PR against the original version 
=> AP-1195: CCMS gross income

app/models/applicant.rb, app/models/cfe/v2/result.rb, config/ccms/attribute_block_configs/non_passported.yml, spec/factories/cfe_results.rb, spec/factories/cfe_results/v2/mock_results.rb, spec/models/applicant_spec.rb, spec/models/cfe/v2/result_spec.rb, spec/services/ccms/requestors/case_add_requestor_xml_blocks/non_passported_attributes_spec.rb, spec/services/ccms/requestors/case_add_requestor_xml_blocks/non_passported_variable_attributes_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1199)
Added the housing cost attributes for CCMS
=> Ap-1199 CCMS Housing attributes

config/ccms/attribute_block_configs/non_passported.yml, spec/services/ccms/requestors/case_add_requestor_xml_blocks/non_passported_variable_attributes_spec.rb
Add the next CCMS attribute, PUI_CLIENT_INCOME_CONT
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1202)
=> AP-1202: CCMS pui contribution

config/ccms/attribute_block_configs/non_passported.yml, spec/services/ccms/requestors/case_add_requestor_xml_blocks/non_passported_attributes_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1246)
Added hard coded FALSE and TRUE attributes
=> Ap 1246 hard coded ccms attrs

app/services/ccms/attribute_value_generator.rb, config/ccms/attribute_block_configs/non_passported.yml, spec/services/ccms/requestors/case_add_requestor_xml_blocks/non_passported_entities_spec.rb, spec/services/ccms/requestors/case_add_requestor_xml_blocks/non_passported_variable_attributes_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1201)
=> AP-1201: Shared ownership CCMS attributes

app/services/ccms/attribute_value_generator.rb, config/ccms/attribute_block_configs/non_passported.yml, spec/factories/cfe_results.rb, spec/factories/cfe_results/v2/mock_results.rb, spec/models/applicant_spec.rb, spec/models/cfe/v2/result_spec.rb, spec/services/ccms/requestors/case_add_requestor_xml_blocks/non_passported_variable_attributes_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1296)
* Added the values in the ticket
* updated one of the traits to clarify use before a clash occurred 
=> AP-1296: CCMS additional maintenance and prospects of success attributes

app/views/citizens/legal_aid_applications/index.html.erb, config/locales/en/citizens.yml, features/citizens/citizens.feature
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1261)
Updated the content on the citizen start page to match the prototype
=> AP-1261 Change citizen start page to match prototype

app/services/ccms/attribute_value_generator.rb, config/ccms/attribute_block_configs/non_passported.yml, spec/services/ccms/requestors/case_add_requestor_xml_blocks/non_passported_attributes_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1295)
Added 4 proceeding description attributes, all of which output the same value.
=> ap-1295 Add proceeding attributes and tests

config/locales/en/citizens.yml, features/citizens/citizens.feature
Update the locale file to reflect the changes required on the citizens/means_test_result view
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1262)
=> AP-1262: Update citizen financial assessment references

config/locales/en/shared.yml
Financial assessment content changes to citizen declaration
[Link to story](https://dsdmoj.atlassian.net/secure/RapidBoard.jspa?rapidView=233&projectKey=AP&modal=detail&selectedIssue=AP-1266)
Change content from 'By submitting this assessment, you agree that:' to 'You agree that:'
=> AP-1266 Content change to citizen declaration page

app/models/ccms/submission.rb, app/models/cfe/submission.rb, app/services/ccms/requestors/case_add_requestor.rb, app/services/ccms/submitters/add_case_service.rb, app/services/ccms/submitters/obtain_document_id_service.rb, app/services/ccms/submitters/upload_documents_service.rb, ccms_integration/ccms_spec.rb, spec/services/ccms/submitters/obtain_document_id_service_spec.rb, spec/services/ccms/submitters/upload_documents_service_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1303)
* Implement a has_many relationship from cfe::submission
* Move the create_history call into the document.each block
* Update the tests
=> AP-1303: Update submission_document handling

app/views/providers/about_the_financial_assessments/show.html.erb, config/locales/en/providers.yml, features/step_definitions/civil_journey_steps.rb, spec/requests/providers/about_the_financial_assessments_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1259)
Update the content for the 'about the financial assessment' page
=> ap-1259Update content

app/mailers/submit_application_reminder_mailer.rb, spec/mailers/submit_application_reminder_mailer_spec.rb, spec/services/submit_application_reminder_service_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1237)
Format the Date in accordance with GDS guidance
=> AP-1237: Update email date display

app/views/providers/check_benefits/_check_benefits_result.html.erb, config/locales/en/providers.yml, features/providers/civil_application_journey.feature, features/providers/pathways_from_check_your_answers.feature, spec/requests/providers/check_benefits_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1276)
update content and tests
=> Ap 1276 benefit check content

app/jobs/bank_transactions_analyser_job.rb, app/models/concerns/legal_aid_application_state_machine.rb, config/locales/en/model_enum_translations.yml, spec/factories/legal_aid_applications.rb, spec/jobs/bank_transactions_analyser_job_spec.rb, spec/models/legal_aid_application_spec.rb, spec/models/scheduled_mailing_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1324)
Added a new state for analysing_bank_transactions, which progresses when the BankTransactionAnalysisJob is run.
=> Ap-1324 adding a new state

package.json, yarn.lock
This will remove the Github security warning
=> FIX: Update the yarn, kind-of dependancy 

Gemfile.lock
last weeks update to pry broke it :(
=> bump guard version

app/jobs/bank_transactions_analyser_job.rb, app/models/concerns/legal_aid_application_state_machine.rb, app/services/cfe/base_service.rb, app/services/cfe/obtain_state_benefit_types_service.rb, app/services/state_benefit_analyser_service.rb, db/migrate/20200327171336_add_meta_data_to_bank_transactions.rb, db/sample_data/bank_transactions.csv, db/schema.rb, spec/factories/transaction_types.rb, spec/jobs/bank_transactions_analyser_job_spec.rb, spec/models/legal_aid_application_spec.rb, spec/requests/citizens/declarations_spec.rb, spec/services/cfe/obtain_state_benefit_types_service_spec.rb, spec/services/state_benefit_analyser_service_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1325)
- Changed the BankTransactionAnalyserJob to call StateBenefitAnalyserService
- Wrote StateBenefitAnalyserService to: 
- get list of state benefits from CFE
- analyses credit bank transactions for matching descriptions
- match codes on descriptions to state benefit codes
- update transaction_type_id and meta_data on BankTransaction record to identify the state benefit
=> AP-1325 Analyse state benefits

app/models/transaction_type.rb, app/services/cfe/create_other_income_service.rb, db/migrate/20200327115101_add_column_to_transaction_types.rb, spec/factories/bank_transactions.rb, spec/models/transaction_type_spec.rb, spec/services/cfe/create_other_income_service_spec.rb
- Added other_income seeds to `TransactionType` model
- Added `.other_income` class method to `TransactionType` to return all `other_income` types
- New `CFE::CreateOtherIncomeService` to gather other income data from bank transactions and send to CFE
=> AP-1335 CFE other_income_service

app/services/cfe/create_state_benefits_service.rb, spec/factories/bank_transactions.rb, spec/factories/benefit_types.rb, spec/services/cfe/create_state_benefits_service_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1334)
=> AP-1334: CFE-Create state benefit service

app/controllers/providers/means_summaries_controller.rb, app/controllers/providers/transactions_controller.rb, app/services/cfe/create_other_income_service.rb, app/services/cfe/create_state_benefits_service.rb, app/services/cfe/submission_manager.rb, features/cassettes/Civil_application_journeys/Completes_the_merits_application_for_applicant_that_does_not_receive_passported_benefits.yml, features/providers/civil_application_journey.feature, features/step_definitions/civil_journey_steps.rb, spec/factories/legal_aid_applications.rb, spec/requests/providers/means_summaries_spec.rb, spec/requests/providers/transactions_spec.rb, spec/services/cfe/create_other_income_service_spec.rb, spec/services/cfe/create_state_benefits_service_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1298)
Update MeansSummariesController To call and handle CFE::SubmissionManager requests
Tweak a couple of the CFE services to correct the URLs 
=> AP-1298: Call CFE for non passported applications

.circleci/config.yml
AP1357 Update circleci to notify slack of approvals waiting
[Link to story](https://dsdmoj.atlassian.net/secure/RapidBoard.jspa?rapidView=233&projectKey=AP&modal=detail&selectedIssue=AP-1357)
Update circleci to notify slack of approvals waiting
=> AP1357 Update circleci to notify slack of approvals waiting

app/controllers/feedback_controller.rb, app/mailers/feedback_mailer.rb, app/models/concerns/translatable_model_attribute.rb, app/models/feedback.rb, app/views/feedback/new.html.erb, config/locales/en/feedback.yml, config/locales/en/model_enum_translations.yml, db/migrate/20200408135701_add_difficulty_to_feedback.rb, db/schema.rb, spec/factories/feedbacks.rb, spec/requests/feedbacks_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1332)
Adds a new question on difficulty to the feedback page and also changes the content.
The content itself is currently being reviewed by Stevey but the code and tests are ready for review.
=> Ap 1332 feedback questions

.circleci/config.yml
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1359)
=> AP-1359: Update circle sequence

app/views/providers/outgoings_summary/index.html.erb, config/locales/en/providers.yml, config/locales/en/transaction_types.yml, features/providers/civil_application_journey.feature, features/providers/complete_and_check_means_answers.feature, features/providers/non_passported_journey.feature, spec/requests/citizens/identify_types_of_outgoings_spec.rb, spec/requests/providers/identify_types_of_outgoings_spec.rb, spec/requests/providers/transactions_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1368)
Updates the content on the transaction identification pages, adds some hint text and changes page titles
=> AP-1368 Update copy on transaction pages

app/models/dashboard/widget_data_providers/feedback_scores.rb, spec/models/dashboard/widget_data_providers/feedback_scores_spec.rb
Update geckoboard feedback dataset
[Update geckoboard user satisfaction calculation](https://dsdmoj.atlassian.net/browse/AP-1380)
Add an additional column for storing the difficulty average values
=> AP-1380: Update geckoboard feedback dataset

app/assets/stylesheets/moj_banner.scss, app/views/providers/check_provider_answers/_read_only.html.erb, app/views/providers/check_provider_answers/_shared.html.erb, app/views/providers/check_provider_answers/_standard.html.erb, app/views/providers/check_provider_answers/index.html.erb, config/locales/en/providers.yml, features/cassettes/Non-passported_applicant_journeys/I_want_the_check_provider_answers_page_to_correctly_display_while_waiting_for_client_to_provide_data.yml, features/providers/non_passported_journey.feature, features/step_definitions/civil_journey_steps.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1414)
**As a** provider
**I want to** be able to understand that the application I started is now with my client
**so that I** can keep track of my applications
Have separate `standard` and `read_only`.   This reduces the complexity of the views (removing multiple tertiary if statements) and allows clearer re-use of the shared block in the center of each.
Re-factor the yml to allow each to have named headers
=> AP-1414: provider review application details

app/views/shared/forms/_identify_types_of_outgoings_form.html.erb, app/views/shared/forms/_types_of_income_form.html.erb, config/locales/en/shared.yml
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1411)
=> AP-1411 Explanatory copy

app/models/irregular_income.rb, app/models/legal_aid_application.rb, db/migrate/20200611123802_create_irregular_incomes.rb, db/schema.rb, spec/models/irregular_income_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1471)
Added a new table with and a model with validation, linking it to legal_aid_applications
=> AP-1474 create new irregular payment table and model

app/services/submit_citizen_reminder_service.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-698)
Rename the mailer as I had not changed all instances as a result scheduled mails were not being cancelled
=> [BUGFIX]rename applicant to citizen

app/models/cfe/remarked_transaction.rb, app/models/cfe/remarked_transaction_collection.rb, app/models/cfe/remarks.rb, app/models/cfe/v2/result.rb, app/services/cfe/create_outgoings_service.rb, app/views/providers/means_reports/_caseworker_review.html.erb, app/views/providers/means_reports/show.html.erb, app/views/shared/check_answers/_deductions_details.html.erb, app/views/shared/check_answers/_outgoings_details.html.erb, config/locales/en/providers.yml, config/locales/en/shared.yml, lib/tasks/cfe_printer.rake, lib/tasks/helpers/cfe_api_displayer.rb, spec/factories/cfe_results/v2/mock_results.rb, spec/factory_specs/cfe_result_factory_spec.rb, spec/models/cfe/remarked_transaction_collection_spec.rb, spec/models/cfe/remarked_transaction_spec.rb, spec/models/cfe/remarks_spec.rb, spec/models/cfe/v2/result_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1367)
- Created classes `CFE::Remarks`, `CFE::RemarkedTransactionCollection` and `CFE::RemarkedTransaction` to organise and classify transactions marked as requiring review in CFE response
- Added Caseworker Review section to means report to details what issues had been found in the remarks section
=> AP-1367 Caseworker review section of means report

spec/services/ccms/submitters/obtain_applicant_reference_service_spec.rb
When running postgres12, `obtain_applicant_reference_service_spec` has failures due to `SubmissionHistory` records not being created in the expected order.
This PR adds an `order` clause to ensure that the correct record is always used for comparison.
It also includes a minor tidyup of the code including renaming some things, and moving the `applicant does not exist on CCMS` context within the `operation successful` context.
=> Enforce ordering of CCMS SubmissionHistories in specs

Dockerfile
Update kubectl to align with the cloud-platform supported versions
=> update kubectl version

app/models/concerns/legal_aid_application_state_machine.rb
=> BUGFIX: Allow applicant_details_checked event to transition from use_ccms

config/banks.yml
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1526)
Added monzo and tesco to the truelayer list
=> ap-1526 add monzo and tesco to the bank list

app/views/providers/client_completed_means/show.html.erb, config/locales/en/providers.yml, features/providers/categorizing_bank_transactions.feature, features/providers/civil_application_journey.feature, features/providers/complete_and_check_means_answers.feature, features/providers/non_passported_journey.feature, spec/requests/providers/client_completed_means_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1412)
**As a** provider
**I want to** be given clear and concise information about next steps
**so that** I understand what is happening next in the journey
Amended the view and locale to reflect the defined changes, then updated the tests to reflect the new page heading
=> AP-1412: Update client completed means content

app/jobs/dashboard/feedback_item_job.rb, app/models/dashboard/single_object/feedback.rb, app/models/feedback.rb, app/services/dashboard_event_handler.rb, spec/factories/feedbacks.rb, spec/jobs/dashboard/feedback_item_job_spec.rb, spec/models/dashboard/single_object/feedback_spec.rb, spec/services/dashboard_event_handler_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1554)
This defines a new method of sending feedback data to a geckoboard dataset
*  test this on UAT to ensure that, if three feedbacks are sent to geckoboard, the guage/values return the same values
=> AP-1554: geckoboard feedback update

db/schema.rb
Update schema because I forgot to run rake:migrate before submitting and merging #1621
=> BugFix: Tidy up after AP-1461

app/controllers/auth_controller.rb
=> Provide more detail on auth error from true layer

app/services/admin/provider_details_service.rb, app/services/provider_details_creator.rb, db/migrate/20200813132316_remove_user_login_from_provider.rb, db/schema.rb, db/seeds/test_provider_populator.rb, spec/services/provider_details_creator_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1590)
Migration to remove the user_login_id which is no longer required
=> Ap 1590 remve login

app/jobs/dashboard/applicant_email_job.rb, app/models/dashboard/single_object/applicant_email.rb, app/services/citizen_email_service.rb, app/services/dashboard_event_handler.rb, spec/jobs/dashboard/applicant_email_job_spec.rb, spec/models/dashboard/single_object/applicant_email_spec.rb, spec/services/citizen_email_service_spec.rb, spec/services/dashboard_event_handler_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1588)
Create a new single_object geckoboard data set, job, dashboard_handler event and calling method
This needed to be a single object because we don't record a database value for emails sent so it must incrementally increase on each send
=> AP-1588: Geckoboard client emails

app/controllers/providers/non_passported_client_instructions_controller.rb, app/services/flow/flows/provider_start.rb, app/views/providers/check_benefits/_applicant_details.html.erb, app/views/providers/check_benefits/_check_benefits_result.html.erb, app/views/providers/check_benefits/_how_we_checked.html.erb, app/views/providers/non_passported_client_instructions/show.html.erb, config/locales/en/providers.yml, config/routes.rb, features/providers/civil_application_journey.feature, features/providers/non_passported_journey.feature, features/providers/pathways_from_check_your_answers.feature, spec/requests/providers/check_benefits_spec.rb, spec/requests/providers/non_passported_client_instructions.rb, spec/requests/providers/substantive_applications_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1409)
The DWP benefit check result page for applicants that do not receive benefits contains too much information and needs to be simplified.
This PR simplifies that page and adds another page as the next step in the journey containing the additional information.
=> AP-1409 - Simplify DWP benefit check result page

app/controllers/auth_controller.rb, spec/requests/applicants/omniauth_callbacks_spec.rb, spec/requests/auth_spec.rb
=> AP1512 WIP access denied

app/controllers/auth_controller.rb, config/initializers/omniauth.rb
AP1512 Update raven capture message for omniauth
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1512)
=> AP1512 Update raven capture message for omniauth

app/controllers/auth_controller.rb
=> True Layer Access Denied debugging

app/controllers/applicants/omniauth_callbacks_controller.rb, config/initializers/omniauth.rb
Update omniauth error message
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1512)
=> Update omniauth error message

app/jobs/dashboard/provider_data_job.rb, app/models/dashboard/single_object/provider_data.rb, app/models/legal_aid_application.rb, app/models/provider.rb, app/services/dashboard_event_handler.rb, spec/jobs/dashboard/provider_data_job_spec.rb, spec/models/dashboard/single_object/provider_data_spec.rb, spec/services/dashboard_event_handler_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1589)
Add a new geckoboard report to improve the handling and tracking of provider creation
=> AP-1589: Geckoboard provider update

config/locales/en/providers.yml
I found a broken translation on the check_benefits page for a positive result.
=> repair broken translation@

app/views/citizens/accounts/gather.html.erb, app/views/citizens/banks/_bank.html.erb, app/views/providers/income_summary/_add_other_income.html.erb, app/views/providers/outgoings_summary/_add_other_outgoings.erb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1609)
Updated the images alt text as per the ticket.
=> ap-1609 accessibility fixes for images

app/models/legal_aid_application.rb
1598 has failed to deploy as I didnt rebase with master before merging. This fixes the issue that causes rubocop to stop the deployment.
=> Use sum instead of inject for rubocop/performance

Dockerfile, bin/cleanup_manual_snapshots, bin/create_manual_snapshot, helm_deploy/apply-for-legal-aid/templates/_helpers.tpl
=> Backup db script fix

bin/cleanup_manual_snapshots, helm_deploy/apply-for-legal-aid/templates/cronjob-db-backup-cleanup.yaml
Sentry is reporting that the clean backup cronjob is failing. This is a fix that has to be tested in staging.
=> Database backup cronjob fix

Dockerfile, bin/cleanup_manual_snapshots, bin/create_manual_snapshot, helm_deploy/apply-for-legal-aid/templates/_helpers.tpl
Reverts the changes used to test in staging.
Add bash back to the build dependencies
Revert script to use `sh`
Revert the schedule for the cronjobs
=> Database Backup: revert staging test changes

.circleci/config.yml
Reverts ministryofjustice/laa-apply-for-legal-aid#1714
This removes the hold we have on UAT master as the pentest is complete
=> Revert "add a hold for releases to UAT master"

helm_deploy/prometheus/prometheus-alerts-uat.yaml
Update a comment with the correct file path for deploying changes to the UAT prometheus rules
=> update comment with new file path

Dockerfile, bin/cleanup_manual_snapshots, bin/create_manual_snapshot, helm_deploy/apply-for-legal-aid/templates/_helpers.tpl
The cronjob to delete old backups is still failing on production.
Changed to test on staging credentials with bash on the dockerfile.
This will need to be merged with master to deploy to staging for testing.
=> staging test

app/controllers/feedback_controller.rb, app/views/feedback/new.html.erb, config/locales/en/feedback.yml, features/providers/civil_application_journey.feature, spec/requests/feedbacks_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1658)
Add in an alternative to the provider/citizen option on feedback to cover `unknown` results.
Reword the Provider question so all visitors see the same questions but we retain the ability to check where a visitor came from
Adds a test to make sure the provider sees the correct question
=> Ap 1658 feedback question

app/controllers/providers/transactions_controller.rb, app/presenters/bank_transaction_presenter.rb, spec/factories/transaction_types.rb, spec/presenters/bank_transaction_presenter_spec.rb, spec/requests/providers/transactions_spec.rb
AP1639 income/outgoing on caseworker csv report
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1639)
Update the bank_transaction_report csv with income and outgoing and the selector e.g. provider or system
=> AP1639 income/outgoing on caseworker csv report

app/services/cfe/create_capitals_service.rb, config/locales/en/shared.yml, spec/services/cfe/create_capitals_service_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1656)
=> AP-1656 Copy change

app/forms/legal_aid_applications/used_delegated_functions_form.rb, app/models/legal_aid_application.rb, app/services/reports/mis/application_detail_csv_line.rb, db/migrate/20200917082925_add_used_delegated_functions_reported_on_to_legal_aid_application.rb, db/schema.rb, spec/factories/legal_aid_applications.rb, spec/forms/legal_aid_applications/used_delegated_functions_form_spec.rb, spec/models/legal_aid_application_spec.rb, spec/services/reports/mis/application_detail_csv_line_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1655)
* Added the `used_delegated_function_reported_on` field to the `LegalAidApplication` model
* Added new methods to the `UsedDelegatedFunctionsForm` to set/clear the value for the new field
* Updated the `application_detail_csv_line` model to add the required fields ('Delegated functions date' and 'Delegated functions reported') 
=> AP-1655: add data to admin report

app/controllers/admin/providers_controller.rb, spec/requests/admin/providers_spec.rb
Usernames are sent to the provider details API uppercased
storing them in lowercase was sometimes creating duplicate
records, lower and upper.
=> HOTFIX: change the case of new usernames

app/controllers/providers/no_income_summaries_controller.rb, app/controllers/providers/no_outgoings_summaries_controller.rb, app/models/legal_aid_application.rb, app/services/flow/flows/provider_capital.rb, app/services/flow/flows/provider_dependants.rb, app/views/providers/income_summary/_income_type_item.html.erb, app/views/providers/no_income_summaries/show.html.erb, app/views/providers/no_outgoings_summaries/show.html.erb, app/views/providers/outgoings_summary/_outgoing_type_item.html.erb, config/locales/en/providers.yml, config/routes.rb, features/providers/categorizing_bank_transactions.feature, features/providers/civil_application_journey.feature, features/providers/complete_and_check_means_answers.feature, features/providers/non_passported_journey.feature, features/step_definitions/civil_journey_steps.rb, features/support/steps_helper.rb, spec/requests/providers/client_completed_means_spec.rb, spec/requests/providers/has_dependants_controller_spec.rb, spec/requests/providers/has_other_dependants_controller_spec.rb, spec/requests/providers/no_income_summaries_spec.rb, spec/requests/providers/no_outgoings_summaries_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1569)
Created 2 new pages and inserted them into the flow.
Added conditionals to the flow to control the provider path depending on application
=> Ap 1569 no income outgoing

app/services/flow/flows/provider_start.rb, app/views/shared/forms/_open_banking_consents.html.erb, config/locales/en/activemodel.yml, config/locales/en/providers.yml, features/cassettes/Civil_application_journeys/I_am_instructed_to_use_CCMS_when_the_applicant_is_not_eligible.yml, features/providers/civil_application_journey.feature, features/providers/non_passported_journey.feature, features/providers/pathways_from_check_your_answers.feature, spec/requests/providers/check_benefits_spec.rb, spec/requests/providers/open_banking_consents_spec.rb, spec/requests/providers/substantive_applications_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1632)
1) Updates content on `/does-client-use-online-banking`
- changes header
- changes bullet points
- changes radio button labels
- changes error message
2) Updates content on `/use_ccms`
- changes bullet points
3) Amends screen order so that `/does-client-use-online-banking` precedes `/non-passported-client-instructions`
=> AP-1632 Update open banking consent content

app/lib/omniauth/strategies/moj_oauth2.rb
=> AP=1735 rename method call

config/locales/en/providers.yml
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1600)
I updated the hint text
=> AP-1600: Update the proceeding type hint text

README.md
Update the readme to remove out of date information 
=> update README.md to reflect changes to the service

app/views/providers/about_the_financial_assessments/show.html.erb, config/locales/en/providers.yml
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1734)
=> AP-1734 Copy change: link active 7 days

app/controllers/admin/submitted_applications_reports_controller.rb
AP-1738 Admin page - Order submitted applications report by submission date
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1738)
=> AP-1738 Admin page - Order submitted applications report by submission date

app/controllers/admin/reports_controller.rb, app/services/reports/mis/non_passported_application_csv_line.rb, app/services/reports/mis/non_passported_applications_report.rb, config/routes.rb, spec/factories/legal_aid_applications.rb, spec/requests/admin/reports_spec.rb, spec/requests/providers/identify_types_of_outgoings_spec.rb, spec/services/reports/mis/non_passported_application_csv_line_spec.rb, spec/services/reports/mis/non_passported_applications_report_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1737)
- Added a Non-passported Applications report to `Admin::ReportscContoller`
- Created classes`Reports::MIS:: NonPassportedApplicationsReport` and `Reports::MIS:: NonPassportedApplicationsCsvLine` to generate new reports
- fixed factories that were generating additional `LegalAidApplication` and `LegalAidApplicationTransactionType` records when created with traits `:with_non_passported_state_machine ` and `: with_passported_state_machine`
=> AP-1737 Non-passported Applications report

app/views/providers/transactions/show.html.erb, config/locales/en/transaction_types.yml
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1631)
Change to copy in details section displayed when the provider is selecting friends and family payments.
=> AP-1631 Update text on friends/family transactions

app/controllers/citizens/additional_accounts_controller.rb, app/models/legal_aid_application.rb, config/locales/en/activemodel.yml, config/locales/en/citizens.yml, config/locales/en/providers.yml, spec/requests/citizens/additional_accounts_spec.rb, spec/requests/providers/date_client_told_incidents_spec.rb, spec/requests/providers/income_summary_spec.rb, spec/requests/providers/substantive_applications_spec.rb, spec/requests/providers/used_delegated_functions_spec.rb, spec/requests/providers/vehicles/ages_spec.rb, spec/requests/providers/vehicles/estimated_values_spec.rb, spec/requests/providers/vehicles/regular_uses_spec.rb, spec/requests/providers/vehicles/remaining_payments_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1423)
* Updates copy for a number of errors.
* Prevents an error being displayed if no disregarded benefits are categorised.
=> AP-1423 Improve errors

app/lib/omniauth/strategies/moj_oauth2.rb, app/models/debug.rb, db/migrate/20201023220052_add_browser_details_to_debug.rb, db/schema.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1777)
=> AP-1777 record browser details on Debug records

app/controllers/accessibility_statement_controller.rb, app/views/accessibility_statement/index.html.erb, app/views/layouts/_footer.html.erb, config/locales/cy/accessibility_statement.yml, config/locales/cy/layouts.yml, config/locales/en/accessibility_statement.yml, config/locales/en/layouts.yml, config/routes.rb, spec/requests/accessibility_statement_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1596)
- Add a route and controller for an accessibility statement page
- Add a view for the accessiblity statement and update the footer view to have a link to this page
- Update locales for accessibility statement page and create test for that page
- Update locale for accessiblity statement foot link
- Run cy rake task to translate locales into fake-welsh.
=> AP-1596 accessibility statement

README.md
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1801)
Added documentation on providing an .env.test file for running tests
=> update README to include info on .env.test

README.md
=> remove duplication in readme file

app/helpers/application_helper.rb, app/javascript/src/print_button.js
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1822)
Removed jQuery functions and rewrote in js. 
One of the print buttons didn't actually work so fixed this. 
=> Convert print button to vanilla JS 

.rubocop.yml, app/controllers/providers/proceedings_types_controller.rb, app/controllers/providers/used_delegated_functions_controller.rb, app/models/legal_aid_application.rb, app/services/add_scope_limitation_service.rb, features/step_definitions/civil_journey_steps.rb, spec/factories/legal_aid_applications.rb, spec/models/legal_aid_application_spec.rb, spec/requests/providers/limitations_spec.rb, spec/services/add_scope_limitation_service_spec.rb
**What**
[Link to story](https://dsdmoj.atlassian.net/secure/RapidBoard.jspa?rapidView=233&projectKey=AP&modal=detail&selectedIssue=AP-1546&assignee=5f968777632c6200712e443f)
Created a Scope limitation service object to refactor and reduce the LegalAidApplication model logic.
**Checklist**
=> Ap-1546 Refactor the LegalAidApplication model

app/models/cfe/v2/result.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1547)
Following the Dev time discussion, this comment has been resolved and can be removed as the team is happy with the way it currently works
=> AP-1547: remove maintenance_per_month comment

app/presenters/bank_transaction_presenter.rb, spec/presenters/bank_transaction_presenter_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1805)
Adds sort code and account number to the bank transaction csv so that caseworkers are able to identify accounts more easily.
=> AP-1805 Add account details to transaction csv

config/locales/en/privacy_policy.yml
**What**
[Link to story](https://dsdmoj.atlassian.net/secure/RapidBoard.jspa?rapidView=233&projectKey=AP&modal=detail&selectedIssue=AP-1694&assignee=5f968777632c6200712e443f)
Updated email address on the privacy policy (footer) from data.compliance@justice.gov.uk to privacy@justice.gov.uk
**Checklist**
=> AP-1694 Updated email address

app/controllers/saml_idp_controller.rb, app/models/legal_aid_application.rb, app/services/provider_details_creator.rb, spec/requests/providers/property_value_spec.rb
=> AP-1553: Remove todos

.rubocop_todo.yml, app/controllers/saml_idp_controller.rb, spec/requests/saml_idp_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1550)
=> AP-1550 Unit specs for saml_idp_controller

app/controllers/providers/start_controller.rb, config/routes.rb
=> AP-1861: Remove todo in routes and provider/start_controller

.env.sample, .gitignore
=> Update .env.sample with sidekiq password and .gitignore

app/presenters/bank_transaction_presenter.rb, spec/presenters/bank_transaction_presenter_spec.rb
=> AP-1853: Refactor the CELLS object in the Bank Transaction Presenter

app/views/citizens/banks/index.html.erb, app/views/citizens/consents/show.html.erb, config/locales/cy/citizens.yml, config/locales/en/citizens.yml, features/citizens/citizens.feature, spec/requests/citizens/consent_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1794)
Content changes to the `consent` and `banks` screens on the applicant journey.
=> AP-1794 applicant content changes

spec/data/ccms/case_add_response.xml, spec/data/ccms/case_add_response_failure.xml
=> Update test ccms xml details

config/locales/en/citizens.yml
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1793)
Content change on the citizen side
=> AP-1793 Update the citizen start page

app/views/providers/legal_aid_applications/index.html.erb, config/locales/en/generic.yml, config/locales/en/providers.yml, features/providers/civil_application_journey.feature, features/step_definitions/civil_journey_steps.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1635)
=> AP-1635 Start page copy change

app/controllers/citizens/check_answers_controller.rb, app/mailers/citizen_confirmation_mailer.rb, app/services/citizen_completion_email_service.rb, config/govuk_notify_templates.yml, spec/mailers/citizen_confirmation_mailer_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1872)
Add a new citizen completion email service and mailer to send an email to client confirming the successful completion of their pat of the application.
=> Ap 1872 completion email

README.md, app/views/providers/legal_aid_applications/index.html.erb, app/views/shared/check_answers/_dependants.html.erb, app/views/shared/check_answers/_income_summary.html.erb, app/views/shared/check_answers/_merits.html.erb, features/accessibility/citizen.feature, features/accessibility/provider.feature, features/cassettes/Provider_accessibility/I_complete_the_client_details_section_of_a_passported_application_and_it_is_accessible.yml, features/cassettes/Provider_accessibility/I_complete_the_financial_assessment_eligibility_section_for_a_non-passported_application.yml, features/cassettes/Provider_accessibility/I_complete_the_non-passported_means_assessment_and_it_is_accessible.yml, features/cassettes/Provider_accessibility/I_start_a_new_application.yml, features/cassettes/Provider_accessibility/I_start_a_new_application_and_it_is_accessible.yml, features/cassettes/Provider_accessibility/I_start_a_new_non-passported_application.yml, features/cassettes/Provider_accessibility/I_start_a_new_non-passported_application_and_enter_client_details.yml, features/cassettes/Provider_accessibility/I_start_a_new_non-passported_application_and_it_is_accessible.yml, features/step_definitions/accessibility.rb, features/step_definitions/civil_journey_steps.rb, features/support/env.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1820)
Added cucumber test feature scenarios for testing accessibility using the axe-cucumber gem. The new accessibility tests will run automatically as part of the pipeline, meaning that we can become aware of and fix (some) accessibility issues quickly. 
These tests will not catch all potential accessibility issues and manual testing is still required. 
NB: There is an issue with radio buttons which will be investigated/fixed in a separate ticket. Pages with this issue are skipping the accessibility step for now.
=> AP-1820 accessibility feature tests

app/controllers/providers/statement_of_cases_controller.rb, app/views/providers/statement_of_cases/show.html.erb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1495)
This:
=> AP-1495 Move file list to below upload button

app/controllers/providers/date_client_told_incidents_controller.rb, app/controllers/providers/provider_base_controller.rb, app/forms/concerns/date_field_builder.rb, app/forms/incidents/told_on_form.rb, spec/forms/concerns/date_field_builder_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1891)
Some additional changes to the formbuilder handling that @RoseSAK is undertaking
=> Formbuilder additions

app/models/cfe/remarks.rb, app/models/concerns/cfe_submission_state_machine.rb, app/models/policy_disregards.rb, app/services/cfe/create_explicit_remarks_service.rb, app/services/cfe/submission_manager.rb, app/services/flow/flows/provider_capital.rb, app/views/providers/means_reports/show.html.erb, config/locales/en/providers.yml, features/accessibility/provider.feature, features/cassettes/Civil_application_journeys/Completes_the_merits_application_for_applicant_that_does_not_receive_passported_benefits.yml, features/cassettes/Civil_application_journeys/I_am_able_to_view_the_client_completed_means_answers.yml, features/cassettes/Civil_application_journeys/Receives_benefits_and_completes_the_application.yml, features/cassettes/Provider_accessibility/I_complete_the_non-passported_means_assessment_and_it_is_accessible.yml, features/providers/civil_application_journey.feature, features/providers/non_passported_journey.feature, features/step_definitions/feature_flagged_steps.rb, spec/cassettes/CFE_SubmissionManager/_call/completes_process.yml, spec/cassettes/CFE_SubmissionManager/_call/when_the_application_is_non-passported/completes_process.yml, spec/cassettes/CFE_SubmissionManager/_call/when_the_application_is_passported/completes_process.yml, spec/factories/legal_aid_applications.rb, spec/factories/policy_disregards.rb, spec/models/cfe/remarks_spec.rb, spec/models/concerns/cfe_submission_state_machine_spec.rb, spec/models/policy_disregards_spec.rb, spec/requests/providers/restrictions_spec.rb, spec/services/cfe/create_dependants_service_spec.rb, spec/services/cfe/create_explicit_remarks_service_spec.rb, spec/services/cfe/obtain_assessment_result_service_spec.rb, spec/services/cfe/submission_manager_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1918)
=> AP-1918: Policy disregards caseworker review

app/controllers/admin/settings_controller.rb, app/forms/settings/setting_form.rb, app/models/setting.rb, app/views/admin/settings/show.html.erb, config/locales/en/admin.yml, config/locales/en/helpers.yml, db/migrate/20210106155819_add_multiple_proceedings_flag_to_settings.rb, db/schema.rb, lib/tasks/setup_db_for_testing.rake, spec/models/setting_spec.rb, spec/requests/admin/settings_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1933)
Add feature flag to allow safe development of multiple proceedings functionality.
=> AP-1933 - Feature flag for multiple proceedings

app/forms/respondents/respondent_form.rb, spec/factories/respondents.rb, spec/forms/respondents/respondent_form_spec.rb, spec/requests/providers/respondents_spec.rb
Update respondent formbuilder and associated tests
=> formbuilder: Respondent form update

app/models/bank_account.rb, app/services/ccms/requestors/case_add_requestor.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1859)
* Removes the majority of TODO statements relating to CCMS attributes.
* Amends remaining TODOs to provide additional context about resolution.
=> AP-1859 Update CCMS TODOs

app/services/true_layer/importers/import_accounts_service.rb, app/services/true_layer/importers/import_provider_service.rb, app/services/true_layer/importers/import_transactions_service.rb
This is because it fails on circle ci
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1796)
=> AP-1796 Undo silencing of logs for certain functions

.rubocop_todo.yml, Guardfile, app/mailers/feedback_mailer.rb, app/models/ccms/submission.rb, app/models/cfe/remarks.rb, app/services/admin/provider_details_service.rb, app/services/ccms/payload_generators/entity_attributes_generator.rb, app/services/reports/base_report_creator.rb, app/services/reports/means_report_creator.rb, app/services/reports/merits_report_creator.rb, spec/models/ccms/submission_spec.rb, spec/services/ccms/payload_generators/entity_attributes_generator_spec.rb
Semi-regular attempt to reduce rubocop todo's and disables
=> Tech-debt: Rubocop tidy

app/controllers/providers/has_other_proceedings_controller.rb, app/models/legal_aid_application.rb, app/services/flow/flows/provider_start.rb, app/views/providers/has_other_proceedings/show.html.erb, config/locales/en/providers.yml, config/routes.rb, features/providers/civil_application_journey.feature, features/step_definitions/civil_journey_steps.rb, spec/factories/legal_aid_applications.rb, spec/factories/proceeding_types.rb, spec/requests/providers/has_other_proceedings_controller_spec.rb, spec/requests/providers/proceedings_types_spec.rb
[AP-1927](https://dsdmoj.atlassian.net/browse/AP-1927)
Add new page for listing previously selected multiple proceeding and the ability to remove them ad hoc.
=> AP-1927 : Add page for reviewing and removing proceedings

app/services/cfe/create_capitals_service.rb
=> Reapply bugfix that has somehow got lost

app/views/providers/statement_of_cases/show.html.erb, features/providers/civil_application_journey.feature, spec/requests/providers/statement_of_case_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1972)
- Updated statement of case page to use new formbuilder
- Updated tests
=> AP-1972 use new formbuilder on statement of case page

app/models/concerns/cfe_submission_state_machine.rb, app/services/cfe/create_cash_transactions_service.rb, app/services/cfe/obtain_assessment_result_service.rb, app/services/cfe/submission_manager.rb, spec/cassettes/CFE_SubmissionManager/_call/allow_cash_payment_setting_is_true/when_the_application_is_non-passported/completes_process.yml, spec/cassettes/CFE_SubmissionManager/_call/allow_cash_payment_setting_is_true/when_the_application_is_passported/completes_process.yml, spec/cassettes/CFE_SubmissionManager/_call/when_the_application_is_non-passported/completes_process.yml, spec/services/cfe/create_cash_transactions_service_spec.rb, spec/services/cfe/obtain_assessment_result_service_spec.rb, spec/services/cfe/submission_manager_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1964)
Add a `CreateCashTransactionsService` to allow cash transactions to be posted to CFE, and amend the CFE `SubmissionManager` to post them for non-passported applications when the `allow_cash_transaction` flag is enabled.
Also amend the `ObtainAssessmentResultService` so that it makes GET requests with a v3 Accept header when the `allow_cash_transaction` flag is enabled.
=> AP-1964 Post cash transactions to CFE

app/controllers/admin/legal_aid_applications_controller.rb, app/controllers/errors_controller.rb, app/views/errors/show.html.erb, spec/requests/admin/legal_aid_applications_controller_spec.rb
Prior to implementing brakeman I thought we should probably address the issues it will raise!
=> Tech debt: brakeman fixes

app/models/bank_account.rb, bin/bundle, spec/factories/bank_transactions.rb, spec/models/bank_account_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1965)
Methods in bank account model now filled. Added a factory trait and testing.
=> AP-1965 Removed hard-coded data from BankAccount model

app/models/concerns/cfe_submission_state_machine.rb, spec/models/concerns/cfe_submission_state_machine_spec.rb, spec/services/cfe/submission_manager_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2008)
Transition in the state machine deleted and the context in the spec renamed.
=> AP-2008 Remove references to student loan

config/ccms/attribute_block_configs/non_passported.yml, spec/services/ccms/requestors/case_add_requestor_xml_blocks/non_passported_additional_property_attributes_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2019)
Updated the text we send to CCMS
=> ap-2019 update text on CCMS attribute

app/models/bank_account.rb, spec/models/bank_account_spec.rb, spec/presenters/bank_transaction_presenter_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2018)
- Update the bank account type labels for later processing in CCMS to:
- Bank Savings
- Bank Current
- Update tests
=> AP-2018 Update the bank account type labels

config/locales/en/shared.yml, config/locales/en/transaction_types.yml, features/accessibility/citizen.feature, features/citizens/citizens.feature, spec/models/aggregated_cash_income_spec.rb, spec/models/aggregated_cash_outgoings_spec.rb, spec/requests/citizens/cash_incomes_spec.rb, spec/requests/citizens/cash_outgoings_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2077)
Update content on means check your answers page for language consistency
=> AP 2077 Update content on means check your answers page

config/locales/en/providers.yml
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2076)
Update content
=> AP-2076 Update content on capital income assessment result

app/views/shared/_cash_transactions.html.erb, config/locales/en/transaction_types.yml
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2075)
=> AP-2075 Content changes on income summary page

app/views/shared/forms/proceedings_types/_proceeding_type.html.erb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2088)
=> AP-2088 Fix Change Proceeding Types link

app/webpack/src/table-sort.js
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2094)
Refactor table-sort.js and remove jquery 
=> AP-2094 remove jquery from table sort js

app/controllers/providers/check_benefits_controller.rb, app/controllers/providers/check_client_details_controller.rb, app/forms/providers/check_client_details_form.rb, app/services/flow/flows/provider_dwp_override.rb, app/views/providers/check_client_details/show.html.erb, app/views/shared/forms/_next_action_buttons.html.erb, app/webpack/stylesheets/govuk-secondary-button.scss, config/locales/en/providers.yml, config/routes.rb, features/providers/civil_application_journey.feature, spec/requests/providers/check_client_details_spec.rb, spec/requests/providers/confirm_dwp_non_passported_applications_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2083)
Add the confirm client details page and add some styling corrections
=> AP-2083: Add the confirm client details page for the DWP Override flow

README.md, lib/tasks/helpers/scope_limitations_migrator.rb
=> Move developer documentation from readme to confluence pages

db/anonymise/rules.rb
The final column was being amended and therefore
needed a trailing newline added
=> Tech-debt: update respondent rule

app/controllers/providers/date_client_told_incidents_controller.rb, app/forms/incidents/told_on_form.rb, app/models/application_merits_task/incident.rb, app/models/incident.rb, app/models/legal_aid_application.rb, config/locales/cy/activemodel.yml, config/locales/en/activemodel.yml, spec/factories/incidents.rb, spec/forms/incidents/told_on_form_spec.rb, spec/requests/providers/date_client_told_incidents_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2133)
Move the `Incident` model into the `ApplicationMeritsTask` namespace, to keep code tidier and allow all merits tasks to be grouped together.
=> AP-2133 Namespace Incident model

Gemfile.lock, app/models/proceeding_type.rb, app/services/proceeding_type_full_text_search.rb, app/webpack/src/modules/proceedings.js, spec/javascript/modules/proceedings.spec.js, spec/requests/proceeding_types/index_proceeding_types_spec.rb, spec/services/proceeding_type_full_text_search_spec.rb
=> Ap 2149 fix full text search

.circleci/config.yml, Gemfile, Gemfile.lock, README.md, spec/spec_helper.rb
=> Update readme badges

.circleci/config.yml, Gemfile, Gemfile.lock, spec/spec_helper.rb
=> Codecov fix

app/webpack/src/worker_waiter.js
=> Bugfix transactions loading

app/models/bank_account.rb, app/services/ccms/requestors/case_add_requestor.rb, config/ccms/means_entity_configs/non_passported.yml, config/ccms/means_entity_configs/passported.yml, spec/data/ccms/case_add_request.xml, spec/services/ccms/requestors/case_add_requestor_xml_blocks/non_passported_entities_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2124)
Add the labels that CCMS is expecting
Added to tests to check the label wording when a block is generated
=> Ap 2124 instance names

app/models/application_merits_task/involved_child.rb, db/anonymise/rules.rb, db/migrate/20210401155950_create_involved_child.rb, db/schema.rb, scripts/migration_hook.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2135)
Created a new model and associated table ApplicationMeritsTask::InvolvedChild belonging to the LegalAidApplication
=> Ap 2135 Create Involved Child class

Guardfile, app/models/application_proceeding_type.rb, features/cassettes/Civil_application_journeys/Allows_return_to_and_proceed_from_Delegated_Function_date_view.yml, features/providers/civil_application_journey.feature, spec/models/application_proceeding_type_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2188)
Add feature and rspec tests to ensure duplicate scope limitations are not created on re-submission of the DF page
=> AP-2188: prevent duplicate scope limitations

app/views/providers/confirm_dwp_non_passported_applications/show.html.erb, app/webpack/stylesheets/alternative-error-style.scss, app/webpack/stylesheets/application.scss, app/webpack/stylesheets/interruption-panel.scss
=> Update styling and confirm dwp form

config/environments/production.rb, config/initializers/filter_parameter_logging.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2224)
Add `statement` to the  filter_parameters to ensure data is not pushed to kibana
=> AP-2224: Fix logging

config/locales/en/providers.yml
=> AP-2034: Update hint text for searching multiple proceedings

README.md
=> Re-instate database section accidentally remvoed from README

app/views/privacy_policy/index.html.erb, config/locales/cy/activemodel.yml, config/locales/cy/citizens.yml, config/locales/cy/dates.yml, config/locales/cy/feedback.yml, config/locales/cy/generic.yml, config/locales/cy/helpers.yml, config/locales/cy/privacy_policy.yml, config/locales/cy/shared.yml, config/locales/cy/transaction_types.yml, config/locales/en/privacy_policy.yml, features/accessibility/citizen.feature, features/citizens/citizens.feature, features/citizens/citizens_welsh.feature, features/providers/civil_application_journey.feature, lib/tasks/helpers/cy_helper.rb, spec/requests/privacy_policy_spec.rb
=> AP-2197: Update privacy policy content

app/controllers/providers/proceeding_merits_task/involved_children_controller.rb, app/services/flow/flows/provider_capital.rb, app/views/providers/proceeding_merits_task/involved_children/show.html.erb, config/routes.rb, spec/factories/legal_aid_applications.rb, spec/factories/proceeding_merits_task/application_proceeding_type_involved_children.rb, spec/requests/providers/proceeding_merits_task/involved_children_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2143)
Add the proceeding merits involved children task to the code base along with the relevant page.
=> AP-2143: Setup initial files for proceeding merits and involved children

app/controllers/providers/used_multiple_delegated_functions_controller.rb, app/forms/legal_aid_applications/used_multiple_delegated_functions_form.rb, spec/forms/legal_aid_applications/used_multiple_delegated_functions_form_spec.rb, spec/requests/providers/used_multiple_delegated_functions_spec.rb
=> Multiple delegted functions tests fix

Gemfile, Gemfile.lock, app/views/saml_idp/idp/saml_post.html.erb, features/providers/mock_saml.feature, features/step_definitions/civil_journey_steps.rb, spec/requests/saml_idp_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2279)
PR to test the updates to rexml and associated gems
Added/updated tests for the mock saml process to ensure future changes don't impact
=> Tech-Debt: REXML update

app/views/providers/about_the_financial_assessments/show.html.erb, config/locales/en/providers.yml, features/accessibility/provider.feature, features/providers/civil_application_journey.feature, features/providers/non_passported_journey.feature
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1898)
Update content on page 'about the financial assessment' to match the prototype
=> AP-1898 update content on about the financial assessment page

app/views/providers/open_banking_consents/show.html.erb, config/locales/en/providers.yml
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1896)
Updated the content on this page to match the prototype
=> AP-1896 update content on open banking provider consent page

app/views/providers/non_passported_client_instructions/show.html.erb, config/locales/en/providers.yml
[Link to story](https://dsdmoj.atlassian.net/browse/AP-1897)
Updated content to match the prototype 
=> AP-1897 update content on non passported client instructions page

app/models/base_aggregated_cash_transaction.rb, config/locales/en/errors.yml, config/locales/en/transaction_types.yml, spec/models/aggregated_cash_income_spec.rb, spec/models/aggregated_cash_outgoings_spec.rb, spec/requests/citizens/cash_incomes_spec.rb, spec/requests/citizens/cash_outgoings_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2080)
Updated content on the cash incomes and cash outgoings blank error messages
Updated relevant tests
=> AP-2080 update cash transactions error messages

app/views/providers/restrictions/show.html.erb, config/locales/en/activemodel.yml, config/locales/en/providers.yml, config/locales/en/shared.yml, features/accessibility/provider.feature, features/providers/check_your_answers.feature, features/providers/civil_application_journey.feature, features/providers/non_passported_journey.feature
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2096)
Update content on restrictions page, and update tests
=> AP-2096 update restrictions content

README.md, app/controllers/admin/reports_controller.rb, app/jobs/reports_uploader_job.rb, app/models/admin_report.rb, db/anonymise/rules.rb, db/migrate/20210518114357_admin_reports.rb, db/schema.rb, helm_deploy/apply-for-legal-aid/templates/cronjob-admin-report.yaml, lib/tasks/jobs/create_admin_reports.rake, spec/factories/admin_report.rb, spec/jobs/reports_uploader_job_spec.rb, spec/requests/admin/reports_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2097)
- Create a cronjob to call an admin reports uploader
- Create admin reports uploader to attach the nonpassported application and submitted applications rerports to the admin reports model
- Test the above 
=> AP-2097 Admin report cron job

app/controllers/concerns/providers/draftable.rb, app/controllers/providers/proceeding_merits_task/linked_children_controller.rb, app/forms/providers/proceeding_merits_task/linked_children_form.rb, app/models/application_merits_task/involved_child.rb, app/models/application_proceeding_type.rb, app/models/proceeding_merits_task/application_proceeding_type_linked_child.rb, app/services/flow/flows/provider_merits.rb, app/views/providers/proceeding_merits_task/linked_children/show.html.erb, config/locales/en/providers.yml, db/anonymise/rules.rb, db/migrate/20210601084320_rename_apt_involved_children_to_apt_linked_children.rb, db/schema.rb, features/providers/merits_task_list.feature, features/step_definitions/civil_journey_steps.rb, features/support/steps_helper.rb, spec/factories/proceeding_merits_task/application_proceeding_type_involved_children.rb, spec/factories/proceeding_merits_task/application_proceeding_type_linked_children.rb, spec/forms/providers/proceeding_merits_task/linked_children_form_spec.rb, spec/helpers/providers_helper_spec.rb, spec/requests/providers/proceeding_merits_task/linked_children_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2294)
This PR updates the handling of linked children. It implements a form object that provides validation and updates the tests to ensure the new handling works
=> AP-2294 linked children update

app/views/providers/applicant_bank_accounts/show.html.erb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2282)
Update spacing on clients bank accounts page
=> AP-2282 update spacing on clients bank accounts page

app/views/providers/dependants/_form.html.erb, config/locales/cy/citizens.yml, config/locales/cy/generic.yml, config/locales/cy/helpers.yml, config/locales/cy/shared.yml, config/locales/en/citizens.yml, config/locales/en/generic.yml, config/locales/en/helpers.yml, config/locales/en/providers.yml, config/locales/en/shared.yml
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2156)
Add full stops to hint text in accordance with the gov uk service standard
=> add full stops to hint text

app/helpers/transaction_type_helper.rb, config/locales/en/activemodel.yml
Two tickets completed here
Make tag text shorter to fit the table better [AP-2205](https://dsdmoj.atlassian.net/browse/AP-2205)
Add a tag for disregarded benefits [AP-2206](https://dsdmoj.atlassian.net/browse/AP-2206)
=> Update tag text in transactions table

app/views/providers/submitted_applications/show.html.erb, app/views/shared/check_answers/_merits.html.erb, config/locales/en/providers.yml
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2339)
Update the page break grouping on the new merits view to
ensure the PDF is rendered correctly
Update the cert page to ensure spacing is consistent
**NOTE** branch name does not match ticket!
=> AP-2339: Update submitted application view

app/views/providers/application_merits_task/statement_of_cases/show.html.erb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2268)
Update upload button to use secondary (grey) style to match MoJ Design System, and avoid having two green CTAs on the page
=> AP-2268 update button styling

spec/requests/errors_spec.rb
Ensure locale is not left on :cy after the tests
=> BugFix: Resolve race condition around welsh locale

app/controllers/providers/capital_assessment_results_controller.rb, app/controllers/providers/capital_income_assessment_results_controller.rb, app/services/results_panel_selector.rb, app/views/shared/assessment_results/_partially_eligible_capital.html.erb, app/views/shared/assessment_results/_partially_eligible_capital_income.html.erb, app/views/shared/assessment_results/_partially_eligible_income.html.erb, config/locales/en/providers.yml, config/locales/en/shared.yml, spec/factories/cfe_results/v4/mock_results.rb, spec/factories/cfe_results/v4/results.rb, spec/services/results_panel_selector_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2159)
Add new result panels
Update ResultPanelSelector to accommodate new options
=> AP-2159 Add new result panels and selection options

config/ccms/attribute_block_configs/non_passported.yml, spec/services/ccms/requestors/case_add_requestor_xml_blocks/non_passported_attributes_spec.rb, spec/services/ccms/requestors/case_add_requestor_xml_blocks/passported_attributes_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2335)
Adds omitted attributes for NP journey
=> AP-2335 add omitted attributes and tests for Non passported

app/services/ccms/requestors/case_add_requestor.rb, config/ccms/attribute_block_configs/non_passported.yml, spec/services/ccms/requestors/case_add_requestor_xml_blocks/non_passported_dependant_child_attributes_spec.rb, spec/services/legal_framework/proceeding_types_service_spec.rb, spec/services/reports/reports_types_creator_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2332)
=> AP-2332. - Dependant attributes in CCMS payload

app/models/cfe/base_result.rb, app/models/cfe/v4/result.rb, app/services/ccms/attribute_value_generator.rb, app/views/providers/means_reports/show.html.erb, app/views/shared/check_answers/_income_result.html.erb, app/views/shared/check_answers/_offline_savings_accounts.html.erb, app/views/shared/means_report/_proceeding_eligibility.html.erb, config/locales/en/providers.yml, db/schema.rb, spec/factories/cfe_results/v4/mock_results.rb, spec/factories/cfe_results/v4/results.rb, spec/models/cfe/v4/result_spec.rb, spec/services/reports/means_report_creator_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2380)
This PR is branched off AP-2159, so best to wait until that is merged and this branch rebased before reviewing.
=> AP-2370 Include results by proceeding type on Means report

config/locales/en/providers.yml, config/locales/en/shared.yml
[Link to story](https://dsdmoj.atlassian.net/browse/AP-856)
Update both client and provider declaration to explain statutory charge
=> Update declaration to explain statutory charge

app/models/bank_account.rb, app/models/irregular_income.rb, app/models/legal_aid_application.rb, app/views/providers/submitted_applications/_irregular_incomes_table.html.erb, app/views/providers/submitted_applications/show.html.erb, app/views/shared/check_answers/_bank_transaction_table.html.erb, config/locales/en/providers.yml, spec/models/bank_account_spec.rb, spec/models/irregular_income_spec.rb, spec/models/legal_aid_application_spec.rb
Normally, the balance reported on the means report is the latest balance from the bank account transactions.  However, if there are no transactions in the calculation period, then take the balance from the BankAccout record.
=> AP-2112 Bank account balance when there are no trasactions

app/views/providers/submitted_applications/_irregular_incomes_table.html.erb
Previsouly, the certificate was only totalling income declared from bank statements.  This change also includes cash transactions and irregular income.
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2382)
=> AP-2382 Include all income and outgoings in certificate

config/initializers/mock_saml.rb, db/seeds/test_provider_populator.rb
Added Katharine Ahern as a user to initializer and seed files so she can run application locally
=> Add Katharine as a user

config/locales/en/activemodel.yml
Update cost limit error message
=> AP-2390 update cost limit error message

app/forms/legal_aid_applications/used_delegated_functions_form.rb, app/forms/legal_aid_applications/used_multiple_delegated_functions_form.rb, config/locales/en/activemodel.yml, spec/forms/legal_aid_applications/used_delegated_functions_form_spec.rb, spec/forms/legal_aid_applications/used_multiple_delegated_functions_form_spec.rb, spec/requests/providers/used_delegated_functions_spec.rb, spec/requests/providers/used_multiple_delegated_functions_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2411)
Remove proceeding name from all error messages, and display full date 
=> AP-2411 update DF dates error messages

app/forms/legal_aid_applications/has_other_proceedings_form.rb, spec/requests/providers/has_other_proceedings_controller_spec.rb
Link error for 'you must select at least one domestic abuse proceeding' to the fieldset
=> AP-2392 link error to radio buttons

app/controllers/providers/confirm_multiple_delegated_functions_controller.rb, app/services/flow/flows/provider_start.rb, app/views/providers/confirm_multiple_delegated_functions/show.html.erb, config/locales/en/providers.yml, features/providers/civil_application_journey.feature, features/providers/pathways_from_check_your_answers.feature
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2397)
Updated content on this page to match the prototype
=> AP-2397 update content on confirm DF page

app/views/citizens/consents/show.html.erb, app/views/providers/use_ccms/show.html.erb, app/views/providers/use_ccms_employed/index.html.erb, config/locales/cy/citizens.yml, config/locales/en/citizens.yml, config/locales/en/providers.yml
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2402)
=> AP-2402 Remove abbr tags from page titles

app/views/providers/confirm_dwp_non_passported_applications/show.html.erb
This was caused by an online rebase :/ that I did via github 🤦 
=> Fix: Trailing erb close after merge

spec/factories/bank_accounts.rb
Update another flickering test by ensuring the test data is
formatted as a BigDemical to two decimal places
=> Fix: More decimal failures

app/services/reports/means_report_creator.rb, app/services/reports/merits_report_creator.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2386)
We have seen issues where the attachments are missing when
uploading to CCMS, this should enable us to track where in
the reporting stage the errors occur, the errors should be
traceable in Kibana …
=> AP-2386: Add logging to report creators

app/services/ccms/parsers/case_add_status_response_parser.rb, spec/data/ccms/case_add_status_response_already_submitted.xml, spec/data/ccms/case_add_status_response_user_authenticated.xml, spec/services/ccms/parsers/case_add_status_response_parser_spec.rb, spec/services/ccms/submitters/check_case_status_service_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2447)
Consider a response with both`Case successfully created` and `Case successfully created.Case already exist, exiting.` to be successful.
=> AP-2447 Bugfix - handle Case already submitted response

app/services/ccms/parsers/case_add_status_response_parser.rb, spec/data/ccms/case_add_status_response_already_submitted.xml, spec/data/ccms/case_add_status_response_user_authenticated.xml, spec/services/ccms/parsers/case_add_status_response_parser_spec.rb, spec/services/ccms/submitters/check_case_status_service_spec.rb
=> Ap 2447a dupe

app/views/providers/proceedings_types/index.html.erb, app/webpack/src/modules/proceedings.js
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2434)
Fixed when the screenreader message is updated to indicate to the user how many results have returned
Also fixed a small alignment issue with the 'No results found' text 
=> AP-2434 proceedings search screenreader msg

.circleci/config.yml, .github/workflows/anonymise_check.yml, .github/workflows/brakeman-analysis.yml, README.md, docs/pull_request_template.md
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2453)
Update the README file to reference `main`
Update CI jobs, where possible to check for master or main
These can be permanently updated when the change is made …
=> AP-2453: Prep for update default branch

app/controllers/admin/settings_controller.rb, app/controllers/providers/check_benefits_controller.rb, app/forms/settings/setting_form.rb, app/models/setting.rb, app/services/use_ccms_arbiter.rb, app/views/admin/settings/show.html.erb, config/locales/cy/helpers.yml, config/locales/en/admin.yml, config/locales/en/helpers.yml, db/migrate/20210805072930_remove_override_dwp_results_feature_flag.rb, db/schema.rb, features/accessibility/provider.feature, features/providers/civil_application_journey.feature, features/providers/non_passported_journey.feature, features/providers/pathways_from_check_your_answers.feature, features/step_definitions/civil_journey_steps.rb, lib/tasks/setup_db_for_testing.rake, spec/models/setting_spec.rb, spec/requests/admin/settings_spec.rb, spec/requests/providers/check_benefits_spec.rb, spec/requests/providers/check_provider_answers_spec.rb, spec/services/use_ccms_arbiter_spec.rb
=> AP-2244 Remove override dwp results feqture flag

app/views/citizens/means_test_results/show.html.erb, app/views/providers/capital_income_assessment_results/show.html.erb, app/views/providers/has_other_dependants/show.html.erb, app/views/providers/proceeding_merits_task/attempts_to_settle/show.html.erb, app/views/providers/proceeding_merits_task/chances_of_success/index.html.erb, app/views/providers/proceeding_merits_task/linked_children/show.html.erb, app/views/providers/proceeding_merits_task/success_prospects/show.html.erb, config/locales/en/citizens.yml, config/locales/en/providers.yml, config/locales/en/shared.yml, config/locales/en/transaction_types.yml
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2303)
Update the default tab title suffix
Amend individual tab titles where necessary
=> Ap2303 Update page titles across application

Gemfile, Gemfile.lock, README.md, spec/spec_helper.rb
Remove codecov from pull requests
* remove the key from CI
* delete the history from the CC website
=> Tech-Debt:  Remove codecov

app/helpers/table_sort_helper.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2435)
Fixed the sort ordering message as this wasn't working before.
Tried to fix the duplicated message too but no joy, decided TMI is better than not enough info …
=> Fix sort order screenreader message

.circleci/config.yml
We have renamed master to main in github, this makes the same changes to circle_ci config. It is a cosmetic change and does not affect functionality
=> update circle config rename master to main

app/workers/ccms/submission_process_worker.rb
The Pull Request predated a rubocop update... I should have rebased before merging 🤦‍♂️ 
=> AP-2472: Fix rubocop issue

config/locales/en/citizens.yml
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2582)
Change heading on client start page 
=> Amend heading on client start page

db/anonymise/rules.rb, db/migrate/20211102100659_add_digest_extracted_at_to_settings.rb, db/migrate/20211102101801_create_application_digest_table.rb, db/schema.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2605)
Created application_digests table
=> AP-2605 create digest table

db/data/20211112125241_add_ccms_matter_code_to_proccedings.rb, db/data_schema.rb
bugfix data migration to populate the ccms_matter_code on all proceedings
=> migartion to add ccms_matter_cocde to existing proceedings

config/locales/en/providers.yml, config/locales/en/shared.yml
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2591)
Content changes to labels on assets page.
=> AP-2591 Amend label content on assets page

config/locales/cy/shared.yml, config/locales/en/shared.yml, spec/services/ccms/requestors/case_add_requestor_xml_blocks/passported_attributes_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2583)
Corrected the one listed in the ticket, also found some other matching misspelled occurences and updated those too
=> AP-2583: Update `financial` typo

config/locales/en/shared.yml
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2396)
Updated CYA wording for emergency cost override.
=> AP-2396 Update emergency cost override CYA wording

app/views/providers/check_benefits/_check_benefits_result.html.erb, config/locales/en/providers.yml, features/accessibility/provider.feature, features/providers/back_button.feature, features/providers/civil_application_journey.feature, features/providers/pathways_from_check_your_answers.feature, spec/requests/providers/check_benefits_spec.rb
=> update passported dwp check result content

app/views/providers/applicant_employed/index.html.erb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2703)
=> AP-2703 remove copy referring to HMRC

app/views/providers/capital_introductions/show.html.erb, config/locales/en/providers.yml, features/providers/civil_application_journey.feature, features/providers/pathways_from_check_your_answers.feature, spec/requests/providers/capital_introductions_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2651)
Updated content, headings and page layout
The last two bullet points for the second section should only appear if the user has selected Section 8 proceedings  …
=> AP-2651 update before you continue page

app/views/providers/client_completed_means/show.html.erb, config/locales/en/providers.yml, features/accessibility/provider.feature, features/providers/categorizing_bank_transactions.feature, features/providers/check_nonpassport_autogrant.feature, features/providers/civil_application_journey.feature, features/providers/complete_and_check_means_answers.feature, features/providers/non_passported_journey.feature, spec/requests/providers/client_completed_means_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2566)
Update content on continue financial assessment page
=> AP-2566 update continue financial assessment page

app/services/reports/mis/application_detail_csv_line.rb, spec/services/reports/mis/application_detail_csv_line_spec.rb
=> Add hmrc field to admin report

app/models/document_category.rb, app/services/document_category_populator.rb, db/anonymise/rules.rb, db/migrate/20211209083010_create_document_categories.rb, db/schema.rb, db/seeds.rb, db/seeds/document_categories.csv, db/seeds/document_categories.rb, spec/factories/document_categories.rb, spec/models/document_category_spec.rb, spec/services/document_category_populator_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2730)
Created migration to add new document_categories table, model and factory
Created document_category_populator to populate new table
=> ap-2730: Create document_categories table

config/locales/en/providers.yml
Fix spelling of eligibility on means report.
=> Fix spelling of eligibility on means report

scripts/restore_anonymised_db.sh
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2766)
After the rake task ends the script checks to see if it completed without any errors and if so it deletes the restore file. …
=> AP-2766 update script to delete file

app/services/flow/flows/provider_capital.rb, app/services/flow/flows/provider_start.rb, app/views/providers/employment_incomes/show.html.erb, config/locales/en/providers.yml, features/step_definitions/civil_journey_steps.rb, spec/requests/providers/applicant_employed_spec.rb, spec/requests/providers/client_completed_means_spec.rb, spec/requests/providers/employed_incomes_spec.rb, spec/requests/providers/received_benefit_confirmations_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2571)
Add conditional to change the page title
Add conditional to add alternative page text
=> Ap 2571 hmrc record exists

helm_deploy/apply-for-legal-aid/templates/ingress.yaml
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2769)
Update the Ingress API and path handling to remove the warnings when deploying to the new EKS/Live cluster
=> AP-2769: Update Ingress API version

config/locales/en/providers.yml
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2822)
Update the content on the blue panel to match the prototype
=> ap-2822 update woording on use CCMS panel

app/models/cfe/v4/result.rb, spec/factories/cfe_results/v4/mock_results.rb, spec/factories/cfe_results/v4/results.rb, spec/models/cfe/v4/result_spec.rb
[Link to story](https://dsdmoj.atlassian.net/jira/software/c/projects/AP/boards/233?modal=detail&selectedIssue=AP-2818)
=> ap-2818: Parse cfe result employment income

app/views/privacy_policy/index.html.erb, config/locales/cy/privacy_policy.yml, config/locales/en/privacy_policy.yml, lib/tasks/helpers/cy_helper.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2752)
Update the privacy policy to match the prototype
=> AP-2752: Update the Privacy Policy text

app/views/providers/merits_task_lists/show.html.erb, features/accessibility/provider.feature, features/providers/check_ccms_autogrant.feature, features/providers/check_nonpassport_autogrant.feature, features/providers/civil_application_journey.feature, features/providers/merits_task_list.feature
update to 'Save and continue' instead of just 'Continue' as we do save the information entered
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2762)
=> AP-2762 update button text on merits task list page

app/services/flow/base_flow_service.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2830
This PR is to produce more diagnostic info on flow errors so that we can debug [this sentry issue](https://sentry.io/organizations/ministryofjustice/issues/2296383807/?project=5416054&query=is%3Aunresolved) …
=> AP-2830 More info on recurring Sentry alert

config/locales/en/shared.yml, spec/requests/providers/capital_income_assessment_results_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2254)
Match the text from the prototype and update the tests to ensure
changes have been rendered as expected
=> AP-2750: Update the means_result content

config/locales/en/providers.yml, features/accessibility/provider.feature, features/providers/civil_application_journey.feature, features/providers/non_passported_journey.feature, features/providers/pathways_from_check_your_answers.feature
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2773)
=> ap-2773: Update content on Check if you can continue using this service page

app/controllers/citizens/legal_aid_applications_controller.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2833)
This was flagged by Snyk as a High Severity
Replace the direct calling of the parameter with
a call to strong parameter version
=> AP-2833: Remove Open Redirect Vulnerability

app/controllers/v1/statement_of_cases_controller.rb, app/forms/base_file_uploader_form.rb, app/lib/malware_scanning.rb, app/webpack/src/dropzone.js, spec/requests/v1/statement_of_cases_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2829)
Refactor the BaseFileUploaderForm to make the code more re-useable
Add the refactored code to the v1/statement_of_case controller and implement the js to handle error message responses …
=> AP-2829: Add dropzone malware scanning

app/jobs/reports_uploader_job.rb, app/services/reports/mis/application_details_report.rb, spec/jobs/reports_uploader_job_spec.rb, spec/services/reports/mis/application_details_report_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2867)
Add some error handling to the report generation and update the job to record
status outcomes for a day
=> AP-2867: Investigate admin report failing

app/services/hmrc/mock_data/employment_tax_credits.json, app/services/hmrc/mock_data/four_weekly_employment.json, app/services/hmrc/mock_data/monthly_employment.json, app/services/hmrc/mock_data/multiple_employments.json, app/services/hmrc/mock_data/single_employment.json, app/services/hmrc/mock_data/weekly_employment.json, app/services/hmrc/mock_interface_response_service.rb, spec/services/hmrc/mock_interface_response_service_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2825)
Add some more scenarios/users for mock HMRC service
=> Ap 2825 hmrc mock

features/step_definitions/admin_steps.rb
=> Remove commented out code

app/models/legal_aid_application.rb, app/models/uploaded_evidence_collection.rb, app/views/shared/check_answers/_merits.html.erb, config/locales/en/shared.yml, spec/factories/uploaded_evidence_collections.rb, spec/models/legal_aid_application_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2874)
Add the supporting evidence section to the merits check your answers page
** I had to rebase on AP-2739 in order to complete this ticket **
The only relevant changes are to app/views/shared/check_answers/_merits.html.erb and shared.yml and models/legal_aid_application.rb …
=> AP-2874 evidence upload check answers page

app/controllers/providers/application_merits_task/statement_of_cases_controller.rb, app/controllers/providers/uploaded_evidence_collections_controller.rb, app/controllers/v1/statement_of_cases_controller.rb, app/controllers/v1/uploaded_evidence_collections_controller.rb, app/policies/legal_aid_application_policy.rb, app/views/providers/application_merits_task/statement_of_cases/_show_new.html.erb, app/views/providers/uploaded_evidence_collections/show.html.erb, app/views/shared/forms/_error_summary_hidden.html.erb, app/webpack/src/dropzone.js, config/locales/en/activemodel.yml, config/routes.rb, spec/requests/providers/application_merits_task/statement_of_case_spec.rb, spec/requests/providers/uploaded_evidence_collection_spec.rb, spec/requests/v1/statement_of_cases_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2908)
Update error handling for Dropzone 
This has been implemented on the Statement of Case and Uploaded evidence pages
=> AP-2908: Improve dropzone error handling

app/controllers/providers/check_merits_answers_controller.rb, app/models/legal_aid_application.rb, lib/tasks/employ.rake, spec/factories/legal_framework_merits_task_list.rb, spec/factories/legal_framework_serialized_merits_task_list.rb, spec/models/legal_aid_application_spec.rb, spec/requests/providers/check_merits_answers_spec.rb, spec/requests/providers/merits_task_lists_controller_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2893)
=> AP-2893 Skip evidence upload page if no documents required

features/providers/evidence_upload.feature, features/step_definitions/evidence_upload_steps.rb
[Link to story](https://dsdmoj.atlassian.net/jira/software/c/projects/AP/boards/233?modal=detail&selectedIssue=AP-2886)
Add feature tests for the evidence upload page covering the following scenarios:
-Uploading a file
-Categorising files
-Deleting a file
-Validation - trying to proceed without categorising a file …
=> Ap 2886 feature tests for evidence upload

config/locales/en/providers.yml, spec/requests/providers/capital_income_assessment_results_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2926)
This is to make it clear that deductions and outgoings include figures from the employment income calculation
=> AP-2926: Update Means Calculation Labels

app/models/cfe/v2/result.rb, app/models/cfe/v3/result.rb, app/models/cfe/v4/result.rb, app/views/providers/capital_income_assessment_results/_disposable_income.html.erb, spec/factories/cfe_results/v4/mock_results.rb, spec/models/cfe/v2/result_spec.rb, spec/models/cfe/v3/result_spec.rb, spec/models/cfe/v4/result_spec.rb, spec/requests/providers/capital_income_assessment_results_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2933)
This pr contains the apply changes to fix display of CFE results with employment income. The CFE changes are in pr https://github.com/ministryofjustice/check-financial-eligibility/pull/815(
- You …
=> ap-2933: Fix cfe display issues

.github/workflows/ci-docker-image.yml
Pushing with _no_ tags only pushed the default
Push both tags explictly
=> Fix: Update docker image action

app/controllers/providers/uploaded_evidence_collections_controller.rb, app/models/uploaded_evidence_collection.rb, app/views/providers/uploaded_evidence_collections/_upload_evidence.html.erb, app/views/providers/uploaded_evidence_collections/_uploaded_files.html.erb, app/webpack/src/dropzone.js
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2904)
Improving the validation on the evidence upload page
* Error messages link to the relevant field
* Error messages show on the relevant part of the page as well as in the error summary at the top …
=> AP-2904 improve validation on evidence upload page

app/webpack/src/dropzone.js
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2976)
Fix the choose files button for all dropzone elements - statement of case page, gateway evidence (?) and evidence upload
=> AP-2976 fix click to upload

config/locales/en/shared.yml
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2966)
Update checkbox content to comply with GDS guidelines on acronyms
=> AP-2966 update checkbox content

Gemfile, Gemfile.lock
This was pointed at the master branch to make the tests
quieter, now that patch has been released we can go
back to calling the gem by version
=> Tech-Debt: Update VCR gem

.rubocop_todo.yml, app/controllers/feedback_controller.rb, app/controllers/providers/transactions_controller.rb, app/forms/citizens/other_assets_form.rb, app/forms/incidents/told_on_form.rb, app/forms/savings_amounts/offline_accounts_form.rb, app/forms/savings_amounts/savings_amounts_form.rb, app/jobs/dashboard/applicant_email_job.rb, app/models/applicant.rb, app/models/base_aggregated_cash_transaction.rb, app/models/legal_aid_application.rb, app/services/banking/bank_transaction_balance_calculator.rb, app/services/ccms/attribute_value_generator.rb, app/services/ccms/payload_generators/entity_attributes_generator.rb, app/services/ccms/requestors/case_add_requestor.rb, app/services/currency_cleaner.rb, app/services/job_queue.rb, app/services/reports/bank_transactions/bank_transaction_report_creator.rb, app/services/reports/mis/application_details_report.rb, app/services/reports/mis/non_passported_applications_report.rb, app/validators/currency_validator.rb, config/initializers/settings.rb, db/anonymise/rules.rb, lib/tasks/helpers/cfe_api_displayer.rb, spec/factories/submissions.rb, spec/i18n_spec.rb, spec/services/ccms/requestors/case_add_requestor_xml_blocks/passported_attributes_spec.rb, spec/services/reports/mis/non_passported_application_csv_line_spec.rb, spec/support/soap_matchers.rb, spec/support/xml_attribute_block_matcher.rb
Fixes offences for the following cops:
* Style/RedundantAssignment
* Style/RedundantFreeze 
* Style/SoleNestedConditional
* Style/Alias
* Style/AccessorGrouping
* Style/FormatString
=> Misc rubocop fixes

.env.sample, README.md, docs/git-crypt.md, spec/requests/status_spec.rb, spec/services/govuk_emails/email_spec.rb
Tweaks to readme and setup from my experience following the existing documentation
=> Setup and documentation tweaks

features/step_definitions/civil_journey_steps.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2901)
=> Fix trailing comma

app/services/banking/bank_transactions_trimmer.rb, app/services/banking/state_benefit_analyser_service.rb
Refactor classes in Banking module to improve adherence of methods to the Single Responsibility Principle (SRP)
=> Refactoring 

Gemfile, Gemfile.lock
This was switched to a github branch as the maintainer was not publishing a required fix.  That has now been released as 1.0.5 and can now be reverted to waiting for future tagged releases
=> Tech-Debt: Update I18n-tasks gem

app/services/hmrc/parsed_response/persistor.rb, spec/models/hmrc/response_spec.rb, spec/services/hmrc/parsed_response/persistor_spec.rb
some tweaks from review of base branch PR
=> [AP-3025] parse HMRC response

Gemfile, Gemfile.lock, app/webpack/packs/rails_admin.js, app/webpack/stylesheets/rails_admin.scss, config/initializers/rails_admin.rb, package.json, yarn.lock
This PR separates it from the Rails 7 PR and replaces the dependabot PR as the changes are more significant than just changing the Gem version
=> Tech debt/update rails admin

app/controllers/citizens/additional_accounts_controller.rb
Refactor nested if statements for readability
=> Refactor nested if statements for readability

app/services/ccms/manual_review_determiner.rb, config/locales/en/providers.yml, spec/services/ccms/manual_review_determiner_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2940)
- Added a check for policy_disregards? to manual_check_required? in manual_review_determiner
- Added restrictions and further_employment_information as caseworker manual review reasons on the means report …
=> ap-2940: caseworker referrals

.rubocop_todo.yml, spec/forms/legal_aid_applications/emergency_cost_override_form_spec.rb, spec/forms/outstanding_mortgage_form_spec.rb, spec/forms/providers/proceeding_merits_task/linked_children_form_spec.rb, spec/helpers/user_transactions_helper_spec.rb, spec/jobs/bank_transactions_analyser_job_spec.rb, spec/models/aggregated_cash_income_spec.rb, spec/models/applicant_spec.rb, spec/models/bank_account_spec.rb, spec/models/cfe/v1/result_spec.rb, spec/models/cfe/v4/result_spec.rb, spec/models/legal_aid_application_spec.rb, spec/models/legal_framework/serializable_merits_task_list_spec.rb, spec/models/transaction_type_spec.rb, spec/requests/feedbacks_spec.rb, spec/requests/providers/invalid_logins_spec.rb, spec/requests/providers/percentage_home_spec.rb, spec/requests/providers/policy_disregards_controller_spec.rb, spec/requests/providers/substantive_applications_spec.rb, spec/services/admin/provider_details_service_spec.rb, spec/services/ccms/requestors/applicant_add_requestor_spec.rb, spec/services/ccms/requestors/case_add_requestor_xml_blocks/non_passported_attributes_spec.rb, spec/services/ccms/requestors/case_add_requestor_xml_blocks/passported_attributes_spec.rb, spec/services/cleanup_capitial_attributes_spec.rb, spec/services/hmrc/create_responses_service_spec.rb, spec/services/reports/mis/application_detail_csv_line_spec.rb
and empty line after example group cops
=> Fix rubocop empty line after example

Gemfile, Gemfile.lock, spec/rails_helper.rb, spec/services/hmrc/parsed_response/persistor_spec.rb
reduce number of test per example and use super_diff
to identify specific unmatching attributes on faliure
Too many expectations per example can get confusing
=> Reduce tests per example

db/seeds/test_provider_populator.rb
add jsugarman to provider seed
So jsugarman can remember his login easily ;)
=> Add jsugarman to provider seed

Brewfile, README.md
Extend brewfile setup
Simplify setup by installing expected antivirus
library, clamav
=> Add clamav to brewfile

.rubocop_todo.yml, db/seeds.rb, lib/tasks/helpers/cy_helper.rb, spec/rails_helper.rb, spec/requests/v1/workers_spec.rb, spec/services/banking/bank_transaction_balance_calculator_spec.rb, spec/services/banking/bank_transactions_trimmer_spec.rb, spec/services/dashboard_event_handler_spec.rb
Fix the following offences:
-Rails/TimeZone
-RSpec/ReceiveCounts
-RSpec/Rails/HttpStatus
-Lint/RedundantDirGlobSort
=> Fix GOVUK Rubocop Offences

app/services/hmrc/mock_data/pending_response.json.erb, spec/services/hmrc/mock_interface_response_service_spec.rb
Remove all references to legacy ingresses
For completeness in line with removing all legacy ingresses
in the configuration
=> Amend mock responses with references to legacy ingresses

Gemfile.lock
Dependabot got confused and this is simpler than
trying to persuade it to rebuild properly!
=> Update: Bump google-apis-drive_v3 to 0.21.0

.github/workflows/base-docker-image.yml, .github/workflows/ci-docker-image.yml
Add slack notification on docker action completion
Initially, this will post on all completions, ultimately it should be set to only fire on fail
=> Tech-Debt: Add slack notification on job completion

app/services/hmrc/parsed_response/validator.rb, spec/services/hmrc/parsed_response/validator_spec.rb
Quieten the sentry output from HMRC responses.
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3068)
Every query to HMRC interface will result in two
response. a use_case one and a use_case two. The
use_case two are not currently valid or usable so
are always considered unpersistable for employment
purposes and so we do not need to alert on them. …
=> [AP-3068] Do not alert on use_case "two" responses

.circleci/config.yml
[Link to story](https://dsdmoj.atlassian.net/jira/software/c/projects/AP/boards/233?modal=detail&selectedIssue=AP-2968)
Updated the cloud-platform-tools docker image in circleci config.yml.
=> ap-2968: update cloud-platform docker image

.github/dependabot.yml
Add default dependabot code reviewers
One more step that could/should be automated
=> Add team members as default dependabot code reviewers

package.json, yarn.lock
Dependabot tried to update them separately
Installing them together lets the tests pass
=> Fix: Jest updates

app/controllers/providers/check_passported_answers_controller.rb, app/lib/duration_logger.rb, app/services/cfe/submission_manager.rb
Output CFE call durations (steps and total) so that the values can be monitored via kibana
=> Test: Log CFE call duration

README.md, docs/vcr_recording.md
Document VCR cassette recording and re-recording
Came out of me trying to rerecord all cassettes and the
difficulties for local env var setup in particular.
=> Add VCR recording and rerecording documentation

README.md, docs/environment_mappings.md
Document constituent parts of apply service and environment mappings
[Link to trello ticket](https://trello.com/c/tLBSVYKk/106-point-uat-envs-to-main-uat-of-dependencies-instead-of-staging)
The Apply service uses many other services which it is useful to document in one place
and map which environment uses which constituent part environment …
=> Add environment mapping details

app/controllers/providers/uploaded_evidence_collections_controller.rb, features/providers/check_multiple_employment.feature, features/providers/check_pending_employment.feature, features/providers/check_single_employment.feature
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3101)
reload @uploaded_evidence_collection when a new file is added, this adds the attachment uploaded via JS to the uploaded_evidence_collection …
=> reload evidence collection before the list is populated

config/locales/en/providers.yml, spec/requests/providers/application_merits_task/has_other_involved_children_spec.rb, spec/requests/providers/proceeding_merits_task/attempts_to_settle_controller_spec.rb
[Link to story](https://dsdmoj.atlassian.net/jira/software/c/projects/AP/boards/233?modal=detail&selectedIssue=AP-2911)
Update error messages to ensure consistency across the service.
=> AP-2911 Update error messages

app/views/providers/start/index.html.erb, config/locales/en/providers.yml, spec/requests/providers/start_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3119)
removed the column with the links
removed unused translations
updated the tests
=> AP-3119 remove column and related content

config/locales/en/activemodel.yml, config/locales/en/providers.yml, features/accessibility/provider.feature, features/providers/check_your_answers.feature, features/providers/civil_application_journey.feature, features/providers/complete_and_check_means_answers.feature, features/providers/non_passported_journey.feature
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3122)
=> AP-3122 Copy change on Vehicle age page

config/locales/en/providers.yml
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3079)
Update content on first CYA page
=> AP-3079 update content for cya page

Brewfile, bin/install_clamav_on_mac
Add git-crypt to the brewfile, this ensures it has been installed
Add a line to install clamav that creates the required socket file and sets permissions so that clam can update it as necessary
=> Update new starter scripts

app/views/shared/check_answers/_assets.html.erb, app/views/shared/check_answers/_restrictions.html.erb, config/locales/en/providers.yml, config/locales/en/shared.yml, features/accessibility/provider.feature, features/providers/back_button.feature, features/providers/check_ccms_autogrant.feature, features/providers/check_multiple_employment.feature, features/providers/check_nonpassport_autogrant.feature, features/providers/check_pending_employment.feature, features/providers/check_single_employment.feature, features/providers/check_your_answers.feature, features/providers/civil_application_journey.feature, features/providers/complete_and_check_means_answers.feature, features/providers/employed_journey.feature, features/providers/non_passported_journey.feature, features/step_definitions/civil_journey_steps.rb
Also slight change in layout of. how restrictions are presented on the page
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3142)
=> AP-3142 Change order of items on means CYA page etc

app/services/hmrc/mock_data/formerly_employed.json.erb, app/services/hmrc/mock_data/recently_employed.json.erb, app/services/hmrc/mock_interface_response_service.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3232)
=> AP-3232 Add two more HMRC mock data use cases

config/application.rb, config/initializers/mock_saml.rb, config/locales/en/accessibility_statement.yml, config/locales/en/contacts.yml, db/seeds/admin_users.rb, db/seeds/test_provider_populator.rb
As part of the re-branding of the service, the support
email has changed.  This updates all references in the
code, including tests, seed data and mailers
=> Fix: Update support-email

app/helpers/application_helper.rb, app/views/providers/open_banking_consents/show.html.erb, app/views/shared/forms/_list_items_numbered.html.erb, config/locales/en/providers.yml, features/accessibility/provider.feature, features/providers/civil_application_journey.feature, features/providers/non_passported_journey.feature, features/providers/pathways_from_check_your_answers.feature, spec/requests/providers/open_banking_consents_spec.rb
Amend open banking consent page content
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3254)
=> [AP-3254] amend open banking consent content

app/views/providers/means/other_assets/show.html.erb, app/views/providers/means/policy_disregards/show.html.erb, app/views/shared/forms/_types_of_income_form.html.erb, app/views/shared/forms/_types_of_outgoings_form.html.erb, config/locales/cy/shared.yml, config/locales/en/citizens.yml, config/locales/en/providers.yml, config/locales/en/shared.yml, features/accessibility/citizen.feature, features/accessibility/provider.feature, features/citizens/citizens.feature, features/citizens/citizens_welsh.feature, features/providers/check_ccms_autogrant.feature, features/providers/check_multiple_employment.feature, features/providers/check_pending_employment.feature, features/providers/check_single_employment.feature, features/providers/check_your_answers.feature, features/providers/civil_application_journey.feature, features/providers/complete_and_check_means_answers.feature, features/providers/employed_journey.feature, features/providers/non_passported_journey.feature, spec/requests/providers/identify_types_of_outgoings_spec.rb, spec/requests/providers/means/identify_types_of_incomes_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3203)
* Update 'None of these' checkboxes to have more descriptive content
* Update rspec tests and feature tests with new content
=> AP-3203 Update none of these checkboxes content

config/locales/en/shared.yml
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3229)
update savings and investments label content on CYA page
=> AP-3229 update savings and investments  label content on CYA page

app/views/providers/open_banking_consents/show.html.erb, config/locales/en/providers.yml, features/providers/bank_statement_upload.feature
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3300)
Update content and make it conditional on providers permissions
=> AP-3300 update consent content

app/controllers/providers/means_summaries_controller.rb, app/controllers/providers/no_eligibility_assessments_controller.rb, app/models/concerns/non_passported_state_machine.rb, app/models/legal_aid_application.rb, app/services/ccms/manual_review_determiner.rb, app/services/flow/flows/provider_capital.rb, app/services/results_panel_selector.rb, app/views/providers/capital_income_assessment_results/show.html.erb, app/views/providers/means_summaries/show.html.erb, app/views/providers/merits_task_lists/show.html.erb, app/views/providers/no_eligibility_assessments/show.html.erb, app/views/providers/open_banking_consents/show.html.erb, app/views/shared/assessment_results/_no_cfe_result.html.erb, config/locales/en/providers.yml, config/locales/en/shared.yml, config/routes.rb, spec/factories/legal_aid_applications.rb, spec/requests/providers/means_summaries_spec.rb, spec/requests/providers/no_eligibility_assessments_spec.rb, spec/services/ccms/manual_review_determiner_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3265)
Add new result panel
Remove call to CFE for these cases (handle this in limited way)
skip the capital_assessment_pages and go to a new page to display a result panel without any cfe call. …
=> Ap 3265 Bank Statement blue result panel

features/providers/bank_statement_flow.feature, features/providers/bank_statement_upload.feature
BUGFIX:
There is a bank_upload feature test that has become very flaky. This PR attempts to fix the issue by separating the tests into separate files to stop the timing/duplication issue that appears to be causing the failure on circle …
=> BUGFIX: separate the flaky test to run on its own

app/views/providers/about_the_financial_assessments/show.html.erb, config/locales/en/providers.yml, features/accessibility/provider.feature, features/providers/non_passported_journey.feature, features/step_definitions/civil_journey_steps.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3205)
Update contemt.
Note: the linked heroku deployments for the current and proposed (on the associated JIRA ticket ap-2486) are dead
Changes to content made based on the wording of ap-3205 …
=> AP-3205 remove old content, list and translations add new title

features/providers/bank_statement_flow.feature, features/providers/bank_statement_upload.feature, features/step_definitions/bank_statement_uploaded_steps.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3330)
Add employed applicant to the setup for the feature tests
update the flow to expect the employment_information page enter details and progress to the income questions …
=> AP-3330 add employed applicant to feature tests for bank statement evidence

config/locales/en/activemodel.yml, config/locales/en/providers.yml, features/providers/complete_and_check_means_answers.feature, features/providers/non_passported_journey.feature, features/step_definitions/civil_journey_steps.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2324)
Update the dependant relationship question so that it makes sense to providers
=> AP-2324: Update dependant content

app/controllers/providers/no_eligibility_assessments_controller.rb, app/models/cfe/base_result.rb, app/models/cfe/empty/empty_result.rb, app/models/cfe/empty/result.rb, app/models/concerns/cfe_submission_state_machine.rb, config/locales/en/providers.yml, config/locales/en/shared.yml, spec/factories/cfe_results/empty/mock_results.rb, spec/factories/cfe_results/empty/results.rb, spec/factories/legal_aid_applications.rb, spec/models/cfe/empty/result_spec.rb, spec/requests/providers/no_eligibility_assessments_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3338)
Add a new blank cfe result type
Create a cfe submission record indicating no cfe_calll was made
Crete a cfe_result record for use by subsequent pages
add tests for everything
Add new state to cfe state machine …
=> Ap 3338 create blank cfe result for bank_statement_upload journey

app/controllers/admin/settings_controller.rb, app/forms/settings/setting_form.rb, app/models/setting.rb, app/views/admin/settings/show.html.erb, config/locales/en/admin.yml, config/locales/en/helpers.yml, db/migrate/20220727125202_add_mini_loop_flag_to_settings.rb, db/schema.rb, lib/tasks/setup_db_for_testing.rake, spec/models/setting_spec.rb, spec/requests/admin/settings_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3358) pt.1
Add a feature flag for the mini-loop
=> AP-3358: Add feature flag for mini-loop

app/controllers/providers/no_eligibility_assessments_controller.rb, app/models/cfe/base_result.rb, app/models/cfe/empty/empty_result.rb, app/models/cfe/empty/result.rb, app/models/concerns/cfe_submission_state_machine.rb, app/services/results_panel_selector.rb, config/locales/en/providers.yml, config/locales/en/shared.yml, spec/factories/cfe_results/empty/mock_results.rb, spec/factories/cfe_results/empty/results.rb, spec/factories/legal_aid_applications.rb, spec/models/cfe/empty/result_spec.rb, spec/requests/providers/no_eligibility_assessments_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3338)
Reverted original branch due to an issue with blue box result panel for dwp_override clients
Fixed in the final commit on this branch.
=> Ap 3338 blank cfe v0 1

config/locales/en/activemodel.yml
Walkthrough of new journey identified an issue with an error message, this change fixes the content.
=> BUGFIX: update error message content

app/models/provider.rb, db/seeds/permissions.rb, lib/tasks/full_section_8.rake, spec/factories/permissions.rb, spec/factories/providers.rb, spec/models/provider_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3361)
=> ap-3361: add new permission for full s8

app/services/ccms/parsers/applicant_search_response_parser.rb, app/services/ccms/requestors/base_requestor.rb, features/providers/bank_statement_upload.feature, spec/data/ccms/applicant_search_response_number_not_matched.xml, spec/services/ccms/parsers/applicant_search_response_parser_spec.rb
During the "CCMS dance" to send data over to CCMS, we send name, dob, nino to ask CCMS if the applicant already exists on their side.  If it does, it returns a applicant ref which we use, if it doesn't we create a new applicant on ccms.
There has been a case where CCMS has returned a match, but it turns out that the match wasn't an exact match (different NINO, different first name), with a match level indicator of `Number Not Matched`
This PR examines the mactch level indicator, and if `Number Not Matched` returns a nil ccms_applicant reference, the same as if there had been no match at all.  This will cause a new applicant with the right details to be created.
Before you ask people to review this …
=> AP-3307 Handle CCMS returning Number Not Matched

app/controllers/admin/settings_controller.rb, app/forms/settings/setting_form.rb, app/models/setting.rb, app/views/admin/settings/show.html.erb, config/locales/en/admin.yml, config/locales/en/helpers.yml, db/migrate/20220818102535_add_loop_flag_to_settings.rb, db/schema.rb, lib/tasks/setup_db_for_testing.rake, spec/models/setting_spec.rb, spec/requests/admin/settings_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3388)
Add a feature flag for the next stage of the proceeding loop
There may be a third, `full-loop` stage so this will either become the full loop by default or, be an interstitial step between the mini and full loops …
=> AP-3388: Add feature flag for next loop stage

app/controllers/admin/settings_controller.rb, app/forms/settings/setting_form.rb, app/models/setting.rb, app/views/admin/settings/show.html.erb, config/locales/en/admin.yml, config/locales/en/helpers.yml, db/migrate/20220824162240_add_enhanced_bank_upload_feature_flag_to_settings.rb, db/schema.rb, lib/tasks/setup_db_for_testing.rake, spec/models/setting_spec.rb, spec/requests/admin/settings_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3443)
Add a feature flag to hide the new enhanced bank statement upload journey behind
=> Ap 3443 Add enhanced bank statement upload journey feature flag

app/views/providers/limitations/_proceeding_type.html.erb, config/locales/en/providers.yml
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3440)
Add the client role to the limitations page behind the mini-loop feature flag
=> AP-3440: Update limitations page

app/views/providers/limitations/_cost_limits.html.erb, app/views/providers/limitations/_proceeding_type.html.erb, app/views/providers/limitations/_proceeding_types_with_df.html.erb, config/locales/en/layouts.yml, config/locales/en/providers.yml
[AP-3190](https://dsdmoj.atlassian.net/browse/AP-3190): Add proceeding name to change links on the 'what you're applying for' page
[AP-3193](https://dsdmoj.atlassian.net/browse/AP-3188): Fix heading hierarchy on 'what you're applying for' page
[AP-3188](https://dsdmoj.atlassian.net/browse/AP-3188): Remove abbreviation from footer link 
All changes are following the DAC recommendations  …
=> AP-3190, AP-3193 and AP-3188: DAC accessibility changes

app/views/layouts/application.html.erb, app/views/providers/bank_statements/_uploaded_files.html.erb, app/views/providers/bank_statements/show.html.erb, app/views/providers/check_merits_answers/show.html.erb, app/views/providers/confirm_multiple_delegated_functions/show.html.erb, app/views/providers/delete/show.html.erb, app/views/providers/substantive_applications/show.html.erb, app/views/shared/_applicant_declaration.html.erb, app/views/shared/partials/_modal_dialogue.html.erb, config/locales/en/generic.yml, config/locales/en/layouts.yml, config/locales/en/providers.yml, config/locales/en/shared.yml
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3457)
Update content to give providers more info about which documents they need to upload, and warn them that unreadable statements may result in a delay to the application …
=> AP-3457 content changes on bank statement upload page

app/controllers/providers/means_summaries_controller.rb, app/models/cfe/submission.rb, app/models/concerns/cfe_submission_state_machine.rb, app/services/cfe/create_regular_transactions_service.rb, app/services/cfe/service_set.rb, app/services/flow/flows/provider_capital.rb, spec/cassettes/CFE_SubmissionManager/_call/when_the_application_is_non-passported/completes_process.yml, spec/cassettes/CFE_SubmissionManager/_call/when_the_application_is_non-passported_with_enhanced_bank_statement_upload_enabled/completes_process.yml, spec/cassettes/CFE_SubmissionManager/_call/when_the_application_is_passported/completes_process.yml, spec/factories/legal_aid_applications.rb, spec/models/cfe/submission_spec.rb, spec/models/concerns/cfe_submission_state_machine_spec.rb, spec/requests/providers/means_summaries_spec.rb, spec/services/cfe/create_regular_transactions_service_spec.rb, spec/services/cfe/service_set_spec.rb, spec/services/cfe/submission_manager_spec.rb
Retrieve cfe result using regular transactions
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3451)
Add regular transaction CFE service "set" to store the CFE
endpoints that will need to be hit and add a regular transactions
service to to convert the db records to the expected payload objects to be sent to CFE. …
=> [AP-3451] retrieve cfe result using regular transactions

app/controllers/providers/transactions_controller.rb
Add safe operator to call
Caused a [sentry error](https://sentry.io/organizations/ministryofjustice/issues/3643901963/?project=5416054&referrer=slack) to be raised in production
=> Add safe operator to chained method call

app/models/cfe/base_result.rb, app/services/ccms/manual_review_determiner.rb, config/locales/en/providers.yml, spec/services/ccms/manual_review_determiner_spec.rb
where cfe returns a result of ineligible
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3504)
=> ap-3504: add ineligible to means report caseworker review reasons

app/controllers/providers/application_merits_task/client_offered_undertakings_controller.rb, app/forms/providers/application_merits_task/client_offered_undertakings_form.rb, app/models/application_merits_task/undertaking.rb, app/models/legal_aid_application.rb, app/services/flow/flows/provider_merits.rb, app/views/providers/application_merits_task/client_offered_undertakings/show.html.erb, app/views/providers/check_merits_answers/show.html.erb, app/views/providers/merits_reports/show.html.erb, app/views/shared/_review_application.html.erb, app/views/shared/check_answers/_merits.html.erb, config/locales/en/activemodel.yml, config/locales/en/providers.yml, config/locales/en/shared.yml, config/routes.rb, db/anonymise/rules.rb, db/migrate/20221017130541_create_undertakings.rb, db/schema.rb, spec/factories/undertakings.rb, spec/forms/providers/application_merits_task/client_offered_undertakings_form_spec.rb, spec/requests/providers/application_merits_task/client_offered_undertakings_controller_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3492)
Add the second of the two merits questions required for the mini-loop
=> AP-3492: Add merits question 08 - Client Undertakings

spec/services/provider_details_creator_spec.rb
This test file contained a [flaky spec].
Trying to isolate the flaky spec in order to reproduce and fix the issue proved difficult, so I took a more pragmatic approach to resolve the issue.
1. Ensure each test is self-contained
2. Ensure each test is repeatable (i.e deterministic)
3. Avoid using `let!` (linked to step 1.)
In the process of refactoring the tests, it also highlighted some tests that didn't add any value -those have been removed.
I'm confident the refactored tests are not flaky, and will improve the robustness of our test suite -saving us frustration, time, and money.
[flaky spec]: https://app.circleci.com/pipelines/github/ministryofjustice/laa-apply-for-legal-aid/18165/workflows/ae431d1e-b060-4638-8b78-91df79353cc1/jobs/95186/steps
=> Fix flaky `ProviderDetailsCreator` spec

.overcommit.yml, app/webpack/src/worker_waiter.js, babel.config.js, package.json, yarn.lock
bump axios from 1.1.2 to 1.1.3 and fix errors arising
Amend @babel/plugin-proposal-class-properties to not use loose mode
to remove warning and amend overcommit's command to run standard using
`yarn run` explicitly so uses yarn "context".
import 'axios' rather than require it. Previoulsy
this resulted in a CI lint failure as below:
```
FAIL spec/javascript/worker_waiter.spec.js
● worker is complete after 2 API calls › polls the correct endpoint twice
TypeError: Cannot read properties of undefined (reading 'get')
3 | async function checkWorkerStatus () {
4 |   const workerId = document.querySelector('.worker-waiter').getAttribute('data-worker-id')
> 5 |   const response = await axios.get(`/v1/workers/${workerId}`)
|                                ^
6 |   return response.data
7 | }
8 |
at …
```
=> bump axious 1.1.3 and fix

app/helpers/proceeding_helper.rb, app/views/shared/_review_application.html.erb, app/views/shared/check_answers/_proceeding_details_section.html.erb, config/locales/en/shared.yml, spec/helpers/proceeding_helper_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3525)
Added new proceeding_details_section partial on Review and print your application page to be displayed when the miniloop is enabled. …
=> ap-3525: Display new proceeding detail partial when miniloop enabled

app/views/admin/firms/index.html.erb, app/views/citizens/legal_aid_applications/index.html.erb, app/views/layouts/mailer.html.erb, app/views/layouts/pdf.html.erb, app/views/providers/means/employment_incomes/show.html.erb, app/views/saml_idp/idp/saml_post.html.erb, app/views/shared/_results_total_bold_row.html.erb, app/webpack/src/details-polyfill.js, spec/requests/providers/capital_income_assessment_results_spec.rb
[SonarCloud - Apply - Bugs](https://dsdmoj.atlassian.net/browse/AP-3520)
Resolve SonarClouds reported bugs. This resolves some of the existing issues in order to reduce and resolve our quality gate thresholds.
=> Resolve SonarCloud Bugs

db/seeds/test_provider_populator.rb
Set up a branch for user research
=> TEMP: Add an email for user research on main UAT

config/locales/en/helpers.yml, config/locales/en/providers.yml, config/locales/en/transaction_types.yml, features/providers/enhanced_bank_upload/check_your_answers.feature, features/providers/enhanced_bank_upload/enhanced_bank_upload_flow.feature
Change content for "housing benefits" --> "Housing Benefit"
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3564)
Comes out of discussion between BA and Content
designer which can be summarised as 
> this is a specific [singular] named State Benefit
and [gov.uk capitalises it](https://www.gov.uk/housing-benefit). …
=> [AP-3654] amend housing benefit content

app/services/legal_framework/merits_tasks_service.rb, spec/services/legal_framework/merits_tasks_service_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3572)
Ensure new questions required by section 8 are ignored unless the feature flag is set
=> AP-3572: Update merits task handling

app/controllers/providers/proceeding_merits_task/specific_issue_controller.rb, app/forms/providers/proceeding_merits_task/specific_issue_form.rb, app/models/proceeding.rb, app/models/proceeding_merits_task/specific_issue.rb, app/services/flow/flows/provider_merits.rb, app/services/flow/merits_loop.rb, app/views/providers/proceeding_merits_task/specific_issue/show.html.erb, app/views/shared/check_answers/_merits.html.erb, config/locales/en/activemodel.yml, config/locales/en/providers.yml, config/locales/en/shared.yml, config/routes.rb, db/anonymise/rules.rb, db/migrate/20221026095914_create_specific_issue.rb, db/schema.rb, spec/factories/legal_framework_merits_task_list.rb, spec/factories/legal_framework_serialized_merits_task_list.rb, spec/factories/proceedings.rb, spec/forms/providers/proceeding_merits_task/specific_issue_form_spec.rb, spec/requests/providers/proceeding_merits_task/attempts_to_settle_controller_spec.rb, spec/requests/providers/proceeding_merits_task/specific_issue_controller_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3485)
Implement the Specific Issue, section 8 question.
Add a DB object to store the responses
Add a new form for validating the answer
Add the route, controller and view
Update the merits task flow and routing
Updated the merits partial to show the response on the CYA, review and merits_report pages …
=> AP-3485: Add specific issue merits question

app/controllers/providers/proceeding_merits_task/prohibited_steps_controller.rb, app/forms/providers/proceeding_merits_task/prohibited_steps_form.rb, app/models/proceeding.rb, app/models/proceeding_merits_task/prohibited_steps.rb, app/services/flow/flows/provider_merits.rb, app/services/flow/merits_loop.rb, app/views/providers/proceeding_merits_task/prohibited_steps/show.html.erb, app/views/shared/check_answers/_merits.html.erb, config/locales/en/activemodel.yml, config/locales/en/providers.yml, config/locales/en/shared.yml, config/routes.rb, db/anonymise/rules.rb, db/migrate/20221027065931_create_prohibited_steps.rb, db/schema.rb, spec/factories/legal_framework_merits_task_list.rb, spec/factories/legal_framework_serialized_merits_task_list.rb, spec/factories/proceedings.rb, spec/factories/prohibited_steps.rb, spec/forms/providers/proceeding_merits_task/prohibited_steps_form_spec.rb, spec/requests/providers/proceeding_merits_task/linked_children_spec.rb, spec/requests/providers/proceeding_merits_task/prohibited_steps_controller_spec.rb, spec/support/shared_examples/provider_auth_shared_examples.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3486)
Implement the Prohibited steps, section 8 question.
Add a DB object to store the responses
Add a new form for validating the answer
Add the route, controller and view
Update the merits task flow and routing
Updated the merits partial to show the response on the CYA, review and merits_report pages …
=> AP-3486: Add prohibited steps merits question

spec/services/legal_framework/merits_tasks_service_spec.rb
This was a placeholder spec setup until the nature_of_urgency question was actually asked
=> Fix: Remove TODO code block

app/controllers/providers/proceeding_merits_task/opponents_application_controller.rb, app/forms/providers/proceeding_merits_task/opponents_application_form.rb, app/models/proceeding.rb, app/models/proceeding_merits_task/opponents_application.rb, app/services/flow/flows/provider_merits.rb, app/services/flow/merits_loop.rb, app/views/providers/proceeding_merits_task/opponents_application/show.html.erb, app/views/providers/proceeding_merits_task/prohibited_steps/show.html.erb, app/views/shared/check_answers/_merits.html.erb, config/locales/en/activemodel.yml, config/locales/en/providers.yml, config/locales/en/shared.yml, config/routes.rb, db/anonymise/rules.rb, db/migrate/20221103164239_create_opponents_application.rb, db/schema.rb, spec/factories/legal_framework_serialized_merits_task_list.rb, spec/factories/proceeding_merits_task/opponents_application.rb, spec/forms/providers/proceeding_merits_task/opponents_application_form_spec.rb, spec/requests/providers/proceeding_merits_task/chances_of_success_spec.rb, spec/requests/providers/proceeding_merits_task/opponents_application_controller_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3488)
- Added a new page for the opponents application question (controller, form, view, route)
- Added a new DB table opponents_applications
- This question appears on a proceeding level, for any proceeding which has the client involvement type as defendant
TODO: 
- Write tests …
=> AP-3488 Opponent application merits task list question

app/controllers/concerns/providers/applicant_details_checkable.rb, app/controllers/providers/capital_introductions_controller.rb, app/controllers/providers/check_benefits_controller.rb, app/controllers/providers/confirm_dwp_non_passported_applications_controller.rb, app/controllers/providers/has_evidence_of_benefits_controller.rb, app/controllers/providers/received_benefit_confirmations_controller.rb
Extract common methods to mixin
[came out of story](https://dsdmoj.atlassian.net/browse/AP-3608)
DRY it out
=> Refactor - move shorthand methods to mixin

app/controllers/admin/settings_controller.rb, app/forms/settings/setting_form.rb, app/models/setting.rb, app/views/admin/settings/show.html.erb, config/locales/en/admin.yml, db/migrate/20221110161139_add_mtr_flag_to_settings.rb, db/schema.rb, spec/models/setting_spec.rb, spec/requests/admin/settings_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3609)
Add a feature flag for MTR changes
=> AP-3609 add feature flag for MTR

app/helpers/proceeding_helper.rb, app/views/providers/limitations/_proceeding_type.html.erb, spec/helpers/proceeding_helper_spec.rb
review and print application pages
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3524)
=> ap-3524: display multiple scope limitations on limitations and

config/locales/en/providers.yml
Add missing full stop
[relates to story](https://dsdmoj.atlassian.net/browse/AP-3608)
Noticed by content designer.
=> Add missing fullstop

app/services/required_document_category_analyser.rb, app/validators/document_category_validator.rb, config/locales/en/activemodel.yml, config/locales/en/providers.yml, config/locales/en/shared.yml, db/seeds/document_categories.csv, spec/factories/legal_aid_applications.rb, spec/factories/proceedings.rb, spec/models/document_category_spec.rb, spec/services/required_document_category_analyser_spec.rb
=> Ap 3404 add new supporting evidence categories

lib/tasks/cucumber_steps.rake, spec/factories/legal_aid_applications.rb, spec/services/legal_aid_applications/calculation_date_service_spec.rb
Refactor and extend calculation date service spec
[while investigating spike](https://dsdmoj.atlassian.net/browse/AP-3629)
Extend to cover the existing expected behaviour
for multiple proceedings with delegated functions..
Fix Style/RedundantEach cop violation that popped up!
- You should …
=> Spec multiple proceedings with delegated function date calculation

app/services/age_calculator.rb, spec/services/age_calculator_spec.rb
Refactor age calculator spec
[relates to spike](https://dsdmoj.atlassian.net/browse/AP-3629)
For clarity and to cover leap years
=> Refactor age calculator spec

config/initializers/mock_saml.rb
Add jsugarman to mock saml
so I can login for testing email receipt etc
=> Add myself to mock saml

app/views/shared/review_application/_questions_and_answers.html.erb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3706)
Match the proceeding details heading to the other section headings
=> AP-3706: Update review and print heading for proceeding details

config/locales/en/providers.yml
Fix typo on email address hint
=> Fix typo on email address hint

config/locales/en/activemodel.yml, config/locales/en/providers.yml
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3722)
A caseworker review identified that the bullet point for the Section 8 court order could be confusing so the removal of `opponents` was agreed
=> AP-3722: Update the support evidence bullet point list

config/locales/en/activemodel.yml, config/locales/en/providers.yml, config/locales/en/shared.yml, features/accessibility/provider.feature, features/providers/check_ccms_autogrant.feature, features/providers/check_multiple_employment.feature, features/providers/check_nonpassport_autogrant.feature, features/providers/check_pending_employment.feature, features/providers/check_single_employment.feature, features/providers/civil_application_journey.feature, features/providers/merits_task_list.feature, features/providers/mini-loop/merits_questions.feature, features/providers/non_means_tested_journey/without_delegated_functions.feature, spec/requests/providers/application_merits_task/opponents_mental_capacities_controller_spec.rb, spec/requests/providers/merits_task_lists_controller_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3723)
Update the references so that it reflects the changes requested by caseworkers
=> AP-3723: Update mental capacity question wording

config/locales/en/activemodel.yml, config/locales/en/providers.yml, config/locales/en/shared.yml, features/providers/merits_task_list.feature, spec/requests/providers/application_merits_task/matter_opposed_reasons_controller_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3720)
Update the references so that it reflects the changes requested by caseworkers
=> AP-3720: Matter opposed question

config/locales/en/activemodel.yml, config/locales/en/providers.yml
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3724)
Update the Opponent Application question to clarify to providers that they should confirm that the matter is at court
=> AP-3724: Update OpponentApplication question

app/views/providers/legal_aid_applications/_legal_aid_applications.html.erb, config/locales/en/providers.yml, features/providers/deleting_applications.feature, features/step_definitions/generic_steps.rb, spec/requests/providers/legal_aid_applications_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3200)
Update the application delere button labelling to improve text for screen reader software, add a visually hidden span that details the application reference and applicant name for the user
Also updates the table header to clarify use of the column …
=> AP-3200: Update delete button labelling

app/views/providers/means_reports/show.html.erb, features/providers/means_report.feature
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3710)
Amended means report to remove everything beneath the client details section for non means tested applications
Amended means_report.feature to reflect/test for this change …
=> Ap 3710 means report non means tested

app/forms/vehicle_form/remaining_payment_form.rb, app/views/providers/vehicles/remaining_payments/show.html.erb, app/views/shared/check_answers/_vehicles.html.erb, features/providers/check_your_answers.feature, features/step_definitions/check_your_answers_steps.rb, spec/requests/providers/vehicles/remaining_payments_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3331)
Save answer when returning from the CYA page
Add feature tests to check that answer is saved on return
=> AP-3331 save vehicles remaining payments answer

.github/workflows/docker-image-scan.yml
This adds a GitHub action to scan the application docker image 
using Snyk each day. The workflow runs each day at 05:45am, 
and the results are uploaded to GitHub CodeQL.
=> Use Snyk to scan docker image daily

.rubocop_todo.yml, spec/forms/applicants/basic_details_form_spec.rb, spec/forms/applicants/email_form_spec.rb, spec/forms/legal_aid_applications/shared_ownership_form_spec.rb, spec/forms/outstanding_mortgage_form_spec.rb, spec/helpers/check_answer_url_helper_spec.rb, spec/lib/omni_auth/hmrc_spec.rb, spec/models/aggregated_cash_income_spec.rb, spec/models/aggregated_cash_outgoings_spec.rb, spec/models/dashboard/single_object/applicant_email_spec.rb, spec/models/dashboard/single_object/feedback_spec.rb, spec/models/dashboard/single_object/provider_data_spec.rb, spec/requests/admin_users/omniauth_callbacks_spec.rb, spec/requests/applicants/omniauth_callbacks_spec.rb, spec/requests/backable_spec.rb, spec/requests/citizens/bank_spec.rb, spec/requests/citizens/check_answers_spec.rb, spec/requests/errors_spec.rb, spec/requests/providers/check_merits_answers_spec.rb, spec/requests/providers/check_passported_answers_spec.rb, spec/requests/providers/check_provider_answers_spec.rb, spec/requests/providers/means/own_home_spec.rb, spec/services/ccms/requestors/case_add_requestor_spec.rb, spec/services/ccms/requestors/case_add_requestor_xml_blocks/non_passported_variable_attributes_spec.rb, spec/services/flow/base_flow_service_spec.rb, spec/services/page_history_service_spec.rb
Fix violations of the following cops (all fixed with autocorrect):-
RSpecHookArgument
RSpecHooksBeforeExamples
RSpecLetBeforeExamples
RSpecPredicateMatcher
RSpecScatteredLet
=> Rubocop rspec todos

docs/CODEOWNERS
[Add CODEOWNERS branch protection setting](https://dsdmoj.atlassian.net/browse/AP-2936)
Adds a `CODEOWNERS` file requiring all pull requests be approved by a member of the `laa-apply-for-legal-aid` GitHub team.
=> [AP-2936] Add codeowners file

app/services/digest_exporter.rb, spec/services/digest_exporter_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3794)
This PR is another attempt to make the digest export more reliable, the SpreadsheetError has been renamed so it can be re-used and the delete_rows method (which could only be called for row 2+) has been replaced with a lower level Google::Apis call that allows the deletion of all rows and columns, leaving only cell A1 behind
The header rows have been incorporated into the @rows variable so that a single write function now exports all data in a single hit (rather than write 1 row, then rows 2 to 25K!)
This still needs refactoring but I would like to get it functioning before making more refinements!
> The last time this script ran it took ~7 minutes for the old delete_rows method to run, according to kibana
>
> It will be …
=> AP-3794: Update DigestExporter... again

app/controllers/providers/check_provider_answers_controller.rb, app/controllers/providers/use_ccms_under16s_controller.rb, app/models/applicant.rb, app/models/concerns/base_state_machine.rb, app/models/legal_aid_application.rb, app/services/flow/flows/provider_start.rb, app/views/providers/start/index.html.erb, app/views/providers/use_ccms/show.html.erb, app/views/providers/use_ccms_under16s/show.html.erb, config/locales/en/providers.yml, config/routes.rb, features/cassettes/Applicant_under_16_blocked_before_or_after_MTR_phase_one_enabled/I_am_NOT_instructed_to_use_CCMS_when_applicant_was_under_16_on_earliest_delegated_function_date.yml, features/cassettes/Applicant_under_16_blocked_before_or_after_MTR_phase_one_enabled/I_am_instructed_to_use_CCMS_when_applicant_was_under_16_on_earliest_delegated_function_date.yml, features/providers/applicant_details.feature, features/providers/applicant_under_16_blocked.feature, features/step_definitions/applicant_detail_steps.rb, spec/concerns/base_state_machine_spec.rb, spec/factories/applicants.rb, spec/models/applicant_spec.rb, spec/models/legal_aid_application_spec.rb, spec/requests/providers/check_provider_answers_spec.rb
Add pre-MTR phase one under 16 interrupt page
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3776)
Under 16s cannot apply through Apply, for section 8
or any other matter, until MTR phase one is enabled. The
provider should be redirected to CCMS.
This is because under 16s require a special means test that
apply does not implement, but CCMS does. …
=> [AP-3776] Add pre-MTR phase one under 16 interrupt page

app/assets/stylesheets/helpers.scss, app/assets/stylesheets/print-styles.scss, app/models/applicant.rb, app/models/legal_aid_application.rb, app/views/providers/confirm_client_declarations/show.html.erb, app/views/providers/declarations/show.html.erb, app/views/providers/end_of_applications/show.html.erb, app/views/providers/open_banking_guidances/show.html.erb, app/views/providers/review_and_print_applications/show.html.erb, app/views/shared/_applicant_declaration.html.erb, app/views/shared/_printable_over_18_declaration.html.erb, app/views/shared/_printable_under_18_declaration.html.erb, app/views/shared/forms/_list_with_items.html.erb, app/views/shared/review_application/_questions_and_answers.html.erb, config/locales/cy/shared.yml, config/locales/en/activemodel.yml, config/locales/en/providers.yml, config/locales/en/shared.yml, features/providers/non_means_tested_journey/certification_test.feature, features/providers/non_means_tested_journey/without_delegated_functions.feature, features/providers/review_and_print.feature, features/step_definitions/civil_journey_steps.rb, spec/forms/legal_aid_applications/confirm_client_declaration_form_spec.rb, spec/models/applicant_spec.rb, spec/models/legal_aid_application_spec.rb, spec/requests/providers/confirm_client_declarations_controller_spec.rb, spec/requests/providers/review_and_print_applications_controller_spec.rb, spec/requests/providers/submitted_applications_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3788)
Content change following review by content designer and others
\* in which case all existing content can use the `under_18?` method to handle the conditional logic, but this impacts all these changes plus previous work done on the client declaration as well as naming considerations [partials and translation impacts]  - see notes below.
This [commit switches to using under 18 logic](https://github.com/ministryofjustice/laa-apply-for-legal-aid/pull/4973/commits/3c4625be67ce902ea91bbc2e5de131ccefb41f80) rather than non-means-tested logic. If BA and content agree it can remain in but if not then it can just be removed.
> if the case continues after their 18th birthday, we may reassess their income and capital to check if they should …
=> [AP-3778] Under 18 content changes

app/controllers/admin/settings_controller.rb, app/forms/settings/setting_form.rb, app/models/setting.rb, app/views/admin/settings/show.html.erb, config/locales/en/admin.yml, db/migrate/20230228112837_add_partner_means_assessment_to_settings.rb, db/schema.rb, spec/models/setting_spec.rb, spec/requests/admin/settings_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3816)
=> Add Partner means assessment feature flag

Dockerfile, docker/apply_ci.dockerfile
[Sonar security hotspots](https://dsdmoj.atlassian.net/browse/AP-3519)
- Make sure use of globbing in Dockerfile is safe `COPY Gemfile*` => `COPY Gemfile Gemfile.lock`
- Make sure protocol in `docker/apply_ci.dockerfile` is safe `http` => `https` …
=> [AP-3519] Fix: Sonar security hotspots

Brewfile, docs/troubleshooting.md
- add to troubleshooting file
- update postgresql command to specifically install v14
When setting up repo locally, I encountered some issues, so i've updated the README to suggest ways to fix
=> add to troubleshooting file

bin/install_clamav_on_mac
Update `install_clamav_on_mac` script to work on m1 mac
=> update clamav script to work on m1 mac

package.json, yarn.lock
Hopefully this will reduce the number of security alerts
=> Security: bump esbuild

.circleci/config.yml
We were using the basic executor and then pulling in packages that were included in the cloud-platform executor
=> Fix: Update circle build and push step

.circleci/config.yml
Update ecr cleanup script to use cloud-platform-executor
=> Update ecr cleanup script

app/controllers/providers/about_the_financial_assessments_controller.rb, spec/requests/providers/about_the_financial_assessments_controller_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3951)
Remove any scheduled emails that do not match the
current stored email for the applicant
=> AP-3951: Remove scheduled mails on change

app/services/cfe/compare_submission.rb, spec/fixtures/files/cfe_civil_comparison/v5/flat_array.json, spec/fixtures/files/cfe_civil_comparison/v6/flat_array.json, spec/services/cfe/compare_submission_spec.rb
Add fixtures and test for when a flat array of values is mismatched e.g. remarks with GUIDs
=> Update CFE Comparison

app/controllers/providers/about_financial_means_controller.rb, app/services/flow/flows/provider_dwp_override.rb, app/services/flow/flows/provider_start.rb, app/views/providers/about_financial_means/show.html.erb, config/locales/en/providers.yml, config/routes.rb, features/accessibility/provider.feature, features/providers/applicant_details.feature, features/providers/change_email.feature, features/providers/non_passported_journey/used_delegated_functions.feature, features/providers/non_passported_journey/waiting_for_applicant.feature, features/providers/passported_journey.feature, features/providers/pathways_from_check_your_answers.feature, spec/requests/providers/about_financial_means_controller_spec.rb, spec/requests/providers/confirm_dwp_non_passported_applications_spec.rb, spec/requests/providers/has_evidence_of_benefits_spec.rb, spec/requests/providers/received_benefit_confirmations_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3902)
add what you need to do page
- add view and controller
- put content in translation file
- reroute accordingly
- update tests
To do
=> AP-3902: What you need to do next page (before financial means assessment)

app/views/providers/bank_statements/show.html.erb, config/locales/en/providers.yml, features/providers/bank_statement_upload/happy_path_journey.feature, features/providers/bank_statement_upload/uploading_files.feature
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4088)
Make content updates and tidy up
- change content to match designs
- tidy up code indentation
- order `providers.yml` alphanumerically
=> AP-4088: Update client upload page

app/forms/providers/means/applicant_owner.rb, app/forms/providers/means/housing_benefit_form.rb, app/forms/providers/means/regular_income_form.rb, app/forms/providers/means/regular_outgoings_form.rb, app/forms/providers/means/regular_transaction_form.rb, db/migrate/20230515130906_update_regular_transactions.rb, db/schema.rb, lib/tasks/migrate_regular_transaction_owners.rake, spec/factories/legal_aid_applications.rb, spec/forms/providers/means/housing_benefit_form_spec.rb, spec/forms/providers/means/regular_income_form_spec.rb, spec/forms/providers/means/regular_outgoings_form_spec.rb, spec/forms/providers/means/regular_transaction_form_spec.rb, spec/requests/providers/means/housing_benefits_controller_spec.rb, spec/requests/providers/means/regular_incomes_controller_spec.rb, spec/requests/providers/means/regular_outgoings_controller_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3909)
Preparation for splitting the benefit regular transactions and partner handling
This PR adds a polymorphic, Owner, to the regular transactions and then updates the regular transaction forms to populate the current versions with the current legal aid applications' applicant.
It also adds a rake task to populate existing records by looping through each regular transaction and updating the owner fields.
Immediately after this is merged, new regular transactions will be recorded with an owner.  The rake task will be run on each environment to update all existing records …
=> AP-3909: Update regular transactions ownership

docker/apply_ci.dockerfile
This PR starts with an empty commit to test the theory that _all_ runs will fail
Then I'll update the dockerfile to explicitly install the requirements that have switched from `will be installed` to `recommended packages` …
=> Urgent: Fix docker build

app/services/cfe_civil/submission_builder.rb, spec/cassettes/CFECivil_SubmissionBuilder/_call/if_HostEnv_is_not_set/still_generates_the_expected_JSON_but_uses_missing_in_the_header.yml, spec/services/cfe_civil/submission_builder_spec.rb
Generate UserAgent header to allow CFECivil to monitor and track submission requests by application and platform
=> Update: CFE-Civil headers

app/javascript/src/cookie_banner.js, app/javascript/src/dropzone.js, app/javascript/src/modal-dialogue.js
Fix code analysis tool bugs & security
=> Fix code analysis tool bugs & security

app/services/cfe_civil/submission_builder.rb
The User-Agent header was misnamed and this corrects it from UserAgent
=> Update: CFECivil headers

app/services/cfe/compare_submission.rb, spec/fixtures/files/cfe_civil_comparison/v5/missing_vehicle.json, spec/fixtures/files/cfe_civil_comparison/v6/missing_vehicle.json, spec/services/cfe/compare_submission_spec.rb
A bug in CFE Civil is preventing comparisons
This PR flags these failures as "errors" so that we can manually assess and ignore them.  
This will allow testing to resume and when the bug is fixed, regular checks can resume. …
=> CFE-Civil comparison: Update vehicle handling

app/controllers/providers/partners/about_financial_means_controller.rb, app/services/flow/flows/provider_capital.rb, app/views/providers/about_financial_means/show.html.erb, app/views/providers/partners/about_financial_means/show.html.erb, config/locales/en/providers.yml, config/routes.rb, features/providers/partner_means_assessment/means_check.feature, features/step_definitions/partner_means_check.rb, spec/requests/providers/partners/about_financial_means_controller_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4069)
Add partner about_financial_means page
- add page
- update flow
- add specs and cucumber feature tests
=> AP-4069: Create partner's financial assessment intro page

app/controllers/providers/partners/about_financial_means_controller.rb, app/services/flow/flows/provider_capital.rb, app/views/providers/about_financial_means/show.html.erb, app/views/providers/partners/about_financial_means/show.html.erb, config/locales/en/providers.yml, config/routes.rb, features/providers/partner_means_assessment/means_check.feature, features/step_definitions/partner_means_check.rb, spec/requests/providers/partners/about_financial_means_controller_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4069)
Add partner about_financial_means page
- add page
- update flow
- add specs and cucumber feature tests
=> Ap 4069/create partner financial assessment intro v2

app/controllers/providers/partners/employed_controller.rb, app/forms/applicants/employed_form.rb, app/forms/base_employed_form.rb, app/forms/partners/employed_form.rb, app/services/flow/flows/provider_capital.rb, app/services/flow/flows/provider_partner.rb, app/views/providers/applicant_employed/index.html.erb, app/views/providers/partners/employed/index.html.erb, app/views/shared/_employment_status.html.erb, config/locales/en/activemodel.yml, config/locales/en/generic.yml, config/locales/en/shared.yml, config/routes.rb, db/migrate/20230614094521_add_employment_to_partners.rb, db/schema.rb, features/providers/partner_means_assessment/means_check.feature, features/step_definitions/partner_means_check.rb, spec/forms/partners/employed_form_spec.rb, spec/requests/providers/partners/about_financial_means_controller_spec.rb, spec/requests/providers/partners/employed_controller_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4067)
- add partner employment page
- add employed, self-employed and armed forces to `partners` table
- create base_employed_form to avoid duplication
- create partials to be reused on both partner and applicant employed views
- add and update specs to reflect changes
- content changes …
=> Ap 4067: Create partner employment status question page 

app/lib/omni_auth/hmrc.rb
Request specific scopes from the Doorkeeper authentication in HMRC Interface
Update the bearer token request with specific scopes requested and point at existing HMRC Interfaces
=> Doorkeeper test: Update scope request

helm_deploy/apply-for-legal-aid/templates/cronjob-admin-report.yaml, helm_deploy/apply-for-legal-aid/templates/cronjob-db-backup-cleanup.yaml, helm_deploy/apply-for-legal-aid/templates/cronjob-deliver-scheduled-mail.yaml, helm_deploy/apply-for-legal-aid/templates/cronjob-destroy-purgeable.yaml, helm_deploy/apply-for-legal-aid/templates/cronjob-export-digest.yaml, helm_deploy/apply-for-legal-aid/templates/cronjob-extract-digest.yaml, helm_deploy/apply-for-legal-aid/templates/cronjob-hourly-db-backup.yaml, helm_deploy/apply-for-legal-aid/templates/cronjob-mark-purgeable.yaml, helm_deploy/apply-for-legal-aid/templates/cronjob-metrics.yaml, helm_deploy/apply-for-legal-aid/templates/cronjob-reset-dashboard-overnight.yaml, helm_deploy/apply-for-legal-aid/templates/deployment_metrics.yaml
Reverts ministryofjustice/laa-apply-for-legal-aid#5416
This is working, but the prometheus integration broke.  Reverting until we understand why
=> Revert "Fix: Reduce 502 errors on pods"

app/helpers/application_helper.rb
[Use back link components](https://dsdmoj.atlassian.net/browse/AP-3639)
Use govuk_back_link component throughout the application. 
=> Use govuk_back_link component

app/models/proceeding.rb, app/services/flow/proceeding_loop.rb, app/services/query/incomplete_proceedings.rb, features/cassettes/Scope_limitations_not_being_set/When_a_provider_creates_an_application_with_multiple_proceedings_and_uses_the_back_button_scope_limitations_should_not_be_removed.yml, features/providers/regressions/scope_limitations.feature, spec/requests/providers/has_other_proceedings_controller_spec.rb, spec/services/flow/proceeding_loop_spec.rb, spec/services/query/incomplete_proceedings_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4222)
An error was seen in production where a submission to CCMS failed. Investigation showed that a proceeding was incomplete. We were able to recreate the steps via logs and found the back button had invalidated the 'incomplete' proceeding check
This PR adds a regression test (that could be deleted after a while?) to recreate those steps and then implements a Query Object that builds the complex query to scan proceedings and linked tables to get incomplete proceedings
It also updates tests to use the new object and removes the, now, simplistic `incomplete` scope
- Github should not be reporting conflicts; you should have recently run …
=> AP-4222: Fix scope limitation/next proceeding handling

app/views/providers/partners/client_has_partners/show.html.erb, config/locales/en/providers.yml
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4214)
- Update partner description
- Remove unused code
=> AP-4214: Update partner description

package.json, yarn.lock
Clean node peer dependencies to:
- Reduce peer dependency management
- Remove redundant peer packages
- Remove & Reduce security vulnerabilities in packages
- Reduce dependency size on HDD by over 50 MB
=> [chore] clean node dependencies

app/views/providers/means/other_assets/_second_home_conditional_checkbox.html.erb, config/locales/en/providers.yml, spec/requests/providers/means/other_assets_controller_spec.rb
These were moved from the top level of provider into a partner folder
All keys were duplicated but the originals were not removed and, in a couple of cases, the duplicates were still referenced in tests
=> Fix: Remove duplicated locale blocks

config/locales/en/providers.yml, features/providers/check_multiple_employment.feature, features/providers/check_nonpassport_autogrant.feature, features/providers/check_pending_employment.feature, features/providers/check_single_employment.feature, features/providers/complete_and_check_means_answers.feature, features/providers/employed_journey.feature, features/providers/non_passported_journey/with_bank_transactions.feature, features/providers/non_passported_journey/with_capital.feature, features/providers/non_passported_journey/with_dependants.feature, features/providers/non_passported_journey/with_means.feature, features/providers/partner_means_assessment/means_check.feature, spec/requests/providers/means/identify_types_of_incomes_controller_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4103)
Update headings, labels and hint texts
=> AP-4103: Update types of income page text

app/controllers/providers/client_completed_means_controller.rb, config/locales/en/providers.yml, spec/requests/providers/client_completed_means_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4084)
This updates the text on the client completed means page in line with tested values
It also allows a provider whose client has a partner to see only the initial 1 or 2 points, whereas a client without a partner will have the full list of steps …
=> AP-4084: Update client financial assessment page

config/locales/en/shared.yml
Tweak upload bank statement help content
Noticed by content designer
=> Tweak upload bank statement help content

app/controllers/providers/application_merits_task/opponent_type_controller.rb, app/controllers/providers/application_merits_task/opponent_types_controller.rb, app/services/flow/flows/provider_merits.rb, app/views/providers/application_merits_task/opponent_types/show.html.erb, config/locales/en/providers.yml, config/routes.rb, features/providers/merits_task_list.feature, spec/requests/providers/application_merits_task/has_other_opponents_controller_spec.rb, spec/requests/providers/application_merits_task/opponent_types_controller_spec.rb
[Add “Is the opponent an individual or an organisation?” page to Apply](https://dsdmoj.atlassian.net/browse/AP-4302)
=> AP-4302: Add page for opponent type question

.rubocop_todo.yml, Rakefile, app/services/true_layer/api_client.rb, app/services/true_layer/bank_data_import_service.rb, spec/services/ccms/requestors/case_add_requestor_xml_blocks/non_passported_dependant_child_attributes_spec.rb, spec/services/true_layer/api_client_spec.rb, spec/services/true_layer/importers/import_transactions_service_spec.rb
Addresses some of the rubocop todos
=> Rubocop tidy

lib/tasks/db.rake, scripts/db_export.sh, scripts/restore_anonymised_db.sh
Make a few updates to the methods of restoring anonymised databases to environments
* Prevent production restoration
* allow staging restoration
* zip the upload file before uploading to speed up the step
* re-seed the staging environment so that providers exist that can be access via the staging portal
* reduce the message output when deleting the existing version …
=> Update: Update DB restoration

.rubocop_todo.yml, spec/models/aggregated_cash_income_spec.rb, spec/models/aggregated_cash_outgoings_spec.rb, spec/models/cash_transaction_spec.rb, spec/requests/admin_users/sessions_controller_spec.rb, spec/requests/providers/uploaded_evidence_collection_spec.rb, spec/services/benefit_check_service_spec.rb, spec/services/ccms/requestors/case_add_requestor_spec.rb, spec/services/ccms/submitters/check_case_status_service_spec.rb, spec/services/reports/reports_types_creator_spec.rb
Address some more infractions in the rubocop todo file
* remove `RSpec/InstanceVariable` blocks
* remove all infractions from `benefit_check_service_spec` and `check_case_status_service_spec`
=> Friday: Rubocop todo

app/services/flow/flows/provider_income.rb, spec/requests/providers/means/cash_outgoings_controller_spec.rb, spec/requests/providers/means/regular_outgoings_controller_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4392)
Update flow:
- fix flow to match requirements
- add specs for these scenarios
=> AP-4392: Fix routing issue on client regular_outgoings and cash_outgoings pages

.rubocop_todo.yml, spec/forms/applicants/email_form_spec.rb, spec/forms/applicants/employed_form_spec.rb, spec/forms/concerns/date_field_builder_spec.rb, spec/forms/incidents/told_on_form_spec.rb, spec/forms/legal_aid_applications/dependant_form_spec.rb, spec/forms/legal_aid_applications/has_evidence_of_benefit_form_spec.rb, spec/forms/legal_aid_applications/own_home_form_spec.rb, spec/forms/legal_aid_applications/restrictions_form_spec.rb, spec/forms/legal_aid_applications/substantive_application_form_spec.rb, spec/forms/providers/application_merits_task/involved_child_form_spec.rb, spec/forms/providers/proceeding_merits_task/linked_children_form_spec.rb, spec/forms/savings_amounts/offline_accounts_form_spec.rb, spec/forms/savings_amounts/savings_amounts_form_spec.rb, spec/models/applicant_spec.rb, spec/services/flow/base_flow_service_spec.rb, spec/services/manual_review_detailer_spec.rb
* Update applicant model tests, ensure test body matches description
and does not duplicate other test
* Update base flow service to remove duplicated test
* Update manual review detailer tests to remove duplicated test
* update rubocop_todo to remove obsolete block
* Address all forms that did not use named subjects …
=> Rubocop: address todos

.github/dependabot.yml
Now we know how they appear, clarify the group names so that the PR list is clearer
=> Update: Dependabot group names

.rubocop_todo.yml, spec/helpers/hash_format_helper_spec.rb, spec/helpers/providers_helper_spec.rb, spec/helpers/user_transactions_helper_spec.rb, spec/jobs/bank_transactions_analyser_job_spec.rb, spec/jobs/citizen_complete_means_job_spec.rb, spec/jobs/dashboard/applicant_email_job_spec.rb, spec/jobs/dashboard/feedback_item_job_spec.rb, spec/jobs/dashboard/provider_data_job_spec.rb, spec/jobs/post_submission_processing_job_spec.rb, spec/jobs/scheduled_mailings_delivery_job_spec.rb, spec/lib/authorized_ip_ranges_spec.rb, spec/lib/omni_auth/strategies/true_layer_spec.rb, spec/lib/prometheus_collectors/sidekiq_queue_collector_spec.rb, spec/policies/legal_aid_application_policy_spec.rb, spec/presenters/applicant_account_presenter_spec.rb, spec/validators/document_category_validator_spec.rb, spec/workers/bank_holiday_update_worker_spec.rb, spec/workers/ccms/submission_process_worker_spec.rb, spec/workers/hmrc/result_worker_spec.rb, spec/workers/hmrc/submission_worker_spec.rb, spec/workers/true_layer_banks_update_worker_spec.rb
Address more NamedSubject infractions
* update tests in spec/helpers folder
* update tests in spec/jobs folder
* update tests in spec/lib folder
* update tests in spec/policies and spec/presenters folders
* update tests in spec/validators and spec/workers folders …
=> Rubocop: Address more named subject infractions

.circleci/config.yml, .rubocop_todo.yml, spec/models/address_spec.rb, spec/models/applicant_spec.rb, spec/models/application_digest_spec.rb, spec/models/application_merits_task/involved_child_spec.rb, spec/models/cfe/v2/result_spec.rb, spec/models/cfe/v3/result_spec.rb, spec/models/cfe/v4/result_spec.rb, spec/models/dashboard/widget_spec.rb, spec/models/legal_aid_application_spec.rb, spec/models/other_assets_declaration_spec.rb, spec/models/savings_amount_spec.rb, spec/models/scheduled_mailing_spec.rb
This removes all infractions in the app/models folder
It also include a comment indicating when and why the Circle CI chromedriver step was removed
=> Rubocop: Address NamedSubject infractions in model tests

app/controllers/providers/means/cash_outgoings_controller.rb, app/controllers/providers/partners/cash_outgoings_controller.rb, app/controllers/providers/partners/regular_outgoings_controller.rb, app/forms/providers/base_regular_outgoings_form.rb, app/forms/providers/partners/regular_outgoings_form.rb, app/models/applicant.rb, app/models/legal_aid_application.rb, app/models/partner.rb, app/services/flow/flows/provider_income.rb, app/services/flow/flows/provider_partner.rb, app/views/providers/means/cash_outgoings/show.html.erb, app/views/providers/means/regular_outgoings/show.html.erb, app/views/providers/partners/cash_outgoings/show.html.erb, app/views/providers/partners/regular_outgoings/show.html.erb, app/views/shared/means/_cash_outgoing.html.erb, app/views/shared/means/_regular_outgoing.html.erb, config/locales/en/activemodel.yml, config/locales/en/helpers.yml, config/locales/en/providers.yml, config/locales/en/shared.yml, config/routes.rb, features/providers/partner_means_assessment/end_to_end_income_assessment.feature, spec/forms/providers/partners/regular_outgoings_form_spec.rb, spec/requests/providers/means/cash_outgoings_controller_spec.rb, spec/requests/providers/partners/cash_outgoings_controller_spec.rb, spec/requests/providers/partners/regular_outgoings_controller_spec.rb, spec/requests/providers/partners/student_finances_controller_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4106)
- update flow
- add pages in routes
- create partial, add view and update client view to use partial
- update translation files to reflect changes
- create base form, add partner form and update client form to use base, add spec
- create partner controller and add controller spec
To do: …
=> AP-4106: Partner outgoings and cash outgoings pages

app/views/providers/means/dependants/_form.html.erb, app/views/providers/means/dependants/show.html.erb, app/views/providers/means/has_dependants/show.html.erb, app/views/providers/means/has_other_dependants/show.html.erb, config/locales/en/providers.yml, features/providers/partner_means_assessment/end_to_end_income_assessment.feature, spec/requests/providers/means/dependants_controller_spec.rb, spec/requests/providers/means/has_dependants_controller_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4126)
- update has_dependants page for client with partner
=> AP-4126: Update dependants pages

app/controllers/providers/means/housing_benefits_controller.rb, app/services/flow/flows/provider_income.rb, app/services/flow/flows/provider_partner.rb, app/views/providers/means/housing_benefits/show.html.erb, config/locales/en/generic.yml, config/locales/en/helpers.yml, config/locales/en/providers.yml, config/locales/en/shared.yml, features/providers/bank_statement_upload/check_your_means_answers.feature, features/providers/bank_statement_upload/happy_path_journey.feature, features/providers/partner_means_assessment/end_to_end_income_assessment.feature, spec/requests/providers/means/cash_outgoings_controller_spec.rb, spec/requests/providers/means/housing_benefits_controller_spec.rb, spec/requests/providers/means/regular_outgoings_controller_spec.rb, spec/requests/providers/outgoings_summary_controller_spec.rb, spec/requests/providers/partners/cash_outgoings_controller_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4107)
- Update Housing Benefit page to include content for partner
- Move HB page to the end of the means assessment
- Update flows to show HB depending on client and partners outgoing categories
- Update rspecs and feature tests
- You …
=> AP-4107 partner housing benefit

app/views/shared/_student_finances.html.erb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4445)
Ensure the `Yes` response has linked_errors set to true, this means that both the client and partner pages now have the correct links from the error block at the top of the page …
=> AP-4445: Update student financial partial

.rubocop_todo.yml, spec/requests/admin/feedback_controller_spec.rb, spec/requests/admin/legal_aid_applications/submissions_controller_spec.rb, spec/requests/admin/legal_aid_applications_controller_spec.rb, spec/requests/admin/reports_controller_spec.rb, spec/requests/admin/roles/permissions_controller_spec.rb, spec/requests/admin/roles_controller_spec.rb, spec/requests/admin/settings_controller_spec.rb, spec/requests/admin/submitted_applications_reports_controller_spec.rb, spec/requests/admin_users/omniauth_callbacks_spec.rb, spec/requests/applicants/omniauth_callbacks_spec.rb, spec/requests/auth_spec.rb, spec/requests/citizens/accounts_spec.rb, spec/requests/citizens/check_answers_spec.rb, spec/requests/citizens/gather_transactions_spec.rb, spec/requests/errors_controller_spec.rb, spec/requests/feedbacks_spec.rb, spec/requests/problem_controller_spec.rb
* Address all request/admin infractions
* Address all top level request or single folder infractions
* Address all request/citizen infractions 
=> Rubocop: More RSpec/NamedSubject improvements

config/locales/en/activemodel.yml
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4446)
Add explicit error messages for the dependant page.  
These were inherited from the individual pages but now they are shared and end up being duplicated …
=> AP-4446: Clarify dependant errors

app/views/providers/capital_introductions/show.html.erb, app/views/providers/means/own_homes/show.html.erb, config/locales/en/activemodel.yml, config/locales/en/generic.yml, config/locales/en/providers.yml, features/providers/partner_means_assessment/end_to_end_income_assessment.feature, spec/requests/providers/means/own_home_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3810)
Change heading content based on whether application has a partner with no contrary interest
Update rspecs and features
NOTE: Change base back to main before merging!!! …
=> AP-3810 partner own home

app/views/providers/means/vehicles/show.html.erb, config/locales/en/providers.yml, features/providers/partner_means_assessment/end_to_end_income_assessment.feature, features/step_definitions/civil_journey_steps.rb, spec/requests/providers/means/vehicles_controller_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4137)
Update the vehicles question to include partner
=> AP-4137 partner vehicles question

config/locales/en/providers.yml
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3813)
Providers were unsure of the source of the data, this clarifies that is has been provided by the client
using truelayer
=> AP-3813: Update bank account guidance

.rubocop_todo.yml, spec/requests/providers/means/dependants_controller_spec.rb, spec/requests/providers/means/other_assets_controller_spec.rb, spec/requests/providers/means/policy_disregards_controller_spec.rb, spec/requests/providers/means/remove_dependants_controller_spec.rb, spec/requests/providers/means/restrictions_spec.rb, spec/requests/providers/means/savings_and_investments_spec.rb, spec/requests/providers/means/vehicles_controller_spec.rb, spec/requests/providers/merits_task_lists_controller_spec.rb, spec/requests/providers/offline_accounts_spec.rb, spec/requests/providers/outgoings_summary_controller_spec.rb, spec/requests/providers/proceeding_merits_task/attempts_to_settle_controller_spec.rb, spec/requests/providers/proceeding_merits_task/chances_of_success_spec.rb, spec/requests/providers/proceeding_merits_task/linked_children_spec.rb, spec/requests/providers/proceeding_merits_task/success_prospects_spec.rb, spec/requests/providers/proceedings_types_controller_spec.rb, spec/requests/providers/providers_controller_spec.rb, spec/requests/providers/received_benefit_confirmations_controller_spec.rb
Address the exclusions in the folders in `spec/requests/providers/` starting `m` to `r`
=> Rubocop: Address the next batch of NamedSubject exclusions

app/views/providers/means/property_details/show.html.erb, config/locales/en/activemodel.yml, config/locales/en/providers.yml, config/locales/en/shared.yml, features/providers/back_button.feature, features/providers/check_your_answers.feature, features/providers/means_report.feature, features/providers/non_passported_journey/with_capital.feature, features/providers/partner_means_assessment/end_to_end_income_assessment.feature, features/providers/passported_journey.feature, spec/requests/providers/means/property_details_controller_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4133)
Update property_details page to show partner content
Update rspec and feature test
=> AP-4133 partner property details

config/locales/en/activemodel.yml, spec/forms/vehicles/details_form_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4478)
Error messages on the vehicle details page have been updated to those listed in the ticket
=> AP-4478: update error messages on vehicle details

.github/dependabot.yml
Update dependabot to merge axe gem updates
=> Axe core updates

app/controllers/admin/settings_controller.rb, app/forms/settings/setting_form.rb, app/models/setting.rb, app/views/admin/settings/show.html.erb, config/locales/en/admin.yml, db/migrate/20231004080150_add_linked_applications_setting_feature_flag.rb, db/schema.rb, spec/models/setting_spec.rb, spec/requests/admin/settings_controller_spec.rb
=> AP-4506: Add linked_applications feature flag

.rubocop_todo.yml, app/controllers/providers/partners/bank_accounts_controller.rb, app/forms/partners/offline_accounts_form.rb, app/forms/savings_amounts/offline_accounts_form.rb, app/models/concerns/capital.rb, app/models/partner.rb, app/services/flow/flows/provider_capital.rb, app/views/providers/partners/bank_accounts/show.html.erb, app/views/shared/check_answers/_assets.html.erb, config/locales/en/activemodel.yml, config/locales/en/providers.yml, config/locales/en/shared.yml, config/routes.rb, db/migrate/20230929072452_add_partner_fields_to_savings_amount.rb, db/schema.rb, features/providers/passported_journey.feature, spec/factories/savings_amounts.rb, spec/forms/partners/offline_accounts_form_spec.rb, spec/forms/savings_amounts/offline_accounts_form_spec.rb, spec/requests/providers/applicant_bank_accounts_controller_spec.rb, spec/requests/providers/check_capital_answers_controller_spec.rb, spec/requests/providers/partners/bank_accounts_controller_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4141)
Update partner bank account handling, add additional fields to the savings amount table 
Add the new view and routing needed for a partner claim to proceed …
=> AP-4141: Partner offline bank account page

.rubocop_todo.yml, spec/factory_specs/v4/cfe_result_factory_spec.rb, spec/helpers/providers_helper_spec.rb, spec/models/cfe/v4/result_spec.rb, spec/requests/citizens/additional_accounts_spec.rb, spec/requests/citizens/gather_transactions_spec.rb, spec/requests/providers/check_merits_answers_spec.rb, spec/requests/providers/means/savings_and_investments_spec.rb, spec/requests/providers/offline_accounts_spec.rb, spec/services/ccms/parsers/applicant_add_status_response_parser_spec.rb, spec/services/ccms/requestors/case_add_requestor_xml_blocks/non_passported_attributes_spec.rb, spec/services/ccms/requestors/case_add_requestor_xml_blocks/passported_attributes_spec.rb
Remove the duplicated steps and, sometimes, clarify
the remaining test definitions
=> Rubocop: address RSpec/RepeatedExample* exclusions

.rubocop_todo.yml, spec/services/reports/means_report_creator_spec.rb
=> Fix rubocop Rspec/ExpectActual violations

app/models/legal_aid_application.rb, app/models/linked_application.rb, config/locales/en/activemodel.yml, config/locales/en/activerecord.yml, db/anonymise/rules.rb, db/migrate/20231009145448_create_linked_applications.rb, db/schema.rb, spec/factories/linked_applications.rb, spec/models/legal_aid_application_spec.rb, spec/models/linked_application_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4381)
Added migration to add linked_applications table.
Added LinkedApplication model.
Added specs and LinkedApplications factory
TODO:
implement validations on LinkedApplications, however, this is to be done as part of ap-4510. …
=> ap-4509: add linked_applications table, model and associations

config/locales/en/providers.yml
Design has asked that this be updated
=> Fix: Partner definition update

app/controllers/providers/partners/contrary_interests_controller.rb, app/models/partner.rb, app/services/flow/flows/provider_partner.rb, app/views/providers/check_provider_answers/_shared.html.erb, app/views/shared/check_answers/_partner_details.html.erb, config/locales/en/shared.yml, spec/requests/providers/partners/contrary_interests_controller_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4328)
* Add the contrary interest section to the first CYA page
* Remove the partner when the provider changes the answer to 'Yes' for the contrary interest question  …
=> AP-4328 Add contrary interest question to check your answers

app/models/linked_application_type.rb, spec/models/linked_application_type_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4508)
=> ap-4508: Add class to handle linked_application_types

app/services/ccms/attribute_value_generator.rb, config/ccms/attribute_block_configs/base.yml, spec/services/ccms/requestors/case_add_requestor_xml_blocks/passported_attributes_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3887)
This implements the CCMS values suggested by the PUI xml output when a partner is added
=> AP-3887: Add Partner CCMS values

bin/delete_dependabot_deployment
Ensure pvcs are removed with clean up
renamed branch to try and trick circle into deleting it :) 
=> Fix: Update delete deployment script

README.md, docs/pull_request_template.md
- Update pull request template to link to git workflow doc
- Minor typos fixed in README
=> Docs: update pull request template

app/models/legal_aid_application.rb, app/services/ccms/manual_review_determiner.rb, config/locales/en/providers.yml, features/providers/means_report.feature, spec/services/ccms/manual_review_determiner_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4628)
This updates the manual review determiner to add specific client/partner errors for bank statement uploads
=> AP-4628: Partner manual review determiner

features/cassettes/Using_the_back_button_on_proceedings_should_not_lock_a_user_out/When_a_provider_is_adding_proceedings_and_uses_the_back_button_they_should_route_to_the_list_of_proceedings_first.yml, features/support/vcr.rb
Add VCR hook_into :faraday
[Came out of story](https://dsdmoj.atlassian.net/browse/AP-4617)
To ensure calls from the faraday http client are being intercepted in 
feature tests.
[hook_into](https://www.rubydoc.info/gems/vcr/VCR%2FConfiguration:hook_into)
[hook_into gitbook](https://andrewmcodes.gitbook.io/vcr/configuration/hook_into)
The current `hook_into :webmock` means faraday is not explicitly intercepted. Though quite 
how we are stubbing most faraday clients calls already is therefore unclear but possibly
because the default adapter is net_http, which is covered by the :webmock hook.
The following http client libraries are used and therefore we need VCR
to intercept them.
| API              | Library |
| Address lookup   | faraday |
| Bank holidays    | Net::HTTP |
| LFA …
=> [AP-4617] Ensure backend external api calls stubbed in features

app/controllers/providers/partners/cash_incomes_controller.rb, app/controllers/providers/partners/cash_outgoings_controller.rb, app/views/providers/means/cash_incomes/show.html.erb, app/views/providers/means/cash_outgoings/show.html.erb, app/views/providers/partners/cash_incomes/show.html.erb, app/views/providers/partners/cash_outgoings/show.html.erb, app/views/shared/means/_cash_income.html.erb, app/views/shared/means/_cash_outgoing.html.erb, db/migrate/20231205092447_add_no_cash_income_to_partners.rb, db/migrate/20231205180352_add_no_cash_outgoings_to_partners.rb, db/schema.rb, spec/requests/providers/partners/cash_incomes_controller_spec.rb, spec/requests/providers/partners/cash_outgoings_controller_spec.rb
[AP-4630: partner/cash_income and outgoings - remembers positive answers provided for client](https://dsdmoj.atlassian.net/browse/AP-4630) …
=> Ap 4630 partner/cash income

app/models/address.rb, app/services/ccms/requestors/applicant_add_requestor.rb, app/services/ccms/requestors/case_add_requestor.rb, spec/data/ccms/case_add_request.xml, spec/data/ccms/df_case_add_request.xml, spec/data/ccms/non_default_client_involvement_type.xml, spec/models/address_spec.rb, spec/services/ccms/requestors/applicant_add_requestor_spec.rb, spec/services/ccms/requestors/case_add_requestor_spec.rb, spec/services/ccms/submitters/add_applicant_service_spec.rb, spec/services/ccms/submitters/add_case_service_spec.rb
Add correspondence address to ccms payload
So we can avoid use of old addressess in CCMS. …
=> Incident: Add correspondence address to CCMS payload

app/controllers/providers/means/dependants_controller.rb, app/forms/legal_aid_applications/dependant_form.rb, spec/requests/providers/means/dependants_controller_spec.rb
=> ap-4460: dependants details fix for Save and come back later

app/forms/proceedings/client_involvement_type_form.rb, spec/cassettes/ClientInvolvementTypeController/POST_/providers/applications/_legal_aid_application_id/client_involvement_type/_proceeding_id/when_the_provider_is_authenticated/when_form_submitted_with_Save_as_draft_button/redirects_to_the_list_of_applications.yml, spec/requests/providers/proceeding_loop/client_involvement_type_controller_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4159) …
=> ap-4159: Client Involvement Type Fix for save and come back later

.rubocop_todo.yml, spec/jobs/bank_transactions_analyser_job_spec.rb, spec/requests/admin/settings_controller_spec.rb, spec/requests/applicants/omniauth_callbacks_spec.rb, spec/requests/providers/application_merits_task/statement_of_case_spec.rb, spec/requests/providers/means/other_assets_controller_spec.rb, spec/requests/v1/statement_of_cases_spec.rb, spec/requests/v1/uploaded_evidence_collections_spec.rb, spec/services/reports/mis/application_details_report_spec.rb
=> Fix some rspec any-instance rubocop warnings

app/views/providers/open_banking_guidances/show.html.erb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4434)
Change heading level from h3 to h2 so no heading levels are skipped
- You …
=> AP-4434: Change h3 to h2

.rubocop_todo.yml, spec/factories/legal_aid_applications.rb, spec/jobs/dashboard/applicant_email_job_spec.rb, spec/jobs/dashboard/feedback_item_job_spec.rb, spec/jobs/dashboard/provider_data_job_spec.rb, spec/mailers/feedback_mailer_spec.rb, spec/models/applicant_spec.rb, spec/models/application_digest_spec.rb, spec/requests/providers/client_completed_means_controller_spec.rb
=> Some rubocop fixes

app/helpers/means_report_helper.rb, app/models/cfe/v6/result.rb, app/views/providers/means_reports/_with_cfe_result_details.html.erb, app/views/shared/check_answers/_assets.html.erb, app/views/shared/check_answers/_benefits_breakdown.html.erb, app/views/shared/check_answers/_employed_income.html.erb, app/views/shared/check_answers/_income_result.html.erb, app/views/shared/check_answers/_property.html.erb, app/views/shared/means_report/_item.html.erb, app/views/shared/review_application/_income_payments_and_assets_for_bank_statement_upload.html.erb, config/locales/en/providers.yml, config/locales/en/shared.yml, features/providers/bank_statement_upload/check_your_means_answers.feature, features/providers/check_your_answers.feature, features/providers/means_report.feature, features/providers/partner_means_assessment/bank_statement_upload/check_your_means_answers.feature, features/providers/partner_means_assessment/means_report.feature, features/step_definitions/means_report_steps.rb, spec/factories/legal_aid_applications.rb, spec/requests/providers/means_reports_controller_spec.rb, spec/services/reports/means_report_creator_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4610)
Update the means report to ensure that the data is presented in the best way for caseworkers, splitting headings to client/partner and with the requested grouping …
=> AP-4610: Update partner means report

config/initializers/mock_saml.rb, db/seeds/test_provider_populator.rb
=> Chore: Remove JSugarman provider details from seeds and saml

config/locales/en/providers.yml, features/providers/applicant_details.feature, features/providers/applicant_under_16_blocked.feature, features/providers/check_provider_answers.feature, features/providers/cost_override.feature, features/providers/link_case.feature, features/providers/no_nino_flow.feature, features/providers/non_means_tested_journey/under_18_application_journey.feature, features/providers/non_means_tested_journey/with_delegated_functions.feature, features/providers/non_means_tested_journey/without_delegated_functions.feature, spec/requests/providers/has_national_insurance_numbers_controller_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4626) …
=> ap-4626: update nino question content

app/models/cfe/v6/result.rb, app/services/flow/flows/provider_income.rb, config/locales/en/shared.yml, spec/requests/providers/means/identify_types_of_outgoings_controller_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4327)
Improve the means report handling of partner disregarded_state_benefits
Improve the flow around outgoings for partners …
=> AP-4327: Partner means fixes

.rubocop_todo.yml, spec/requests/providers/uploaded_evidence_collection_spec.rb, spec/services/ccms/submitters/upload_documents_service_spec.rb, spec/services/reports/merits_report_creator_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4732) …
=> ap-4732: some rubocop fixes

app/controllers/citizens/banks_controller.rb, app/views/citizens/banks/index.html.erb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4465)
Put banks in alphabetical order, regardless of case. Mock bank stays at the top as it is only used for testing …
=> AP-4465: Order banks alphabetically on view

helm_deploy/apply-for-legal-aid/templates/deployment_web.yaml
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3151)
Update clamav to latest version …
=> AP-3151: Update clamav to latest version

.github/dependabot.yml
Add a new group to merge the css and js bundlingrails gems …
=> Chore: add *bundling-rails dependabot group

docker/apply_base.dockerfile
Update alpine to v19 to be on the same version as in each of our other services …
=> Chore: update alpine to v19

app/views/providers/start/index.html.erb, config/locales/cy/generic.yml, config/locales/en/generic.yml, config/locales/en/providers.yml, features/providers/applicant_under_16_blocked.feature, features/providers/cookies.feature, features/providers/non_means_tested_journey/under_18_application_journey.feature, features/providers/non_means_tested_journey/with_delegated_functions.feature, features/providers/non_means_tested_journey/without_delegated_functions.feature, features/providers/search_applications.feature, features/providers/search_proceedings.feature, features/step_definitions/civil_journey_steps.rb, features/step_definitions/cookie_steps.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4695)
Update start page content
Screenshot: …
=> AP-4695: Update start page content

app/views/providers/means_reports/show.html.erb, app/views/providers/merits_reports/show.html.erb, app/views/shared/review_application/_questions_and_answers.html.erb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4796)
Add to means report, merits report and review and print page
**NB. This raised against AP-4796 for now. Will be updated to be raised against `main` once that ticket is merged**
- You …
=> AP-4796: Add surname at birth details to reports

app/forms/base_address_form.rb, app/views/providers/addresses/show.html.erb, config/locales/en/activemodel.yml, config/locales/en/providers.yml, config/routes.rb, spec/forms/addresses/address_form_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4789)
Update labels on each field
Update validation to match those specified in the design
Add and update relevant error messages …
=> AP-4789: Update client correspondence address

app/controllers/admin/settings_controller.rb, app/forms/settings/setting_form.rb, app/models/setting.rb, app/views/admin/settings/show.html.erb, config/locales/en/admin.yml, db/migrate/20240214160228_add_home_address_to_settings.rb, db/schema.rb, spec/models/setting_spec.rb, spec/requests/admin/settings_controller_spec.rb
[AP-4788: Add home address feature flag](https://dsdmoj.atlassian.net/browse/AP-4788) …
=> AP-4788: Add home address feature flag

package.json, yarn.lock
Resolve warning of unmet peer dependency.
=> chore: yarn add @babel/core

Gemfile
=> Chore remove gem wdm

app/controllers/providers/address_lookups_controller.rb, app/forms/addresses/address_lookup_form.rb, app/views/providers/address_lookups/show.html.erb, config/locales/en/helpers.yml, config/locales/en/providers.yml, config/routes.rb, db/anonymise/rules.rb, db/migrate/20240215131834_add_building_number_name_to_addresses.rb, db/migrate/20240216110009_add_type_to_address.rb, db/schema.rb, features/providers/check_provider_answers.feature, features/providers/no_nino_flow.feature, features/step_definitions/civil_journey_steps.rb, spec/requests/providers/address_lookups_controller_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4798)
Update the find correspondence address page
* Add the new house number/name field
* Add a location field to allow recording current applications as correspondence and allow extending to home addresses in the near future …
=> AP-4798: Add field for improved postcode search

app/helpers/application_helper.rb, app/views/privacy_policy/index.html.erb, app/views/providers/capital_introductions/show.html.erb, app/views/providers/client_completed_means/show.html.erb, app/views/providers/confirm_client_declarations/show.html.erb, app/views/providers/means/restrictions/show.html.erb, app/views/providers/open_banking_guidances/show.html.erb, app/views/shared/_transactions_summary.html.erb, config/locales/cy/privacy_policy.yml, config/locales/en/privacy_policy.yml, config/locales/en/providers.yml, config/locales/en/shared.yml
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4777) …
=> AP-4777: refactor list from translation path

app/views/shared/_employment_status.html.erb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4179) …
=> ap-4179: Fix missing part of error message on employment status page

app/views/shared/_address_lookup.html.erb, config/locales/en/shared.yml
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4898)
This was duplicated from the correspondence page but this version makes more sense for providers inputting a home address …
=> AP-4898: Update home address warning text

app/assets/stylesheets/application.scss
[Enable GOVUK responsive type scale](https://github.com/alphagov/govuk-frontend/blob/main/CHANGELOG.md#weve-adjusted-our-responsive-type-scale) …
=> Chore enable responsive type scale

app/controllers/providers/link_application/confirm_links_controller.rb, app/forms/providers/link_application/confirm_link_form.rb, app/helpers/linked_applications_helper.rb, app/models/linked_application.rb, app/services/flow/flows/provider_start.rb, app/services/flow/steps/linked_applications/confirm_link_step.rb, app/services/flow/steps/step.rb, app/views/providers/link_application/confirm_links/show.html.erb, config/locales/en/activemodel.yml, config/locales/en/providers.yml, config/routes.rb, spec/forms/providers/link_application/confirm_link_form_spec.rb, spec/helpers/linked_applications_helper_spec.rb, spec/models/linked_application_spec.rb, spec/requests/providers/link_application/confirm_links_controller_spec.rb, spec/requests/providers/link_application/find_link_applications_controller_spec.rb, spec/services/flow/steps/linked_applications/confirm_link_step_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4827) …
=> ap-4827: add link applications confirm link page

app/forms/proceedings/emergency_defaults_form.rb, app/forms/proceedings/emergency_level_of_service_form.rb, app/forms/proceedings/substantive_level_of_service_form.rb, spec/cassettes/Proceedings_EmergencyLevelOfServiceForm/_save_as_draft/when_the_submission_is_valid/and_the_user_selects_Family_Help_Higher_/updates_the_emergency_level_of_service_value.yml, spec/cassettes/Proceedings_EmergencyLevelOfServiceForm/_save_as_draft/when_the_submission_is_valid/and_the_user_selects_Full_Representation/updates_the_accepted_emergency_defaults_value.yml, spec/cassettes/Proceedings_EmergencyLevelOfServiceForm/_save_as_draft/when_the_user_doesn_t_answer_the_question/is_valid.yml, spec/cassettes/Proceedings_SubstantiveLevelOfServiceForm/_save_as_draft/when_the_submission_is_valid/and_the_user_selects_Family_Help_Higher_/updates_the_substantive_level_of_service_value.yml, spec/cassettes/Proceedings_SubstantiveLevelOfServiceForm/_save_as_draft/when_the_submission_is_valid/and_the_user_selects_Full_Representation/updates_the_accepted_substantive_defaults_value.yml, spec/cassettes/Proceedings_SubstantiveLevelOfServiceForm/_save_as_draft/when_the_user_doesn_t_answer_the_question/is_valid.yml, spec/forms/proceedings/emergency_defaults_form_spec.rb, spec/forms/proceedings/emergency_level_of_service_form_spec.rb, spec/forms/proceedings/substantive_level_of_service_form_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4951)
Steps to recreate issue (on main):-
Navigate to the emergency or substantive  level of service page.
Click save as draft
The fix adds levels_of_service to the list of form attributes not to be passed to model. …
=> ap-4951: attempt to fix unknow-levels-of-service error

app/controllers/providers/link_application/confirm_links_controller.rb, app/services/flow/steps/linked_applications/confirm_link_step.rb, config/locales/en/providers.yml, spec/requests/providers/link_application/confirm_links_controller_spec.rb, spec/services/flow/steps/linked_applications/confirm_link_step_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4830)
Update flow and flash message following confirm linking to match designs. …
=> ap-4830: refactor routing after linking

app/views/providers/start/index.html.erb, config/locales/en/providers.yml
[Update start page re type of linking available](https://dsdmoj.atlassian.net/browse/AP-4914) …
=> AP-4919: Update start page with linking type available

app/services/ccms/requestors/case_add_requestor.rb, spec/data/ccms/case_add_request.xml, spec/data/ccms/case_add_request_with_surname_at_birth.xml, spec/data/ccms/df_case_add_request.xml, spec/data/ccms/non_default_client_involvement_type.xml, spec/services/ccms/requestors/case_add_requestor_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4941)
Add linked applications to CCMS payload. …
=> ap-4941: add linked applications to ccms payload

app/controllers/providers/check_provider_answers_controller.rb, app/forms/providers/link_application/copy_form.rb, app/forms/providers/link_application/make_link_form.rb, app/models/legal_aid_application.rb, app/services/flow/flows/provider_start.rb, app/services/flow/steps/linked_applications/confirm_link_step.rb, app/services/flow/steps/linked_applications/copy_step.rb, app/services/flow/steps/linked_applications/make_link_step.rb, app/views/providers/check_provider_answers/_shared.html.erb, app/views/providers/check_provider_answers/_standard.html.erb, app/views/shared/check_answers/_proceeding_details.html.erb, config/locales/en/providers.yml, features/cassettes/Checking_answers_for_linked_and_copied_cases/If_I_change_the_copied_from_Yes_to_No.yml, features/cassettes/Checking_answers_for_linked_and_copied_cases/If_I_change_the_linked_from_Family_to_No.yml, features/providers/linked_applications/check_your_answers_link_and_copy.feature, features/providers/linked_applications/check_your_answers_link_only.feature, features/providers/linked_applications/check_your_answers_not_linked.feature, features/step_definitions/linked_cases_steps.rb, spec/forms/providers/link_application/copy_form_spec.rb, spec/forms/providers/link_application/make_link_form_spec.rb, spec/models/legal_aid_application_spec.rb, spec/requests/providers/link_application/make_links_controller_spec.rb, spec/services/flow/steps/linked_applications/confirm_link_step_spec.rb, spec/services/flow/steps/linked_applications/copy_step_spec.rb, spec/services/flow/steps/linked_applications/make_link_step_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4601)
This PR adds the link and copy sections to the `check provider answers` page
It also updates some of the forms on the link and copy pages to properly set or clear values as the information is changed …
=> AP-4601: Update CYA page with link and copy sections

app/services/flow/flows/citizen_start.rb, app/services/flow/steps/citizen_start/accounts_step.rb, app/services/flow/steps/citizen_start/additional_accounts_step.rb, app/services/flow/steps/citizen_start/banks_step.rb, app/services/flow/steps/citizen_start/consents_step.rb, app/services/flow/steps/citizen_start/contact_provider_step.rb, app/services/flow/steps/citizen_start/gather_transactions_step.rb, app/services/flow/steps/citizen_start/legal_aid_applications_step.rb, app/services/flow/steps/citizen_start/true_layer_step.rb, spec/requests/citizens/banks_controller_spec.rb, spec/requests/citizens/consents_controller_spec.rb, spec/services/flow/steps/citizen_start/accounts_step_spec.rb, spec/services/flow/steps/citizen_start/additional_accounts_step_spec.rb, spec/services/flow/steps/citizen_start/banks_step_spec.rb, spec/services/flow/steps/citizen_start/consents_step_spec.rb, spec/services/flow/steps/citizen_start/contact_provider_step_spec.rb, spec/services/flow/steps/citizen_start/gather_transactions_step_spec.rb, spec/services/flow/steps/citizen_start/legal_aid_applications_step_spec.rb, spec/services/flow/steps/citizen_start/true_layer_step_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4666) …
=> Ap 4666 citizen start flow refactor

app/services/flow/flows/citizen_end.rb, app/services/flow/steps/citizen_end/check_answers_step.rb, app/services/flow/steps/citizen_end/means_test_results_step.rb, spec/services/flow/steps/citizen_end/check_answers_step_spec.rb, spec/services/flow/steps/citizen_end/means_test_results_step_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4665) …
=> AP-4665: Flow refactoring - citizen_end flow

app/services/copy_case/cloner_service.rb, spec/services/copy_case/cloner_service_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-5020)
Add `proceeding_linked_children` and `involved_children` to cloner
Add spec coverage …
=> AP-5020: Add proceeding_linked_children and involved_children to cloner

app/controllers/admin/settings_controller.rb, app/forms/settings/setting_form.rb, app/models/setting.rb, app/views/admin/settings/show.html.erb, config/locales/en/admin.yml, db/migrate/20240517110634_add_sca_to_settings.rb, db/schema.rb, spec/models/setting_spec.rb, spec/requests/admin/settings_controller_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-5028)
Add the feature flag for SCA. …
=> AP-5028: Add SCA feature flag

app/helpers/task_list_helper.rb, app/services/copy_case/cloner_service.rb, spec/helpers/task_list_helper_spec.rb, spec/services/copy_case/cloner_service_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-5023)
Added legal_framework_merits_task_list to ClonerService
Resolved TODO (removed guard clause to obtain legal_framework_merits_task_list from copied application if copy_case == true) …
=> ap-5023: add merits task list to cloner service

app/services/flow/flows/provider_start.rb, app/services/flow/steps/provider_start/bank_statements_step.rb, app/services/flow/steps/provider_start/email_addresses_step.rb, app/services/flow/steps/provider_start/open_banking_consents_step.rb, app/services/flow/steps/provider_start/open_banking_guidances_step.rb, spec/requests/providers/bank_statements_spec.rb, spec/requests/providers/email_addresses_spec.rb, spec/requests/providers/open_banking_consents_spec.rb, spec/requests/providers/open_banking_guidances_controller_spec.rb, spec/services/flow/steps/provider_start/bank_statements_step_spec.rb, spec/services/flow/steps/provider_start/email_addresses_step_spec.rb, spec/services/flow/steps/provider_start/open_banking_consents_step_spec.rb, spec/services/flow/steps/provider_start/open_banking_guidances_step_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4682) …
=> AP-4682: Flow refactoring - open banking and bank accounts steps

app/services/flow/flows/provider_start.rb, app/services/flow/steps/provider_start/has_other_proceedings_step.rb, app/services/flow/steps/provider_start/limitations_step.rb, app/services/flow/steps/provider_start/proceedings_types_step.rb, spec/requests/providers/limitations_controller_spec.rb, spec/requests/providers/proceedings_types_controller_spec.rb, spec/services/flow/steps/provider_start/has_other_proceedings_step_spec.rb, spec/services/flow/steps/provider_start/limitations_step_spec.rb, spec/services/flow/steps/provider_start/proceedings_types_step_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4683) …
=> Ap 4683 flow refactor proceedings and limitations

app/javascript/src/modules/proceedings.js, app/services/legal_framework/proceeding_types/all.rb, spec/services/legal_framework/proceeding_types/all_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-5047)
Only show SCA proceedings from LFA if the feature flag is set to `on`
Gracefully handle if they don't exist, yet …
=> AP-5047: Updating ProceedingTypes all service

app/views/providers/application_merits_task/involved_children/_form.html.erb, config/locales/en/providers.yml
[Link to story](https://dsdmoj.atlassian.net/browse/AP-6424)
Update example date to be relative to current year …
=> AP-4624: Update example date to be relative to current year

config/locales/en/admin.yml
Minor updates to feature flag content to make it more descriptive. …
=> Content: make feature flags more descriptive

package.json, yarn.lock
Remove the packages containing `monorepo-symlink-test` as it is flagging as malicious in AWS console …
=> Bug: Remove eslint-plugin-react

docker/apply_base.dockerfile
This should address busybox security warnings
=> Chore: Update Alpine to 3.20

app/services/flow/flows/provider_merits.rb, app/services/flow/steps/provider_merits/attempts_to_settle_step.rb, app/services/flow/steps/provider_merits/chances_of_success_step.rb, app/services/flow/steps/provider_merits/linked_children_step.rb, app/services/flow/steps/provider_merits/prohibited_steps_step.rb, app/services/flow/steps/provider_merits/specific_issue_step.rb, app/services/flow/steps/provider_merits/success_prospects_step.rb, app/services/flow/steps/provider_merits/vary_order_step.rb, spec/requests/providers/proceeding_merits_task/attempts_to_settle_controller_spec.rb, spec/requests/providers/proceeding_merits_task/chances_of_success_spec.rb, spec/requests/providers/proceeding_merits_task/linked_children_spec.rb, spec/requests/providers/proceeding_merits_task/prohibited_steps_controller_spec.rb, spec/requests/providers/proceeding_merits_task/specific_issue_controller_spec.rb, spec/requests/providers/proceeding_merits_task/success_prospects_spec.rb, spec/services/flow/steps/provider_merits/attempts_to_settle_step_spec.rb, spec/services/flow/steps/provider_merits/chances_of_success_step_spec.rb, spec/services/flow/steps/provider_merits/linked_children_step_spec.rb, spec/services/flow/steps/provider_merits/prohibited_steps_step_spec.rb, spec/services/flow/steps/provider_merits/specific_issue_step_spec.rb, spec/services/flow/steps/provider_merits/success_prospects_step_spec.rb, spec/services/flow/steps/provider_merits/vary_order_step_spec.rb
[Flow refactor provider_merits](https://dsdmoj.atlassian.net/browse/AP-4676)
Following the defined pattern to refactor the above flow. …
=> AP-4676: Flow refactoring of provider_merits

app/services/flow/flows/provider_merits.rb, app/services/flow/steps/provider_merits/has_other_involved_children_step.rb, app/services/flow/steps/provider_merits/in_scope_of_laspos_step.rb, app/services/flow/steps/provider_merits/involved_children_step.rb, app/services/flow/steps/provider_merits/matter_opposed_reasons_step.rb, app/services/flow/steps/provider_merits/nature_of_urgencies_step.rb, app/services/flow/steps/provider_merits/start_involved_children_task_step.rb, spec/requests/providers/application_merits_task/has_other_involved_children_spec.rb, spec/requests/providers/application_merits_task/involved_children_spec.rb, spec/requests/providers/application_merits_task/matter_opposed_reasons_controller_spec.rb, spec/services/flow/steps/provider_merits/has_other_involved_children_step_spec.rb, spec/services/flow/steps/provider_merits/in_scope_of_laspos_step_spec.rb, spec/services/flow/steps/provider_merits/involved_children_step_spec.rb, spec/services/flow/steps/provider_merits/matter_opposed_reasons_step_spec.rb, spec/services/flow/steps/provider_merits/nature_of_urgencies_step_spec.rb, spec/services/flow/steps/provider_merits/start_involved_children_task_step_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4675)
Steps:-
start_involved_children_task
involved_children
has_other_involved_children
removed_involved_child
in_scope_of_laspos
matter_oppposed_reasons
nature_of_urgencies …
=> AP-4675: Flow refactoring - provider_merits

app/services/flow/flows/provider_merits.rb, app/services/flow/steps/provider_merits/date_client_told_incidents_step.rb, app/services/flow/steps/provider_merits/domestic_abuse_summaries_step.rb, app/services/flow/steps/provider_merits/has_other_opponents_step.rb, app/services/flow/steps/provider_merits/opponent_existing_organisations_step.rb, app/services/flow/steps/provider_merits/opponent_individuals_step.rb, app/services/flow/steps/provider_merits/opponent_types_step.rb, app/services/flow/steps/provider_merits/opponents_mental_capacities_step.rb, app/services/flow/steps/provider_merits/start_opponent_task_step.rb, app/services/flow/steps/provider_merits/statement_of_cases_step.rb, spec/requests/providers/application_merits_task/date_client_told_incidents_spec.rb, spec/requests/providers/application_merits_task/domestic_abuse_summaries_controller_spec.rb, spec/requests/providers/application_merits_task/has_other_opponents_controller_spec.rb, spec/requests/providers/application_merits_task/opponent_existing_organisations_controller_spec.rb, spec/requests/providers/application_merits_task/opponent_individuals_controller_spec.rb, spec/requests/providers/application_merits_task/opponent_types_controller_spec.rb, spec/requests/providers/application_merits_task/opponents_mental_capacities_controller_spec.rb, spec/requests/providers/application_merits_task/statement_of_case_spec.rb, spec/services/flow/steps/provider_merits/date_client_told_incidents_step_spec.rb, spec/services/flow/steps/provider_merits/domestic_abuse_summaries_step_spec.rb, spec/services/flow/steps/provider_merits/has_other_opponents_step_spec.rb, spec/services/flow/steps/provider_merits/opponent_existing_organisations_step_spec.rb, spec/services/flow/steps/provider_merits/opponent_individuals_step_spec.rb, spec/services/flow/steps/provider_merits/opponent_types_step_spec.rb, spec/services/flow/steps/provider_merits/opponents_mental_capacities_step_spec.rb, spec/services/flow/steps/provider_merits/start_opponent_task_step_spec.rb, spec/services/flow/steps/provider_merits/statement_of_cases_step_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4674)
Flow refactor on the following flow steps:
- date_client_told_incidents
- opponent_types
- opponent_individuals
- opponent_existing_organisations
- opponent_new_organisations
- start_opponent_task
- opponent_types
- has_other_opponents
- remove_opponent
- opponents_mental_capacities
- domestic_abuse_summaries
- statement_of_cases …
=> AP-4674: Flow refactoring - provider_merits

app/controllers/providers/correspondence_address/care_ofs_controller.rb, app/forms/addresses/care_of_form.rb, app/models/address.rb, app/services/flow/flows/provider_start.rb, app/services/flow/steps/addresses/correspondence_address_care_ofs_step.rb, app/services/flow/steps/addresses/correspondence_address_manuals_step.rb, app/services/flow/steps/addresses/correspondence_address_selections_step.rb, app/views/providers/correspondence_address/care_ofs/show.html.erb, app/views/shared/check_answers/_client_details.html.erb, config/locales/en/activemodel.yml, config/locales/en/providers.yml, config/locales/en/shared.yml, config/routes.rb, db/migrate/20240603140432_add_care_of_to_address.rb, db/schema.rb, features/providers/linked_applications/back_button.feature, spec/forms/addresses/care_of_form_spec.rb, spec/models/address_spec.rb, spec/requests/providers/correspondence_address/care_ofs_controller_spec.rb, spec/services/flow/steps/addresses/correspondence_address_care_ofs_step_spec.rb, spec/services/flow/steps/addresses/correspondence_address_manuals_step_spec.rb, spec/services/flow/steps/addresses/correspondence_address_selections_step_spec.rb
[AP-5040](https://dsdmoj.atlassian.net/browse/AP-5040)
Add 'Do you want to add a ‘care of’ recipient for your client’s mail?' question …
=> Ap 5040 add care of question

app/views/providers/correspondence_address/care_ofs/show.html.erb
This was set to L and should have been XL
=> Chore: Fix CareOf page heading level

config/locales/en/providers.yml
This was noted during a run-through and it is simpler to just remove it than raise a ticket …
=> Chore: fix typo

app/controllers/providers/correspondence_address/manuals_controller.rb, app/forms/addresses/address_form.rb, app/views/shared/_addresses.html.erb, config/locales/en/shared.yml, db/migrate/20240605105731_add_address_line_three_to_address.rb, db/schema.rb, spec/forms/addresses/address_form_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-5039)
This updates the manual correspondence page to add a third (optional) address line and some guidance text …
=> AP-5039: Update manual correspondence page

app/controllers/providers/proceedings_sca/supervision_orders_controller.rb, app/services/flow/flows/provider_start.rb, app/services/flow/steps/proceedings_sca/supervision_order_step.rb, app/views/providers/proceedings_sca/supervision_orders/show.html.erb, config/locales/en/providers.yml, config/routes.rb, spec/requests/providers/proceedings_sca/supervision_orders_controller_spec.rb, spec/services/flow/steps/proceedings_sca/supervision_order_step_spec.rb
=> AP-4532: Add supervision order SCA question

app/controllers/providers/proceedings_sca/interrupts_controller.rb, app/controllers/providers/proceedings_sca/proceeding_issue_statuses_controller.rb, app/services/flow/flows/provider_start.rb, app/services/flow/steps/proceedings_sca/proceeding_issue_statuses_step.rb, app/views/providers/proceedings_sca/proceeding_issue_statuses/show.html.erb, config/locales/en/providers.yml, config/routes.rb, spec/requests/providers/proceedings_sca/proceeding_issue_statuses_controller_spec.rb, spec/services/flow/steps/proceedings_sca/proceeding_issue_statuses_step_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4531)
Add controller, view, flow step, route, locales and specs for proceeding_issue_statuses page
Add interrupt page …
=> AP-4531: Add proceeding_issue_statuses question

app/controllers/providers/proceedings_sca/child_subjects_controller.rb, app/services/flow/flows/provider_start.rb, app/services/flow/steps/proceedings_sca/child_subjects_step.rb, app/views/providers/proceedings_sca/child_subjects/show.html.erb, config/locales/en/providers.yml, config/routes.rb, spec/requests/providers/proceedings_sca/child_subjects_controller_spec.rb, spec/services/flow/steps/proceedings_sca/child_subjects_step_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4563) …
=> ap-4563: add Is your client the child subject of this proceeding? question

app/services/legal_framework/merits_tasks_service.rb, app/views/providers/merits_task_lists/show.html.erb, config/locales/en/providers.yml
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4724)
Switch the proceeding level questions to use an html format with the proceeding name included in a visually hidden span
Resequenced the yaml file to make it clearer for any future work *cough* SCA *cough* that requires adding more proceeding level questions that they should use this pattern …
=> AP-4724: Improve accessibility of merits task list

app/helpers/application_helper.rb, app/models/legal_aid_application.rb, app/views/providers/check_provider_answers/_standard.html.erb, app/views/shared/check_answers/_linking_and_copying.html.erb, spec/models/legal_aid_application_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-5071)
No line break on application ref …
=> AP-5071: No line break on application ref

app/controllers/providers/proceedings_sca/heard_as_alternatives_controller.rb, app/services/flow/flows/provider_start.rb, app/services/flow/steps/proceedings_sca/heard_as_alternatives_step.rb, app/views/providers/proceedings_sca/heard_as_alternatives/show.html.erb, app/views/providers/proceedings_sca/interrupts/show.html.erb, config/locales/en/providers.yml, config/routes.rb, spec/requests/providers/proceedings_sca/heard_as_alternatives_controller_spec.rb, spec/services/flow/steps/proceedings_sca/heard_as_alternatives_step_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4570)
Add `heard_as_alternatives` controller, view, specs, route, locales
- You …
=> AP-4570: Add heard_as_alternatives question

app/controllers/providers/proceedings_sca/change_of_names_controller.rb, app/services/flow/flows/provider_start.rb, app/services/flow/steps/proceedings_sca/change_of_names_step.rb, app/views/providers/proceedings_sca/change_of_names/show.html.erb, config/locales/en/providers.yml, config/routes.rb, spec/requests/providers/proceedings_sca/change_of_names_controller_spec.rb, spec/services/flow/steps/proceedings_sca/change_of_names_step_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4533) …
=> ap-4533: SCA question 4

app/services/flow/flows/provider_capital.rb, app/services/flow/steps/provider_capital/check_capital_answers_step.rb, app/services/flow/steps/provider_capital/check_passported_answers_step.rb, app/services/flow/steps/provider_capital/means_reports_step.rb, spec/requests/providers/check_capital_answers_controller_spec.rb, spec/requests/providers/check_passported_answers_spec.rb, spec/services/flow/steps/provider_capital/check_capital_answers_step_spec.rb, spec/services/flow/steps/provider_capital/check_passported_answers_step_spec.rb, spec/services/flow/steps/provider_capital/means_reports_step_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4669)
Update flow steps for provider capital CYA …
=> AP-4669: Flow refactor capital steps

app/controllers/providers/address_selections_base_controller.rb, app/controllers/providers/correspondence_address/selections_controller.rb, app/controllers/providers/home_address/selections_controller.rb, app/helpers/check_provider_answers_helper.rb, app/views/providers/check_provider_answers/_shared.html.erb, app/views/providers/means_reports/show.html.erb, app/views/shared/check_answers/_client_details.html.erb, app/views/shared/review_application/_questions_and_answers.html.erb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4840)
While testing locally I identified and had to resolve a couple of bugs that prevented reaching the means_report
When we changed the home address flow, we can now go straight to the home address controller.  This had a no_state_change_required? override that always by-passed the state change.  
This meant that when we reached the CYA page the applictaion state was in the initialised state and could not transition to the next state.
Reverting the home controller to match the correspondence controller allows either one to change the state and enable access to the CYA page.
If an application was created before the home address flag was enabled it would render incorrectly,
This adds some checks to the view and helper to ensure it …
=> AP-4840: Improve home address handling

app/forms/providers/link_application/find_link_application_form.rb, spec/forms/providers/link_application/find_link_application_form_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-5062) …
=> Ap 5062 normalise application ref when linking

app/controllers/providers/proceedings_sca/heard_togethers_controller.rb, app/services/flow/flows/provider_start.rb, app/services/flow/steps/proceedings_sca/heard_togethers_step.rb, app/views/providers/proceedings_sca/heard_togethers/show.html.erb, config/locales/en/providers.yml, config/routes.rb, spec/factories/proceedings.rb, spec/requests/providers/proceedings_sca/heard_togethers_controller_spec.rb, spec/services/flow/steps/proceedings_sca/heard_togethers_step_spec.rb
[SCA Question 3b - 'Will this proceeding be heard as an alternative to the '[core SCA]' proceeding?'](https://dsdmoj.atlassian.net/browse/AP-4569) …
=> AP-4569: Will proceedings be heard together

app/services/flow/flows/provider_capital.rb, app/services/flow/steps/provider_capital/add_other_vehicles_step.rb, app/services/flow/steps/provider_capital/introductions_step.rb, app/services/flow/steps/provider_capital/own_homes_step.rb, app/services/flow/steps/provider_capital/property_details_step.rb, app/services/flow/steps/provider_capital/vehicle_details_step.rb, app/services/flow/steps/provider_capital/vehicles_step.rb, spec/requests/providers/capital_introductions_controller_spec.rb, spec/requests/providers/means/add_other_vehicles_controller_spec.rb, spec/requests/providers/means/own_home_controller_spec.rb, spec/requests/providers/means/property_details_controller_spec.rb, spec/requests/providers/means/vehicle_details_controller_spec.rb, spec/requests/providers/means/vehicles_controller_spec.rb, spec/services/flow/steps/provider_capital/add_other_vehicles_step_spec.rb, spec/services/flow/steps/provider_capital/introductions_step_spec.rb, spec/services/flow/steps/provider_capital/own_homes_step_spec.rb, spec/services/flow/steps/provider_capital/property_details_step_spec.rb, spec/services/flow/steps/provider_capital/vehicle_details_step_spec.rb, spec/services/flow/steps/provider_capital/vehicles_step_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4667)
Refactor the required steps to use the new flow pattern …
=> AP-4667: flow refactor of capital property and vehicles steps

app/services/flow/flows/provider_income.rb, app/services/flow/steps/provider_income/cash_incomes_step.rb, app/services/flow/steps/provider_income/client_completed_means_step.rb, app/services/flow/steps/provider_income/employment_incomes_step.rb, app/services/flow/steps/provider_income/full_employment_details_step.rb, app/services/flow/steps/provider_income/identify_types_of_income_step.rb, app/services/flow/steps/provider_income/income_summary_step.rb, app/services/flow/steps/provider_income/incoming_transactions_step.rb, app/services/flow/steps/provider_income/regular_incomes_step.rb, app/services/flow/steps/provider_income/student_finances_step.rb, app/services/flow/steps/provider_income/unexpected_employment_incomes_step.rb, spec/requests/providers/income_summary_controller_spec.rb, spec/requests/providers/means/cash_incomes_controller_spec.rb, spec/requests/providers/means/employment_incomes_controller_spec.rb, spec/requests/providers/means/full_employment_details_controller_spec.rb, spec/requests/providers/means/identify_types_of_incomes_controller_spec.rb, spec/requests/providers/means/regular_incomes_controller_spec.rb, spec/requests/providers/means/student_finances_controller_spec.rb, spec/requests/providers/means/unexpected_employment_incomes_controller_spec.rb, spec/services/flow/steps/provider_income/cash_incomes_step_spec.rb, spec/services/flow/steps/provider_income/client_completed_means_step_spec.rb, spec/services/flow/steps/provider_income/employment_incomes_step_spec.rb, spec/services/flow/steps/provider_income/full_employment_details_step_spec.rb, spec/services/flow/steps/provider_income/identify_types_of_income_step_spec.rb, spec/services/flow/steps/provider_income/income_summary_step_spec.rb, spec/services/flow/steps/provider_income/incoming_transactions_step_spec.rb, spec/services/flow/steps/provider_income/regular_incomes_step_spec.rb, spec/services/flow/steps/provider_income/student_finances_step_spec.rb, spec/services/flow/steps/provider_income/unexpected_employment_incomes_step_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4671)
Refactored the following steps:-
- client_completed_means
- employment_incomes
- unexpected_employment_incomes
- full_employment_details
- identify_types_of_income
- incoming_transactions
- regular_inomes
- cash_incomes
- student_finances
- income_summary
(I did not refactor a couple of the steps that were originally on the ticket. domestic_abuse_summaries had already been refactored, I think this might have been an error when the ticket was drafted. I moved housing_benefits to ap-4672 as it seemed to be a better fit with the outgoings tickets)
- Github should not be reporting conflicts; you should have recently run `git rebase …
=> Ap 4671 flow refactor capital incomes

app/services/flow/flows/provider_capital.rb, app/services/flow/steps/provider_capital/applicant_bank_accounts_step.rb, app/services/flow/steps/provider_capital/offline_accounts_step.rb, app/services/flow/steps/provider_capital/other_assets_step.rb, app/services/flow/steps/provider_capital/partner_bank_accounts_step.rb, app/services/flow/steps/provider_capital/policy_disregards_step.rb, app/services/flow/steps/provider_capital/restrictions_step.rb, app/services/flow/steps/provider_capital/savings_and_investments_step.rb, spec/requests/providers/applicant_bank_accounts_controller_spec.rb, spec/requests/providers/means/other_assets_controller_spec.rb, spec/requests/providers/means/policy_disregards_controller_spec.rb, spec/requests/providers/means/restrictions_controller_spec.rb, spec/requests/providers/means/savings_and_investments_controller_spec.rb, spec/requests/providers/offline_accounts_spec.rb, spec/requests/providers/partners/bank_accounts_controller_spec.rb, spec/services/flow/steps/provider_capital/applicant_bank_accounts_step_spec.rb, spec/services/flow/steps/provider_capital/offline_accounts_step_spec.rb, spec/services/flow/steps/provider_capital/other_assets_step_spec.rb, spec/services/flow/steps/provider_capital/partner_bank_accounts_step_spec.rb, spec/services/flow/steps/provider_capital/policy_disregards_step_spec.rb, spec/services/flow/steps/provider_capital/restrictions_step_spec.rb, spec/services/flow/steps/provider_capital/savings_and_investments_step_spec.rb
[Flow refactoring - provider_capital - bank accounts, savings and investments, assets steps](https://dsdmoj.atlassian.net/browse/AP-4668) …
=> AP-4668: refactor final capital flow steps

app/services/flow/flows/provider_partner.rb, app/services/flow/steps/partner/cash_outgoings_step.rb, app/services/flow/steps/partner/regular_outgoings_step.rb, spec/requests/providers/partners/cash_outgoings_controller_spec.rb, spec/requests/providers/partners/regular_outgoings_controller_spec.rb, spec/services/flow/steps/partner/cash_outgoings_step_spec.rb, spec/services/flow/steps/partner/regular_outgoings_step_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4690)
- `partner_regular_outgoings` step
- `partner_cash_outgoings` step
- You …
=> AP-4690: Flow refactor partner outgoings steps

app/controllers/admin/reports_controller.rb, config/routes.rb, spec/requests/admin/reports_controller_spec.rb
[Add a report to allow Apply admin users to view/download details of user feedback](https://dsdmoj.atlassian.net/browse/AP-5056)
- You …
=> AP-5056-Add-user-feedback-report

app/services/flow/flows/provider_start.rb, app/services/flow/steps/provider_start/about_the_financial_assessments_step.rb, app/services/flow/steps/provider_start/application_confirmations_step.rb, app/services/flow/steps/provider_start/check_benefits_step.rb, app/services/flow/steps/provider_start/check_provider_answers_step.rb, app/services/flow/steps/provider_start/delegated_confirmation_step.rb, app/services/flow/steps/provider_start/no_national_insurance_numbers_step.rb, app/services/flow/steps/provider_start/substantive_applications_step.rb, app/services/flow/steps/provider_start/use_ccms_employment_step.rb, app/services/flow/steps/provider_start/use_ccms_step.rb, app/services/flow/steps/provider_start/use_ccms_under16s_step.rb, spec/requests/providers/no_national_insurance_numbers_controller_spec.rb, spec/requests/providers/substantive_applications_controller_spec.rb, spec/services/flow/steps/provider_start/about_the_financial_assessments_step_spec.rb, spec/services/flow/steps/provider_start/application_confirmations_step_spec.rb, spec/services/flow/steps/provider_start/check_benefits_step_spec.rb, spec/services/flow/steps/provider_start/check_provider_answers_step_spec.rb, spec/services/flow/steps/provider_start/delegated_confirmation_step_spec.rb, spec/services/flow/steps/provider_start/no_national_insurance_numbers_step_spec.rb, spec/services/flow/steps/provider_start/substantive_applications_step_spec.rb, spec/services/flow/steps/provider_start/use_ccms_employment_step_spec.rb, spec/services/flow/steps/provider_start/use_ccms_step_spec.rb, spec/services/flow/steps/provider_start/use_ccms_under16s_step_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4681) …
=> ap-4681: refactor end of provider_start flow

config/initializers/strong_migrations.rb
Update strong_migration target_version to match production psql version …
=> Chore: Update strong_migration target_version

app/services/flow/flows/provider_merits.rb, app/services/flow/steps/provider_merits/check_merits_answers_step.rb, app/services/flow/steps/provider_merits/confirm_client_declarations_step.rb, app/services/flow/steps/provider_merits/end_of_applications_step.rb, app/services/flow/steps/provider_merits/merits_reports_step.rb, app/services/flow/steps/provider_merits/merits_task_lists_step.rb, app/services/flow/steps/provider_merits/review_and_print_applications_step.rb, app/services/flow/steps/provider_merits/submitted_applications_step.rb, app/services/flow/steps/provider_merits/uploaded_evidence_collections_step.rb, spec/requests/providers/check_merits_answers_spec.rb, spec/requests/providers/confirm_client_declarations_controller_spec.rb, spec/requests/providers/end_of_applications_controller_spec.rb, spec/requests/providers/merits_task_lists_controller_spec.rb, spec/requests/providers/review_and_print_applications_controller_spec.rb, spec/requests/providers/uploaded_evidence_collection_spec.rb, spec/services/flow/steps/provider_merits/check_merits_answers_step_spec.rb, spec/services/flow/steps/provider_merits/confirm_client_declarations_step_spec.rb, spec/services/flow/steps/provider_merits/end_of_applications_step_spec.rb, spec/services/flow/steps/provider_merits/merits_reports_step_spec.rb, spec/services/flow/steps/provider_merits/merits_task_lists_step_spec.rb, spec/services/flow/steps/provider_merits/review_and_print_applications_step_spec.rb, spec/services/flow/steps/provider_merits/submitted_applications_step_spec.rb, spec/services/flow/steps/provider_merits/uploaded_evidence_collections_step_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4677) …
=> AP-4677: Flow refactoring - provider_merits - summary steps

app/controllers/providers/proceeding_merits_task/is_client_biological_parent_controller.rb, app/forms/providers/proceeding_merits_task/biological_parent_form.rb, app/services/flow/flows/provider_merits.rb, app/services/flow/merits_loop.rb, app/services/flow/steps/provider_merits/biological_parent_step.rb, app/views/providers/proceeding_merits_task/is_client_biological_parent/show.html.erb, config/locales/en/providers.yml, config/routes.rb, db/migrate/20240704134837_add_relationship_to_child_to_proceedings.rb, db/schema.rb, spec/factories/legal_framework_merits_task_list.rb, spec/factories/legal_framework_serialized_merits_task_list.rb, spec/forms/providers/proceeding_merits_task/biological_parent_form_spec.rb, spec/requests/providers/proceeding_merits_task/is_client_biological_parent_controller_spec.rb, spec/services/flow/steps/provider_merits/biological_parent_step_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4643)
This adds the first of the relationship SCA questions.
It implements the new question on the merits task list
It handles a positive response by recording it and moving to the next task on the list, if the answer is negative, for now, it will route back to the task list.  This will need updating to move to question 2 as part of the next ticket …
=> AP-4643: Add sca client relationship task

app/controllers/providers/proceeding_merits_task/does_client_have_parental_responsibilities_controller.rb, app/controllers/providers/proceeding_merits_task/is_client_biological_parent_controller.rb, app/forms/providers/proceeding_merits_task/parental_responsibilities_form.rb, app/services/flow/flows/provider_merits.rb, app/services/flow/steps/provider_merits/parental_responsibilities_step.rb, app/views/providers/proceeding_merits_task/does_client_have_parental_responsibilities/show.html.erb, app/views/providers/proceeding_merits_task/is_client_biological_parent/show.html.erb, config/locales/en/providers.yml, config/routes.rb, spec/forms/providers/proceeding_merits_task/parental_responsibilities_form_spec.rb, spec/requests/providers/proceeding_merits_task/does_client_have_parental_responsibilities_controller_spec.rb, spec/requests/providers/proceeding_merits_task/is_client_biological_parent_controller_spec.rb, spec/services/flow/steps/provider_merits/parental_responsibilities_step_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4644) …
=> AP-4644: SCA Q2 parental responsibilities

app/services/flow/flows/provider_partner.rb, app/services/flow/steps/partner/add_other_state_benefits_step.rb, app/services/flow/steps/partner/bank_statements_step.rb, app/services/flow/steps/partner/cash_incomes_step.rb, app/services/flow/steps/partner/receives_state_benefits_step.rb, app/services/flow/steps/partner/regular_incomes_step.rb, app/services/flow/steps/partner/state_benefits_step.rb, app/services/flow/steps/partner/student_finances_step.rb, spec/requests/providers/partners/add_other_state_benefits_controller_spec.rb, spec/requests/providers/partners/bank_statements_controller_spec.rb, spec/requests/providers/partners/cash_incomes_controller_spec.rb, spec/requests/providers/partners/receives_state_benefits_controller_spec.rb, spec/requests/providers/partners/regular_incomes_controller_spec.rb, spec/requests/providers/partners/state_benefits_controller_spec.rb, spec/requests/providers/partners/student_finances_controller_spec.rb, spec/services/flow/steps/partner/add_other_state_benefits_step_spec.rb, spec/services/flow/steps/partner/bank_statements_step_spec.rb, spec/services/flow/steps/partner/cash_incomes_step_spec.rb, spec/services/flow/steps/partner/receives_state_benefits_step_spec.rb, spec/services/flow/steps/partner/regular_incomes_step_spec.rb, spec/services/flow/steps/partner/state_benefits_step_spec.rb, spec/services/flow/steps/partner/student_finances_step_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4688)
Refactor the following steps: …
=> AP-4689: flow refactor partner income steps

app/services/flow/flows/provider_partner.rb, app/services/flow/steps/partner/employed_step.rb, app/services/flow/steps/partner/employment_incomes_step.rb, app/services/flow/steps/partner/full_employment_details_step.rb, app/services/flow/steps/partner/unexpected_employment_income_step.rb, app/services/flow/steps/partner/use_ccms_employment_step.rb, spec/factories/legal_aid_applications.rb, spec/requests/providers/partners/employed_controller_spec.rb, spec/requests/providers/partners/employment_incomes_controller_spec.rb, spec/requests/providers/partners/full_employment_details_controller_spec.rb, spec/requests/providers/partners/unexpected_employment_incomes_controller_spec.rb, spec/services/flow/steps/partner/employed_step_spec.rb, spec/services/flow/steps/partner/employment_incomes_step_spec.rb, spec/services/flow/steps/partner/full_employment_details_step_spec.rb, spec/services/flow/steps/partner/unexpected_employment_income_step_spec.rb, spec/services/flow/steps/partner/use_ccms_employment_step_spec.rb
[Flow refactoring - provider_partner - employment details steps](https://dsdmoj.atlassian.net/browse/AP-4688)
Refactor the employment details steps flow/steps into individual step classes.
Steps:
1. partner_employed
2. partner_use_ccms_employment
3. partner_full_employment_details
4. partner_employment_incomes
5. partner_unexpected_employment_income …
=> AP-4688: Flow refactor partner employment steps

app/services/flow/flows/provider_partner.rb, app/services/flow/steps/partner/add_other_state_benefits_step.rb, app/services/flow/steps/partner/bank_statements_step.rb, app/services/flow/steps/partner/cash_incomes_step.rb, app/services/flow/steps/partner/receives_state_benefits_step.rb, app/services/flow/steps/partner/regular_incomes_step.rb, app/services/flow/steps/partner/state_benefits_step.rb, app/services/flow/steps/partner/student_finances_step.rb, spec/requests/providers/partners/add_other_state_benefits_controller_spec.rb, spec/requests/providers/partners/bank_statements_controller_spec.rb, spec/requests/providers/partners/cash_incomes_controller_spec.rb, spec/requests/providers/partners/receives_state_benefits_controller_spec.rb, spec/requests/providers/partners/regular_incomes_controller_spec.rb, spec/requests/providers/partners/state_benefits_controller_spec.rb, spec/requests/providers/partners/student_finances_controller_spec.rb, spec/services/flow/steps/partner/add_other_state_benefits_step_spec.rb, spec/services/flow/steps/partner/bank_statements_step_spec.rb, spec/services/flow/steps/partner/cash_incomes_step_spec.rb, spec/services/flow/steps/partner/receives_state_benefits_step_spec.rb, spec/services/flow/steps/partner/regular_incomes_step_spec.rb, spec/services/flow/steps/partner/state_benefits_step_spec.rb, spec/services/flow/steps/partner/student_finances_step_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4689)
Update flow refactor steps …
=> AP-4689: Flow refactor partner income

app/controllers/providers/proceeding_merits_task/does_client_have_parental_responsibilities_controller.rb, app/controllers/providers/proceeding_merits_task/is_client_child_subject_controller.rb, app/forms/providers/proceeding_merits_task/child_subject_form.rb, app/services/flow/flows/provider_merits.rb, app/services/flow/steps/provider_merits/child_subject_step.rb, app/views/providers/proceeding_merits_task/is_client_child_subject/show.html.erb, config/locales/en/providers.yml, config/routes.rb, spec/forms/providers/proceeding_merits_task/child_subject_form_spec.rb, spec/requests/providers/proceeding_merits_task/does_client_have_parental_responsibilities_controller_spec.rb, spec/requests/providers/proceeding_merits_task/is_client_child_subject_controller_spec.rb, spec/services/flow/steps/provider_merits/child_subject_step_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4645) …
=> Ap 4645 sca client role q3

app/controllers/providers/proceeding_merits_task/check_who_client_is_controller.rb, app/controllers/providers/proceeding_merits_task/does_client_have_parental_responsibilities_controller.rb, app/controllers/providers/proceeding_merits_task/is_client_biological_parent_controller.rb, app/controllers/providers/proceeding_merits_task/is_client_child_subject_controller.rb, app/forms/providers/proceeding_merits_task/biological_parent_form.rb, app/forms/providers/proceeding_merits_task/child_subject_form.rb, app/forms/providers/proceeding_merits_task/parental_responsibilities_form.rb, app/helpers/task_list_helper.rb, app/services/flow/flows/provider_merits.rb, app/services/flow/steps/provider_merits/check_who_client_is_step.rb, app/views/providers/merits_task_lists/show.html.erb, app/views/providers/proceeding_merits_task/check_who_client_is/show.html.erb, app/views/shared/check_answers/_relationship_to_child.html.erb, config/locales/en/providers.yml, config/locales/en/shared.yml, config/routes.rb, spec/helpers/task_list_helper_spec.rb, spec/requests/providers/proceeding_merits_task/check_who_client_is_controller_spec.rb, spec/requests/providers/proceeding_merits_task/is_client_child_subject_controller_spec.rb, spec/services/flow/steps/provider_merits/check_who_client_is_step_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4646)
- Add check who your client is CYA page
- Update forms for Qs 1-3 so they behave as expected
- Add check_who_your_client_is step and step spec …
=> AP-4646: SCA check who your client is

app/controllers/providers/check_merits_answers_controller.rb, app/forms/legal_aid_applications/confirm_separate_representation_form.rb, app/views/providers/check_merits_answers/show.html.erb, config/locales/en/activemodel.yml, config/locales/en/providers.yml, db/migrate/20240711135846_add_separate_representation_required_to_legal_aid_applications.rb, db/schema.rb, spec/forms/legal_aid_applications/confirm_separate_representation_form_spec.rb, spec/requests/providers/check_merits_answers_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4623) …
=> Ap 4623 add separate representation confirmation

app/controllers/providers/proceedings_sca/confirm_delete_core_proceedings_controller.rb, app/models/legal_aid_application.rb, app/views/providers/has_other_proceedings/show.html.erb, app/views/providers/proceedings_sca/confirm_delete_core_proceedings/show.html.erb, config/locales/en/providers.yml, config/routes.rb, spec/models/legal_aid_application_spec.rb, spec/requests/providers/proceedings_sca/confirm_delete_core_proceedings_controller_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-5211)
Added confirm_delete_core_proceedings route, controller and view
TODO
Further work on back link functionality? (see comment for discussion) …
=> Ap 5211 user removing core proceeding

app/views/providers/has_other_proceedings/show.html.erb, config/locales/en/providers.yml
[Link to story](https://dsdmoj.atlassian.net/browse/AP-5233)
This is to alert providers that subsequent searches may have a restricted list due to current choices …
=> AP-5233: Add proceeding inset text

Brewfile, README.md, spec/services/pda/compare_provider_details_spec.rb, spec/services/pda/provider_details_creator_spec.rb, spec/services/provider_details_creator_spec.rb
Some documentation and fixes coming out of setup
- Remove redundant tap that fails from brew file
- Update readme based on setup experience
- Replace constants, that output warnings,  with lets …
=> Changes coming out of setup experience

app/models/application_digest.rb, app/models/legal_aid_application.rb, app/services/reports/mis/application_detail_csv_line.rb, db/migrate/20240918073446_add_fields_to_application_digest.rb, db/schema.rb, spec/models/application_digest_spec.rb, spec/models/legal_aid_application_spec.rb, spec/services/reports/mis/application_detail_csv_line_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-5272)
Added six new columns to admin report and digest; Family linked?, Family link lead?, Number of family links, Legal linked?, Family link lead? and Number of legal links. See ticket for discussion. …
=> Ap 5272 add linked cases application digest

app/controllers/admin/settings_controller.rb, app/forms/settings/setting_form.rb, app/models/setting.rb, app/views/admin/settings/show.html.erb, config/locales/en/admin.yml, db/migrate/20241001081701_add_public_law_family_to_settings.rb, db/schema.rb, spec/models/setting_spec.rb, spec/requests/admin/settings_controller_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-5322)
Add feature flag for public law family …
=> AP-5322: Add feature flag for public law family

app/controllers/application_controller.rb, app/controllers/concerns/providers/application_dependable.rb
Add sentry capturing and error logging for page_not found
Because national legal services providers are encountering this when
selecting an office. …
=> Add sentry capturing and error logging for page_not found

app/services/legal_framework/proceeding_types/all.rb, spec/services/legal_framework/proceeding_types/all_spec.rb
[Add Public Law Family feature flag to Apply's proceeding search](https://dsdmoj.atlassian.net/browse/AP-5326) …
=> AP-5326: Add Public Law Family feature flag to proceeding search

config/initializers/sidekiq.rb
Use default prometheus exporter sidekiq Instrumentation
[Link to story](https://dsdmoj.atlassian.net/browse/AP-5317)
An Prometheus custom alert rule was added that relies on
`ruby_sidekiq_stats_dead_size` stats. These do not appear to
be being generated and therefore no alerts triggered.
Changing the Prometheus exporter death handler and other Instrumentation
in line with those used in laa-submit-crime-forms in the hope
this will generate the necessary stats to alert on.
- The standards in the [Git Workflow document on Confluence](https://dsdmoj.atlassian.net/wiki/spaces/ATPPB/pages/4602855954/Git+Work …
=> AP-5317: Use default prometheus exporter sidekiq Instrumentation

app/controllers/providers/legal_aid_applications_controller.rb
add latest to in progress applications
=> Chore: add latest to in progress applications

app/controllers/providers/partners/add_other_state_benefits_controller.rb, app/models/concerns/binary_choice_form.rb, app/views/providers/transactions/show.html.erb, app/views/shared/means/_regular_income.html.erb, app/views/shared/state_benefits/_add_other_state_benefits.html.erb, app/views/shared/state_benefits/_new_benefit_form.erb, config/locales/cy/transaction_types.yml, config/locales/en/activemodel.yml, config/locales/en/helpers.yml, config/locales/en/providers.yml, config/locales/en/shared.yml, config/locales/en/transaction_types.yml, features/providers/bank_statement_upload/happy_path_journey.feature, features/providers/bank_statement_upload/state_benefit_loop.feature, features/providers/check_your_answers.feature, features/providers/means_report.feature, features/providers/non_passported_journey/with_bank_transactions.feature, features/providers/non_passported_journey/with_means.feature, features/providers/partner_means_assessment/end_to_end_income_assessment.feature, features/providers/partner_means_assessment/means_report.feature, features/providers/partner_means_assessment/state_benefits.feature, features/providers/review_and_print.feature, spec/requests/providers/means/add_other_state_benefits_controller_spec.rb, spec/requests/providers/means/state_benefits_controller_spec.rb, spec/requests/providers/partners/add_other_state_benefits_controller_spec.rb, spec/requests/providers/partners/state_benefits_controller_spec.rb
> [!WARNING] 
> Confirm with BA these changes are ok to go out! ✅ 
Amend content for benefit and income pages inline with designs
[Link to story](https://dsdmoj.atlassian.net/browse/AP-5412)
This applies some content changes that can go in before MTR A release
and therefore does not require a release flag. …
=> AP-5412: Amend benefit and income quesion content

features/providers/check_ccms_autogrant.feature, features/providers/check_multiple_employment.feature, features/providers/check_pending_employment.feature, features/providers/check_single_employment.feature, features/providers/check_your_answers.feature, features/providers/mtr_accelerated/main_dwelling.feature, features/providers/non_passported_journey/waiting_for_applicant.feature, features/providers/partner_means_assessment/means_check.feature
Fix pending feature tests by updating to visit the in progress applications page …
=> Chore: fix pending feature tests

config/routes.rb, db/anonymise/rules.rb, db/migrate/20241022133251_create_capital_disregards.rb, db/schema.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-5426)
Add a new table `CapitalDisregards` to record both mandatory and discretionary disregards.
Add the `capital_disregards` namespace  …
=> AP-5426 Create capital disregards DB table and add namespace

.github/workflows/dependabot-jira.yml
Changed jira summary and description due to character limits within Jira …
=> Chore: amend gajira summary and description

app/models/legal_aid_application.rb, app/views/providers/proceeding_loop/client_involvement_type/show.html.erb, config/locales/en/providers.yml, features/cassettes/Adding_an_SCA_Secure_Accommodation_Order_proceeding_sets_all_client_involvement_types_to_Child/When_a_provider_is_adding_proceedings_and_only_adds_a.yml, features/providers/special_children_act/secure_accomodation_order_cit.feature
[Link to story](https://dsdmoj.atlassian.net/browse/AP-5397)
Update the client_involvement_type page to set the cit submitted to the form to be the code for child if _any_ of the proceedings on the application are an SCA Secure Accommodation Order
The user has already selected a yes response to the question `Is your client the child subject of this proceeding`
- There should be no unnecessary whitespace changes. These make diffs harder to read …
=> AP-5397: Update handling of CIT for SCA Secure Accommodation Orders

app/models/proceeding.rb, app/views/providers/application_merits_task/statement_of_cases/show.html.erb, config/locales/en/providers.yml
[Link to story](https://dsdmoj.atlassian.net/browse/AP-5376)
Remove first bullet point if not domestic abuse case …
=> AP-5376: Remove first bullet if not domestic abuse

config/locales/en/providers.yml
[Link to story](https://dsdmoj.atlassian.net/browse/AP-5391)
Update bullet point lead in text on interrupt/supervision page
- You …
=> AP-5391: Update bullet point lead in text

app/views/shared/means/_cost_of_living_and_disregarded_benefits.html.erb, config/locales/en/helpers.yml, config/locales/en/shared.yml, db/schema.rb, features/providers/mtr_accelerated/disregard_list.feature
Content changes to disregarded benefits list and question
[Link to story](https://dsdmoj.atlassian.net/browse/AP-5412)
These are content changes/fixes coming out of design review of AP-5349, but which can be done separately …
=> AP-5412: Amend MTRA disregard list

app/controllers/admin/user_dashboard_controller.rb
It got deleted during the great geckoboard removal and was not spotted during the code review! …
=> Chore: Restore the admin user dashboard controller

app/javascript/src/dropzone.js, app/javascript/src/file-upload-categorisation.js
Refactor of evidence upload js
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2910)
Share initialisation code
- You should …
=> AP-2910: Refactor of evidence upload js

app/controllers/application_controller.rb, app/controllers/errors_controller.rb, app/forms/applicants/basic_details_form.rb, app/views/errors/show.html.erb, config/application.rb, config/environments/development.rb, config/locales/cy/errors.yml, config/locales/en/errors.yml, config/routes.rb, spec/requests/citizens/legal_aid_applications_controller_spec.rb, spec/requests/errors_controller_spec.rb, spec/requests/providers/bank_transactions_controller_spec.rb, spec/support/request_error_helpers.rb
Implement custom error handling using a rails approach
[Link to story](https://dsdmoj.atlassian.net/browse/AP-5524)
This uses application config `exceptions_app` to wire up our own exception handling via the same controller. it enables a page not found to raise 404 and not redirect, so that logs will informs us what caused the 404. It also handles internal servers errors, which currently aren't, by displaying the custom error page but still resulting in 500s as there are no redirects. Access denied and "Assessment already completed" are handled as they were previously.
Idea from https://dev.to/ayushn21/custom-error-pages-in-rails-4i43
See rails documentation for [exceptions_app](https://guides.rubyonrails.org/configuring.html#config-exceptions-app)
- Access denied can be tested on this …
=> AP-5524: Replace error handling with exceptions_app

app/forms/applicants/basic_details_form.rb, config/environments/development.rb
Remove test code from 5524 branch merge
[Link to story](https://dsdmoj.atlassian.net/browse/AP-5524)
Forgot to take this out before merge …
=> AP-5524: Revert temp commit c7e536240

.env.sample
=> Amend .env.sample for LFA local development

docs/pull_request_template.md
Remove top linebreaks from PR tempplate
They are not needed and I always end up deleting them …
=> Remove top linebreaks from PR template

.env.sample
Update instructions for development and UAT LFA usage
[Link to story](https://dsdmoj.atlassian.net/browse/AP-5377)
Agreed by team to use AWS secret for pointing branches at UAT 
LFA branches.
Approach has been tested on a separate branch with success …
=> AP-5377: Update instructions for development and UAT LFA usage

app/forms/proceedings/emergency_defaults_form.rb, app/forms/proceedings/substantive_defaults_form.rb, app/views/providers/proceeding_loop/emergency_level_of_service/show.html.erb, app/views/providers/proceeding_loop/substantive_level_of_service/show.html.erb, features/cassettes/Loop_through_proceeding_questions/No_preselected_emergency_or_substantive_levels_of_service.yml, features/cassettes/Loop_through_proceeding_questions/When_provider_does_not_accept_default_levels_of_service.yml, features/providers/proceeding_loop.feature, features/providers/regressions/scope_limitations.feature, spec/cassettes/EmergencyDefaultsController/POST_/providers/applications/_legal_aid_application_id/emergency_defaults/_proceeding_id/when_the_provider_is_authenticated/when_the_Continue_button_is_pressed/when_the_provider_accepts_the_defaults/redirects_to_next_page.yml, spec/cassettes/EmergencyDefaultsController/POST_/providers/applications/_legal_aid_application_id/emergency_defaults/_proceeding_id/when_the_provider_is_authenticated/when_the_Continue_button_is_pressed/when_the_provider_accepts_the_defaults/sets_the_default_emergency_levels_of_service.yml, spec/cassettes/EmergencyDefaultsController/POST_/providers/applications/_legal_aid_application_id/emergency_defaults/_proceeding_id/when_the_provider_is_authenticated/when_the_Continue_button_is_pressed/when_the_provider_does_not_accept_the_defaults/clears_the_emergency_levels_of_service.yml, spec/cassettes/EmergencyDefaultsController/POST_/providers/applications/_legal_aid_application_id/emergency_defaults/_proceeding_id/when_the_provider_is_authenticated/when_the_Continue_button_is_pressed/when_the_provider_does_not_accept_the_defaults/redirects_to_next_page.yml, spec/forms/proceedings/emergency_defaults_form_spec.rb, spec/requests/providers/proceeding_loop/emergency_defaults_controller_spec.rb
Stop preselecting emergency level of service
[Link to story](https://dsdmoj.atlassian.net/browse/AP-5589)
Came out of UAT of another bug.
The emergency levels of service were being cleared but not saved
due to the location of the `super` call in the local form `save`
method, I believe.
This duplicates what the substantive defaults form does more
closely which does ensure that the clearing of defaults is followed
by a save. …
=> AP-5589: Stop preselecting emergency level of service

app/views/providers/proceeding_merits_task/vary_order/show.html.erb, app/views/shared/check_answers/_merits_proceeding_section.html.erb, config/locales/en/activemodel.yml, config/locales/en/providers.yml, config/locales/en/shared.yml, config/routes.rb
[Amend to existing “Why are you making a new application?” question](https://dsdmoj.atlassian.net/browse/AP-4414) …
=> AP-4414: Amend question why new application

README.md
[Link to story](https://dsdmoj.atlassian.net/browse/AP-5162)
Minor cleanup of README following git-crypt removal …
=> AP-5162: Remove encryption documentation

app/views/providers/start/index.html.erb, config/locales/en/providers.yml
[Link to story](https://dsdmoj.atlassian.net/browse/AP-5616)
Update the landing page text generally and add a specific line to highlight to SCA users that it has been added …
=> AP-5616: Update landing page for SCA users

config/locales/en/providers.yml
The colon got dropped from the end of the line
in the SCA update, this was a mistake …
=> Fix: Typo on landing page

app/controllers/providers/application_merits_task/second_appeals_controller.rb, app/forms/providers/application_merits_task/second_appeal_form.rb, app/models/application_merits_task/appeal.rb, app/models/legal_aid_application.rb, app/models/legal_framework/merits_task_list.rb, app/services/flow/flows/provider_merits.rb, app/services/flow/merits_loop.rb, app/services/flow/steps/provider_merits/second_appeals_step.rb, app/views/providers/application_merits_task/second_appeals/show.html.erb, app/views/shared/check_answers/_merits.html.erb, app/views/shared/check_answers/_second_appeal.html.erb, config/locales/en/activemodel.yml, config/locales/en/providers.yml, config/locales/en/shared.yml, config/routes.rb, db/anonymise/rules.rb, db/migrate/20241211093840_create_appeals.rb, db/schema.rb, features/providers/check_merits_answers.feature, features/step_definitions/check_merits_answers.rb, features/step_definitions/civil_journey_steps.rb, spec/factories/application_merits_task/appeals.rb, spec/factories/legal_aid_applications.rb, spec/factories/legal_framework_merits_task_list.rb, spec/factories/legal_framework_serialized_merits_task_list.rb, spec/factories/proceedings.rb, spec/forms/providers/application_merits_task/second_appeal_form_spec.rb, spec/models/legal_framework/merits_task_list_spec.rb, spec/requests/providers/application_merits_task/second_appeals_controller_spec.rb, spec/services/flow/steps/provider_merits/second_appeals_step_spec.rb
Add second appeal merits question
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4408)
Inline with requirements and designs for PLF …
=> AP-4408: Add second appeal merits question

app/controllers/providers/application_merits_task/original_judge_levels_controller.rb, app/forms/base_form.rb, app/forms/providers/application_merits_task/original_judge_level_form.rb, app/forms/providers/application_merits_task/second_appeal_form.rb, app/services/flow/flows/provider_merits.rb, app/services/flow/steps/provider_merits/original_judge_levels_step.rb, app/services/flow/steps/provider_merits/second_appeals_step.rb, app/views/providers/application_merits_task/original_judge_levels/show.html.erb, app/views/providers/application_merits_task/second_appeals/show.html.erb, app/views/providers/proceeding_loop/emergency_level_of_service/show.html.erb, app/views/shared/check_answers/_second_appeal.html.erb, config/locales/en/activemodel.yml, config/locales/en/providers.yml, config/locales/en/shared.yml, config/routes.rb, features/providers/check_merits_answers.feature, features/providers/public_law_family/merits_appeal_question_flow.feature, features/step_definitions/check_merits_answers.rb, features/step_definitions/civil_journey_steps.rb, features/step_definitions/merits_task_list_steps.rb, spec/factories/legal_aid_applications.rb, spec/factories/legal_framework_serialized_merits_task_list.rb, spec/forms/providers/application_merits_task/original_judge_level_form_spec.rb, spec/forms/providers/application_merits_task/second_appeal_form_spec.rb, spec/requests/providers/application_merits_task/original_judge_levels_controller_spec.rb, spec/requests/providers/application_merits_task/second_appeals_controller_spec.rb, spec/services/flow/steps/provider_merits/original_judge_levels_step_spec.rb, spec/services/flow/steps/provider_merits/second_appeals_step_spec.rb
Add original judge level question
[Link to story](https://dsdmoj.atlassian.net/browse/AP-5530)
Inline with requirements and designs for PLF …
=> AP-5530: Add original judge level question

app/views/shared/check_answers/_children_involved.html.erb, app/views/shared/check_answers/_gateway_evidence.html.erb, app/views/shared/check_answers/_laspo.html.erb, app/views/shared/check_answers/_latest_incident_details.html.erb, app/views/shared/check_answers/_matter_opposition.html.erb, app/views/shared/check_answers/_merits_proceeding_section.html.erb, app/views/shared/check_answers/_opponent_details.html.erb, app/views/shared/check_answers/_separate_representation.html.erb, app/views/shared/check_answers/_supporting_evidence.html.erb, app/views/shared/check_answers/_undertaking.html.erb, app/views/shared/check_answers/_urgency.html.erb, config/locales/en/shared.yml, features/providers/check_merits_answers.feature, features/providers/partner_means_assessment/review_and_print.feature, features/providers/review_and_print.feature, features/step_definitions/civil_journey_steps.rb, spec/factories/legal_framework_merits_task_list.rb, spec/factories/legal_framework_serialized_merits_task_list.rb, spec/requests/providers/check_merits_answers_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-5584)
Visual changes to merits cya page - use summary cards. …
=> Ap 5584 check merits answers

app/helpers/proceeding_helper.rb, app/services/scope_limitation_detail_builder.rb
This work was recommended in the #7541 ticket but that was merged before the Christmas change freeze 
This PR extracts the logic to a new external class to simplify the helper code
It is tested as part of the proceeding_helper_spec
#proceeding helper …
=> LnD: Refactor the proceeding_helper

app/controllers/providers/proceeding_merits_task/child_care_assessment_results_controller.rb, app/forms/providers/proceeding_merits_task/child_care_assessment_result_form.rb, app/services/flow/flows/provider_merits.rb, app/services/flow/steps/provider_merits/child_care_assessment_result_step.rb, app/services/flow/steps/provider_merits/child_care_assessment_step.rb, app/views/providers/proceeding_merits_task/child_care_assessment_results/show.html.erb, app/views/shared/check_answers/_child_care_assessment.html.erb, config/locales/en/activemodel.yml, config/locales/en/providers.yml, config/locales/en/shared.yml, config/routes.rb, features/providers/check_merits_answers.feature, features/providers/public_law_family/merits_child_care_assessment_question_flow.feature, spec/forms/providers/proceeding_merits_task/child_care_assessment_result_form_spec.rb, spec/requests/providers/proceeding_merits_task/child_care_assessment_results_controller_spec.rb, spec/requests/providers/proceeding_merits_task/child_care_assessments_controller_spec.rb, spec/services/flow/steps/provider_merits/child_care_assessment_result_step_spec.rb, spec/services/flow/steps/provider_merits/child_care_assessment_step_spec.rb
Add PLF question 4b - child care assessment result
[Link to story](https://dsdmoj.atlassian.net/browse/AP-5533) …
=> AP-5533: Add PLF question 4b - child care assessment result

features/providers/non_passported_journey/with_bank_transactions.feature
This was merged after a few significant PRs and it should have been rebased first... my bad! …
=> Fix: Update expected text in feature

app/controllers/providers/application_merits_task/court_order_copies_controller.rb, app/forms/providers/application_merits_task/plf_court_order_form.rb, app/services/flow/flows/provider_merits.rb, app/services/flow/merits_loop.rb, app/services/flow/steps/provider_merits/court_order_copies_step.rb, app/views/providers/application_merits_task/court_order_copies/show.html.erb, app/views/shared/check_answers/_merits.html.erb, app/views/shared/check_answers/_plf_court_order.html.erb, config/locales/en/activemodel.yml, config/locales/en/providers.yml, config/locales/en/shared.yml, config/routes.rb, db/migrate/20250114135742_add_plf_court_order_to_legal_aid_application.rb, db/schema.rb, spec/factories/legal_aid_applications.rb, spec/factories/legal_framework_merits_task_list.rb, spec/factories/legal_framework_serialized_merits_task_list.rb, spec/forms/providers/application_merits_task/plf_court_order_form_spec.rb, spec/requests/providers/application_merits_task/court_order_copies_controller_spec.rb, spec/services/flow/steps/provider_merits/court_order_copies_step_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4305)
Adds the new, PLF, application level, Court Order question
This is stored on the application model to avoid another small table with single field, happy to discuss …
=> AP-4305: PLF court order merits question

app/controllers/admin/feedback_controller.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-5732)
Sort feedback newest first on admin page …
=> AP-5732: Sort feedback newest first

app/views/shared/page_templates/_basic_page_template.html.erb, app/views/shared/page_templates/_default_page_template.html.erb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-5086) …
=> AP-5086: Error message boxes - full page width

db/schema.rb
Run migration to update schema to 8.0. Missed on previous PR …
=> Chore: update schema to 8.0

spec/services/uploaded_evidence/shared_examples_for_uploaded_evidence.rb
Fix failing shared spec from previous PR for ticket.
[Link to story](https://dsdmoj.atlassian.net/browse/AP-5792)
Not sure how this passed the test suite on the branch TBH. …
=> AP-5792: Fix failing shared expectation

app/services/flow/merits_loop.rb
The actual step name got refactored but this reference did not! …
=> Fix: Update flow step name

README.md, config/locales/en/activerecord.yml, config/locales/en/layouts.yml, config/locales/en/providers.yml, config/locales/en/shared.yml, features/providers/back_button.feature, features/providers/cookies.feature, features/providers/start_page.feature, features/step_definitions/cookie_steps.rb, spec/requests/providers/legal_aid_applications_spec.rb
[Update the service name to ‘Apply for _**civil**_ legal aid’](https://dsdmoj.atlassian.net/browse/AP-5816) …
=> AP-5816: Update service name to add civil

app/views/feedback/new.cy.html.erb, app/views/feedback/new.en.html.erb, features/citizens/citizens_welsh.feature, features/providers/provider_feedback.feature, spec/requests/feedbacks_spec.rb
[Update the service name to ‘Apply for civil legal aid’.](https://dsdmoj.atlassian.net/browse/AP-5816)
Fix test failures due to not having rebased after feedback page changes from ticket [AP-5771](https://dsdmoj.atlassian.net/browse/AP-5771), which was merged earlier today . …
=> AP-5816: Fix test failures

app/views/feedback/_form.html.erb, config/locales/cy/feedback.yml, config/locales/en/feedback.yml
An update to AP-5771, this is to improve the accessibility of the feedback form  textarea. …
=> AP-5771: Accessibility update to feedback form

app/views/citizens/check_answers/_bank_accounts.html.erb, app/views/citizens/check_answers/index.html.erb, config/locales/cy/citizens.yml, config/locales/en/citizens.yml
[Link to story](https://dsdmoj.atlassian.net/browse/AP-5818)
Update check_answers to use summary cards
Screenshot: …
=> AP-5818: Update check_answers to use summary cards

config/locales/en/activemodel.yml
[Link to story](https://dsdmoj.atlassian.net/browse/AP-5072) …
=> AP-5072: Change error message for accessibility

.github/dependabot.yml, package.json, yarn.lock
Split `ministryofjustice/frontend` into it's own group so that the major update to 4.x+ does not delay other package updates …
=> Fix: Update NPM dependabot

.github/dependabot.yml
The first attempt did not split the moj frontend out like expected. This tries adding the leading @ symbol …
=> Chore: Update npm dependabot instructions

app/services/hmrc/interface/submission_service.rb, config/application.rb, helm_deploy/apply-for-legal-aid/values-production.yaml, helm_deploy/apply-for-legal-aid/values-staging.yaml, helm_deploy/apply-for-legal-aid/values-uat.yaml, spec/services/hmrc/interface/submission_service_spec.rb
Amend HMRC duration check from 4 months to 93 days
[Link to story](https://dsdmoj.atlassian.net/browse/AP-5809)
Requested by caseworkers
- I have checked that a 93 day old start date causes no issues against the HMRC Interface app on staging and UAT. There is no data returned however which i believe is expected in any event.
- I have checked that the 93 day period is reflected on Civil Apply UAT environment, albeit that it is merely querying mock data, as in screenshot below
Aside from that I believe we will need to release and monitor to ensure no issues arise in production.
- The [development …
=> AP-5809: Amend HMRC duration check from 4 months to 93 days

app/controllers/admin/reports_controller.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-5733) …
=> AP-5733: Change feedback report to created_at ascending

app/services/legal_framework/merits_tasks_retriever_service.rb, spec/services/legal_framework/merits_tasks_retriever_service_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-5698)
Update merits task retriever to send level of service, this will allow us to track the S8 merit question rules …
=> AP-5698: Update Chance of Success handling

features/cassettes/Scope_limitations_not_being_set/When_a_provider_creates_an_application_with_multiple_proceedings_and_uses_the_back_button_scope_limitations_should_not_be_removed.yml
Fix feature test that broke
[Link to story](https://dsdmoj.atlassian.net/browse/AP-5324)
Not sure how this broke against main but rerecorded cassette should fix it. …
=> AP-5324: Fix scope limitation feature test

app/views/providers/means_reports/_caseworker_review.html.erb, config/locales/en/providers.yml, features/providers/means_report.feature, features/providers/partner_means_assessment/means_report.feature, features/step_definitions/means_report_steps.rb, spec/factories/attachments.rb, spec/factories/cfe_results/v6/mock_results.rb, spec/factories/cfe_results/v6/results.rb, spec/factories/legal_aid_applications.rb
> [!IMPORTANT]
> Waiting for comms to go out to case workers before merge/release
Amend case worker review reason content
[Link to story](https://dsdmoj.atlassian.net/browse/AP-5942)
Comes out of reviews and discussions to help caseworkers understand
the review reasons. …
=> AP-5942: Amend caseworker review reasons content

helm_deploy/apply-for-legal-aid/values-production.yaml, helm_deploy/apply-for-legal-aid/values-staging.yaml
=> Incident: take down service

config/locales/en/pages.yml
=> Incident: amend servicedown content

helm_deploy/apply-for-legal-aid/values-production.yaml, helm_deploy/apply-for-legal-aid/values-staging.yaml
Add an nginx permanent redirect for staging and production …
=> Fix: Add NGINX redirect for staging as a test

lib/tasks/update_provider_step_to_nino_page.rake
Refactor data migration rake task
[Link to story](https://dsdmoj.atlassian.net/browse/AP-5970)
Remove redundant where clause and make logging of stats more accurate
Run below against an anonymised  production dump:
```sh
Migrating legal aid applications: setting provider_step: has_national_insurance_numbers
----------------------------------------
Number of applications that need to be moved: 1023
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Migrate:  0.070832   0.020266   0.091098 (  0.124474)
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
Applications updated    : 0
Applications not updated: 1023
----------------------------------------
```
```sh
Migrating legal aid applications: setting provider_step: has_national_insurance_numbers
----------------------------------------
Number of applications …
```
=> AP-5970: Refactor data migration rake task

app/services/flow/steps/linked_applications/copy_step.rb, app/services/flow/steps/provider_start/applicant_details_step.rb, app/services/flow/steps/provider_start/applicants_step.rb, app/services/flow/steps/provider_start/has_national_insurance_numbers_step.rb, app/services/flow/steps/provider_start/limitations_step.rb, app/views/shared/check_answers/_client_details.html.erb, features/providers/applicant_details.feature, features/providers/cost_override.feature, features/providers/linked_applications/back_button.feature, features/providers/no_nino_flow.feature, features/providers/non_means_tested_journey/under_18_application_journey.feature, features/providers/non_means_tested_journey/with_delegated_functions.feature, features/providers/non_means_tested_journey/without_delegated_functions.feature, features/providers/proceeding_loop.feature, features/providers/regressions/back_button_on_proceedings.feature, features/providers/regressions/scope_limitations.feature, features/providers/search_proceedings.feature, features/providers/special_children_act/secure_accomodation_order_cit.feature, lib/tasks/update_provider_step_to_nino_page.rake, spec/requests/providers/concerns/providers/draftable_spec.rb, spec/services/flow/steps/linked_applications/copy_step_spec.rb, spec/services/flow/steps/provider_start/applicant_details_step_spec.rb, spec/services/flow/steps/provider_start/applicants_step_spec.rb, spec/services/flow/steps/provider_start/has_national_insurance_numbers_step_spec.rb, spec/services/flow/steps/provider_start/limitations_step_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-5970)
Move nino question to earlier in the journey …
=> AP-5970: Move nino question

Dockerfile, app/views/accessibility_statement/index.cy.html.erb, app/views/accessibility_statement/index.en.html.erb, config/application.rb, config/initializers/mock_saml.rb, db/seeds/admin_users.rb, db/seeds/test_provider_populator.rb, docker/apply_base.dockerfile, docker/apply_ci.dockerfile, features/cassettes/Scope_limitations_not_being_set/When_a_provider_creates_an_application_with_multiple_proceedings_and_uses_the_back_button_scope_limitations_should_not_be_removed.yml, features/providers/provider_feedback.feature, spec/requests/contact_spec.rb
Amend team email address
Following migration from google accounts to Microsoft
`apply-for-civil-legal-aid@digital.justice.gov.uk` -->
`apply-for-civil-legal-aid@justice.gov.uk` …
=> Chore: Amend team email address

README.md, docs/clamav.md
Document latest Clamav implementation
[Link to story](https://dsdmoj.atlassian.net/browse/AP-6027)
Document how the clamav implementation is configured. …
=> Documentation: For Clamav implementation

helm_deploy/apply-for-legal-aid/values-production.yaml, helm_deploy/apply-for-legal-aid/values-staging.yaml
Switch on whitelist for staging and production
This enables whitesliting for stagin and production so if we remove the redirect
it will immeditaley be whitelisted nontheless. …
=> Chore: switch on whitelist for staging and production

app/controllers/feedback_controller.rb, app/views/feedback/thanks.html.erb, app/views/layouts/application.html.erb, config/locales/cy/feedback.yml, config/locales/en/feedback.yml, features/citizens/citizens.feature, features/providers/provider_feedback.feature, features/step_definitions/generic_steps.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-6060)
Open feedback in new tab
Indicate which feedback questions are optional
- You …
=> AP-6060: updates to feedback

helm_deploy/apply-for-legal-aid/templates/deployment_clamav.yaml
=> Allow one clamav pod to be deleted at a time

spec/presenters/task_list/section_spec.rb
One of the tests was leaking code into the RSpec outputs …
=> Fix: Remove text from test output

.env.sample, app/controllers/auth_controller.rb
Tweaks to omniauth branch
[Link to story](https://dsdmoj.atlassian.net/browse/AP-6125)
- **AP-6125: Amend env.sample's OMNIAUTH_ENTRAID_REDIRECT_URI**
- **AP-6125: Refactor auth controller failure**
- The PR description should say …
=> AP-6125: Tweaks to omniauth branch

helm_deploy/apply-for-legal-aid/values-production.yaml, helm_deploy/apply-for-legal-aid/values-staging.yaml
[Link to story](https://dsdmoj.atlassian.net/browse/AP-6045)
The credentials have been updated remotely, this updates the target URLs for prod, and non-prod, benefit checker instances …
=> AP-6045: Update URLs for new Benefit Checker

config/initializers/omniauth.rb
Update Entra prompt, to ensure correct account is already used …
=> Chore: Update entra prompt

app/javascript/src/dropzone.js
Sanitize dropzone response.
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2832)
Handles the last remaing snyk XSS warning - see [snyk analysis](https://app.snyk.io/org/legal-aid-agency/project/d9dcadca-a6f0-4663-94b6-68a9d843ad86). AI, at least, also recommends
sanitizing responses from dropzone. …
=> AP-2832: Sanitize dropzone response.

app/helpers/application_helper.rb, app/helpers/flow_helper.rb, app/views/providers/end_of_applications/show.html.erb, app/views/providers/review_and_print_applications/show.html.erb, app/views/providers/submitted_applications/show.html.erb, app/views/shared/forms/_next_action_buttons.html.erb, app/views/shared/review_application/_application_details.html.erb, app/views/shared/review_application/_questions_and_answers.html.erb, config/locales/en/providers.yml, config/locales/en/shared.yml, features/providers/check_ccms_autogrant.feature, features/providers/check_multiple_employment.feature, features/providers/check_nonpassport_autogrant.feature, features/providers/check_pending_employment.feature, features/providers/check_single_employment.feature, features/providers/merits_task_list.feature, features/providers/non_means_tested_journey/without_delegated_functions.feature, features/providers/passported_journey.feature, features/providers/review_and_print.feature, spec/helpers/application_helper_spec.rb, spec/helpers/flow_helper_spec.rb, spec/requests/providers/review_and_print_applications_controller_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-6230)
Update the following pages to match designs:
- `review_and_print_application`
- `end_of_application`
- `submitted_application` …
=> AP-6230: Update pages to match designs

.env.sample, app/controllers/admin_users/omniauth_callbacks_controller.rb, app/models/admin_user.rb, app/views/admin_users/sessions/new.html.erb, bin/deploy, config/initializers/omniauth.rb, config/locales/en/admin_users.yml, config/routes.rb, db/migrate/20250911153550_add_omni_auth_columns_to_admin_users.rb, db/schema.rb, features/step_definitions/admin_steps.rb, helm_deploy/apply-for-legal-aid/templates/_envs.tpl, helm_deploy/apply-for-legal-aid/values-production.yaml, helm_deploy/apply-for-legal-aid/values-staging.yaml, helm_deploy/apply-for-legal-aid/values-uat.yaml, spec/requests/admin_users/omniauth_callbacks_spec.rb, spec/requests/admin_users/sessions_controller_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-5739)
Add ability for admin users to log in via entra. …
=> Ap 5739 create admin entra login

app/views/providers/change_of_names_interrupts/_actions.html.erb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-6253)
Change button to link on interrupt …
=> AP-6253: Change button to link on interrupt

Gemfile, Gemfile.lock, config/application.rb, config/initializers/omniauth.rb, features/support/env.rb, helm_deploy/apply-for-legal-aid/templates/_envs.tpl
[Link to story](https://dsdmoj.atlassian.net/browse/AP-5741)
- Remove secrets
- Remove google oauth gem …
=> AP-5741: Remove google oauth

app/views/providers/link_application/confirm_links/show.html.erb, app/views/providers/link_application/copies/show.html.erb, app/views/shared/_all_linked_applications.html.erb, config/locales/en/providers.yml, config/locales/en/shared.yml
[Link to story](https://dsdmoj.atlassian.net/browse/AP-6264)
Created shared partial that can be shared by the confirm_links and copies pages.
- …
=> ap-6264: Add all_linked_applications to do you want to copy page
