- .github/workflows/delete-uat-release.yml
Bump GHA v1.0.1 to v1.0.2
corrects output values
> Bump laa-civil-apply-delete-uat-release v1.0.1 to v1.0.2

- app/views/providers/application_merits_task/statement_of_cases/show.html.erb
- config/locales/en/helpers.yml
Before, the label for the statement of case textarea input was generic. The accessibility audit highlighted that this could be confusing out of context, so this updates the label.
Now, the label is more descriptive and explicitly refers to the information that should be entered in the input.
<details>
<summary>Screenshot</summary>
</details>
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3202)
> Update statement of case textarea label

- app/views/providers/uploaded_evidence_collections/_uploaded_files.html.erb
- config/locales/en/providers.yml
[Add label to select component on evidence upload page](https://dsdmoj.atlassian.net/browse/AP-3199)
The select component does not have a programmatically determined label. Whilst screen reading software may attempt to generate a label from the name attribute this cannot be relied upon; additionally, out of context the select component will present as unlabelled. …
> [AP-3199] Add label to select component on evidence upload page

- .overcommit.yml
- app/views/admin/feedback/_feedbacks.erb
- app/views/admin/legal_aid_applications/_legal_aid_applications.html.erb
- app/views/admin/submitted_applications_reports/_submitted_applications.html.erb
- app/views/providers/legal_aid_applications/_legal_aid_applications.html.erb
- app/views/shared/partials/_pagination.html.erb
- app/webpack/stylesheets/pagination.scss
- spec/requests/admin/feedback_spec.rb
- spec/requests/admin/legal_aid_applications_controller_spec.rb
- spec/requests/admin/submitted_applications_reports_spec.rb
- spec/requests/providers/legal_aid_applications_spec.rb
[Use pagination component](https://dsdmoj.atlassian.net/browse/AP-3646)
Update existing pagination to use the GOV.UK Design System pagination component
[AP-3646]: …
> [AP-3646] Use govuk pagination component

- app/views/providers/means_reports/show.html.erb
- app/views/providers/merits_reports/show.html.erb
- app/views/shared/check_answers/_client_details.html.erb
- config/locales/cy/shared.yml
- config/locales/en/shared.yml
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3711)
Add the `Was the client means-tested?` question to the reports.  
Ensuring that it is not shown on the provider-facing pages, review and print pages, etc …
> AP-3711: Update Means and Merits report

- app/models/concerns/base_state_machine.rb
- spec/concerns/base_state_machine_spec.rb
- spec/factories/base_state_machines.rb
- spec/factories/legal_aid_applications.rb
Add a base state machine spec
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3629)
Was missing and there is quite a bit of logic that relies on this base state
machine. Some logic is tested in other state machine specs, some on over-riden
methods such as `legal_aid_application.applicant_details_checked!` or 
elsewhere(?). 
I have also added because it is otherwise possible to have faulty
code such as typos that is simply not exercised. …
> Add a base_state_machine spec

- .rubocop_todo.yml
These infractions were resolved in #4439, but never removed 
from the `.rubocop_todo.yml` configuration.
This removes the redundant configuration.
> Remove redundant rubocop_todo config

- .circleci/config.yml
Bump test executor postgres version 10.18 to 11.16
matching staging/production version.
> Bump test executor postgres version 10.18 to 11.16

- app/forms/vehicle_form/remaining_payment_form.rb
- app/views/providers/vehicles/remaining_payments/show.html.erb
- app/views/shared/check_answers/_vehicles.html.erb
- features/providers/check_your_answers.feature
- features/step_definitions/check_your_answers_steps.rb
- spec/requests/providers/vehicles/remaining_payments_spec.rb
Reverts ministryofjustice/laa-apply-for-legal-aid#4786
Since this was deployed yesterday, we have seen a number (11)
of `CFE::Submission` errors in production.
```
CFE::SubmissionError
Message: Unprocessable entity: URL: http://check-financial-eligibility.check-financial-eligibility-production.svc.cluster.local/assessments/5938f952-355d-49a9-8ab1-3e42908d5d7d/vehicles, details: The property ‘#/vehicles/0/loan_amount_outstanding’ of type null matched the disallowed schema in schema file:///myapp/public/schemas/common/currency
```
It looks like the schema in CFE does not allow `null` for the `loan_amount_outstanding` attribute.
This reverts the change.
> Revert "AP-3331 save vehicles remaining payments answer"

- app/models/concerns/translatable_model_attribute.rb
- app/views/feedback/new.html.erb
- spec/models/concerns/translatable_model_attribute_spec.rb
Before, the feedback page used the `.enum_radio_buttons` class method from the `TranslatableModelAttribute` concern to build options for the difficulty and satisfaction feedback questions.
While these provided a nice API for building the options, it added unnecessary complexity and opened cache-sized door of opportunity for bugs.
This was highlighted by the [flaky test] which started failing intermittently (but with very high frequency) since tests were broken down in #4852.
When the feedback form was completed in Welsh, the translations were cached and subsequent tests of the feedback form in English would fail because the "Easy" option was missing (it was "ysaE" instead).
This fixes the flaky test by replacing the use of `.enum_radio_buttons` with an inline translation lookup —removing …
> Fix flaky test

- spec/cassettes/Providers_AddressSelectionsController/GET_/providers/applications/_legal_aid_application_id/address_selections/edit/when_the_provider_is_authenticated/when_a_postcode_has_been_entered_before/but_the_lookup_does_not_return_any_valid_results/renders_the_manual_address_selection_page.yml
- spec/cassettes/Providers_AddressSelectionsController/GET_/providers/applications/_legal_aid_application_id/address_selections/edit/when_the_provider_is_authenticated/when_a_postcode_has_been_entered_before/performs_an_address_lookup_with_the_provided_postcode.yml
- spec/cassettes/Providers_AddressSelectionsController/GET_/providers/applications/_legal_aid_application_id/address_selections/edit/when_the_provider_is_authenticated/when_a_postcode_has_been_entered_before/renders_the_address_selection_page.yml
- spec/cassettes/Providers_ProceedingsTypesController/index_GET_/providers/applications/_legal_aid_application_id/proceedings_types/when_the_provider_is_authenticated/back_link/when_the_applicant_s_address_used_address_lookup_service/redirects_to_the_address_lookup_page.yml
- spec/services/address_lookup_service_spec.rb
- spec/spec_helper.rb
[Apply the correct spelling for Ordnance Survey](https://dsdmoj.atlassian.net/browse/AP-3762)
Not all references were updated in commit #6852f31
This new commit captures the remaining references
This will require devs to update their local .env file manually with the corrected spelling.
- …
> Correct spelling of Ordnance Survey

- app/models/hmrc/response.rb
- spec/workers/hmrc/result_worker_spec.rb
- spec/workers/hmrc/submission_worker_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3235)
This PR addresses the multiple `HMRC Response is unacceptable` errors from Sidekiq/HMRC::SubmissionWorker that are seen each day
It is caused by the implementation of the HMRC::ParsedResponse::Persistor being called from an after_update hook in the HMRC::Response model
- New hmrc_response is created and passed to an HMRC::SubmissionWorker job
- HMRC::SubmissionWorker requests an ID from the HMRC Interface,
- HMRC::SubmissionWorker updates the hmrc_response with a url and id
<-- persistor trying to validate response here and raising error -->
- HMRC::SubmissionWorker creates an HMRC::ResultWorker job
- HMRC::ResultWorker queries the HMRC Interface until a result is available
- HMRC::ResultWorker updates the hmrc_response with …
> AP-3235: Update HMRC response alerting

- app/controllers/providers/confirm_client_declarations_controller.rb
- app/forms/legal_aid_applications/confirm_client_declaration_form.rb
- app/views/providers/confirm_client_declarations/show.html.erb
- config/locales/en/activemodel.yml
- config/locales/en/providers.yml
- features/accessibility/provider.feature
- features/providers/check_ccms_autogrant.feature
- features/providers/check_multiple_employment.feature
- features/providers/check_nonpassport_autogrant.feature
- features/providers/check_pending_employment.feature
- features/providers/check_single_employment.feature
- features/providers/merits_task_list.feature
- features/providers/non_means_tested_journey/without_delegated_functions.feature
- features/providers/passported_journey.feature
- spec/forms/legal_aid_applications/confirm_client_declaration_form_spec.rb
- spec/requests/providers/confirm_client_declarations_controller_spec.rb
Once the means test review work has been completed, providers 
will be able to apply for legal aid on the behalf of clients under the
age of 18.
This change means the wording of the declaration needs to be
different depending on whether the applicant is under the age of
18 or not.
Currently, the concept of a `non_means_tested?` legal aid 
application is synonymous with an applicant being under the age
of 18 for the purposes of the means test (i.e 
`age_for_means_test_purposes < 18`).
I'm not convinced this coupling is particularly future-proof though
since there will likely be future scenarios where an application is 
not means tested, but the applicant is 18 or over.
I think it would be worthwhile the team thinking about whether this
is a problem worth solving now, or whether we should …
> Means test review declaration content changes

- app/views/shared/review_application/_questions_and_answers.html.erb
[Link to story](https://dsdmoj.atlassian.net/jira/software/c/projects/AP/boards/233?modal=detail&selectedIssue=AP-3224)
Only display the CCMS reference: heading if the application has a CCMS reference.
The question_and_answers partial is shared and the application might not yet have been submitted (and therefore might not yet have a CCMS reference). …
> ap-3224: Do not display CCMS reference if this doesn't yet exist

- config/locales/en/helpers.yml
This adds some clarifying hint text to the substantive cost limit request question when a provider selects "Yes" to request a higher substantive cost limit.
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3227)
> Add hint text when a new substantive cost limit is requested

- .github/dependabot.yml
- package.json
- yarn.lock
Puppeteer (and Chromium) are used by the Grover gem to generate PDF reports.
In development Puppeteer downloads the relevant Chromium version when installed, but we need to install Chromium separately in CircleCI and when building a docker image.
Since each Alpine image only supports a specific Chromium version, we need to install a specific version of Puppeteer.
If we want to use the same version across all environments (production, test, development), then we shouldn't update until we move to a new Alpine image.
This pins the version in `package.json` and ignores Puppeteer in the dependabot config.
> Ignore Puppeteer dependabot updates

- app/controllers/providers/confirm_dwp_non_passported_applications_controller.rb
- app/views/providers/confirm_dwp_non_passported_applications/show.html.erb
- config/locales/en/providers.yml
- features/accessibility/provider.feature
- features/providers/applicant_details.feature
- features/providers/change_email.feature
- features/providers/non_means_tested_journey/under_18_application_with_means_test_review_phase_one_disabled.feature
- features/providers/non_passported_journey/used_delegated_functions.feature
- features/providers/non_passported_journey/waiting_for_applicant.feature
- features/providers/passported_journey.feature
- features/providers/pathways_from_check_your_answers.feature
- spec/requests/providers/confirm_dwp_non_passported_applications_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3569)
Move radios below the blue interruption panel, this also fixes the error messaging so it displays correctly.
This design also matches crime apply
> Update DWP results page

- app/services/ccms/manual_review_determiner.rb
- spec/services/ccms/manual_review_determiner_spec.rb
Removed a couple of TODOs left over from [AP-3338](https://dsdmoj.atlassian.net/browse/AP-3338)
Re-enabled a spec for manual_review_required? for applications with bank statements uploaded in manaul_review_determiner_spec.
Also removed conditional if statement in manual_review_determiner testing if application has uploaded bank statements. I believe this is no longer required as applications with uploaded bank statements are now assessed by CFE and receive a CFE result in the same way as other applications.
Tested that the CFE result page is the same for applications with uploaded bank statements before and after the change. …
> Reenable manual_review_determiner spec

- app/models/application_digest.rb
- app/models/legal_aid_application.rb
- app/services/digest_exporter.rb
- app/services/reports/mis/application_detail_csv_line.rb
- db/migrate/20230131084513_add_banking_paths_to_application_digest.rb
- db/schema.rb
- spec/services/digest_exporter_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3442)
In order for the team to monitor and track the different banking journey paths we need to record whether a non passported application has started the bank statement uploads or Truelayer journey
This PR adds field to the digest, for datastudio tracking, and admin report output for excel analysis …
> AP-3442: Monitor banking path usage

- helm_deploy/apply-for-legal-aid/templates/deployment_web.yaml
Update clamav build to latest available
Pin to most recent tagged version, rather than use `latest` for
testing and stability reasons.
see available tags
https://github.com/ministryofjustice/hmpps-tools-images/pkgs/container/hmpps-clamav …
> Update clamav image to most recent build

- config/sidekiq.yml
- spec/services/metrics/sidekiq_queue_sizes_spec.rb
We removed the sidekiq-alive gem in Nov 2021 #2823 This should have been removed at the same time!
> Fix: Remove sidekiq-alive queue

- features/support/env.rb
When running cucumber there is a Selenium deprecation warning 
This PR updates the config as described
> Tech-debt: Update capybara config

- spec/forms/applicants/basic_details_form_spec.rb
Amend and extend DoB specs
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3782)
Came of investigating bug AP-3782
Previous use of `3.days.from_now`, which returns a Timestamp, in
the test was actually excercising an invalid date error. Actual behaviour
in the app for dates in the future is to raise date_is_in_future error
with message "Date of birth must be in the past". Replacing with
`Date.tomorrow` excercises the intended logic.
Extended tests to cover far in past dates too.
- The …
> [AP-3782] Tweak and extend application DoB specs

- app/services/digest_exporter.rb
- spec/services/digest_exporter_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3794)
This PR updates the generation of the digest
As data-studio requires a static sheet name of `Sheet1`, previously
this would delete rows and re-create, this has started to cause errors
where the header row would get overwritten and cause the data-studio to break
This now renames the current Sheet1 to `Archive` and the date it was
originally generated and recreates Sheet1 from scratch …
> AP-3794: Update digest-exporter

- app/services/digest_exporter.rb
- spec/services/digest_exporter_spec.rb
Reverts ministryofjustice/laa-apply-for-legal-aid#4951
The new code worked perfectly - a new sheet was created and populated 🎉 
Regrettably, the data-studio link is to an explicit worksheet, not the name as the config implies.
Therefore another approach is needed to replace this data each night 😞
> Revert "AP-3794: Update digest-exporter"

- config/govuk_notify_templates.yml
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3781)
Update the template ID for the citizen_start_application mailer
We are not using the ref_number field but sending it will not cause notify to break so retaining it, in case we change back to using it in the future …
> AP-3781: Update client truelayer notify email

- app/models/applicant.rb
- app/views/providers/check_provider_answers/_shared.html.erb
- app/views/shared/check_answers/_client_details.html.erb
- config/locales/cy/activemodel.yml
- config/locales/cy/shared.yml
- config/locales/en/activemodel.yml
- config/locales/en/shared.yml
- features/providers/non_passported_journey/waiting_for_applicant.feature
- spec/models/applicant_spec.rb
[Link to story](https://dsdmoj.atlassian.net/jira/software/c/projects/AP/boards/233?modal=detail&selectedIssue=AP-3472)
Added Employment status to the "Your application" page (the page the provider sees when clicking into the application while waiting for the client to finish their part). 
- …
> ap-3472: add employment status to your application

- app/models/applicant.rb
- lib/tasks/secure_data_migration.rake
- spec/models/applicant_spec.rb
Before, the bespoke `SecureData` pattern was used to store applicant TrueLayer tokens.
In #4967, a new `encrypted_true_layer_token` encrypted attribute was introduced, and data was written to it as part of the TrueLayer flow.
This adds a temporary idempotent task to copy encrypted token data to the new attribute, and updates existing methods to read from the new attribute if it is present.
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3743)
> Migrate applicant SecureData true layer tokens

- config/initializers/content_security_policy.rb
[Upgrade to Google Analytics 4](https://dsdmoj.atlassian.net/browse/AP-3549)
Update the google analytics glob to allow Google Analytics 4 subdomain to our content security policy in order to load GA4
GA4 is loaded via new subdomains of `regionx.google-analytics.com` Therefore GA4 connections are refused because it violates the Content Security Policy directives. …
> [AP-3549] Add Google Analytics 4 subdomain to our content security policy

- config/environments/production.rb
Before, urls passed to the mailer used the `http` protocol in all environments.
While these are canonically redirected to `https`, it is possible email clients might flag links as potentially unsafe or insecure.
Ideally we would update `config.action_mailer.default_url_options`, but we can't since we use a "Service object" pattern to send mail rather than leaning on ActionMailer.
> Use `https` protocol in mailer urls in Production

- app/models/benefit_type.rb
- config/locales/cy/activerecord.yml
- config/locales/en/activerecord.yml
The `benefit_types` table was dropped in #1105, but this model got left behind :(
> Remove redundant `BenefitType` model

- .circleci/config.yml
- docker/run
- docker/setup_db
Since Rails 6, the [`db:prepare` task][task] has provided a simple API for managing databases in Rails applications.
Running `bin/rails db:prepare` will prepare the database. This means
If the database does not exist:
1. Create the database
2. Load the schema if it exists, or run migrations
3. Seed the database
If the database exists already, then only migrations are run.
[task]: https://github.com/rails/rails/blob/9fcfbe5306cf632f5f47fa8bb5dfa36545ab1be6/activerecord/lib/active_record/tasks/database_tasks.rb#L188
> Use `rails db:prepare` to prepare the database

- db/migrate/20230215160839_remove_true_layer_secure_data_id_from_applicants.rb
- db/migrate/20230215161023_remove_token_from_bank_providers.rb
- db/migrate/20230215161035_remove_token_expires_at_from_bank_providers.rb
- db/schema.rb
In #4991, some TrueLayer related columns were ignored in the Applicant and BankProvider models.
Now that those columns are ignored, they can be safely removed from their respective tables.
> Remove ignored true layer columns

- app/models/applicant.rb
- app/models/bank_provider.rb
In #5001 these columns were removed.
We can stop ignoring them now!
> Stop ignoring removed columns

- app/models/legal_aid_application.rb
- db/migrate/20230217105228_add_citizen_url_id_to_legal_aid_applications.rb
- db/migrate/20230217111318_add_citizen_url_expires_on_to_legal_aid_applications.rb
- db/schema.rb
- spec/models/legal_aid_application_spec.rb
Similarly to #4967, we can use this new API to encrypt citizen URLs rather than our bespoke `SecureData` pattern.
This begins deterministically encrypting a random UUID that is stored against the LegalAidApplication alongside an expiry date.
The UUID is encrypted deterministically (rather than non-deterministically) so that applications can be queried by the `citizen_url_id` when requests are made to the Citizen application page.
A new `CITIZEN_URL_EXPIRES_AFTER_IN_DAYS` constant is used to define the number of days the URL is valid for.
For example, if the URL is generated on 2023-01-01, it will be valid for 7 days, expiring on the 8th day (i.e 2023-01-09).
This is consistent with the existing behaviour, although the implementation differs slightly.
Currently, if a URL is generated at …
> Use `ActiveRecord::Encryption` for citizen URLs

- config/application.rb
- config/environments/test.rb
- spec/services/citizen_email_service_spec.rb
- spec/services/provider_email_service_spec.rb
- spec/services/submit_application_reminder_service_spec.rb
- spec/services/submit_citizen_reminder_service_spec.rb
- spec/services/submit_provider_reminder_service_spec.rb
This config variable was added initially in #573 when we added smoke tests, and renamed in #2033 when those smoke tests were disabled.
The only reference to this config in application was removed in #2302, but the config was never removed.
This removes the config and updates references to it in tests.
> Remove `simulated_email_address` config

- app/models/citizen/access_token.rb
- app/models/legal_aid_application.rb
- db/anonymise/rules.rb
- db/migrate/20230221174503_create_citizen_access_tokens.rb
- db/schema.rb
- lib/tasks/migrate_citizen_urls.rake
- spec/factories/citizen/access_tokens.rb
- spec/models/citizen/access_token_spec.rb
- spec/models/legal_aid_application_spec.rb
In https://github.com/ministryofjustice/laa-apply-for-legal-aid/pull/5010 we started encrypting a `citizen_url_id` and storing it alongside the
date the corresponding Citizen application link would expire on the
`LegalAidApplication` model.
As work to migrate from the `SecureData` approach continued in https://github.com/ministryofjustice/laa-apply-for-legal-aid/pull/5018, a bug was
discovered in manual testing.
Rather than generating a token for the Citizen URL once and passing that around,
tokens are generated multiple times for an application in the process of sending
an email to the client.
This means there could be X different `SecureData` records in the database for
an application, and we don't know which correspond to links sent in emails to
Citizens.
In order to accommodate this …
> Introduce encrypted Citizen access tokens 

- db/migrate/20230223154933_remove_citizen_url_from_legal_aid_applications.rb
- db/schema.rb
The new approach taken in #5031 means these columns are no longer relevant and can be safely removed.
> Remove citizen URL columns

- app/models/legal_aid_application.rb
This columns were removed in #5032, so we can safely stop ignoring them now.
> Stop ignoring Citizen URL columns

- app/models/applicant.rb
- spec/models/applicant_spec.rb
- spec/requests/applicants/omniauth_callbacks_spec.rb
The `Applicant#true_layer_token_expires_at` method isn't called anywhere in the application.
We continue to capture this information in the `jsonb` token, but this removes the method that exposes it.
Perhaps we don't need to capture that data in the first place?
> Remove unused method

- db/anonymise/rules.rb
- db/migrate/20230228132829_update_opponent_fields.rb
- db/schema.rb
- lib/tasks/migrate_opponents.rake
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3873)
PR 2 of 2
This clears up after the first PR, it:
* removes the database columns from the opponent table
* removes some anonymisation rules that were no longer needed
* updates the migration script after some edge cases were found on production  …
> AP-3873: Opponent clear up

- app/services/reports/mis/application_detail_csv_line.rb
- spec/services/reports/mis/application_detail_csv_line_spec.rb
The previous update did not handle missing objects as gracefully as expected
> Fix: Admin report generation

- app/controllers/citizens/legal_aid_applications_controller.rb
- spec/requests/citizens/legal_aid_applications_controller_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3943)
When a citizen reaches the CYA page, the state of the application changes. If they close the browser and return later, the application tries to run the same starting code that involves resetting the state.  The state machine does not allow this and, even if it did, would mean they update their bank statements twice.
This checks for the change of state and routes them back to the CYA page
A ticket to investigate a proper save and return function for citizens will investigate a better long term solution 🤞 …
> AP-3943: Fix for citizens locked out of applications

- Gemfile
- Gemfile.lock
The new version of Devise includes support for Hotwire/Turbo.
We're not using Turbo, so we shouldn't need to change anything.
[Changelog](https://github.com/heartcombo/devise/blob/main/CHANGELOG.md#490---2023-02-17)
> Bump Devise to v4.9.0

- app/models/legal_aid_application.rb
- app/models/provider.rb
- app/services/flow/flows/provider_start.rb
- app/views/shared/check_answers/_student_finance.html.erb
- db/migrate/20200708102815_create_permissions_table.rb
- db/seeds/permissions.rb
- features/providers/applicant_details.feature
- features/step_definitions/bank_statement_upload_steps.rb
- features/step_definitions/check_your_answers_steps.rb
- features/step_definitions/means_report_steps.rb
- features/step_definitions/review_and_print_steps.rb
- spec/factories/permissions.rb
- spec/factories/providers.rb
- spec/models/legal_aid_application_spec.rb
- spec/models/provider_spec.rb
- spec/requests/providers/bank_statements_spec.rb
- spec/requests/providers/means/employed_incomes_spec.rb
- spec/requests/providers/means/full_employment_details_controller_spec.rb
- spec/requests/providers/means/student_finances_controller_spec.rb
- spec/requests/providers/no_eligibility_assessments_spec.rb
- spec/requests/providers/open_banking_consents_spec.rb
- spec/requests/providers/open_banking_guidances_controller_spec.rb
- spec/services/ccms/manual_review_determiner_spec.rb
- spec/services/cfe/submission_manager_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3896)
As part of a phased rollout a set of permissions was created, `application.non_passported.bank_statement_upload.*`, and granted to certain firms.
We now want everyone to be able to use this feature so we are removing the permissions completely so that all users will have access
This PR removes the permissions, factory traits, and code references.  When it is merged, _all_ providers will be able to upload bank statements for their clients …
> AP-3896: Remove bank statement upload restrictions

- app/models/concerns/non_passported_state_machine.rb
A state machine transition error was found on _all_ of the employed page when a user selected employed or none of the above
It could be bypassed by selecting self employed and returning but this allows the application to transition from `checking_applicant_details` to provider_confirm_applicant_eligibility` with no error …
> Fix: Error with bank uploads

- app/controllers/admin/ccms_queues_controller.rb
- app/models/ccms/submission.rb
- app/views/admin/ccms_queues/index.html.erb
- app/views/admin/ccms_queues/show.html.erb
- app/views/layouts/admin.html.erb
- config/locales/cy/layouts.yml
- config/locales/en/admin.yml
- config/locales/en/dates.yml
- config/locales/en/layouts.yml
- config/routes.rb
- spec/models/ccms/submission_spec.rb
- spec/requests/admin/ccms_queues_controller_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3915)
This proof of concept will, in its current form, allow admin users to assess the CCMS queue 
Currently, a developer has to access the console to monitor the steps that have been taken and then assess the next best steps 
The hope is that this is the first step in allowing a non-dev admin to see the current state and then re-start submissions
Index page
Individual submission page with both options expanded …
> AP-3915: Add CCMS queue analysis to admin

- Procfile.dev
Rather than defaulting to 3002, read the PORT=xxxx value from a local `.env` file or use 3002 as a fallback
This ensures that generated emails and script will work if a dev uses 3000, 4050, etc in their local .env file …
> Update: Allow the bin/div to read $PORT from .env

- app/controllers/providers/partner/client_has_partners_controller.rb
- app/forms/providers/partners/client_has_partner_form.rb
- app/models/applicant.rb
- app/models/legal_aid_application.rb
- app/services/flow/flows/provider_partner.rb
- app/services/flow/flows/provider_start.rb
- app/services/flow/provider_flow_service.rb
- app/views/providers/partner/client_has_partners/show.html.erb
- config/locales/en/activemodel.yml
- config/locales/en/providers.yml
- config/routes.rb
- db/migrate/20230320094303_add_has_partner_to_applicant.rb
- db/schema.rb
- spec/forms/providers/partners/client_has_partner_form_spec.rb
- spec/models/applicant_spec.rb
- spec/requests/providers/has_national_insurance_numbers_controller_spec.rb
- spec/requests/providers/partner/client_has_partners_controller_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3800)
This is the first step page in the partner means assessment flow
It adds a new page that follows the Does your client have a NINO question
A new value has been added to the applicant object (`has_partner`) that stores the response ti the question.  It is expected that this will be used later in flows and assessments as a quick check of the application (and applicant) status
Because we won't store a `has_partner` value until the flag is turned on a default attribute is set using 
```ruby
attribute :has_partner, default: -> { Setting.partner_means_assessment? ? nil : false }
```
rather than a default value at the DB level that will pre-populate the page when testing the new page
The pattern was taken from the [Andy …
> AP-3800: Client has a partner question

- app/controllers/concerns/providers/pre_dwp_check_visible.rb
- app/controllers/providers/address_lookups_controller.rb
- app/controllers/providers/address_selections_controller.rb
- app/controllers/providers/addresses_controller.rb
- app/controllers/providers/applicant_details_controller.rb
- app/controllers/providers/check_benefits_controller.rb
- app/controllers/providers/check_provider_answers_controller.rb
- app/controllers/providers/has_national_insurance_numbers_controller.rb
- app/controllers/providers/limitations_controller.rb
- app/controllers/providers/partner/client_has_partners_controller.rb
- app/controllers/providers/proceeding_loop/client_involvement_type_controller.rb
- app/controllers/providers/proceeding_loop/delegated_functions_controller.rb
- app/controllers/providers/proceeding_loop/emergency_defaults_controller.rb
- app/controllers/providers/proceeding_loop/final_hearings_controller.rb
- app/controllers/providers/proceeding_loop/substantive_defaults_controller.rb
- app/controllers/providers/proceedings_types_controller.rb
- spec/requests/providers/address_lookups_spec.rb
- spec/requests/providers/address_selections_spec.rb
- spec/requests/providers/applicant_details_spec.rb
- spec/requests/providers/check_benefits_spec.rb
- spec/requests/providers/check_provider_answers_spec.rb
- spec/requests/providers/has_national_insurance_numbers_controller_spec.rb
- spec/requests/providers/limitations_spec.rb
- spec/requests/providers/proceedings_types_spec.rb
This module was included in lots of controllers, but the method it includes isn't used anywhere.
The module was introduced in #1583, but the last remaining usage of the `pre_dwp_check?` method was removed as part of #4699.
This removes the module and associated tests.
> Remove redundant module

- app/controllers/providers/proceeding_merits_task/prohibited_steps_controller.rb
- app/forms/providers/proceeding_merits_task/prohibited_steps_form.rb
- app/views/providers/proceeding_merits_task/prohibited_steps/show.html.erb
- config/locales/en/activemodel.yml
- config/locales/en/providers.yml
- db/migrate/20230330155942_add_confirmed_not_change_of_name_to_prohibited_steps.rb
- db/schema.rb
- spec/forms/providers/proceeding_merits_task/prohibited_steps_form_spec.rb
- spec/requests/providers/proceeding_merits_task/prohibited_steps_controller_spec.rb
This adds a confirmation checkbox to the prohibited steps step of the proceeding task list, similarly to the specific issue question.
This should act as a speedbump for providers when submitting an application, to ensure that they do not try to submit an application for a prohibited steps proceeding when they are trying to submit a change of name application.
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3911)
> Confirm prohibited steps is not for change of name

- app/views/shared/check_answers/_client_details.html.erb
The new govuk style displays were displaying change links on the review and print applications page as well as the CYA page.  
This could allow providers to change data after submission
This update uses the read_only method to hide the actions column …
> Fix: Update Check your answer actions handling

- package.json
Silence 29 repetitive deprecation warnings
Example:
Deprecation Warning: Using / for division outside of calc() is deprecated.
More info: https://sass-lang.com/d/slash-div
Deprecation Warning: $weight: Passing a number without unit % (60) is deprecated.
More info: https://sass-lang.com/d/function-units …
> Sass: silence deprecation warnings

- spec/factories/applicants.rb
- spec/factories/providers.rb
- spec/factories/scheduled_mailings.rb
- spec/forms/applicants/email_form_spec.rb
- spec/mailers/citizen_completed_means_mailer_spec.rb
- spec/mailers/citizen_confirmation_mailer_spec.rb
- spec/mailers/notify_mailer_spec.rb
- spec/mailers/submit_application_reminder_mailer_spec.rb
- spec/mailers/submit_citizen_financial_reminder_mailer_spec.rb
- spec/mailers/submit_provider_financial_reminder_mailer_spec.rb
- spec/models/scheduled_mailing_spec.rb
- spec/requests/providers/applicant_details_spec.rb
- spec/requests/providers/email_addresses_spec.rb
After the Faker 3.2.0 update we were seeing a lot of:
```NOTE: Faker::Internet.safe_email is deprecated; use email instead. It will be removed on or after 2023-10.```
warnings
This PR should remove them
> Fix: Faker safe_email deprecation warnings

- .circleci/config.yml
The `rails assets:precompile` in unit tests takes <10s but in integration tests it was taking 2m+
This PR resequences the integration test steps - precompile now runs before installing chromedrivers, etc
> Fix: Speed up CircleCI integration test steps

- .github/dependabot.yml
This is to prevent failures when servers are shutdown overnight
> Fix: Update dependabot time

- app/controllers/concerns/providers/draftable.rb
- app/controllers/providers/check_provider_answers_controller.rb
- app/controllers/providers/partners/shared_addresses_controller.rb
- app/models/partner.rb
- app/services/flow/flows/provider_partner.rb
- app/services/flow/flows/provider_start.rb
- app/views/providers/check_provider_answers/_shared.html.erb
- app/views/providers/check_provider_answers/index.html.erb
- app/views/providers/means_reports/show.html.erb
- app/views/providers/merits_reports/show.html.erb
- app/views/shared/check_answers/_client_details.html.erb
- app/views/shared/check_answers/_partner_details.html.erb
- app/views/shared/review_application/_questions_and_answers.html.erb
- config/locales/en/shared.yml
- features/cassettes/partner_means_assessment_check_your_answers/I_am_able_to_add_a_partner_with_an_address_shared_with_the_applicant_and_then_change_it.yml
- features/providers/partner_means_assessment/check_your_answers.feature
- features/step_definitions/civil_journey_steps.rb
- spec/factories/applicants.rb
- spec/models/partner_spec.rb
- spec/requests/providers/check_provider_answers_spec.rb
- spec/requests/providers/partners/shared_addresses_controller_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3802)
Implement the check your answers page for the Partner details pages
This also adds minor tweaks to the client pages as there was some repetition and conflicts when having two `Change first name` aria links …
> AP-3802: Implement check your answers for partner details

- app/views/citizens/consents/show.html.erb
- app/views/providers/limitations/_proceeding_type.html.erb
- app/views/providers/open_banking_guidances/show.html.erb
- app/views/shared/forms/_types_of_income_form.html.erb
- app/views/shared/forms/_types_of_outgoings_form.html.erb
- config/locales/cy/shared.yml
- config/locales/en/shared.yml
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3642)
Use GOV.UK components library to render all instances of the details component
Also removed some code in the types_of_income and types_of_outgoings forms which was no longer used as the citizen is not asked questions about payment types anymore
***I rebased on @agoldstone93 's  AP-3991 summary list component branch so that's why there are so many changes showing at the moment*** …
> AP-3642 details component

- app/services/cfe/compare_results.rb
- app/services/cfe/compare_submission.rb
- app/services/cfe_civil/submission_builder.rb
- spec/services/cfe/compare_results_spec.rb
- spec/services/cfe/compare_submission_spec.rb
Following discussions with Eligibility Platform for more data to help diagnose issues...
Refactor CFECivil::SubmissionBuilder to use each_with_object pattern
Refactor CFE::CompareResults to instantiate and call the submission builder separately 
Refactor CFE::CompareSubmission to output extra fields in a more human-readable format …
> Update cfe comparison

- app/controllers/providers/delete_controller.rb
- spec/requests/providers/delete_controller_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4039)
The non-js delete controller was mistakenly deleted as part of the JS modal delete implementation.  
This PR simply restores the files deleted as part of #3165 and updates them inline with recent rubocop changes …
> AP-4039: Fix non-js application delete

- app/services/cfe_civil/components/employments.rb
- spec/services/cfe_civil/components/employments_spec.rb
Ensure data types are consistent
Populated data is returned with `.to_json` the empty version should be too
> Update: CFE Comparison

- app/views/providers/application_merits_task/statement_of_cases/show.html.erb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3231)
Moved `uploaded_files` partial outside form to fix bug
> AP-3231: Uploading multiple files on the statement of case page with JS disabled

- app/services/cfe_civil/components/outgoings.rb
- spec/services/cfe_civil/components/outgoings_spec.rb
CFE-Civil requires a valid housing_cost_type when submitting transactions flagged as rent_or_mortgage, this feeds into a calculation for board and lodging that was never implemented into Apply and has been ignored by CFE Legacy.
This implements the correct logic and can be expanded if the correct board and lodging handling is implemented in the future …
> Update CFECivil handling of outgoings

- app/services/cfe_civil/components/irregular_incomes.rb
- spec/services/cfe_civil/components/irregular_incomes_spec.rb
The combined endpoint requires the `payments` object to be nested inside a `irregular_incomes` block
> Update: CFE-Civil irregular income submissions

- README.md
- helm_deploy/apply-for-legal-aid/README.md
Updated the README.md with details of 1Password instead of LastPass since we are no longer using LastPass.
> Update README.md to replace LastPass with 1Password

- docker/apply_ci.dockerfile
Add `--no-install-recommends` flag to `apt` in dockerfile to prevent unnecessary packages from being installed, thereby reducing possible attack vectors and reducing bloatware in Docker.
See [We reduced our Docker images by 60% with –no-install-recommends](https://ubuntu.com/blog/we-reduced-our-docker-images-by-60-with-no-install-recommends) …
> chore: use `--no-install-recommends` flag to `apt` in dockerfile

- app/models/concerns/base_state_machine.rb
When we have turned off CCMS Submission there is usually a small number of queued submissions to restart.  After a significant outage we may want to try submitting one or two applications first before opening the floodgates.
This allows a developer to open a terminal window and start a rails console session that will allow some applications to be processed individually
Open a rails console with
```shell
LOCAL_CCMS_OVERRIDE=true rails c
```
Then you can find an application and
```ruby
@applications = LegalAidApplication.joins(:state_machine).
where(state_machine_proxies: { aasm_state: "submission_paused" }).
order(:created_at)
laa.first.restart_submission!
``` …
> Fix: Allow a CCMS Submission when the flag is off

- app/assets/stylesheets/govuk-mods.scss
- app/helpers/application_helper.rb
- app/views/citizens/legal_aid_applications/index.html.erb
- app/views/providers/legal_aid_applications/index.html.erb
- app/views/providers/start/index.html.erb
[Use start button helper](https://dsdmoj.atlassian.net/browse/AP-3648)
Update views to use the start button helper from the govuk-components gem
Identify and remove redundant code related to the start button component …
> [AP-3648] Use start button helper

- helm_deploy/apply-for-legal-aid/templates/deployment_worker.yaml
This came out of a conversation with @Obsiye around issues seen on CCCD
There is a chance that, as the deployment_worker pods share a label with the deployment_web pods,it causes routing issues that raise 502 errors on production.
This is because kubernetes sees the two types of pod as the same and tries to route web queries to a sidekiq pod that cannot respond to a Rails-based web request.
This PR adds a specific suffix to the worker pods so that kubernetes can route the requests correctly.
This has been tested on UAT and email requests were successfully sent, this means that the worker pods are still linked, and running, successfully.
The only way of testing _full_ success is to deploy to production and see if the number of 502 errors reduces.
I will set up a google sheet to track the …
> Fix: Update MatchLabel with worker Suffix for sidekiq pods

- app/javascript/src/cookie_banner.js
- app/views/shared/partials/_cookie_banner.html.erb
- config/locales/en/shared.yml
- features/providers/cookies.feature
[Use cookie banner helper](https://dsdmoj.atlassian.net/browse/AP-3641)
Update cookie banner view, `govuk_cookie_banner` accepts multiple message component, message component used for the accept/reject actions.
Update locales to reflect translation change
Cookie helper now uses links instead of buttons, JS module updated to reflect change …
> [AP-3641] Use cookie banner helper

- app/controllers/admin/ccms_queues_controller.rb
A 500 error is being recorded everytime an admin visits the ccms_queue/show page
There is no error in the logs, but a 500 response is shown on kibana
I cannot trace any reason for this, but the `authenticate_admin_user!` method is being called twice, once explicitly in this controller and again in the inherited AdminBaseController
That seems a bit superfluous, so I am removing this one to see if it is causing the issue …
> Fix: CCMS Queue errors

- app/services/cfe_civil/components/assessment.rb
- spec/services/cfe_civil/components/assessment_spec.rb
There are two `level of help` options in CFE-Civil, `certificated` and `controlled`
The schema documentation says that `certificated` is the default and Apply should always be certificated but, just in case that ever changes, this ensures we send the correct value each time.
Controlled = Provider does not apply for Legal Aid - they self grant.
Civil Apply's scope is only for certificated applications
- …
> CFE-Civil handling

- app/services/cfe/store_compare_result.rb
- spec/services/cfe/store_compare_result_spec.rb
Previously, if the data sheet was left filtered the tool would find the last "complete" row and then add 1 to the number and export. If the sheet had 4000 rows and the last filtered row was 3001, the tool would export to 3002 onwards, overwriting previous records
This PR ensures that any filters on the data sheet are cleared before exporting further data …
> CFE: Update Spreadsheet Comparison

- app/views/shared/check_answers/_benefits_breakdown.html.erb
- spec/cassettes/CFECivil_SubmissionBuilder/_call/when_HostEnv_is_not_set/still_generates_the_expected_JSON_but_uses_missing_in_the_header.yml
- spec/cassettes/CFECivil_SubmissionBuilder/_call/when_not_saving_the_result/does_not_create_a_submission_history_object.yml
- spec/cassettes/CFECivil_SubmissionBuilder/_call/when_not_saving_the_result/does_not_save_a_submission_object.yml
- spec/cassettes/CFECivil_SubmissionBuilder/_call/when_not_saving_the_result/generates_the_expected_JSON.yml
- spec/cassettes/CFECivil_SubmissionBuilder/_call/when_saving_the_result/does_not_create_a_submission_history_object.yml
- spec/cassettes/CFECivil_SubmissionBuilder/_call/when_saving_the_result/does_not_save_a_submission_object.yml
- spec/cassettes/CFECivil_SubmissionBuilder/_call/when_saving_the_result/generates_the_expected_JSON.yml
- spec/services/cfe_civil/submission_builder_spec.rb
The benefit changes were intended to roll out as a single hit, but some providers pause before submitting.  
We have seen, so far, at least one application that has a state benefit without a description.
This fix will allow that application to complete, generate a means report, and be submitted to CCMS.  it should allow applications in a similar state to proceed as well …
> Fix: Benefit breakdown view

- app/services/cfe/compare_results.rb
- app/services/cfe/reset_google_sheet_filter.rb
- app/services/cfe/shared_google_sheet.rb
- app/services/cfe/store_compare_result.rb
- spec/services/cfe/compare_results_spec.rb
- spec/services/cfe/reset_google_sheet_filter_spec.rb
- spec/services/cfe/store_compare_result_spec.rb
The overnight comparison tool has been erroring and looping because of the number of API calls to google sheets 
I added a method of clearing the filter but it was being called on each line addition, in retrospect it should only be called once, at the start of the run, and this PR implements that.
This code is still quite inefficient, but should only be running for another two weeks until we cut over permanently …
> CFE: Comparison sheet filter update

- app/services/cfe/compare_submission.rb
- spec/fixtures/files/cfe_civil_comparison/v5/employment_mismatch.json
- spec/fixtures/files/cfe_civil_comparison/v6/employment_mismatch.json
- spec/services/cfe/compare_submission_spec.rb
The handling of employment has changed in CFE Civil this has been accepted and we no longer send empty employment blocks to the new version unless actual pay is included.
In this instance, there were two empty employment
blocks so Legacy adds multiple employment remarks
but Civil has no employments and adds no remarks
This adds an override handler so it will add an
observation to the comparison spreadsheet for
review and, ultimately, to be ignored …
> Fix: Update CFE Comparison

- bin/install_clamav_on_mac
- spec/services/malware_scanner_spec.rb
Proposition to change the clamav install script, plus tests
- Change clamav install script to use TCP instead of LocalSocket configuration
- Add  more specific test for virus definition
This comes out of work on laa-assure-hmrc-data that identified false positive tests resulting from
failure to communicate with local clamav resulting in virsu_found? returning true, not because there
was a virus but because the scan returned an error.
The fix for assure was, firstly to ensure the tests fail for the right reason (a virus was found or not) and
secondly to amend the clamav install script to configure clamav to function as it does in a production like
environment - namely the App's clamav "client" communicates with the clamav "server" over TCP on localhost:3310.
**Pros IMO:**
1. it functions …
> Change anti-virus script and tests

- .env.sample
- README.md
- app/services/malware_scanner.rb
- config/application.rb
- spec/services/malware_scanner_spec.rb
Remove use of LOCAL_CLAMAV
The bin/install_clamav_on_mac was altered to install and
configure local claim to use TCP instead of Local[unix]Socket
This means local clamav server and client should work in the same way
as the production clamav server client - namely itwill use the
`clamd.container.conf` settings for TCP.
Therefore we do not need, and should no longer use, the LOCAL_CLAMAV var
and its assoicated command which uses `--fdpass` (for improved speed?!).
```
--fdpass
Pass the file descriptor permissions to clamd. This is useful if clamd is
running as a different user as it is faster than streaming the file to clamd.
Only available if connected to clamd via local(unix) socket.
```
- …
> Remove use of LOCAL_CLAMAV

- helm_deploy/apply-for-legal-aid/templates/cronjob-admin-report.yaml
- helm_deploy/apply-for-legal-aid/templates/cronjob-db-backup-cleanup.yaml
- helm_deploy/apply-for-legal-aid/templates/cronjob-deliver-scheduled-mail.yaml
- helm_deploy/apply-for-legal-aid/templates/cronjob-destroy-purgeable.yaml
- helm_deploy/apply-for-legal-aid/templates/cronjob-export-digest.yaml
- helm_deploy/apply-for-legal-aid/templates/cronjob-extract-digest.yaml
- helm_deploy/apply-for-legal-aid/templates/cronjob-hourly-db-backup.yaml
- helm_deploy/apply-for-legal-aid/templates/cronjob-mark-purgeable.yaml
- helm_deploy/apply-for-legal-aid/templates/cronjob-metrics.yaml
- helm_deploy/apply-for-legal-aid/templates/cronjob-reset-dashboard-overnight.yaml
- helm_deploy/apply-for-legal-aid/templates/deployment_metrics.yaml
Following the work Abdi presented at Dev COP and previous attempt at updating pod idenifiers to reduce 502 errors.
We previously added identifiers to the worker pods, but we still see a number of 502 errors during the day, matching the exact pattern shown on their slides, two IP addresses.
This adds explicit cron tags to all the cron jobs in case they run at a time where a user is trying to use the service, e.g. db backups, scheduled mails, etc.
This will probably cause issues when merging and deploying and with in-progress branches, shoult and I will help you merge and rebase as needed :+1:
- There …
> Fix: Reduce 502 errors on pods

- scripts/db_export.sh
The download anonymised DB export often failed with an `EOF` issue
This allows the `cp` command to retry
It has been tested locally and allows the download to restart multiple times and still allow the file to completely download and restore …
> Fix: Update DB export

- app/models/applicant.rb
- app/models/hmrc/response.rb
- app/models/partner.rb
- app/services/hmrc/create_responses_service.rb
- db/migrate/20230628085216_add_owner_to_hmrc_responses.rb
- db/schema.rb
- lib/tasks/migrate_hmrc_responses.rake
- spec/factory_specs/hmrc_response/use_case_one_helper_spec.rb
- spec/models/hmrc/response_spec.rb
- spec/models/legal_aid_application_spec.rb
- spec/requests/providers/means/full_employment_details_controller_spec.rb
- spec/services/cfe/create_employments_service_spec.rb
- spec/services/hmrc/create_responses_service_spec.rb
- spec/services/hmrc/interface/result_service_spec.rb
- spec/services/hmrc/interface/submission_service_spec.rb
- spec/services/hmrc/mock_interface_response_service_spec.rb
- spec/services/hmrc/parsed_response/persistor_spec.rb
- spec/services/hmrc/parsed_response/validator_spec.rb
- spec/workers/hmrc/result_worker_spec.rb
- spec/workers/hmrc/submission_worker_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3805)
Altered the HMRC responses table and model so a HMRC response can now belong to _either_ an applicant object or a partner object. At the moment all responses will belong to an applicant and the partner HMRC response functionality will be added in a future PR.
The existing relation to a legal_aid_application is left as is
- Added a polymorphic column 'owner' to the hmrc_responses table
- Added ActiveRecord has_many hmrc_responses associations to Applicant and Partner 
- Added a rake task to update existing hmrc_responses and set the owner to the applicant
- Updated the HMRC create_responses_service to add the applicant as owner when a new response is created
- Tests and rubocop should be …
> AP-3805 Update HMRC Responses to have owner 

- app/models/applicant.rb
- app/models/employment.rb
- app/models/partner.rb
- app/services/hmrc/parsed_response/persistor.rb
- db/migrate/20230703102937_add_owner_to_employment.rb
- db/schema.rb
- features/step_definitions/bank_statement_upload_steps.rb
- features/step_definitions/check_your_answers_steps.rb
- features/step_definitions/civil_journey_steps.rb
- lib/tasks/migrate_employments.rake
- spec/factories/legal_aid_applications.rb
- spec/models/hmrc/response_spec.rb
- spec/models/legal_aid_application_spec.rb
- spec/requests/providers/means/employed_incomes_spec.rb
- spec/requests/providers/means/full_employment_details_controller_spec.rb
- spec/requests/providers/means/unexpected_employed_incomes_spec.rb
- spec/services/cfe/create_employments_service_spec.rb
- spec/services/cfe_civil/components/employments_spec.rb
- spec/services/hmrc/parsed_response/persistor_spec.rb
- spec/services/hmrc/status_analyzer_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3805)
Update Employment model and DB table to have owner as a polymorphic column. 
The owner will be either the applicant or partner. At the moment the owner is just the applicant.
Added rake task to set owner of all existing employments to the applicant.
Updated rspecs and feature tests to create the employment object with an owner
NB: At the moment all employments have to be explicitly created in each setup step for rspec/features by passing the owner (in all cases the applicant right now). There is probably a more efficient way of doing this but I couldn't figure it out. It would be ideal if in the employment factory the owner could be created/added there, but the three-way dependency between LegalAidApplication, Employment, and …
> AP-3805 Part 2 add owner to employments

- app/models/cfe/submission.rb
These are not being deleted when the owning cfe_submission is deleted by its owner, the legal_aid_application.
This has been tested on a local instance and ensures that deleting a legal_aid_appliation now destroys the linked cfe_result …
> Fix: Update CFE::BaseResult ownership

- .circleci/config.yml
- bin/uat_deploy
Amend config to push to new ECR repo which uses IRSA and lifecycle policy
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4293)
- Add command to build and push to new ECR repo using IRSA
- Replace ECR_ENDPOINT with ECR_REGISTRY
- Amend ECR repo to pull from
- Remove GITHUB_TEAM_NAME_SLUG envvar
- Remove unneeded ECR login
- Remove almost duplicate step for UAT
See this [cloud platform environments PR](https://github.com/ministryofjustice/cloud-platform-environments/pull/14533) that creates the new ECR repo with IRSA for circleci and adds a lifecycle policy relating to [AP-4294](https://dsdmoj.atlassian.net/browse/AP-4294)
Once merged then [AP-4294](https://github.com/ministryofjustice/laa-apply-for-legal-aid/pull/5472) can be too and the following vars can be removed from circleci …
> AP-4293: Use new ECR repo with IRSA for push

- app/models/partner.rb
- app/services/hmrc/create_responses_service.rb
- app/services/hmrc/interface/submission_service.rb
- app/services/hmrc/mock_interface_response_service.rb
- app/services/hmrc/parsed_response/persistor.rb
- app/services/hmrc/parsed_response/validator.rb
- app/views/admin/legal_aid_applications/submissions/show.html.erb
- features/step_definitions/partner_means_check.rb
- spec/services/cfe_civil/components/employments_spec.rb
- spec/services/hmrc/create_responses_service_spec.rb
- spec/services/hmrc/interface/submission_service_spec.rb
- spec/services/hmrc/mock_interface_response_service_spec.rb
- spec/services/hmrc/parsed_response/validator_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3805)
Part 3 of the ticket to allow HMRC requests for partners
This switches `HMRC::CreateResponsesService` and `HMRC::MockInterfaceResponseService` to parse the owner of the `HMRC::Response` object, whether it is an Applicant or Partner. …
> AP-3805: HRMC request for partner

- docker-compose.yml
Replace laa-apply-for-legal-aid/clamav with ministryofjustice/hmpps-clamav for docker-compose
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4321)
Remove reference to old, archived and unused clamav image.
The old clamav is archived and not used any longer, plus its ECR repo is to be deleted. This
updates to use the same exact image and commit as production.
I also:
1. updated postgres to production version
2. changed to use the docker/run script as bin/run no longer exists
see cloud-platform-environments PR to [remove clamav ECR repo](https://github.com/ministryofjustice/cloud-platform-environments/pull/14563)
- Github should not be reporting conflicts; you should have recently run …
> AP-4321: Replace references to unused/maintained clamav images

- docker-compose.yml
- helm_deploy/apply-for-legal-aid/templates/deployment_web.yaml
Bump anti virus softare, [hmpps-clamav](https://github.com/ministryofjustice/hmpps-utility-container-images/pkgs/container/hmpps-clamav), to latest version
From sha-0ae98e9 to sha-ae9a953
I have UAT'd an upload of malware with successful blocking. …
> Bump hmpps-clamav to latest commit shah

- helm_deploy/apply-for-legal-aid/templates/cronjob-admin-report.yaml
- helm_deploy/apply-for-legal-aid/templates/cronjob-deliver-scheduled-mail.yaml
- helm_deploy/apply-for-legal-aid/templates/cronjob-destroy-purgeable.yaml
- helm_deploy/apply-for-legal-aid/templates/cronjob-export-digest.yaml
- helm_deploy/apply-for-legal-aid/templates/cronjob-extract-digest.yaml
- helm_deploy/apply-for-legal-aid/templates/cronjob-mark-purgeable.yaml
- helm_deploy/apply-for-legal-aid/templates/cronjob-metrics.yaml
- helm_deploy/apply-for-legal-aid/templates/cronjob-reset-dashboard-overnight.yaml
Add short lived credentials service account name to all cronjobs
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4323)
If jobs need access to AWS resources, such as S3, they will
require the IRSA credentials.
Adding to all cronjobs is just a precaution that matches
previous long lived credential provision via secrets.
I tested this on UAT and it fixes the daily admin report
**job completion**
**file uploaded** …
> AP-4323: Add short lived credentials service account name to all cronjobs

- app/controllers/providers/application_merits_task/remove_involved_child_controller.rb
- app/controllers/providers/application_merits_task/remove_opponent_controller.rb
- app/controllers/providers/means/remove_dependants_controller.rb
- app/models/concerns/binary_choice_form.rb
- app/views/providers/application_merits_task/remove_involved_child/show.html.erb
- app/views/providers/application_merits_task/remove_opponent/show.html.erb
- app/views/providers/capital_introductions/show.html.erb
- config/locales/en/providers.yml
- features/providers/merits_task_list.feature
- features/providers/non_passported_journey/with_dependants.feature
- spec/requests/providers/application_merits_task/remove_involved_child_spec.rb
- spec/requests/providers/means/remove_dependant_controller_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4033)
Update headings and error messages on remove_dependant and remove_involved_child pages to make them consistent and to include the name of the person to be removed
Both these pages use the BinaryChoiceForm so it requires changing this slightly to accept an error message, so the name could be passed into the form …
> AP-4033 make child error messages and headings consistent

- app/models/applicant.rb
- app/services/flow/flows/provider_start.rb
- app/views/providers/start/index.html.erb
- config/locales/en/providers.yml
- features/cassettes/Applicant_under_16_blocked_before_and_after_MTR_phase_one_enabled/I_am_instructed_to_use_CCMS_when_applicant_was_under_16_on_earliest_delegated_function_date_with_MTR_phase_one_disabled.yml
- features/cassettes/Applicant_under_16_blocked_before_and_after_MTR_phase_one_enabled/I_am_instructed_to_use_CCMS_when_applicant_was_under_16_on_earliest_delegated_function_date_with_MTR_phase_one_enabled.yml
- features/providers/applicant_under_16_blocked.feature
- spec/models/applicant_spec.rb
- spec/models/legal_aid_application_spec.rb
- spec/requests/providers/check_provider_answers_spec.rb
Warn and block under 16s post MTR phase one too
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4343)
Under 16s will not be able to use the service even after MTR phase
one goes live. This is because they must provide linked cases information
as a minimum and this is not yet implemented. Instead we need to redirect
their providers to CCMS. …
> AP-4343: warn and redirect under 16s to CCMS post MTR phase one

- db/anonymise/rules.rb
- db/migrate/20230720124309_create_individuals.rb
- db/migrate/20230720125540_add_opposable_to_opponents.rb
- db/schema.rb
Add database structures necessary to migrate opponents to polymorphic individual opponents
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4284)
-  Create individuals table
-  Add opposable to opponents table, but null values allowed
First part of database changes required to migrate opponents to being a polymorphic
relationship, so that we can extend opponents to include organisations
- You …
> AP-4284: Add db structure for polymorphic opponent individuals

- .circleci/config.yml
- features/support/env.rb
- Temporarily fix chromedriver at v114 when running locally to allow cucumber feature tests to run without failing, due to this issue: https://github.com/titusfortner/webdrivers/issues/247
- Fix chromedriver at v112 in CircleCI as this is the only version that seems to be working at the moment. I tried fixing the version to v114 in circle in the CircleCI `config.yml` [using this guidance](https://circleci.com/developer/orbs/orb/circleci/browser-tools#commands-install-chrome) but it didn't work
There is a ticket in the backlog to come up with a more long term fix: https://dsdmoj.atlassian.net/browse/AP-4345
- Github should not be reporting conflicts; you should have recently run `git rebase …
> Fix chromedriver at v114

- scripts/db_export.sh
The suggested script shown to the user restores the file to the local DB but the internal metadata leaves the DB flagged as production.  This can cause issues if the user wants to reset or rebuild their local DB.
This PR adds the `&& rails db:environment:set RAILS_ENV=development` command to the psql restore line.  This ensures rails is set to be in development mode when the database is successfully restored …
> Fix: DB Export clear production flag on restore

- db/anonymise/rules.rb
This occurred a few times when it was set up and I had not noticed the recurrence, or needed to use the affected tables
This adds an explanation to the anonymizer ruleset and updates the two affected tables
> Fix: Opponent bug in anonymizer

- spec/requests/providers/means/remove_dependant_controller_spec.rb
This test failed locally when a name with an apostrophe was generated by faker.  Using the html_compare helper removes the chance of it happening again
> Fix: Flickering test

- db/anonymise/rules.rb
Remove linebreak from opponents#last_name rule
Breaks dump file's opponents COPY command by forcing
a linebreak mid record
> Remove linebreak from opponents#last_name rule

- app/views/providers/means/full_employment_details/show.html.erb
- config/locales/en/shared.yml
- features/providers/partner_means_assessment/bank_statement_upload/uploading_files.feature
- spec/factories/applicants.rb
- spec/factories/legal_aid_applications.rb
- spec/requests/providers/means/full_employment_details_controller_spec.rb
- spec/requests/providers/partners/full_employment_details_controller_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4346)
- Add applicant no NI number page
- Update heading for partner's no data page - previously incorrectly said 'client'
> AP-4346: create no NI page for client

- helm_deploy/apply-for-legal-aid/templates/deployment_web.yaml
This is the workaround proposed for puma dropping requests while the K8s pod shuts down
> Fix: Update web deploy with shell sleep

- app/views/providers/means/identify_types_of_incomes/show.html.erb
- app/views/providers/means/identify_types_of_outgoings/show.html.erb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3194)
This was applying the same error tag to _all_ transactions this applies the same pattern seen on the regular_* pages
Set the first input to be marked as an error so the standard error block at the top of the page has a target to link to while still allowing the listing of checkboxes for accessibility users …
> AP-3194: Update error handling in line with DAC review

- .rubocop_todo.yml
- spec/services/ccms/attribute_configuration_spec.rb
- spec/services/ccms/attribute_value_generator_spec.rb
- spec/services/ccms/manual_review_determiner_spec.rb
- spec/services/ccms/parsers/applicant_add_response_parser_spec.rb
- spec/services/ccms/parsers/applicant_search_response_parser_spec.rb
- spec/services/ccms/parsers/case_add_response_parser_spec.rb
- spec/services/ccms/parsers/case_add_status_response_parser_spec.rb
- spec/services/ccms/parsers/document_id_response_parser_spec.rb
- spec/services/ccms/parsers/reference_data_response_parser_spec.rb
- spec/services/ccms/payload_generators/entity_attributes_generator_spec.rb
- spec/services/ccms/requestors/case_add_requestor_xml_blocks/non_passported_additional_property_attributes_spec.rb
- spec/services/ccms/requestors/case_add_requestor_xml_blocks/non_passported_benefits_attrs_spec.rb
- spec/services/ccms/requestors/case_add_requestor_xml_blocks/non_passported_dependant_child_attributes_spec.rb
- spec/services/ccms/submitters/add_applicant_service_spec.rb
- spec/services/ccms/submitters/add_case_service_spec.rb
- spec/services/ccms/submitters/check_applicant_status_service_spec.rb
- spec/services/ccms/submitters/check_case_status_service_spec.rb
- spec/services/ccms/submitters/obtain_applicant_reference_service_spec.rb
- spec/services/ccms/submitters/obtain_case_reference_service_spec.rb
- spec/services/ccms/submitters/obtain_document_id_service_spec.rb
- spec/services/ccms/submitters/upload_documents_service_spec.rb
Start addressing the context exclusions in the CCMS namespace, remove another 106 infractions
> Rubocop: Address RSpec/ContextWording exclusions in CCMS tests

- app/views/citizens/accounts/index.html.erb
[Use table component](https://dsdmoj.atlassian.net/browse/AP-3650)
Update all citizen views to use GOVUK Table component
> [AP-3650] Apply GOVUK Table component to citizen views

- app/views/admin/ccms_queues/index.html.erb
- app/views/admin/feedback/_feedbacks.erb
- app/views/admin/firms/index.html.erb
- app/views/admin/legal_aid_applications/_legal_aid_applications.html.erb
- app/views/admin/providers/index.html.erb
- app/views/admin/reports/index.html.erb
- app/views/admin/submitted_applications_reports/_submitted_applications.html.erb
- config/locales/en/admin.yml
[Use table component](https://dsdmoj.atlassian.net/browse/AP-3650)
Update all admin views to use GOVUK Table component
> [AP-3650] Apply GOVUK Table component to admin views

- .rubocop_todo.yml
- spec/services/ccms/requestors/case_add_requestor_xml_blocks/non_passported_attributes_spec.rb
Address the issues in spec/services/ccms/requestors/case_add_requestor_xml_blocks/non_passported_attributes_spec.rb
This also had some weirdly nested tests that I have flattened but this makes it harder to review
> Rubocop: reduce RSpec/ContextWording exclusions

- app/services/ccms/parsers/reference_data_response_parser.rb
- spec/data/ccms/reference_data_response_error.xml
- spec/services/ccms/parsers/reference_data_response_parser_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-2509)
Ensure an error is raised if CCMS returns the case_ccms_reference as `ERROR`
Add a new xml response block replicating a live response that failed so we can test the situation …
> AP-2509: Improve error handling when case_ccms_reference is ERROR

- app/helpers/opponent_helper.rb
- app/views/providers/application_merits_task/has_other_opponents/show.html.erb
- app/views/shared/check_answers/_opponent_details.html.erb
- spec/helpers/opponent_helper_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4304)
Amended opponent details on CYA page to match sigma designs
- Renamed opponent_url_helper -> opponent_helper in order to use it as a helper for opponent views more generally.
- Added opponent_type_description function to opponent_helper
- Used opponent_type_description to display opponents as required in ticket on Check your answers page (I believe this has also automatically updated the merits report to display opponent organisations correctly as they share the same view) …
> ap-4304: amend opponent_details cya

- app/services/flow/flows/provider_start.rb
- features/cassettes/Using_the_back_button_on_proceedings_should_not_lock_a_user_out/When_a_provider_is_adding_proceedings_and_uses_the_back_button_they_should_route_to_the_list_of_proceedings_first.yml
- features/providers/regressions/back_button_on_proceedings.feature
When users use the back button to move back past the proceedings search page they get stuck having to
search again.  If they have already added the single proceeding they need, this is very counter intuitive.
This PR matches the newer, add another, implementations and skips to the 'list and add another proceeding' page
It has been checked with the design team and they are happy with the change to the flow …
> AP-4374: Update proceeding flow

- app/models/application_merits_task/opponent.rb
- spec/models/application_merits_task/opponent_spec.rb
Ignore unneeded `opponents` model attributes as prelude to dropping
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4350)
Following migration to using opponent individuals and
organisations via a polymorphic relation these attributes
are no longer needed.
There will be a follow up PR to remove/drop the opponents.first_name and opponents.last_name columns in a migration. This follows the [strong_migrations style for removing columns](https://github.com/ankane/strong_migrations#removing-a-column) …
> AP-4350: Ignore unneeded opponent model attributes

- .rubocop_todo.yml
- spec/services/ccms/requestors/case_add_requestor_xml_blocks/passported_attributes_spec.rb
Address the issues in spec/services/ccms/requestors/case_add_requestor_xml_blocks/non_passported_entities_spec.rb
This removes the RSpec/ContextWording block from rubocop_todo
> Rubocop: Remove RSpec/ContextWording exclusions

- db/migrate/20230815072458_remove_first_name_last_name_from_opponents.rb
- db/schema.rb
Drop the first_name and last_name attributes from opponents
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4350)
Second part of removal of unneeded attributes following
move to using individuals as a polymorphic relation - [first PR](https://github.com/ministryofjustice/laa-apply-for-legal-aid/pull/5617).
A third PR will remove the ignore_columns from opponents model, following [strong_migrations removing column style](https://github.com/ankane/strong_migrations#removing-a-column).
- …
> AP-4350: Drop first_name, last_name from opponents

- app/views/providers/open_banking_guidances/show.html.erb
- app/views/providers/proceeding_loop/client_involvement_type/show.html.erb
- app/views/providers/proceeding_loop/confirm_delegated_functions_date/show.html.erb
- app/views/providers/proceeding_loop/delegated_functions/show.html.erb
- app/views/providers/proceeding_loop/emergency_defaults/show.html.erb
- app/views/providers/proceeding_loop/emergency_level_of_service/show.html.erb
- app/views/providers/proceeding_loop/emergency_scope_limitations/show.html.erb
- app/views/providers/proceeding_loop/final_hearings/show.html.erb
- app/views/providers/proceeding_loop/substantive_defaults/show.html.erb
- app/views/providers/proceeding_loop/substantive_level_of_service/show.html.erb
- app/views/providers/proceeding_loop/substantive_scope_limitations/show.html.erb
- app/views/shared/state_benefits/_add_other_state_benefits.html.erb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4196)
Changed the caption class suffix (eg ‘-xl’) so that it matches the heading class.
> Add caption class suffix to match corresponding heading class

- db/anonymise/rules.rb
- lib/tasks/db.rake
Anonymise `chances_of_successes#success_prospect_details` during dump
Because this field may contain sensitive information
Also, amend the connect details mechanism for anonymised database dumping
I have tested this by performing a database dump both locally with rails `db:export` and via the script
on the branch and both work. The `chances_of_successes#success_prospect_details` is anonymised only
when it is not null. …
> Anonymise success prospect details

- app/controllers/providers/means/cash_incomes_controller.rb
- app/controllers/providers/means/cash_outgoings_controller.rb
- app/models/base_aggregated_cash_transaction.rb
- app/models/cash_transaction.rb
- db/migrate/20230821070336_add_owner_to_cash_transaction.rb
- db/schema.rb
- lib/tasks/migrate_cash_transaction_ownership.rake
- spec/factories/legal_aid_applications.rb
- spec/forms/providers/means/regular_income_form_spec.rb
- spec/forms/providers/means/regular_outgoings_form_spec.rb
- spec/models/aggregated_cash_income_spec.rb
- spec/models/aggregated_cash_outgoings_spec.rb
- spec/models/cash_transaction_spec.rb
- spec/models/legal_aid_application_transaction_type_spec.rb
- spec/requests/providers/means/cash_incomes_controller_spec.rb
- spec/requests/providers/means/cash_outgoings_controller_spec.rb
- spec/requests/providers/means/identify_types_of_incomes_controller_spec.rb
- spec/requests/providers/means/identify_types_of_outgoings_controller_spec.rb
- spec/services/cfe_civil/components/cash_transactions_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4285)
Set ownership of the cash transactions, this will ease work on AP-4106 too
Ensure that all controller, forms and tests set the Applicant as the owner of existing Cash Transactions, this will allow us to extend it to Partner in 4285 and 4106
Add a migration rake task to update existing records …
> AP-4285: Set cash transaction ownership

- .circleci/config.yml
This was added a while ago because of a change to Ubuntu, circle jobs started failing one day because the `ffi` package wasn't installed any more... that was two years ago
Try removing it to see if it is still required as a stand-alone step …
> Fix: Remove FFI from Circle CI lint executor

- spec/requests/providers/application_merits_task/remove_involved_child_spec.rb
When checking the passing of a name to the translation helper we should use unescaped_response_body so that, when faker generates a name with an apostrophe, the html is unescaped
> Fix: Update flaky RemoveInvolvedChildController test

- app/controllers/providers/means/cash_incomes_controller.rb
- app/controllers/providers/means/cash_outgoings_controller.rb
- app/models/base_aggregated_cash_transaction.rb
- db/migrate/20230822111710_change_cash_transaction_index.rb
- db/schema.rb
- spec/models/aggregated_cash_income_spec.rb
- spec/models/aggregated_cash_outgoings_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4285)
During the work to set up partner cash transactions another stumbling block has been identified.
The current handling loads _all_cash transactions and deletes them on changing.
This PR adds filters for ownership and ensures that only the correct transactions are handled by a controller.
It also means updating the DB index to ensure the uniqueness accounts for ownership too …
> AP-4285: Update cash transaction handling

- app/forms/providers/application_merits_task/domestic_abuse_summary_form.rb
- app/views/shared/check_answers/_opponent_details.html.erb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4411)
Update code to correctly show warning_letter_sent rather than understand_terms_of_court_order. Fix issue whereby warning_letter_sent_details were not clearing correctly …
> AP-4411: Fix incorrectly displaying warning letter sent info

- .github/dependabot.yml
Rather than have two npm dependabot PRs for jest and jest-environment-jsdom try and get them grouped together to reduce circle runs when the first is merged and the second has to be rebased
Also, late addition, try grouping the aws-* PRs for the same reason …
> Test: Group Jest dependencies together in dependabot

- app/views/providers/means/cash_incomes/show.html.erb
- config/locales/en/providers.yml
- features/providers/bank_statement_upload/check_your_means_answers.feature
- features/providers/bank_statement_upload/happy_path_journey.feature
- features/providers/check_multiple_employment.feature
- features/providers/check_nonpassport_autogrant.feature
- features/providers/check_pending_employment.feature
- features/providers/check_single_employment.feature
- features/providers/complete_and_check_means_answers.feature
- features/providers/non_passported_journey/with_bank_transactions.feature
- features/providers/partner_means_assessment/end_to_end_income_assessment.feature
- features/providers/partner_means_assessment/means_check.feature
While working on the partner cash payments I had a discussion with a content designer who requested this change to bring the page in line with other pages being developed and updated
I separated this out from AP-4285 as it was bloating the number of files changed and was confusing to read through …
> Refactor: Client cash income checkbox

- app/controllers/providers/means/identify_types_of_incomes_controller.rb
- app/controllers/providers/means/identify_types_of_outgoings_controller.rb
- spec/requests/providers/means/identify_types_of_incomes_controller_spec.rb
- spec/requests/providers/means/identify_types_of_outgoings_controller_spec.rb
While working on AP-4285, I found another pattern for creating LegalAidApplicationTransactionType records in the DB
This fix ensures that the truelayer client controllers are creating the record with ownership so that tests will pass and Client records will not 'drift' onto the pages of Partners …
> Fix: Ensure truelayer transactions set ownership too

- app/services/flow/flows/provider_income.rb
- spec/requests/providers/income_summary_controller_spec.rb
If an application is created where they have a partner but have not set any outgoing payments, the flow skips straight to dependants when it should move to the partner start income page.
> Fix: Partner routing after income summary

- app/controllers/providers/means/cash_incomes_controller.rb
- app/controllers/providers/partners/cash_incomes_controller.rb
- app/models/legal_aid_application.rb
- app/services/flow/flows/provider_partner.rb
- app/views/providers/means/cash_incomes/show.html.erb
- app/views/providers/partners/cash_incomes/show.html.erb
- app/views/shared/means/_cash_income.html.erb
- config/locales/en/providers.yml
- config/locales/en/shared.yml
- config/routes.rb
- features/providers/partner_means_assessment/end_to_end_income_assessment.feature
- features/support/steps_helper.rb
- spec/requests/providers/means/cash_incomes_controller_spec.rb
- spec/requests/providers/partners/cash_incomes_controller_spec.rb
- spec/requests/providers/partners/regular_incomes_controller_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4285)
This adds the cash payments handling to the partner flow.
It duplicates the client pages and refactors the view to reduce the duplication
> AP-4285: Partner cash payments

- app/services/reports/mis/application_detail_csv_line.rb
A while ago #5630 removed some code around gateway evidence because we believed it was obsolete.  The admin report generator still had a reference to a deleted method.  This replaces the CSV generator with the internal structure of the deleted method …
> Fix: GatewayEvidence count in admin report

- app/controllers/v1/providers_controller.rb
- app/helpers/cookie_banner_helper.rb
- app/views/layouts/_header.html.erb
- db/migrate/20230821163930_add_cookie_timestamp_to_provider.rb
- db/schema.rb
- features/providers/cookies.feature
- features/step_definitions/cookie_steps.rb
- spec/helpers/cookie_banner_helper_spec.rb
- spec/requests/providers/legal_aid_applications_spec.rb
- spec/requests/v1/providers_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3212)
Store user cookie preferences for a year only.
> AP-3212:Set user cookie duration for 1 year

- app/forms/providers/regular_transaction_form.rb
- features/providers/partner_means_assessment/end_to_end_income_assessment.feature
- features/support/steps_helper.rb
- spec/forms/providers/means/housing_benefit_form_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4425)
Extend the feature test to ensure that cash transactions from the client are not included in the partner page generation
> AP-4425: Fix CashTransaction handling client/partner separation

- .rubocop_todo.yml
- spec/services/ccms/attribute_configuration_spec.rb
- spec/services/ccms/manual_review_determiner_spec.rb
- spec/services/ccms/parsers/applicant_add_response_parser_spec.rb
- spec/services/ccms/requestors/applicant_add_requestor_spec.rb
- spec/services/ccms/requestors/applicant_add_status_requestor_spec.rb
- spec/services/ccms/requestors/applicant_search_requestor_spec.rb
- spec/services/ccms/requestors/case_add_requestor_spec.rb
- spec/services/ccms/requestors/case_add_requestor_xml_blocks/passported_attributes_spec.rb
- spec/services/ccms/requestors/case_add_status_requestor_spec.rb
- spec/services/ccms/requestors/document_id_requestor_spec.rb
- spec/services/ccms/requestors/document_upload_requestor_spec.rb
- spec/services/ccms/requestors/reference_data_requestor_spec.rb
- spec/services/ccms/restart_submissions_spec.rb
- spec/services/ccms/submitters/add_applicant_service_spec.rb
- spec/services/ccms/submitters/add_case_service_spec.rb
- spec/services/ccms/submitters/check_applicant_status_service_spec.rb
- spec/services/ccms/submitters/obtain_applicant_reference_service_spec.rb
- spec/services/ccms/submitters/obtain_case_reference_service_spec.rb
- spec/services/ccms/submitters/obtain_document_id_service_spec.rb
- spec/services/ccms/submitters/upload_documents_service_spec.rb
As we are about to ramp up work in the CCMS namespace I wanted to try and remove some of the rubocop infractions we've been ignoring!
This addresses the issues with:
* RSpec/NamedSubject
* RSpec/ExpectInHook
If this gets approved while I'm away, please merge.
Also, please bear in mind the number of offences we currently ignore in the services/CCMS area when extending or duplicating tests! 
- You should …
> Rubocop: services/CCMS fixes

- app/models/application_merits_task/opponent.rb
- app/models/application_merits_task/organisation.rb
- db/migrate/20230905133536_rename_organisations_columns.rb
- db/schema.rb
- spec/forms/opponents/organisation_form_spec.rb
- spec/models/application_merits_task/organisation_spec.rb
Rename organisations#ccms_code and organisations#description
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4399)
These names are clearer descriptions of their data content and
purpose as well as what is currently returned from LFA's
organisation endpoints. …
> AP-4399: Rename organisation columns part 2

- .github/dependabot.yml
Group Babel and Stylelint dependencies together, thereby creating a single PR for related dependencies instead of many
[Dependabot grouping feature in public beta](https://github.blog/changelog/2023-06-30-grouped-version-updates-for-dependabot-public-beta/) …
> chore: group npm dependencies in dependabot

- app/controllers/providers/partners/employed_controller.rb
- app/models/concerns/base_state_machine.rb
- app/models/concerns/non_passported_state_machine.rb
- spec/requests/providers/partners/employed_controller_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4449)
Add valid state transitions between use_ccms and assessing_partner_means states, and add spec
> AP-4449 fix states for partner employment page

- .snyk
We are currently getting [CWE-226](https://security.snyk.io/vuln/SNYK-GOLANG-GOLANGORGXSYSUNIX-3310442) alerts while using esbuild in our container
This is due to the esbuild maintainers fixing the golang version to v0.0.0
see:
https://github.com/evanw/esbuild/commit/fd13718c6195afb9e63682476a774fa6d4483be0
https://github.com/evanw/esbuild/pull/3254
https://github.com/evanw/esbuild/pull/3248
As we cannot resolve this ourselves, we will ignore it for the next 6 months …
> chore: snyk ignore (temporarily) golang.org CWE-226

- docker/apply_base.dockerfile
This was added so that the DB backup jobs could be run as a cronjob.  
As the DB jobs have been removed, this setup is no longer needed.
This should speed up the build and deploy steps as well as reducing the docker image size …
> Update: Remove kubectl from Dockerfile

- .sonarcloud.properties
Exclude cassettes from analysis
There is a 400 character limit on directory/file name lengths
in sonarcloud. Cassettes do not need to be analysed and because
cassette names and dirs are automatically generated by VCR based
on spec file names and example/scenario descriptions these names can
up up being very long.
[Came out of story](https://dsdmoj.atlassian.net/browse/AP-4399) …
> Sonarcloud: exclude cassettes from analysis

- db/migrate/20230911120457_update_legal_framework_merits_task_list_foreign_key.rb
- db/migrate/20230912082919_validate_legal_framework_merits_task_list_fk.rb
- db/schema.rb
The overnight purge job had been failing because the LegalFrameworkMeritsTaskList was not being cascade deleted.  This PR updates the foreign key link between the two models and has been tested with an anonymised DB backup.
Before the fix, the job failed with the same error seen in production. After the fix it successfully completed
- You should …
> AP-4441: Fix the overnight purge job

- .rubocop_todo.yml
- spec/models/legal_aid_application_spec.rb
- spec/requests/feedbacks_spec.rb
- spec/services/ccms/requestors/case_add_requestor_xml_blocks/non_passported_variable_attributes_spec.rb
- spec/services/reports/mis/application_detail_csv_line_spec.rb
- spec/services/required_document_category_analyser_spec.rb
- spec/services/true_layer/importers/import_accounts_service_spec.rb
These occur when a spec is configured as
```ruby
let(:something) { create(:something) }
let(:something) { create(:something, :with_trait) }
```
and usually occur in long complex test files.
This PR removes the occurrences of duplicated `let`s and ensured the tests passed before committing
- …
> Rubocop: Address RSpec/OverwritingSetup infractions

- .rubocop_todo.yml
- spec/models/application_merits_task/involved_child_spec.rb
- spec/models/dashboard/widget_spec.rb
- spec/models/legal_aid_application_spec.rb
- spec/requests/citizens/gather_transactions_spec.rb
- spec/services/bank_holiday_retriever_service_spec.rb
- spec/services/provider_after_login_service_spec.rb
- spec/services/reports/mis/application_details_report_spec.rb
- spec/services/true_layer/api_client_mock_spec.rb
In a before hook, we should only use `allow` to set an required response. If we actually "expect" something, it should be in an `it` test block
> Rubocop: Remove RSpec/ExpectInHook exclusions

- app/controllers/providers/capital_introductions_controller.rb
- app/services/flow/flows/provider_income.rb
- app/views/providers/capital_introductions/show.html.erb
- app/views/shared/check_answers/_income_cash_payments.html.erb
- app/views/shared/check_answers/_outgoings_cash_payments.html.erb
- config/locales/en/providers.yml
- features/providers/check_multiple_employment.feature
- features/providers/check_nonpassport_autogrant.feature
- features/providers/check_pending_employment.feature
- features/providers/check_single_employment.feature
- features/providers/complete_and_check_means_answers.feature
- features/providers/non_passported_journey/with_capital.feature
- features/providers/non_passported_journey/with_dependants.feature
- features/providers/non_passported_journey/with_means.feature
- features/providers/partner_means_assessment/end_to_end_income_assessment.feature
- spec/requests/providers/capital_introductions_controller_spec.rb
- spec/requests/providers/means/check_income_answers_controller_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4128)
Add capital introductions page to the non-passported flow, show conditional content based on whether or not the application has a partner, and remove the merits list items
Update rspecs …
> AP-4128 partner capital introductions page

- app/controllers/providers/means/has_dependants_controller.rb
- app/controllers/providers/means/has_other_dependants_controller.rb
- app/forms/legal_aid_applications/has_dependants_form.rb
- app/views/providers/means/has_dependants/show.html.erb
- app/views/providers/means/has_other_dependants/show.html.erb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4442)
One did not have it at all, the other was conditional reverting to false.  It was agreed that these should _always_ be present, so this PR sets the value to always be true on both pages …
> AP-4442: Ensure dependant pages show save as draft button

- app/views/admin/legal_aid_applications/submissions/show.html.erb
- app/views/providers/transactions/show.html.erb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4379)
Replaced `<summary class="govuk-details__summary"` with the `govuk_details` component throughout the code base.
> Ap 4379/use details helper

- .rubocop_todo.yml
- spec/requests/providers/address_lookups_controller_spec.rb
- spec/requests/providers/address_selections_controller_spec.rb
- spec/requests/providers/addresses_spec.rb
- spec/requests/providers/applicant_bank_accounts_controller_spec.rb
- spec/requests/providers/applicant_details_controller_spec.rb
- spec/requests/providers/application_confirmations_spec.rb
- spec/requests/providers/application_dependable_spec.rb
- spec/requests/providers/application_merits_task/date_client_told_incidents_spec.rb
- spec/requests/providers/application_merits_task/has_other_involved_children_spec.rb
- spec/requests/providers/application_merits_task/involved_children_spec.rb
- spec/requests/providers/application_merits_task/remove_involved_child_spec.rb
- spec/requests/providers/application_merits_task/statement_of_case_spec.rb
- spec/requests/providers/bank_transactions_controller_spec.rb
Address the exclusions in the folders in `spec/requests/providers/` starting with `a` and `b`
> Rubocop: address RSpec/NamedSubject exclusions

- .rubocop_todo.yml
- spec/requests/providers/capital_assessment_results_controller_spec.rb
- spec/requests/providers/capital_income_assessment_results_controller_spec.rb
- spec/requests/providers/check_benefits_controller_spec.rb
- spec/requests/providers/check_client_details_controller_spec.rb
- spec/requests/providers/check_merits_answers_spec.rb
- spec/requests/providers/check_passported_answers_spec.rb
- spec/requests/providers/check_provider_answers_controller_spec.rb
- spec/requests/providers/client_completed_means_controller_spec.rb
- spec/requests/providers/concerns/providers/draftable_spec.rb
- spec/requests/providers/confirm_dwp_non_passported_applications_controller_spec.rb
- spec/requests/providers/confirm_offices_spec.rb
- spec/requests/providers/delegated_confirmation_controller_spec.rb
- spec/requests/providers/email_addresses_spec.rb
- spec/requests/providers/end_of_applications_controller_spec.rb
- spec/requests/providers/has_evidence_of_benefits_controller_spec.rb
- spec/requests/providers/has_other_proceedings_controller_spec.rb
- spec/requests/providers/income_summary_controller_spec.rb
- spec/requests/providers/legal_aid_applications_spec.rb
- spec/requests/providers/limitations_controller_spec.rb
Address the exclusions in the folders in `spec/requests/providers/` starting `c` to `l`
> Rubocop: Address more NamedSubject exclusions

- app/helpers/admin_helper.rb
- app/helpers/flow_helper.rb
- app/helpers/language_switcher_helper.rb
- app/helpers/providers_helper.rb
- app/views/accessibility_statement/index.html.erb
- app/views/admin/ccms_queues/show.html.erb
- app/views/admin/firms/index.html.erb
- app/views/admin/legal_aid_applications/submissions/show.html.erb
- app/views/admin/reports/index.html.erb
- app/views/admin/user_dashboard/index.html.erb
- app/views/citizens/accounts/index.html.erb
- app/views/citizens/check_answers/_bank_accounts.html.erb
- app/views/citizens/gather_transactions/display_error.html.erb
- app/views/citizens/means_test_results/show.html.erb
- app/views/citizens/resend_link_requests/show.html.erb
- app/views/feedback/show.html.erb
- app/views/problem/index.html.erb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3655)
Replaced all instances of `link_to_accessible` with the `govuk_link_to` component in the helper, admin, citizens, feedback and problem files. 
> Ap 3655 use link helpers part 1

- app/controllers/providers/check_capital_answers_controller.rb
- app/controllers/providers/means/vehicle_details_controller.rb
- app/forms/vehicles/details_form.rb
- app/views/providers/means/vehicle_details/show.html.erb
- app/views/shared/check_answers/_assets.html.erb
- app/views/shared/check_answers/_vehicles.html.erb
- config/locales/en/activemodel.yml
- config/locales/en/providers.yml
- config/locales/en/shared.yml
- db/migrate/20230918144429_add_owner_to_vehicles.rb
- db/schema.rb
- features/providers/partner_means_assessment/end_to_end_capital_assessment.feature
- features/step_definitions/partner_means_check.rb
- lib/tasks/add_vehicle_ownership.rake
- spec/factories/vehicles.rb
- spec/forms/vehicles/details_form_spec.rb
- spec/requests/providers/check_capital_answers_controller_spec.rb
- spec/requests/providers/means/vehicle_details_controller_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4138)
Add owner question which is only displayed when applicant has a partner. When applicant has no partner, `owner` is set to 'client'. Add a rake task to update existing vehicles to have an owner set to 'client'
As vehicles can be owned by the applicant, the partner or both, the `owner` is a string value
To do: …
> AP-4138: Update partner vehicle questions

- .rubocop_todo.yml
- spec/requests/providers/select_offices_spec.rb
- spec/requests/providers/start_spec.rb
- spec/requests/providers/submitted_applications_controller_spec.rb
- spec/requests/providers/substantive_applications_controller_spec.rb
- spec/requests/providers/transactions_controller_spec.rb
- spec/requests/providers/uploaded_evidence_collection_spec.rb
- spec/requests/providers/use_ccms_controller_spec.rb
- spec/requests/saml_sessions_spec.rb
- spec/requests/v1/legal_aid_applications_spec.rb
- spec/requests/v1/statement_of_cases_spec.rb
- spec/requests/v1/uploaded_evidence_collections_spec.rb
- spec/requests/v1/workers_spec.rb
This addresses the final batch of request specs without named subjects, only leaving the service infractions
> Rubocop: Address remaining request RSpec/NamedSubject exclusions

- app/views/providers/means/vehicle_details/_form.html.erb
This seems to have been present for a while but only triggered today. I saw it on UAT and then shortly after on prod.
It occurs when a provider says `yes, payments remain` but then enter text, e.g. `n/a` into the field.  One of the handlers used `!= 0` and the other used `.zero?`.
`.zero?` fails when the value is a string but `.eql?(0)` works as expected
This PR updates both checks to use the same, working, style of check
`== 0` was tried but failed an erblint check suggesting `use .zero?` 🤔  …
> Fix: vehicle_detail error handling

- app/views/providers/means_reports/_with_bank_statement_uploads.html.erb
- app/views/providers/means_reports/_with_cfe_result_details.html.erb
There were two places where the call to the full_employment_details was not being passed the `individual` parameter.  This caused the means report generation to fail when there was a call to the employment block
> Fix: @individual parameter missing from partial

- app/views/shared/check_answers/_payments_summary.html.erb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4490)
Removed empty paragraph tag when income summary table contains value "None"
Example of issue: 
> AP-4490: Remove empty paragraph tag

- app/assets/stylesheets/application.scss
This got removed in a refactor and left the tables on the blue-box page looking a bit lop-sided
> Fix: css table styling

- features/providers/check_your_answers.feature
- features/providers/passported_journey.feature
- features/step_definitions/check_your_answers_steps.rb
- features/step_definitions/civil_journey_steps.rb
Amend step susceptible to false positives and use, correct or replace in features
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4468)
- Amend offending step to use within so as to prevent false positives
- Correct newly failing feature step call by correct the section name used
- Correct use of step for statement of case where expected text is not actually
connected to the DOM row, wrongly or rightly?!
- Add new step to allow CYA list items to exhausively check row questions and answers …
> AP-4468: Update feature step susceptible to false positives

- .rubocop_todo.yml
- spec/services/admin/provider_details_service_spec.rb
- spec/services/bank_holiday_retriever_service_spec.rb
- spec/services/banking/bank_transaction_balance_calculator_spec.rb
- spec/services/banking/bank_transactions_trimmer_spec.rb
- spec/services/banking/state_benefit_analyser_service_spec.rb
- spec/services/dashboard_event_handler_spec.rb
- spec/services/delegated_functions_date_service_spec.rb
- spec/services/flow/base_flow_service_spec.rb
- spec/services/flow/key_point_spec.rb
- spec/services/govuk_emails/delivery_man_spec.rb
- spec/services/job_queue_spec.rb
- spec/services/legal_framework/add_proceeding_service_spec.rb
- spec/services/legal_framework/lead_proceeding_assignment_service_spec.rb
- spec/services/malware_scanner_spec.rb
- spec/services/metrics/send_metrics_spec.rb
- spec/services/metrics/sidekiq_queue_sizes_spec.rb
- spec/services/mock_benefit_check_service_spec.rb
First of two PRs addressing RSpec/NamedSubject exclusions in the services folder
This addresses those in services where the folder or class starts with `a` to `m`
> Rubocop: Address RSpec/NamedSubjects in services

- .rubocop_todo.yml
- spec/services/page_history_service_spec.rb
- spec/services/pdf_converter_spec.rb
- spec/services/populators/transaction_type_populator_spec.rb
- spec/services/provider_after_login_service_spec.rb
- spec/services/provider_details_retriever_spec.rb
- spec/services/provider_email_service_spec.rb
- spec/services/reports/bank_transactions/bank_transaction_report_creator_spec.rb
- spec/services/reports/merits_report_creator_spec.rb
- spec/services/reports/mis/non_passported_application_csv_line_spec.rb
- spec/services/reports/reports_creator_spec.rb
- spec/services/required_document_category_analyser_spec.rb
- spec/services/submit_application_reminder_service_spec.rb
- spec/services/submit_provider_reminder_service_spec.rb
- spec/services/substantive_application_deadline_calculator_spec.rb
- spec/services/true_layer/api_client_mock_spec.rb
- spec/services/true_layer/banks_retriever_spec.rb
- spec/services/true_layer/importers/import_account_balance_service_spec.rb
- spec/services/true_layer/importers/import_account_holders_service_spec.rb
- spec/services/true_layer/importers/import_accounts_service_spec.rb
- spec/services/true_layer_error_decoder_spec.rb
This is the final PR addressing RSpec/NamedSubject exclusions.
It addresses those in services where the folder or class starts with n to x
It switches to using `subject(:call)` for brevity
- You should …
> Rubocop: Final removal of NamedSubject exclusions

- .simplecov
- lib/utilities/redis_scanner.rb
Add a Redis utitlity class
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4499)
Utility class for inspecting and cleaning up
redis keys. Came out of work looking at removing
the redis-namespace gem (AP-4499). …
> AP-4499: Add redis scanner utility class

- app/views/providers/confirm_client_declarations/show.html.erb
- app/views/providers/end_of_applications/show.html.erb
- app/views/providers/review_and_print_applications/show.html.erb
- app/views/shared/_partner_declaration.html.erb
- app/views/shared/review_application/_questions_and_answers.html.erb
- config/locales/en/providers.yml
- config/locales/en/shared.yml
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4018)
This adds partner variations for all the declaration displays.
It also includes changes documented in [AP-4038](https://dsdmoj.atlassian.net/browse/AP-4038) to make the client declaration first person as it meant changing the same page at the same time. …
> AP-4018: Update declarations

- .rubocop_todo.yml
- spec/forms/legal_aid_applications/substantive_application_form_spec.rb
- spec/models/cfe/v2/result_spec.rb
- spec/models/cfe/v3/result_spec.rb
- spec/models/dependant_spec.rb
- spec/services/ccms/requestors/case_add_requestor_xml_blocks/passported_attributes_spec.rb
- spec/services/ccms/submitters/upload_documents_service_spec.rb
Remove the todo entry for RSpec/RepeatedDescription and update the repeated descriptions in the tests.  Most of the times this invloved clarifying the text to be more specific.  In one instance I deleted a completely duplicated test and in another I merged the expectations as the initial lines were identical but the check for the error message had a slight change …
> Rubocop: address RSpec/RepeatedDescription exclusions

- app/controllers/admin/settings_controller.rb
- app/forms/settings/setting_form.rb
- app/helpers/task_list_helper.rb
- app/models/setting.rb
- app/services/flow/flows/provider_merits.rb
- app/views/admin/settings/show.html.erb
- config/locales/en/admin.yml
- db/migrate/20231004144844_remove_opponent_organisations_flag_from_settings.rb
- db/schema.rb
- features/providers/check_ccms_autogrant.feature
- features/providers/check_nonpassport_autogrant.feature
- features/providers/merits_task_list.feature
- features/providers/merits_task_list_opponent.feature
- features/providers/non_means_tested_journey/without_delegated_functions.feature
- features/providers/passported_journey.feature
- features/providers/search_opponent_organisations.feature
- spec/helpers/task_list_helper_spec.rb
- spec/models/setting_spec.rb
- spec/requests/admin/settings_controller_spec.rb
- spec/requests/providers/application_merits_task/domestic_abuse_summaries_controller_spec.rb
- spec/requests/providers/application_merits_task/has_other_opponents_controller_spec.rb
- spec/requests/providers/application_merits_task/remove_opponent_controller_spec.rb
Remove opponent organisations feature flag
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4452)
The feature has been live since 04/10/2023 so we can get rid 
of the feature flag.
> AP-4452: Remove organisation feature flag

- .circleci/config.yml
- .github/dependabot.yml
- docker/apply_base.dockerfile
- package.json
- yarn.lock
[Update puppeteer dependency to use the latest version](https://dsdmoj.atlassian.net/browse/AP-4314)
Puppeteer was previously fixed to an older version (v19.2.0) in order to allow pdf generation to work.
The fixed version of puppeteer is dated and no longer supported, therefore this branch was to test our functionality using the latest version of puppeteer.
Reference: https://github.com/ministryofjustice/laa-apply-for-legal-aid/pull/4700 …
> AP-4314: Update Puppeteer

- app/helpers/capital_helper.rb
- app/helpers/policy_disregards_helper.rb
- app/models/concerns/non_passported_state_machine.rb
- app/models/savings_amount.rb
- app/services/flow/flows/provider_capital.rb
- app/views/providers/check_capital_answers/show.html.erb
- app/views/providers/check_passported_answers/show.html.erb
- app/views/providers/means_reports/_with_bank_statement_uploads.html.erb
- app/views/providers/means_reports/_with_cfe_result_details.html.erb
- app/views/shared/check_answers/_assets.html.erb
- app/views/shared/check_answers/_property.html.erb
- app/views/shared/check_answers/_restrictions.html.erb
- app/views/shared/check_answers/_vehicles.html.erb
- app/views/shared/review_application/_income_payments_and_assets.html.erb
- app/views/shared/review_application/_income_payments_and_assets_for_bank_statement_upload.html.erb
- config/locales/cy/shared.yml
- config/locales/en/providers.yml
- config/locales/en/shared.yml
- features/providers/bank_statement_upload/check_your_means_answers.feature
- features/providers/check_your_answers.feature
- features/providers/means_report.feature
- features/providers/review_and_print.feature
- features/step_definitions/means_report_steps.rb
- spec/factories/legal_aid_applications.rb
- spec/factories/savings_amounts.rb
- spec/requests/providers/check_capital_answers_controller_spec.rb
- spec/requests/providers/check_passported_answers_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3809)
Update capital CYA pages for all journeys:
- Make simple content changes
- Move details into translation file to follow pattern for rest of the codebase
- Use summary list component in `_restrictions.html.erb`
- Sort out flow and state so there's no error when changing bank account amounts …
> AP-3809: Means assessment capital check your answers page

- config/initializers/sidekiq.rb
Prevent sidekiq info log output during test run
Dont't want to clutter up rspec and other test output
with information log entries as below.
```sh
......2023-10-24T11:22:09.788Z pid=43543 tid=rhf INFO: Sidekiq 7.1.6 connecting to Redis with options {:size=>10, :pool_name=>"internal", :url=>"redis://localhost:6379"}
``` …
> Prevent sidekiq info log output during test run

- app/controllers/saml_idp_controller.rb
- app/views/saml_idp/idp/new.html.erb
[Announce error message via screen reader ](https://dsdmoj.atlassian.net/browse/AP-4427)
Added role="alert" aria-live="assertive" to sign in page so that error message will be announced via screen readers.
> AP-4427: Add alert and area-live=assertive for screen readers and reformat sign in page

- spec/services/banking/state_benefit_analyser_service_spec.rb
There is a flickering test caused by adding two bank transactions, and asserting what the first of these will look like. Due to race conditions, the order of the two is not consistent. This PR changes nesting of the context within a spec so only one bank transaction is added, giving a more consistent result …
> Fix: update context nesting so test passes every time

- app/services/cfe_civil/component_list.rb
- app/services/cfe_civil/components/base_data_block.rb
- app/services/cfe_civil/components/capitals.rb
- app/services/cfe_civil/components/cash_transactions.rb
- app/services/cfe_civil/components/employments.rb
- app/services/cfe_civil/components/irregular_incomes.rb
- app/services/cfe_civil/components/partner.rb
- app/services/cfe_civil/components/regular_transactions.rb
- app/services/cfe_civil/components/vehicles.rb
- spec/factories/employments.rb
- spec/factories/regular_transactions.rb
- spec/services/cfe_civil/component_list_spec.rb
- spec/services/cfe_civil/components/capitals_spec.rb
- spec/services/cfe_civil/components/cash_transactions_spec.rb
- spec/services/cfe_civil/components/employments_spec.rb
- spec/services/cfe_civil/components/irregular_incomes_spec.rb
- spec/services/cfe_civil/components/partner_spec.rb
- spec/services/cfe_civil/components/regular_transactions_spec.rb
- spec/services/cfe_civil/components/vehicles_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4359)
Update the CFE submission builder to add a partner object, if needed.
Update the, current supported, individual components to build an applicant or partner data set if an owner tpe of partner is submitted.
Some of the components are not needed, and some will need updating in the future when the truelayer flow is implemented for the partners
- …
> AP-4359: Add cfe_civil partner submission

- Gemfile
- Gemfile.lock
- helm_deploy/apply-for-legal-aid/templates/deployment_metrics.yaml
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4586)
The redis update was blocked by the locked version of this gem.  
This updates the code to remove the lock and add the changes required to make the newer versions work
The following steps were undertaken and then merged into a single commit- at each stage I monitored the prometheus website to ensure that metrics were being received
Once this is merged, we will need to update the promethus checks in CPE to update some of the check names, e.g. 
`ruby_http_duration_seconds` has changed to `ruby_http_request_duration_seconds`
- There should be …
> AP-4586: Update PrometheusExporter

- app/controllers/providers/confirm_dwp_non_passported_applications_controller.rb
- spec/requests/providers/confirm_dwp_non_passported_applications_controller_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4170)
Delete dwp override on page load
> AP-4170: Correct validation for dwp override

- app/views/shared/check_answers/_partner_details.html.erb
The partner_details partial was calling `partner_has_contrary_interest?` on a non-existant @applicant object.  
Changing it to invoke the full path, `@legal_aid_application.applicant.partner_has_contrary_interest?` ensures the pages renders correctly …
> Fix: Partner review application page

- Gemfile.lock
While rebasing the rails 7 PR, there was a conflict that I manually resolved and got the gems in the wrong, alphabetical, sequence.
This works fine on the servers but this PR should prevent other users seeing confusing update after running bundle install …
> Fix: Gemfile.lock order

- lib/utilities/redis_scanner.rb
Amend example for RedisScanner utility class
The scanner requires an instance of the Redis gem's Redis client
rather than the Redis connection return by Sidekiq.redis.
> Amend example for RedisScanner utility class

- spec/rails_helper.rb
- spec/requests/providers/application_merits_task/matter_opposed_reasons_controller_spec.rb
- spec/requests/providers/confirm_client_declarations_controller_spec.rb
- spec/requests/providers/has_national_insurance_numbers_controller_spec.rb
- spec/requests/providers/has_other_proceedings_controller_spec.rb
- spec/requests/providers/means/student_finances_controller_spec.rb
- spec/requests/providers/partners/client_has_partners_controller_spec.rb
- spec/requests/providers/partners/contrary_interests_controller_spec.rb
- spec/requests/providers/partners/student_finances_controller_spec.rb
- spec/support/capybara/request_helpers.rb
Mixin the have_error_message helper to all request specs
[Came out of story](https://dsdmoj.atlassian.net/browse/AP-4575)
use an extensible mixin for request spec capybara based helpers. Currently
there is only the have_error_message helper but there could be others in
the future or already existing that could be shared via this mechanims. …
> Share the have_error_message helper

- package.json
- yarn.lock
Manually bump govuk-frontend from 4.6.0 to 4.7.0
It's been over 3 months since v4.7.0 was released, manually bumping it as our bot has not done it.
> build(deps): bump govuk-frontend from 4.6.0 to 4.7.0

- app/models/legal_aid_application.rb
- app/services/ccms/manual_review_determiner.rb
- config/locales/en/providers.yml
- features/providers/means_report.feature
- spec/services/ccms/manual_review_determiner_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4567)
Add "Non-Passported application" to list of review reasons on means report if the application is non-passported. This is to avoid a situation whereby caseworkers are flagged to review an application but the list of review reasons is empty …
> AP-4567: Add non-passported to list of reasons on means report

- app/views/shared/check_answers/_assets.html.erb
- config/locales/en/shared.yml
- features/providers/means_report.feature
- features/step_definitions/generic_steps.rb
- features/step_definitions/means_report_steps.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4566)
Added a table to display bank accounts where the provider has selected the TrueLayer journey.
A table was chosen rather than a summary list to mirror the display of Income and Regular Payments becuase of the width of the account_name,number,sort_code column.
Also made changes to the display of bank account totals for applicant, partner and joint accounts as specified in figma file.
The app/views/shared/check_answers/_assets.html.erb partial is share by the Means Report, Check your answers and Review and print application pages, so these will all need to be tested to check they display properly.
- …
> Ap-4566: means report bank account changes

- .rubocop_todo.yml
- spec/forms/applicants/employed_form_spec.rb
- spec/jobs/email_monitor_job_spec.rb
- spec/jobs/scheduled_mailings_delivery_job_spec.rb
- spec/presenters/applicant_account_presenter_spec.rb
- spec/services/ccms/requestors/case_add_requestor_spec.rb
- spec/services/ccms/requestors/case_add_requestor_xml_blocks/non_passported_additional_property_attributes_spec.rb
- spec/services/ccms/requestors/case_add_requestor_xml_blocks/non_passported_attributes_spec.rb
- spec/services/ccms/requestors/case_add_requestor_xml_blocks/non_passported_benefits_attrs_spec.rb
- spec/services/ccms/requestors/case_add_requestor_xml_blocks/non_passported_dependant_child_attributes_spec.rb
- spec/services/ccms/requestors/case_add_requestor_xml_blocks/non_passported_entities_spec.rb
- spec/services/ccms/requestors/case_add_requestor_xml_blocks/non_passported_variable_attributes_spec.rb
- spec/services/ccms/requestors/case_add_requestor_xml_blocks/passported_attributes_spec.rb
- spec/services/reports/merits_report_creator_spec.rb
- spec/workers/bank_holiday_update_worker_spec.rb
- spec/workers/true_layer_banks_update_worker_spec.rb
Remove RSpec/LetSetup from rubocop_todo
Remove all superfluous let! invocations from the RSpec code
> Rubocop: Address let! usage in tests

- .github/dependabot.yml
Slight amendment to the current babel group name, but today
16/Nov/23 we had two `@babel` dependabots opened that the
existing babel group did not trigger, adding the * prefix
should allow it to group wether it has the @ prefix or not …
> Chore: Amend babel dependabot group

- app/services/cfe_civil/components/vehicles.rb
This was being called from the submissionbuilder in a way that used the inherited .new method that set the default owner_type to applicant, when the data is stored with owner "client"
This overrides the initializer to call with owner_type client …
> Fix: CFE vehicle submission

- config/routes.rb
Remove unused copy_case_confirmation route
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4575)
Leftover from an earlier unnamespaced controller iteration that was,
indevertently, not removed.
> Fix: remove unused copy_case_confirmation route

- app/controllers/providers/means/add_other_vehicles_controller.rb
- app/controllers/providers/means/restrictions_controller.rb
- app/controllers/providers/means/vehicles_controller.rb
- app/forms/base_form.rb
- app/forms/legal_aid_applications/own_home_form.rb
- app/forms/legal_aid_applications/own_vehicle_form.rb
- app/forms/legal_aid_applications/property_details_form.rb
- app/forms/legal_aid_applications/restrictions_form.rb
- app/forms/providers/other_assets_form.rb
- app/forms/providers/policy_disregards_form.rb
- app/forms/savings_amounts/offline_accounts_form.rb
- app/forms/savings_amounts/savings_amounts_form.rb
- app/validators/currency_validator.rb
- app/validators/numericality_partner_optional_validator.rb
- app/validators/presence_partner_optional_validator.rb
- app/views/providers/means/other_assets/show.html.erb
- app/views/providers/means/savings_and_investments/show.html.erb
- config/locales/cy/activemodel.yml
- config/locales/en/activemodel.yml
- config/locales/en/providers.yml
- spec/forms/legal_aid_applications/property_details_form_spec.rb
- spec/forms/legal_aid_applications/restrictions_form_spec.rb
- spec/forms/savings_amounts/savings_amounts_form_spec.rb
- spec/requests/providers/means/restrictions_spec.rb
- spec/requests/providers/means/savings_and_investments_controller_spec.rb
- spec/requests/providers/offline_accounts_spec.rb
- spec/validators/currency_validator_spec.rb
- spec/validators/numericality_partner_optional_validator_spec.rb
- spec/validators/presence_partner_optional_validator_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4574)
This PR implements error messages on pages where we sometimes ask about client and sometimes about client _and_partner.
It updates the `currency_validator` and adds two new `*_partner_optional` validators to replace the error messages with a `_with_partner` suffixed version if `:partner_labels` is set to true
`partner_labels` should be passed a method of the form that will return true or false, this has been added to the base_from class using a method named `has_partner_with_no_contrary_interest?` that scans the connected model for an applicant with a parter with no contrary interest and sets the value accordingly.
If the form's model is non-standard, the `has_partner_with_no_contrary_interest?` method can be overridden in the …
> AP-4574: Partner error messages on shared pages

- app/forms/copy_case/confirmation_form.rb
- app/forms/copy_case/invitation_form.rb
- spec/forms/copy_case/confirmation_form_spec.rb
- spec/forms/copy_case/invitation_form_spec.rb
Cleanup copy case related data during negative or reverse flows
[Link to original story](https://dsdmoj.atlassian.net/browse/AP-4575)
<details>
<summary>Add cleanup to copy case invitation form</summary>
When traversing backward though the flow the copy_case_id could
already have been added and even its details copied. If this page is
reached we need to remove the copy_case_id to start the process again.
</details>
<details>
<summary>Add cleanup to copy case confirmation form</summary>
When No is selected on the confirmation page we should nullify 
the copy_case boolean flag to indicate this as
false/unset and remove the id that was search for. this
leaves the application in a state equivalent to not
having copied anything. Flows can then allow the user
to restart the process.
</details> …
> AP-4575[ext]: handle clearup of copy case data for negative and reverse flows 

- app/models/partner.rb
- app/views/shared/check_answers/_assets.html.erb
- app/views/shared/check_answers/_partner_details.html.erb
Update some minor tweaks from the Partner means run-through...
these were quicker than writing a ticket!
* Fix: Partner Details minor tweak to align CYA
The govuk-!-width-one-half was missing from a row which resulted in one block being mis-aligned
* Fix: Partner bank account display
Improve alignment of change buttons and display of partner/joint responses when empty
The govuk-!-width-one-half was missing from a row which
resulted in one block being mis-aligned …
> Fix: partner minor tweaks

- app/forms/providers/proceeding_merits_task/linked_children_form.rb
- spec/forms/providers/proceeding_merits_task/linked_children_form_spec.rb
Fix save as draft functionality for "Children involved in this proceeding" task page
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4592)
Allow save as draft button to function as expected. Namely,
to save the checked items/children if checked but not to enforce 
this, via validation, as a requirement for returning to the "home" page. …
> AP-4592: Fix "involved child for proceeding" save as draft

- config/locales/en/providers.yml
- features/providers/check_single_employment.feature
- features/providers/partner_means_assessment/upload_partner_employment_evidence.feature
[When prompted for employment evidence, the word status is potentially confusing](https://dsdmoj.atlassian.net/browse/AP-4633)
After review, the word "status" seems to have crept in by mistake, so this is to remove it from the end of the client and partner evidence request. …
> AP-4633: Remove word status

- app/controllers/providers/capital_income_assessment_results_controller.rb
- app/helpers/ineligible_reasons_helper.rb
- app/models/cfe/v6/result.rb
- app/views/shared/assessment_results/_ineligible.html.erb
- config/locales/en/shared.yml
- spec/factories/cfe_results/v6/mock_results.rb
- spec/factories/cfe_results/v6/results.rb
- spec/helpers/ineligible_reasons_helper_spec.rb
- spec/models/cfe/v6/result_spec.rb
- spec/requests/providers/capital_assessment_results_controller_spec.rb
- spec/requests/providers/capital_income_assessment_results_controller_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4503)
I have added code to handle the scenario where CFE returns 'ineligible' for multiple categories out of gross income, disposable income and capital and added a 'fake' CFE result to test this scenario, however, in practice this is not currently happening, see https://dsdmoj.atlassian.net/browse/AP-4503?focusedCommentId=342986 and https://github.com/ministryofjustice/laa-apply-for-legal-aid/pull/5982/files#r1392418804. This has been added as it is the desired way for CFE to work that is shown in the designs for this ticket but I am not sure if it is the best/correct approach? …
> Ap 4503 correction to ineligible result

- app/controllers/providers/copy_case/searches_controller.rb
- app/forms/copy_case/invitation_form.rb
- app/views/providers/copy_case/searches/show.html.erb
- spec/forms/copy_case/invitation_form_spec.rb
- spec/requests/providers/copy_case/searches_controller_spec.rb
"Remember" already searched for copy case reference during back paging
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4575)
when backpaging we can display the existing
application reference of a previous search
and copy flow. This means the user does not have to
go and retrieve it again if they went back inadvertently
or are attempting to get further back to amend details. …
> AP-4575 [EXT]: Display copy case search ref if exists

- app/assets/stylesheets/modal-dialogue.scss
- app/javascript/src/modal-dialogue.js
- app/views/providers/legal_aid_applications/_legal_aid_applications.html.erb
- app/views/shared/partials/_modal_dialogue.html.erb
- features/step_definitions/civil_journey_steps.rb
[Modal delete buttons inaccessible when NVDA is running](https://dsdmoj.atlassian.net/browse/AP-4428)
Update modal to use `<dialog>` html element as it represents a modal or non-modal dialog box or other interactive component, such as a dismissible alert, inspector, or sub-window, plus this will be semantically correct and therefore assistive technology tools should clearly describe its meaning to users.
The auditors recommended we test the site using different assistive technology to ensure that the screen reader output is consistent across multiple platforms and devices.
To be checked using the following matrix:
| Browser | NVDA      | VoiceOver |
| :------ | :------:  | ----:     |
| Chrome  |  ok   | ok    |
| Edge    |  ok   | ok    |
| Firefox |  ok   | ok    |
| Safari |  -  | ok …
> AP-4428 Enable accessible modal buttons when using NVDA

- spec/rails_helper.rb
A recent update to rspec-rails (I think) added this in, so this removes it
> Fix: Remove fixture-path deprecation warning

- app/views/providers/means/policy_disregards/show.html.erb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4629)
Implement the work-around for displaying an error block when nothing is selected
> AP-4629: Update policy-disregards error handling

- spec/factories/employments.rb
- spec/services/cfe_civil/components/employments_spec.rb
- spec/services/cfe_civil/components/partner_spec.rb
Remove factory attributes and tests that rely on PK ids
Split from [factory_bot_rails bump PR](https://github.com/ministryofjustice/laa-apply-for-legal-aid/pull/6014)
Problem with factory_bot_rails include a default config option that 
seeks to prevent setting of PK ids in factories.  The `config.factory_bot.reject_primary_key_attributes`
is set to true AND setting to false is not working currently (possibly due to loading bugs with factory_bot
and factory_bot_rails). However this is probably for the best as tests reliant on PK Ids are not
ideal. …
> FactoryBot/Fix: remove primary key generation from factories and specs

- app/forms/base_form.rb
- app/forms/copy_case/search_form.rb
- app/forms/link_case/search_form.rb
- spec/forms/copy_case/search_form_spec.rb
- spec/forms/link_case/search_form_spec.rb
Allow whitespace and case-insenstive search for copy and link of cases
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4575)
So inadvertent whitespace or character case use does
not prevent users from finding otherwise valid case
references for copying or linking.
The addition of the class method to the base_form
means this could be used for other form attributes, such
as postcode (BaseAddressLookupForm) …
> AP-4575 [EXT]: Allow whitespace and case-insensitive searching

- app/views/shared/check_answers/_partner_details.html.erb
- app/views/shared/review_application/_questions_and_answers.html.erb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4632)
Update the review and print page for handling the partner details.
When the partner has no contrary interest, display the populated values otherwise, show the contrary interest question the the yes response …
> AP-4632: Update partner details on review page

- bin/delete_dependabot_deployment
delete any dependabot persistent volume claims after build and deploy of branch
we have too many PVCs sitting around and have been asked to tidy them up. This mechanism is looking to use something that is not dependant on the PVC name so as to decouple it from the complex naming logic.
- You …
> delete any PVC named after the release

- .github/workflows/delete-uat-release.yml
Bump delete uat GHA v1.0.2 --> v1.1.0
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4659)
We have not been clearing up our persistenvolumeclaims
when deleting UAT branches. This eats up cloud platform 
cluster resource and cost (particularly backups apparently).
This bumped version will do the PVC cleanup going forward.
- The …
> AP-4659: Bump delete uat GHA v1.0.2 --> v1.1.0

- .simplecov
- app/controllers/pages_controller.rb
- app/models/setting.rb
- app/views/pages/servicedown.html.erb
- config/locales/en/pages.yml
- config/routes.rb
- db/schema.rb
- helm_deploy/apply-for-legal-aid/templates/_envs.tpl
Add maintenance page
Following security incident we need to put application in maintenance mode
with a custom content/servicedown page. The CP version of doing this
is involved and burdensome.
- Add route controller and view for servicedown
- Add maintenance mode env var and use …
> Add maintenance mode (v2)

- .github/dependabot.yml
The previous configuration meant that dependabot would try and group all wildcards into a single PR
This meant, that when a problem occurred, it was hard to isolate the cause …
> Fix: npm Dependabot grouping

- .circleci/config.yml
- Fix: remove unneeded docker env vars - see [clearing project dependency cache](https://support.circleci.com/hc/en-us/articles/115015426888-Clear-Project-Dependency-Cache)
- Fix: replace deprecated circle step name - [migrate from deploy to run](https://circleci.com/docs/migrate-from-deploy-to-run/)
These references are referring to a Circle project env var
not a docker image env var.
```
{{ .Environment.CACHE_VERSION }}
```
Currently cache names are `blah-<no-value>-blah`
- The standards in the [Git Workflow document on Confluence](https://dsdmoj.atlassian.net/wiki/spaces/ATPPB/pages/4602855954/Git+W …
> Fix circle cache resetting and step deprecation

- features/cassettes/Applicant_details/Allows_return_to_and_proceed_from_Delegated_Function_date_view.yml
- features/cassettes/Applicant_details/Completes_the_application_using_address_lookup.yml
- features/cassettes/Applicant_details/Completes_the_application_using_address_lookup_with_multiple_proceedings.yml
- features/cassettes/Applicant_details/Completes_the_application_using_manual_address.yml
- features/cassettes/Applicant_details/I_can_see_that_the_applicant_does_not_receive_benefits.yml
- features/cassettes/Applicant_details/I_can_see_that_the_applicant_receives_benefits.yml
- features/support/env.rb
Stub all bank holiday API calls for feature test scenarios.
[Leftover from ticket](https://dsdmoj.atlassian.net/browse/AP-4617)
Bank holidays could introduce flakiness plus, with wifi off, the following tests currently fail with:
```sh
cucumber features/providers/applicant_details.feature:3
cucumber features/providers/applicant_details.feature:300
=> 
Failed to open TCP connection to www.gov.uk:443 (getaddrinfo: nodename nor servname provided, or not known) (SocketError)
./app/services/bank_holiday_retriever.rb:27:in `response'
```
Which i believe relates to async sidekiq jobs attempting to call the API and no vcr stubs existing. recording requests with VCR when they originate from sidekiq bakcground jobs does not appear to work and inlineing the sidekiq jobs causes many other calls (to …
> AP-4617: fix bank holiday test reliance

- app/forms/applicants/employed_form.rb
- app/forms/base_employed_form.rb
- app/forms/partners/employed_form.rb
- app/forms/partners/offline_accounts_form.rb
- app/forms/providers/other_assets_form.rb
- app/forms/providers/policy_disregards_form.rb
- app/forms/savings_amounts/offline_accounts_form.rb
- app/forms/savings_amounts/savings_amounts_form.rb
- config/locales/en/activemodel.yml
- spec/forms/applicants/employed_form_spec.rb
- spec/forms/partners/employed_form_spec.rb
- spec/forms/partners/offline_accounts_form_spec.rb
- spec/forms/providers/other_assets_form_spec.rb
- spec/forms/savings_amounts/offline_accounts_form_spec.rb
- spec/forms/savings_amounts/savings_amounts_form_spec.rb
- spec/requests/providers/means/policy_disregards_controller_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4606)
Add extra validation so "None of the above" and another checkbox cannot both be selected when JS is disabled …
> AP-4604: Validation so "none" and another checkbox cannot both be selected

- app/models/cfe/v4/result.rb
- app/models/cfe/v6/result.rb
- app/views/providers/capital_assessment_results/_result_details.html.erb
- app/views/providers/capital_income_assessment_results/_bank_statements.html.erb
- app/views/providers/capital_income_assessment_results/_deductions.html.erb
- app/views/providers/capital_income_assessment_results/_disposable_income.html.erb
- app/views/providers/capital_income_assessment_results/_employment_income.html.erb
- app/views/providers/capital_income_assessment_results/_other_income.html.erb
- app/views/providers/capital_income_assessment_results/_outgoings.html.erb
- app/views/providers/capital_income_assessment_results/_result_details.html.erb
- app/views/shared/_property_results.html.erb
- app/views/shared/_savings_and_investments.html.erb
- app/views/shared/_total_capital.html.erb
- app/views/shared/_vehicle_results.html.erb
- config/locales/en/providers.yml
- config/locales/en/shared.yml
- spec/factories/cfe_results/v6/mock_results.rb
- spec/factories/cfe_results/v6/results.rb
- spec/models/cfe/v6/result_spec.rb
- spec/models/cfe/v6/with_partner_result_spec.rb
- spec/requests/providers/capital_assessment_results_controller_spec.rb
- spec/requests/providers/capital_income_assessment_results_controller_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3811)
Updated the means assessment result page to show the partner assessment details.
This required creating the CFE V6 result model which implements many method to retrieve/calculate the partner financial results, overriding these methods from CFE V4 while ensuring these updated methods also still work for client-only applications. 
CFE V4 also had to be updated to take option args (**) to avoid throwing a NoMethod error when the updated V6 methods are called with `partner: true` on an old CFE V4 result
A new separate rspec file was created to test all these methods for an application with a partner `spec/models/cfe/v6/with_partner.rb`. A new mock result `with_partner` has been added. 
Existing rspecs were udpated
Before you ask …
> AP-3811 partner means assessment

- app/lib/message_logger.rb
- app/services/ccms/parsers/applicant_search_response_parser.rb
- app/services/ccms/parsers/base_response_parser.rb
- app/services/ccms/submitters/base_submission_service.rb
- app/services/ccms/submitters/obtain_applicant_reference_service.rb
- spec/data/ccms/applicant_search_response_multiple_number_not_matched.xml
- spec/data/ccms/applicant_search_response_multiple_results.xml
- spec/data/ccms/applicant_search_response_number_not_held.xml
- spec/data/ccms/applicant_search_response_number_not_matched.xml
- spec/data/ccms/applicant_search_response_one_result.xml
- spec/services/ccms/parsers/applicant_search_response_parser_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4716)
Following the recent discovery of issues at the CCMS end of our submissions, issues with identifying applicants were discovered.  This PR addresses the following, newly identified, issues with the ApplicantSearchResponseParser:
* when an applicant matches surname and DOB but has no NINO, it would return `Number Not held`
* If two records for the same values were returned with `Number Not Matched` the previous equality check would fail because it would resolve to does `Number Not Matched` equal `Number Not MatchedNumber Not Matched`
This adds tests for the new scenarios and updates the validation checks for the new scenarios
While investigating I discovered that the existing XML example files did not match the current returns …
> AP-4716: Update applicant search response parser

- features/providers/bank_statement_upload/state_benefit_loop.feature
Check page title in feature test
Remove todo from codebase …
> Chore: check page title in feature test

- app/controllers/saml_sessions_controller.rb
- app/views/providers/start/index.html.erb
- features/providers/cookies.feature
- features/providers/mock_saml.feature
- features/providers/non_means_tested_journey/under_18_application_journey.feature
- features/providers/non_means_tested_journey/with_delegated_functions.feature
- features/providers/non_means_tested_journey/without_delegated_functions.feature
- features/providers/search_applications.feature
- features/providers/search_proceedings.feature
- features/step_definitions/civil_journey_steps.rb
- features/step_definitions/cookie_steps.rb
- spec/requests/saml_sessions_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4694)
This changes the login flow, we know that providers generally start from the portal and then directed into our service from there.
This meant that we routed them to the office select screen and they did not see the Start/Declaration page
This PR changes the login flow to only show the office choice page if the user has seen the root_page within the last 10 page views in the service, or we are using the mock saml provider, otherwise they will be shown the root page …
> AP-4694: SAML login sequence change

- config/initializers/devise.rb
This is set explicitly to remove a deprecation warning during the Rails 7.1 to 7.2 transition, if Devise is set above 4.9.3, try removing it to see if the deprecation warning has been addressed …
> Chore: Remove Rails Secret deprecation warning

- app/services/ccms/submitters/obtain_document_id_service.rb
This came out of the CCMS dance review.
The DocumentIdRequestor was called on line 57 when it was extracted into a separate method.
It was then called it again and the end of the `update_document_and_return_response` method and, best case, did nothing with the duplicate call.
Worst case, it (correctly) saved number 00001 into the database and then logged 00002 into the submission history
This would have made tracking issues harder, and created empty rows in the CCMS database, but not have been a significant error …
> Fix: remove duplicate DocumentIdRequestor call

- app/views/providers/address_lookups/show.html.erb
- config/locales/en/providers.yml
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4735)
Update hint text on address lookup page to what's shown in the screenshot below.
Screenshot: …
> AP-4735: Update hint text on address lookup page

- docs/puffing_billy_recording.md
- features/step_definitions/civil_journey_steps.rb
- features/support/env.rb
The purpose of this pr is to try and resolve (some) of the circleci integration test failures we are seeing. Looking [here](https://app.circleci.com/insights/gh/ministryofjustice/laa-apply-for-legal-aid/workflows/merge_pr/tests?branch=main) it appears the most common test failures are still on applicant_details.feature. We [previously](https://github.com/ministryofjustice/laa-apply-for-legal-aid/pull/6041) attempted to resolve these by introducing puffing billy to stub calls made in javascript to LFA and I do believe this has worked when the test failed due to network connectivity, as the applicant_details.feature test passes for me when run locally with wifi switched off.
I therefore think the remaining failures are a result of a timing issue/race condition. The failures we are seeing on …
> ap-3772: attempt to fix failures on proceeding search

- app/models/cfe/submission.rb
- app/services/cfe_civil/component_list.rb
- app/views/providers/means/check_income_answers/_applicant_income_assessment.html.erb
- app/views/shared/check_answers/_assets.html.erb
- app/views/shared/check_answers/_income_details.html.erb
- spec/services/cfe_civil/component_list_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4759)
Based off the work on #6254 which was undertaken before the stakeholder run through - feel free to review entirely but the first three commits have been reviewed on the original PR
After a partner run through we saw some issues and this fixes some of them
* Update the means report income summary to use the combined total instead of the client total
* Update asset partial to show truelayer bank accounts as well as the manually entered values
* Update the CFECivil component list to ensure that truelayer data is sent when the partner uploads bank statements
* Update applicant_income_assessment view - Only switch when the client is uploading bank statements not
either party
* Update asset view - ensure the heading is only shown when …
> AP-4759: Update partner means

- app/views/citizens/consents/show.html.erb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4437)
Remove hidden element which duplicates the page heading as this could be navigated to using a screen reader. Page should look visually identical …
> AP-4437: Remove additional element

- .github/workflows/anonymise_check.yml
- .github/workflows/base-docker-image.yml
- .github/workflows/ci-docker-image.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/delete-uat-release.yml
There are a number of alerts that the current github actions use an outdated node version. 
This PR bumps all standard actions to reduce Node warnings …
> Chore: Update github action versions

- app/views/providers/cookies/show.html.erb
- app/views/providers/legal_aid_applications/search.html.erb
- config/locales/en/providers.yml
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4774)
Remove instances of visually hidden text, that is read out with a screenreader, which duplicates visual text …
> AP-4774: Fix accessibility issues with hidden labels

- app/views/providers/about_the_financial_assessments/show.html.erb
- app/views/providers/check_provider_answers/_shared.html.erb
- app/views/shared/check_answers/_client_details.html.erb
- app/views/shared/check_answers/_proceeding_details.html.erb
- config/locales/en/generic.yml
- config/locales/en/shared.yml
[AP-4431](https://dsdmoj.atlassian.net/browse/AP-4431)
Add association between change button and context for screen readers. 
- You …
> AP-4431: Add association between change button and context

- app/services/faraday/soap_call.rb
- spec/cassettes/benefit_check_service/savon_successful_call.yml
- spec/services/faraday/soap_call_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4767)
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4771)
Class to allow Faraday to make SOAP calls - this will allow us to replace Savon but the aim is to add this and allow us to update the Savon calls individually before removing the gem.
It was developed during a mob session and has been overseen by all current developers …
> Faraday soap call

- spec/requests/saml_sessions_spec.rb
This is a race condition that checks the count of values in the page history, if other tests visit pages first it causes a false positive in these tests.
The fix clears the test redis instance for the page_history database before each test in this block …
> Fix: Flickering SAML tests

- Gemfile
- Gemfile.lock
The gem has been update to 3.0.0 and started a deprecation process to replace dotenv-rails with a single-use dotenv gem
closes #6346  …
> Fix: update DotEnv

- app/services/ccms/requestors/applicant_add_status_requestor.rb
- app/services/ccms/requestors/base_requestor.rb
- app/services/ccms/requestors/case_add_status_requestor.rb
- app/services/ccms/requestors/document_id_requestor.rb
- app/services/ccms/requestors/document_upload_requestor.rb
- app/services/ccms/requestors/reference_data_requestor.rb
- app/services/ccms/submitters/base_submission_service.rb
- spec/services/ccms/requestors/applicant_add_status_requestor_spec.rb
- spec/services/ccms/requestors/case_add_status_requestor_spec.rb
- spec/services/ccms/requestors/document_id_requestor_spec.rb
- spec/services/ccms/requestors/document_upload_requestor_spec.rb
- spec/services/ccms/requestors/reference_data_requestor_spec.rb
- spec/services/ccms/submitters/add_applicant_service_spec.rb
- spec/services/ccms/submitters/add_case_service_spec.rb
- spec/services/ccms/submitters/check_applicant_status_service_spec.rb
- spec/services/ccms/submitters/check_case_status_service_spec.rb
- spec/services/ccms/submitters/obtain_applicant_reference_service_spec.rb
- spec/services/ccms/submitters/obtain_case_reference_service_spec.rb
- spec/services/ccms/submitters/obtain_document_id_service_spec.rb
- spec/services/ccms/submitters/upload_documents_service_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4767)
Replace Savon calls in the CCMS namespace with Faraday::SoapCall
Set the faraday_soap class to load in test: This is eager loaded in dev and production but ignored in test so needs an explicit require …
> AP-4767: Use faraday for CCMS soap calls

- app/models/dependant.rb
- spec/models/dependant_spec.rb
- spec/services/ccms/requestors/case_add_requestor_xml_blocks/non_passported_dependant_child_attributes_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4821)
Ensure the `Dependent adult` values in `CLI_RES_PER_INPUT_T_12WP3_17A` fields are spelled correctly when submitting to CCMS …
> AP-4821: Fix client relationship ccms values

- app/controllers/providers/address_lookups_controller.rb
- app/forms/addresses/address_lookup_form.rb
- app/views/providers/address_lookups/show.html.erb
- config/locales/en/helpers.yml
- config/locales/en/providers.yml
- config/routes.rb
- db/migrate/20240216110009_add_type_to_address.rb
- db/schema.rb
- features/providers/check_provider_answers.feature
- features/providers/no_nino_flow.feature
- features/step_definitions/civil_journey_steps.rb
- spec/requests/providers/address_lookups_controller_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4798)
Update the find correspondence address page
* Add the new house number/name field
* Add a `correspondence` field to allow extending to home addresses in the near future …
> AP-4798: Update find correspondence address

- spec/forms/addresses/address_form_spec.rb
Amend typo in address test. Test description referred to city instead of county.  …
> fix: amend typo in address test

- helm_deploy/apply-for-legal-aid/templates/_helpers.tpl
- helm_deploy/apply-for-legal-aid/templates/cronjob-admin-report.yaml
- helm_deploy/apply-for-legal-aid/templates/cronjob-destroy-purgeable.yaml
- helm_deploy/apply-for-legal-aid/templates/cronjob-export-digest.yaml
- helm_deploy/apply-for-legal-aid/templates/cronjob-extract-digest.yaml
- helm_deploy/apply-for-legal-aid/templates/cronjob-mark-purgeable.yaml
The overnight jobs all require a database to function but, as we turn it off overnight, they all fail and cause errors which eat into the sentry allowance.
This PR tries adding a 7 hour offset to staging to allow them to run once the DB has restarted.
It currently adds a 1 hour offset to UAT so I can test if the theory works without deploying to staging and potentially breaking everything!
It sets an offset of 0 otherwise so production remain at the normal scheduled times
- The standards in the [Git Workflow document on Confluence](https://dsdmoj.atlassian.net/wiki/spaces/ATPPB/pages/4602855954/Git+Wor …
> Fix: reduce Staging sentry alerts

- features/step_definitions/applicant_detail_steps.rb
- spec/forms/proceedings/delegated_functions_form_spec.rb
minus 1 year from 29th February = 28th February and that 'counts' as the same date so fails validation.  This increases the check to 13 months old to reduce the risk of recurrence …
> Fix: Update leap-date check

- helm_deploy/apply-for-legal-aid/templates/cronjob-reset-dashboard-overnight.yaml
Apply the overnight staging offset to reduce the noise from this job.  When updating the others I assumed this would not be causing issues as it "resets" the overnight count, but actually it tries to read the DB first …
> Fix: Update the dashboard update cronjob

- app/controllers/providers/home_address/different_address_reasons_controller.rb
- app/controllers/providers/home_address/different_addresses_controller.rb
- app/forms/home_address/different_address_form.rb
- app/forms/home_address/different_address_reason_form.rb
- app/helpers/address_helper.rb
- app/services/flow/flows/provider_start.rb
- app/views/providers/home_address/different_address_reasons/show.html.erb
- app/views/providers/home_address/different_addresses/show.html.erb
- app/views/shared/address_selection/_confirm_address.html.erb
- app/views/shared/address_selection/_select_address.html.erb
- config/locales/en/activemodel.yml
- config/locales/en/generic.yml
- config/locales/en/providers.yml
- config/locales/en/shared.yml
- config/routes.rb
- db/migrate/20240229074123_add_different_home_address_to_applicant.rb
- db/migrate/20240229074123_add_same_correspondence_and_home_address_to_applicant.rb
- db/migrate/20240229150804_add_no_fixed_residence_to_applicant.rb
- db/schema.rb
- spec/requests/providers/address_selections_controller_spec.rb
- spec/requests/providers/home_address/different_address_reasons_controller_spec.rb
- spec/requests/providers/home_address/different_addresses_controller_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4802)
- Add `same_correspondence_and_home_address` and  `no_fixed_residence` to applicant model
- Add model, view, controller, form for `different_address` and `different_address_reason` pages
- Update specs
- Update flow
- Add `generic.search_again` to locales file
- The PR …
> AP-4802: different home address question v2

- app/controllers/providers/addresses_controller.rb
- app/controllers/providers/home_address/addresses_controller.rb
- app/services/flow/flows/provider_start.rb
- app/views/providers/addresses/show.html.erb
- app/views/providers/home_address/addresses/show.html.erb
- app/views/shared/_address_lookup.html.erb
- app/views/shared/_addresses.html.erb
- app/views/shared/address_selection/_confirm_address.html.erb
- app/views/shared/address_selection/_no_address.html.erb
- app/views/shared/address_selection/_select_address.html.erb
- config/locales/en/activemodel.yml
- config/locales/en/providers.yml
- config/locales/en/shared.yml
- config/routes.rb
- spec/helpers/providers_helper_spec.rb
- spec/requests/providers/addresses_controller_spec.rb
- spec/requests/providers/home_address/addresses_controller_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4831)
- Update flow for manual correspondence address path when `home_address` feature flag is enabled
- Added home_address/addresses_controller and  corresponding views
- Created shared addresses partial for manual correspondence and home address entry …
> AP-4831: Manual home address

- app/controllers/providers/address_lookups_controller.rb
- app/controllers/providers/address_selections_controller.rb
- app/controllers/providers/addresses_controller.rb
- app/controllers/providers/home_address/addresses_controller.rb
- app/controllers/providers/home_address/home_address_lookups_controller.rb
- app/controllers/providers/home_address/home_address_selections_controller.rb
- spec/requests/providers/address_lookups_controller_spec.rb
- spec/requests/providers/address_selections_controller_spec.rb
- spec/requests/providers/addresses_controller_spec.rb
- spec/requests/providers/home_address/addresses_controller_spec.rb
- spec/requests/providers/home_address/home_address_lookups_controller_spec.rb
- spec/requests/providers/home_address/home_address_selections_controller_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4906)
When adding Non-UK countries we forgot to set the default to GBR when storing a new address, this updates the creation of address and ensures they get set to the default value, GBR
- You …
> AP-4906: Update default country handling for addresses

- app/forms/home_address/different_address_form.rb
- app/forms/home_address/different_address_reason_form.rb
- app/helpers/check_provider_answers_helper.rb
- app/models/address.rb
- app/services/flow/flows/provider_start.rb
- app/views/providers/check_provider_answers/_shared.html.erb
- app/views/shared/check_answers/_client_details.html.erb
- config/locales/en/shared.yml
- features/cassettes/Checking_client_details_answers_backwards_and_forwards/I_am_able_to_return_and_amend_the_client_s_home_address.yml
- features/cassettes/Checking_client_details_answers_backwards_and_forwards/I_am_able_to_return_and_amend_the_client_s_overseas_home_address.yml
- features/providers/check_provider_answers.feature
- features/step_definitions/civil_journey_steps.rb
- spec/forms/home_address/different_address_form_spec.rb
- spec/forms/home_address/different_address_reason_form_spec.rb
- spec/helpers/check_provider_answers_helper_spec.rb
- spec/models/address_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4854)
- Added home address to cya.
- Fix to remove existing home address where a user sets no_fixed_residence? or same_correspondence_and_home_address? to true.
- Removed validation on address model as this is not applicable to overseas addresses and we will rely on the forms for validation. …
> ap-4854: add home address to check_provider_answers

- app/helpers/address_helper.rb
- app/models/address.rb
- app/models/applicant.rb
- app/services/ccms/requestors/applicant_add_requestor.rb
- spec/factories/addresses.rb
- spec/factories/legal_aid_applications.rb
- spec/models/applicant_spec.rb
- spec/services/ccms/requestors/applicant_add_requestor_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4728)
This PR is to update the address handling when submitting data to CCMS
It updates the Applicant model:
* with a `home_address_for_ccms` method that checks for a home address and falls back to the correspondence address if one is not found
* it does not send a home address if the provider has said they have no fixed residence
It updates the ApplicantAddRequestor to:
* use the new method from the Applicant model
* to submit a calculated value to `clientbio:NoFixedAbode` rather than using a fixed, `false` response
It updates the Address model and AddressHelper to return the country value if it is anything other than GBR, this allows us to display the chosen country code on CYA, review pages etc for non-UK home addresses
Before you …
> AP-4728: Update CCMS address handling

- app/controllers/providers/home_address/addresses_controller.rb
- app/controllers/providers/home_address/home_address_lookups_controller.rb
- app/controllers/providers/home_address/non_uk_home_addresses_controller.rb
- spec/cassettes/Providers_HomeAddress_NonUkHomeAddressesController/GET_/providers/applications/_legal_aid_application_id/home_address/non_uk_home_address/edit/when_the_provider_is_authenticated/when_the_applicant_has_an_existing_overseas_home_address/displays_the_home_address.yml
- spec/cassettes/Providers_HomeAddress_NonUkHomeAddressesController/GET_/providers/applications/_legal_aid_application_id/home_address/non_uk_home_address/edit/when_the_provider_is_authenticated/when_the_applicant_has_an_existing_uk_home_address/does_not_display_the_home_address.yml
- spec/requests/providers/home_address/addresses_controller_spec.rb
- spec/requests/providers/home_address/home_address_lookups_controller_spec.rb
- spec/requests/providers/home_address/non_uk_home_addresses_controller_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4913)
The overseas address page was displaying a uk home address if one had been entered previously.
On further investigation it was found that that there was also a similar issue with displaying overseas addresses on pages that should only display uk addresses.
The country was also consequently not being updated correctly when swapping between uk and non-uk home addresses;  i.e. if an overseas address home address was entered and then a uk home address the home address still had the overseas country.
Fix - introduce current_non_uk_home_address in non-uk-home_addresses_controller to check whether a home address exists and whether it is an overseas home address, if both are true use the existing home address if not build a new home …
> ap-4913: build a new home address if changing between overseas and uk home address

- app/assets/stylesheets/language-switcher.scss
This has been warning for a while on yarn build
```
Warning: govuk-typography-responsive is deprecated. Use govuk-font-size instead. To silence this warning, update $govuk-suppressed-warnings with key: "govuk-typography-responsive"
node_modules/govuk-frontend/dist/govuk/settings/_warnings.scss 49:5    -warning()
node_modules/govuk-frontend/dist/govuk/helpers/_typography.scss 117:3  govuk-typography-responsive()
app/assets/stylesheets/language-switcher.scss 2:3                      @import
app/assets/stylesheets/application.scss 19:9                           root stylesheet
```
Changing the import to govuk-font-size removes the warning and causes no issues on the citizen views when the (incomplete) welsh translation flag is enabled
- Tests and …
> Fix: Remove govuk-typography-responsive deprecation warning

- .sonarcloud.properties
Chore: ignore SonarCloud rule:
- Ruby:S1186 (Methods should not be empty) …
> Chore: SonarCloud ignore rule

- spec/requests/providers/home_address/addresses_controller_spec.rb
The default factory for address populates address_line_one with a building number.  
Sometimes the randomly generated building number is included elsewhere in the HTML rendering this test failing.  
In this failing screenshot, the house number was set to 268, which is part of the colour polyfill for the govuk logo!
This PR replaces the one off flickery test with a building_name to prevent it recurring.  
Changing the factory could have affected many more tests and caused more fragility so was left as-is for now. 
If we see more of this type of flickering, it may be worth switching the factory to always use street_name.
- Github should not be reporting conflicts; you should have recently run …
> Fix: Resolve flickering address test

- config/locales/en/enums.yml
- config/locales/en/providers.yml
- config/routes.rb
- spec/helpers/providers_helper_spec.rb
[Update design to stop providers from submitting existing draft applications](https://dsdmoj.atlassian.net/browse/AP-4933)
Replace "out of date" with "voided" and update text on the interrupt page to match updated design.  …
> AP-4933: Replace out-of-date text with voided

- app/controllers/providers/link_application/make_links_controller.rb
- app/forms/providers/link_application/make_link_form.rb
- app/forms/providers/link_applications/make_link_form.rb
- app/models/linked_application.rb
- app/services/flow/flows/provider_start.rb
- app/views/providers/link_application/make_links/show.html.erb
- config/locales/en/activemodel.yml
- config/locales/en/providers.yml
- config/routes.rb
- db/migrate/20240415074736_change_linked_application_lead_application_null_constraint.rb
- db/schema.rb
- spec/cassettes/Providers_HomeAddress_NonUkHomeAddressesController/PATCH_/providers/applications/_legal_aid_application_id/home_address/non_uk_home_address/when_the_provider_is_authenticated/with_a_valid_address/when_the_linked_application_feature_flag_is_enabled/redirects_to_link_applications.yml
- spec/forms/providers/link_application/make_link_form_spec.rb
- spec/requests/providers/correspondence_address/manuals_controller_spec.rb
- spec/requests/providers/correspondence_address/selections_controller_spec.rb
- spec/requests/providers/home_address/different_address_reasons_controller_spec.rb
- spec/requests/providers/home_address/different_addresses_controller_spec.rb
- spec/requests/providers/home_address/manuals_controller_spec.rb
- spec/requests/providers/home_address/non_uk_home_addresses_controller_spec.rb
- spec/requests/providers/home_address/selections_controller_spec.rb
- spec/requests/providers/link_application/make_links_controller_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4825)
- Added the "Do you want to link this application with another one?" page.
- Selecting Yes to Family or Legal link will create a new LinkedApplication, with the associated link_type_code, but without a lead_linked_application (this will be updated as part of ap-4826).
- Changed validation on linked_appliccation to allow creation when lead_linked_application is nil …
> ap-4825: add Do you want to link this application with another one?' question

- config/initializers/devise.rb
After a regular reminder to check this, and seeing that Devise had updated, I checked but the deprecation warning still occurs in Devise 4.9.4.  This updates the explanation so we can monitor after future updates. …
> Chore: Update devise warning

- app/controllers/providers/link_application/find_link_applications_controller.rb
- app/forms/providers/link_application/find_link_application_form.rb
- app/services/flow/flows/provider_start.rb
- app/views/layouts/application.html.erb
- app/views/providers/link_application/find_link_applications/show.html.erb
- config/locales/en/activemodel.yml
- config/locales/en/providers.yml
- config/routes.rb
- spec/forms/providers/link_application/find_link_application_form_spec.rb
- spec/requests/providers/link_application/find_link_applications_controller_spec.rb
- spec/requests/providers/link_application/make_links_controller_spec.rb
[AP-4826](https://dsdmoj.atlassian.net/browse/AP-4826)
Add ‘What is the LAA reference of the application you want to link to?’ question. Users will see this question if they have selected yes to either family or legal linking.
For MVP, they will be restricted to only searching by LAA reference, with an exact match of ref number required.
A message is displayed if:
- no case is found
- a case is found, but it has not yet been submitted - this will provide a link to the application that needs to be submitted via the search …
> AP-4826: Add LAA reference link question

- app/controllers/providers/link_application/copies_controller.rb
- app/forms/providers/link_application/copy_form.rb
- app/services/flow/flows/provider_start.rb
- app/services/flow/steps/linked_applications/confirm_link_step.rb
- app/services/flow/steps/linked_applications/copy_step.rb
- app/views/providers/link_application/copies/show.html.erb
- config/locales/en/activemodel.yml
- config/locales/en/providers.yml
- config/routes.rb
- spec/forms/providers/link_application/copy_form_spec.rb
- spec/requests/providers/link_application/copies_controller_spec.rb
- spec/services/flow/steps/linked_applications/confirm_link_step_spec.rb
- spec/services/flow/steps/linked_applications/copy_step_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4828)
This adds the copy case question page required by the link/copy case feature
When yes is selected it sets a flash message to be displayed on the next page, when no is selected it routes to the next step in the standard flow, proceedings …
> AP-4828: Add copy case question

- app/forms/addresses/address_form.rb
[(Addresses) undefined method `many?' for nil (ActionView::Template::Error)](https://dsdmoj.atlassian.net/browse/AP-4953)
Bug: undefined method `many?` for nil
@address_collection was returning nil
Further investigation indicates address city and or county with special characters cause errors
This fix improves validation for address city and county …
> AP-4953: Bug - improve validation of address city and county

- app/services/flow/flows/provider_capital.rb
- app/services/flow/flows/provider_means_state_benefits.rb
- app/services/flow/flows/provider_merits.rb
- app/services/flow/flows/provider_partner.rb
- app/services/flow/steps/addresses/correspondence_address_manuals_step.rb
- app/services/flow/steps/addresses/home_address_manuals_step.rb
- app/services/flow/steps/partner/remove_state_benefits_step.rb
- app/services/flow/steps/provider_capital/remove_vehicles_step.rb
- app/services/flow/steps/provider_means/remove_state_benefits_step.rb
- app/services/flow/steps/provider_merits/opponent_new_organisation_step.rb
- app/services/flow/steps/provider_merits/remove_involved_child_step.rb
- app/services/flow/steps/provider_merits/remove_opponent_step.rb
- spec/cassettes/Providers_ApplicationMeritsTask_OpponentNewOrganisationsController/update_PATCH_/providers/applications/_legal_aid_application_id/opponent_new_organisation/_opponent_id/redirects_along_the_flow.yml
- spec/requests/providers/application_merits_task/opponent_new_organisations_controller_spec.rb
- spec/requests/providers/application_merits_task/remove_involved_child_spec.rb
- spec/requests/providers/application_merits_task/remove_opponent_controller_spec.rb
- spec/requests/providers/home_address/manuals_controller_spec.rb
- spec/requests/providers/means/remove_state_benefits_controller_spec.rb
- spec/requests/providers/means/remove_vehicles_controller_spec.rb
- spec/requests/providers/partners/remove_state_benefits_controller_spec.rb
- spec/services/flow/steps/addresses/correspondence_address_manuals_step_spec.rb
- spec/services/flow/steps/addresses/home_address_manuals_step_spec.rb
- spec/services/flow/steps/partner/remove_state_benefits_step_spec.rb
- spec/services/flow/steps/provider_capital/remove_vehicles_step_spec.rb
- spec/services/flow/steps/provider_means/remove_state_benefits_step_spec.rb
- spec/services/flow/steps/provider_merits/opponent_new_organisation_step_spec.rb
- spec/services/flow/steps/provider_merits/remove_involved_child_step_spec.rb
- spec/services/flow/steps/provider_merits/remove_opponent_step_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4952)
The bug listed was caused by a provider reaching a page with no flow step and then closing the webpage or returning to the application list.  The list then tried to reach a flow step with no path, errored and re-directed the user to the first page.
This corrects the error seen and all other steps with no path.
It might be easier to review each commit in turn as the changes get scattered in the whole PR review.
The correspondence manual controller tests had already been updated to the new flow and required no additional changes, in case you wonder why it's the only controller with no tests changed! …
> AP-4952: Bug - move any step with no path into new step pattern

- Gemfile.lock
v12.0.0 was pulled from rubygems over the weekend, after we updated Friday, and replaced with 12.0.1
>[!Warning]
> 
> This release has been yanked, as it included changes that weren't properly
> logged in the changelog. This release wasn't ideal as it contained some
> leftover print statements, anyway.
This causes all subsequent deploys to fail as 12.0.1 is not available for the docker build process on CircleCI …
> CHORE: Update super_diff gem

- app/helpers/linked_applications_helper.rb
- app/views/providers/link_application/confirm_links/show.html.erb
- spec/helpers/linked_applications_helper_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4991)
- Updated linked_applications_helper to ensure discarded/soft-deleted applications are not displayed.
- Updated linked_applications_helper to retrieve all_linked_applications using a single db query
- Fixed bug so that the "All applications with a family link to this one" detail panel is not displayed if all_linked_applications_details returns empty string …
> Ap 4991 update linked applications helper for discarded applications

- spec/models/legal_aid_application_spec.rb
This was caused by a race condition when setting up the proceedings, the test expected `A` -> `B`, 
but the setup sometimes created `B` a fraction of a second before `A`
To replicate the failure on main, duplicating the setup from the failing Circle job:
```shell
TEST_FILES=(spec/services/ccms/requestors/case_add_requestor_xml_blocks/non_passported_attributes_spec.rb
spec/requests/providers/partners/bank_statements_controller_spec.rb
spec/requests/pages_controller_spec.rb
spec/models/legal_aid_application_spec.rb)
bundle exec rspec --seed 56013 --fail-fast -- ${TEST_FILES}
```
This changes the test to expect the text in the same order
- Github should not be reporting conflicts; you should …
> Fix: Flickery linked Application proceeding test

- Gemfile
- Gemfile.lock
Since the last ruby update, each time rails starts, for testing, server, etc Their has been the following warning
> csv.rb was loaded from the standard library, but will no longer be part of the default gems since Ruby 3.4.0. Add csv to your Gemfile or gemspec.
Manually adding it to the gemfile should remove the warning and reduce the chance of the next ruby update failing …
> Chore: Add csv gem to remove deprecation warning

- app/controllers/providers/link_application/confirm_links_controller.rb
- app/forms/providers/link_application/confirm_link_form.rb
- app/forms/providers/link_application/make_link_form.rb
- app/services/flow/flows/provider_start.rb
- app/services/flow/steps/linked_applications/confirm_link_step.rb
- app/services/flow/steps/linked_applications/find_link_step.rb
- app/services/flow/steps/linked_applications/make_link_step.rb
- app/views/providers/check_provider_answers/_shared.html.erb
- app/views/providers/link_application/confirm_links/show.html.erb
- config/locales/en/activemodel.yml
- config/locales/en/providers.yml
- db/migrate/20240510114941_add_confirm_link_to_linked_application.rb
- db/schema.rb
- features/cassettes/Linking_cases_back_button_use/Complete_flow_reversion_with_back_button.yml
- features/providers/linked_applications/back_button.feature
- features/step_definitions/linked_cases_steps.rb
- spec/forms/providers/link_application/confirm_link_form_spec.rb
- spec/forms/providers/link_application/make_link_form_spec.rb
- spec/requests/providers/link_application/confirm_links_controller_spec.rb
- spec/requests/providers/link_application/find_link_applications_controller_spec.rb
- spec/requests/providers/link_application/make_links_controller_spec.rb
- spec/services/flow/steps/linked_applications/confirm_link_step_spec.rb
- spec/services/flow/steps/linked_applications/find_link_step_spec.rb
- spec/services/flow/steps/linked_applications/make_link_step_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4992)
This PR updates the views, forms and flow for each of the linking cases pages and updated to allow the use of back buttons, it also updates the CYA page to use the new values 
>[!NOTE]
A future PR will have to delete the linked_application if user has picked no
- The PR …
> AP-4992: Update linking case back button handling

- app/views/providers/check_provider_answers/_shared.html.erb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-5026)
Add condition remove any linked application information when linked cases feature flag is disabled
Update indentation …
> AP-5026: Linking cases displayed on cya pages when linked cases is disabled

- app/views/providers/proceeding_loop/delegated_functions/show.html.erb
- app/views/providers/proceeding_loop/substantive_defaults/show.html.erb
Remove custom spacing so default spacing is used on the `substantive_defaults` and `delegated_functions` pages
Agreed with designers
- …
> Chore: update proceeding loop spacing

- app/controllers/providers/check_provider_answers_controller.rb
- db/migrate/20240514091845_rename_link_case_to_case_cloned_on_legal_aid_application.rb
- db/schema.rb
- features/step_definitions/linked_cases_steps.rb
- spec/requests/providers/check_provider_answers_controller_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-5005)
This implements a call to the cloner service when the provider clicks continue on the Check Provider Answers page
It also deletes the lead_linked_application object if the provider has selected `no` to linking or changed their mind on the confirm_link page …
> AP-5005: Implement cloner service

- app/controllers/providers/check_provider_answers_controller.rb
- app/helpers/task_list_helper.rb
- app/services/flow/flows/provider_capital.rb
- app/services/flow/flows/provider_start.rb
- app/services/flow/steps/provider_capital/capital_assessment_results_step.rb
- app/services/flow/steps/provider_capital/capital_income_assessment_results_step.rb
- app/services/flow/steps/provider_start/confirm_non_means_tested_application_step.rb
- db/migrate/20240514091845_rename_link_case_to_case_cloned_on_legal_aid_application.rb
- db/schema.rb
- features/step_definitions/linked_cases_steps.rb
- spec/helpers/task_list_helper_spec.rb
- spec/requests/providers/capital_assessment_results_controller_spec.rb
- spec/requests/providers/capital_income_assessment_results_controller_spec.rb
- spec/requests/providers/check_provider_answers_controller_spec.rb
- spec/requests/providers/confirm_non_means_tested_applications_controller_spec.rb
- spec/services/flow/steps/provider_capital/capital_assessment_results_step_spec.rb
- spec/services/flow/steps/provider_capital/capital_income_assessment_results_step_spec.rb
- spec/services/flow/steps/provider_start/confirm_non_means_tested_application_step_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4942)
- Updated routing in 3 places to bypass merits task list for copied cases and go directly to the merits cya page.
- This reflects routing for passported, means-tested and non-means tested applications.
- The TaskListHelper which is used by the opponent_details partial on the merits cya page relies on legal_aid_application.legal_framework_merits_task_list however this is currently nil for copied cases. A workaround has been introduced on this ticket to obtain it from the copied application. However, a ticket has been created AP-5023 to add legal_framework_merits_task_list to the cloner service. …
> Ap 4942 update merits routing copied cases

- app/services/flow/flows/provider_dependants.rb
- app/services/flow/steps/provider_dependants/dependants_step.rb
- app/services/flow/steps/provider_dependants/has_dependants_step.rb
- app/services/flow/steps/provider_dependants/has_other_dependants_step.rb
- app/services/flow/steps/provider_dependants/remove_dependants_step.rb
- spec/requests/providers/means/dependants_controller_spec.rb
- spec/requests/providers/means/has_dependants_controller_spec.rb
- spec/requests/providers/means/has_other_dependants_controller_spec.rb
- spec/requests/providers/means/remove_dependants_controller_spec.rb
- spec/services/flow/steps/provider_dependants/dependants_step_spec.rb
- spec/services/flow/steps/provider_dependants/has_dependants_step_spec.rb
- spec/services/flow/steps/provider_dependants/has_other_dependants_step_spec.rb
- spec/services/flow/steps/provider_dependants/remove_dependants_step_spec.rb
[Flow refactoring - provider_dependants flow](https://dsdmoj.atlassian.net/browse/AP-4670)
- You should …
> AP-4670-flow-refactoring-provider-dependants

- app/services/flow/flows/provider_means_state_benefits.rb
- app/services/flow/steps/provider_means_state_benefits/add_other_state_benefits_step.rb
- app/services/flow/steps/provider_means_state_benefits/receives_state_benefits_step.rb
- app/services/flow/steps/provider_means_state_benefits/state_benefits_step.rb
- spec/requests/providers/means/add_other_state_benefits_controller_spec.rb
- spec/requests/providers/means/receives_state_benefits_controller_spec.rb
- spec/requests/providers/means/state_benefits_controller_spec.rb
- spec/services/flow/steps/provider_means_state_benefits/add_other_state_benefits_step_spec.rb
- spec/services/flow/steps/provider_means_state_benefits/receives_state_benefits_step_spec.rb
- spec/services/flow/steps/provider_means_state_benefits/state_benefits_step_spec.rb
[Flow refactoring - provider_means_state_benefits flow](https://dsdmoj.atlassian.net/browse/AP-4673)
Refactor the provider_means_state_benefits flow steps into individual step classes. …
> AP-4673: refactor receives_state_benefits_step

- app/views/providers/merits_task_lists/show.html.erb
- config/locales/en/providers.yml
- spec/requests/providers/merits_task_lists_controller_spec.rb
- Amended headings to match designs
- Added "No more information is needed" text where there are no additional merits questions associated with the proceeding".
- Can be tested (locally) by using this url for LFA ap-5029-spike-lfa-proceeding-w-legal-framework-uat.cloud-platform.service.justice.gov.uk
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4660) …
> ap-4660: merits task list content changes to headings and

- .github/workflows/docker-image-scan.yml
The scan job was running at the same time as the base-docker-image job so, if a new build is scheduled that fixes a security incident, the fixes won't be picked up until the following day.
It now runs 30 minutes after the base-docker-image job so that it should be testing the newest build each day
This also adds a workflow dispatch trigger so we can run manually if needed, like today! …
> Chore: Update docker scan action

- app/controllers/providers/provider_base_controller.rb
- app/controllers/providers/submitted_applications_controller.rb
- app/views/providers/submitted_applications/show.html.erb
- config/locales/en/providers.yml
- spec/requests/providers/submitted_applications_controller_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-5045)
Update theSubmitted Application page to show a banner if _other_ applications have retrospectively selected it as a lead application …
> AP-5045: Update SubmittedApplication view with link banner

- app/controllers/providers/correspondence_address/choices_controller.rb
- app/forms/addresses/choice_form.rb
- app/models/applicant.rb
- app/services/flow/flows/provider_start.rb
- app/services/flow/steps/addresses/correspondence_address_choices_step.rb
- app/services/flow/steps/provider_start/applicant_details_step.rb
- app/services/flow/steps/provider_start/applicants_step.rb
- app/views/providers/check_provider_answers/_shared.html.erb
- app/views/providers/correspondence_address/choices/show.html.erb
- app/views/shared/check_answers/_client_details.html.erb
- app/views/shared/review_application/_questions_and_answers.html.erb
- config/locales/en/activemodel.yml
- config/locales/en/providers.yml
- config/locales/en/shared.yml
- config/routes.rb
- db/migrate/20240531070655_add_correspondence_address_choice_to_applicant.rb
- db/schema.rb
- features/providers/linked_applications/back_button.feature
- spec/forms/addresses/choice_form_spec.rb
- spec/requests/providers/correspondence_address/choices_controller_spec.rb
- spec/services/flow/steps/addresses/correspondence_address_choices_step_spec.rb
- spec/services/flow/steps/provider_start/applicant_details_step_spec.rb
- spec/services/flow/steps/provider_start/applicants_step_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-5038)
This PR adds the new correspondence choice page for the updated home address flow.  
It updates the existing flow when the flag is enabled to route to the new page and move onto to the next pages as defined in the figma file …
> AP-5038: Add where_to_send_correspondence page

- app/controllers/providers/address_lookups_base_controller.rb
- app/views/shared/_address_lookup.html.erb
- config/locales/en/providers.yml
- config/locales/en/shared.yml
- spec/requests/providers/home_address/lookups_controller_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-5042)
Add another condition for rendering non uk home address link
- You should …
> AP-5042: Non UK home address link

- app/models/legal_aid_application.rb
- config/ccms/attribute_block_configs/base.yml
- spec/services/ccms/requestors/case_add_requestor_xml_blocks/passported_attributes_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-5061)
It was set up to add partner details if applicant_has_partner was true but if the partner has a contrary interest we do not save values
This changes the CCMS builders to only add them if applicant_has_partner_with_no_contrary_interest is true as then the partner values should exist …
> AP-5061: Update CCMS partner handling

- app/controllers/providers/proceedings_sca/interrupts_controller.rb
- app/views/providers/proceedings_sca/interrupts/show.html.erb
- config/initializers/inflections.rb
- config/locales/en/providers.yml
- config/routes.rb
- spec/requests/providers/proceedings_sca/interrupts_controller_spec.rb
Implement an SCA interrupt page as we need a standard page we can use for each question …
> Chore: SCA interrupt page

- app/forms/providers/link_application/make_link_form.rb
- app/services/flow/steps/linked_applications/confirm_link_step.rb
- spec/forms/providers/link_application/make_link_form_spec.rb
- spec/services/flow/steps/linked_applications/confirm_link_step_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-5075)
Update the link case flow, ensure when then link_case_confirm page is reached that the `No` option is no pre-selected
When a use clicks on the `No, I want to link to a different case` option they are taken to the search page, not the link_type page …
> AP-5075: update link case confirm page

- config/locales/en/providers.yml
- spec/requests/providers/proceedings_sca/heard_as_alternatives_controller_spec.rb
Add quotes to `heard_as_alternative` page that were missed off previous ticket …
> Chore: add quotes to heard_as_alternative page

- app/forms/providers/link_application/make_link_form.rb
- app/views/shared/check_answers/_linking_and_copying.html.erb
- spec/forms/providers/link_application/make_link_form_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-5076)
- Copy case info removed from CYA page when legal link is selected
- When family link is chosen and case is copied, but then link is changed to legal link, copying information is removed
- …
> AP-5076: Remove copy info from CYA when legal link

- app/controllers/providers/proceedings_sca/heard_togethers_controller.rb
- spec/requests/providers/proceedings_sca/heard_togethers_controller_spec.rb
Rack gem update renamed the unprocessable_* status from entity to content while this was being developed …
> Fix unprocessable-entity

- app/views/providers/proceedings_types/index.html.erb
- features/providers/linked_applications/check_your_answers_link_and_copy.feature
[Link to story](https://dsdmoj.atlassian.net/browse/AP-5077)
Fix no back button on proceeding page after link change …
> AP-5077: No back link on proceeding page after link change

- app/views/providers/proceedings_sca/heard_togethers/show.html.erb
- config/locales/en/providers.yml
- spec/requests/providers/proceedings_sca/heard_togethers_controller_spec.rb
During the many rebases of SCA questions the page title and headings got a bit jumbled and started to cause i18n warnings
This clarifies the page title and heading and ensures that warnings are removed and that the tab renders with the expected text …
> Fix: broken page title

- package.json
- yarn.lock
There is a security alert on `ws` but `pupetteer` had a locked version of `ws` preventing the update.  
This PR should either install the updated `ws` or allow the upgraded `ws` version to be deployed by dependabot …
> Fix: Update puppeteer to bump ws

- app/models/legal_aid_application.rb
- app/views/providers/confirm_non_means_tested_applications/show.html.erb
- config/locales/en/providers.yml
- spec/factories/legal_aid_applications.rb
- spec/models/legal_aid_application_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-5096)
Add a means test interrupt page for SCA proceedings.
When the application is non-means tested, route to the interrupt page and then on to the merits task list page
Note: The merits task list page will be empty as we have not added those into LFA yet …
> AP-5096: SCA means test interrupt

- app/controllers/providers/link_application/confirm_links_controller.rb
- spec/requests/providers/link_application/confirm_links_controller_spec.rb
with no linked application
[Link to story](https://dsdmoj.atlassian.net/browse/AP-5105)
- You should …
> ap-5105: fix error when clicking save as draft on Search Results page

- app/views/providers/has_national_insurance_numbers/show.html.erb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4622)
Remove NINO hint text when there is SCA proceeding
Move hint text into govuk fieldset component …
> AP-4622: Remove NINO hint text when there is SCA proceeding

- spec/services/flow/steps/provider_capital/applicant_bank_accounts_step_spec.rb
This test failed on a [circle ci](https://app.circleci.com/pipelines/github/ministryofjustice/laa-apply-for-legal-aid/28900/workflows/43c274e1-a637-45e0-9b98-50b96846fd80/jobs/151445) run and was reproducible locally.  
This issue seems to sometimes fail and sometimes only warn which is a bit weird, but this update definitely fixes a reproducible flicker …
> Fix: Flickery step test

- app/forms/vehicles/details_form.rb
- app/services/flow/steps/provider_capital/vehicle_details_step.rb
- spec/forms/vehicles/details_form_spec.rb
- spec/services/flow/steps/provider_capital/vehicle_details_step_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-5094)
See ticket for steps to recreate
This pr attempts to prevent the application from creating a second vehicle (wrongly) when the user has clicked save_as_draft on the vehicle details page and returns to the application. …
> ap-5094-attept-to-fix-vehicle-details-error

- app/models/applicant.rb
- app/services/ccms/attribute_value_generator.rb
- app/services/ccms/requestors/case_add_requestor.rb
- spec/factories/applicants.rb
- spec/models/applicant_spec.rb
- spec/requests/providers/check_provider_answers_controller_spec.rb
- spec/requests/providers/correspondence_address/care_ofs_controller_spec.rb
- spec/services/ccms/requestors/case_add_requestor_spec.rb
- spec/services/ccms/requestors/case_add_requestor_xml_blocks/non_means_tested_attributes_spec.rb
- spec/services/ccms/requestors/case_add_requestor_xml_blocks/passported_attributes_spec.rb
- spec/services/ccms/submitters/add_applicant_service_spec.rb
- spec/services/flow/steps/provider_capital/applicant_bank_accounts_step_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-5083)
This PR updates the applicant model to update and add home_ and correspondence_address_for_ccms methods
These implement logic that should work for applications created before, during, or after the home_address flag is enabled. 
It updates CCMS tests to use, and expect, the new methods rather than just `applicant.address` or `applicant.home_address`
It also adds a temporary trait and uses it to make some tests pass
- The standards in the [Git Workflow document on Confluence](https://dsdmoj.atlassian.net/wiki/spaces/ATPPB/pages/4602855954/Git+W …
> AP-5083: Update CCMS home address payloads

- app/controllers/providers/link_application/copies_controller.rb
- app/forms/providers/link_application/copy_form.rb
- app/forms/providers/link_application/find_link_application_form.rb
- app/helpers/linked_applications_helper.rb
- app/models/legal_aid_application.rb
- app/models/linked_application.rb
- app/views/providers/link_application/confirm_links/show.html.erb
- app/views/providers/link_application/copies/show.html.erb
- app/views/shared/check_answers/_linking_and_copying.html.erb
- db/migrate/20240627104142_add_target_application_to_linked_applications.rb
- db/schema.rb
- features/step_definitions/linked_cases_steps.rb
- spec/factories/legal_aid_applications.rb
- spec/forms/providers/link_application/copy_form_spec.rb
- spec/forms/providers/link_application/find_link_application_form_spec.rb
- spec/helpers/linked_applications_helper_spec.rb
- spec/models/linked_application_spec.rb
- spec/requests/providers/link_application/confirm_links_controller_spec.rb
- spec/requests/providers/link_application/copies_controller_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-5107)
This PR extends the linked_application model to set a target_application as well as a lead_application.
This should allow us to display the link to data on the link search result page:
As well as having a flattened lead_application structure:
So, when creating Application G, we could link to, and optionally copy data from, Application C. While setting Application A as the lead application as CCMS requires this
- The standards in the [Git Workflow document on Confluence](https://dsdmoj.atlassian.net/wiki/spaces/ATPPB/pages/4602855954/Git+Workf …
> AP-5107: Update case link handling

- app/controllers/admin/reports_controller.rb
- app/models/application_digest.rb
- app/services/reports/mis/application_detail_csv_line.rb
- app/views/admin/reports/index.html.erb
- db/migrate/20240702132532_add_new_fields_to_application_digest.rb
- db/schema.rb
- spec/models/application_digest_spec.rb
- spec/services/reports/mis/application_detail_csv_line_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-5095)
This PR adds the following columns to both the overnight digest generation and the Application report
- has_partner? 
- contrary_interest? 
- partner_dwp_challenge?
- applicant_age
- non_means_tested? 
As the data is getting more complex, it also adds a link to the reports page to allow a link to confluence to help users interpret the contained within the report …
> AP-5095: Add partner data to reports

- app/services/legal_framework/merits_tasks_service.rb
While investigating AP-5030 the FULL_SECTION_8_TASKS stood out as something that is superflouous.
It was added when we implemented the Section 8 matter type and has been superseded by the new `ignore_questions` method.  Previously we would ignore questions included in the array, now we ignore them if values haven't been added into the task list locale collection. This is easier to update (add a new value to the locale file when adding new questions) and less prone to atrophy as the array needs to change …
> Chore: Update MeritsTaskService

- app/controllers/providers/proceeding_loop/substantive_defaults_controller.rb
- app/forms/proceedings/substantive_defaults_form.rb
- app/models/proceeding.rb
- app/services/flow/steps/provider_proceeding_loop/substantive_defaults_step.rb
- app/views/providers/proceeding_loop/substantive_defaults/show.html.erb
- spec/cassettes/Proceedings_SubstantiveDefaultsForm/_save/with_a_Special_Childrens_Act_proceeding/sets_the_default_values.yml
- spec/cassettes/Proceedings_SubstantiveDefaultsForm/_save/with_a_Special_Childrens_Act_proceeding/without_calling_the_subject/creates_a_scope_limitation_object.yml
- spec/forms/proceedings/substantive_defaults_form_spec.rb
- spec/requests/providers/proceeding_loop/substantive_defaults_controller_spec.rb
- spec/services/flow/steps/provider_proceeding_loop/substantive_defaults_step_spec.rb
Do not display the Do you want to use the default level of service or scope for the substantive application? question for SCA applications.
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4572)
- Removed question from substantive_defaults view for SCA proceedings.
- Updated flow logic so that SCA proceedings should behave as if the user selected Yes to accept the substantive defaults
- Updated form logic so that SCA proceedings should behave as if the user selected Yes to accept the substantive defaults in terms of updating the default service level and scope limitations.
- The standards in the …
> ap-4752: Remove the do you want to use the default level of service or scope for the substantive application? question

- app/controllers/providers/partners/bank_statements_controller.rb
- app/controllers/v1/partners/bank_statements_controller.rb
- app/forms/providers/partners/bank_statement_form.rb
- app/models/legal_aid_application.rb
- app/services/ccms/requestors/document_id_requestor.rb
- app/services/ccms/requestors/document_upload_requestor.rb
- app/services/required_document_category_analyser.rb
- app/validators/document_category_validator.rb
- app/views/providers/capital_income_assessment_results/_result_details.html.erb
- app/views/providers/means/check_income_answers/_partner_income_assessment.html.erb
- app/views/providers/means_reports/_with_cfe_result_details.html.erb
- app/views/providers/partners/bank_statements/show.html.erb
- app/views/shared/review_application/_partner_income.erb
- config/locales/en/activemodel.yml
- config/locales/en/providers.yml
- config/locales/en/shared.yml
- db/seeds/document_categories.csv
- lib/tasks/migrate_partner_attachments.rake
- spec/factories/attachments.rb
- spec/models/document_category_spec.rb
- spec/requests/providers/partners/bank_statements_controller_spec.rb
- spec/requests/v1/partners/bank_statements_spec.rb
- spec/services/ccms/requestors/document_id_requestor_spec.rb
- spec/services/ccms/requestors/document_upload_requestor_spec.rb
- spec/services/ccms/submitters/obtain_document_id_service_spec.rb
- spec/services/required_document_category_analyser_spec.rb
- spec/validators/document_category_validator_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-5141)
The default file names for partner uploads were too long to send, via SOA, into CCMS
This PR shortens the file names
Should work!
New names are less understandable …
> AP-5141: Change partner file name lengths

- app/services/required_document_category_analyser.rb
- app/validators/document_category_validator.rb
- config/locales/en/activemodel.yml
- config/locales/en/providers.yml
- db/seeds/document_categories.csv
- spec/models/document_category_spec.rb
- spec/services/required_document_category_analyser_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4641)
This PR adds a new document type, `parental_responsibility`, and ensures it is added to the required_document list for the upload evidence page  …
> AP-4641: Add sca evidence upload

- app/services/flow/flows/provider_income.rb
- app/services/flow/steps/provider_income/cash_outgoings_step.rb
- app/services/flow/steps/provider_income/check_income_answers_step.rb
- app/services/flow/steps/provider_income/housing_benefits_step.rb
- app/services/flow/steps/provider_income/identify_types_of_outgoings_step.rb
- app/services/flow/steps/provider_income/outgoing_transactions_step.rb
- app/services/flow/steps/provider_income/outgoings_summary_step.rb
- app/services/flow/steps/provider_income/regular_outgoings_step.rb
- spec/requests/providers/means/cash_outgoings_controller_spec.rb
- spec/requests/providers/means/check_income_answers_controller_spec.rb
- spec/requests/providers/means/housing_benefits_controller_spec.rb
- spec/requests/providers/means/identify_types_of_outgoings_controller_spec.rb
- spec/requests/providers/means/regular_outgoings_controller_spec.rb
- spec/requests/providers/outgoings_summary_controller_spec.rb
- spec/services/flow/steps/provider_income/cash_outgoings_step_spec.rb
- spec/services/flow/steps/provider_income/check_income_answers_step_spec.rb
- spec/services/flow/steps/provider_income/housing_benefits_step_spec.rb
- spec/services/flow/steps/provider_income/identify_types_of_outgoings_step_spec.rb
- spec/services/flow/steps/provider_income/outgoing_transactions_step_spec.rb
- spec/services/flow/steps/provider_income/outgoings_summary_step_spec.rb
- spec/services/flow/steps/provider_income/regular_outgoings_step_spec.rb
[Flow refactoring - provider_capital - outgoings steps (7)](https://dsdmoj.atlassian.net/browse/AP-4672)
Refactor the provider_capital outgoings flow/steps into individual step classes. 
Steps:
- identify_types_of_outgoings
- outgoings_summary
- outgoings_transactions
- regular_outgoings
- cash_outgoings
- housing_benefits
- check_income_answers …
> AP-4672: Flow refactor provider_capital outgoings steps

- app/services/flow/flow_steps.rb
urls class method is no longer being used or tested since final flow step refactor. Remove to fix coverage. …
> Fix code coverage: remove urls method from flow_steps class

- app/assets/stylesheets/check-your-answers.scss
- app/assets/stylesheets/language-switcher.scss
- app/assets/stylesheets/sort-transactions.scss
- app/assets/stylesheets/tables.scss
This resequences the includes in line with the guidance from sass on [their website](https://sass-lang.com/documentation/breaking-changes/mixed-decls/)
No deprecation warnings are now outputted when running the `yarn build:css` command
- You should …
> Chore: Reduce Sass deprecation warnings

- app/services/flow/proceeding_loop.rb
- app/services/query/incomplete_proceedings.rb
- spec/factories/proceedings.rb
- spec/services/query/incomplete_proceedings_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-5152)
- Proceeding loop expects `accepted_substantive_defaults` not to be null to proceed. As this is not set for SCA proceedings, proceeding loop doesn't proceed. Update SQL query to fix this and spec to cover this scenario.
- Add safe navigation operator when calling `IncompleteProceedings` as it sometimes returns nil. …
> AP-5152: Fix proceeding loop bug

- app/views/providers/proceeding_merits_task/check_who_client_is/show.html.erb
- app/views/shared/check_answers/_merits.html.erb
- app/views/shared/check_answers/_merits_proceeding_section.html.erb
- app/views/shared/check_answers/_opponent_details.html.erb
- app/views/shared/check_answers/_relationship_to_child.html.erb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-5145)
This pr fixes the errors that were preventing the merits cya page from being displayed for SCA applications and adds the relationship to child question to the page.
It does not update the page to use the new styling. …
> ap-5145: fix merits cya

- .github/dependabot.yml
Enable all GOVUK* gems to be updated together.
> Chore: Add GOVUK dependabot bundler group

- app/services/benefit_check_service.rb
- spec/services/benefit_check_service_spec.rb
AlertManager is expecting an exception not a string when the benefit check call fails (e.g. see https://ministryofjustice.sentry.io/issues/5325010673/events/a416dcfa6f224e11874b755399f6acaa/?project=5416054&query=is%3Aunresolved+issue.priority%3A%5Bhigh%2C+medium%5D&referrer=next-event&statsPeriod=14d&stream_index=0) …
> Fix benefit checker error handling

- app/controllers/providers/confirm_dwp_non_passported_applications_controller.rb
- app/models/application_digest.rb
- app/services/reports/mis/application_detail_csv_line.rb
- db/migrate/20240722082922_add_shared_benefit_column_to_applicant.rb
- db/schema.rb
- spec/models/application_digest_spec.rb
- spec/requests/providers/confirm_dwp_non_passported_applications_controller_spec.rb
- spec/services/reports/mis/application_detail_csv_line_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-5136)
This stores the shared benefit override answer on the applicant as well as the partner
This caused issues with reporting when the partner has a contrary interest and the answer was only stored on the partner model, it was unavailable
Now we record on, and check, both models and improve the reporting accuracy
We _could_ remove the partner handling but that should probably be a separate ticket as it would be out of the scope of a bug fix ticket …
> AP-5136: Store dwp partner override on applicant too

- config/initializers/grover.rb
After chromium updated to 127+ grover stopped generating PDFs, it would hang and eventually fail.  After testing the interactions between Alpine, Chromium, Puppeteer and Grover for many days, we identified this as a working fix
Further work is needed to ensure that the issue cannot get deployed to production, but this fix will allow us to resume merging and deploying fixes, while we investigate that solution more …
> AP-5195: PDF generation bug fix

- .circleci/config.yml
- docker/apply_base.dockerfile
Lock the puppeteer version at 22.15
This will allow us to test, build and deploy while we investigate the changes needed to update puppeteer to 23+ …
> Chore: Test Grover

- app/controllers/concerns/providers/draftable.rb
- app/controllers/providers/proceeding_merits_task/check_who_client_is_controller.rb
- app/controllers/providers/proceeding_merits_task/does_client_have_parental_responsibilities_controller.rb
- app/controllers/providers/proceeding_merits_task/is_client_biological_parent_controller.rb
- app/controllers/providers/proceeding_merits_task/is_client_child_subject_controller.rb
- app/models/concerns/base_state_machine.rb
- app/models/concerns/non_means_tested_state_machine.rb
- app/models/legal_aid_application.rb
- app/services/flow/steps/provider_merits/biological_parent_step.rb
- app/services/flow/steps/provider_merits/child_subject_step.rb
- app/services/flow/steps/provider_merits/parental_responsibilities_step.rb
- spec/concerns/non_means_tested_state_machine_spec.rb
- spec/factories/legal_aid_applications.rb
- spec/requests/providers/proceeding_merits_task/check_who_client_is_controller_spec.rb
- spec/requests/providers/proceeding_merits_task/does_client_have_parental_responsibilities_controller_spec.rb
- spec/requests/providers/proceeding_merits_task/is_client_biological_parent_controller_spec.rb
- spec/requests/providers/proceeding_merits_task/is_client_child_subject_controller_spec.rb
- spec/services/flow/steps/provider_merits/biological_parent_step_spec.rb
- spec/services/flow/steps/provider_merits/child_subject_step_spec.rb
- spec/services/flow/steps/provider_merits/parental_responsibilities_step_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-5154)
This PR changes the forms for parental responsibility. 
It uses changes to the state machine to track a) the start of the parental_responsibility questions and b) when all answers are no
It adds a global splat variable to the `update_task_save_continue_or_draft` draftable method so we can pass a value that allows the flow to route accordingly …
> AP-5154: Revisit SCA parental relationship CYA

- app/models/applicant.rb
- app/models/bank_transaction.rb
- app/models/dependant.rb
- app/models/feedback.rb
- app/models/final_hearing.rb
- app/models/legal_aid_application.rb
- app/models/proceeding_merits_task/chances_of_success.rb
- app/models/scope_limitation.rb
Update Enum handling to use new pattern.  This will be required for Rails 8 and has deprecation warnings for Rails 7.2+
Adding it now to reduce cognitive load on the Rails 7.2 upgrade PR …
> Chore: Prepare for Rails 7.2

- config/locales/en/enums.yml
This happnened locally and only breaks teh amdin pages If a Provider has an application at the parental relationship questions on an SCA task list, the admin page breaks.  This adds the two new states into the enums and enables the admin list to work as expected …
> Fix: State enums

- app/services/flow/steps/addresses/correspondence_address_manuals_step.rb
- app/services/flow/steps/addresses/correspondence_address_selections_step.rb
- features/providers/check_provider_answers.feature
- spec/services/flow/steps/addresses/correspondence_address_manuals_step_spec.rb
- spec/services/flow/steps/addresses/correspondence_address_selections_step_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-5222)
- Ask 'care of' question if user changes their mind on CYA about sending correspondence to client's home address, as per figma
- Update specs and feature tests to reflect changes
- Remove now duplicate feature test. …
> AP-5222: Ask 'care of' question after cya page

- app/helpers/check_provider_answers_helper.rb
- app/views/shared/check_answers/_client_details.html.erb
- features/providers/check_provider_answers.feature
- features/step_definitions/civil_journey_steps.rb
- spec/helpers/check_provider_answers_helper_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-5221)
- Update change links for addresses on "check provider answers" page
- Update specs and feature tests to reflect changes
- Remove outdated feature test
- Add feature test for new scenario …
> AP-5221: Update change links

- app/views/providers/link_application/confirm_links/show.html.erb
- app/views/providers/link_application/copies/show.html.erb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-5219)
Update spacing to make consistent and use default margins.
Screenshots:
- …
> AP-5219: Update spacing to make consistent and use default margins

- app/views/providers/link_application/find_link_applications/show.html.erb
Changes made as suggested in the design system:
- Add extra letter spacing
- Make the text box smaller
Also changed text to hint text
Screenshot: …
> Chore: minor visual changes to ref num search page

- app/views/providers/proceedings_sca/heard_as_alternatives/show.html.erb
- app/views/providers/proceedings_sca/heard_togethers/show.html.erb
- config/locales/en/providers.yml
- spec/requests/providers/proceedings_sca/heard_as_alternatives_controller_spec.rb
- spec/requests/providers/proceedings_sca/heard_togethers_controller_spec.rb
`core` is a descriptive term only used by the Civil Apply team, using it on provider pages could cause confusion 
This PR ensures we have consistent page titles, H1's and error messages on the two SCA proceeding loop questions …
> AP-5149: Update SCA proceeding questions to remove core

- app/controllers/providers/limitations_controller.rb
- app/models/legal_aid_application.rb
- app/services/copy_case/cloner_service.rb
- app/views/providers/limitations/_cost_limits.html.erb
- app/views/providers/limitations/show.html.erb
- app/views/providers/proceedings_sca/supervision_orders/show.html.erb
- config/locales/en/providers.yml
- features/providers/linked_applications/check_your_answers_link_and_copy.feature
- spec/models/legal_aid_application_spec.rb
- spec/services/copy_case/cloner_service_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-5142)
Updated logic to zero cost limitations for family associated linked applications.
Added additional details panel to limitations page for non family associated linked applications.
This should automatically update the CCMS payload with the 0 default subsantive cost limit for associated family linked applications.
NB additional BA work required to determine whether the merits report needs to be updated with the 0 emergency cost limit for associated family linked applications. …
> Ap 5142 zero cost limits associated applications

- app/forms/proceedings/substantive_defaults_form.rb
- app/views/shared/check_answers/_proceeding_details.html.erb
- config/locales/en/shared.yml
- spec/factories/proceedings.rb
- spec/forms/proceedings/substantive_defaults_form_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-5273)
Update the SubstantiveDefaultsForm handling of the default level of service
On a non-sca proceeding the view stores default values and passes them as controller params to the form.  
The SCA skip removed the submission of these and meant that the default LOS was not set
This updates the test to ensure the proceeding is instantiated in the same way that it occurs in the controller, i.e. no default values populated for the three substantive default level of service fields. It then updates the form to set the value using the values called from LFA and stored as form values …
> AP-5273: SCA level of service fix

- app/views/providers/has_other_proceedings/show.html.erb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-5257)
Add matter type and category of law to added proceedings page as per designs in the ticket
Screenshot: …
> AP-5257: Add matter type and category of law to added proceedings page

- app/controllers/providers/check_provider_answers_controller.rb
- app/views/providers/check_provider_answers/_standard.html.erb
- app/views/shared/check_answers/_linking_and_copying.html.erb
- spec/requests/providers/check_provider_answers_controller_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-5230)
- Delete linked applications if confirm_link != true. NB in order for the back link to work as expected we do not actually delete the linked applciation record until the provider goes past the cya page.
- Hide linked applications on the cya page if confirm_link != true
- The …
> Ap 5230 link cannot be removed

- app/controllers/admin/settings_controller.rb
- app/forms/settings/setting_form.rb
- app/views/admin/settings/show.html.erb
- config/locales/en/admin.yml
Remove remaining home address feature flag code
> Chore: remove remaining home address feature flag code

- app/services/flow/proceeding_loop.rb
- app/services/query/incomplete_proceedings.rb
- app/views/providers/check_provider_answers/_shared.html.erb
- app/views/providers/legal_aid_applications/_legal_aid_applications.html.erb
- app/views/providers/limitations/_proceeding_type.html.erb
- app/views/shared/check_answers/_proceeding_details.html.erb
- config/locales/en/providers.yml
- config/locales/en/shared.yml
- spec/services/flow/proceeding_loop_spec.rb
- spec/services/query/incomplete_proceedings_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-5231)
This updates the SCA flow to remove references to emergency certificates
* The ‘Emergency application’ page should not be shown
* The Check your answers page makes no reference to ‘Emergency’ scope or costs
* A new certificate type has been added to the Applications page
- The …
> AP-5231: SCA emergency references

- app/services/legal_framework/proceeding_types/all.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-5297)
When submitting the current proceedings to LFA it expects an array of proceeding codes, e.g. `["PB003", "PB019"]`
The previous (join) code in Apply was merging them and sending `["PB003, PB019"]`
This caused the proceeding search code to fail and would not match the individual codes, i.e. it could not find a proceeding with the code "PB003, PB019" and would return non-SCA data
- There …
> AP-5297: Fix proceeding search requests for SCA

- app/models/applicant.rb
- app/views/providers/proceeding_merits_task/check_who_client_is/show.html.erb
- app/views/shared/check_answers/_merits_proceeding_section.html.erb
- app/views/shared/check_answers/_relationship_to_child.html.erb
- spec/models/applicant_spec.rb
The merits report was failing for SCA applications (without a DF date) because it was unable to calculate the applicant's age to display. Use age_for_means_test_purposes attribute.
[Link to story](https://dsdmoj.atlassian.net/browse/AP-5168) …
> ap-5168: Fix sca merits report unable to display age

- config/govuk_notify_templates.yml
Remove notify feedback template config code
To do:
> Chore: remove notify feedback template config code

- app/views/providers/review_and_print_applications/show.html.erb
- config/locales/en/providers.yml
- features/providers/review_and_print.feature
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4642)
- Update content when application is means tested
- Minor content tidy up: change curly apostrophes to straight
Means tested:
Non means tested: …
> AP-4642: Update content when application is means tested

- app/views/providers/application_merits_task/in_scope_of_laspos/show.html.erb
Make 'in scope of laspo' page heading xl to be consistent with other pages
Screenshot: …
> Chore: make 'in scope of laspo' page heading consistent

- app/assets/stylesheets/providers/search_results.scss
[Link to story](https://dsdmoj.atlassian.net/browse/AP-5027)
Update govuk-link-right class to extend govuk-body so the link is the correct size
Screenshot: …
> AP-5027: Fix different change link sizes

- app/controllers/providers/merits_reports_controller.rb
- spec/requests/providers/merits_reports_controller_spec.rb
This was present on the means report, but never implemented on the merits report. 
This PR rectifies that so developers can check pdf appearance in browser …
> Chore: Add `?debug` handler to merits report

- app/services/ccms/manual_review_determiner.rb
- spec/services/ccms/manual_review_determiner_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4454)
In production a caseworker found an application where it had been flagged for caseworker review as the provider had overridden the dwp response.
In reality, they must have said yes, gone back and changed the client record and moved onto the passported flow.
A DWPOverride record was created but the questions had not been answered.
I was unable to replicate the steps needed to get the application into that state so this PR adds addition checks to the manual review determiner to ensure that we only flag an application when the object is present _and_ the questions have been answered
- Github should not be reporting conflicts; you …
> AP-4454: Fix for DWP Override means report review reason

- .github/workflows/base-docker-image.yml
- .github/workflows/ci-docker-image.yml
This was pinned at v1, upgraded to v3 to see if all alerts are removed when the job is run
The last time this ran on main: 
Run against this branch, it has removed all warnings …
> Chore: Update docker/login-action

- docker/apply_base.dockerfile
- package.json
- yarn.lock
Update the puppeteer version in the ApplyBase docker image
It got locked at 22.15 when the updates started to break everything.
We are now running 23.x and this PR includes the dependabot update to 23.4 to see if it matches what is used in the app
>[!IMPORTANT]
>We know that 22.15 was working, the temp commit allows us to have confidence 
that if we do a new daily apply build with the latest version, it will also work
>The temp commit will be removed before merging
- The standards in the [Git Workflow document on Confluence](https://dsdmoj.atlassian.net/wiki/spaces/ATPPB/pages/4602855954/Git+Workflow) …
> Chore: puppeteer update

- app/services/pda/compare_provider_details.rb
- app/services/pda/provider_details_creator.rb
- app/services/pda/provider_details_retriever.rb
- helm_deploy/apply-for-legal-aid/templates/NOTES.txt
- spec/cassettes/PDA_ProviderDetailsRetriever/_call/with_a_non_existent_user/returns_an_error.yml
- spec/cassettes/PDA_ProviderDetailsRetriever/_call/with_an_existing_user/returns_provider_details.yml
- spec/services/pda/compare_provider_details_spec.rb
- spec/services/pda/provider_details_creator_spec.rb
- spec/services/pda/provider_details_request_stubs.rb
- spec/services/pda/provider_details_retriever_spec.rb
Add and log firm offices from new PDA API
[Link to story](https://dsdmoj.atlassian.net/browse/AP-5307)
The existing PDA returns all offices in the providers firm as part of the "provider offices". The new PDA
only returns the offices of the specific individual provider (a person/user). To understand the impact and how
to handle it we want to compare all the offices in the firm of the specific provider from the new PDA with those coming from the old CCSM PDA.
The new PDA requires a second call to achieve this, so the relevant part of the response body of the second call has been merged with the response body of the first call and returned as a result object. …
> AP-5307: Add firm offices to new PDA result

- app/controllers/admin/settings_controller.rb
- app/forms/settings/setting_form.rb
- app/models/setting.rb
- app/views/admin/settings/show.html.erb
- config/locales/en/admin.yml
- db/migrate/20240923104047_add_means_test_review_a_to_settings.rb
- db/schema.rb
- spec/models/setting_spec.rb
- spec/requests/admin/settings_controller_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-5313)
Create MTR A feature flag …
> AP-5313: create MTR A feature flag

- app/views/shared/check_answers/_merits.html.erb
- app/views/shared/check_answers/_separate_representation.html.erb
- config/locales/en/shared.yml
[Link to story](https://dsdmoj.atlassian.net/browse/AP-5169)
Add separate representation required question to merits report.
Made sure this section doesn't appear on the CYA page or RTA page (which all use the same partials) by checking the application `summary_state`. …
> AP-5169 Add separate representation required to merits report

- app/javascript/src/modules/proceedings.js
[Link to story](https://dsdmoj.atlassian.net/browse/AP-5315)
When LFA returns a code that is not present on the page, i.e. an SCA related proceeding on an initial search, previously it showed the failure message and returned from the loop.
This updates the proceedings javascript so that it counts successfully displayed proceedings, using a new, `shown`, variable. After the loop is complete it then sets the ariaText and shows/hides the no-proceeding-items element accordingly.
- The standards in the [Git Workflow document on Confluence](https://dsdmoj.atlassian.net/wiki/spaces/ATPPB/pages/4602855954/Git+ …
> AP-5315: Fix SCA proceeding search bug

- app/models/bank_account.rb
- spec/models/bank_account_spec.rb
Handle nil meta_data for truelayer bank transactions
Caused by the bank_account_has_tax_credits? call of submission processor which fails
via the `bank_account.has_tax_credits?` method
```
Sidekiq/CCMS::SubmissionProcessWorker
undefined method `[]' for nil (NoMethodError)
map { |element| element[key] }
^^^^^
``` …
> Handle nil meta_data for truelayer bank transactions

- features/support/env.rb
Use javascript_strategy of :deletion only 
Local testing results show me a bit of an increase between a general `:truncation`
strategy and a javascript_strategy of `:deletion`, rather than truncation.
```
\# rails 7.1 transaction strategy only - baseline
cucumber  797.65s user 547.86s system 105% cpu 21:19.52 total
```
```
\# with strategy of truncation generally
cucumber  883.71s user 606.80s system 101% cpu 24:33.67 total
```
```
\# with javascript strategy of :truncation otherwise :transaction
cucumber  881.75s user 594.94s system 107% cpu 22:53.44 total
```
\* best performer for rails 7.2
```
\# with javascript strategy of :deletion otherwise :transaction
cucumber  836.40s user 561.81s system 115% cpu 20:10.36 total
```
- Tests and rubocop …
> Rails 7.2 bump with javascript strategy

- app/models/application_digest.rb
- app/services/reports/mis/application_detail_csv_line.rb
- db/migrate/20240930074635_add_address_to_digest.rb
- db/schema.rb
- spec/models/application_digest_spec.rb
- spec/services/reports/mis/application_detail_csv_line_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-5180)
Add tracking of `No fixed address` responses to the Application Digest and Admin reports …
> AP-5180: Client address tracking data

- app/services/reports/mis/application_detail_csv_line.rb
- spec/services/reports/mis/application_detail_csv_line_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-5329)
Add a true/false display to the admin report that shows whether the provider has recorded a previous CCMS reference to an application. …
> AP-5329: Add previous_reference to admin report

- app/assets/stylesheets/interruption-panel.scss
- app/helpers/flow_helper.rb
- app/views/providers/application_merits_task/has_other_involved_children/show.html.erb
- app/views/providers/check_benefits/index.html.erb
- app/views/providers/confirm_non_means_tested_applications/show.html.erb
- app/views/providers/interrupt/blocks/show.html.erb
- app/views/providers/no_national_insurance_numbers/show.html.erb
- app/views/providers/proceedings_sca/interrupts/show.html.erb
- app/views/shared/_use_ccms.html.erb
- app/views/shared/forms/_next_action_buttons.html.erb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4926)
Replace custom code for white button with `inverse: true` on button component …
> AP-4926: use white button component

- app/controllers/application_controller.rb
- app/controllers/concerns/providers/application_dependable.rb
- app/services/flow/steps/provider_capital/vehicle_details_step.rb
- spec/services/flow/steps/provider_capital/vehicle_details_step_spec.rb
Fix vehicle not found error
[Link to story](https://dsdmoj.atlassian.net/browse/AP-5365)
This was causing the application list/index for national legal service’s firm to
redirect to page not found as vehicle id had been stored with the value 'new' for
one of their firms applications. This resulted in an ActiveRecord::NotFound error
which is rescued at application controller level and redirected to the page_not_found. …
> AP-5365: Fix vehicle not found error

- Gemfile.lock
ran `bundle lock --add-platform ruby` and `bundle lock --add-platform x86_64-darwin` to ensure the gems needed by development osx machines and deployed linux containers are explicitly included …
> Chore: Update gemfile-lock with new darwin osx version

- app/services/populators/transaction_type_populator.rb
Stop updating student_loan `archived_at` date
[Came out of looking at story](https://dsdmoj.atlassian.net/browse/AP-5346)
This was causing the archived_at date to be updated with the current
date time everytime it is deployed.
Arguably we could/should remove this line entirely?! …
> Stop updating student_loan `archived_at` date

- app/controllers/providers/means/identify_types_of_incomes_controller.rb
- app/controllers/providers/means/identify_types_of_outgoings_controller.rb
- app/forms/providers/regular_transaction_form.rb
- config/locales/en/activemodel.yml
- config/locales/en/providers.yml
- spec/forms/providers/means/regular_income_form_spec.rb
- spec/forms/providers/means/regular_outgoings_form_spec.rb
- spec/forms/providers/partners/regular_income_form_spec.rb
- spec/forms/providers/partners/regular_outgoings_form_spec.rb
- spec/requests/providers/means/identify_types_of_incomes_controller_spec.rb
- spec/requests/providers/means/identify_types_of_outgoings_controller_spec.rb
Prevent none plus other checkbox selection when JS not enabled
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4707)
We rely on JS to deselect other regular income and outgoings checkboxes if the "none" checkbox option
is selected. Without JS, therefore, we need a validation that ensures "none" plus any other income/outgoing
cannot be saved.
This PR also ensures that selected checkboxes are re-rendered with user input when an error is encountered
and links the "none plus other" error to the checkbox list itself.
This change impacts the following forms:
- client regular income
- client regular outgoings 
- partner regular income
- partner regular outgoings (shown below)
Similar functionality applied to truelayer path  form equivalents - identify_types_of_income|outgoings
Before you …
> AP-4707: Prevent none plus other checkbox selection when JS not enabled

- app/controllers/citizens/consents_controller.rb
- app/views/shared/check_answers/_full_employment_details.html.erb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-3985)
Delete employment answer if citizen does not complete truelayer, so that this information is not displayed before the provider answers the question. The question is asked twice in this scenario - this is a quirk of the sequencing of the questions …
> AP-3985: Clear employment if citizen does not complete truelayer

- app/views/providers/transactions/show.html.erb
- features/providers/non_passported_journey/with_bank_transactions.feature
- features/step_definitions/generic_steps.rb
Fix truelayer category display
[Came out of](https://dsdmoj.atlassian.net/browse/AP-5336)
For already selected/categorised transactions the current app is
displaying the category of whatever transaction type (Benefits, Disregards,
Maintenance) you happen to be on the page for selecting, rather than the
actual category that it has already been categorised as.
On the select maintenance payments page already selected transactions appear as maintenance (same applies to any transaction type page you are on though)
With fix in place pre categorised transactions appear as what they were categorised as
- The …
> FIX: fix truelayer category display

- app/views/shared/_student_finances.html.erb
- app/views/shared/means/_regular_outgoing.html.erb
Update caption sizes to be consistent
> Chore: Update caption sizes to be consistent

- app/views/providers/means/own_homes/show.html.erb
- app/views/providers/means/property_details/show.html.erb
- app/views/shared/check_answers/_property.html.erb
- config/locales/en/providers.yml
- config/locales/en/shared.yml
- features/providers/mtr_accelerated/main_dwelling.feature
- spec/requests/providers/means/own_home_controller_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-5343)
Update the text descriptions for Main dwelling pages
This adds more variable switching on views (which I don't love) but most of them should be removeable in around a month when the MTR legislation goes live 🤞  …
> AP-5343: MTR accelerated measures - Main dwelling updates

- db/migrate/20241018070508_alter_foreign_key_on_benefit_check_result.rb
- db/migrate/20241018071246_validate_foreign_key_on_benefit_check_result.rb
- db/schema.rb
Add on delete cascade to benefit_check_result foreign key constraint
Was causing a database error when purging the application
```
ActiveRecord::InvalidForeignKey: PG::ForeignKeyViolation: ERROR:  update or delete on table "legal_aid_applications" violates foreign key constraint "fk_rails_d026359e92" on table "benefit_check_results" (ActiveRecord::InvalidForeignKey)
DETAIL:  Key (id)=(4166cd72-5ae3-4c30-ac85-69f7694fc73c) is still referenced from table "benefit_check_results".
```
- The standards in the [Git Workflow document on Confluence](https://dsdmoj.atlassian.net/wiki/spaces/ATPPB/pages/460285595 …
> Fix: Add on delete cascade to benefit_check_result fk

- .simplecov
- lib/tasks/digest.rake
- spec/lib/tasks/digest_spec.rb
Disable digest extract, export and reset on UAT
It just causes a lot of failed pods which eat up quotas.
This is to prevent the regular failures that branches
on UAT get which create pods that eat up our pod quota
and distract devs unnecessarily.
We can remove if we are want to actually change and test
on a branch. …
> Disable digest export on UAT

- app/services/govuk_emails/monitor.rb
- spec/services/govuk_emails/monitor_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-5080)
Turn off alerts and emails to apply team for undeliverable citizen_start emails only. …
> ap-5080: Do not alert apply team if citizen_start_email is undeliverable

- app/services/ccms/requestors/document_id_requestor.rb
- app/services/ccms/requestors/document_upload_requestor.rb
- db/migrate/20241018081039_update_document_categories.rb
- db/schema.rb
- db/seeds/document_categories.csv
- spec/services/ccms/requestors/document_id_requestor_spec.rb
- spec/services/ccms/requestors/document_upload_requestor_spec.rb
- spec/services/ccms/submitters/obtain_document_id_service_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-5404)
* Update the database to handle the file extension and free-text fields
* Update the seed data to ensure it matches the new document types and includes file extensions and additional text values
* Updates the DocumentIdRequestor and DocumentUploadRequestor classes to call the values in the database with fallbacks to ADMIN1 and default file extension if an unknown or legacy document type is presented
- The standards in the [Git Workflow document on Confluence](https://dsdmoj.atlassian.net/wiki/spaces/ATPPB/pages/4602855954/Git+Workflow) …
> AP-5404: Improve document naming

- app/views/shared/means/_cost_of_living_and_disregarded_benefits.html.erb
- config/locales/en/shared.yml
- features/providers/mtr_accelerated/disregard_list.feature
- features/step_definitions/bank_statement_upload_steps.rb
- features/step_definitions/civil_journey_steps.rb
> [!IMPORTANT]
> Must go in after [AP-5412](https://github.com/ministryofjustice/laa-apply-for-legal-aid/tree/ap-5412/amend-benefit-and-income-content) ✅ 
Amend the list of disregarded benefits behind mtra feature flag
[Link to story](https://dsdmoj.atlassian.net/browse/AP-5344)
This list can only change once MTRA goes live. There is also a minor content change to the detail text
that can go in without a flag (confirmed by designer).
- There …
> AP-5344: Amend list of disregarded benefits

- config/initializers/pagy.rb
- spec/requests/providers/legal_aid_applications_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-5436)
If e.g 11 applications exist, and there are 10 on each page, when the 11th is deleted, the application tried to redirect to page 2. Address this so it always redirects to page 1
- You …
> AP-5436: Stop redirecting to page that no longer exists

- app/helpers/task_list_helper.rb
- app/views/shared/check_answers/_merits_proceeding_section.html.erb
- features/providers/check_merits_answers.feature
- features/step_definitions/civil_journey_steps.rb
- spec/factories/legal_framework_merits_task_list.rb
- spec/factories/legal_framework_serialized_merits_task_list.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-5392)
Add a loop skip when the proceeding being displayed has no tasks on the merits_task_list …
> AP-5392: SCA update check merits answers

- lib/tasks/erblint.rake
Fix deprecated call to erblint 
```
Calling `erblint` is deprecated, please call the renamed executable `erb_lint` instead.
``` …
> Fix deprecated call to erblint

- app/models/concerns/delegated_functions.rb
- app/views/shared/check_answers/_client_details.html.erb
- app/views/shared/check_answers/_merits.html.erb
- app/views/shared/check_answers/_proceeding_details_section.html.erb
- app/views/shared/review_application/_questions_and_answers.html.erb
- features/providers/review_and_print.feature
- features/step_definitions/review_and_print_steps.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-5394)
Update the review_and_print and submitted_application pages:
* hide the email row from client if it is empty
* hide the emergency level of service and scope limits for SCA DF applications
* hide the Emergency cost limit block for SCA DF applications
* hide the separate representation block on the submitted_application page too.  It will _only_appear on the merits_report now 
- There …
> AP-5394: Update SCA review and print

- app/helpers/client_helper.rb
- app/views/shared/check_answers/_client_details.html.erb
- config/locales/en/generic.yml
- spec/helpers/client_helper_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-5395)
Create ClientHelper for means_tested display text and call it from the _client_details partial …
> AP-5395: Update SCA means_tested display on Means Report

- app/controllers/providers/means/capital_disregards/discretionary_controller.rb
- app/forms/providers/means/capital_disregards/discretionary_form.rb
- app/views/providers/means/capital_disregards/discretionary/show.html.erb
- config/locales/en/activemodel.yml
- features/providers/mtr_accelerated/discretionary_capital_disregards.feature
- spec/factories/applicants.rb
- spec/forms/providers/means/capital_disregards/discretionary_form_spec.rb
- spec/requests/providers/means/capital_disregards/discretionary_controller_spec.rb
Implement working discretionary disregards form for saving and displaying existing data.
[Link to story](https://dsdmoj.atlassian.net/browse/AP-5450)
The form as it previously existed was not reflecting selecting
disregards, synchronising of records (without a full delete).
Have used a separate pattern more similar to regular income/outgoings
because was seeing odd behaviour using the base form which does not
work well with a `has_many` relation per checkbox - it requires its own
intializer to handle its list of existing check box values, at least. …
> AP-5450: Working discretionary disregards form

- app/components/reports/merits/delegated_functions_component.rb
- app/views/providers/merits_reports/show.html.erb
- app/views/shared/check_answers/_merits_proceeding_section.html.erb
- app/views/shared/check_answers/_separate_representation.html.erb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-5396)
Update the merits report when handling SCA cases:
- Hide Emergency cost limit section for a backdated SCA application
- The delegated function section is now aligned to matchthe rest of the page
- The spacing above Separate representation has been corrected to match the other sections' spacing …
> AP-5396: Update SCA merits report

- app/controllers/providers/means/identify_types_of_incomes_controller.rb
- app/controllers/providers/means/identify_types_of_outgoings_controller.rb
- app/models/legal_aid_application.rb
- app/models/legal_aid_application_transaction_type.rb
- app/services/flow/steps/provider_income/identify_types_of_income_step.rb
- app/services/flow/steps/provider_income/identify_types_of_outgoings_step.rb
- app/views/providers/means/identify_types_of_incomes/show.html.erb
- app/views/providers/means/identify_types_of_outgoings/show.html.erb
- features/providers/regressions/client_truelayer_partner_bank_statements_check_means_answer.feature
- features/step_definitions/civil_journey_steps.rb
- features/step_definitions/regression_steps.rb
- spec/models/legal_aid_application_transaction_type_spec.rb
- spec/requests/providers/means/identify_types_of_incomes_controller_spec.rb
- spec/requests/providers/means/identify_types_of_outgoings_controller_spec.rb
- spec/services/flow/steps/provider_income/identify_types_of_income_step_spec.rb
- spec/services/flow/steps/provider_income/identify_types_of_outgoings_step_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-5453)
This PR addresses a bug found while working on #7340 where a user returning to the Payments your client receives page from CYA would see payments that had been selected for a partner too
While resolving that, another bug was found where a payment that has been assigned to a category which was subsequently removed, cannot be re-assigned to a category (new or the previous one if re-enabled)
- Update checkbox selection on incoming truelayer, CYA path
- Update meta-data handling after incoming and outgoing checkboxes are cleared
- Update checkbox selection on outgoing truelayer, CYA path
- Update CYA routing when a provider selects no payments
- Update routing after the identify_* pages, there were routes that _could_ be reached …
> AP-5453: CYA truelayer transaction bug

- app/forms/concerns/date_field_builder.rb
- spec/forms/applicants/basic_details_form_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-5398)
When the builder is reading the form values, it now strips leading and trailing spaces from the individual parts of the date …
> AP-5398: Update date_field_builder to handle spaces

- app/controllers/providers/means/receives_state_benefits_controller.rb
- app/controllers/providers/means/student_finances_controller.rb
- app/controllers/providers/partners/receives_state_benefits_controller.rb
- app/controllers/providers/partners/student_finances_controller.rb
- app/forms/providers/means/receives_state_benefits_form.rb
- app/forms/providers/partners/receives_state_benefits_form.rb
- app/forms/student_finances/base_student_finance_form.rb
- app/services/flow/steps/partner/receives_state_benefits_step.rb
- app/services/flow/steps/provider_means_state_benefits/receives_state_benefits_step.rb
- app/views/shared/state_benefits/_new_benefit_form.erb
- spec/requests/providers/means/receives_state_benefits_controller_spec.rb
- spec/requests/providers/means/student_finances_controller_spec.rb
- spec/requests/providers/partners/receives_state_benefits_controller_spec.rb
- spec/requests/providers/partners/student_finances_controller_spec.rb
- spec/services/flow/steps/partner/receives_state_benefits_step_spec.rb
- spec/services/flow/steps/provider_means_state_benefits/receives_state_benefits_step_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-5418)
Previously there was no handler for the Save and come back later button
Now we save the form and redirect to the application list as expected
I have removed the save_as_draft button from the new_benefit_form as the database has been configured to not allow empty fields and this means we cannot save part completed data on this page
I will create a follow up ticket to investigate the impact of changing the database table.  It will have a note to reinstate the save as draft function on this ticket if the DB can be updated
- The standards in the …
> AP-5418: Update save as draft handling in the means pages

- app/services/flow/steps/provider_capital/restrictions_step.rb
- spec/services/flow/steps/provider_capital/restrictions_step_spec.rb
Change capital question flow from restrictions to mandatory capital disregards when flag enabled
[Link to story](https://dsdmoj.atlassian.net/browse/AP-5347)
Missed as part of AP-5347? This is a branching step flow that directs to policy disregards, and therefore needs to move foward to mandatory capital disregards when the mtra flag is enabled. …
> AP-5347: Change flow from restrictions to mandatory capital disregards when flag enabled

- app/assets/stylesheets/interruption-panel.scss
- app/controllers/providers/proceedings_sca/interrupts_controller.rb
- app/views/providers/proceedings_sca/interrupts/show.html.erb
- config/routes.rb
- spec/requests/providers/proceedings_sca/interrupts_controller_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-5389)
- Changed the colour for visited link on interrupt page to white.
- Delete the current proceeding and redirect to the proceeding search page if the user selects to Check for another matter type. Also add applications index page to page history as user will no longer be able to navigate back (as the proceeding has been deleted). …
> Ap 5389 update heard as alternatives page

- app/views/providers/review_and_print_applications/show.html.erb
- features/providers/partner_means_assessment/review_and_print.feature
- features/providers/review_and_print.feature
[Link to story](https://dsdmoj.atlassian.net/browse/AP-5443)
Change review and print heading from h1 to h2 …
> AP-5443: Change review and print heading from h1 to h2

- app/models/legal_aid_application.rb
- app/views/providers/limitations/_proceeding_type.html.erb
- app/views/providers/limitations/show.html.erb
- spec/models/legal_aid_application_spec.rb
There was a duplicate method in the delegated_functions concern that is being used in multiple other places.  Therefore the removal and replacement of these calls to the other method made the most sense
The replacement method is 
```ruby 
def non_sca_used_delegated_functions?
used_delegated_functions? && !special_children_act_proceedings?
end
``` …
> AP-5473: Replace display_emergency_certificate? calls

- app/helpers/capital_disregard_helper.rb
- app/views/providers/means_reports/_capital_disregards.html.erb
- app/views/providers/means_reports/_with_cfe_result_details.html.erb
- app/views/shared/check_answers/_assets.html.erb
- app/views/shared/check_answers/_capital_disregard_details.html.erb
- app/views/shared/check_answers/_capital_disregards.html.erb
- config/locales/en/providers.yml
- config/locales/en/shared.yml
- features/providers/mtr_accelerated/capital_disregards.feature
- features/providers/mtr_accelerated/check_capital_answers.feature
- features/providers/mtr_accelerated/disregard_list.feature
- features/providers/mtr_accelerated/main_dwelling.feature
- features/providers/mtr_accelerated/means_report.feature
- features/step_definitions/check_your_answers_steps.rb
- features/step_definitions/means_report_steps.rb
- spec/factories/legal_aid_applications.rb
- spec/helpers/capital_disregard_helper_spec.rb
Implement designs for capital disregards CYA, review & print/certificate and means report
[Link to story](https://dsdmoj.atlassian.net/browse/AP-5424)
Inline with designs …
> AP-5424: Add capital disregards CYA, review & print/certificate and means report

- app/models/application_digest.rb
- app/models/legal_aid_application.rb
- app/services/reports/mis/application_detail_csv_line.rb
- db/migrate/20241107092712_add_sca_fields_to_application_digest.rb
- db/schema.rb
- spec/factories/attachments.rb
- spec/models/application_digest_spec.rb
- spec/models/legal_aid_application_spec.rb
- spec/services/reports/mis/application_detail_csv_line_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-5338)
Added biological_parent?, parental_responsibility_order?, child_subject? and autogranted? columns to the application digest and additionally child_subject_client_involvement_type?  to the application details report.
Whether or not the application is an SCA application can already be determined from the matter_types column and similarly the applicant age from the applicant_age column.
TODO
After discussions, it was decided that it was best to wait to populate the auto_grant_special_children_act? on the LegalAidApplication model until after the autogrant work is complete. …
> ap-5338: add sca fields to application details report

- app/views/providers/confirm_client_declarations/show.html.erb
- features/providers/special_children_act/client_declaration.feature
- features/step_definitions/civil_journey_steps.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-5393)
Update the handling on the view to be reliant on the age of the applicant rather than proceeding types (SCA) …
> AP-5393: Update SCA client declaration page

- lib/tasks/digest.rake
- spec/lib/tasks/digest_spec.rb
It became problematic to test the digest on UAT branches when you have to comment out code that is tested...
This allows a dev to run the task with a `BYPASS=` ENVVAR to get a branch to run the export on demand without additional code changes
It also outputs a warning to guide us when it occurs …
> Chore: Update UAT digest Rake task exclusion

- app/models/provider.rb
- app/services/legal_framework/proceeding_types/all.rb
- app/views/providers/has_national_insurance_numbers/show.html.erb
- db/seeds/permissions.rb
- features/cassettes/Adding_an_SCA_Secure_Accommodation_Order_proceeding_sets_all_client_involvement_types_to_Child/When_a_provider_is_adding_proceedings_and_only_adds_a_Secure_Accommodation_Order.yml
- features/providers/special_children_act/secure_accomodation_order_cit.feature
- features/step_definitions/debug_steps.rb
- spec/factories/firms.rb
- spec/factories/permissions.rb
- spec/models/provider_spec.rb
- spec/services/legal_framework/proceeding_types/all_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-5442)
This implements a `special_children_act` role in the permissions table
It then ensures that, once the feature flag is enabled, only a provider with the role set is able to search for SCA proceedings  …
> AP-5442: Implement SCA firm permissions

- app/controllers/providers/means/student_finances_controller.rb
- app/controllers/providers/partners/student_finances_controller.rb
- app/forms/student_finances/base_student_finance_form.rb
- app/views/providers/means/vehicle_details/_form.html.erb
- app/views/shared/_student_finances.html.erb
- spec/forms/applicants/student_finance_form_spec.rb
- spec/forms/partners/student_finance_form_spec.rb
- spec/requests/providers/means/student_finances_controller_spec.rb
- spec/requests/providers/partners/student_finances_controller_spec.rb
Fix: nullify student_finance_amount when provider selects "Yes" with amount then amends to "No" 
[Came out of looking at](https://dsdmoj.atlassian.net/browse/AP-5496)
Currently saying yes, adding an amount then coming back and answering No 
will not nullify the student_finance_amount. This is because while it updates the
record it subsequently saves the form values from the form params, which still
contain the `student_finance_amount` value.
This refactors the form and partial to transparently use the `student_finance` boolean attribute, via the BaseForm pattern, value rather than use a specific instance variable, `@receives_student_finance`, to set the radio option - taken from `has_national_insurance_number_form` controller and forms pattern.
- …
> Fix: nullify student_finance_amount when no

- app/views/providers/means_reports/_with_cfe_result_details.html.erb
- app/views/shared/check_answers/_dependants.html.erb
- config/locales/en/generic.yml
- features/providers/means_report.feature
- features/providers/mtr_accelerated/means_report.feature
- features/providers/partner_means_assessment/means_report.feature
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4823)
Include dependants info on means report …
> AP-4823: Include dependants info on means report

- helm_deploy/apply-for-legal-aid/templates/_envs.tpl
[Link to story](https://dsdmoj.atlassian.net/browse/AP-5465)
Replace references to old secrets with the new secret. 
Secrets updated:
- googleDataStudioUrl
- legalFrameworkApiHost
- legalFrameworkApiJsHost
NB: This will be tested before merging (UAT), after merging (on Staging) and before and after deployment to production as it affects all environments and will affect the proceedings page.  …
> AP-5465 Replace old secrets references

- db/schema.rb
Revert changes to schema.rb
Inadvertently added using by this [commit](https://github.com/ministryofjustice/laa-apply-for-legal-aid/pull/7428/commits/08c4e0e929505d2a2ce41d7cb19f7194a4ba8e0c)
due to local restore of a production database and a migration run locally.
- The PR description should say what you changed and why, with a link …
> Revert changes to schema.rb

- app/models/legal_aid_application.rb
- spec/models/legal_aid_application_spec.rb
Initiate state machine after application creation
[Link to story](https://dsdmoj.atlassian.net/browse/AP-5143)
With the removal of this hook an inadvertent side effect has been
removed
```
after_create do
ActiveSupport::Notifications.instrument "dashboard.application_created", id:, state:
end
````
The calling of the `state` method in this code means it actually calls
`state_machine_proxy` method, which creates a `state_machine` relation
on the application if it does not have one. Its removal therefore opens
up issues both in tests and possibly functioning of the app.
By replacing it with an explicit call to `state_machine_proxy` we avoid
the issue.
- Github should not be reporting conflicts; …
> AP-5143: initiate state machine after create

- app/services/pda/current_contracts.rb
- app/services/pda/provider_details_retriever.rb
- spec/cassettes/PDA_ProviderDetailsRetriever/_call/with_a_non_existent_user/returns_an_error.yml
- spec/cassettes/PDA_ProviderDetailsRetriever/_call/with_an_existing_user/returns_provider_details.yml
- spec/services/pda/current_contracts_spec.rb
- spec/services/pda/provider_details_request_stubs.rb
- spec/services/pda/provider_details_retriever_spec.rb
The Provider Details API has deprecated a number of endpoints, replacing singular names with pluralised, 
e.g. provider_user -> provider_users
This PR updates the `provider_user` and `provider_office` uses in our service to use the new names
- You …
> Chore: Update PDA endpoints

- app/controllers/providers/proceedings_sca/interrupts_controller.rb
- app/services/flow/flows/provider_start.rb
- app/services/flow/steps/proceedings_sca/interrupts_step.rb
- app/views/providers/proceedings_sca/interrupts/show.html.erb
- config/locales/en/providers.yml
- spec/services/flow/steps/proceedings_sca/interrupts_step_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-5390)
- Amended the interrupt page for change of names to reflect the designs in the ticket.
- Fixed a bug where an error "path of step interrupts is undefined" was being raised if a user attempted to return to an application that was previously on the interrupts page from the legal_aid_applications index/Your applications In progress page. …
> ap-5390: update change_of_names interrupt

- db/migrate/20241115143002_remove_home_address_from_settings.rb
- db/schema.rb
- features/providers/check_provider_answers.feature
- features/providers/linked_applications/back_button.feature
The setting was removed over the summer but the column was left behind in the database …
> Chore: Remove Settings home_address column

- config/locales/en/providers.yml
- spec/requests/providers/proceedings_sca/interrupts_controller_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-5515)
The text for the button needed to be updated to ensure the user was aware they were taking a 'destructive' action. …
> AP-5515: Update the SCA Interrupt pages

- .github/dependabot.yml
The rubocop changes block so many other gems, we agreed to try splitting like this and see if it allows us to work on rubocop fixes without delaying other gems …
> Chore: split rubocop from dependabot

- .github/dependabot.yml
The first version did not work as the documentation suggested, so this is V2
The rubocop changes block so many other gems, we agreed to try splitting liek this and see if it allows us to work on rubocop fixes without delaying other gems
- You should …
> Chore: split rubocop from bulk dependabot

- Gemfile
- Gemfile.lock
- app/services/faraday/soap_call.rb
The URI gem jumped from 0.13.1 to 1.0.x a couple of times... It removed some regex patterns and renamed some.
This PR removes the lock below v1, updates the Gem and updates the URI pattern loader for the ABS_URI pattern …
> Chore: Update URI gem

- app/controllers/providers/means/cash_incomes_controller.rb
- app/controllers/providers/means/cash_outgoings_controller.rb
- app/views/shared/means/_cash_income.html.erb
- app/views/shared/means/_cash_outgoing.html.erb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-5368)
Ensure none_selected value is retained when there is an error
- You …
> AP-5368 cash income and outgoings bug

- .rubocop_todo.yml
- app/models/provider.rb
- app/services/provider_after_login_service.rb
- app/services/provider_details_retriever.rb
- helm_deploy/apply-for-legal-aid/values-uat.yaml
- spec/models/provider_spec.rb
- spec/requests/saml_sessions_controller_spec.rb
- spec/services/provider_after_login_service_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-5177)
This implements calls to the new, name-spaced PDA, versions of the provider classes, PDA::ProviderDetailsCreator
I had to add some `# :nocov:` tags to the old ProviderDetailsRetriever as it was only tested via other invocations. 
As the intention is to remove this class once we are happy with the new classes, this seemed like a small infraction.  
Feel free to argue in the comments! 😆  
I have tested locally by re-creating my database, re-seeding and deleting a test account, it's firm and the offices. Once pointed at a portal instance, it creates all three objects successfully.
This can be re-created on the branch for testing purposes
- Tests and rubocop should be passing: `bundle exec …
> AP-5177: Switch to new PDA after login

- app/controllers/providers/means/cash_incomes_controller.rb
- app/controllers/providers/means/cash_outgoings_controller.rb
- app/views/shared/means/_cash_income.html.erb
- app/views/shared/means/_cash_outgoing.html.erb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-5368)
Ensure none_selected value is retained when there is an error
- You …
> AP-5368 cash income and outgoings bug 

- app/models/application_digest.rb
- app/models/concerns/non_means_tested_state_machine.rb
- app/models/concerns/special_children_act_state_machine.rb
- app/models/legal_aid_application.rb
- app/services/ccms/attribute_configuration.rb
- app/services/ccms/attribute_value_generator.rb
- app/services/ccms/requestors/case_add_requestor.rb
- app/services/ccms/requestors/special_children_act_case_add_requestor.rb
- app/services/flow/steps/provider_start/check_provider_answers_step.rb
- app/services/reports/mis/application_detail_csv_line.rb
- config/ccms/attribute_block_configs/special_children_act.yml
- spec/concerns/non_means_tested_state_machine_spec.rb
- spec/concerns/special_children_act_state_machine_spec.rb
- spec/factories/legal_aid_applications.rb
- spec/factories/non_means_tested_state_machines.rb
- spec/factories/proceedings.rb
- spec/requests/providers/proceeding_merits_task/check_who_client_is_controller_spec.rb
- spec/requests/providers/proceeding_merits_task/does_client_have_parental_responsibilities_controller_spec.rb
- spec/requests/providers/proceeding_merits_task/is_client_biological_parent_controller_spec.rb
- spec/requests/providers/proceeding_merits_task/is_client_child_subject_controller_spec.rb
- spec/services/ccms/requestors/case_add_requestor_spec.rb
- spec/services/ccms/requestors/special_children_act_case_add_requestor_spec.rb
- spec/services/flow/steps/provider_start/check_provider_answers_step_spec.rb
- spec/support/xml_extractor.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-5288)
This PR allows for submission of SCA cases to CCMS
It includes a new, SCA, state machine, case_add_requestor and attribute_block list. 
This allows us to test the SCA submissions in isolation without having to write a lot of `if SCA...else` tests in the generators
It also refactors some of the SCA reporting methods, as very similar ones are needed here.  Where possible the legal_aid_application model is the source of truth with alias_method used to provide the same code with a different inflection for the two calling methods
- The standards …
> AP-5288: SCA CCMS payload updates

- spec/requests/errors_controller_spec.rb
- spec/support/welsh_language.rb
A recent change to the error controller removed the around block for the welsh language checks.  This was needed as, otherwise, it leaves the locale set to CY for subsequent tests.  This caused flickers in CI.
This PR creates a new rspec flag, :use_welsh_locale, to reduce the noise in individual rspec files, while still allowing the locale to be set for an individual group of tests …
> Chore: Fix Welsh locale flicker

- app/views/providers/check_capital_answers/show.html.erb
- app/views/providers/check_merits_answers/show.html.erb
- app/views/providers/check_provider_answers/_shared.html.erb
- app/views/providers/means/check_income_answers/show.html.erb
- config/locales/en/generic.yml
- config/locales/en/providers.yml
- features/providers/check_provider_answers.feature
[Link to story](https://dsdmoj.atlassian.net/browse/AP-5490)
Add inset text to inform users that they cannot go back once they have gone past a CYA page …
> AP-5490 add inset text to CYA pages

- app/views/shared/forms/_applicant_form.html.erb
- config/locales/en/shared.yml
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4435)
Add an aria-label to the `Name` group on the client details page to make it clear to screen-reader users that the fields `First name` and `Last name` refer to the client name
- You should …
> AP-4435 fix form grouping accessibility error

- app/views/providers/proceeding_loop/substantive_defaults/show.html.erb
Remove debug block
left in accidentally
> fix: remove debug block

- app/helpers/application_helper.rb
- config/locales/cy/layouts.yml
- config/locales/en/layouts.yml
- helm_deploy/apply-for-legal-aid/templates/_envs.tpl
[Link to story](https://dsdmoj.atlassian.net/browse/AP-5529)
This was raised by the central UR team.  They have requested that the url be hidden from github crawlers, so the form link is stored in AWS Secret Manager for each environment.
It is then loaded in _ENVS.tpl and passed to the footer meta items.
This routes to root_path if the value is missing, this should only affect devs without a RESEARCH_PANEL_FORM_LINK in their .env files, as each environment has the value set
- The standards in the [Git Workflow document on Confluence](https://dsdmoj.atlassian.net/wiki/spaces/ATPPB/pages/4602855954/Git+W …
> AP-5529: Add  Join our research panel link to the footer

- app/controllers/admin_users/omniauth_callbacks_controller.rb
- app/controllers/applicants/omniauth_callbacks_controller.rb
- app/controllers/auth_controller.rb
- app/controllers/concerns/providers/authorizable.rb
- app/controllers/errors_controller.rb
- spec/requests/errors_controller_spec.rb
Change status code for the access_denied page redirect to 403
[Link to story](https://dsdmoj.atlassian.net/browse/AP-5524)
So the response status matches the intended behaviour of being
forbidden/403 for the current user.
A subsequent commit removes sentry capturing of details of failures
because the originating PR suggests doing so and there does not appear
to have been any action taken on these, if they are still occuring (which I cannot
see). …
> AP-5524: Change access denied status to 403

- app/controllers/concerns/providers/application_dependable.rb
- spec/policies/provider_access_spec.rb
- spec/requests/errors_controller_spec.rb
- spec/requests/providers/about_the_financial_assessments_controller_spec.rb
- spec/requests/providers/check_merits_answers_spec.rb
Let rails handle application not found
[Link to story](https://dsdmoj.atlassian.net/browse/AP-5524)
A question on how we want to handle legal_aid_application records that are Not Found.
Currently we swallow the fact that a legal_aid_application from the id in params is not found,
returning nil for it instead. It then handles it being nil by redirecting to the page_not_found page.
The rails way would be to let it raise RecordNotFound, which on this branch, will then be handled as
a 404 transparently by the ErrorController (via the exceptions_app  config).
The Advantage of letting rails handle it is that there is no redirect so the URL remains the same,
which is more typical behaviour for not found, and logs will reflect the true cause of the 404. A
Disadvantage is I do not know what …
> AP-5524: Let rails handle application not found

- .github/dependabot.yml
the rails-i18n gem forces railties to 8+ and thus all of rails, this breaks the deploys and updates …
> Chore: Remove rails-i18n from dependabot checks

- app/views/layouts/application.html.erb
Add primary nav to search page. Should have been added as part of AP-5268 but was accidentally missed …
> Chore: Add primary nav to search page

- db/migrate/20241202152952_change_capital_disregards_index.rb
- db/schema.rb
- spec/forms/providers/means/capital_disregards/discretionary_form_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-5564)
This error was occuring because it was possible to add both a mandatory and a discretionary capital disregard with  name backdated benefits but there was a unique index on the capital_disregards table for legal_aid_application and name.
This pr adds mandatory to the the index so that it is possible to add both a discretionary and a mandatory capital disregard with name backdated_benefits.
- The standards in the [Git Workflow document on Confluence](https://dsdmoj.atlassian.net/wiki/spaces/ATPPB/pages/4602855954/Git+Workflow) should be …
> Ap 5564 capital discretionary disregards bug

- app/forms/providers/base_regular_income_form.rb
- app/models/transaction_type.rb
- app/services/populators/transaction_type_populator.rb
- app/views/providers/capital_income_assessment_results/_other_income.html.erb
- config/locales/cy/activemodel.yml
- config/locales/cy/transaction_types.yml
- config/locales/en/activemodel.yml
- config/locales/en/providers.yml
- config/locales/en/transaction_types.yml
- db/migrate/20241206121926_destroy_student_loan_transaction_type.rb
- db/schema.rb
- features/step_definitions/civil_journey_steps.rb
- features/step_definitions/review_and_print_steps.rb
- spec/factories/bank_transactions.rb
- spec/factories/legal_aid_applications.rb
- spec/models/transaction_type_spec.rb
- spec/services/cfe_civil/components/other_income_spec.rb
- spec/services/populators/transaction_type_populator_spec.rb
Remove old transaction type -`student_loan`
[Link to story](https://dsdmoj.atlassian.net/browse/AP-5387)
Was replaced by `[applicant|partner].student_finance` attribute and functionality
2+ years ago and no data currently exists on staging or production for this transaction type.
have run through applications using HMHO/bank-statement-upload and truelayer journey before and after code changes and data migration added without incident.
- There …
> AP-5387: Remove student loan

- app/views/providers/merits_reports/show.html.erb
An error was being generated on production while trying to generate the merits report.
This PR updates the partial to use the same pattern as other invocations
When tested locally on an anonymised database, the merits report render switched from 
to …
> Fix: substantive cost limit heading

- spec/services/ccms/requestors/case_add_requestor_spec.rb
This is caused by the set-up creating many opponents and a race condition meaning they sometimes get created in a different sequence.
By converting the two hashes into json we can run a, sequence idempotent, match_json_expression comparison
This ensures the payloads match, regardless of sequence
To track this down I re-created a failing CircleCI run
Adding the tests from the split job and re-using the same seed value.  Then, with a binding.pry, ensured the test woudl fail and then tried different match methods until I could consistently get it to pass …
> Fix: Flickering CCMS case requestor test

- app/services/ccms/attribute_value_generator.rb
- config/ccms/attribute_block_configs/non_passported.yml
- spec/factories/legal_aid_applications.rb
- spec/services/ccms/requestors/case_add_requestor_xml_blocks/non_passported_variable_attributes_spec.rb
Correct data query for student finance CCMS question
> [!WARNING]  
> Test on UAT for impact and ask BA for input.
> _Tested and discussed - BA gives the go ahead to merge - see ticket for details_
[Link to story](https://dsdmoj.atlassian.net/browse/AP-5602)
The student_loan transaction_type was archived 2+ years ago, having been replaced
by student_finance and student_finance_amount questions on applicant and partner.
However, our CCMS payload includes an attribute that is described as
'Client Student Income: Receives a student loan/grant or bursary?'
whose answer is generated from a lookup of data for the `student_loan`
`transaction_type`.It was, as a result, always false.
This should therefore be changed to use the correct data
Civil Apply stores, namely applicant.student_finance? . …
> AP-5602: Correct data query for CCMS student finance question

- app/models/legal_aid_application.rb
- features/step_definitions/review_and_print_steps.rb
- spec/factories/legal_aid_applications.rb
Ignore unused column.
[Link to related story](https://dsdmoj.atlassian.net/browse/AP-5387)
Column was migrated to applicant and partner models 16 months ago. This is the first step
in dropping it. Subsequent PR to drop once we deploy this.
[Removing a column in strong-migrations gem](https://github.com/ankane/strong_migrations?tab=readme-ov-file#removing-a-column)
- There should be no unnecessary whitespace changes. These make diffs harder to …
> AP-5387-extension: ignore unused `student_finance` column

- db/migrate/20241210160206_remove_student_finance_from_legal_aid_application.rb
- db/schema.rb
- features/step_definitions/review_and_print_steps.rb
Drop unused column.
[Link to related story](https://dsdmoj.atlassian.net/browse/AP-5387)
Column was migrated to applicant and partner models 16 months ago. This is the second step
that drops it. Subsequent PR to remove ignore line once we deploy this.
[Removing a column in strong-migrations gem](https://github.com/ankane/strong_migrations?tab=readme-ov-file#removing-a-column) …
> Chore: drop the unused `legal_aid_application.student_finance` attribute

- app/controllers/providers/proceeding_interrupts/related_orders_controller.rb
- app/forms/providers/proceeding_interrupts/related_orders_form.rb
- app/services/flow/flows/provider_proceeding_interrupts.rb
- app/services/flow/provider_flow_service.rb
- app/services/flow/steps/provider/proceeding_interrupts/related_orders_step.rb
- app/services/flow/steps/provider_start/proceedings_types_step.rb
- app/views/providers/proceeding_interrupts/related_orders/show.html.erb
- config/initializers/inflections.rb
- config/locales/en/activemodel.yml
- config/locales/en/providers.yml
- config/routes.rb
- db/migrate/20241209111158_add_related_orders_to_proceedings.rb
- db/schema.rb
- spec/factories/proceedings.rb
- spec/forms/providers/proceeding_interrupts/related_orders_form_spec.rb
- spec/requests/providers/proceeding_interrupts/related_orders_controller_spec.rb
- spec/services/flow/steps/provider/proceeding_interrupts/related_orders_step_spec.rb
- spec/services/flow/steps/provider_start/proceedings_types_step_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4409)
Add new interrupt pages for PLF proceedings
This includes a new variety of proceeding interrupt pages.  I deliberately did not put them into the proceedings_sca namespace
Should we re-factor the other proceeding interrupts into a more generic namespace to keep them contained, but not tied explicitly to a certain proceeding type? …
> AP-4409: Add the related_orders page to the PLF proceeding loop

- app/models/legal_aid_application.rb
Remove ignored_column reference for student_finance
Column was dropped im previous PR that has now been deployed. …
> Chore: remove ignored_column following it having been dropped

- .rubocop_todo.yml
- app/models/provider.rb
- app/services/provider_after_login_service.rb
- app/services/provider_details_retriever.rb
- spec/models/provider_spec.rb
- spec/requests/saml_sessions_spec.rb
- spec/services/provider_after_login_service_spec.rb
Reverting due to unmatched firms, this is caused by a provider residing within multiple firms.
Further analysis required, to understand impact to providers and the Apply service.
> Revert "AP-5177: Switch to new PDA after login"

- app/controllers/providers/proceeding_merits_task/specific_issue_controller.rb
- app/forms/providers/proceeding_merits_task/specific_issue_form.rb
- app/views/providers/merits_task_lists/show.html.erb
- app/views/providers/proceeding_merits_task/specific_issue/show.html.erb
- config/locales/en/activemodel.yml
- config/locales/en/providers.yml
- db/migrate/20241210171604_remove_confirmed_from_specific_issues.rb
- db/schema.rb
- spec/forms/providers/proceeding_merits_task/specific_issue_form_spec.rb
- spec/requests/providers/proceeding_merits_task/specific_issue_controller_spec.rb
[Amend to existing “What specific issue do you want to determine at court” question](https://dsdmoj.atlassian.net/browse/AP-5378)
Remove the text “I confirm this specific issue proceeding is not for a change of name application” and the checkbox for all proceedings. This is because we have added a question to the proceeding loop instead to confirm that the application is not for a change of name. …
> ap-5378-amend-specific-issue-at-court-question

- spec/services/delegated_functions_date_service_spec.rb
- spec/services/substantive_application_deadline_calculator_spec.rb
I pulled down a release candidate of ruby 3.4 to see how "bad" the transition could be, and the only, obvious, issue was these two files requiring RSpec.
As they are a superfluous require and Rails was not able to open a console and rspec would not run with these present in 3.4, they can be removed now
- The PR description should say …
> Chore: Pre Ruby 3.4 updates

- config/initializers/grover.rb
Switches the display_url in the grover initializer to use the Rails.configuration.x.application.host_url, the previous version tried to replicate this setting but needed extra values to be present in .ENV files.
This change should allow developers with a `PORT` value in their `.env` file to view to render PDF files locally while not affecting the generation on deployed environments; UAT, Staging and Production …
> Chore: Improve Grover set up for developers

- app/views/providers/means/capital_disregards/discretionary/show.html.erb
- app/views/providers/means/capital_disregards/mandatory/show.html.erb
- config/locales/en/providers.yml
- features/providers/partner_means_assessment/end_to_end_capital_assessment.feature
Update checkbox on the mandatory and discretionary disregard pages to reflect whether or not the client has a partner, as in the designs. …
> Chore: Update disregards content for client and partner

- app/assets/stylesheets/check-your-answers.scss
- app/helpers/proceeding_helper.rb
- app/views/shared/check_answers/_proceeding_details.html.erb
- features/cassettes/Checking_client_details_answers_backwards_and_forwards/Multiple_scope_limitations_are_displayed_as_expected.yml
- features/providers/check_provider_answers.feature
- features/step_definitions/check_provider_answers_steps.rb
- spec/factories/scope_limitations.rb
- spec/helpers/proceeding_helper_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-5592)
This PR changes the proceeding_details partial IDs quite heavily to make testing easier. 
Update the proceeding_helper to display the new logic required
* don't repeat the date on two lines
* do show the additional notes on a new line
* show the scope limitation meaning in bold if there is more than one for a proceeding  …
> AP-5592: Update scope limits on check provider answers

- app/javascript/src/modules/proceedings.js
[Link to story](https://dsdmoj.atlassian.net/browse/AP-5641)
Fix bug so "Clear search" link actually clears the search, and an error message is shown if the user tries to progress after clicking it …
> AP-5641: Fix issue on proceeding search page

- app/views/admin/roles/permissions/show.html.erb
- app/views/shared/check_answers/_merits_proceeding_section.html.erb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-5648)
Update conditional to add additional client involvement type. This means that if a special children act proceeding has a client involvement type of applicant, the correct info will now be shown on the check your answers page …
> AP-5648: Fix bug on merits CYA page

- scripts/restore_anonymised_db.sh
Allow us to pass in a named file to restore, this allows us to backup a UAT instance and restore it, it improves the instructions to make the new uses clearer. …
> Chore: Update DB restore script

- Gemfile.lock
Bump bundler 2.5.11 to 2.6.2
see [changlog](https://github.com/rubygems/rubygems/blob/master/bundler/CHANGELOG.md) …
> Chore: Bump bundler 2.5.11 to 2.6.2

- app/helpers/gov_uk_form_helper.rb
- app/views/admin/user_dashboard/index.html.erb
- app/views/providers/applicant_bank_accounts/show.html.erb
- app/views/shared/forms/_fieldset_header.html.erb
Remaining references to helper method `govuk_fieldset_header` being used for headings
Replace these with actual Heading Ones
Remove helper `govuk_fieldset_header` …
> Chore: remove helper govuk_fieldset_header

- app/controllers/status_controller.rb
- spec/requests/status_controller_spec.rb
Amend /healthcheck endpoint to use database_exists?
[Identified while working on](https://dsdmoj.atlassian.net/browse/AP-5668)
Inline with hmrc-interface app, at least, and best
practice since rails 7.2 as `active?` may be false
due to lazy loaded connections. …
> Chore: Amend /healthcheck endpoint to use database_exists?

- spec/requests/providers/application_merits_task/original_judge_levels_controller_spec.rb
- spec/requests/providers/application_merits_task/second_appeals_controller_spec.rb
These were added while the individual pages were implemented and can now be removed
Remove the TODO and add the correct path to the expectations …
> Chore: Remove PLF routing TODOs

- spec/requests/providers/change_of_names_interrupts_controller_spec.rb
I think the `display` parameter was copy pasted from another controller test.  As it was empty in this test, it caused debug output to be added to the test run, e.g.
........#<RSpec::ExampleGroups::ProvidersChangeOfNamesInterruptsController::GETProvidersApplicationsIdChangeOfNamesInterrupts::WhenTheProviderIsNotAuthenticated::BehavesLikeAProviderNotAuthenticated:0x000000013e0a8450>.#<RSpec::ExampleGroups::ProvidersChangeOfNamesInterruptsController::GETProvidersApplicationsIdChangeOfNamesInterrupts::WhenTheProviderIsAuthenticated:0x000000013db62ae0>..... …
> Chore: Remove extraneous parameter

- app/views/citizens/means_test_results/show.html.erb
Panel markup on citizen journey was previously unnecessarily complex. Simplify this to keep in line with rest of the codebase and use default spacing. …
> Chore: simplify panel markup on citizen journey

- config/initializers/content_security_policy.rb
- docker/apply_base.dockerfile
[Link to story](https://dsdmoj.atlassian.net/browse/AP-5415)
Add url to content security policy so images will display
- You should …
> AP-5415: Add url to content security policy so images will display

- app/controllers/providers/change_of_names_controller.rb
- app/controllers/providers/proceedings_sca/child_subjects_controller.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-5467)
Switch from proceedings.last to proceedings.order(:created_at).last
Because we use GUIDs as the id, there is no value in a plain .last call as it orders by GUID text.  Adding the order allows us to get the most recently created proceeding, which is what is expected, without having to make the URLs and routing more complex by adding specific proceeding IDs into the routes.
This also matches the existing use in the ProceedingIssueStatusesController …
> AP-5647: Update proceeding captions

- app/helpers/flow_helper.rb
- app/views/citizens/accounts/index.html.erb
- app/views/providers/submitted_applications/show.html.erb
- app/views/shared/_worker_complete.html.erb
Remove next_action_link as the functionality can just as easily be provided with the govuk_button_link_to method from the govuk_components gem …
> Chore: Remove next_action_link helper method

- app/views/shared/check_answers/_children_involved.html.erb
- app/views/shared/check_answers/_client_details.html.erb
- app/views/shared/check_answers/_gateway_evidence.html.erb
- app/views/shared/check_answers/_laspo.html.erb
- app/views/shared/check_answers/_latest_incident_details.html.erb
- app/views/shared/check_answers/_linking_and_copying.html.erb
- app/views/shared/check_answers/_matter_opposition.html.erb
- app/views/shared/check_answers/_merits_proceeding_section.html.erb
- app/views/shared/check_answers/_opponent_details.html.erb
- app/views/shared/check_answers/_partner_details.html.erb
- app/views/shared/check_answers/_proceeding_details.html.erb
- app/views/shared/check_answers/_proceedings.html.erb
- app/views/shared/check_answers/_supporting_evidence.html.erb
- app/views/shared/check_answers/_undertaking.html.erb
- app/views/shared/check_answers/_urgency.html.erb
- features/providers/check_merits_answers.feature
- features/providers/check_provider_answers.feature
- features/providers/linked_applications/check_your_answers_link_and_copy.feature
- features/providers/linked_applications/check_your_answers_link_only.feature
- features/providers/linked_applications/check_your_answers_not_linked.feature
- features/providers/non_passported_journey/waiting_for_applicant.feature
- features/providers/partner_means_assessment/review_and_print.feature
- features/providers/review_and_print.feature
[Link to story](https://dsdmoj.atlassian.net/browse/AP-5676)
Update heading levels for summary cards on `check_provider_answers` and `check_merits_answers` so they are semantic. This ticket will allow the heading level to be updated on the other check your answers page tickets …
> AP-5676: CYA update heading levels

- app/controllers/providers/bank_transactions_controller.rb
- app/views/layouts/_flash.html.erb
- app/views/layouts/application.html.erb
- app/views/providers/bank_transactions/remove_transaction_type.js.erb
- config/locales/en/providers.yml
- features/providers/non_passported_journey/with_bank_transactions.feature
- features/step_definitions/generic_steps.rb
- features/support/steps_helper.rb
- spec/requests/providers/bank_transactions_controller_spec.rb
Add a "removed bank transaction" flash message
[Link to story](https://dsdmoj.atlassian.net/browse/AP-4439)
For accessibility we need to announce the removal of the
record to the page/screen reader. For progressive web app
reasons we need to ensure removal is also available and
announced to screen readers when javascript is disabled.
This provides mechanism that should be both accessible and
progressive. 
The remove action is **Accessible** because it adds a 
govuk notification banner (which is accessible) whenever a bank 
transaction is removed. In addition [all] flash messages have had an `aria-live: assertive`
and `aria-atomic: true` attribute added to their outer `div` inline with suggestions from
[a11yonrails](https://www.a11yonrails.com/pages/flash.html)
The remove action is also …
> AP-4439: Add a "removed bank transaction" flash message

- app/controllers/admin/ccms_queues_controller.rb
- app/models/concerns/base_state_machine.rb
- app/views/admin/ccms_queues/index.html.erb
- app/workers/reports_creator_worker.rb
- config/initializers/sidekiq.rb
- config/locales/en/admin.yml
- spec/requests/admin/ccms_queues_controller_spec.rb
When CCMS submissions were restarted on the morning of 20 Dec the submissions restarted but the reports did not generate as expected.
This PR identified an issue where CCMS submissions have been paused during an evening downtime. Previously we had only seen 2 or 3 submissions maximum.  
On this occasion there were 10 applications to restart.  This turned out to be too many! 
I recreated the situation, 10 paused applications, and turned the submissions back on.  The first 5 (each sidekiq worker has 5 threads) requested a CCMS case reference and then tried to generate reports at the same time... the worker container ran out of memory and crashed.  When a new pod was spawned, the next 5 started.  This left all 10 applications trying to build reports and failing.
Working as a team we …
> LnD: investigation into restart submission report generation

- Gemfile.lock
Bump bundler 2.6.2 --> 2.6.3
Fixes some RDoc warnings aside from anything else. …
> Chore: Bump bundler 2.6.2 --> 2.6.3

- app/models/legal_aid_application.rb
- app/views/providers/confirm_non_means_tested_applications/show.html.erb
- config/locales/en/providers.yml
- spec/factories/proceedings.rb
- spec/models/legal_aid_application_spec.rb
- spec/services/flow/steps/provider_start/check_provider_answers_step_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-5685)
Add routing for non-means-tested PLF proceedings
I know we discussed extracting this logic to a service class, but the small additions to the LegalAidApplication made a lot of sense... refactoring would have involved a lot more work at this stage and it didn't seem valuable when the change was so small... happy to discuss …
> AP-5685: PLF non means tested routing

- app/controllers/providers/application_merits_task/is_matter_opposed_controller.rb
- app/forms/providers/application_merits_task/matter_opposed_form.rb
- app/services/flow/flows/provider_merits.rb
- app/services/flow/merits_loop.rb
- app/services/flow/steps/provider_merits/is_matter_opposed_step.rb
- app/views/providers/application_merits_task/is_matter_opposed/show.html.erb
- app/views/providers/check_merits_answers/show.html.erb
- app/views/providers/merits_reports/show.html.erb
- app/views/shared/check_answers/_merits.html.erb
- app/views/shared/check_answers/merits/_is_matter_opposed.html.erb
- app/views/shared/review_application/_questions_and_answers.html.erb
- config/locales/en/activemodel.yml
- config/locales/en/providers.yml
- config/locales/en/shared.yml
- config/routes.rb
- db/migrate/20250124104720_add_matter_opposed_to_matter_oppositions.rb
- db/schema.rb
- spec/factories/legal_framework_merits_task_list.rb
- spec/factories/legal_framework_serialized_merits_task_list.rb
- spec/forms/providers/application_merits_task/matter_opposed_form_spec.rb
- spec/requests/providers/application_merits_task/is_matter_opposed_controller_spec.rb
- spec/requests/providers/check_merits_answers_controller_spec.rb
- spec/services/flow/steps/provider_merits/is_matter_opposed_step_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-5380)
Add the new, PLF, Is matter opposed? question
This chooses to extend the `MatterOpposition` object to store the optional values.  It now stores a text value for `request` and a boolean value for `matter_opposed`.  This required changes to the CYA (and associated)pages to check for the object _and_ value presence before rendering as the questions are exclusive to PLF and optional for other matter types.  
Happy to discuss if a different structure is preferred! 🙂  …
> AP-5380: Add  PLF merits question, Is matter opposed? 

- app/views/providers/proceeding_loop/delegated_functions/show.html.erb
- config/locales/en/providers.yml
- spec/requests/providers/proceeding_loop/delegated_functions_controller_spec.rb
Add hint text to delegated functions question
[Link to story](https://dsdmoj.atlassian.net/browse/AP-5525)
Inline with designs and business logic (see ticket) the hint should be shown only on SCA proceeding delegated function pages.
- You should …
> AP-5525: Add delegated function hint

- app/assets/stylesheets/print-styles.scss
[Link to story](https://dsdmoj.atlassian.net/browse/AP-5621)
The fixed width caused the lines and data to overflow when generating Means and Merits reports.  This is a minimal fix
There was conversation about reviewing the entire print CSS handling, but this ticket is just to address the overruns …
> AP-5621: Remove fixed width of means report print style

- app/controllers/providers/address_selections_base_controller.rb
- app/controllers/providers/correspondence_address/choices_controller.rb
- spec/requests/providers/correspondence_address/choices_controller_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-5725)
The method of changing the state from initiated to entering_applicant_details was only being called on certain address and the limitation controllers.  When a provider chose a business address and linked a case, it bypassed all of the state change mechanisms.
This PR moves the address state change to the first address page which should not be bypassed in any of our current flows
- There …
> AP-5725: Update state change for linked cases

- lib/tasks/fixes/ap_5699.rake
- lib/tasks/provider_transfer/ptr_migrations.rake
- spec/lib/tasks/provider_transfer/ptr_migrations_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-5699)
The new PDA added Provider to incorrect firms and therefore office.
A few new firms where then created because of the above.
This is to transfer application to the correct office; providers to the correct firms; and to remove Firms where no providers have been onboarded.
- The …
> AP-5699 Fix incorrect PDA data

- app/assets/stylesheets/print-styles.scss
- app/views/providers/merits_reports/_applied_previously.html.erb
- app/views/providers/merits_reports/_delegated_functions.html.erb
- app/views/providers/merits_reports/_proceeding_details.html.erb
- app/views/providers/merits_reports/show.html.erb
- app/views/shared/check_answers/_merits.html.erb
- config/locales/en/providers.yml
Avoid page breaks between headings and their summary card on the merits report
[Link to story](https://dsdmoj.atlassian.net/browse/AP-5742)
For sections with a single card the heading can otherwise
become separated from the summary card's page. Which is
not ideal for a printed document being reviewed by caseworkers.
**Also**, this replaces a deprecated css attribute `page-break-inside` for `break-inside` - 
see [deprecation notice](https://developer.mozilla.org/en-US/docs/Web/CSS/page-break-inside) …
> AP-5742: Add avoid breaks css to merits report

- spec/models/legal_aid_application_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-5754)
Previously this test was flickering. Add sort to ensure the order is consistent, so that it is hopefully more stable. …
> AP-5754: Add sort to ensure evidence order is consistent

- spec/services/secure_application_finder_spec.rb
This was created 2 years ago and hard coded... Happy Valentines Day all your test runs will fail! :D
This moves the creation date to always be perpetually two years away …
> Fix: spec date timebomb

- docs/pull_request_template.md
add link to standards to pull request template
> Chore: add link to standards to pull request template

- app/views/providers/check_capital_answers/show.html.erb
- app/views/providers/check_passported_answers/show.html.erb
- app/views/providers/means/check_income_answers/show.html.erb
- features/providers/check_capital_answers.feature
[Link to story](https://dsdmoj.atlassian.net/browse/AP-5796)
These pages had H3 What happens next links, but they (confirmed with Design) should have been H2's
One had a mismatched opening  and close tag  this reverts it back to an h2, and updates some others.  Ensuring the tests still pass …
> AP-5796: Fix mismatched HTML tag

- app/models/application_digest.rb
- app/models/legal_aid_application.rb
- app/services/ccms/attribute_value_generator.rb
- app/services/ccms/requestors/case_add_requestor.rb
- app/services/reports/mis/application_detail_csv_line.rb
- config/ccms/attribute_block_configs/base.yml
- config/ccms/attribute_block_configs/non_passported.yml
- db/migrate/20250217105318_add_ecct_routed_to_application_digest.rb
- db/schema.rb
- spec/factories/proceedings.rb
- spec/models/legal_aid_application_spec.rb
- spec/services/ccms/requestors/case_add_requestor_spec.rb
- spec/services/ccms/requestors/case_add_requestor_xml_blocks/non_passported_additional_property_attributes_spec.rb
- spec/services/ccms/requestors/case_add_requestor_xml_blocks/non_passported_attributes_spec.rb
- spec/services/ccms/requestors/case_add_requestor_xml_blocks/non_passported_variable_attributes_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-5639)
This PR updates the CCMS payload to set routing details for passported and non-passported PLF applications that have the second_appeal present and set to true …
> AP-5639: Add routing to ECCT for PLF Second Appeal cases

- app/views/shared/check_answers/merits/_second_appeal.html.erb
Prevent change link for second appeal question appearing on read-only pages
[Came out of this ticket](https://dsdmoj.atlassian.net/browse/AP-5709)
BUG identified during PLF playback.  …
> Fix: Stop displaying change link for second appeals in read_only mode

- app/views/shared/check_answers/_child_care_assessment.html.erb
Correct summary card column widths for child care assessment merits CYA 
[Came out of ticket](https://dsdmoj.atlassian.net/browse/AP-5709)
Make one-third/two-third not half/half to make it consistent with other merits CYA page summary
cards. This was noticed during PLF playback session. …
> Fix: correct width of child_care_assessment CYA section

- config/locales/en/activemodel.yml
- config/locales/en/providers.yml
- config/locales/en/shared.yml
Amend content for court_application_or_order evidence
[Link to story](https://dsdmoj.atlassian.net/browse/AP-5812)
This document category and its error message specifically relates
to providing an opponents' (on or more) court application or court
order. Further, this question and it's evidence do NOT relate purely
to section 8 matters but also to Domestic abuse and Public Law Family 
matter type proceedings.
Design has confirmed we should therefore 
- Remove the term "for Section 8 proceedings"
- add the word "opponent" to its error and evidence category description.
- The [development …
> AP-5812: Amend content for court_application_or_order evidence

- app/controllers/providers/uploaded_evidence_collections_controller.rb
- app/services/uploaded_evidence/base.rb
- app/services/uploaded_evidence/deletion_service.rb
- app/services/uploaded_evidence/uploader_service.rb
- app/views/providers/uploaded_evidence_collections/_uploaded_files.html.erb
- spec/services/uploaded_evidence/base_spec.rb
- spec/services/uploaded_evidence/deletion_service_spec.rb
- spec/services/uploaded_evidence/list_service_spec.rb
- spec/services/uploaded_evidence/populate_upload_form_service_spec.rb
- spec/services/uploaded_evidence/shared_examples_for_uploaded_evidence.rb
BUG: when delete is hit the document category's select list names change to a humanized version of their value.
[Link to story](https://dsdmoj.atlassian.net/browse/AP-5792)
To replicate just add evidence, categorise, then delete one of the documents …
> AP-5792: Fix evidence category naming after delete

- app/assets/stylesheets/print-styles.scss
- app/views/providers/means_reports/_benefits_breakdown.html.erb
- app/views/providers/means_reports/_capital_result.html.erb
- app/views/providers/means_reports/_caseworker_review.html.erb
- app/views/providers/means_reports/_income_details.html.erb
- app/views/providers/means_reports/_income_result.html.erb
- app/views/providers/means_reports/_outgoings_and_deductions_details.html.erb
- app/views/providers/means_reports/_proceeding_eligibility.html.erb
- app/views/providers/means_reports/_receives_benefits.html.erb
- app/views/providers/means_reports/_uploaded_bank_statements.html.erb
- app/views/providers/means_reports/_with_cfe_result_details.html.erb
- app/views/providers/means_reports/show.html.erb
- app/views/shared/_savings_and_investments.html.erb
- app/views/shared/check_answers/_assets.html.erb
- app/views/shared/check_answers/_one_link_section.html.erb
- app/views/shared/check_answers/_property.html.erb
- app/views/shared/check_answers/_vehicles.html.erb
[Means reports - Headings appearing on separate pages to content.](https://dsdmoj.atlassian.net/browse/AP-5753)
Connect headings with sections on Means report so that sections are printed on the same page. …
> AP-5753: Add print-no-break sections on means reports print page

- app/assets/stylesheets/print-styles.scss
- app/views/providers/means_reports/_with_cfe_result_details.html.erb
- app/views/providers/means_reports/show.html.erb
- config/initializers/grover.rb
- config/locales/en/providers.yml
[Link to story](https://dsdmoj.atlassian.net/browse/AP-5837)
- Move caseworker review to top of means report
- Update grover to print background colours …
> AP-5837: make review reasons more clear on means report

- app/views/shared/review_application/_questions_and_answers.html.erb
- features/providers/review_and_print.feature
[Link to story](https://dsdmoj.atlassian.net/browse/AP-5842)
The capital section should be excluded from the review and print pages when the application is non-means tested
But one of the recent CYA updates accidentally removed it from a non-means test check and included it on all applications …
> AP-5842: Update capital logic on review pages

- app/models/applicant.rb
- spec/factories/legal_aid_applications.rb
- spec/models/applicant_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-5708)
The age handling for applicants had handlers for under 18 and SCA but could not handle PLF non-means tested applications.
Applicant and legal_aid_application both had methods of tracking non-means tested status and it had some duplicated methods, this uses the legal_aid_application method for applicant to remove some of the duplication and ensure consistent rules application if we add more non-means tested extensions in the future
- The [development standards](https://dsdmoj.atlassian.net/wiki/spaces/ATPPB/pages/5503385837/Development+standa …
> Fix: Update applicant age handling

- Gemfile
- Gemfile.lock
- db/migrate/20180807211758_create_legal_aid_applications.rb
- db/migrate/20180820112730_create_applicant.rb
- db/migrate/20180829144026_create_proceeding_types.rb
- db/migrate/20180829150801_create_legal_aid_application_proceeding_types.rb
- db/migrate/20181011143410_create_addresses.rb
- db/migrate/20181018165405_id_to_uuid_fk.rb
- db/migrate/20181018165537_uuid_migration.rb
This is a follow up/replacement for #5727 
The [webdack_uuid-migration gem](https://github.com/kreatio-sw/webdack-uuid_migration) was used 5 years ago to change tables and has only been referenced in migration files, not actively used, since.
This version (as opposed to the original!) removes the gem and modifies the migration files affected.
It adds `id: :uuid` to the affected tables and removes the contents of the webdack migrations
* A new user will be able to spin up a local database using `rails db:migrate`
* removes a little used gem and reduces our lock file and dependabot updates
* reduces our dependency attack surface
* should we be amending old migrations?  It won't affect production as the tables already exist
How do people feel about older migrations being modified?
The …
> FIX: remove webdack gem

- app/forms/providers/means/capital_disregards/add_details_form.rb
- config/locales/en/activemodel.yml
- spec/forms/providers/means/capital_disregards/add_details_form_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-5526)
Add validation on add details page. If backdated benefits content says a date should be over 24 months ago, enforce it with validation. If backdated benefits content says a date should be within the last 24 months, enforce it with validation.
Add error messages and update specs to reflect changes.
- The [development standards](https://dsdmoj.atlassian.net/wiki/spaces/ATPPB/pages/5503385837/Development+standards) and [Git Workflow](https://dsdmoj.atlassian.net/wiki/spaces/ATPPB/pages/4602855954/Git+Workflow) documentation on Confluence …
> AP-5526: Update validation on capital disregards add details page

- .github/dependabot.yml
* v3 of trying to get the ministry of justice frontend package split or ignored
* remove the ignore block from bundler - it was needed before we updated rails …
> Chore: Update dependabot instructions

- app/models/vehicle.rb
- app/services/flow/steps/provider_capital/own_homes_step.rb
- app/views/providers/means/add_other_vehicles/show.html.erb
- config/locales/en/providers.yml
- features/step_definitions/employment_setup_steps.rb
- spec/factories/legal_aid_applications.rb
- spec/models/vehicle_spec.rb
- spec/requests/providers/means/add_other_vehicles_controller_spec.rb
- spec/services/flow/steps/provider_capital/own_homes_step_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-5789)
We have seen a few occurrences of providers getting stuck on CFE submission because partially complete vehicles were being submitted.
On the last incident, we tracked the logs and the user started a new vehicle and hit save as draft.  the next log shows them restarting from the capital introductions page.  It's not clear if this was a glitch or if they used the browser back button.
This PR takes a couple of steps to mitigate this...
It updates the add another vehicle page to show that a record is incomplete
It also re-routes the page so that if the provider has said yes to vehicle, they will not see the yes/no question on a second pass through, they will see the above page with an incomplete record warning
I discussed validating …
> AP-5789: Prevent phantom vehicle submissions

- app/controllers/providers/proceeding_merits_task/prohibited_steps_controller.rb
- app/forms/providers/proceeding_merits_task/prohibited_steps_form.rb
- app/models/proceeding_merits_task/prohibited_steps.rb
- app/views/providers/proceeding_merits_task/prohibited_steps/show.html.erb
- config/locales/en/activemodel.yml
- config/locales/en/providers.yml
- spec/forms/providers/proceeding_merits_task/prohibited_steps_form_spec.rb
- spec/requests/providers/proceeding_merits_task/prohibited_steps_controller_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-5651)
Remove change of name checkbox from question as it is already asked earlier in the application. Remove associated translation values and specs. Remove padding class as it is not being used correctly, so was having no effect and it doesn't seem necessary.
Ignore `confirmed_not_change_of_name` column that will be removed in another PR
- The [development standards](https://dsdmoj.atlassian.net/wiki/spaces/ATPPB/pages/5503385837/Development+standards) and [Git Workflow](https://dsdmoj.atlassian.net/wiki/spaces/ATPPB/pages/4602855954/Git+Workflow …
> AP-5651: Remove change of name checkbox

- .github/dependabot.yml
Add quotes around the NPM ignore package name to try and remove parse issue …
> Chore: Update npm ignore block with quotes

- db/migrate/20250312140551_remove_confirmed_not_change_of_name_from_prohibited_steps.rb
- db/schema.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-5651)
Remove `confirmed_not_change_of_name` column. It is not being displayed anywhere and is just providing validation so there seems to be no issue with removing it
- The PR …
> AP-5651: Part 2 - remove change of name column

- app/models/proceeding_merits_task/prohibited_steps.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-5651)
Remove ignore column as column has now been removed …
> AP-5651: Part 3 - Tidy up

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/providers/search_results.scss
- package.json
This addresses the sass warning within our control, `mix` -> `color.mix`
It also addresses the warnings about future breaking changes by ignoring more govuk and Dart deprecation warnings
Pro: 
* quieter yarn builds
Con:
* risk of future updates taking us by surprise because we've been ignoring the warnings! …
> Fix: Sass css compilation deprecation warnings

- app/controllers/admin/settings_controller.rb
- app/forms/proceedings/substantive_defaults_form.rb
- app/forms/settings/setting_form.rb
- app/models/legal_aid_application.rb
- app/models/proceeding.rb
- app/models/setting.rb
- app/services/ccms/attribute_value_generator.rb
- app/services/flow/proceeding_loop.rb
- app/services/flow/steps/provider_proceeding_loop/substantive_defaults_step.rb
- app/services/legal_framework/proceeding_types/all.rb
- app/views/admin/settings/show.html.erb
- app/views/providers/has_national_insurance_numbers/show.html.erb
- app/views/providers/proceeding_loop/delegated_functions/show.html.erb
- app/views/providers/proceeding_loop/substantive_defaults/show.html.erb
- app/views/providers/start/index.html.erb
- app/views/shared/check_answers/_proceeding_details.html.erb
- app/views/shared/check_answers/merits/_merits_proceeding_section.html.erb
- config/locales/en/admin.yml
- config/locales/en/providers.yml
- db/migrate/20250313140248_remove_sca_from_settings.rb
- db/schema.rb
- features/providers/special_children_act/secure_accomodation_order_cit.feature
- features/providers/start_page.feature
- spec/models/setting_spec.rb
- spec/requests/admin/settings_controller_spec.rb
- spec/services/legal_framework/proceeding_types/all_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-5239)
- Remove all references to SCA feature flag as it is now on by default
- Rename everything from special_childrens_act to special_children_act, to keep codebase consistent and to match the name of the act
- Update view on start page to use list component from govuk components library …
> AP-5239: Remove SCA feature flag

- app/workers/bank_holiday_update_worker.rb
- spec/workers/bank_holiday_update_worker_spec.rb
Reduce the BankHolidayUpdateWorker update interval from every 2 days to once a month.
Having an update interval in days seemed wasteful.
This also removes the `UPDATE_INTERVAL` constant as it is used once in this worker and once in spec. …
> Reduce BankHolidayUpdateWorker update interval

- app/views/providers/start/index.html.erb
- config/locales/en/providers.yml
- spec/requests/providers/start_spec.rb
Add PLF to the list of matter types if the flag is active …
> Update: Landing page list for PLF

- app/views/providers/merits_reports/_applied_previously.html.erb
- app/views/providers/merits_reports/_delegated_functions.html.erb
- app/views/providers/merits_reports/_proceeding_details.html.erb
- app/views/shared/check_answers/_emergency_costs.html.erb
- app/views/shared/check_answers/_substantive_costs.html.erb
- app/views/shared/check_answers/merits/_separate_representation.html.erb
Make merits report summary card column widths one-third/two-thirds
Inline with means report, CYA and R&P pages. Agreed with devs
- You should …
> Chore: make merits report summary card column widths one-third/two-thirds

- app/views/shared/check_answers/_assets.html.erb
AP-5432: Fix incorrect closing h tag
[Link to story](https://dsdmoj.atlassian.net/browse/AP-5432)
Typo/Missed in [previous PR](https://github.com/ministryofjustice/laa-apply-for-legal-aid/pull/7660) 
- The PR description should say …
> AP-5432: Fix incorrect closing h tag

- app/models/vehicle.rb
- app/services/cfe_civil/components/vehicles.rb
- app/services/reports/mis/application_detail_csv_line.rb
- spec/factories/vehicles.rb
- spec/models/vehicle_spec.rb
- spec/services/ccms/requestors/case_add_requestor_spec.rb
- spec/services/ccms/requestors/case_add_requestor_xml_blocks/non_passported_variable_attributes_spec.rb
- spec/services/ccms/requestors/special_children_act_case_add_requestor_spec.rb
- spec/services/cfe_civil/components/partner_spec.rb
- spec/services/cfe_civil/components/vehicles_spec.rb
- spec/services/cfe_civil/submission_builder_spec.rb
- spec/services/reports/mis/application_detail_csv_line_spec.rb
We migrated from purchase date to boolean, more than three years old, question in Feb 2020
Production has zero vehicles of (5K+ stored) with a purchased_on date
Therefore we should remove the column and stop interpolating a fake date _if_ it is empty
This removes, and renames, the helper methods to be clearer and updates the factories to remove the obsolete column
It also updates the reporting and test usages to use the new handling
- The [development standards](https://dsdmoj.atlassian.net/wiki/spaces/ATPPB/pages/5503385837/Development+standards) and [Git …
> Update:  Vehicle model and factory bot handling

- app/models/vehicle.rb
- db/migrate/20250325114131_remove_purchased_on_from_vehicle.rb
- db/schema.rb
Tidy up vehicle.purchased_on
* Remove the database column
* Remove the ignored_column from the model …
> Chore: Vehicle tidyup

- app/controllers/concerns/providers/delete_attachments.rb
- app/controllers/providers/application_merits_task/court_order_copies_controller.rb
- app/controllers/providers/proceeding_merits_task/child_care_assessments_controller.rb
- app/views/providers/application_merits_task/court_order_copies/show.html.erb
- app/views/providers/proceeding_merits_task/child_care_assessments/show.html.erb
- config/locales/en/generic.yml
- config/locales/en/providers.yml
- spec/factories/attachments.rb
- spec/factories/legal_aid_applications.rb
- spec/requests/providers/application_merits_task/court_order_copies_controller_spec.rb
- spec/requests/providers/proceeding_merits_task/child_care_assessments_controller_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-5775)
Delete evidence if user changes their answer to the question that determines if evidence is needed. Add notification banner to warn them that their attachment will be deleted. Add tests to cover functionality …
> AP-5775: Changing merits answers that require evidence - not handled

- app/controllers/errors_controller.rb
- app/controllers/providers/check_benefits_controller.rb
- app/views/errors/show/_benefit_checker_down.html.erb
- config/locales/cy/errors.yml
- config/locales/en/errors.yml
- spec/requests/errors_controller_spec.rb
- spec/requests/providers/check_benefits_controller_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-5881)
Update the check_benefits controller to change the redirect from the generic, problem, page to the specific,
benefit_checker_down, error page
The new error page will output a 500 error so it should still trigger alerts in prometheus/open search/sentry …
> AP-5881: update benefit check error handling

- helm_deploy/apply-for-legal-aid/values-staging.yaml
Test the upgraded nginx modsec controller on non-prod environments
To mitigate problems on 15/04/2025 when they switch over to it on all production environments
From Cloud-platform:
```txt
We have deployed a non-prod modsec ingress controller to the cluster with the latest nginx and modsec rules (and upped the PCRE limit to tackle some of the errors you might have experienced with the recent failed upgrade).
You can test your existing ingress controller workloads by moving over your non prod workloads to the new non prod modsec controller and checking for any issues before the 15th. Please let us know what issues you hit asap.
To move your workloads over you just need to update your ingress className  from modsec => modsec-non-prod.
````
- Tests …
> Test: turn on modsec-non-prod for staging

- app/controllers/admin/reports_controller.rb
- app/views/admin/reports/index.html.erb
- config/routes.rb
- spec/requests/admin/reports_controller_spec.rb
[Add ApplicationDigest CSV to admin reports](https://dsdmoj.atlassian.net/browse/AP-5877) …
> AP-5877: Add ApplicationDigest csv to admin report

- .github/dependabot.yml
- app/assets/stylesheets/_imports.scss
- app/assets/stylesheets/admin.scss
- app/assets/stylesheets/application.scss
- app/assets/stylesheets/check-your-answers.scss
- app/assets/stylesheets/dropzone.scss
- app/assets/stylesheets/helpers.scss
- app/assets/stylesheets/language-switcher.scss
- app/assets/stylesheets/layout.scss
- app/assets/stylesheets/pagination.scss
- app/assets/stylesheets/providers/legal_aid_applications.scss
- app/assets/stylesheets/providers/search_results.scss
- app/assets/stylesheets/sort-transactions.scss
- app/assets/stylesheets/table-sort.scss
- app/assets/stylesheets/tables.scss
- app/javascript/application.js
- package.json
- yarn.lock
This PR updates the npm packages to:
* update `@ministryofjustice/frontend`
* add `moment` and `bare` to reduce warnings and noise on build
It then updates the scss files to import the external files using the new sass methods, `@use` and `@forward`
- should we add the additional packages?  They reduce warnings, but significantly increase package dependancies
- The [development standards](https://dsdmoj.atlassian.net/wiki/spaces/ATPPB/pages/5503385837/Development+standards) and [Git Workflow](https://dsdmoj.atlassian.net/wiki/spaces/ATPPB/pages/4602855954/Git+Workflow) documentation on Confluence …
> AP-5914: Update MOJ Frontend npm package

- helm_deploy/apply-for-legal-aid/templates/cronjob-admin-report.yaml
- helm_deploy/apply-for-legal-aid/templates/cronjob-deliver-scheduled-mail.yaml
- helm_deploy/apply-for-legal-aid/templates/cronjob-destroy-purgeable.yaml
- helm_deploy/apply-for-legal-aid/templates/cronjob-export-digest.yaml
- helm_deploy/apply-for-legal-aid/templates/cronjob-extract-digest.yaml
- helm_deploy/apply-for-legal-aid/templates/cronjob-mark-purgeable.yaml
- helm_deploy/apply-for-legal-aid/templates/cronjob-metrics.yaml
Add timezone to each scheduled cronjob so that daylight saving time is respected …
> Chore: add timezone to each scheduled cronjob

- app/views/shared/forms/_error_summary_hidden.html.erb
- spec/requests/providers/application_merits_task/statement_of_case_spec.rb
Remove unneeded html id and refactor specs
[Came out of looking at bug](https://dsdmoj.atlassian.net/browse/AP-5073) …
> Tidy: remove unneeded html ID and refactor specs

- helm_deploy/apply-for-legal-aid/values-uat.yaml
Change UAT ingress to default-non-prod
Following recommendations from CP.
see https://user-guide.cloud-platform.service.justice.gov.uk/documentation/other-topics/does-my-app-need-ingress.html#does-my-app-need-an-ingress
- The PR …
> Chore: Change UAT ingress to default-non-prod

- app/controllers/providers/application_merits_task/court_order_copies_controller.rb
- app/forms/providers/application_merits_task/plf_court_order_form.rb
- app/services/flow/steps/provider_merits/child_care_assessment_result_step.rb
- app/services/flow/steps/provider_merits/court_order_copies_step.rb
- features/providers/check_merits_answers.feature
- features/providers/public_law_family/merits_child_care_assessment_question_flow.feature
- features/support/steps_helper.rb
- spec/forms/providers/application_merits_task/plf_court_order_form_spec.rb
- spec/requests/providers/application_merits_task/court_order_copies_controller_spec.rb
- spec/services/flow/steps/provider_merits/child_care_assessment_result_step_spec.rb
- spec/services/flow/steps/provider_merits/court_order_copies_step_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-5776)
Having come from the Checking Merits Answers page, redirect to supporting evidence page when the `copy of court order` answer is changed from `No` to `Yes` so the provider can upload the court order. 
Same for the `child_care_assessment` page and question. …
> AP-5776 Fix bypassing evidence validation bug

- app/forms/concerns/date_field_builder.rb
- spec/forms/partners/details_form_spec.rb
- spec/forms/proceedings/final_hearing_form_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-5646)
This was written a long time ago, when only date of birth was entered
We now have multiple date inputs that require future dates to be entered, e.g. hearing dates in the future, and this handler would reset a future date to be 19xx.
This update only applies a rollback on dates when the requested field is a date of birth entry. For all others it will roll forward
- The [development standards](https://dsdmoj.atlassian.net/wiki/spaces/ATPPB/pages/5503385837/Development+standards) and [Git …
> AP-5646: Update two year digit handling

- app/forms/base_employed_form.rb
- app/views/shared/_employment_status.html.erb
- features/providers/applicant_details.feature
- features/providers/employment_status.feature
- features/step_definitions/civil_journey_steps.rb
- features/step_definitions/generic_steps.rb
- spec/forms/applicants/employed_form_spec.rb
- spec/forms/partners/employed_form_spec.rb
Fix employment status form to show already checked items
[Link to story](https://dsdmoj.atlassian.net/browse/AP-5955)
So the checkboxes are checked or not when page returned to. …
> AP-5955: Fix employment status form

- app/controllers/providers/capital_assessment_results_controller.rb
- app/controllers/providers/capital_income_assessment_results_controller.rb
- app/controllers/providers/means_assessment_results_controller.rb
- spec/helpers/liquid_capital_items_helper_spec.rb
- spec/requests/providers/capital_assessment_results_controller_spec.rb
- spec/requests/providers/capital_income_assessment_results_controller_spec.rb
Refactor assessment result controllers and more
[Came out of story](https://dsdmoj.atlassian.net/browse/AP-5828)
Two controllers that are identical. One for assessment
results for passported one for non-passported.
Can also potentially rename the child controllers, steps
and perhaps look at the views to remove repetition. …
> Tidy: Refactor assessment results controllers

- .github/dependabot.yml
- package.json
- yarn.lock
This updates the MOJ frontend package to the latest version and removes the dependabot ignore
I checked the release notes [here](https://github.com/ministryofjustice/moj-frontend/releases/tag/v5.1.0) and found no breaking changes but **a second pair of eyes may be useful**!
We have always imported _all_ JS from the frontend.  We could reduce our JS footprint by only importing the required components but that should probably be a discussion
- The [development standards](https://dsdmoj.atlassian.net/wiki/spaces/ATPPB/pages/5503385837/Development+standards) and [Git …
> Chore: Update MOJ frontend package

- .github/dependabot.yml
Warning issued by circleci:
```
The reviewers field in the dependabot.yml file will be removed soon. Please use the code owners file to specify reviewers for Dependabot PRs. For more information, see this blog post.
````
see https://github.blog/changelog/2025-04-29-dependabot-reviewers-configuration-option-being-replaced-by-code-owners/
Note that we already have CODEOWNERS file pointing to the same team user
- The [development standards](https://dsdmoj.atlassian.net/wiki/spaces/ATPPB/pages/5503385837/Development …
> Chore: Remove dependabot reviewers config

- app/controllers/admin/settings_controller.rb
- app/forms/settings/setting_form.rb
- app/models/setting.rb
- app/services/legal_framework/proceeding_types/all.rb
- app/views/admin/settings/show.html.erb
- app/views/providers/start/index.html.erb
- config/locales/en/admin.yml
- config/locales/en/providers.yml
- features/cassettes/Loop_through_proceeding_questions/No_preselected_emergency_or_substantive_levels_of_service.yml
- features/cassettes/Loop_through_proceeding_questions/When_provider_accepts_default_levels_of_service.yml
- features/cassettes/Loop_through_proceeding_questions/When_provider_does_not_accept_default_levels_of_service.yml
- features/cassettes/Scope_limitations_not_being_set/When_a_provider_creates_an_application_with_multiple_proceedings_and_uses_the_back_button_scope_limitations_should_not_be_removed.yml
- features/providers/cost_override.feature
- features/providers/proceeding_loop.feature
- features/providers/regressions/back_button_on_proceedings.feature
- features/providers/special_children_act/secure_accomodation_order_cit.feature
- features/providers/start_page.feature
- features/step_definitions/civil_journey_steps.rb
- spec/models/setting_spec.rb
- spec/requests/admin/settings_controller_spec.rb
- spec/requests/providers/start_spec.rb
- spec/services/legal_framework/proceeding_types/all_spec.rb
Remove all references to public_law_family feature flag
[Link to story](https://dsdmoj.atlassian.net/browse/AP-5324)
It has been signed off by product to remove this feature flag
following a period of monitoring.
First of two parts. the second will drop the settings.public_law_family column. …
> AP-5324: Remove public_law_family feature flag

- features/providers/regressions/scope_limitations.feature
This started failing today but was fine yesterday. 
The cause seems to be sequencing... a recent update re-recorded the VCR cassette expecting the first radio button in the SE003 results to be the enforcement option.  
The first option, today, is the appeal option.  
I have changed the radio button select to the explicit `Prohibited steps order - enforcement` option so that the VCR condition will always be met
- The [development standards](https://dsdmoj.atlassian.net/wiki/spaces/ATPPB/pages/5503385837/Development+standards) and [Git Workflow](https://dsdmoj.atlassian.net/wiki/spaces/ATPPB/pages/46028 …
> Fix: Broken feature test

- app/views/shared/check_answers/merits/_merits_proceeding_section.html.erb
- features/step_definitions/civil_journey_steps.rb
- spec/requests/providers/check_merits_answers_controller_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-5959)
Involved children for proceeding were not being shown so add them back into cya page …
> AP-5959: Add involved children back into merits cya

- app/helpers/page_template_helper.rb
- app/views/layouts/_flash.html.erb
- app/views/layouts/application.html.erb
- app/views/providers/legal_aid_applications/index.html.erb
- app/views/shared/page_templates/_basic_page_template.html.erb
- app/views/shared/page_templates/_default_page_template.html.erb
- spec/requests/providers/bank_transactions_controller_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-6008)
Move flash partial into template partials, so that it is inside the div which determines the column width. This means that the flash messages will match the width of page content, which is specified in the govuk design system. …
> AP-6008: Notification banner full width on applications page

- helm_deploy/apply-for-legal-aid/templates/cronjob-alert-ccms-submissions.yaml
- helm_deploy/apply-for-legal-aid/templates/cronjob-deliver-scheduled-mail.yaml
- helm_deploy/apply-for-legal-aid/templates/cronjob-turn-off-ccms-submissions.yaml
- helm_deploy/apply-for-legal-aid/templates/cronjob-turn-on-ccms-submissions.yaml
Incident: Suspend cronjobs
To prevent unnecessary enabling and disabling of CCMS submission and
prevent scheduled mail going out.
- You should …
> Incident: Suspend cronjobs

- features/cassettes/Scope_limitations_not_being_set/When_a_provider_creates_an_application_with_multiple_proceedings_and_uses_the_back_button_scope_limitations_should_not_be_removed.yml
- features/providers/regressions/scope_limitations.feature
- spec/helpers/transaction_type_helper_spec.rb
Couple of flaky tests need fixing
The feature test flakiness is caused by an ordering issues on 
proceedings, resulting from use a less than specific search term.
The helper specs use of `eq` makes the tests order dependant, possibly 
unnecesarily - to check with Adam. …
> Fix: fix flaky tests

- .circleci/config.yml
Chore: Revert to using underscore step names
[Came out of story](https://dsdmoj.atlassian.net/browse/AP-6023)
For consistency, despite myself preferring hyphenated-keys.
NOTE: This qill require removing and then readding the deploy-uat step
as required from github branch protection. Re add `deploy_uat` as required
once merged.
- There should …
> Chore: Revert to using underscore step names

- bin/deploy
- helm_deploy/apply-for-legal-aid/templates/_helpers.tpl
Move whitelist IP to deploy script
This centralises them in one location and simplifies the
helm templates. The IPs may change but would be a small change to apply in any event …
> Chore: Move whitelist IPs to deploy script

- app/views/providers/has_national_insurance_numbers/show.html.erb
Add extra letter spacing to national insurance number text input as in the design system …
> Chore: add nino extra letter spacing

- app/controllers/concerns/grover_optionable.rb
- app/controllers/providers/means_reports_controller.rb
- app/controllers/providers/merits_reports_controller.rb
- app/services/reports/base_report_creator.rb
- spec/requests/providers/means_reports_controller_spec.rb
- spec/requests/providers/merits_reports_controller_spec.rb
Inline styles for PDF generation
To avoid whitelisting issues. Taken from [this PR](ministryofjustice/laa-submit-crime-forms#1526)
This should be in a shared/central location but putting it in the
grover intializer fails tests with error below so adding it to call
instead.
```sh
Errno::ENOENT: No such file or directory @ rb_sysopen - /home/circleci/project/app/assets/builds/application.css (Errno::ENOENT)
```
- The [development standards](https://dsdmoj.atlassian.net/wiki/spaces/ATPPB/pages/5503385837/Development+standards) and [Git Workflow](https://dsdmoj.atlassian.net/wiki/spaces/ATPPB/pages/460285 …
> Fix: Inline styles for PDF generation

- helm_deploy/apply-for-legal-aid/templates/deployment_clamav.yaml
Remove duplicate k8s attribute
typo fix …
> Fix: remove duplicate k8s attribute

- features/providers/proceeding_loop.feature
Once again, the sequence of LFA returns seems to have shifted
Where yesterday, `Child arrangements order (CAO) - residence - appeal` would have selected the vary option, today it does not :(
This makes the text selection explicit, the recorded VCR cassette expected `SE016A` to have been chosen, and now the text selector matches it precisely
- …
> Fix: Flickering feature

- app/forms/providers/regular_transaction_form.rb
- app/helpers/transaction_type_helper.rb
- app/models/base_aggregated_cash_transaction.rb
- app/views/shared/check_answers/_benefits_income.html.erb
- app/views/shared/check_answers/_housing_benefit.html.erb
- features/providers/bank_statement_upload/check_your_means_answers.feature
- features/providers/check_your_answers.feature
- features/providers/partner_means_assessment/bank_statement_upload/check_your_means_answers.feature
- features/providers/regressions/client_truelayer_partner_bank_statements_check_means_answer.feature
- spec/helpers/transaction_type_helper_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-5519)
Use the CurrencyCleaner class in the forms and handlers that had a different solution used.  This ensures the same substitutions are used in all forms and a consistent return is provided by the system.
This is, possibly, a short term solution as we are using many different ways of validating, storing and displaying currency values between different forms and handlers
This PR also fixes the display of currency amounts on the Check your Answers pages, to display without trailing zeros i.e. `£45` instead of `£45.00`. Amounts with pence still display as `£45.01`.
- Github should not be reporting conflicts; you should have recently run …
> AP-5519: Ensure consistent currency validation

- spec/requests/admin/legal_aid_applications_controller_spec.rb
- spec/requests/admin/submitted_applications_reports_controller_spec.rb
Fix othere tests impacted by system test capybara changes
[Link to story](https://dsdmoj.atlassian.net/browse/AP-6089)
The introduction of system tests has made of capybara matchers
different but only for system tests. However if they load before
another test that requests more basic capybnara matchers for requests
it can break.
- There should …
> AP-6089: These test also need updating to avoid flicker errors

- features/providers/review_and_print.feature
This step name was renamed in June but this usage was missed.  
This PR restores full feature test running …
> Chore: Fix feature test

- .circleci/config.yml
- README.md
The CodeClimate quality checks were deprecated over the weekend, this PR removes the circle ci test report setup and removes the badges from the Readme
It turns out that the data wasn't being pushed to CC on this repo anyway!
- The …
> Chore: Remove CodeClimate from repo

- app/controllers/providers/omniauth_callbacks_controller.rb
- app/helpers/application_helper.rb
- app/views/providers/start/index.html.erb
- config/routes.rb
- spec/support/shared_examples/provider_auth_shared_examples.rb
This is normally provided by devise but we are only using :trackable so some routes are not handled silently …
> AP-6125: Add explicit provider/sign_in route

- spec/models/aggregated_cash_outgoings_spec.rb
These were hard coded with the dates during the month written
As the month clicked over today, they started to break.
This reuses an error_msg method by extracting to the top level so all tests can use it. …
> Fix: Hardcoded test dates

- app/helpers/application_helper.rb
- app/views/providers/providers/show.html.erb
- config/locales/en/layouts.yml
- spec/helpers/application_helper_spec.rb
- spec/requests/providers/providers_controller_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-6125)
Agreed with design, show static text for "My profile" in header when signed in and remove the username/guid field from the profile page
The heading text will be reviewed once the service is live and we can confirm that the data for first/last name is consistently filled in by provider admins when creating accounts
- The [development standards](https://dsdmoj.atlassian.net/wiki/spaces/ATPPB/pages/5503385837/Development+standards) and [Git Workflow](https://dsdmoj.atlassian.net/wiki/spaces/ATPPB/pages/4602855954/Git+Workflow) documentation on …
> AP-6125: Update my profile

- bin/deploy
fix bad merge conflict resolution that results in broken deployment …
> Fix: Remove unneeded vars from deploy

- .env.sample
- app/views/providers/invalid_schedules/show.html.erb
- config/application.rb
- config/locales/en/providers.yml
- helm_deploy/apply-for-legal-aid/values-uat.yaml
- spec/requests/providers/invalid_schedules_spec.rb
Correct invalid schedules interrupt content and styling
[Link to story](https://dsdmoj.atlassian.net/browse/AP-6146)
- add correct links (confirmed by designer)
- add white/reverse links …
> Correct invalid schedules interrupt content and styling

- app/views/providers/has_other_proceedings/show.html.erb
- app/views/providers/proceedings_types/index.html.erb
- config/locales/en/providers.yml
[Link to story](https://dsdmoj.atlassian.net/browse/AP-6141)
Make changes as per designs:
- add details component to proceedings_types page
- add link to has_other_proceedings page from proceedings_types page
- change inset text to paragraph text …
> AP-6141: Make changes to proceedings search pages

- .circleci/config.yml
Add auto rerun to merge of PR CI/CD
Flickers in the test suite should be retried automatically. Having
redeployment failures retry should be ok to.
As agreed by devs. …
> Chore: Add autorerun to merge of PR CI/CD

- .simplecov
- app/controllers/concerns/providers/appointable.rb
- app/controllers/providers/invalid_schedules_controller.rb
- app/controllers/providers/provider_base_controller.rb
- app/controllers/providers/select_offices_controller.rb
- app/helpers/home_path_helper.rb
- app/models/provider.rb
- features/providers/selecting_office.feature
- features/step_definitions/civil_journey_steps.rb
- features/step_definitions/sign_in_steps.rb
- spec/factories/providers.rb
- spec/helpers/home_path_helper_spec.rb
- spec/models/provider_spec.rb
- spec/requests/providers/confirm_offices_spec.rb
- spec/requests/providers/invalid_schedules_spec.rb
- spec/requests/providers/select_offices_spec.rb
- spec/services/pda/mock_provider_details_updater_spec.rb
- spec/services/pda/provider_details_updater_spec.rb
Ensure office selection before provider access
[Link to story](https://dsdmoj.atlassian.net/browse/AP-6202)
This borrows from devise logic to prevent navigation to any provider page without having selected
an office for that provider, barring 3 exceptions*1.
This is important because, for new logins in particular, if a provider has no office then any applications they create will not have an office and will not be injectable into CCMS as a result.
Current logic signs users out "just in case" if they select an office without the correct schedules/contract-details. However, there was a clickable journey via the profile page that allowed circumnavigation of current logic which has been corrected separately by preventing the banner link going to the in progress app list _[this may need …
> AP-6202: Ensure office selection before provider access

- config/locales/en/layouts.yml
- features/citizens/citizens.feature
- features/providers/selecting_office.feature
- features/providers/sign_in.feature
- features/step_definitions/generic_steps.rb
- spec/helpers/application_helper_spec.rb
- spec/system/mock_auth/sign_in_spec.rb
Rename "Sign In" to "Sign in"
For consistency and adherence to govuk conventions.
- …
> Chore: Rename "Sign In" to "Sign in"

- .github/dependabot.yml
There's an issue with updating view components and govuk components so these have been separated into their own dependabot group
- You should …
> Chore: separate components into own dependabot group

- .github/dependabot.yml
Ignore npm based updates
[Link to story](https://dsdmoj.atlassian.net/browse/AP-6260)
Due to on-going supply chain attack on npm, termed shai-hulud. …
> AP-6260: Ignore npm based updates

- config/locales/en/providers.yml
- spec/requests/providers/proceedings_sca/interrupts_controller_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-6252)
Updated content on sca interrupt pages. …
> ap-6252: update content on sca interrupt pages

- app/controllers/providers/application_merits_task/when_contact_was_made_controller.rb
- app/forms/incidents/when_contact_was_made_form.rb
- app/services/flow/flows/provider_merits.rb
- app/services/flow/merits_loop.rb
- app/services/flow/steps/provider_merits/when_contact_was_made_step.rb
- app/views/providers/application_merits_task/when_contact_was_made/show.html.erb
- app/views/shared/check_answers/_merits.html.erb
- app/views/shared/check_answers/merits/_latest_incident_details.html.erb
- config/locales/en/activemodel.yml
- config/locales/en/providers.yml
- config/locales/en/shared.yml
- config/routes.rb
- db/migrate/20250929104707_add_first_contact_date_to_incidents.rb
- db/schema.rb
- features/providers/public_law_family/merits_appeal_question_flow.feature
- features/providers/public_law_family/merits_child_care_assessment_question_flow.feature
- spec/factories/incidents.rb
- spec/factories/legal_framework_serialized_merits_task_list.rb
- spec/forms/incidents/when_contact_was_made_form_spec.rb
- spec/requests/providers/application_merits_task/when_contact_was_made_controller_spec.rb
- spec/services/flow/steps/provider_merits/when_contact_was_made_step_spec.rb
[Link to story](https://dsdmoj.atlassian.net/browse/AP-5620)
Add a new page 'When client made contact' which will be shown as the first page in the merits task list (at an application level) for all proceeding types except for DA and SCA (so currently for S8 and PLF).
In the case of a combined DA and S8 application, the old latest incident details page should still be shown, not the new page.  
> [!CAUTION]
> Do not merge until the commit to point at a specific LFA branch is removed
- The [development standards](https://dsdmoj.atlassian.net/wiki/spaces/ATPPB/pages/5503385837/Development+standards) …
> Ap 5620 Add 'When contact was made' question to merits 
